### PR TITLE
[CI:DOCS] Bump to v4.0.3

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
Also damn, realizing now I should have `[CI:DOCS]`'d this

**Comment by mheon** [comment]
Green

**Comment by mheon** [comment]
@Luap99 @baude @rhatdan PTAL

**Review by Luap99 — COMMENTED** [review]
LGTM

**Pull request merged**
