### PR TITLE
[CI:DOCS] Update release notes for v2.0.4

### PR DESCRIPTION
**Pull request by mheon**
As the title says.

### CODE REVIEW

**Comment by mheon** [comment]
@TomSweeneyRedHat @vrothberg @rhatdan @giuseppe @ashley-cui PTAL

**Comment by mheon** [comment]
Oh, periods. Let me add those.

**Comment by mheon** [comment]
@TomSweeneyRedHat Added periods, please LGTM

**Comment by mheon** [comment]
Anyone want to merge?

**Comment by TomSweeneyRedHat** [comment]
I missed @ashley-cui 's LGTM, here goes!
/lgtm

**Pull request merged**
