### PR TITLE
Makefile: do not hardcode `GOOS` in `podman-remote-static` target

### PR DESCRIPTION
**Pull request by xduugu**
Follow-up of https://github.com/containers/podman/pull/22060#issuecomment-2009960603

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM
@containers/podman-maintainers PTAL
Thanks @xduugu

**Comment by mheon** [comment]
@cevich PTAL

**Comment by baude** [comment]
please use an actual commit message on why we need to do this.

**Comment by cevich** [comment]
Yes, please write up a complete commit message and PR description.  Though I'm glad to see CI passing with this, I don't recall off-hand if any CI builds exercise any of the affected targets.  I can double-check once the commit message is ready.

**Comment by cevich** [comment]
Thanks for the archaeology and confirming Ed.  Though IIRC, Windows builds are in a weird CI situation, where we test the installer using a cross-compiled binary but the official release builds come from the `winmake` powershell script.  The later I don't believe runs a build anywhere in CI.

**Comment by xduugu** [comment]
@baude What do you have in mind? It actually never was required to restrict the OS in `podman-remote-static`. I just did not remove it when I added the target in #22060, so should I just write this into the commit message?

@edsantiago The `podman-remote-static` target in #14444 is not the same as the one that I added in #22060. The CI most likely uses the `release-artifacts` target which again calls `make podman-remote-static-linux_amd64` and `make podman-remote-static-linux_arm64` to generate the binaries.

The history is:

- #14444 sets `GOOS` to `linux`
- #16667 renames `podman-remote-static` target to `podman-remote-static-linux_amd64` and adds `podman-remote-static-linux_arm64`
- #18238 adds target `release-artifacts` which uses `podman-remote-static-linux_amd64` and `podman-remote-static-linux_arm64`
- #22060 adds a new target `podman-remote-static` which is also used by `podman-remote-static-linux_amd64` and `podman-remote-static-linux_arm64`

**Comment by TomSweeneyRedHat** [comment]
@cevich @edsantiago @baude thoughts on what to do with this one?

**Comment by cevich** [comment]
Oh sorry I completely forgot about this.  IIRC this gives us the option to produce static podman-remote binaries, have I got that right?  I *think* this change is syntactically correct, if somebody else could confirm we're actually touching the `$(SRCBINDIR)/podman-remote-static-linux_%` target in CI somewhere.  If so then this LGTM.

**Pull request merged**
