### PR TITLE
Upgrade go-criu to v6

### PR DESCRIPTION
**Pull request by snprajwal**
The v6.0.0 release of go-criu has deprecated the `rpc` and `stats`
packages in favour of the `crit` package. This commit provides the
changes required to use this version in podman.

Signed-off-by: Prajwal S N <prajwalnadig21@gmail.com>

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
Looks like you have build issues, but changes LGTM otherwise

**Comment by snprajwal** [comment]
> Looks like you have build issues, but changes LGTM otherwise

There's a namespace conflict between the proto files from another dependency. I'll get this repaired and working shortly.

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by snprajwal** [comment]
@mheon @TomSweeneyRedHat would it be possible to override the CI constraint for binary deltas over 51200B? The remaining tests are passing :)

**Review by rst0git — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
@baude @Luap99 Looks like ~1mb of growth. I'm OK with merging, but you both have stronger opinions on this than I do.

**Comment by Luap99** [comment]
Eh, why exactly do we need this? +1 MB for no new features?
It looks like the dependency structure for go-criu/v6 is bad. It pulls in way to much because of the stupid protobuf code generation, one of the reason we dropped the k8s dep.

**Comment by rhatdan** [comment]
Can we work around this issue. One of the things Automotive wants out of us is guarantees that we prevent the start up time of Podman from going up.  Each time it gets fatter, the total time of starting the podman command slows down. Automotive has a requirement to start container from boot in < 2 seconds.

**Comment by rst0git** [comment]
> why exactly do we need this? +1 MB for no new features?

In go-criu version 6.X we introduced support for image processing functionality ([`crit`](https://github.com/checkpoint-restore/go-criu/pull/66)) and we plan to extend the `podman inspect` command with support for checkpoint container images. This functionality also replaces the existing stats API and would also allow us to enable pre-copy migration container migration.

**Comment by snprajwal** [comment]
> Can you do something about the protobuf problem @Luap99 mentions?

Although we do not need all the bindings for the stats API, they will be required to extend `podman inspect` for checkpointed images.

**Comment by rst0git** [comment]
> Can you do something about the protobuf problem @Luap99 mentions?

We briefly discussed this problem in https://github.com/checkpoint-restore/go-criu/pull/95#discussion_r964597749, but so far this is the best solution we have.

**Comment by adrianreber** [comment]
I agree over 1MB increase of binary size for just moving code around does not sound right. It is not clear why the binary size increases so much as non of the imported protobuf files are actually used. We need to structure go-criu differently.

**Comment by snprajwal** [comment]
> It is not clear why the binary size increases so much as non of the imported protobuf files are actually used.

Since all Go programs are statically linked, the Go compiler includes the entire library, even if just a single function is being used (in this case, `crit/images`). On the other hand, if we add a bunch of new features that use the same libraries, the size increase will be in the order of a few bytes, since nothing needs to be included from the imports.

**Comment by rst0git** [comment]
@snprajwal Would you be able to update this pull request with go-criu version 6.3.0 (e.g., https://github.com/containers/podman/commit/a71a19e25a795eb13c60db470eb11c629f8fc2fa)?
This version should be backwards compatible with v5 and therefore the size of the Podman library shouldn't change.

**Comment by rst0git** [comment]
@Luap99 @mheon @rhatdan PTAL

**Review by Luap99 — APPROVED** [review]
LGTM, thanks for fixing this

**Pull request merged**
