### PR TITLE
[CI:DOCS] Add tables to podman-systemd.unit man page

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @TomSweeneyRedHat @ygalblum @alexlarsson What do you think about adding a table like this to the man page.  This helps me understand what the options are for.

**Comment by rhatdan** [comment]
Will add other sections once this format is approved.

**Comment by rhatdan** [comment]
@edsantiago PTAL

**Comment by ygalblum** [comment]
Makes sense to me

**Comment by edsantiago** [comment]
I love it! Thank you!

And of course that's exactly the sort of thing that I need to cross-reference, so I wrote a quick hack to do so:

>Found in .go but not in .md: ConfigMap Copy Device DisableDNS Driver Gateway IPAMDriver IPRange IPv6 Internal Options Subnet Options Type Yaml

Seems likely (IMO) that those omissions are intentional, so, LGTM.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
