### PR TITLE
e2e tests: use HaveKey() and HaveLen() when possible

### PR DESCRIPTION
**Pull request by edsantiago**
I learned about HaveKey() and HaveLen(). We should use them wherever possible.

This is another multi-part PR, in small reviewable chunks.

- e2e tests: a little more minor cleanup
- Same as previous, for assertions other than Equal()
- Use BeEmpty() instead of len(x).To(Equal(0))
- Same thing, for BeNumerically("==", 0)
- Use HaveLen(x) instead of Expect(len(y)).To(Equal(x))
- Same thing, with BeNumerically("==", x)
- Manual fixes

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once things go green.

**Comment by edsantiago** [comment]
I need help here. (I could figure it out myself, but it'll be faster and more reliable for me to ask). The error is:
```
         Expected
               <map[string]string | len:2>: {
                   "io.buildah.version": "1.23.1",
                   "marge": "mom",
               }
           to have {key: value}
               <map[interface {}]interface {} | len:1>: {
                   <string>"homer": <string>"",
               }
```
The cause is this diff:
```diff
-               Expect(inspectData[0].Config.Labels["homer"]).To(Equal(""))
+               Expect(inspectData[0].Config.Labels).To(HaveKeyWithValue("homer", ""))
```
My initial interpretation is: Go returns `""` (empty string) when looking up a nonexistent key in a map. Is that correct? If so, should the replacement assertion be `...To(Not(HaveKey("homer")))`?

**Comment by edsantiago** [comment]
Re-pushed on the assumption that my above comment is correct. Edit was to the first commit. I amended the commit message appropriately, to indicate manual muckery.

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
Your assumption is correct, Ed

/lgtm

**Pull request merged**
