### PR TITLE
[DO NOT MERGE] Test Packit

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

### CODE REVIEW

**Comment by lsm5** [comment]
hmm the packit process seems to add rpms and tarball to git, which seems undesirable at first glance. Gotta check further if that's helpful at all.

**Comment by lsm5** [comment]
blocked on https://github.com/packit/notifications/issues/355

**Comment by lsm5** [comment]
> blocked on [packit/notifications#355](https://github.com/packit/notifications/issues/355)

Entire containers org has been granted access now.

**Comment by csomh** [comment]
> hmm the packit process seems to add rpms and tarball to git, which seems undesirable at first glance. Gotta check further if that's helpful at all.

Hey @lsm5, I think this is b/c `packit init` was used with `--upstream-ref` or some other source-git specific option, in which case packit will try to set up a source-git repo, but I don't think this is your intention in this case.

Generally when setting up Packit to help you with testing a project in Fedora Linux, you would just run `packit init` in the repo root, without any options and add the spec-file. Please check out our [onboarding guide](https://packit.dev/docs/guide/) for more details, or let me know if there is anything else I could help with.

And sorry for the confusion, we definitely need to improve this part of the CLI so that it's less confusing.

**Comment by vrothberg** [comment]
Going through old PRs. Closing since it doesn't look needed anymore. Feel free to reopen if I am mistaken.

**Comment by lsm5** [comment]
new attempt at https://github.com/containers/podman/pull/15375

**Pull request closed without merging**
