### PR TITLE
[v3.0.1-rhel] Fix attempt to use incompatible go tools

### PR DESCRIPTION
**Pull request by cevich**
Change breaks on this branch which depends on an older toolchain:

https://cs.opensource.google/go/x/tools/+/master:internal/gocommand/invoke.go;bpv=1;bpt=0;drc=866a2000920cc5ae9d6650c27c4b14f4654938e7;dlc=5214f412aecffbca887fc0c26f8d59e3a2342d44

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
Re-ran 8 tasks due to a quay.io fart.

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
Looks like commit ae9a2d26dff4 is needed.  The search tests are very fragile.

**Comment by cevich** [comment]
Thanks, I'll cherry-pick that.

**Comment by cevich** [comment]
K. This is good to go.

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
and happy green test buttons.
Thanks @cevich, nice bubblegum and duct tape job!

**Pull request merged**
