### PR TITLE
[CI:DOCS] Minor: Fix podmanimage README links

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by TomSweeneyRedHat** [comment]
I coulda sworn I'd looked for those and didn't find  them the other day....

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
