### PR TITLE
[ci:docs] Fix link to point at correct content

### PR DESCRIPTION
**Pull request by rhatdan**
Version of runtime.spec was incorrect.

Fixes: https://github.com/containers/podman/issues/8244

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
LGTM

**Review by QiWang19 — COMMENTED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
