### PR TITLE
container_create: Expand env variables for commands or entrypoint with format $(ENV)

### PR DESCRIPTION
**Pull request by ch33hau**
container_create: Expand env variables for commands or entrypoint with format $(ENV)

Fixes: #15983

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by ch33hau** [comment]
Hi @rhatdan , this PR should fix the issue, but I wasn't sure that am I solving it the right way, would be great if you can review it and give some comments.

There are a few things I would like to point out:
- The expansion code are copied from kubernetes project from [here](https://github.com/kubernetes/kubernetes/tree/20b01afecbba85c53b58711b07049e8c1b764b2d/third_party/forked/golang/expansion), including its test and license files. It is mentioning [here](https://github.com/containers/podman/issues/15983#issuecomment-1262024774) and I think the code is perfect and its tests are very detailed, so I think re-using it is better (if possible).
- There are many possible ways where I can apply the expansion code, not sure if I applied it at the correct place.
- Is there a better place where I can write the tests? Right now I have e2e test only.

Thanks a lot

**Comment by rhatdan** [comment]
You should vendor in the change not copy it directly.

Replace your patch with this.
[vendor-patch.patch](https://github.com/containers/podman/files/12061287/vendor-patch.patch.txt)

**Comment by rhatdan** [comment]
@ch33hau Thanks for the PR, and overall looks good, other then vendor.

**Comment by ygalblum** [comment]
@rhatdan are you able to compile with the patch you attached here? I tried applying it to main and it seems to not be able to import `k8s.io/kubernetes`. I then checked the code and found that according to [this](https://github.com/kubernetes/kubernetes#to-start-using-k8s):
> Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported

**Comment by rhatdan** [comment]
Replaced by  #19630

**Comment by ch33hau** [comment]
@rhatdan @ygalblum sorry that I was missing for quite a while. Thanks for taking care of this PR!

**Pull request closed without merging**
