### PR TITLE
gvproxy: Update to 0.7.2 release

### PR DESCRIPTION
**Pull request by cfergeau**
This updates the Windows installer and macOS installer to ship the newer
binaries, as well as the vendored gvisor-tap-vsock code.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

(unless you track version updates of the modules you are using, in which case this would become "Update gvisor-tap-vsock binaries to 0.7.2 - this fixes a startup race condition when using applehv")

### CODE REVIEW

**Review by gbraad — APPROVED** [review]
/lgtm

**Comment by gbraad** [comment]
This release solves several issues related to AppleHV (vfkit)

**Comment by mheon** [comment]
/hold cancel
LGTM

**Comment by baude** [comment]
@mheon auto cherrypick failed here.

**Comment by cfergeau** [comment]
> @mheon auto cherrypick failed here.

I don't know in which branch/PR/... the cherry-pick happens, but I've rebased https://github.com/cfergeau/podman/commits/gvisor-tap-vsock-update/ on top of the v4.9 branch and resolved the conflict (roughly `git checkout HEAD -- go.mod && go get github.com/containers/gvisor-tap-vsock@v0.7.2 && go mod tidy && go mod vendor`)

**Pull request merged**
