### PR TITLE
reduce binary size for programs using the bindings

### PR DESCRIPTION
**Pull request by giuseppe**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
Code LGTM. Splitting entities/ is a bit strange since that was supposed to be exclusively for data structures, but I suppose it's bloated enough that we need to.

**Review by vrothberg — APPROVED** [review]
Q:  Did you measure the size reduction?

**Comment by giuseppe** [comment]
> Q: Did you measure the size reduction?

these are the results I get with the PR (and especially by using the `remote` tag): https://github.com/containers/podman/issues/12548#issuecomment-1910416390

**Comment by rhatdan** [comment]
That is excellent shrinkage, lets move forwards. Getting callers to remember "remote" tag kind of stinks, but do not see an easy way around it.

@Luap99 @vrothberg Lets get this in.

**Comment by umohnani8** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
