### PR TITLE
[v4.6] [CI:DOCS] podmansh release notes

### PR DESCRIPTION
**Pull request by lsm5**
#### Does this PR introduce a user-facing change?

```release-note
None
```

Depends on https://github.com/containers/podman/pull/19274 . Merge this after that one.

@ashley-cui @mheon @Luap99 @TomSweeneyRedHat PTAL.

### CODE REVIEW

**Comment by ashley-cui** [comment]
I think this PR also has the commit that merged with https://github.com/containers/podman/pull/19274?

**Comment by lsm5** [comment]
> I think this PR also has the commit that merged with #19274?

yes i had rebased on that PR. That one's merged, so this should be good to go.

**Comment by ashley-cui** [comment]
Do we need a release note on this? Podmansh hasn't been in any official release, so do we need to document these as changes, since I guess nothing really has changed for a user?

**Comment by lsm5** [comment]
> Do we need a release note on this? Podmansh hasn't been in any official release, so do we need to document these as changes, since I guess nothing really has changed for a user?

good point :) . Closing..

**Pull request closed without merging**
