### PR TITLE
Align docker load and podman load output

### PR DESCRIPTION
**Pull request by cipherboy**
The comma-separated podman load output isn't conducive for using the
subsequent images. For tarballs with multiple images, the comma
separator must be manually identified and a suitable range identified.

Docker CLI on the other hand, has one image identifier per line:

```
Loaded image: repo1/name1:latest
Loaded image: repo1/name1:tag1
Loaded image: repo2/name2:tag1
```

(as of Docker version 20.10.16, build aa7e414).

Switch `podman load` to this format for consistency and usability.

`Signed-off-by: Alexander Scheel <alex.scheel@hashicorp.com>`

---

#### Does this PR introduce a user-facing change?

```release-note
podman load CLI now mirrors docker load's imported image list output format
```

/cc: @baude

### CODE REVIEW

**Comment by baude** [comment]
code looks fine ...

**Comment by cipherboy** [comment]
Per conversation on IRC with Baude, adding a `[NO NEW TESTS NEEDED]` label to the commit.

**Comment by rhatdan** [comment]
Thanks @cipherboy 
/lgtm
/hold

**Comment by cipherboy** [comment]
Looks like one of the test failures was legitimate, the others looked like false-positives. I've pushed a new commit fixing this expectation and the documentation. Let me know if I should squash it into the previous commit.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, tests looked like probable flakes, I've restarted.  @cipherboy is this the first PR for this project?  If so, it will be nice to have your fingerprints in the code base!  ;^)

**Comment by cipherboy** [comment]
Thanks @TomSweeneyRedHat! Yes, first contribution here... :-)

**Pull request merged**
