### PR TITLE
[CI:DOCS] Add more annnotation information to podman kupe play man page

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Help Document https://github.com/containers/podman/discussions/22378#discussioncomment-9155116

**Comment by rhatdan** [comment]
@cevich @umohnani8 Whay are testing-farm tests running on CI:DOCS PRs?

**Comment by mheon** [comment]
LGTM

**Comment by umohnani8** [comment]
I am not sure, might be a test configuration that you have to set to not run on these kind of PRs. @cevich do you know?

Changes LGTM

**Comment by Luap99** [comment]
> @cevich @umohnani8 Whay are testing-farm tests running on CI:DOCS PRs?

Packit has no concept of our cirrus specific PR titles. It will always run everything (well at least by default, I am sure there are ways to configure what is run)

**Pull request merged**
