### PR TITLE
CI: mount tmpfs for container storage

### PR DESCRIPTION
**Pull request by Luap99**
Try to speed up the CI test by using tmpfs as container storage.

No idea if this works or will make a measurable difference but let's find out. 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Sorry for taking so long. Can you hold off on this for a little while? Specifically: hold off on anything that increases any use of tmpfs? I've been observing an ENOSPC flake in #17831, only in e2e, and I _think_ it might be due to multiple disk-hog tests running at once. Haven't looked deeply enough, and am not likely to do so soon. I'd like to understand that one before we keep piling onto tmpfs.

(In case it's not obvious, the reason it only happens in #17831 is because it disables flake retries. I am confident that it is happening in real-world PRs but we don't see it because the ginkgo flake-retry mechanism hides it).

**Comment by Luap99** [comment]
Sure all I wanted to know if it makes a measurable difference, so far it does not like it so I have no good reason to push for this.

**Comment by edsantiago** [comment]
Thanks. I still think this is worth pursuing (potentially).

The noise in sys tests bothers me. I understand noise in e2e tests: flake retries, parallelization load differences. But sys tests I would expect to be more consistent.

**Comment by Luap99** [comment]
@edsantiago Are you fine with me pushing this forward?
It doesn't improve a lot alone but with the parallel work in https://github.com/containers/podman/pull/23048 I see a measurable speed up and I think it is easer to review this change here alone rather than in the big parallel PR.

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
Yes, let's try it. Please rebase and remove the WIP.

**Comment by Luap99** [comment]
@edsantiago Good to merge like this?

**Comment by edsantiago** [comment]
Sure... worth a try

/lgtm

(may need to be merged manually)

**Pull request merged**
