### PR TITLE
Vendor c/common@main

### PR DESCRIPTION
**Pull request by ashley-cui**
Fixes windows CI.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Assuming eventual happy tests
LGTM

**Comment by ashley-cui** [comment]
Compose and api tests say the same thing. Looking...

**Comment by mheon** [comment]
Um. Let me see if adding it to my PR fixes things.

**Comment by mheon** [comment]
Threw it in https://github.com/containers/podman/pull/21339 - let's see if that fixes things

**Pull request closed without merging**
