### PR TITLE
Remove unused VolumeList* structs

### PR DESCRIPTION
**Pull request by rhatdan**
[NO TESTS NEEDED] since we are just removing unused code.

Replaces: https://github.com/containers/podman/pull/9558

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Swagger tests are angry - I think we need to tell swagger that the volume endpoints return a define.InspectVolumeData

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
/lgtm
/hold
Restarted one flake

**Pull request merged**
