### PR TITLE
[v3.4.2-rhel] fix e2e sign tests

### PR DESCRIPTION
**Pull request by vrothberg**
The key used in the tests has expired.  Remove the expiration date to
turn CI happy and green.

Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

@containers/podman-maintainers PTAL

### CODE REVIEW

**Comment by vrothberg** [comment]
Ready to merge

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Pull request merged**
