### PR TITLE
V2.1.1 RHEL backports

### PR DESCRIPTION
**Pull request by mheon**
Backports for a couple fixes that were approved but never made it into the branch.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by jnovy** [comment]
@ashley-cui 's commit message in https://github.com/containers/podman/pull/8108/commits/aed918c45984228269974e0a9a92dff154188257 misses reference to https://bugzilla.redhat.com/show_bug.cgi?id=1873204. Otherwise LGTM.

**Comment by ashley-cui** [comment]
@jnovy oh how would i fix that? since it's a backport PR

**Comment by mheon** [comment]
@ashley-cui I'll add it

**Comment by mheon** [comment]
Re-pushed with that change

**Pull request merged**
