### PR TITLE
security: use the bounding caps with --privileged

### PR DESCRIPTION
**Pull request by giuseppe**
when --privileged is used, make sure to not request more capabilities
than currently available in the current context.

[NO TESTS NEEDED] since it fixes existing tests.

Replaces: https://github.com/containers/podman/pull/9761

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by giuseppe** [comment]
we can simplify some of the new code after: https://github.com/containers/common/pull/482

**Comment by giuseppe** [comment]
tests are green now

**Comment by TomSweeneyRedHat** [comment]
LGTM
/hold cancel

**Comment by giuseppe** [comment]
> LGTM
> /hold cancel

it needs the lgtm label too

**Comment by mheon** [comment]
/lgtm

Got no idea why it didn't pick up Dan's

**Pull request merged**
