### PR TITLE
[CI:BUILD] copr: enable podman-restart.service on rpm installation

### PR DESCRIPTION
**Pull request by lsm5**
Resolves: #16669

@rhatdan PTAL

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@vrothberg @containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
> Also restart podman-restart.service on upgrade.

Why should it restart on updates? If my containers are already running I do not want them to be restarted for a podman update.

**Comment by lsm5** [comment]
> > Also restart podman-restart.service on upgrade.
> 
> Why should it restart on updates? If my containers are already running I do not want them to be restarted for a podman update.

alright, I can make that change.

**Comment by lsm5** [comment]
done

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

Thanks!

**Pull request merged**
