### PR TITLE
Bump remote API version to 3.0.0

### LINKED ISSUE #9175: podman 3.0.0 server seems to still be using the 2.0.0 API
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

As seen in https://github.com/containers/podman/issues/9098#issuecomment-770394950, it seems that Podman 3.0.0-rc2 is still using the API version from Podman 2.1.0 (that is: `2.0.0`) and not the new API version from Podman 3.0.0 (`3.0.0`)

**Steps to reproduce the issue:**

1. `podman3-remote version`

2.

3.

**Describe the results you received:**

Client:
Version:      3.0.0-rc2
API Version:  3.0.0

Server:
Version:      3.0.0-rc2
API Version:  2.0.0

`GET /v2.0.0/libpod/_ping`

**Describe the results you expected:**

Client:
Version:      3.0.0-rc2
API Version:  3.0.0

Server:
Version:      3.0.0-rc2
API Version:  3.0.0

`GET /v3.0.0/libpod/_ping`

**Additional information you deem important (e.g. issue happens only occasionally):**

The APIVersion seems to be defined in three different places, but only one of those was updated.

12f835d125bda9c6971258d54e627b8b2acf859a

So both the client and the server _seems_ to be using the older API, which apparently was unintended:

https://github.com/containers/podman/issues/9098#issuecomment-770408386

**Output of `podman version`:**

```
podman3 version 3.0.0-rc2
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04, physical

### PR DESCRIPTION
**Pull request by mheon**
Fixes #9175

I thought I did this during the initial bump to v3.0.0-dev a few months back, but evidently not.

### CODE REVIEW

**Comment by mheon** [comment]
@jwhonce What would you think about moving these version constants over to `version/version.go` so they live with all the other version info? It's honestly horribly confusing that we define API version in two entirely distinct places.

**Review by vrothberg — COMMENTED** [review]
LGTM

I am concerned that we never bumped the current API version before.  Should any change impacting the API (e.g., bug fix) have caused a version change?

**Comment by mheon** [comment]
@vrothberg We did bump the version - in `version/version.go`. Which is apparently only one of the two locations we define API version in...

**Comment by mheon** [comment]
Also, further issue for discussion: should minimum version remain as v2.0.0 - we did have some breaking changes in the API, didn't we?

**Comment by vrothberg** [comment]
> Also, further issue for discussion: should minimum version remain as v2.0.0 - we did have some breaking changes in the API, didn't we?

@rhatdan ?

**Comment by edsantiago** [comment]
Methinks you might be overly optimistic with the no-tests-needed thing. Suggestion:
```diff
diff --git a/test/apiv2/01-basic.at b/test/apiv2/01-basic.at
index f550d5fc3..cef752537 100644
--- a/test/apiv2/01-basic.at
+++ b/test/apiv2/01-basic.at
@@ -18,7 +18,7 @@ t HEAD libpod/_ping 200
 for i in /version version; do
     t GET  $i      200                           \
       .Components[0].Name="Podman Engine"        \
-      .Components[0].Details.APIVersion=2.0.0    \
+      .Components[0].Details.APIVersion=3.0.0    \
       .Components[0].Details.MinAPIVersion=2.0.0 \
       .Components[0].Details.Os=linux            \
       .ApiVersion=1.40
```
(and, for posterity, please remove the magic no-test string)

**Comment by mheon** [comment]
I'll decline to actually fix the tests for now until we have solid answers on whether to bump minimum version, and whether to consolidate all version info in version.go

**Comment by mheon** [comment]
(Can all happen in this PR but I don't want to push again until I have something approaching a final version)

**Comment by jwhonce** [comment]
@mheon I can move my version maps into that file and make the API server and client use them.  They were separate since at one  time we thought the API would live in a different repository than libpod but I no longer see that as viable. 

Do you want this by Thursday?

**Comment by mheon** [comment]
@jwhonce Doesn't need to happen for 3.0, but we should get it in before 3.1, definitely.

**Comment by mheon** [comment]
Bumped minimum API version, updated tests, this should be ready. I'd like to have it landed in time for RC3.

**Comment by edsantiago** [comment]
/lgtm
/hold

(Because this is a significant change, and I don't want the final say-so on it)

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by vrothberg** [comment]
@mheon added the backport label. Please remove it if I am mistaken.

**Pull request merged**
