### PR TITLE
Bump to v2.2.0

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
Um. It looks like the Total Success task succeeded, but Success (missing entirely) did not.

**Comment by mheon** [comment]
/hold
I think we need @cevich to untangle the CI situation on the new branch tomorrow morning.

**Comment by baude** [comment]
its in the merge pool

**Comment by mheon** [comment]
The Gating and Success tasks are Required. But not present.

**Comment by mheon** [comment]
Ah, I think I know what it is - branch protection is set wonky.

**Comment by mheon** [comment]
Alright, updated branch protection rules.

**Comment by cevich** [comment]
> I think we need @cevich to untangle the CI situation on the new branch tomorrow morning.

Ref: #8537

**Pull request merged**
