### PR TITLE
Remove SkipIfRootless if possible, document other calls

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL
Adding a bunch more tests to rootless, along with documenting why we are skipping tests.

**Comment by rhatdan** [comment]
@edsantiago PTAL, I have a follow up PR to switch to using reason for all PRs, but I want to get this in first.

**Comment by giuseppe** [comment]
LGTM

**Comment by edsantiago** [comment]
LGTM. I'll need to enable one of the system tests (`080-pause.bats`) but first need to add a cgroups v1/v2 switch.

Thanks for doing this, I'm really heartened by the increasing test coverage.

/lgtm
/hold

**Pull request merged**
