### PR TITLE
Backport: Add restart-sec option to systemd generate

### PR DESCRIPTION
**Pull request by machacekondra**
#### What this PR does / why we need it:
This PR add new parameter called `restart-sec` to `podman generate systemd` command. This parameter is used to set `RestartSec` parameter in `[Service]` section of the pod unit in systemd. The `RestartSec` configures the time to sleep before restarting a service. Some users may need to set this variable to make sure the service is controlled by default mechanism.

#### How to verify it
When running following command:
```bash
podman generate systemd --restart-sec 15 pod_name
```
You should see in the pod unit [Service] section `RestartSec=15`.

### CODE REVIEW

**Comment by vrothberg** [comment]
Why backport a _feature_?  We usually don't do that.

**Comment by rhatdan** [comment]
Yes we don't backport features.

**Comment by pkliczewski** [comment]
Here is [the bug](https://bugzilla.redhat.com/show_bug.cgi?id=2030195) tracking this backport

**Comment by vrothberg** [comment]
> Here is [the bug](https://bugzilla.redhat.com/show_bug.cgi?id=2030195) tracking this backport

Thanks! Let's see if we get an ACK for backporting.

**Comment by pkliczewski** [comment]
@vrothberg It seems like we got the ACK

**Comment by vrothberg** [comment]
@mheon, do we have green light in https://bugzilla.redhat.com/show_bug.cgi?id=2030195?  I am always worried if there's a special flag we have to wait for.

**Comment by mheon** [comment]
I think we're good to proceed? Missing some flags but the stakeholders are buying in.

**Comment by mheon** [comment]
We do need a new PR, though, this is approved for the v3.4.2-rhel branch, not v3.4

**Comment by pkliczewski** [comment]
@machacekondra please create new PR

**Comment by machacekondra** [comment]
> @machacekondra please create new PR

Opened here: https://github.com/containers/podman/pull/12602

**Pull request closed without merging**
