### PR TITLE
update c/common

### PR DESCRIPTION
**Pull request by vrothberg**
Update containers common to the latest HEAD.  Some bug fixes in libimage
forced us to have a clearer separation between ordinary images and
manifest lists.  Hence, when looking up manifest lists without recursing
into any of their instances, we need to use `LookupManifestList()`.

Also account for some other changes in c/common (e.g., the changed order
in the security labels).

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan will tackle the remaining bits here tomorrow.

**Comment by vrothberg** [comment]
Now including https://github.com/containers/common/pull/564 which should make the system tests pass.

**Comment by vrothberg** [comment]
Sigh...yet another regression in c/common. This time, evaluating the runtime in containers.conf.

**Comment by vrothberg** [comment]
https://github.com/containers/common/pull/565

**Comment by vrothberg** [comment]
Now vendored in the HEAD from Buildah to get the bud tests to pass.

**Comment by edsantiago** [comment]
@vrothberg please download this and save as test/buildah-bud/buildah-tests.diff  :  https://paste.centos.org/view/80ce0f8e

**Comment by vrothberg** [comment]
Thank you :100: times, Ed!

**Comment by vrothberg** [comment]
restarted the flake

**Comment by vrothberg** [comment]
@rhatdan ready to merge

**Pull request merged**
