### PR TITLE
[CI:DOCS] Enable readthedocs build on v4.3

### PR DESCRIPTION
**Pull request by jt-nti**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@cevich @edsantiago PTAL

**Comment by edsantiago** [comment]
LGTM but I think we're going to need a cherrypick of #16577. @jt-nti are you comfortable adding that (as a separate commit) to your PR, or would you like one of us to do so and then you can rebase?

**Review by ashley-cui — COMMENTED** [review]
/hold
/lgtm

**Comment by jt-nti** [comment]
@edsantiago I think I've added that commit 🤞

**Comment by edsantiago** [comment]
/hold cancel

Thank you!

**Pull request merged**
