### PR TITLE
[CI:DOCS] typo

### PR DESCRIPTION
**Pull request by mattcen**

### CODE REVIEW

**Comment by zhangguanzhang** [comment]
thanks for contribute, your commit messages should change to include your `Sign-off-by: <xxx>`

**Comment by baude** [comment]
do a `git commit --amend -s` and force push.

**Comment by TomSweeneyRedHat** [comment]
LGTM
other than the signature
Thanks for the PR!

**Comment by mattcen** [comment]
Ah, the challenges of making an edit on a phone via the GitHub web UI! Will update with a signature when I'm on a computer later :)

**Comment by vrothberg** [comment]
Friendly ping @mattcen. Back at the computer?

**Comment by mattcen** [comment]
Thanks for the ping, @vrothberg! Sorted now.

**Comment by rhatdan** [comment]
/lgtm
/approve

I am going to merge this because it is correct, but we could also point out that you could chown the volume to match the user inside of the container.

The :U  PR that has not been merged yet, would make this easier.

podman run -v ~/mydata;:/tmp/data:U --user foobar  

Will chown the mydata directory to match the foobar user inside of the container.

**Pull request merged**
