### PR TITLE
legacy events: also set Action="die"

### LINKED ISSUE #12628: Docker incompatibility: events API uses Action="died", not Action="die"
This is essentially the same issue as #10168 (fixed in 3.2.0), but for the `Action` field of the event. I suggest to change it for the legacy API as well.

### PR DESCRIPTION
**Pull request by leahneukirchen**
Closes #12628.

This only affects the legacy Docker API, so can be merged as a bugfix.

### CODE REVIEW

**Comment by mheon** [comment]
CI is complaining about lack of a regression test; otherwise LGTM

/approve

**Comment by leahneukirchen** [comment]
I would love to add a test, but I couldn't find any for this part of the code yet?

**Comment by rhatdan** [comment]
LGTM
Thanks @leahneukirchen

**Comment by TomSweeneyRedHat** [comment]
LGTM
but tests are unhappy, I suspect it's a flake and not related.

**Comment by mheon** [comment]
Naw, it's still angry about tests. Integration tests can't test this because it's specific to the HTTP API - APIv2 tests at https://github.com/containers/podman/tree/main/test/apiv2 would seem the appropriate place, but I can find no tests for the `events` endpoint in there.

**Comment by leahneukirchen** [comment]
These failures are totally unrelated to what I touched, no?

**Comment by mheon** [comment]
Restarted the failed test

**Pull request merged**
