### PR TITLE
vendor: drop override for github.com/opencontainers/runc

### PR DESCRIPTION
**Pull request by giuseppe**
podman builds fine with the latest runc, so we can drop the override.

Closes: https://github.com/containers/podman/issues/19795

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by giuseppe** [comment]
shurg, we are pulling in a huge new dependency (github.com/cilium/ebpf).

As usual, I forgot to run `git add vendor` before pushing the first version of the patch

**Comment by vrothberg** [comment]
I think there's still some vendor-dependency fart.  The main branch of runc doesn't require cilium anymore.  But trying to vendor that will revert many other dependencies.
`$ go mod edit -replace github.com/opencontainers/runc=github.com/opencontainers/runc@24ae5c258c41a122f1b96319c087337bac7b308a`  moves it to the latest commit and doesn't pull in cilium ... but it still replaces.

**Comment by giuseppe** [comment]
I still see cilium in the latest revision: https://github.com/opencontainers/runc/blob/main/go.mod#L7

and I get the same bloat locally: it is 59137488 vs 58094336

@kolyshkin do you think it would make sense to have a build tag to drop ebpf?

**Comment by giuseppe** [comment]
opened a PR for runc to allow disabling eBPF support: https://github.com/opencontainers/runc/pull/4005

let's see if that breaks any test

**Comment by giuseppe** [comment]
@kolyshkin I am using the latest HEAD version here, still the binary size grew by 836320 bytes

**Comment by giuseppe** [comment]
temporary version bump until there is a new runc version: https://github.com/containers/podman/pull/19854

**Comment by vrothberg** [comment]
> temporary version bump until there is a new runc version: #19854

@cyphar, do you have another runc version bump scheduled?

**Comment by giuseppe** [comment]
rebased and testing: https://github.com/containers/common/pull/1633

**Comment by vrothberg** [comment]
The system failures look consistent

**Comment by giuseppe** [comment]
runc is still bloated, the last version didn't fix the dependency issue with EPBF (reported here: https://github.com/opencontainers/runc/pull/4005), I'll close this PR for now

**Pull request closed without merging**
