### PR TITLE
Add dockerignore override support

### PR DESCRIPTION
**Pull request by AndiDog**
Same feature as in Docker (https://github.com/moby/buildkit/pull/901).

Prefer `<path to Containerfile or Dockerfile>.dockerignore` or `<path to Containerfile or Dockerfile>.containerignore` over `.dockerignore`.

This allows having a separate ignore file, which is very handy when building multiple components that each need a very different context to be sent to the builder. Example: `Dockerfile.{client,server,website}{.dockerignore}`.

I wanted to write a test but couldn't make it work on macOS (`make ginkgo-remote` gives me `Failed to compile e2e: [...] build constraints exclude all Go files [...]` – maybe because it only works on Linux?).

The changed `parseDockerignore` function is mostly taken from `vendor/github.com/containers/buildah/pkg/parse/parse.go:ContainerIgnoreFile`.

#### Does this PR introduce a user-facing change?

Yes.

```release-note
Added support for overriding `.dockerignore` by a more specific ignore file `<path to Containerfile or Dockerfile>.dockerignore` or `<path to Containerfile or Dockerfile>.containerignore`
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Thanks for contributing, @AndiDog !

@flouthoc @nalind PTAL

I think we may need to touch buildah before?

**Comment by nalind** [comment]
Looks like https://github.com/containers/buildah/issues/4236 already did it there, but we forgot to add a similar change to podman remote build.

**Comment by flouthoc** [comment]
But if this PR gets in first I'll rebase mine :) thanks for the PR @AndiDog .

**Comment by TomSweeneyRedHat** [comment]
Lot's of test unhappiness and no updates for a bit.  @flouthoc did you complete your competing PR?

**Comment by AndiDog** [comment]
> Lot's of test unhappiness

@TomSweeneyRedHat do you have a hint how to test reasonably on macOS? I couldn't get it to work (see summary).

**Comment by TomSweeneyRedHat** [comment]
Sorry @AndiDog , IDK.  I was just noting the nasty red marks next to the test results as an FYI.

**Comment by flouthoc** [comment]
@AndiDog  Do we still need this since https://github.com/containers/podman/pull/16315 is merged.

**Comment by flouthoc** [comment]
@vrothberg I think i also added support for the feature which is being implemented in this PR here: https://github.com/containers/podman/pull/16315/files#diff-e6e1e278bb9aa45783091135a432cd460a791ad0bca115061d46d6d4c18b4227R91

**Comment by vrothberg** [comment]
@flouthoc is this PR still needed?

**Comment by flouthoc** [comment]
I don't think this PR is needed anymore.

**Comment by flouthoc** [comment]
@AndiDog This is already implemented in newer versions of podman.

**Pull request closed without merging**
