### PR TITLE
Final v2.0.5 backports

### PR DESCRIPTION
**Pull request by mheon**
These are really the last ones. Definitely. For sure this time.

### CODE REVIEW

**Comment by mheon** [comment]
@edsantiago Poke - could I ask for a moment of your time to take a look at these tests?

**Comment by edsantiago** [comment]
@mheon I can reproduce, it's a real error: looking at logs gives me the supremely unhelpful:
```json
{
  "cause": "some containers failed",
  "message": "error starting some containers: some containers failed",
  "response": 500
}
```

**Comment by mheon** [comment]
At this point I'm wondering if it depends on some other part of the test that wasn't backported. Somewhat tempted to disable it.

**Comment by edsantiago** [comment]
Server logs with `--log-level=debug` does not give me any clues either, posting in case it helps you:
```
time="2020-08-24T07:50:49-06:00" level=debug msg="APIHandler -- Method: POST URL: /v1.40/libpod/pods/bar/start"
time="2020-08-24T07:50:49-06:00" level=debug msg="Strongconnecting node 6af392e59fc0dc894c533504ba775d8fe4a23120a9628f8eb0d7c23e2b01f559"
time="2020-08-24T07:50:49-06:00" level=debug msg="Pushed 6af392e59fc0dc894c533504ba775d8fe4a23120a9628f8eb0d7c23e2b01f559 onto stack"
time="2020-08-24T07:50:49-06:00" level=debug msg="Recursing to successor node 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2"
time="2020-08-24T07:50:49-06:00" level=debug msg="Strongconnecting node 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2"
time="2020-08-24T07:50:49-06:00" level=debug msg="Pushed 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2 onto stack"
time="2020-08-24T07:50:49-06:00" level=debug msg="Finishing node 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2. Popped 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2 off stack"
time="2020-08-24T07:50:49-06:00" level=debug msg="Finishing node 6af392e59fc0dc894c533504ba775d8fe4a23120a9628f8eb0d7c23e2b01f559. Popped 6af392e59fc0dc894c533504ba775d8fe4a23120a9628f8eb0d7c23e2b01f559 off stack"
time="2020-08-24T07:50:49-06:00" level=debug msg="mounted container \"7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2\" at \"/dev/shm/test-apiv2.tmp.KfdsUS/overlay/e58e0f3de08a6b1be4818e3f4c5b1d83333ad697196863a0684a7159e539c9df/merged\""
time="2020-08-24T07:50:49-06:00" level=debug msg="Created root filesystem for container 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2 at /dev/shm/test-apiv2.tmp.KfdsUS/overlay/e58e0f3de08a6b1be4818e3f4c5b1d83333ad697196863a0684a7159e539c9df/merged"
time="2020-08-24T07:50:49-06:00" level=debug msg="Made network namespace at /run/user/14904/netns/cni-6decf55c-1c60-166a-3ad0-065d2c3a696a for container 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2"
time="2020-08-24T07:50:49-06:00" level=debug msg="slirp4netns command: /usr/bin/slirp4netns --disable-host-loopback --mtu 65520 --enable-sandbox --enable-seccomp -c -e 3 -r 4 --netns-type=path /run/user/14904/netns/cni-6decf55c-1c60-166a-3ad0-065d2c3a696a tap0"
time="2020-08-24T07:50:49-06:00" level=debug msg="/etc/system-fips does not exist on host, not mounting FIPS mode secret"
time="2020-08-24T07:50:49-06:00" level=warning msg="User mount overriding libpod mount at \"/dev/shm\""
time="2020-08-24T07:50:49-06:00" level=debug msg="Setting CGroups for container 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2 to user-libpod_pod_58022376464d800a078afba95f76124c805933a5e6f5c935d87c7b955f93a616.slice:libpod:7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2"
time="2020-08-24T07:50:49-06:00" level=debug msg="reading hooks from /usr/share/containers/oci/hooks.d"
time="2020-08-24T07:50:49-06:00" level=debug msg="Created OCI spec for container 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2 at /dev/shm/test-apiv2.tmp.KfdsUS/overlay-containers/7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2/userdata/config.json"
time="2020-08-24T07:50:49-06:00" level=debug msg="/usr/bin/conmon messages will be logged to syslog"
time="2020-08-24T07:50:49-06:00" level=debug msg="running conmon: /usr/bin/conmon" args="[--api-version 1 -c 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2 -u 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2 -r /usr/bin/crun -b /dev/shm/test-apiv2.tmp.KfdsUS/overlay-containers/7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2/userdata -p /run/user/14904/containers/overlay-containers/7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2/userdata/pidfile -n 58022376464d-infra --exit-dir /run/user/14904/libpod/tmp/exits --socket-dir-path /run/user/14904/libpod/tmp/socket -s -l k8s-file:/dev/shm/test-apiv2.tmp.KfdsUS/overlay-containers/7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2/userdata/ctr.log --log-level debug --syslog --conmon-pidfile /run/user/14904/containers/overlay-containers/7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2/userdata/conmon.pid --exit-command /home/esm/src/atomic/2018-02.podman/libpod/bin/podman --exit-command-arg --root --exit-command-arg /dev/shm/test-apiv2.tmp.KfdsUS --exit-command-arg --runroot --exit-command-arg /run/user/14904/containers --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/user/14904/libpod/tmp --exit-command-arg --runtime --exit-command-arg /usr/bin/crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mount_program=/usr/bin/fuse-overlayfs --exit-command-arg --events-backend --exit-command-arg file --exit-command-arg --syslog --exit-command-arg true --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2]"
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

time="2020-08-24T07:50:49-06:00" level=debug msg="Received: -1"
time="2020-08-24T07:50:49-06:00" level=debug msg="Cleaning up container 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2"
time="2020-08-24T07:50:49-06:00" level=debug msg="Tearing down network namespace at /run/user/14904/netns/cni-6decf55c-1c60-166a-3ad0-065d2c3a696a for container 7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2"
time="2020-08-24T07:50:49-06:00" level=debug msg="unmounted container \"7cb597e875dac131e9020f458ac889b8d24ff4e2afe2943db1ff60efc34ab6d2\""
time="2020-08-24T07:50:49-06:00" level=info msg="Request Failed(Internal Server Error): error starting some containers: some containers failed"
```

**Comment by edsantiago** [comment]
well... except that AFAICT the test itself has not changed, only the pod code. This implies that, before your PR, that test was passing.

**Comment by edsantiago** [comment]
881af314d introduces the error. I can't seem to reproduce using `podman-remote` commands

**Comment by mheon** [comment]
That landed in a separate PR that passed tests with flying colors...

**Comment by mheon** [comment]
@edsantiago Anything from Conmon in syslog? It seems to be doing the thing where it prints the actual error to the logs and doesn't give it to us.

**Comment by edsantiago** [comment]
I see nothing useful via `journalctl -f` nor `tail -f /var/log/messages`.

You can very easily reproduce this:
```console
$ ./test/apiv2/test-apiv2 40
```

**Comment by edsantiago** [comment]
Through selective commenting-out of individual tests, I see that what's causing the error is a `restart`:
```bash
#t POST  "libpod/pods/bar/restart (restart on nonexistent pod)" '' 404
t POST libpod/pods/create name=bar 201 .Id~[0-9a-f]\\{64\\}
pod_bar_id=$(jq -r .Id <<<"$output")

#t POST  libpod/pods/bar/restart '' 200 \
#  .Errs=null \
#  .Id=$pod_bar_id

#t GET  libpod/pods/bar/json        200 \
#  .State=Running

t POST  libpod/pods/bar/restart '' 200 \
  .Errs=null \
  .Id=$pod_bar_id

#t POST "libpod/pods/bar/stop?t=invalid" '' 400 \
#  .cause="schema: error converting value for \"t\"" \
#  .message~"Failed to parse parameters for"

podman run -d --pod bar busybox sleep 999

t POST libpod/pods/bar/stop?t=1 '' 200 \
  .Errs=null \
  .Id=$pod_bar_id

t POST libpod/pods/bar/start '' 200 sdf
```
If I comment out that "restart", the error goes away.

Once again, I cannot reproduce this via command line:
```console
$ ./bin/podman-remote pod create --name=foo;./bin/podman-remote pod restart foo;./bin/podman-remote run -d --pod foo busybox sleep 999;./bin/podman-remote pod stop -t 1 foo;./bin/podman-remote pod start foo
4c75633ad2e1e78ccd9d873e5e45c5f336af13699691b40d5cec0ec769cf9606
4c75633ad2e1e78ccd9d873e5e45c5f336af13699691b40d5cec0ec769cf9606
e00074fa049046a7c9467b09efa237b7fe1a71c794fd13087356fce034bfbcee
4c75633ad2e1e78ccd9d873e5e45c5f336af13699691b40d5cec0ec769cf9606
4c75633ad2e1e78ccd9d873e5e45c5f336af13699691b40d5cec0ec769cf9606
```

**Comment by mheon** [comment]
Hmmmm. Investigating.

**Comment by edsantiago** [comment]
Got it! This is the smallest reproducer I can come up with. The key seems to be to `start` an already-started container:
```console
$ ./bin/podman-remote pod create --name=foo;./bin/podman-remote pod start foo;./bin/podman-remote pod create --name=bar;./bin/podman-remote run -d --pod bar busybox sleep 999;./bin/podman-remote pod stop -t 1 bar;./bin/podman-remote pod start bar
71e850427778688a4464685cc82874ad2418d1c338a17ce8ff509f13a2e8260a
71e850427778688a4464685cc82874ad2418d1c338a17ce8ff509f13a2e8260a
7449c1cfc2f14c40f476312e73eaab06f919169cd5b2b0c073c5f2d8ee107742
3418123acafdf565cd7bb88c96e60218a3ef26edfa54d5a14d440ebc1c824cd3
7449c1cfc2f14c40f476312e73eaab06f919169cd5b2b0c073c5f2d8ee107742
Error: error starting some containers: some containers failed
```
There may be a smaller or different reproducer, but I think this should get you on the right track.

**Comment by edsantiago** [comment]
Update: the following will also reproduce it:
```console
$ ./bin/podman pod create --name=foo;./bin/podman pod start foo;./bin/podman pod create --name=bar;./bin/podman-remote run -d --pod bar busybox sleep 999;./bin/podman-remote pod stop -t 1 bar;./bin/podman-remote pod start bar
cc89c70513e8c93b5f57cba57fd2c869a04e89e3e68cac899bf4c11bbfe1e1a1
cc89c70513e8c93b5f57cba57fd2c869a04e89e3e68cac899bf4c11bbfe1e1a1
84c3ccadb39e23d0dd70384fed896d60bb23d68e33acf7ffe43393a83fce427b
827e76d45de187f17ec67d28508a4e2d2b4758e5d4ef3a54faf7af39e9fd9d71
84c3ccadb39e23d0dd70384fed896d60bb23d68e33acf7ffe43393a83fce427b
Error: error starting some containers: some containers failed
```
(difference is: the first two commands, the ones with `foo`, are `podman` only, not `podman-remote`).

There is something about `podman pod start already-running-pod` that is leaving bad state behind somewhere.

**Comment by mheon** [comment]
Needs https://github.com/containers/storage/pull/698 to fix CI

**Comment by rhatdan** [comment]
Released containers/storage https://github.com/containers/storage/releases/tag/v1.23.2

**Comment by edsantiago** [comment]
Cirrus shows "Failed to stop: Remote host terminated the handshake" on a red background. Probably a flake, although not one that I'm accustomed to. Restarting.

**Comment by mheon** [comment]
`[+0256s] # error opening file `/sys/fs/cgroup//system.slice/buildah-buildah651017202-477311.scope/cgroup.freeze`: No such file or directory`

Lovely. Restarting again.

**Comment by edsantiago** [comment]
Oh yeah, that's the elusive #7148

**Comment by mheon** [comment]
It's happened 3 times in a row now. I think it's escalated from a flake.

I'm going to restart this one more time. If it still fails, we need to chase this down tomorrow morning.

**Pull request merged**
