### PR TITLE
fix: fix up memory usage for cgroup v2

### PR DESCRIPTION
**Pull request by ttys3**
2022-01-15 update:

this PR has been included in https://github.com/containers/podman/pull/12786 , so this one could be closed

https://github.com/containers/podman/pull/12786/files#diff-e4a5be3ec14dc0340e98adece8398a26007a4e9aaed9f12a285e2c0690262a01L44

-----------------------------------------

as described in https://github.com/containers/podman/issues/12702

this PR depends on upstream PR  https://github.com/containers/common/pull/870

related file:

```
 M vendor/github.com/containers/common/pkg/cgroups/cgroups.go
 M vendor/github.com/containers/common/pkg/cgroups/memory.go
```

### CODE REVIEW

**Comment by rhatdan** [comment]
You want to do something like

go mod edit --replace github.com/containers/common=github.com/ttys3/common@ff0756f34c46b413ea0f179942e0b517cc873fd5

make vendor-in-container

And then git push --force

**Comment by ttys3** [comment]
@rhatdan  thank you. I got it.
Is it better to wait the official upstream got merged ?

**Comment by rhatdan** [comment]
Now that is is merged, yes, it is better to wait.  :^)

LGTM
/approve

**Comment by ttys3** [comment]
seems not related to this PR CI tests failed:  https://cirrus-ci.com/task/5146326085140480?logs=main#L163

```
[+0020s] not ok 156 [10-images] POST images/prune?filters={"dangling":["true"]} [-d {}] : status
[+0020s] #  expected: 200
[+0020s] #    actual: 500
[+0020s] #  response: {"cause":"specifying \"dangling\" filter more then once is not supported","message":"specifying \"dangling\" filter more then once is not supported","response":500}
[+0020s] ok 157 [10-images] GET images/json?filters={"dangling":["true"]} : status=200
[+0020s] not ok 158 [10-images] GET images/json?filters={"dangling":["true"]} : length
[+0020s] #  expected: 0
```

**Comment by rhatdan** [comment]
https://github.com/containers/podman/pull/12572 has the changes needed to get containers/common revendored.

**Comment by ttys3** [comment]
OK, I re-vendor like https://github.com/containers/podman/pull/12572

use `github.com/containers/common v0.46.1-0.20211226134707-c7fd073cc020`

**Comment by ttys3** [comment]
@rhatdan 
this PR has been included in https://github.com/containers/podman/pull/12786 , so this one could be closed

https://github.com/containers/podman/pull/12786/files#diff-e4a5be3ec14dc0340e98adece8398a26007a4e9aaed9f12a285e2c0690262a01L44

**Pull request closed without merging**
