### PR TITLE
vendor c/common@main

### PR DESCRIPTION
**Pull request by vrothberg**
Finalizes the linked BZ to fix passing down custom authfiles during auto
updates.  Also fixes the if-newer pull policy.

BZ: bugzilla.redhat.com/show_bug.cgi?id=2000943
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
