### PR TITLE
system tests: disable ping tests on RHEL

### PR DESCRIPTION
**Pull request by edsantiago**
RHEL sets the net.ipv4.ping_group_range sysctl to "1 0",
basically preventing ping from working without setuid.
Disable the ping system test if we detect we're on RHEL.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
We should open an Issue with RHEL to change this default though.

**Comment by edsantiago** [comment]
If someone wants to do that, I think the starting point might be [rhbz1740809](https://bugzilla.redhat.com/show_bug.cgi?id=1740809) (closed, f31). It references this very nice [requirements document](https://fedoraproject.org/wiki/Changes/EnableSysctlPingGroupRange). Unfortunately the BZ does not link to a kernel commit or any form of detail on how this was made to happen. It doesn't seem to be as simple as setting `net.ipv4.ping_group_range="0 0"` because doing so on a RHEL8.4 system makes no difference: rootless ping still doesn't work:

    $ podman run quay.io/libpod/testimage:20200929 ping -c 3 127.0.0.1
    PING 127.0.0.1 (127.0.0.1): 56 data bytes
    bind: Permission denied

    $ podman run -it ubi8 sh
    sh-4.4# dnf -y install iputils
    ...
    sh-4.4# ping -c 3 10.0.138.150
    PING 10.0.138.150 (10.0.138.150) 56(84) bytes of data.

    --- 10.0.138.150 ping statistics ---
    3 packets transmitted, 0 received, 100% packet loss, time 69ms

(Curiously -- but not curiously enough for me to spend any time on it -- the latter actually works with 127.0.0.1. Just, not with an address outside the lo interface).  Setting the sysctl to "0 2147483647" allows rootless ping to work.

Other reference points:
* [rhbz1882136](https://bugzilla.redhat.com/show_bug.cgi?id=1882136) - toolbox-related errors writing the sysctl
* #7766 - Related discussion on Fedora gating-test failures

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by vrothberg** [comment]
> /hold

Cheers! :)

**Comment by edsantiago** [comment]
Resubmitting: I tested this as *root* on RHEL, and it failed. Looks like ping doesn't work on containers in RHEL, even root! (Glad I tested). New diff is cleaner because there's no need for nested conditionals.

**Comment by TomSweeneyRedHat** [comment]
@edsantiago Does RHEL not work at all, or only later versions?

**Comment by edsantiago** [comment]
I have no idea. The `ping` test is new (#8535, November 2020) and it looks like it has never been tested on RHEL until now. Per IRC conversation with @rhatdan earlier today, he believes that with the RHEL settings of `net.ipv4.ping_group_range`, there's no way ping would work in a container. 

Allow me to mention, once again, how dangerous it is for us to run zero CI tests on RHEL.

**Comment by edsantiago** [comment]
Oh boy... I'm sensing a great disturbance in the CI force coming soon: [build-each-commit test failed](https://cirrus-ci.com/task/5506549349089280) without my having done anything other than a new push. I've tried rebasing on master (post-#8956) and am crossing my fingers...

**Comment by rhatdan** [comment]
We need to get Root to fix their broken sysctl.

**Comment by rhatdan** [comment]
I am now thinking we might need to add back net_raw to RHEL.

**Comment by edsantiago** [comment]
FWIW, that fixes ping on RHEL, both root and rootless:
```console
$ podman run --cap-add cap_net_raw quay.io/libpod/testimage:20200929 ping -c 3 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.055 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.088 ms
64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.062 ms

--- 127.0.0.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
```
(Still can't ping the host IP on eth0, rootless, but that doesn't work on f33 either, and ISTR it will never work anyway due to rootless networking. Works fine as root).

**Comment by rhatdan** [comment]
@edsantiago do you have the sysctls set?

**Comment by edsantiago** [comment]
```
net.ipv4.ping_group_range = 1   0
```

**Comment by rhatdan** [comment]
And this works in rootless mode?  How about if you do 
--net=host?

**Comment by edsantiago** [comment]
No, `--net=host` breaks it again:
```console
$ podman run --net=host --cap-add cap_net_raw quay.io/libpod/testimage:20200929 ping -c 3 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
ping: permission denied (are you root?)
```
With ubi8:
```console
sh-4.4# ping -c 3 10.0.138.150
ping: socket: Operation not permitted
```

**Comment by rhatdan** [comment]
Ok that makes some sense.  Although it could be revealing a bug in the kernel.
Bottom line is you can not send a ping on the host network from within a rootless container, without the "BIG" sysctl set.  Which makes sense from a security point of view.  You need a trusted setuid program with NET_ADMIN caps to be able to send ping packets.

When in a usernamespace with a controlled network, you can send ping packets with Namespaced NET_ADMIN

**Comment by rhatdan** [comment]
Bottom line we have to talk to Product Management about what they want the defaults to be.

**Comment by edsantiago** [comment]
@rhatdan I get nervous with "we need to" statements. Do you have someone in mind to do this? How do we guarantee that this gets properly assigned and resolved? Should I create an issue? a BZ?

**Comment by rhatdan** [comment]
Sent an email to begin discussion.

**Comment by edsantiago** [comment]
AIUI the cause of this problem is being addressed by re-adding CAP_NET_RAW to podman on RHEL8. Can we close this PR?

**Pull request closed without merging**
