### PR TITLE
Semiperiodoc cleanup of obsolete FIXMEs

### PR DESCRIPTION
**Pull request by edsantiago**
Some refer to issues that are closed. Some, I have no idea if
they're fixed or not, we'll find out in CI.

Signed-off-by: Ed Santiago <santiago@redhat.com>

```release-note
Increase test coverage by removing outdated skips
```

### CODE REVIEW

**Comment by edsantiago** [comment]
@containers/podman-maintainers @adrianreber  any idea what's going on here? TL;DR checkpoint tests are [failing in ubuntu SYSTEM tests[(https://api.cirrus-ci.com/v1/artifact/task/5410976672514048/html/sys-podman-ubuntu-2204-root-host.log.html) but [passing in ubuntu INT tests](https://api.cirrus-ci.com/v1/artifact/task/5586898532958208/html/int-podman-ubuntu-2204-root-host.log.html).

Context is that I found a stray skip/FIXME, about checkpoint tests not working in Ubuntu, and removed the skip because I thought checkpointing was working on ubuntu. Is this a filesystem thing? system tests use `/var` and int tests use `/tmp`

**Comment by edsantiago** [comment]
Oh well. Not as ambitious as I'd hoped, but still removes some skips, and at least semi-documents others.

@giuseppe, @cdoern, please confirm my full-rootless-skip changes and description.

Checkpointing is still broken in Ubuntu. I may take another look next year in my next `find-obsolete-skips` PR.

**Review by cdoern — APPROVED** [review]
LGTM, skip message makes sense. I think honestly these tests worked before because the resource limits for v2 were finicky

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
