### PR TITLE
sqlite: set connection attributes on open

### PR DESCRIPTION
**Pull request by vrothberg**
The symptoms in #17859 indicate that setting the PRAGMAs in individual EXECs outside of a transaction can lead to concurrency issues and failures when the DB is locked.  Hence set all PRAGMAs when opening the connection.  Move them into individual constants to improve documentation and readability.

Further make transactions exclusive as #17859 also mentions an error that the DB is locked during a transaction.

Fixes: #17859

#### Does this PR introduce a user-facing change?

```release-note
None
```

@mheon @baude @edsantiago PTAL

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by vrothberg** [comment]
> The string "database is locked" does not appear in any of the CI logs for this PR, yay.
> 
> There is one instance of the "UNIQUE constraint failed" bug, in [f37 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5281869495795712/html/int-podman-fedora-37-root-host-sqlite.log.html#t--Podman-start-after-signal-kill--1).

Yes, I did not tackle https://github.com/containers/podman/issues/17858 in this PR.

> I rebased my #17831 on top of this, so we can see what system tests do.

That is good news, thanks!

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by edsantiago** [comment]
The string "database is locked" does not appear in any of the logs for the abovementioned CI run of #17831. (Two systest failures, both expected). (And, two "UNIQUE constraint" failures, and I know this PR did not set out to fix that, but I had this fantasy that the bugs were related and could be 2birds1stoned...)

`cirrus-pr-timing` results below (only the boltdb vs sqlite comparison). The new sqlite options seem to slow things down a little bit, I don't know how significantly.

| type | distro              | user     | DB     |    local |   remote | container |
| ---- | --------            | ----     | --     |    ----: |   -----: | --------: |
| int  | fedora-37           | root     |        |    29:49 |    32:55 |     28:10 |
| int  | fedora-37           | root     | sqlite |    29:33 |    33:49 |
| int  | fedora-37           | rootless |        |    28:15 |          |
| int  | fedora-37           | rootless | sqlite |    30:39 |          |

Anyhow, LGTM

**Comment by vrothberg** [comment]
> cirrus-pr-timing results below (only the boltdb vs sqlite comparison). The new sqlite options seem to slow things down a little bit, I don't know how significantly.

Those numbers are really great to have, thanks, Ed!  @baude, we can leverage Ed's timing tracking for the upcoming performance massages.

**Comment by vrothberg** [comment]
> @vrothberg PTAL at #17874 - I think we can avoid transaction exclusivity

Why open a new PR that conflicts with this one?  Seems like a time waste.

**Comment by vrothberg** [comment]
OK, we had a quick chat and greed to mix the two PRs together.  This PR gets rid of the multiple EXECs setting the PRAGMAs which is flaking.  An open question is what setting max connections does in comparison to making transactions exclusive.  I assumed that transactions (i.e., writes) _must_ be exclusive.

But I am buried in meeting til the end of my workday and let @mheon take over :)

**Comment by mheon** [comment]
Pulled it into my PR, closing this now

**Pull request closed without merging**
