### PR TITLE
Handle --rm when starting a container

### PR DESCRIPTION
**Pull request by rhatdan**
podman start should follow the same behaviour as podman run when removing a
container.

Fixes: https://github.com/containers/podman/issues/7746

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago @mheon I am not sure this is the correct behaviour.

IE Should failing to start, remove an autoremove container?

# podman run -rm fedora foo
#  podman create --name test1 --rm alpine foo;podman start test1

Both remove it, so for consistancy

 podman-run create --name test1 --rm alpine foo;podman-run start test1

Will also.

**Comment by edsantiago** [comment]
@rhatdan I think we should probably preserve the behavior documented in `podman-create(1)`:

>Note that the container will not be removed when it could not be created or started successfully. This allows the user to inspect the container after failure.

**Comment by edsantiago** [comment]
Ugh. Thinking it over some more, I'm uncertain what "started successfully" means. I could argue that getting to the point where the container says "dude, no such command" _is_ a successful execution of the container. 

This is too tricky for me to think about at the end of a long week...

**Comment by mheon** [comment]
From everything we've done so far, I think the expectation is that autoremove always removes, even containers that error. Recommendation: we should retain existing behavior and just remove that bit from the manpage.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL
@mheon @edsantiago Tests are passing, we might as well work the same way in podman as podman-remote and remove the containers when start completes, whether it succeeds or fails.

**Comment by edsantiago** [comment]
SGTM but I agree with @mheon: those two sentences need to be removed from the manpage.

**Review by vrothberg — COMMENTED** [review]
Code LGTM but I'd love a test or two.

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons

**Pull request merged**
