### PR TITLE
fix: move filter flags from StringSliceVar to StringArrayVar

### PR DESCRIPTION
**Pull request by 89luca89**
#### Does this PR introduce a user-facing change?

```release-note
User's won't be able to use `--filter label=a,label=b` but will need to specify multiple `--filter` flags
```

Currently using some complex filters (for example in `podman ps`) leads to parsing failures, for example:

```console
podman ps -q -a --filter label=dev.containers.id=devpod --filter 'label=devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"id":"ghcr.io/devcontainers/features/go:1","customizations":{"vscode":{"extensions":["golang.Go"]}},"init":true,"capAdd":["SYS_PTRACE"],"securityOpt":["seccomp=unconfined"]},{"id":"ghcr.io/devcontainers/features/node:1","customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}}},{"remoteUser":"vscode","customizations":{"vscode":{"extensions":["golang.Go"],"settings":{"go.gopath":"/go","go.toolsManagement.checkForUpdates":"local","go.useLanguageServer":true}}}},{"entrypoint":"/usr/local/share/docker-init.sh","customizations":{"vscode":{"extensions":["ms-azuretools.vscode-docker"]}},"mounts":[{"type":"volume","source":"dind-var-lib-docker-${devcontainerId}","target":"/var/lib/docker"}],"privileged":true},{"mounts":[{"type":"volume","source":"devpod","target":"/home/vscode"}]}]'
Error: invalid argument "label=devcontainer.metadata=[{\"id\":\"ghcr.io/devcontainers/features/common-utils:2\"},{\"id\":\"ghcr.io/devcontainers/features/git:1\"},{\"id\":\"ghcr.io/devcontainers/features/go:1\",\"customizations\":{\"vscode\":{\"extensions\":[\"golang.Go\"]}},\"init\":true,\"capAdd\":[\"SYS_PTRACE\"],\"securityOpt\":[\"seccomp=unconfined\"]},{\"id\":\"ghcr.io/devcontainers/features/node:1\",\"customizations\":{\"vscode\":{\"extensions\":[\"dbaeumer.vscode-eslint\"]}}},{\"remoteUser\":\"vscode\",\"customizations\":{\"vscode\":{\"extensions\":[\"golang.Go\"],\"settings\":{\"go.gopath\":\"/go\",\"go.toolsManagement.checkForUpdates\":\"local\",\"go.useLanguageServer\":true}}}},{\"entrypoint\":\"/usr/local/share/docker-init.sh\",\"customizations\":{\"vscode\":{\"extensions\":[\"ms-azuretools.vscode-docker\"]}},\"mounts\":[{\"type\":\"volume\",\"source\":\"dind-var-lib-docker-${devcontainerId}\",\"target\":\"/var/lib/docker\"}],\"privileged\":true},{\"mounts\":[{\"type\":\"volume\",\"source\":\"devpod\",\"target\":\"/home/vscode\"}]}]" for "-f, --filter" 
flag: parse error on line 1, column 31: bare " in non-quoted-field
See 'podman ps --help'
```
This PR aims to fix problems with StringSliceVar, moving it to StringArrayVar, like was done in #2582 for label parsing.

Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

### CODE REVIEW

**Comment by Luap99** [comment]
Please add tests to prevent new regressions. Also technically this is a breaking change when users used `--filter label=one,label=two` although I guess that is unavoidable. How does docker behave?

**Comment by 89luca89** [comment]
> Please add tests to prevent new regressions. Also technically this is a breaking change when users used `--filter label=one,label=two` although I guess that is unavoidable. How does docker behave?

Thanks for the feedback!

I'll add the tests asap

For the behaviour, yes now that I think of it, that changes, I wasn't even aware it was a valid syntax (always used the multiple `--filter` flag) 
Trying with docker, it indeed works both ways, I'm not sure how they avoid the StringSlice problem when passing those filters
tried those same filters with docker, and indeed they don't have the "unquoted" error, **and** they support the `--filter label=one,label=two` syntax

**Comment by Luap99** [comment]
>   and they support the --filter label=one,label=two syntax

Mhh not on my version, did you actually matched real labels to see if you get containers as result?

```
# docker ps --filter label=test1=1 --filter label=test2=2 -a 
CONTAINER ID   IMAGE     COMMAND     CREATED              STATUS    PORTS     NAMES
fc3bbc9082c6   alpine    "/bin/sh"   About a minute ago   Created             t1
92ba2b69dfd2   alpine    "/bin/sh"   2 minutes ago        Created             wonderful_mahavira
# docker ps --filter label=test1=1,label=test2=2 -a 
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
# docker ps --filter status=created,status=exited 
Error response from daemon: invalid filter 'status=created,status=exited'
# docker ps --filter status=created --filter status=exited 
CONTAINER ID   IMAGE     COMMAND                  CREATED         STATUS       PORTS        NAMES
fc3bbc9082c6   alpine    "/bin/sh"                2 minutes ago   Created                   t1
...

```

This change looks correct ot me. I don't think anyone uses this syntax for filters and if our tests pass I think we should be good. It is clearly a bug as you shown, users are unable to match labels with comma.

**Comment by 89luca89** [comment]
> > and they support the --filter label=one,label=two syntax
> 
> Mhh not on my version, did you actually matched real labels to see if you get containers as result?
> 
> ```
> # docker ps --filter label=test1=1 --filter label=test2=2 -a 
> CONTAINER ID   IMAGE     COMMAND     CREATED              STATUS    PORTS     NAMES
> fc3bbc9082c6   alpine    "/bin/sh"   About a minute ago   Created             t1
> 92ba2b69dfd2   alpine    "/bin/sh"   2 minutes ago        Created             wonderful_mahavira
> # docker ps --filter label=test1=1,label=test2=2 -a 
> CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
> # docker ps --filter status=created,status=exited 
> Error response from daemon: invalid filter 'status=created,status=exited'
> # docker ps --filter status=created --filter status=exited 
> CONTAINER ID   IMAGE     COMMAND                  CREATED         STATUS       PORTS        NAMES
> fc3bbc9082c6   alpine    "/bin/sh"                2 minutes ago   Created                   t1
> ...
> ```
> 
> This change looks correct ot me. I don't think anyone uses this syntax for filters and if our tests pass I think we should be good. It is clearly a bug as you shown, users are unable to match labels with comma.

You're right, I've tested it again and indeed doesn't find containers, not sure why I had results before, probably ran the wrong script, sorry :/

**Comment by 89luca89** [comment]
Just to add, I've sneaked in also a fix for the same issue in `podman volume create --label test=with,comma [...]`, now it works correctly :+1:

**Comment by rhatdan** [comment]
LGTM
@Luap99 PTAL

**Review by Luap99 — APPROVED** [review]
LGTM, our docs explicitly state that multiple --filter arguments must be used to set multiple filters so we should be good.

/lgtm

**Comment by 89luca89** [comment]
Thanks a lot everyone!

**Pull request merged**
