### PR TITLE
[CI:DOCS] podman-image-sign.1.md: typo fix

### PR DESCRIPTION
**Pull request by elimisteve**
identify -> identity

### CODE REVIEW

**Comment by mheon** [comment]
Please add a signoff (`git commit --amend -s`) and re-push to fix CI. Otherwise LGTM.

**Comment by rhatdan** [comment]
Thanks @elimisteve LGTM
But you need to sign.

**Comment by TomSweeneyRedHat** [comment]
LGTM once signed
`git commit --amend -s` then rebase and repush

**Comment by elimisteve** [comment]
Done :slightly_smiling_face:

**Review by Luap99 — APPROVED** [review]

**Pull request merged**
