### PR TITLE
Test new VM build

### PR DESCRIPTION
**Pull request by inknos**
https://github.com/containers/automation_images/pull/376

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
centos stream 10 dnf repos are messed up right now for whatever reason.

**Review by lsm5 — APPROVED** [review]
LGTM assuming all tests pass.

**Comment by edsantiago** [comment]
LGTM, thank you

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
