### PR TITLE
Version: bump to v5.3.0-dev

### PR DESCRIPTION
**Pull request by lsm5**
We have v5.2 branch now.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by baude** [comment]
I have pushed images for testing ... and restarted jobs, lets see how it goes.

**Comment by Luap99** [comment]
```
Location: C:\Users\Administrator\AppData\Local\cirrus-ci-build\repo
Set-LocalUser : Unable to update the password. The value provided for the new password does not meet the length, 
complexity, or history requirements of the domain.
At C:\Users\Administrator\AppData\Local\cirrus-ci-build\repo\contrib\cirrus\win-sess-launch.ps1:19 char:5
+     Set-LocalUser -Name $username -Password $encPass
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-LocalUser], InvalidPasswordException
    + FullyQualifiedErrorId : InvalidPassword,Microsoft.PowerShell.Commands.SetLocalUserCommand
 
Exit code = '1' running command at 
```

new hyperV/windows flake?

**Comment by rhatdan** [comment]
Looks like it passed tests.
LGTM

**Comment by mheon** [comment]
/lgtm

As we have a v5.2.0 out now

**Pull request merged**
