### PR TITLE
[WIP] Vendor https://github.com/containers/storage/pull/473 for testing

### PR DESCRIPTION
**Pull request by saschagrunert**
To verify that https://github.com/containers/storage/pull/473 works (or not)

### CODE REVIEW

**Comment by saschagrunert** [comment]
I'm wondering why the remote CLI tests are failing :thinking:

**Comment by rhatdan** [comment]
Will try again, if they fail again, you might have an issue.  Theoretically containers/storage should not be involved in remote.

**Comment by TomSweeneyRedHat** [comment]
@saschagrunert now it needs a rebase.

**Comment by rhatdan** [comment]
@saschagrunert Needs a rebase.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master and https://github.com/containers/storage/pull/473 PR

**Review by lastthyme — APPROVED** [review]

**Comment by vrothberg** [comment]
@saschagrunert, can we close this PR or is it in your pipeline?

I am going through some older issues and PRs at the moment.

**Comment by saschagrunert** [comment]
Yes, let's close this one for now.

**Pull request closed without merging**
