### PR TITLE
vendor updates - replacing failed dependabot PRs

### PR DESCRIPTION
**Pull request by vrothberg**
A number of commits to bump dependencies which failed in the PRs opened by dependabot.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by vrothberg** [comment]
@cevich help :sos: 

Looks like a bug in the script?  It shouldn't check changes in ./vendor.

```
#####
##### Confirming changes have no use of deprecated ioutil vs recommended io or os packages.
************************************************
ERROR: Found use of deprecated ioutil vs recommended io or os packages.:
@@ -3678,7 +3779,7 @@ var stdlib = map[string][]string{
 		"WalkDir",
 		"WalkDirFunc",
 	},
-	"io/ioutil": []string{
+	"io/ioutil": {
 		"Discard",
 		"NopCloser",
 		"ReadAll",
@@ -3688,7 +3789,7 @@ var stdlib = map[string][]string{
 		"TempFile",  (contrib/cirrus/check_go_changes.sh:29 in check_diffs())
```

**Comment by Luap99** [comment]
@vrothberg I guess it is missing this because the change is in ./test/tools/vendor.
https://github.com/containers/podman/blob/757fdca77b0fc72e61f7ee69f19a36144bfcac36/contrib/cirrus/check_go_changes.sh#L50

**Comment by cevich** [comment]
Not sure if it's relevant, but also remember that the dependabot PRs don't automatically rebase and re-test once any PR is merged.  It seems possible to me that an out-of-order merge into vendor from a bot-PR, would give a false-positive WRT CI results.  If that makes sense.

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
