### PR TITLE
[CI:DOCS] Cleanup some man pages to display options with line breaks

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/podman/issues/17388

**Review by vrothberg — COMMENTED** [review]
LGTM

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
