### PR TITLE
system tests: enable sdnotify tests

### PR DESCRIPTION
**Pull request by edsantiago**
Oops. PR #6693 (sdnotify) added tests, but they were disabled
due to broken crun on f31. I tried for three weeks to get a
magic CI:IMG PR to update crun on the CI VMs ... but in that
time I forgot to actually enable those new tests.

This PR removes a 'skip'. It also changes the test image,
from fedora:latest to :31, because (sigh) :latest removed
the systemd-notify tool.

WARNING WARNING WARNING: the symptom of a missing systemd-notify
is that podman will hang forever, not even stopped by the timeout
command in podman_run! (Filed: #7316). This means that if the
sdnotify-in-container test ever fails, the symptom will be that
Cirrus itself will time out (2 hours?). This is horrible. I
don't know what to do about it other than push for a fix for 7316.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by edsantiago** [comment]
Note: @vrothberg's #7312 mucks with NOTIFY_SOCKET, and I pushed this PR before that one merged. I did, of course, test (root, rootless; my f32 laptop and a rawhide VM) that both work together. I can rebase and push if anyone is nervous.

**Comment by edsantiago** [comment]
What is `verify_test_built_images_task` and why is it running instead of all the other things like `testing_task`?  @cevich?

**Comment by edsantiago** [comment]
@cevich this verify_test_built_images thing, could it have to do with this change in 576ce0f1b5012bec7d0a5648b1d8d752e42fba03 ?
```diff
 # Update metadata on VM images referenced by this repository state
 meta_task:

-    depends_on:
-        - "gating"
-        - "vendor"
-        - "varlink_api"
-        - "build_each_commit"
-        - "build_without_cgo"
-
```

**Comment by cevich** [comment]
> What is `verify_test_built_images_task` and why is it running instead of all the other things like `testing_task`? @cevich?

@edsantiago that should only run when building new VM images, (i.e. `CI:IMG` magic).  I don't believe it will function properly in any other context.

**Comment by edsantiago** [comment]
@cevich if you click 'View details' on this PR (next to openshift-merge-robot), you'll see a slew of `verify-*` jobs.

Aw, crap. I bet they triggered because I include CI:IMG in the commit message body. This is why a bad PR got merged: CI never actually ran. Filed #7374. Thanks for the insight, that's what I was missing.

**Pull request merged**
