### PR TITLE
[CI:MACHINE] DO NOT MERGE: TESTING MAC FLAKE

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/podman/pull/23162

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
Run one success: https://api.cirrus-ci.com/v1/artifact/task/4995050482958336/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html

**Comment by cevich** [comment]
Ya, just need to run a bunch more times to see if the flake is fixed.

**Comment by cevich** [comment]
:cry: Seems like this [doesn't fix the problem](https://api.cirrus-ci.com/v1/artifact/task/5222903464067072/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Basic-ops--1).

**Comment by Luap99** [comment]
Sad, just to confirm can you pick https://github.com/containers/podman/pull/23162 into here so we can see that it is indeed hanging at the same step.

**Comment by cevich** [comment]
@Luap99 Since I have this Mac isolated anyway, would it be helpful to go hands-on and see if that makes debugging this any easier?

I aborted task 5452333704806400 right in the middle, stopping cleanup from running, so all the files should be there.

[This script](https://github.com/containers/automation/blob/main/mac_pw_pool/InstanceSSH.sh) may help you access `MacM1-6`, the "shared" ssh key is in the secret storage service.  Remember to set all [the expected envars](https://github.com/containers/podman/blob/main/contrib/cirrus/mac_setup.sh#L26-L38) before running tests.

**Comment by cevich** [comment]
> Sad, just to confirm can you pick https://github.com/containers/podman/pull/23162 into here so we can see that it is indeed hanging at the same step.

Sorry our posts crossed.  Sure, one sec.

**Comment by Luap99** [comment]
If there is way for direct access even better, I can will try to take a look at this tomorrow

**Comment by cevich** [comment]
> If there is way for direct access

Yes.  And more importantly, "MacM1-6" is isolated from the rest of the pool, so only this PR is using it.

**Comment by cevich** [comment]
I did some googling on "APFS" + elements from the traceback.  I'm wondering if given the number of threads involved, could this be some kind of deadlock situation?

**Comment by Luap99** [comment]
> I did some googling on "APFS" + elements from the traceback. I'm wondering if given the number of threads involved, could this be some kind of deadlock situation?

The podman stack trace and this clearly shows us hanging in the write syscall, so if there is a deadlock it would be in the macos kernel assuming the go stack trace can be trusted.

**Comment by cevich** [comment]
> it would be in the macos kernel

Aye, there were a few posts I ready suspecting that.  Nothing definitive I could find though, and most references were old.  But I felt it worthwhile checking since google is often easier than low-level system debugging (esp on a closed-source OS) :stuck_out_tongue_winking_eye:

**Comment by Luap99** [comment]
Its not a deadlock, I bumped the timeout to 10 mins and with that it seems to pass https://github.com/containers/podman/pull/23162

**Pull request closed without merging**
