### PR TITLE
WIP- update runc to v1.0.0-rc93

### PR DESCRIPTION
**Pull request by vrothberg**
I saw the latest runc regressing in Podman's CI last Friday.  Since we had to unblock CI, we quickly reverted the bump in c/common but did not track down the issue. Something in the `gocapability` dep caused hiccups.

Let's start dancing and see what's going on.

### CODE REVIEW

**Comment by vrothberg** [comment]
> Error: OCI runtime error: unknown cap: `CAP_PERFMON` 

Looks like `crun` needs some massaging. @giuseppe PTAL

**Comment by vrothberg** [comment]
Looks like libcap needs updating.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/crun/issues/589 for `crunc` but I am a bit afraid if non-Fedora systems are impacted as well.

**Comment by rhatdan** [comment]
Update karma on this and we can move this along  
https://bodhi.fedoraproject.org/updates/FEDORA-2021-570cc05441

**Comment by giuseppe** [comment]
the new libcap is available for F33, F34 and Rawhide.  F32 is still affected

**Comment by giuseppe** [comment]
should we ask for a new build also on F32: https://bodhi.fedoraproject.org/updates/FEDORA-2021-570cc05441 ?

**Comment by rhatdan** [comment]
We are not planning on updateding f32, so is it required there?

**Comment by vrothberg** [comment]
> We are not planning on updateding f32, so is it required there?

It won't pass CI otherwise.  But given we won't update F32, we could remove it from CI entirely and give back the polar bears some more days on this planet.

**Comment by rhatdan** [comment]
Agree, athough f34 is about to branch, so we might start using it to melt the polar icecaps, soon.
@cevich PTAL

**Comment by cevich** [comment]
Nod.  There was another PR somewhere that needed updated VM images also...here https://github.com/containers/podman/pull/9245 also for runc/crun updates but for Ubuntu.  Might as well do them both at once. @lsm5 poke.

**Comment by lsm5** [comment]
runc v1.0.0-rc93 building now: https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/cri-o-runc

**Comment by cevich** [comment]
Built Image suffix `c4770991810281472`, versions below:

* Fedora 33 (uses cgroups v2):
  ```
  Kernel:  5.10.17-200.fc33.x86_64
  Cgroups:  cgroup2fs
  conmon-2.0.26-1.fc33-x86_64
  containernetworking-plugins-0.9.1-2.fc33-x86_64
  containers-common-1.2.0-13.fc33-x86_64
  container-selinux-2.156.0-1.fc33-noarch
  criu-3.15-1.fc33-x86_64
  crun-0.17-1.fc33-x86_64
  golang-1.15.8-1.fc33-x86_64
  libseccomp-2.5.0-3.fc33-x86_64
  podman-2.2.1-1.fc33-x86_64
  runc-1.0.0-279.dev.gitdedadbf.fc33-x86_64
  skopeo-1.2.0-13.fc33-x86_64
  slirp4netns-1.1.8-1.fc33-x86_64
  ```
* Ubuntu 2010 (uses cgroups v2):
   ```
   Kernel:  5.8.0-1008-gcp
   Cgroups:  cgroup2fs
   conmon-100:2.0.26-1-amd64
   containernetworking-plugins-100:0.9.1-1-amd64
   containers-common-100:1-10-all
   cri-o-runc-1.0.0~rc93.1-amd64
   criu-3.15-0.buster-amd64
   crun-100:0.17-5-amd64
   libseccomp2-2.5.1~3-amd64
   podman-100:3.0.0-3-amd64
   skopeo-100:1.2.1-10-amd64
   slirp4netns-100:1.1.8-3-amd64
   ```
* Fedora 32 (uses cgroups v1)
   ```
   Kernel:  5.10.16-100.fc32.x86_64
   Cgroups:  tmpfs
   conmon-2.0.26-1.fc32-x86_64
   containernetworking-plugins-0.9.0-1.fc32-x86_64
   containers-common-1.2.0-13.fc32-x86_64
   container-selinux-2.155.0-2.fc32-noarch
   criu-3.15-1.fc32-x86_64
   crun-0.17-1.fc32-x86_64
   golang-1.14.13-1.fc32-x86_64
   libseccomp-2.5.0-3.fc32-x86_64
   podman-2.2.1-1.fc32-x86_64
   runc-1.0.0-146.rc92.fc32-x86_64
   skopeo-1.2.0-13.fc32-x86_64
   slirp4netns-1.1.8-1.fc32-x86_64
   ```
* Ubuntu 2004 (uses cgroups v1):
   ```
   Kernel:  5.4.0-1028-gcp
   Cgroups:  tmpfs
   conmon-100:2.0.26-1-amd64
   containernetworking-plugins-100:0.9.1-1-amd64
   containers-common-100:1-10-all
   cri-o-runc-1.0.0~rc93.1-amd64
   criu-3.15-1ppa1.20.04-amd64
   crun-100:0.17-5-amd64
   libseccomp2-2.5.1~3-amd64
   podman-100:3.0.0-3-amd64
   skopeo-100:1.2.1-10-amd64
   slirp4netns-100:1.1.8-3-amd64
   ```

**Comment by vrothberg** [comment]
@cevich, can you assemble the same list for `libcap`?

**Comment by vrothberg** [comment]
Since Ubuntu e2e tests pass, I am confident that ditching F32 will unblock.

**Comment by cevich** [comment]
> can you assemble the same list for libcap?

It's kind of a PITA to do, but assuming it's crucial information I'll grab it...

fedora 32: `libcap-2.26-7.fc32.x86_64`
fedora 33: `libcap-2.48-2.fc33.x86_64`
ubuntu-2010: `libcap-dev:amd64 1:2.43-1`
ubuntu-2004: `libcap-dev:amd64 1:2.32-1`

Odd it's older on F32 than ubuntu-2004

**Comment by cevich** [comment]
> I am confident that ditching F32 will unblock.

https://github.com/containers/podman/pull/9474

**Comment by vrothberg** [comment]
Closing since another PR includes the bump.  F32 has been disabled in CI, so we are good to go.

**Pull request closed without merging**
