### PR TITLE
Cirrus: Restore APIv2 Testing

### LINKED ISSUE #7954: CI: looks like we lost test-apiv2
As best I can tell, it looks like we lost `test/apiv2` in the big Cirrus switchover. It needs to be added back.

### PR DESCRIPTION
**Pull request by cevich**
Fixes #7954

This was mistakenly left out of 2c9084e2245

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by rhatdan** [comment]
How come this 
APIv2 test on fedora-32 

Does not have a green check mark?

**Comment by cevich** [comment]
> Does not have a green check mark?

Oh thanks for reminding me.  I marked it 'ignore failure', since some of the test items are not working and I need to open an issue on it...

**Comment by cevich** [comment]
@baude PTAL and would you mind taking/assigning #7972?

**Comment by rhatdan** [comment]
So we have a checking and the egg situation on this PR.  If we merge this PR we will need another PR to turn enforcing mode on.
I wish the Skip if failed was a little more visual that the tests actually failed.
If these tests succeed do they get a check mark?  IE Does the grey square box indicated a failed, ignored check?

**Comment by cevich** [comment]
> So we have a checking and the egg situation on this PR.

Aye, hence the issue :disappointed: 

> If these tests succeed do they get a check mark?

Hmmm, I would only be guessing.  I believe the effect of that option is for Cirrus to NOT report any value back, so I think it remains a gray-square no matter what.  

@rhatdan one idea could be...just leave this PR sit here until the tests are fixed, and/or rebasing it into the fixing PR.

**Comment by cevich** [comment]
Note: I added a separate commit which makes the test ignore failures.  So once they're green, that commit can just be reverted.

**Comment by rhatdan** [comment]
@baude @mheon Most of the breakage here is in the Network Stack

**Comment by edsantiago** [comment]
@cevich try rebasing on #7994

**Comment by cevich** [comment]
Sure, happy to...

**Comment by edsantiago** [comment]
My bad; I tested only rootless on my laptop, not root. #8000 should fix.

**Comment by edsantiago** [comment]
@cevich third time's the charm? Please rebase at your convenience, let's see if #8000 can get tests passing.

**Comment by cevich** [comment]
rebased.

**Comment by cevich** [comment]
@edsantiago in case you didn't realize: It works the other way too, you can temporarily rebase the "fix" pr ontop of this one.  You can make the temporary test even faster by marking irreverent tasks with `skip: $CI == $CI` in `.cirrus.yml`

**Comment by edsantiago** [comment]
I think you accidentally rebased on an old master, can you try current master?

**Comment by cevich** [comment]
> I think you accidentally rebased on an old master, can you try current master?

git says `everything up to date`...maybe my clone or config is messed up...

**Comment by cevich** [comment]
...oof, git config is messed up.

**Comment by edsantiago** [comment]
Failure in `int remote ubuntu-20 root host` was a CI timeout; restarted

**Comment by cevich** [comment]
Ugg, `Failed in 01:30:50`...these remote tasks are running awful close to the line.  I know some folks have a mind to make these tests run quicker.  If we keep seeing this, it's probably worth bumping up the timeout by another 10-20 minutes :disappointed:

**Comment by edsantiago** [comment]
AFAIK nobody has even the slightest intention of making anything run quicker. If anything, it's the opposite. So, yeah, bumping the timeout might be necessary.

**Comment by cevich** [comment]
> AFAIK nobody has even the slightest intention of making anything run quicker.

@baude spoke last week or the one before about speeding them up.  IIRC was something about moving calls from `PodmanNoCache()` -> `Podman()`, eh?  I tried to look if there's a card for this...but jira is not behaving ATM :disappointed:

**Comment by cevich** [comment]
@mheon @baude confirmed, I don't see any jira card for this activity.  Mind creating one, so the wish is retained in writing? :smile:

**Pull request merged**
