### PR TITLE
Fix build for mips architecture follow-up 

### PR DESCRIPTION
**Pull request by Luap99**
Follow-up to commit (1ad7966). The build on mips is still
failing because SIGWINCH was not defined in the signal pkg.
Also stat_t.Rdev is unit32 on mips so we need to typecast.

Second, add mips architecture to the cross build target.
I confirmed that the cross compile for mips works now.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by Luap99** [comment]
@edsantiago @cevich I don't see the `local-cross` make target executed in CI. I think we should add this to prevent regression.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 do you want to do the Makefile change in this PR or should we merge this and do that in a follow up?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by Luap99** [comment]
> @Luap99 do you want to do the Makefile change in this PR or should we merge this and do that in a follow up?

This can be merged. The makefile target exists I just need someone to make the CI use it to prevent a regression. This should be a task for @cevich or @edsantiago. I don't understand the `.cirrus.yml` stuff.

**Comment by cevich** [comment]
> The makefile target exists I just need someone to make the CI use it to prevent a regression. This should be a task for @cevich or @edsantiago. I don't understand the .cirrus.yml stuff.

Sure I'm happy to help add this to CI @Luap99.  Does CI simply need to confirm that `make local-cross` runs w/o returning an error-exit code?

**Comment by Luap99** [comment]
> Sure I'm happy to help add this to CI @Luap99. Does CI simply need to confirm that make local-cross runs w/o returning an error-exit code?

Yes

**Comment by cevich** [comment]
Ref: https://github.com/containers/podman/pull/8939

**Pull request merged**
