### PR TITLE
Quadlet test - add case for multi = sign in mount

### PR DESCRIPTION
**Pull request by ygalblum**
#### Does this PR introduce a user-facing change?
No

```release-note
None
```

### CODE REVIEW

**Comment by ygalblum** [comment]
Added another case following #20645

**Comment by rhatdan** [comment]
/approve
LGTM
@containers/podman-maintainers PTAL
@edsantiago PTAL

**Review by flouthoc — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
