### PR TITLE
Fix netavark error handling and teardown issue

### PR DESCRIPTION
**Pull request by Luap99**
#### What this PR does / why we need it:

The return error was not returned by podman , instead a different error
was created. Also make sure to free assigned ips on an error to not leak
them.

Lastly podman container cleanup uses the default network backend instead
of the provided one, we need to add `--network-backend` to the exit
command.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
but you'll need the "NO NEW TESTS NEEDED" tag to get the CI happy.

**Comment by rhatdan** [comment]
Sadly needs a rebase.

**Comment by rhatdan** [comment]
Force merging.

**Pull request merged**
