### PR TITLE
Add support for podman manifest rm command

### PR DESCRIPTION
**Pull request by rhatdan**
This is mainly to match command line of Docker.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
My man-page checker is being pedantic:
```
Inconsistent subcommand descriptions:
  podman-manifest-rm.1.md          = 'Removes one or more manifest lists.'
  podman-manifest.1.md             = 'Remove manifest list or image index from local storage'
Please ensure that the NAME section of podman-manifest-rm.1.md
matches the subcommand description in podman-manifest.1.md
```

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM once the tests are hip.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
