### PR TITLE
podman machine start: make checkExclusiveActiveVM check race free 

### PR DESCRIPTION
**Pull request by Luap99**
see commits
```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@baude @mheon @ashley-cui PTAL

**Comment by ashley-cui** [comment]
LGTM

**Comment by mheon** [comment]
Though your test appears to be failing on WSL

**Comment by Luap99** [comment]
Uh mac failed as well but this looks like a legit test bug there: https://api.cirrus-ci.com/v1/artifact/task/4904265781608448/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--podman-machine-start-start-two-machines-in-parallel--1

I think I know what is wrong, maybe that is the same issue on windows.

**Comment by mheon** [comment]
Failure is consistent. Is WSL VM startup conflict detection broken?

**Comment by baude** [comment]
@Luap99 hit me up in the morning if you don't have this pinned down.  I should be able to help.

**Comment by Luap99** [comment]
Ok looks like everything should be working now.

**Pull request merged**
