### PR TITLE
Consolidate filter logic to pkg subdirectory

### PR DESCRIPTION
**Pull request by bblenard**
Per the conversation on pull/8724 I am consolidating filter logic
and helper functions under the pkg/domain/filters dir.

Signed-off-by: Baron Lenardson <lenardson.baron@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@mheon PTAL

**Comment by bblenard** [comment]
@baude kept my promise!

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by bblenard** [comment]
> @containers/podman-maintainers PTAL

bump ^

**Pull request merged**
