### PR TITLE
Release v3.3.2

### PR DESCRIPTION
**Pull request by mheon**
Backports, release notes, and release tag. Entirely focused on `podman machine` and OS X fixes; everything else will wait until 3.4.0 releases later this month.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
but tests are falling down hard

**Comment by mheon** [comment]
@baude This is my backport of https://github.com/containers/podman/pull/11591 - is this important enough to justify keeping or should I just drop it?

**Comment by mheon** [comment]
Build still failing - might need a newer c/image? @vrothberg This looks like the auto-update backport from 0.42.3 - did you also require a c/image bump?

**Comment by Luap99** [comment]
@mheon https://github.com/containers/podman/pull/11653/files You need to add a new function argument. No other dependencies are needed.
https://github.com/containers/podman/blob/cd7b48198c38c5028540e85dc72dd3406f4318f0/pkg/autoupdate/autoupdate.go#L407-L408

**Comment by vrothberg** [comment]
@Luap99 is right on spot.  I did not expect another 3.3 release, so I didn't backport the change, sorry.

**Comment by mheon** [comment]
Alright, new plan: drop this, move the 3.4 schedule up.

**Pull request closed without merging**
