### PR TITLE
Clarify remote client means Mac and Windows

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @vrothberg PTAL

**Review by vrothberg — COMMENTED** [review]
`s/Windows Machines/Windows (excluding WSL2) machines/`

Thanks!

**Comment by rhatdan** [comment]
@n1hility could you verify for Windows.  Do we use Podman-remote with Windows, or is it actually a full fledge podman client that WSL is showing?

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/podman/issues/13060

**Review by vrothberg — COMMENTED** [review]
LGTM, thank you @rhatdan

**Comment by TomSweeneyRedHat** [comment]
I'm probably being badly effected by PTO brain today, but why the "(excluding WSL2)" bit?  I thought Podman on windows required WSL2?  Unless I'm misunderstanding, you're saying "this option doesn't work on Windows (excluding Windows)".  But perhaps it's time fro the first cup of tea.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat If you grab the podman exe for Windows, it is remote and is podman-remote. If you run within WLS2 you are running the Linux Podman directly, through WSL magic. So you can run it in either mode. There is a PR to add qemu based images just like Podman on a Mac works.

**Comment by n1hility** [comment]
Would it be clearer to say “(unless within machine ssh or WSL2 prompt)”? 

I mainly mean the explanation applies to both Mac and Windows.

**Comment by jwhonce** [comment]
/lgtm 

I am in agreement with @rhatdan

**Pull request merged**
