### PR TITLE
1.6.4 cleanup

### PR DESCRIPTION
**Pull request by vrothberg**
A series of backported downstream patches that were not part of the upstream branch and caused maintenance issues for the 1.6.4-rhel branch.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2087994

@TomSweeneyRedHat @jnovy @mheon PTAL

### CODE REVIEW

**Comment by vrothberg** [comment]
@cevich gating fails with networking (see https://github.com/containers/podman/pull/14752/checks?check_run_id=7091424921). PTAL.

**Comment by cevich** [comment]
Yep, this failed on [the cirrus-cron job yesterday.](https://cirrus-ci.com/build/5652130798239744).  That `failed_branch` (IRC notification) task can be deleted, it will never pass.

**Comment by cevich** [comment]
LGTM.  I can remove that `failed_branch` task separately.

**Comment by TomSweeneyRedHat** [comment]
@vrothberg :cookie: for this one,TYVM!

**Pull request merged**
