### PR TITLE
Bump to 5.0.0-rc5

### PR DESCRIPTION
**Pull request by ashley-cui**
Replaces https://github.com/containers/podman/pull/21970 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by n1hility** [comment]
LGTM

**Comment by ashley-cui** [comment]
@containers/podman-maintainers PTAL and merge :)

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by ashley-cui** [comment]
I think my pkginstaller PR broke Mac tests, taking a look now. :(

**Comment by TomSweeneyRedHat** [comment]
Almost time for dinner here @ashley-cui , I'll check back later this evening.

**Comment by ashley-cui** [comment]
Thanks @TomSweeneyRedHat for keeping an eye on it :) Hopefully I found the fix, fingers crossed. A slash-lgtm whenever would be helpful!

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by ashley-cui** [comment]
Heading out for a sec, will finish up the release once I'm back

**Comment by TomSweeneyRedHat** [comment]
the fedora-39--aarch64 rootless host sqlite failed with a timeout in the "start simple machine" test:

```
[+1348s]   Machine "cff8bc694aaa" started successfully
[+1348s]   /var/tmp/go/src/github.com/containers/podman/bin/podman-remote machine stop cff8bc694aaa
[+1348s]   Waiting for VM to exit...
[+1350s]   Machine "cff8bc694aaa" stopped successfully
[+1350s]   /var/tmp/go/src/github.com/containers/podman/bin/podman-remote machine start cff8bc694aaa --quiet
[+1590s]   [FAILED] Timed out after 240.001s.
[+1590s]   Expected process to exit.  It did not.
[+1590s]   In [It] at: /var/tmp/go/src/github.com/containers/podman/pkg/machine/e2e/config_test.go:56 @ 03/08/24 00:33:32.1
[+1590s] 
[+1590s]   Full Stack Trace
[+1590s]     github.com/containers/podman/v5/pkg/machine/e2e_test.(*machineSession).waitWithTimeout(0x40002aa580?, 0x142f7a0?)
[+1590s]     	/var/tmp/go/src/github.com/containers/podman/pkg/machine/e2e/config_test.go:56 +0xc8
[+1590s]     github.com/containers/podman/v5/pkg/machine/e2e_test.runWrapper({0x4000556840, 0x3e}, {0x40005ce340, 0x4, 0x4}, 0x0?, 0x1)
[+1590s]     	/var/tmp/go/src/github.com/containers/podman/pkg/machine/e2e/config_test.go:175 +0x2cc
[+1590s]     github.com/containers/podman/v5/pkg/machine/e2e_test.(*machineTestBuilder).run(...)
[+1590s]     	/var/tmp/go/src/github.com/containers/podman/pkg/machine/e2e/config_test.go:159
[+1590s]     github.com/containers/podman/v5/pkg/machine/e2e_test.glob..func14.3()
[+1590s]     	/var/tmp/go/src/github.com/containers/podman/pkg/machine/e2e/start_test.go:54 +0x798
[+1590s]   < Exit [It] start simple machine - /var/tmp/go/src/github.com/containers/podman/pkg/machine/e2e/start_test.go:24 @ 03/08/24 00:33:32.1 (5m10.32s)
[+1590s]   > Enter [AfterEach] podman machine start - /var/tmp/go/src/github.com/containers/podman/pkg/machine/e2e/start_test.go:20 @ 03/08/24 00:33:32.1
[+1590s]   /var/tmp/go/src/github.com/containers/podman/bin/podman-remote machine rm --force cff8bc694aaa
[+1830s]   [FAILED] Timed out after 240.000s.
[+1830s]   Expected process to exit.  It did not.
[+1830s]
```

I'll restart, I don't see any changes in there that should have caused that.

**Comment by TomSweeneyRedHat** [comment]
@ashley-cui the "Optional Release Test" is failing due to the `-dev` tag.  I think that can be ignored, everything else is green.  I'm good if you concur and hit the shiny "Merge pull request" with the Merge Hammer.

**Pull request merged**
