### PR TITLE
System tests: add podman run --tz

### PR DESCRIPTION
**Pull request by edsantiago**
New tests for podman run --tz=EXPLICIT and =local. Requires
updating our testimage by adding a fixed reference timestamp
to a known file path.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by edsantiago** [comment]
Test failure looks like a flake. Please don't restart, I'm investigating (and possibly filing an issue), will restart after I find out more.

**Comment by edsantiago** [comment]
Filed #7837. And restarted due to another flake, this time #7808.

**Pull request merged**
