### PR TITLE
vendor c/common@main

### PR DESCRIPTION
**Pull request by vrothberg**
Update the `--filter reference=...` tests to reflect recent changes in
c/common.  The reference values now match as specified without
implicitly adding wildcards around.

Fixes: #11905
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by vrothberg** [comment]
@giuseppe @flouthoc PTAL

**Pull request merged**
