### PR TITLE
[v4.5] Cirrus: Disable CI

### PR DESCRIPTION
**Pull request by cevich**
As of the `v4.6` release, there is no reason to maintain functional CI on this upstream-only release branch.  Disable it.

***Note***: I also removed the `v4.5` cirrus-cron job entry.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by lsm5** [comment]
ignoring rawhide and el9 failures.

/lgtm

**Comment by cevich** [comment]
@lsm5 PTAL @ failing packit jobs.  Would you like me to disable that here as well?  If so, what is preferred method?

**Comment by lsm5** [comment]
> @lsm5 PTAL @ failing packit jobs. Would you like me to disable that here as well? If so, what is preferred method?

If this branch is dead to us across the board, let's also get rid of `.packit.yaml` in this PR. And we'll be green.

**Comment by cevich** [comment]
Thanks Lokesh.  I've removed it.

**Pull request merged**
