### PR TITLE
Fix handling of podman-remote stop --ignore

### PR DESCRIPTION
**Pull request by rhatdan**
This patch simplifies the hanlding of rhe --ignore flag, for podman stop, rm

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
but one of the tests is not hip

**Comment by rhatdan** [comment]
@mheon @vrothberg @baude @ashley-cui @QiWang19 @jwhonce @edsantiago PTAL
Mainly this turns on additional test for remote.

**Comment by QiWang19** [comment]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by edsantiago** [comment]
Belated LGTM (I feel so dense)

**Pull request merged**
