### PR TITLE
[CI:DOCS] Fix podman farm update --help examples

### LINKED ISSUE #20079: podman farm update --help error
### Issue Description

https://github.com/containers/podman/blob/dce3ef3c42805b56adadad6c452791d52928e7cb/cmd/podman/farm/update.go#L24
https://github.com/containers/podman/blob/dce3ef3c42805b56adadad6c452791d52928e7cb/cmd/podman/farm/update.go#L25
in line 24 and line 25, it shoule be "	podman farm update --remove con2 farm2", we miss out "farm" indeed

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by boaz0**
closes #20079
#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM
@boaz0 please add [CI:DOCS] to the commit message as well to make the tests happy

**Comment by edsantiago** [comment]
/hold cancel
/approve

This only changes the cobra `Example`, not `Usage`, but I still needed to convince myself (via unsetting `Hidden`) that all the doc strings are ok. They are. Thank you for taking the time to report and fix this!

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@mheon this might need the merge hammer

**Comment by mheon** [comment]
Release note block is improperly formatted, let me fix

**Pull request merged**
