### PR TITLE
Fixed Typo in help command

### PR DESCRIPTION
**Pull request by jjasghar**
#### Does this PR introduce a user-facing change?

None 

```release-note
None
```

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
I added the [NO NEW TESTS NEEDED] flag to your PR.

Could you repush.

git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
LGTM

**Review by Luap99 — CHANGES_REQUESTED** [review]
This change is not correct, the var already includes a whitespace and the var might be empty. The correct fix is https://github.com/containers/podman/pull/20580

**Pull request closed without merging**
