### PR TITLE
Set config environment variables early in Podman init

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/12296

[NO NEW TESTS NEEDED] because there is no easy way to test this.
Tests are in containers/common.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Requires https://github.com/containers/common/pull/828 to be merged.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
You can test this with something like `podman -e TMPDIR alpine printenv TMPDIR`.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
Great idea @Luap99

**Comment by rhatdan** [comment]
@Luap99 @vrothberg @giuseppe PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
