### PR TITLE
Seems compat to see 'No such image' when creating container

### PR DESCRIPTION
**Pull request by rhatdan**
[ NO NEW TESTS NEEDED ]
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
See if this fixes: https://github.com/containers/podman/pull/12315

**Comment by rhatdan** [comment]
@mscherer could you try this out and see if this fixes the problem.
@mheon @jwhonce The Utils.Error code seems like it could use some work.

**Comment by rhatdan** [comment]
It looks like the Docker clients are expecting "No such %s" in their error messages, but we tend to return

"%s not found", Should we generalize this for Docker compatibility.

**Comment by mscherer** [comment]
So I tired. It doesn't work. however, if the patch is change to modify the "Message" key, as in https://github.com/containers/podman/pull/12315#issuecomment-970514938 , it work

(then I hit another issue where docker normalize image name and I have no idea on how to fix that one without lowering security)

**Comment by mscherer** [comment]
See https://github.com/containers/podman/pull/12318

**Comment by Luap99** [comment]
Lets close this in favour of #12318

**Pull request closed without merging**
