### PR TITLE
Use new secret store API

### PR DESCRIPTION
**Pull request by ashley-cui**
Refactored secrets API in common for stability purposes. Move podman to
said API.

#### Does this PR introduce a user-facing change?

```release-note
None

```

### CODE REVIEW

**Comment by ashley-cui** [comment]
Ready to look at! This should unblock vendoring, as it vendors common@main and deals with the breaking change in the secrets API.

**Comment by vrothberg** [comment]
Event tests aren't happy.  @Luap99 probably you need to cherry-pick this commit here or the other way around.

**Comment by Luap99** [comment]
I cherry-picked it into #15717.

**Comment by vrothberg** [comment]
Thanks!  Let's close this PR there then.

**Pull request closed without merging**
