### PR TITLE
fix api swagger docs

### LINKED ISSUE #22351: Latest docs.podman.io Reference page has a circular dependency.
### Issue Description

When going to this URL https://docs.podman.io/en/latest/_static/api.html, you receive:

```
Something went wrong...
Self-referencing circular pointer

Stack trace
ReDoc Version: 2.0.0-rc.75
Commit: d7440fb
```

This can also happen if you go to docs.podman.io->reference->latest

This appears to be an issue only with latest, the other links on that page pointing to particular versions are working fine.

@baude any thoughts?

### Steps to reproduce the issue

Steps to reproduce the issue
1.  See description
2.
3.

### Describe the results you received

Error page

### Describe the results you expected

API documentation page

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by Luap99**
see commits, that last commit fixes the real issue in the swagger generation

Fixes #22351

#### Does this PR introduce a user-facing change?

```release-note
The API swagger docs should now work again and include proper type information.
```

### CODE REVIEW

**Comment by Luap99** [comment]
@baude @jwhonce PTAL

**Comment by jwhonce** [comment]
LGTM, tested on my laptop

**Comment by Luap99** [comment]
https://docs.podman.io/en/latest/_static/api.html
Looks like it worked.

**Pull request merged**
