### PR TITLE
[CI-DOCS] Update license with copyright info

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Updates the license with copyright info.

Addresses Discussion #18646

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
I've added a DO NOT MERGE label as I'd like to get someone from Legal to give this a once over.  @mheon, I think the dates are correct, please leave a comment if not.

**Comment by richardfontana** [comment]
As I commented in #18646, I think it is historically erroneous to instantiate the generic example license notice in the Apache License 2.0 appendix, but harmless and I do see a number of projects doing this nowadays. But the other aspect of the change in this pull request that I think is actually bad practice, and which I urge not be merged, is the insertion of a license notice inside the Apache License 2.0 text itself, i.e. 
https://github.com/containers/podman/pull/18658/files#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7R5-R19

**Comment by TomSweeneyRedHat** [comment]
@richardfontana thanks. Yeah, I'm not at all sure about the formatting or appropriate placement of the copyrights.  I've sent a mail to the Red Hat Legal team, specifically, the folks that deal with Open Source, I'll let them guide me on that.  I don't suspect this current rev will be final

**Comment by richardfontana** [comment]
>  I've sent a mail to the Red Hat Legal team, specifically, the folks that deal with Open Source, 

Haha, that would be me :)

**Comment by TomSweeneyRedHat** [comment]
Ooops!  Just saw the email and made the connection.  Thanks @richardfontana.

**Comment by TomSweeneyRedHat** [comment]
Thanks all for the discussion here, in email, and in #18646.  Given all that, I'm going to close this PR and will leave the license as it was.

**Pull request closed without merging**
