### PR TITLE
Vendor in latest containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg PTAL

BTW I have no idea why we have to do the replace, but modifying go.mod with just storage, is failing.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
Ok I bumbed the version of storage and removed the other replace for runc.

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
