### PR TITLE
[v3.0.1-rhel] backport `podman cp` fixes

### PR DESCRIPTION
**Pull request by vrothberg**
A number of backports to fix https://bugzilla.redhat.com/show_bug.cgi?id=1936927.

@TomSweeneyRedHat @rhatdan PTAL

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
Hopefully, we'll be able to merge tomorrow, March 11

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
/hold cancel

We have approval

**Pull request merged**
