### PR TITLE
WSL refactoring

### PR DESCRIPTION
**Pull request by baude**
Small amount of refactoring to make WSL specific stuff into the WSL package where possible.  This is in preparation for the possibility of adding more virtualization backends.

[NO NEW TESTS NEEDED]

Signed-off-by: Brent Baude <bbaude@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by baude** [comment]
hold until 4.4 is branched.

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by n1hility** [comment]
LGTM

**Review by n1hility — APPROVED** [review]

**Comment by vrothberg** [comment]
4.4 has been branched, so
/hold cancel

**Pull request merged**
