### PR TITLE
Fix interrupting machine start leaves the machine unstartable

### PR DESCRIPTION
**Pull request by shanesmith**
Interrupting a `podman machine start` (ex: with CTRL-C) would leave
`Starting: true` in the machine's config file. Due to #14469 any
subsequent starts would fail since Podman would think the machine is
still in the process of starting.

Fixed here by listening for the interrupt signal and setting `Starting:
false` in the event.

```release-note
Fix interrupting a machine start leaves the machine unstartable
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by shanesmith** [comment]
Thanks for the lightning quick review! ⚡

**Pull request merged**
