### PR TITLE
vendor containers/common@main

### PR DESCRIPTION
**Pull request by vrothberg**
Pull in fixes for local image lookups.

Fixes: #10835
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
Sorry @vrothberg, we have to revert the cobra bump in c/common, see https://github.com/containers/podman/pull/10841. The flag completion is completely broken, https://github.com/spf13/cobra/issues/1437

**Comment by vrothberg** [comment]
> Sorry @vrothberg, we have to revert the cobra bump in c/common, see #10841. The flag completion is completely broken, [spf13/cobra#1437](https://github.com/spf13/cobra/issues/1437)

Thanks for the pointer.  I will force cobra to `github.com/spf13/cobra v1.1.3` here in Podman.  I am sure that other dependencies want to bump it as well.

**Review by Luap99 — COMMENTED** [review]
LGTM

**Pull request merged**
