### PR TITLE
[v3.3] Bump c/storage to v1.34.1 and c/image to v5.15.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Bump c/storage to v1.34.1 and c/image to v5.15.1 for
Podman v3.3 rc3

[NO TESTS NEEDED]
[NO NEW TESTS NEEDED]

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@mheon @baude @rhatdan please merge when ready and then cut v3.3 rc3

**Comment by TomSweeneyRedHat** [comment]
UGH!  The one day I just need the CI to cooperate and note flake...  It's bit me twice already, one more to go.

**Comment by TomSweeneyRedHat** [comment]
I've restarted thet test

**Comment by TomSweeneyRedHat** [comment]
Unfortunately, I called it.  3rd flake of the day....

**Comment by TomSweeneyRedHat** [comment]
@mheon @rhatdan @baude all green test buttons, please merge me!

**Review by lsm5 — APPROVED** [review]
LGTM

**Pull request merged**
