### PR TITLE
sqlite: add a hidden --db-backend flag

### PR DESCRIPTION
**Pull request by vrothberg**
Add a hidden flag to set the database backend and plumb it into podman-info.  Further add a system test to make sure the flag and the info output are working properly.

Note that the test may need to be changed once we settled on how to test the sqlite backend in CI.

@baude @mheon PTAL

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
@Luap99 PTAL

**Comment by vrothberg** [comment]
@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
