### PR TITLE
Change Tests to ignore missing containers when removing --all

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/12740

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago PTAL

**Comment by Luap99** [comment]
@edsantiago Did you checked if all containers were deleted?

**Comment by edsantiago** [comment]
@Luap99 no, sorry. All I really care about is that there's no errors.

**Comment by Luap99** [comment]
Well if it does not remove anything it is dangerous and could hide real bugs

**Comment by mheon** [comment]
Concur - this seems like a real bug, and now we're just working around it.

**Comment by rhatdan** [comment]
The ignore only tells it to ignore container does not exist errors.  If this `podman rm --all --force --ignore` command succeeds all containers will be removed.

**Pull request merged**
