### PR TITLE
specgen: add support for ambient capabilities

### PR DESCRIPTION
**Pull request by giuseppe**
if the kernel supports ambient capabilities (Linux 4.3+), also set them when running with euid != 0.

This is different that what Moby does, as ambient capabilities are never set.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

Note that `podman top -l capamb` would also work for testing (or demos).

**Comment by zhangguanzhang** [comment]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
