### PR TITLE
[NO TESTS NEEDED] swagger: add missing schema properties

### PR DESCRIPTION
**Pull request by tmds**
@jwhonce ptal.

### CODE REVIEW

**Comment by tmds** [comment]
cc @baude

**Comment by zhangguanzhang** [comment]
thanks for contribute, and your commit messages should change to include `Sign-off-by $name ..` and `git push -f`

**Comment by zhangguanzhang** [comment]
Fixes: https://github.com/containers/podman/issues/8577

**Comment by rhatdan** [comment]
Do we need this change in all of the register_*go files?

**Comment by tmds** [comment]
> Do we need this change in all of the register_*go files?

@rhatdan I think this covers all needed cases. Do you have some specific section in mind that still should be patched?

Is this good to merge?

**Comment by rhatdan** [comment]
Could you repush to see if we get by the smoke test.

**Comment by baude** [comment]
I think thew NO_TESTS_NEEDED needs to be in the body of your commit message.  Speaking of which, can you provide a commit message?

**Comment by baude** [comment]
LGTM other than my comments about commit messages

**Comment by jwhonce** [comment]
@tmds Please let me know what tool you are using, or why you need these changes? I'm curious if we need to add that property to all our responses.

**Comment by tmds** [comment]
>  Please let me know what tool you are using, or why you need these changes? 

I'm using a .NET specific tool: https://github.com/RicoSuter/NSwag

Without the `schema` properties it considers the swagger invalid.
I'm not a swagger expert. Based on the docker swagger, and skimming through the swagger spec, I think the tool is probably right.

> I'm curious if we need to add that property to all our responses.

The other responses already include it, for example:
```yaml
  BadParamError:
    description: Bad parameter in request
    schema:
      properties:
        cause:
          description: API root cause formatted for automated parsing
          example: API root cause
          type: string
          x-go-name: Because
        message:
          description: human error message, formatted for a human to read
          example: human error message
          type: string
          x-go-name: Message
        response:
          description: http response code
          format: int64
          type: integer
          x-go-name: ResponseCode
      type: object

```

**Comment by tmds** [comment]
Is this good to merge?

**Comment by mheon** [comment]
Wait, CI is red
/hold

**Comment by mheon** [comment]
@tmds I think you need a force-push to make the [NO TESTS NEEDED] label work - I recommend changing something trivial (punctuation in a description, maybe) and force-pushing an amended commit

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by rhatdan** [comment]
@tmds Could you rebase your PR and repush, so that the tests will notice the [NO TESTS NEEDED] flag and we can get this in.

**Comment by tmds** [comment]
I've rebased.

**Pull request merged**
