### PR TITLE
Switch podman save default to oci-archive

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
podman save now defaults to oci-archive format.
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Tests fail.  Please also link to https://github.com/containers/podman/issues/21347.  It's a breaking change that requires context.

**Comment by mheon** [comment]
Feels like we should add a note to the manpage about the change ("The previous default, until Podman 5.0, was `docker-archive`" or something like that)

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
but the tests are still kicking hard.

**Comment by mtrmac** [comment]
This is not actually what we want.

Docker 25 is doing something more interesting: they are creating a single archive which is consumable _both_ as an OCI archive and as a traditional `docker-archive` (mostly? There are actually _two_ `docker-archive` formats, and IIRC the older one is conceptually incompatible with OCI, so the generated archive is probably OCI + “new” `docker-archive`)

Creating such a hybrid archive in `podman save` would be interesting. Just switching to OCI would make the output no longer compatible with old `docker load`, and thus not in line with the Podman/Docker CLI compatibility ambition.

**Comment by rhatdan** [comment]
Ok will close, no time to investigate that change.

**Pull request closed without merging**
