### PR TITLE
cleanup: always delete netns mount

### PR DESCRIPTION
**Pull request by Luap99**
We should not keep the netns if there was a cleanup problem. Deleting the netns will also delete the virtual links inside and thus make the IPs available again for the next use.

context: https://github.com/containers/netavark/issues/302

[NO NEW TESTS NEEDED] This is very hard to trigger reliable and it would need to work with cni and netavark. This mostly happens because of specic bugs but those will be fixed and then this test would fail.

#### Does this PR introduce a user-facing change?

```release-note
The network namespace cleanup is now always removed even when the network teardown in CNI/netavark fails.
```

### CODE REVIEW

**Comment by Luap99** [comment]
@mheon PTAL

**Comment by Luap99** [comment]
Note for myself we need to take a look at those `*cni*` function names and rename them to better match the actual business logic.

**Comment by mheon** [comment]
LGTM

**Pull request merged**
