### PR TITLE
Get masked paths and readonly masked patchs from containers/common @rhatdan

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rhatdan still fighting the red test marks here.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL
@Luap99 @vrothberg @umohnani8 @ashley-cui PTAL

**Comment by mheon** [comment]
LGTM

**Pull request merged**
