### PR TITLE
Vendor in latest containers/common

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @mtrmac PTAL, brings in fixes for zstd:chunked testing.

**Comment by mtrmac** [comment]
LGTM … alternatively I can just incorporate this in #21571, and verify there.

**Comment by Luap99** [comment]
seeing a bunch of hyperV errors @baude 
```
Error: stat /Users/ADMINI~1/AppData/Local/Temp/podman_test2607210929: stat /Users/ADMINI~1/AppData/Local/Temp/podman_test2607210929: no such file or directory
```

I would guess this is due the default volume change in c/common, not sure if this is a bug in the test setup or something broken in the code.

**Comment by mheon** [comment]
https://github.com/containers/podman/pull/21572 might fix

**Comment by mheon** [comment]
Scratch that, will fix.

**Pull request closed without merging**
