### PR TITLE
Convert SpecGen values to be nullable where possible

### PR DESCRIPTION
**Pull request by mheon**
SpecGen is our primary container creation abstraction, and is used to connect our CLI to the Libpod container creation backend. Because container creation has a million options (I exaggerate only slightly), the struct is composed of several other structs, many of which are quite large.

The core problem is that SpecGen is also an API type - it's used in remote Podman. There, we have a client and a server, and we want to respect the server's containers.conf. But how do we tell what parts of SpecGen were set by the client explicitly, and what parts were not? If we're not using nullable values, an explicit empty string and a value never being set are identical - and we can't tell if it's safe to grab a default from the server's containers.conf.

Fortunately, we only really need to do this for booleans. An empty string is sufficient to tell us that a string was unset (even if the user explicitly gave us an empty string for an option, filling in a default from the config file is acceptable). This makes things a lot simpler. My initial attempt at this changed everything, including strings, and it was far larger and more painful.

Also, begin the first steps of removing all uses of containers.conf defaults from client-side. Two are gone entirely, the rest are marked as remove-when-possible.

Marking as release note none for now, because this may not actually be a breaking change to our API, given how lenient Go's JSON parsing has always been.

[NO NEW TESTS NEEDED] This is just a refactor.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by martinpitt** [comment]
The cockpit failure here is much less severe than in #21308. 

> wait_js_cond(ph_in_text(".pf-v5-c-alert","address already in use")): actual text: Danger alert:Container failed to be created Error message: Internal Server Error: invalid config provided: invalid ImageVolumeMode "bind", value must be one of ignore,tmpfs,anonymous 

This test creates a first container with exposing port 5000 on the CLI (` -p 5000:5000`) and then tries to create a container in the UI with also exposing port 5000, and expects that "address already in use" error message. Instead it fails with that curious one -- `bind` should certainly be a valid volume mode, and it does work in other cases as well?

Is that enough for you to spot the error, or do you need a `curl` reproducer?

**Comment by mheon** [comment]
Vendored our updated c/common

**Comment by baude** [comment]
/lgtm

hold is already present

**Pull request merged**
