### PR TITLE
doc: fix words repetitions

### PR DESCRIPTION
**Pull request by M5oul**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
You need to sign off your commit, see https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs

**Comment by M5oul** [comment]
Thanks, I missed this part.
That’s a long contribution guide to read for the first time. I stopped with the [pointed §](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#submitting-pull-requests).

**Comment by Luap99** [comment]
The DCO check is still failing because your git commit author field does not match the sign off line. The sign off line is fine but the author filed should match, you can update it via
`git commit --amend --author="Author Name <email@address.com>" --no-edit`
Generally if you have set the right user and email fields for the git commit it should just work going forward. Anyway I can manually set the DCO check to passing if you do not want to update this which is also fine.

**Review by Luap99 — APPROVED** [review]
/lgtm

Thank you

**Pull request merged**
