### PR TITLE
DO NOT MERGE: Vendor https://github.com/containers/storage/pull/1407

### PR DESCRIPTION
**Pull request by mtrmac**
Signed-off-by: Miloslav Trmač <mitr@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Improves resiliency against interrupted image pulls.
```

### CODE REVIEW

**Comment by mtrmac** [comment]
In system tests, seeing
```
ok 333 podman corrupt images - cleanup
[+1206s] not ok 334 podman container storage is not accessible by unprivileged users
         # (from function `die' in file test/system/[helpers.bash, line 594](https://github.com/containers/podman/blob/51df93b6fa50a329a365468e134c22aebaa87285/test/system/helpers.bash#L594),
         #  from function `run_podman' in file test/system/[helpers.bash, line 214](https://github.com/containers/podman/blob/51df93b6fa50a329a365468e134c22aebaa87285/test/system/helpers.bash#L214),
         #  in test file test/system/[400-unprivileged-access.bats, line 14](https://github.com/containers/podman/blob/51df93b6fa50a329a365468e134c22aebaa87285/test/system/400-unprivileged-access.bats#L14))
         #   `run_podman run --name c_uidmap   --uidmap 0:10000:10000 $IMAGE true' failed
         # # podman rm -t 0 --all --force --ignore
         # # podman ps --all --external --format {{.ID}} {{.Names}}
         # # podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
         # quay.io/libpod/testimage:20221018 fb12c9a035c2
         # # podman run --name c_uidmap --uidmap 0:10000:10000 quay.io/libpod/testimage:20221018 true
         # Error: open /etc in the container: no such file or directory
```
and one more in `not ok 372 podman run /etc/* permissions` .

**Comment by edsantiago** [comment]
/me checks his world clock. Rubs eyes, checks again.

Are you fully rebased on main? This smells a little like #15698 and #15977,  which I reluctantly workarounded in #15981.

**Comment by mtrmac** [comment]
@edsantiago Thanks, I found one of those. I do think this was built after #15981, and anyway I have just pushed a rebase on current `main.

It’s very possible that this truly broken storage, a bug in my work.

**Comment by mtrmac** [comment]
The c/storage PR was merged.

**Pull request closed without merging**
