### PR TITLE
[WIP] vendor in secrets pkg

### PR DESCRIPTION
**Pull request by ashley-cui**
Signed-off-by: Ashley Cui <acui@redhat.com>

### CODE REVIEW

**Comment by ashley-cui** [comment]
@rhatdan here's the vendored wip secrets package

**Comment by rhatdan** [comment]
I don't see any functions that use the secrets?

I was hoping to see how this would work with Podman.

podman run --secret=....

**Comment by rhatdan** [comment]
podman build --secret

**Comment by ashley-cui** [comment]
@rhatdan ah, i'm still working on that ..

**Pull request closed without merging**
