### PR TITLE
Copy past golang/expansion form ks8.io/kubernetes

### PR DESCRIPTION
**Pull request by BlackHole1**
Stop depending on `k8s.io/kubernetes`. The upstream code is super stable, so there is little harm to copy it here.

Ref: https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-505627280

Close: #20806 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — CHANGES_REQUESTED** [review]
I don't see any reason to not use that package directly, this was discussed in https://github.com/containers/podman/pull/19630 and were were fine with using only iy.

Copying means we have to manually update it every time it changes and there is little point in doing that work if we can just have this dep. As long as it works it works and we can worry about it if it breaks at some point or causes unnecessary bloat.

**Comment by giuseppe** [comment]
@BlackHole1 why are you suggesting this?  What is the advantage?

**Comment by BlackHole1** [comment]
The reason for this modification is because I encountered an error while using [Goland IDE](https://www.jetbrains.com/go/). When opening a project with Goland IDE, it automatically runs the command: `go list -modfile=./go.mod -m -json -mod=mod all`, which results in the following error:



> Copying means we have to manually update it every time it changes

I don’t think there is any need to worry about this. The source code was originally written in Golang and then copied by Kubernetes. Moreover, this source code has not been modified for 7 years. So, I believe it is already stable enough. The same goes for the following projects:

1. https://github.com/labring/sealos/blob/fd55bac/fork/golang/expansion/expand.go
2. https://github.com/apecloud/kubeblocks/blob/main/pkg/common/expand.go
3. https://github.com/virtual-kubelet/virtual-kubelet/blob/master/internal/expansion/expand.go
4. https://github.com/uber/peloton/blob/master/pkg/jobmgr/util/expansion/expand.go
5.

**Comment by giuseppe** [comment]
@Luap99 Given that the version in the k8s repository is copied from Golang and these libraries are not meant to be used as modules, perhaps it is not a bad idea to copy this file

**Comment by giuseppe** [comment]
> I still do not see the benefit of that? I Am not sure what the go command does or why it tries to parse dependencies we do not have.

seems to be a known problem with kubernetes: https://suraj.io/post/2021/05/k8s-import/

The alternative is to clobber the go.mod file with a bunch of replaces.

from https://github.com/kubernetes/kubernetes#to-start-using-k8s:

> To use Kubernetes code as a library in other applications, see the [list of published components](https://git.k8s.io/kubernetes/staging/README.md). Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported.

**Comment by BlackHole1** [comment]
Maybe we need someone else to vote?

**Comment by baude** [comment]
ive seen it in goland too @BlackHole1 ... but i have been ignoring it.  What is the downside of those in the the IDE?  Does something not work or is this more related to cleanliness?  (this is a genuine question)

**Comment by BlackHole1** [comment]
@baude After testing, if go list fails, some features related to dependency management in Goland will be disabled. For example, [dependency update](https://www.jetbrains.com/help/go/create-a-project-with-go-modules-integration.html#updating-dependencies-in-go-mod) and others. It will not affect critical features such as project indexing.

Personally, I rarely use dependency update, but this error is really annoying… So I still hope this PR will be merged.

**Comment by sanmai-NL** [comment]
Rather than copying data, if you want to fix this at all, perform a Git partial clone or add it as a submodule.

**Comment by giuseppe** [comment]
> Rather than copying data, if you want to fix this at all, perform a Git partial clone or add it as a submodule.

I think the proposed PR is better.  We are not using git submodules in Podman so this will complicate things.  It possibly breaks any user just pulling from the podman repository and building it since we'd need another git command to pull the missing pieces.

**Comment by sanmai-NL** [comment]
@giuseppe 

> By default, the git pull command recursively fetches submodules changes

https://git-scm.com/book/en/v2/Git-Tools-Submodules

Managing implicit dependencies through vendoring brings its own (invisible) complexity.

**Comment by giuseppe** [comment]
> @giuseppe
> 
> > By default, the git pull command recursively fetches submodules changes
> 
> https://git-scm.com/book/en/v2/Git-Tools-Submodules
> 
> Managing implicit dependencies through vendoring brings its own (invisible) complexity.

right, but in this case we are copying the file

**Comment by rhatdan** [comment]
@BlackHole1 Please rebase and then we can get this merged.

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by BlackHole1** [comment]
ping @rhatdan

**Comment by rhatdan** [comment]
/lgtm
Thanks @BlackHole1

**Pull request merged**
