### PR TITLE
Update vendor of containers/buildah and friends

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Tests are red, otherwise LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, if you can smooth out the test redness.

**Comment by flouthoc** [comment]
@rhatdan Test is failing because version `5.20` was cut before this was merged https://github.com/containers/image/pull/1480 , so release `5.20` is missing this PR and hence it reverts back to racy `c/image`. 

I think we must release a new `c/image` before it can be vendor-ed into podman or `c/image`.

**Comment by vrothberg** [comment]
> I think we must release a new c/image before it can be vendor-ed into podman or buildah.

No need for a release.  Just `go get github.com/containers/image/v5@$desiredCommit`.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Review by flouthoc — COMMENTED** [review]
Oh it seems new diff for https://github.com/containers/podman/blob/main/test/buildah-bud/buildah-tests.diff  needs to be generated.

**Comment by rhatdan** [comment]
@flouthoc Since I am on PTO this week, do you want to take this one over?

**Comment by flouthoc** [comment]
Sure. I'll take over this.

**Comment by flouthoc** [comment]
@rhatdan Please feel free to close this PR i'll open a new one to vendor everything into podman.

**Pull request closed without merging**
