### PR TITLE
api: add `compatMode` parameter to libpod's pull endpoint

### PR DESCRIPTION
**Pull request by vrothberg**
Add a new `compatMode` parameter to libpod's pull endpoint. If set, the
streamed JSON payload is identical to the one of the Docker compat
endpoint and allows for a smooth integration into existing tooling such
as podman-py and Podman Desktop, some of which already have code for
rendering the compat progress data.

We may add a libpod-specific parameter in the future which will stream
differnt progress data.

Fixes: issues.redhat.com/browse/RUN-1936?
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Add a new `compatMode` parameter to libpod's pull endpoint. If set, the streamed JSON payload is identical to the one of the Docker compat endpoint.
```

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
Should `podman --remote pull` set this flag?

**Comment by vrothberg** [comment]
> Should `podman --remote pull` set this flag?

No.  There is absolutely no code to render it on the client side.  That's something we still need to figure out.

**Comment by baude** [comment]
thanks @vrothberg 

/lgtm

**Pull request merged**
