### PR TITLE
build: don't set `contextDir` when path to `Containerfile` is directory

### PR DESCRIPTION
**Pull request by flouthoc**
Following PR ensures that podman does not sets wrong context when path
to containerfile is a directory.

[NO NEW TESTS NEEDED]
[NO TESTS NEEDED]
This does not adds a feature instead disables one and test for this will be added in buildah at lower level.
Tests for this here: https://github.com/containers/buildah/pull/4096

Example use-case should not work
```Console
podman build -f ./
```
Closes: https://github.com/containers/podman/issues/14836

#### Does this PR introduce a user-facing change?

```release-note
build: podman will populate contextdir if path to container file is a directory and instead will error out
```

### CODE REVIEW

**Comment by vrothberg** [comment]
> podman build -f ./

That breaks on Docker and I think it should break on Podman as well as I find it counterintuitive that `--file` could resolve to a directory.

**Comment by flouthoc** [comment]
> > podman build -f ./
> 
> That breaks on Docker and I think it should break on Podman as well as I find it counterintuitive that `--file` could resolve to a directory.

SGTM if we want to drop this support I can amend the PR to disable this feature but this was already a working feature don't know when was this added maybe from the start, could dropping support for this break old users ?

**Comment by vrothberg** [comment]
When did `podman build -f ./` work?

**Comment by flouthoc** [comment]
> When did `podman build -f ./` work?

I must be missing something but from upstream when i do it works but just sets wrong context and on `buildah` it even sets the correct context. But i think similar scenario is already replayed in this issue: https://github.com/containers/podman/issues/14836

```dockerfile
FROM alpine
RUN echo hello
```
```console
podman build -f ./
STEP 1/2: FROM alpine
STEP 2/2: RUN echo hello
--> Using cache ef296be9c1bb5c36830ab5a1f7da21329ed77ee678c33b0f31221ba7605a56f2
--> ef296be9c1b
ef296be9c1bb5c36830ab5a1f7da21329ed77ee678c33b0f31221ba7605a56f2
```
works but just sets the wrong build context and on `buildah` even context is configured correctly.

**Comment by vrothberg** [comment]
@nalind @rhatdan WDYT?

**Comment by nalind** [comment]
If someone passes a directory to a flag that expects a file, go ahead and treat it as an error.  Trying to be more flexible than `docker build` about the locations we're given has gotten us corner case after corner case.

**Comment by flouthoc** [comment]
Will error out and test this at imagebuildah where this feature was actually added: https://github.com/containers/buildah/pull/4096
Following PR would just ensure that podman does not populates **wrong** context dir for provided use-case and buildah will eventually decide if this will error out or not.

**Comment by rhatdan** [comment]
LGTM, but it would be better to just vendor in the fixed buildah code?

**Comment by flouthoc** [comment]
Closing this since https://github.com/containers/buildah/pull/4096 is merged at a lower level.

**Pull request closed without merging**
