### PR TITLE
Cirrus: Use Fedora 34beta images

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@giuseppe do you know if something in F34 kernel/crun [change that would cause `--blkio-weigh` behavior to change w/ CgroupsV2?](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4793455495872512/html/int-podman-fedora-34beta-root-host.log.html#t--podman-run-blkio-weight-test--1).  I went into one of the new VMs and checked:

```
[root@cevich-fedora-c4917211555954688 podman]# stat -f -c %T /sys/fs/cgroup
cgroup2fs
```

Even running the command manually, seems to give an unexpected value:

```
[root@cevich-fedora-c4917211555954688 podman]# podman run --rm quay.io/libpod/alpine:l
atest sh -c 'cat /proc/self/cgroup'
0::/
[root@cevich-fedora-c4917211555954688 podman]# podman run --rm --blkio-weight=15 quay.
io/libpod/alpine:latest sh -c 'cat /sys/fs/cgroup/io.bfq.weight'
default 15
```

The test expects that value to scale to `51` :confused:

**Comment by vrothberg** [comment]
@cevich, could we break out the updates to the F33 images?  I need them fetch updates to libcap to make certain PRs pass.

**Comment by giuseppe** [comment]
@cevich is this PR still needed?

**Comment by cevich** [comment]
> @cevich is this PR still needed?

Yes, I'm periodically running tests to try and keep ahead of the F34 release and expose problems in our testing.  In fact I could use help digging through the failures to see what adjustments are needed in the VM Image build PR: https://github.com/containers/automation_images/pull/49

**Comment by cevich** [comment]
@vrothberg any idea why [your unitterst is segfaulting on F34b?](https://cirrus-ci.com/task/6726636918800384?command=main#L1407)

Hint: There ***really*** isn't any TTY available :grin: 

Anything I can do to help fix this?

**Comment by vrothberg** [comment]
> @vrothberg any idea why [your unitterst is segfaulting on F34b?](https://cirrus-ci.com/task/6726636918800384?command=main#L1407)

Thanks for the ping.

They are segfaulting because the tests are sloppy (i.e., errors should be treated fatal).  It's erroring because F34 is now in enforcing mode (see `man containers-registries.conf`).

> Hint: There _**really**_ isn't any TTY available grin
> 
> Anything I can do to help fix this?

I'll wrap up a PR.  Just to set expectations: I expect more tests to fail because of the enforcement. (Cc: @rhatdan)

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/9800

**Comment by vrothberg** [comment]
A rebase onto HEAD will get us a big step forward.

**Comment by cevich** [comment]
(waiting for new images to finish building)

**Comment by rhatdan** [comment]
LGTM
/approve

**Comment by cevich** [comment]
@containers/podman-maintainers PTAL - The currently running tests are confirming the latest (3-29-21) nightly F34b image + Ubuntu 20.10 updates for crun and libcap2 for @lsm5.  Assuming tests remain green (they should) feel free to merge.

**Comment by cevich** [comment]
[F33 failure `[Fail] Podman run with volumes [It] podman run with volumes and suid/dev/exec options` ](https://cirrus-ci.com/task/6143951188000768) seems genuine :cry: I'm able to reproduce it manually, using the container image `quay.io/libpod/prior-fedora_podman:c6526331153285120` (run in privileged mode).

The only thing I changed was in the `Makefile`:

```diff
diff --git a/Makefile b/Makefile
index 7bed7f5dd..f6212351c 100644
--- a/Makefile
+++ b/Makefile
@@ -307,7 +307,7 @@ test: localunit localintegration remoteintegration localsystem remotesystem  ##

 .PHONY: ginkgo-run
 ginkgo-run:
-       $(GOBIN)/ginkgo -v $(TESTFLAGS) -tags "$(TAGS)" $(GINKGOTIMEOUT) -cover -flakeAttempts 3 -progress -trace -noColor -nodes 3 -debug test/e2e/. $(HACK)
+       $(GOBIN)/ginkgo -v $(TESTFLAGS) -tags "$(TAGS)" $(GINKGOTIMEOUT) -cover -flakeAttempts 3 -progress -trace -noColor -nodes 3 -focus='podman run with volumes and suid' -debug test/e2e/. $(HACK)

 .PHONY: ginkgo
 ginkgo:
```

The problem does *not* appear to be happening on master, so it seems the problem could be related to the new images.

**Comment by cevich** [comment]
[Oof, new VM images, same error.](https://cirrus-ci.com/task/4640154959740928)

@mheon should this 'Podman run with volumes [It] podman run with volumes and suid/dev/exec options ' test even be running inside a container environment?

**Comment by cevich** [comment]
Update: As of this comment, the necessary `crun-0.18-5` package just moved to stable but is not yet available in the `updates` repo.  I'll try again tomorrow, then *fingers-crossed* this PR will be ready to go.

**Comment by cevich** [comment]
@containers/podman-maintainers PTAL *quick* while the tests are green :grin: 

Note: I did need to re-run a few system tests, otherwise things have been passing cleanly.  These images also include @baude golang speed-mode changes for Ubuntu.

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
