### PR TITLE
[CI:DOCS] podman-info.1.md: update examples (now also shell completion and jq)

### PR DESCRIPTION
**Pull request by eriksjolund**
* Add example "Extracting the list of container registries with a Go template".
  (The example was already present but in a much shorter form)

* Add example "Extracting the list of container registries from JSON with jq".

* Add shell completion instructions

Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by eriksjolund** [comment]
The extra newline in the end of the output
```
 $ podman info -f '{{range index .Registries "search"}}{{.}}\n{{end}}'
 registry.fedoraproject.org
 registry.access.redhat.com
 docker.io
 quay.io

 ```
is a bit unfortunate.

**Comment by vrothberg** [comment]
> The extra newline in the end of the output [...] is a bit unfortunate.

Would you open an issue or (even better) a PR for it?

**Review by vrothberg — APPROVED** [review]
/lgtm
Thanks a lot!

**Comment by eriksjolund** [comment]
> > The extra newline in the end of the output [...] is a bit unfortunate.
> 
> Would you open an issue or (even better) a PR for it?

I created an issue
* https://github.com/containers/podman/issues/14888

**Pull request merged**
