### PR TITLE
journald: podman events only show events for current user

### PR DESCRIPTION
**Pull request by Luap99**
I noticed this while running some things in parallel, podman events
would show events from other users. Because all events are written to
the journal everybody can see them. So when we read the journal we must
filter events for only the current UID.

To reproduce run `podman events` as user then in another window create a
container as root for example. After this patch it will correctly ignore
these events from other users.

[NO NEW TESTS NEEDED] I don't think we can test with two users at the same
time.

journald: podman logs only show logs for current user

In the super rare case that there are two containers with the same ID
for two different users, podman logs with the journald driver would show
logs from both containers.

[NO NEW TESTS NEEDED] Impossible to reproduce.

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where podman events with the journald driver could show events from other users.
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Review by vrothberg — COMMENTED** [review]
Nice catch!

**Comment by larry-cable** [comment]
should podman events *not* support the ability for a superuser to obtain events for *all* current activity independent of user identity?

**Comment by vrothberg** [comment]
> should podman events _not_ support the ability for a superuser to obtain events for _all_ current activity independent of user identity?

That's not on the roadmap.  A superuser can query the journal (e.g., via journalctl) to see the events of all user on the system (including Podman events).

**Pull request merged**
