### PR TITLE
[CI:DOCS] Remove dead link from README

### PR DESCRIPTION
**Pull request by cgiradkar**
The link for podman-hello.png was replaced with a textual representation but a dangling pointer to dead link was still present. This PR removes the dead link to avoid hitting 404

closes [#168](https://github.com/containers/podman.io/issues/168)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by cgiradkar** [comment]
@TomSweeneyRedHat I have added a tag of `closes` to the PR top description, but that number is from podman.io issues page, not sure if the bot will close podman bug by the same number, could you please clarify?

**Comment by TomSweeneyRedHat** [comment]
Looks like the bot was happy to nuke the issue on podman.io, at least it's closed at this point.

**Pull request merged**
