### PR TITLE
Bump to v4.1.0

### PR DESCRIPTION
**Pull request by mheon**
As the title says.

### CODE REVIEW

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

**Comment by jwhonce** [comment]
LGTM

**Comment by Luap99** [comment]
Why is this CI:DOCS when it contains actual code?

**Comment by mheon** [comment]
Because I wasn't thinking straight when I made it. Removing CI:DOCS

**Comment by mheon** [comment]
/hold

Total success is failing. Unclear why.

**Comment by mheon** [comment]
Seems completely stalled. @cevich Mind taking a look when you get in tomorrow morning?

**Comment by rhatdan** [comment]
The issue is the `APIVersion: 4.1.1-dev` I think the last PR should be removed, from a branch.
https://github.com/containers/podman/pull/14132/commits/3b4de8efc33d3eba4c4f280487f5d9eacb852da4

**Comment by Luap99** [comment]
The release test is optional we can just ignore it.

**Comment by mheon** [comment]
Oh, total success actually succeeded overnight, apparently?

Let me whack this in, then.

**Comment by cevich** [comment]
> Seems completely stalled. @cevich Mind taking a look when you get in tomorrow morning?

Sure...This appears to be Cirrus-CI infrastructure-related since the success task runs in a container on the community-cluster.  I've seen [this and similar, seemingly autoscale related issues](https://github.com/containers/podman/pull/14075#issuecomment-1118630417).  I'm sure Cirrus support is aware of excessive task scheduling times, they're certainly abnormal.  If it becomes a really bad problem, we have the option of using (and paying for) our own GKE cluster to execute container tasks in.

> The release test is optional we can just ignore it.

Please do be careful/mindful/deliberate when ignoring this.  This check is intended to catch accidental release of a `-dev` version - which does happen from time to time still :confused: Nevertheless, the **REALLY** important execution of this check happens on the actual tag-push CI-run, [which did pass](https://github.com/containers/podman/runs/6323738789).

**Comment by Luap99** [comment]
> > The release test is optional we can just ignore it.
> 
> Please do be careful/mindful/deliberate when ignoring this. This check is intended to catch accidental release of a `-dev` version - which does happen from time to time still confused Nevertheless, the **REALLY** important execution of this check happens on the actual tag-push CI-run, [which did pass](https://github.com/containers/podman/runs/6323738789).

Of course but how can this check ever pass on this PR if there are always commits after the actual release commit? So this should be ignored.

**Comment by cevich** [comment]
This is true, and why it's optional.  The intent is to trigger it when the (tagged) bump commit is pushed, but not for anything afterward.  TBH, I'd live for someone to go in and update the check to handle this better, perhaps by checking if `$CIRRUS_PR` is non-empty, and only check the "correct" commit from the PR (I think it's always the second one).

**Pull request merged**
