### PR TITLE
Add missing return after utils.InternalServerError()

### PR DESCRIPTION
**Pull request by eriksjolund**
#### Does this PR introduce a user-facing change?

```release-note
None
```
[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by eriksjolund** [comment]
### possible addition

In the PR I excluded this candidate patch as I'm a bit uncertain about it.


At first sight it looks strange to see the success message `      logrus.Debugf("Attach for container %s completed successfully", ctr.ID())`   after an error has occurred.




``` diff
--- a/pkg/api/handlers/compat/containers_attach.go
+++ b/pkg/api/handlers/compat/containers_attach.go
@@ -95,28 +95,30 @@ func AttachContainer(w http.ResponseWriter, r *http.Request) {
        }
 
        logErr := func(e error) {
                logrus.Errorf("Error attaching to container %s: %v", ctr.ID(), e)
        }
 
        // Perform HTTP attach.
        // HTTPAttach will handle everything about the connection from here on
        // (including closing it and writing errors to it).
        hijackChan := make(chan bool, 1)
        err = ctr.HTTPAttach(r, w, streams, detachKeys, nil, query.Stream, query.Logs, hijackChan)
 
        if <-hijackChan {
                // If connection was Hijacked, we have to signal it's being closed
                t := r.Context().Value(api.IdleTrackerKey).(*idle.Tracker)
                defer t.Close()
 
                if err != nil {
                        // Cannot report error to client as a 500 as the Upgrade set status to 101
                        logErr(err)
+                       return
                }
        } else {
                // If the Hijack failed we are going to assume we can still inform client of failure
                utils.InternalServerError(w, err)
                logErr(err)
+               return
        }
        logrus.Debugf("Attach for container %s completed successfully", ctr.ID())
 }
```

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by rhatdan** [comment]
I believe you need the [NO NEW TESTS NEEDED] added, which I added, but you will need to repush.

**Comment by eriksjolund** [comment]
First time the test failed rather quickly. Then I added to
```
 [NO NEW TESTS NEEDED] 
```
to the commit message and repushed. This time the tests are running without failing (it seems)

Let's see if I need to repush again.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by Luap99** [comment]
Well ideally we would add a test for this and not `[NO NEW TESTS NEEDED]`, unless there is actually a reason why this cannot be tested. I know it makes things harder for contributors but without regression tests we often break again in the future.

But more importantly we should really look into writing a custom linter/check for this, we are clearly unable to spot this in code review.

**Comment by eriksjolund** [comment]
I searched around and found this file

https://github.com/containers/podman/blob/main/test/apiv2/40-pods.at

Is that the file where to add a test?

Regarding  _custom linter/check_, maybe moving around `return` would make it easier to use a regexp:

Just an example 
``` diff
                 if errors.Is(err, storage.ErrImageUnknown) {
                         utils.ImageNotFound(w, name, fmt.Errorf("failed to find image %s: %w", name, err))
+                        return
                 } else {
                         utils.Error(w, http.StatusInternalServerError, err)
+                        return
                 }
-                return
+
 		
```
Such an edit makes the code less beautiful but maybe it's worth the cost.

**Comment by vrothberg** [comment]
> Is that the file where to add a test?

Yes, that would be good place to add it.

**Comment by eriksjolund** [comment]
I added a test. 
(I'm not sure what `.cause=` is used for so I just reused the `.message=`)

**Comment by TomSweeneyRedHat** [comment]
The remote debian-12 root host boltdb test timedout, I restarted.

**Review by vrothberg — APPROVED** [review]
LGTM
restarted another time :heavy_check_mark:

**Pull request merged**
