### PR TITLE
e2e: GetPort(): never reuse ports

### PR DESCRIPTION
**Pull request by edsantiago**
Intended to fix an obscure, unlikely race condition in which (I
think) two parallel jobs called GetPort() and were assigned
the same port.

[test log](https://api.cirrus-ci.com/v1/artifact/task/5857246123393024/html/int-podman-debian-12-root-host-sqlite.log.html#t--podman-search-doesnt-attempt-HTTP-if-registry-is-not-listed-as-insecure--1)

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by Luap99 — CHANGES_REQUESTED** [review]
This is not working/doing what you expect.
We run ginkgo in parallel mode which means each node is its own process -> own memory space. Therefore your map isn't shared at all between parallel running tests.

Second, we should really bind any ip here and not just localhost as the test also bind any address.

**Comment by edsantiago** [comment]
@Luap99 is this better? I followed the mutex convention used in `processTestResult()`. 

I am deliberately not addressing your second comment ("not just localhost") because I don't see the use case.

**Comment by Luap99** [comment]
Unless you use something with inter process communication it is not going to work in parallel testing, processTestResult is only storing stuff for the single process, i.e. we can actually drop the mutex there: https://github.com/containers/podman/pull/18163/commits/5eb99a0ac88a6d65d11d307c87043f42b0df07be

One way would be to write files into a shared dir, see `LockTmpDir`.
But maybe the better way is to drop this at all do not use some free random from the `/proc/sys/net/ipv4/ip_local_port_range` like it does right now. These ports are bound dynamically by processes which makes conflicts more likely then lets say bind some port below that.

So I would say it is better to follow what we do in the system tests. Pick a random port in some fixed range (e.g. 5000-6000) then test if it is free then use it. To prevent the TOCTOU race between the parallel ginkgo processes the port should fulfil the condition `port % GinkgoT().ParallelTotal() == GinkgoT().ParallelProcess() - 1` (ParallelProcess is 1-indexed so we need to subtract one)

**Comment by edsantiago** [comment]
Closing in favor of #18769

**Pull request closed without merging**
