### PR TITLE
play kube: notifyproxy: listen before starting the pod

### PR DESCRIPTION
**Pull request by vrothberg**
Starting listening for the READY messages on the sdnotify proxies before starting the Pod.  Otherwise, we may be missing messages.

[NO NEW TESTS NEEDED] as it's hard to test this very narrow race.

Related to but may not be fixing #16076.

Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Fix a potential race condition in play kube's sdnotify support.
```

### CODE REVIEW

**Comment by vrothberg** [comment]
Needs more work.  I'll tackle that tomorrow.

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL

**Review by ashley-cui — COMMENTED** [review]
/lgtm

**Comment by lsm5** [comment]
@edsantiago guess this needs to be cherrypicked to v4.3? I can add this as a patch to the rpm

**Pull request merged**
