### PR TITLE
Machine decompress.go refactoring follow-up

### PR DESCRIPTION
**Pull request by l0rd**
⚠️ This PR is based on #21592 but with a broader impact:
 - local `xz` implementation removed and implementation from `c/image` used (for consistency with other compressors)
 -  the decompression implementation is independent from the OS (no
 - SparseWriter is always used on macOS (not on other platforms) 
 
This PR should also fix https://github.com/containers/podman/issues/21772

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by mtrmac — COMMENTED** [review]
The implementation mechanism LGTM.

I’ll defer to `machine` experts as to whether removing the external `xz` decompression path is worth worrying about.

**Comment by Luap99** [comment]
@baude @mheon @ashley-cui PTAL

**Comment by mheon** [comment]
LGTM, but I'd like an ack from @baude before merging is considered

**Comment by l0rd** [comment]
There are 6 Cirrus CI failing.

<details>

<summary>bud remote fedora-39 root host sqlite</summary>

```
Error: creating build container: copying system image from manifest list: reading blob sha256:2c2d948710f21ad82dce71743b1654b45acb5c059cf5c19da491582cef6f2601: fetching blob: received unexpected HTTP status: 502 Bad Gateway
```
</details>
<details>

<summary> int remote rawhide root host sqlite</summary>

```
Error: initializing source docker://quay.io/libpod/cirros:latest: can't talk to a V1 container registry
```

```
Error: copying system image from manifest list: determining manifest MIME type for docker://quay.io/libpod/cirros:latest: reading manifest sha256:c7d58d6d463247a2540b8c10ff012c34fd443426462e891b13119a9c66dfd28a in quay.io/libpod/cirros: received unexpected HTTP status: 502 Bad Gateway
```

</details>
<details>

<summary>sys podman debian-13 rootless host sqlite</summary>

```
# 	* updating image for container 19eae661009f8dd5151d1fd67c906b51e870bfcdebab31ba98acc5dac25abea3: initializing source docker://quay.io/libpod/alpine:latest: can't talk to a V1 container registry
# 	* checking image updates for container 80605c476f439022d0a441d398a45e2ec0bf37be4196e4686e967db53a9615db: reading manifest latest in quay.io/libpod/busybox: received unexpected HTTP status: 502 Bad Gateway
```
</details>
<details>

<summary>sys podman rawhide root host sqlite</summary>

```
# Error: updating image for container 40d75534a0ae254277b96c99d253444caaa9964c51da08f3aea7d667bd69d97d: initializing source docker://quay.io/libpod/alpine:latest: can't talk to a V1 container registry
```
</details>

At first look those failures don't seam related to this PR.

I am going to rebase it to re-trigger the tests 🤞

**Comment by Luap99** [comment]
@l0rd Yes these are your normal share of registry/network flakes, given so many tests have to pull images in some form we notice quickly if quay.io has some problems.

**Comment by Luap99** [comment]
@baude This is waiting on you.

**Comment by Luap99** [comment]
> > @l0rd Yes these are your normal share of registry/network flakes, given so many tests have to pull images in some form we notice quickly if quay.io has some problems.
> 
> @Luap99 thank you for looking at it. After rebasing I still have a (different) test failing. It doesn't seem related to this PR though but it's kind of cryptic (is there a logformatter for packit-dev tests?):
> 
> ```
> > warning: Failed to update container stats: "Your session has been terminated."
> > log: {"problem":"terminated","message":"Your session has been terminated."}
> CDP: {"source":"other","level":"warning","text":"XrayWrapper denied access to property \"toString\" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.","timestamp":1710289306538,"url":"chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs","lineNumber":50}
> > warning: IncompleteRead(0 bytes read)
> > warning: IncompleteRead(0 bytes read)
> > warning: Failed to update container stats: "Your session has been terminated."
> > log: {"problem":"terminated","message":"Your session has been terminated."}
> Connection to 127.0.0.1 closed by remote host.
> 
> > warning: transport closed: disconnected
> Exiting due to channel error.
> Exiting due to channel error.
> Exiting due to channel error.
> Exiting due to channel error.
> Exiting due to channel error.
> Traceback (most recent call last):
>   File "/var/ARTIFACTS/work-podman-systemugyvyr9u/plans/cockpit-podman/podman-system/discover/default-0/tests/test/check-application", line 432, in testBasicSystem
>     self._testBasic(True)
>   File "/var/ARTIFACTS/work-podman-systemugyvyr9u/plans/cockpit-podman/podman-system/discover/default-0/tests/test/check-application", line 636, in _testBasic
>     b.click(hello_sel + " .pf-v5-c-menu-toggle")
>   File "/var/ARTIFACTS/work-podman-systemugyvyr9u/plans/cockpit-podman/podman-system/discover/default-0/tests/test/common/testlib.py", line 412, in click
>     self.mouse(selector + ":not([disabled]):not([aria-disabled=true])", "click", 0, 0, 0)
>   File "/var/ARTIFACTS/work-podman-systemugyvyr9u/plans/cockpit-podman/podman-system/discover/default-0/tests/test/common/testlib.py", line 404, in mouse
>     self.wait_visible(selector)
>   File "/var/ARTIFACTS/work-podman-systemugyvyr9u/plans/cockpit-podman/podman-system/discover/default-0/tests/test/common/testlib.py", line 648, in wait_visible
>     self._wait_present(selector)
>   File "/var/ARTIFACTS/work-podman-systemugyvyr9u/plans/cockpit-podman/podman-system/discover/default-0/tests/test/common/testlib.py", line 639, in _wait_present
>     self.wait_js_func('ph_is_present', selector)
>   File "/var/ARTIFACTS/work-podman-systemugyvyr9u/plans/cockpit-podman/podman-system/discover/default-0/tests/test/common/testlib.py", line 633, in wait_js_func
>     self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
>   File "/var/ARTIFACTS/work-podman-systemugyvyr9u/plans/cockpit-podman/podman-system/discover/default-0/tests/test/common/testlib.py", line 618, in wait_js_cond
>     self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
>   File "/var/ARTIFACTS/work-podman-systemugyvyr9u/plans/cockpit-podman/podman-system/discover/default-0/tests/test/common/testlib.py", line 319, in raise_cdp_exception
>     raise Error("%s(%s): %s" % (func, arg, msg))
> testlib.Error: timeout
> ```
> 
> I am going to rebase again to re-trigger the tests.

No need to worry about them, cockpit revdeps are not blocking and this is not related to your PR so just ignore it.

**Pull request merged**
