### PR TITLE
utils: Add missing symbols for FreeBSD

### PR DESCRIPTION
**Pull request by dfr**
[NO NEW TESTS NEEDED]

Signed-off-by: Doug Rabson <dfr@rabson.org>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by dfr** [comment]
Note: this simply copies the windows version from utils_windows.go - it may be better to have a single common file for non-linux builds

**Comment by rhatdan** [comment]
LGTM

**Comment by dfr** [comment]
Rebased to see if that fixes the failing tests

**Comment by dfr** [comment]
> Rebased to see if that fixes the failing tests

❗ Failed to start: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@da34922[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@6466455[Wrapped task = TrustedListenableFutureTask@49f775ab[status=PENDING, info=[task=[running=[NOT STARTED YET], com.google.api.gax.rpc.CheckingAttemptCallable@2450e8d8]]]]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3872e00f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]

I'm pretty sure I didn't cause that :)

**Comment by mheon** [comment]
Tests seem to be running, but not updating GH status until they actually complete.

**Comment by dfr** [comment]
All the tests are passing now, which is nice.

**Pull request merged**
