### PR TITLE
[CI:DOCS] Updated Troubleshooting.md Closes #5431

### LINKED ISSUE #5431: CNI: Make firewalld rules --permanent
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I configured CNI to use firewalld as firewall backend and added my podman network interface to the `trusted` zone. When I'm reloading firewalld (`firewall-cmd --reload`) all my podman related rules go missing. I'd like to have the ability to make the podman firewalld rules --permanent.
(I'm starting my containers as root.)

**Steps to reproduce the issue:**

1. Start container

2. `firewall-cmd --reload`

3. Rules are missing.

**Describe the results you received:**

```
# podman start pihole
5d95bb331f8d59c4d7d5da9af98570b3f82dd933aaf22126650e31741f225a6a
# podman ps
CONTAINER ID  IMAGE                                   COMMAND  CREATED            STATUS             PORTS  NAMES
5d95bb331f8d  docker.io/pihole/pihole:latest                   About an hour ago  Up 49 seconds ago         pihole
# firewall-cmd --zone=trusted --list-all
trusted (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces:
  sources: 172.16.21.4/32 fd00:c001::9e/128
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
# firewall-cmd --reload
success
# firewall-cmd --zone=trusted --list-all
trusted
  target: ACCEPT
  icmp-block-inversion: no
  interfaces:
  sources:
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```

**Describe the results you expected:**

Rules don't go missing.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 7a4f0dd7b20a3d4bf9ef3e5cbfac05606b08eac0'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 32140668928
  MemTotal: 33369112576
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 16835932160
  SwapTotal: 16835932160
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: carter
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  os: linux
  rootless: false
  uptime: 1h 35m 6.12s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-1.6.4-2.module_el8.1.0+272+3e64ee36.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical server

### PR DESCRIPTION
**Pull request by afro-coder**
Hi,

I didn't know what to do to remove the previous commits that had the whitespace issue so I deleted the branch itself.

This is a fresh branch I've checked with 3 different methods, including the commands from the vim wiki for trailing whitespaces but I couldn't find any.

I'm hoping this doesn't fail.
Closes #5431

### CODE REVIEW

**Comment by mheon** [comment]
Gitvalidation is complaining about a signoff - can you add one with `git commit --amend -s` and force-push?

**Comment by rhatdan** [comment]
You have to sign your commits, could you please sign and fix your commit message to something useful,

git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by afro-coder** [comment]
Thank you for being patient with me @mheon and @rhatdan not sure why git wasn't picking up the GPG key but forcing it to do so did verify it.

**Comment by rhatdan** [comment]
LGTM, although you should put the closes #5431 in the body of the commit, not in the heading.

**Comment by afro-coder** [comment]
Oh, I didn't know about the Commit heading and body part can I do a `git commit -a --amend -s` and `git push --force` again, since it'll run all the tests again, is that alright?

**Comment by rhatdan** [comment]
Yes.

**Comment by TomSweeneyRedHat** [comment]
LGTM
Thanks @afro-coder!

**Comment by rhatdan** [comment]
Thanks @afro-coder

**Comment by afro-coder** [comment]
Thank you for being so patient with me

**Pull request merged**
