### PR TITLE
[CI:DOCS] Document TESTFLAGS in test README file

### PR DESCRIPTION
**Pull request by ygalblum**
#### Does this PR introduce a user-facing change?
No

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
> [CI:DOCS]

This should no longer be used as it is a NOP, CI is smart enough to notice when you only change docs files to not trigger all the tests. But of course it does no harm either so it is not a problem to have it in the title.

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by ygalblum** [comment]
> > [CI:DOCS]
> 
> This should no longer be used as it is a NOP, CI is smart enough to notice when you only change docs files to not trigger all the tests. But of course it does no harm either so it is not a problem to have it in the title.

Didn't know that. Great, I won't need to look for the correct tag in the future :)

**Pull request merged**
