### PR TITLE
When chowning we should not follow symbolic link

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/podman/issues/7086

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
symlinks will keep us busy for years to come I fear....

LGTM

**Comment by edsantiago** [comment]
Flake is the `cgroup.freeze` one, which #7070 is intended to fix.

**Pull request merged**
