### PR TITLE
[3.0.1-rhel] bump go module to v3

### PR DESCRIPTION
**Pull request by vrothberg**
We missed bumping the go module, so let's do it now :)

* Automated go code with github.com/sirkon/go-imports-rename
* Manually via vgrep podman/v2 the rest

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
I'm doubtful we can justify a backport on this.

**Comment by vrothberg** [comment]
> I'm doubtful we can justify a backport on this.

@rhatdan & @TomSweeneyRedHat wanted this as a blocker. We can close the PR in case minds change.

**Comment by vrothberg** [comment]
/hold

... until we can :)

**Comment by vrothberg** [comment]
/hold cancel

I think we can merge.  BZ: 1931545.

**Comment by mheon** [comment]
Not yet - blocker is not yet approved

**Comment by TomSweeneyRedHat** [comment]
Approvals are a bit delayed due to RHEL F2F meetings.  I suspect we'll see a flurry of stuff on Monday.  Has this been fixed upstream?

**Comment by vrothberg** [comment]
> Approvals are a bit delayed due to RHEL F2F meetings. I suspect we'll see a flurry of stuff on Monday. Has this been fixed upstream?

Yes. Both in the master branch and the v3.0 one.

**Comment by TomSweeneyRedHat** [comment]
/lgtm
Approved per Josh Boyer in email

**Pull request merged**
