### PR TITLE
Cirrus: NM/CNI workaround + Remove prior-Ubuntu

### LINKED ISSUE #11123: New networking flake (root, compose)
New [flake](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6225438482628608/html/compose-podman-fedora-34-root-host.log.html). Looks identical to #10052, except this is root. It is also happening on my new PR, which sits on top of #11091.
```
[+0106s] ok 15 simple_port_map - up
[+0110s] curl: (7) Failed to connect to 127.0.0.1 port 5000: No route to host
[+0113s] curl: (7) Failed to connect to 127.0.0.1 port 5000: No route to host
[+0117s] curl: (7) Failed to connect to 127.0.0.1 port 5000: No route to host
[+0124s] curl: (7) Failed to connect to 127.0.0.1 port 5000: No route to host
         not ok 16 simple_port_map - curl (port 5000) failed with status 7
[rest of log is way too long]
```

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/automation_images/pull/88

Closes #11123

### CODE REVIEW

**Comment by edsantiago** [comment]
New task map (confirms that ubuntu-2010 is gone):

cirrus-map-pr11512

PS test is failing with:
```
ERROR: Most recent distro. version should never run with CGv1  (contrib/cirrus/setup_environment.sh:85 in main())
`

**Comment by cevich** [comment]
> PS test is failing with

Ya, I'm glad I added that check.  Something must have gone wrong in the build.  I'll investigate.

**Comment by Luap99** [comment]
Can you add "Closes #11123" to your PR description so that the issue is auto closed when this merges.

**Comment by cevich** [comment]
Oh I wasn't aware there was an open issue, yep, sure, happy to.

**Comment by cevich** [comment]
@containers/podman-maintainers PTAL, this is good to go and should fix some of the networking-flakes we experience occasionally.  Thanks @Luap99 for figuring this out!

**Pull request merged**
