### PR TITLE
Netavark userns test: give aardvark time to come up

### PR DESCRIPTION
**Pull request by edsantiago**
Nasty test flake, "bad address nc-server.dns.podman"

Cause: "There is absolutely no guarantee that aardvark-dns
is ready before the container is started." (source: Paul).

"Solution" (not really): wait before doing a host lookup.

Closes: #16272   (I hope)

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
Yeah that is a very unfortunate thing but I don't see us fixing this any time soon so this LGTM.

**Comment by edsantiago** [comment]
OOPS! Re-pushed because I looked at flake logs and realized that this is flaking in the non-Netavark test also.

**Comment by Luap99** [comment]
> OOPS! Re-pushed because I looked at flake logs and realized that this is flaking in the non-Netavark test also.

Oh good I really need to clean these duplicates up, so many pointless skipIfCNI/Netavark stuff in there. These tests are equivalent, we don't need two tests for the same thing.

**Comment by edsantiago** [comment]
Good point. This is the ONLY diff between those two tests:
```diff
--- test/e2e/aaa        2023-04-25 09:32:09.641689452 -0600
+++ test/e2e/bbb        2023-04-25 09:32:23.550742868 -0600
@@ -1,5 +1,6 @@
-       It("podman network works across user ns", func() {
-               netName := stringid.GenerateRandomID()
+       It("podman Netavark network works across user ns", func() {
+               SkipIfCNI(podmanTest)
+               netName := createNetworkName("")
                create := podmanTest.Podman([]string{"network", "create", netName})
                create.WaitWithDefaultTimeout()
                Expect(create).Should(Exit(0))
```
@Luap99 I'm happy to compress those two into one, in this PR, but I don't if there's a valid important difference between a network named by `GenerateRandomIO()` and one generated by `createNetworkName()`. My ignorant guess is that there is no difference, and the `createNetworkName` version is more readable and should be kept. Without the `skip` and without `Netavark` in the test name. Any objection to my doing that?

**Comment by Luap99** [comment]
>  Any objection to my doing that?

No if you want feel free to do that, I am also fine merging it like that.

**Comment by edsantiago** [comment]
Cleanup is one of life's little joys, and I would like some joy today. Repushed with duplication removed and with updated commit message. Thanks again for your feedback.

**Comment by Luap99** [comment]
Understandable, LGTM

**Pull request merged**
