### PR TITLE
rename libpod nettypes fields

### PR DESCRIPTION
**Pull request by Luap99**
#### What this PR does / why we need it:
Some field names are confusing. Change them so that they make more sense
to the reader.
Since these fields are only in the main branch we can safly rename them
without worrying about backwards compatibility.
Note we have to change the field names in netavark too.

### CODE REVIEW

**Comment by Luap99** [comment]
netavark PR: https://github.com/containers/netavark/pull/79

**Comment by baude** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons

**Pull request merged**
