### PR TITLE
add compose regression to ci

### PR DESCRIPTION
**Pull request by baude**
to prevent any regressionsm, we should be running regression tests using
compose.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
[With my new images](https://cirrus-ci.com/build/5239921134796800) this seems to be causing this test to fail almost universally:

```
Podman pod create 
           podman run --add-host in pod
           /var/tmp/go/src/github.com/containers/podman/test/e2e/pod_infra_container_test.go:379
         
         [BeforeEach] Podman pod create
           /var/tmp/go/src/github.com/containers/podman/test/e2e/pod_infra_container_test.go:19
         [It] podman run --add-host in pod
           /var/tmp/go/src/github.com/containers/podman/test/e2e/pod_infra_container_test.go:379
         Running: podman [options] pod create
         7dcd641b352967b92a3d4129821f7b10f189113f360fdd2f7bf3f403eebf7eed
         Running: podman [options] run --pod 7dcd641b352967b92a3d4129821f7b10f189113f360fdd2f7bf3f403eebf7eed --add-host foobar:127.0.0.1 quay.io/libpod/alpine:latest ping -c 1 foobar
         ping: permission denied (are you root?)
         PING foobar (127.0.0.1): 56 data bytes
         output: PING foobar (127.0.0.1): 56 data bytes
```

Exit code: 1

**Comment by cevich** [comment]
Took a quick peek, this looks really good!

@edsantiago Q: I didn't check the system-tests, but it seems there are a number of "helper" functions here that may be duplicates?  De-duplicating these things later can be a PITA, based on my experience.  Maybe consider if makes sense to arrange for helper-code sharing early rather than later?

**Comment by rhatdan** [comment]
I am going to merge.  @edsantiago Please do deduplication if you agree with @cevich in future PRs.
/lgtm

**Comment by rhatdan** [comment]
Great work @baude and @edsantiago Now we can start talking about Compose support and any bugs we fix, we can add to these tests to prevent regressions.

**Comment by cevich** [comment]
I second that, really nice work for something that's been a (literal) FAQ for a really long time.

**Pull request merged**
