### PR TITLE
vendor containers/storage@main

### PR DESCRIPTION
**Pull request by vrothberg**
Mainly to pull in fixes for #1382 which is impossible to reproduce locally so let's optimistically mark it as fixed and reopen if needed in the future.

Fixes: #1382
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@edsantiago a more or less informed guess that https://github.com/containers/storage/pull/1382 may fix https://github.com/containers/podman/issues/11594.

**Comment by edsantiago** [comment]
Fingers crossed. BTW you need to re-push with committed vendor files.

**Comment by vrothberg** [comment]
@rhatdan @baude PTAL

**Pull request merged**
