### PR TITLE
Close error handling

### PR DESCRIPTION
**Pull request by mtrmac**
- Fix spurious reports about failures to close a destination underlying `SparseWriter`, fixing https://github.com/containers/podman/pull/21936#issuecomment-1981567103
- Modify `SparseWriter` not to motivate callers to rely on `ErrClosed`, in the first place; first mentioned in https://github.com/containers/podman/pull/21592#discussion_r1496744844
- Fail on more errors, don’t just ignore/log them, to be more certain we got the full contents we need.

Cc: @l0rd 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mtrmac** [comment]
(See individual commit messages for details.)

**Comment by jakecorrenti** [comment]
LGTM

**Pull request merged**
