### PR TITLE
Handle podman-remote --arch, --platform, --os

### PR DESCRIPTION
**Pull request by rhatdan**
Podman remote should be able to handle remote specification of
arches.

Requires: https://github.com/containers/buildah/pull/3116

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago PTAL

**Comment by edsantiago** [comment]
Something not quite right: it's not working with just plain `--os`, no other flags:
```console
$ echo "FROM scratch" | ./bin/podman-remote build -t foo --os=windows -
Error: failed to parse query parameter 'platform': "windows": invalid platform syntax for "windows" (use OS/ARCH)
```
It works fine if I append `--arch=foo` or if I use `--platform=foo/windows`.

**Comment by rhatdan** [comment]
@edsantiago `$ echo "FROM scratch" | ./bin/podman-remote build -t foo --os=windows -`
Should work now.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by edsantiago** [comment]
Confirmed: passes buildah-bud tests (on my local setup. They won't pass in this PR due to the `tag-YMD-SHA` vendor string, which I don't know how to grok.

**Comment by rhatdan** [comment]
@edsantiago I am going to cut a Buildah test so we can get this to pass.

**Comment by edsantiago** [comment]
@rhatdan try rebasing on #9943 to test the custom buildah version. Unfortunately, you will need to do some manual conflict resolution, which means you will need to be the guinea pig for testing  https://github.com/containers/podman/blob/626b7ebd74dbd2614c4e6e9f99514404c50e806a/test/buildah-bud/README.md

**Comment by edsantiago** [comment]
(Spoiler alert: whether you cut a new buildah, or rebase on my PR, there are going to be conflicts because of the buildah system-test PR I merged last week. I will gladly help with the conflict resolution, but I hope someone else does the brunt of the work so we can test my documentation).

**Comment by edsantiago** [comment]
I don't see any changes to `test/buildah-bud/buildah-tests.diff`, which (I suspect) means you didn't read and follow `test/buildah-bud/README.md`, which (I suspect) means this PR is going to fail in the `bud` step with a merge conflict.

**Comment by edsantiago** [comment]
>error: corrupt patch at line 130

Sigh.

**Comment by edsantiago** [comment]
I got past that hurdle by manually editing line 134:
```
from:  @@ -2729,1 +2733,1 @@ _EOF     <--- '1' makes no sense! How did that happen?
to:    @@ -2729,6 +2733,7 @@ _EOF
```
...but then ran into a different snag, and I have to give up for the day. @rhatdan I'm sorry, obviously my code is not ready for prime time. I will spend more effort polishing it up this week.

**Comment by edsantiago** [comment]
Fixed in #9962.

**Pull request closed without merging**
