### PR TITLE
New release: v4.7.1

### PR DESCRIPTION
**Pull request by lsm5**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
@Luap99 @mheon @TomSweeneyRedHat @ashley-cui PTAL @ release notes update.

**Comment by lsm5** [comment]
I can append to this PR with version bump if release notes are ok.

**Comment by ashley-cui** [comment]
LGTM

**Comment by lsm5** [comment]
I guess we can ignore the release test.

**Comment by TomSweeneyRedHat** [comment]
Late to the review party, but LGTM

**Pull request merged**
