### PR TITLE
[v3.4.2-rhel] all: stop using deprecated GenerateNonCryptoID

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Cherry-pick #15788 to v3.4.2-rhel branch per RHBZ 2157930

In view of https://github.com/containers/storage/pull/1337, do this:

	for f in $(git grep -l stringid.GenerateNonCryptoID | grep -v '^vendor/'); do
		sed -i 's/stringid.GenerateNonCryptoID/stringid.GenerateRandomID/g' $f;
	done

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
Consider applying commit ae9a2d26dff4 and/or commit 7a9c14d6266a to fix the flakes.

**Comment by TomSweeneyRedHat** [comment]
I've added the commits that Valentin recommended.  Fingers crossed for happy tests.

**Comment by vrothberg** [comment]
validate doesn't pass

**Comment by vrothberg** [comment]
Ping

**Comment by vrothberg** [comment]
@TomSweeneyRedHat what's up with this backport?

**Comment by TomSweeneyRedHat** [comment]
On my list, it's just fallen down the stack too far atm.

**Pull request closed without merging**
