### PR TITLE
[#11408] podman help machine init

### PR DESCRIPTION
**Pull request by jesperpedersen**
Fix for #11408

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Thanks for contributing. The changes look good to me.  In order pass CI, you need add two things to the commit message:
1. It must be signed (i.e., have the Signed-off-by) field. You can do that via `git commit --amend -s`).
2. Since there's no test file changed, you need to add `[NO TESTS NEEDED]` to the body of the commit message.

**Comment by rhatdan** [comment]
LGTM

**Comment by jesperpedersen** [comment]
Thanks, Valentin.

(Maybe put a tl ;dr; in CONTRIBUTING about minimum requirements)

**Review by flouthoc — APPROVED** [review]

**Pull request merged**
