### PR TITLE
APIv2 test: add more tests for containers

### PR DESCRIPTION
**Pull request by Edward5hen**
Tests covering:
container exists
container pause
container unpause
container top
container mount
container unmount

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@Edward5hen thanks for the contribution!  Our CI requires that the commits be signed.  Please do `git commit --amend-s`, rebase and repush your commit.  In addition, it looks like lint is not too happy with this either, please check the failed gating test for more information.

**Comment by mheon** [comment]
@baude wanted it - intended for use cases where `podman-remote` and `podman system service` are on the same machine, I think?

**Comment by rhatdan** [comment]
I have no idea on why we have this for mount, (Which means someone will remind me, why I wanted it)

**Comment by Edward5hen** [comment]
@TomSweeneyRedHat @edsantiago PTAL

**Comment by TomSweeneyRedHat** [comment]
@Edward5hen changes LGTM, but I think you'll need to rebase to clear up the test issue.  A PR went in very recently that should hopefully fix that once rebased.

**Comment by Edward5hen** [comment]
@TomSweeneyRedHat rebase is done, but still exists fail some tests. I've no idea why they got "IO error" and "Remote host terminated the handshake". Could you please help check? Thanks.

**Comment by edsantiago** [comment]
@Edward5hen those were Cirrus flakes. Pressing Re-run made them pass. 

/lgtm

**Pull request merged**
