### PR TITLE
test: simplify cleanup code

### PR DESCRIPTION
**Pull request by giuseppe**
do not try to first stop and then rm but combine the two operations in
a single command.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
Nice idea!!!

LGTM

**Comment by rhatdan** [comment]
LGTM
Not sure why this is a WIP?

**Comment by giuseppe** [comment]
> LGTM Not sure why this is a WIP?

I am still playing with it.  I need to check whether it is worth and if there is anything more I can change

**Comment by vrothberg** [comment]
Couldn't we just call `podman system reset -f`?

**Comment by giuseppe** [comment]
> Couldn't we just call `podman system reset -f`?

let's try that!

**Comment by mheon** [comment]
I like it, LGTM!

**Review by vrothberg — COMMENTED** [review]
/lgtm|
/hold

**Comment by giuseppe** [comment]
> Couldn't we just call `podman system reset -f`?

unfortunately it doesn't work as expected and the tests timeout.

I've reverted to the previous version.  Integration tests take 5-10% less time

**Comment by TomSweeneyRedHat** [comment]
LGTM
I restarted the one red test, looked to be a network flake.

**Review by vrothberg — APPROVED** [review]
/lgtm

**Comment by vrothberg** [comment]
/hold cancel

Really cool idea to tackle _that_ part of the tests.  Since cleanup is faster now, I wonder whether the setup could also be improved.

**Pull request merged**
