### PR TITLE
kube: add DaemonSet support

### LINKED ISSUE #18899: Support DaemonSet with `podman kube play`
### Feature request description

The current command supports Pods and Deployments in the yaml file, it would be great, if it also supports a `DaemonSet`.

### Suggest potential solution

If I provide a yaml containing a `DaemonSet`, instead of a `Deployment` it should generate the corresponding pod for it.

### Have you considered any alternatives?

Currently, I simply replace the `DaemonSet` in the yaml with `Deployment` and that works.
Only it would improve the interoperability of the podman itself, if it would be done "properly".

### Additional context

The field `.spec.template` of  a `DaemonSet` is a `PodTemplateSpec`. The same as a `Deployment`.

Presumably, there is a large overlap in the functionality, so I hope it would be a rather low hanging fruit.

### PR DESCRIPTION
**Pull request by danishprakash**
Closes #18899

```release-note
kube: adds support for `DaemonSet`
```

Signed-off-by: danishprakash <danish.prakash@suse.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Looks like Validate is complaining.

**Review by vrothberg — COMMENTED** [review]
@umohnani8 @ygalblum PTAL

**Comment by umohnani8** [comment]
This looks like it is only for `kube play`, can we add support to generate Daemonset yamls in `kube generate` as well? We should try and keep support for k8s Kinds the same on both the generate and play parts.

**Comment by ygalblum** [comment]
LGTM
@umohnani8 while I agree that adding this support can be beneficial, I don't think we should block this PR for it. I think we should merge and open a ticket for generate

**Comment by vrothberg** [comment]
That sounds OK as well.  Only adding it to `generate` would be a blocker since we always want to be able to `play` what we `generate`.
@umohnani8 @rhatdan WDYT?

**Comment by rhatdan** [comment]
Agree we need to be able to `play` what we `generate`.

**Comment by danishprakash** [comment]
I've been looking into `generate`, and should have a PR up and running in a day or two.

**Comment by umohnani8** [comment]
I am fine with merging this while we wait for the generate PR
LGTM

**Comment by rhatdan** [comment]
/approve
/lgtm
Thanks @danishprakash

**Pull request merged**
