### PR TITLE
conmonrs usage implementation

### PR DESCRIPTION
**Pull request by cdoern**
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by jakecorrenti** [comment]
@cdoern if you haven't started working on it already I was planning on trying to integrate file logging into conmon-rs after finals next week

**Comment by cdoern** [comment]
@jakecorrenti sounds good, I am really just trying to get this to work still. I will probably take one more pass as it and update the vendoring before finals ends and then you can continue with it. I also think the rust for certain functions (attach or exec?) still needs to be written

**Comment by jakecorrenti** [comment]
> @jakecorrenti sounds good, I am really just trying to get this to work still. I will probably take one more pass as it and update the vendoring before finals ends and then you can continue with it. I also think the rust for certain functions (attach or exec?) still needs to be written

Last time I was working on it (3-4 months ago) there was an issue where Attach was detaching too early. On the conmon-rs side it looks like they resolved the issue I opened, but I haven't tried anything yet.

In terms of conmon-rs itself these are the issues that Matt had mentioned still remain: https://github.com/containers/podman/pull/14804#issuecomment-1224178549

**Pull request closed without merging**
