### PR TITLE
Jira RUN-1106 Network handlers updates

### PR DESCRIPTION
**Pull request by jwhonce**
* Add network API tests
* Update network create endpoint to return ID not Name

Audit:
- GET /networks ListNetworks
- GET /networks/{id} InspectNetwork
- DELETE /networks/{id} RemoveNetwork
- POST /networks/create CreateNetwork
- POST /networks/prune 405 not implemented

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
LGTM

**Pull request merged**
