### PR TITLE
Support hashed hostnames in the known_hosts file

### LINKED ISSUE #8159: Host key validation should also support hashed host names
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

User can choose to hash the hostnames in known_hosts, currently that disables "secure"

Continuation from https://github.com/containers/podman/issues/8139#issuecomment-717036222

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by afbjorklund**
Some systems have "HashKnownHosts yes" in their ssh_config

This causes entries in the ssh known_hosts to be hashed (|)

Closes #8159

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@jwhonce PTAL

**Comment by jwhonce** [comment]
LGTM

**Pull request merged**
