### PR TITLE
Client call to /play/kube incorrectly set tlsVerify

### PR DESCRIPTION
**Pull request by AlbanBedel**
The API parameter `tlsVerify` should be the invert of the internal option `SkipTLSVerify`, fix this conversion.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL
Would be nice to have a test for this.

**Comment by TomSweeneyRedHat** [comment]
Good catch @AlbanBedel 
An added regression test would be most welomed!

**Review by QiWang19 — COMMENTED** [review]
LGTM

**Comment by AlbanBedel** [comment]
I don't think I'll be able to provide a test for this bug in a timely manner. It's surely not a major security issue as only users that explicitly set `--tls-verify=true` are affected, but I would still expect such a bug to be fixed ASAP and backported to all affected stable releases if there is such a process.

**Comment by rhatdan** [comment]
/lgtm
@QiWang19 Could you throw together a test for this.

**Comment by rhatdan** [comment]
Thanks @AlbanBedel

**Pull request merged**
