### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**
Regular monthly update; BTW, it is now failing as below:

```
$ nix build -f nix/
builder for '/nix/store/4dd7a34bv0sx18wa10r1mknjfknabrnb-fontforge-20200314.drv' failed with exit code 2; last 10 log lines:
  /nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../../lib/libfontforge.so.4: undefined reference to `g_variant_type_get_gtype'
  /nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../../lib/libfontforge.so.4: undefined reference to `g_signal_emit_by_name'
  /nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../../lib/libfontforge.so.4: undefined reference to `mnt_new_iter'
  /nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../../lib/libfontforge.so.4: undefined reference to `g_value_get_schar'
  /nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../../lib/libfontforge.so.4: undefined reference to `g_signal_connect_object'
  /nix/store/cqxfi2q7d7k6y0q91wcx2cbkj4xsak63-binutils-2.31.1/bin/ld: ../../lib/libfontforge.so.4: undefined reference to `g_enum_get_value_by_nick'
  collect2: error: ld returned 1 exit status
  make[2]: *** [contrib/fonttools/CMakeFiles/acorn2sfd.dir/build.make:111: bin/acorn2sfd] Error 1
  make[1]: *** [CMakeFiles/Makefile2:647: contrib/fonttools/CMakeFiles/acorn2sfd.dir/all] Error 2
  make: *** [Makefile:171: all] Error 2
cannot build derivation '/nix/store/xyw4lgpcpavwfhq1myaw4mvf7pmvxmd8-dejavu-fonts-full-2.37.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7lrm28jwxkgdma6ir6i6b1ks7laj900v-dejavu-fonts-minimal-2.37.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/n44c4ncpna4csmvmf6c91dbhl0ck20a5-fontconfig-2.13.92.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zw3r5raw35p63xwbr7bfxqqf3r0kkcz0-fonts.conf.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d5nmji8lw80skxz3szd7mrab8aqwpgi6-cairo-1.16.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jnv8rklccj07w787ir6y658p6c3qgb9v-pango-1.47.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d6mvckwy2i2gsry6kxnlbxf7qmw21wqm-ruby2.6.6-mathematical-1.6.12.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4gvrvagafg0y92frjhyrnyh2q6cs24d1-asciidoctor-2.0.10.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2wj33m7l7gxam92z4prv72q6n9zvr860-asciidoctor-2.0.10.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z6jc188ckfrfqpqwr8zzg0rpjfhwn2li-git-2.29.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/qcgc87yqrdmyp31k44jgfqnd3b06v4z4-podman.drv': 1 dependencies couldn't be built
[0 built (1 failed), 0.0 MiB DL]
error: build of '/nix/store/qcgc87yqrdmyp31k44jgfqnd3b06v4z4-podman.drv' failed
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Hopefully @hswong3i can figure this out.

**Comment by hswong3i** [comment]
> Hopefully @hswong3i can figure this out.

https://github.com/containers/conmon/pull/218#issuecomment-736377128

**Comment by hswong3i** [comment]
This PR introduce 3 changes:

  - Upgrade Nix stable channel from 20.03 to 20.09.
 
    NixOS 20.09 released at 2020-10-27, see
    <https://nixos.org/manual/nixos/stable/release-notes.html#sec-release-20.09>
    for more information.

  - Replace `git` with `gitMinimal`.
 
    All 6 projects (i.e. crun/conmon/skopeo/buildah/podman/cri-o) are
    having `git` as dependency for failsafe during bootstrap. BTW
    <https://github.com/NixOS/nixpkgs/pull/104896> replace `asciidoc`
    with `asciidoctor` so trigger the dependency chain to `glib` and so
    failed (see below). Switching to `gitMinimal` skip this dependency
    chain to `glib`, which also speed up overall build process.

  - Adding `-pthread` for `glib`
 
    `conmon` couldn't skip the error by replacing `git` with
    `gitMinimal` since it do depend on `glib`. Since `glib` trigger
    error message "undefined reference to 'pthread\_create'", therefore
    adding `pthread` to `CFLAGS` could solve the problem.

Also see:

  - <https://github.com/containers/crun/pull/550>
  - <https://github.com/containers/conmon/pull/218>
  - <https://github.com/containers/skopeo/pull/1120>
  - <https://github.com/containers/buildah/pull/2831>
  - <https://github.com/containers/podman/pull/8526>
  - <https://github.com/cri-o/cri-o/pull/4395>

**Comment by hswong3i** [comment]
@rhatdan now it should be good again ;-)

**Comment by rhatdan** [comment]
As long as we can get it to pass tests.

LGTM
/approve

**Comment by hswong3i** [comment]
> As long as we can get it to pass tests.
> 
> LGTM
> /approve

@rhatdan the fail most likely related to outdated cache; BTW, the static build procedure in `.cirrus.yml` had been revamped since my original contribution, so I have no idea about how to expire the existing cache now :-S

**Pull request merged**
