### PR TITLE
ExitWithError() - more upgrades from Exit()

### PR DESCRIPTION
**Pull request by edsantiago**
Add error-message checks to pod_xxxx_test.go

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Draft, because I don't think it'll pass CI (network error message diffs). Also, maybe #22986 will be fixed by the time I get back from PTO.

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
This is ready. Rather than wait for #22986 and #22989, let's merge this now. Then whoever fixes those will have an almost-zero-effort test ready for them.

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
