### PR TITLE
machine: usb: Fix 'passtrough' typo

### PR DESCRIPTION
**Pull request by cfergeau**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
Thanks, please add `[NO NEW TESTS NEEDED]` to your commit message to get CI passing.

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
Thanks @cfergeau

**Pull request merged**
