### PR TITLE
[CI:BUILD] rpm: spec file updates from Fedora dist-git

### PR DESCRIPTION
**Pull request by lsm5**
#### Does this PR introduce a user-facing change?

```release-note
None
```

Ref: https://src.fedoraproject.org/rpms/podman/pull-request/131#commit_list

### CODE REVIEW

**Comment by Luap99** [comment]
> /var/tmp/rpm-tmp.PwVshJ: line 53: SOURCE_DATE_EPOCH: parameter null or not set

Looks like epel 8 builds do not work with this?

**Comment by lsm5** [comment]
> > /var/tmp/rpm-tmp.PwVshJ: line 53: SOURCE_DATE_EPOCH: parameter null or not set
> 
> Looks like epel 8 builds do not work with this?

@Luap99 yes, I'm checking with Zbigniew on that. Worst case I could revert to the older format on epel8

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
