### PR TITLE
Implement top streaming for containers and pods

### LINKED ISSUE #12115: API: list processes for pods and containers doesn't stream
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The list processes API endpoint for pods and containers both don't seem to support streaming.

This affects version 3.4.x, I have not tested the development version 4.x since the project I'm working on is targeting 3.4.x and 4.x will contain breaking API changes.

**Steps to reproduce the issue:**

1. ``podman system service unix:///home/`whoami`/testing.sock --log-level=debug --time=500`` with running pod and container.

2. ``curl -X GET --unix-socket "/home/`whoami`/testing.sock" "http://d/v3.0.0/libpod/containers/test_container/top?stream=true"`` or ``curl -X GET --unix-socket "/home/`whoami`/testing.sock" "http://d/v3.0.0/libpod/containers/test_container/top"`` since streaming should be `true` by default according to the reference.

3. ``curl -X GET --unix-socket "/home/`whoami`/testing.sock" "http://d/v3.0.0/libpod/pods/test_pod/top?stream=true"`` or ``curl -X GET --unix-socket "/home/`whoami`/testing.sock" "http://d/v3.0.0/libpod/pods/test_pod/top"`` since streaming should be `true` by default according to the reference.

**Describe the results you received:**
One response.

**Describe the results you expected:**
Multiple responses streamed over time.

**Output of `podman version`:**

```
Version:      3.4.2-dev
API Version:  3.4.2-dev
Go Version:   go1.15.9
Git Commit:   09aade7816e096550e805869f1300d7198aa8f91
Built:        Thu Oct 21 13:36:11 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/local/libexec/podman/conmon
    version: 'conmon version 2.0.31-dev, commit: 8d4355071e51ba4b597fc7ccb410808da73e54d5'
  cpus: 12
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: file
  hostname: DESKTOP
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.16.3-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 10731507712
  memTotal: 13343838208
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.4.0
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 4h 5m 59.63s (Approximately 0.17 days)
plugins:
  log:
  - k8s-file
  - none
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/alpaca/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/alpaca/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 7
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/alpaca/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2-dev
  Built: 1634816171
  BuiltTime: Thu Oct 21 13:36:11 2021
  GitCommit: 09aade7816e096550e805869f1300d7198aa8f91
  GoVersion: go1.15.9
  OsArch: linux/amd64
  Version: 3.4.2-dev
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes, latest version of 3.4.x built from source.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10, WSL, Debian Bullseye, 64bit

### PR DESCRIPTION
**Pull request by jwhonce**
* Implement API query parameter stream and delay for containers and
  pods top endpoints
* Update swagger with breaking changes
* Add python API tests for endpoints

Fixes #12115

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Comment by Luap99** [comment]
I think this should also be added to the CLI.
Also why is this marked as breaking change you only add new options, no?

**Comment by jwhonce** [comment]
@containers/podman-maintainers PTAL

**Comment by jwhonce** [comment]
> I think this should also be added to the CLI. Also why is this marked as breaking change you only add new options, no?

CLI already has this feature, and it was initially a breaking change until I changed the documentation. I'll remove the flag.

**Comment by Luap99** [comment]
> > I think this should also be added to the CLI. Also why is this marked as breaking change you only add new options, no?
> 
> CLI already has this feature, and it was initially a breaking change until I changed the documentation. I'll remove the flag.

`podman top` prints once for me and I do not see a streaming option

**Comment by mheon** [comment]
Concur with @Luap99 - there is no streaming built into the current CLI implementation. Do we need a card to add that? It seems like a reasonable ask.

**Comment by jwhonce** [comment]
@Luap99 Sorry for the confusion, I must have been thinking of some other command. I agree streaming is good for the CLI as well.

@mheon Either a card or GH issue would be good.

**Pull request merged**
