### PR TITLE
Remove workarounds for 14653 (checkpoint test failures)

### PR DESCRIPTION
**Pull request by edsantiago**
Closes: #14653

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
Are we good?

**Comment by edsantiago** [comment]
No -- I want to wait for new images (#16525) and then at least two successful runs before having any confidence that the flake is gone.

**Comment by edsantiago** [comment]
Two successful CI runs on old VMs, two successful runs on new (#16525) VMs. Not proof that the bug is fixed, of course. Do we feel lucky?

**Comment by vrothberg** [comment]
> Two successful CI runs on old VMs, two successful runs on new (#16525) VMs. Not proof that the bug is fixed, of course. Do we feel lucky?

I think we may need to feel the pain of the flake to get the incentive to fix the bug if it is still there.

**Review by vrothberg — COMMENTED** [review]
LGTM
@containers/podman-maintainers PTAL

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
