### PR TITLE
Output messages display rawInput

### PR DESCRIPTION
**Pull request by sstosh**
`init`, `checkpint/restore` and `cleanup` command now display
output messages which is rawInput instead of a container ID.

Example:
```
$ podman init <container name>
<container name>

$ podman init <short container ID>
<short container ID>
```

Signed-off-by: Toshiki Sonoda <sonoda.toshiki@fujitsu.com>

#### Does this PR introduce a user-facing change?

```release-note
Now output messages display rawInput instead of a container ID.
```

### CODE REVIEW

**Comment by mheon** [comment]
I don't know if we can do this by default, it will break Docker compatibility (and this feels like one of the places where it's very likely that scripts - including our own test suite - are parsing the output of the `podman create` and `podman run -d` command literally, and we'd definitely break them).

**Comment by sstosh** [comment]
> I don't know if we can do this by default, it will break Docker compatibility (and this feels like one of the places where it's very likely that scripts - including our own test suite - are parsing the output of the `podman create` and `podman run -d` command literally, and we'd definitely break them).

I understand. I'll try not to modify `create` and `run`.
For other commands about `rm`, `stop` and so on... , I would like to modify the output message that the container name is displayed by `--all` or `--latest`. What do you think?

Example:
```
$ podman rm -a
ctr_name1
ctr_name2
ctr_name3
```

**Comment by rhatdan** [comment]
Can you break this out into two PRs one for the podman rm --filter and one for the CID Files.

**Comment by edsantiago** [comment]
As you can tell by the number of changes you're making to the test suite, this is an ultra-breaking change. Even just changing `rm` and `stop` would cause chaos in the field.

**Comment by sstosh** [comment]
Certainly. This change has too much impact...
I will modify output message to show `rawInput` for the moment.
Currently, `start/stop`, `pause/unpause` and `kill` are already displayed `rawInput` (Also, `rm` and `restart` will be reflected by #A and #B).
Therefore, I'll try to modify the other commands (`cleanup`, `checkpoint/restore`, `init`).

**Comment by Luap99** [comment]
What is the docker behaviour? We should not make breaking changes for no reasons.

**Comment by sstosh** [comment]
> What is the docker behaviour? We should not make breaking changes for no reasons.

<details>
<summary>docker version</summary>

```
# docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:59 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```
</details>

<details>
<summary>docker info</summary>

```
# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.18.11-200.fc36.x86_64
 Operating System: Fedora Linux 36 (Server Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.755GiB
 Name: fedora36
 ID: S5ZI:PX3W:RFN7:TAPG:YPG5:HO4X:ZLLD:E5AJ:ULTL:WPXC:AYZP:3DGP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: <mask>
 HTTPS Proxy: <mask>
 No Proxy: <mask>
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
</details>

I verified the command `run`, `restart`, `start`, `stop`, `pause`, `unpause` outputs `rawInput`, at least.

<details>
<summary>docker command by name</summary>

```
# docker run -d --name test nginx
f4b27a7a3bf84b1803eb00e70738dbc12c3a8ae5a41ce452f4aafcaabba6224e
# docker restart test
test
# docker stop test
test
# docker start test
test
# docker pause test
test
# docker unpause test
test
# docker rm -f test
test
```
</details>

<details>
<summary>docker command by short ID</summary>

```
# docker run -d nginx
1960031807c74adfc82b91dc4adf03c9d657ebad5e171f9a119c599ee73575a0
# docker restart 19600
19600
# docker stop 19600
19600
# docker start 19600
19600
# docker pause 19600
19600
# docker unpause 19600
19600
# docker rm -f 19600
19600
```
</details>


`docker checkpoint` outputs checkpoint name.
However, `podman container checkpoint` does not have the concept of `checkpoint name`.


<details>
<summary>docker checkpoint by name</summary>

```
# docker run -d --name test nginx
62009aad0bdc976c7b7d64e1136deca849803ea4ee96bd107d1cb1a25ea8832d
# docker checkpoint create test cp
cp

# docker stop test
test
# docker ps -a
CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS                        PORTS     NAMES
62009aad0bdc   nginx     "/docker-entrypoint.…"   42 seconds ago   Exited (137) 32 seconds ago             test
# docker start --checkpoint cp test
<nothing outputs, is it bug?>

# docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS         PORTS     NAMES
62009aad0bdc   nginx     "/docker-entrypoint.…"   59 seconds ago   Up 3 seconds   80/tcp    test
```
</details>

<details>
<summary>docker checkpoint by short ID</summary>

```
# docker run -d nginx
d83bd9117e1cce39ef48a1107c8b9d676c25ab6a21b90cce3a4482755eb9975a
# docker checkpoint create d83b cp2
cp2

# docker stop d83b
d83b
# docker ps -a
CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS                        PORTS     NAMES
d83bd9117e1c   nginx     "/docker-entrypoint.…"   46 seconds ago   Exited (137) 17 seconds ago             sweet_cannon
# docker start --checkpoint cp2 d83b
<nothing outputs, is it bug?>

# docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED              STATUS         PORTS     NAMES
d83bd9117e1c   nginx     "/docker-entrypoint.…"   About a minute ago   Up 4 seconds   80/tcp    sweet_cannon
```
</details>

To my understanding, Docker has no equivalent commands for `podman container cleanup` and `podman init`.

**Review by vrothberg — COMMENTED** [review]
The changes touch more commands than the commit message describes.  It may have been better to have one commit per command but I am OK to go with a big change.

I think Podman should behave as Docker does.  If tests fail, for instance, because they expect an ID to be returned instead of a name, we can adjust them.

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
/approve

LGTM on my end

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
