### PR TITLE
[CI:ALL] Bump main to v5.4.0-dev

### PR DESCRIPTION
**Pull request by lsm5**
We have a v5.3 branch already.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
Yeah we will need new machine images first

**Comment by baude** [comment]
I have pushed 5.4 images now (still actually has podman-5.3 in it ofc) ... restarting failed tests.

**Comment by baude** [comment]
I pinged @l0rd via email as I know he is travelling.

**Comment by l0rd** [comment]
Ok, let me look at it.

**Comment by l0rd** [comment]
I have added the 5.4 tag

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
