### PR TITLE
CI VMs: bump to f41

### PR DESCRIPTION
**Pull request by edsantiago**
Built in https://github.com/containers/automation_images/pull/392

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
FYI I just remembered https://github.com/containers/podman/commit/d03e8ffc56e4337d6b14e9b4d0569555b0aadb3d so  that should be reverted to actually test f40 not just f41

**Comment by Luap99** [comment]
I guess we need to revert https://github.com/containers/podman/pull/24236 (or we just skip the test f40 part for a week or so until we get newer kernels) I am fine with whatever you prefer.

**Comment by edsantiago** [comment]
All `checkpoint and restore container out of and into pod` tests are now running and passing on [f41](https://api.cirrus-ci.com/v1/artifact/task/5157184160399360/html/int-podman-fedora-41-root-host-sqlite.log.html)  and [rawhide](https://api.cirrus-ci.com/v1/artifact/task/4875709183688704/html/int-podman-rawhide-root-host-sqlite.log.html) with crun 1.18.2. This closes my concern with #24327.

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
