### PR TITLE
Remove runc edit to lock to specific version

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/19795

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
1MB bloat? Do we really want this?

**Comment by mheon** [comment]
If you want to revendor, I recommend taking the latest commit in runc main and manually pinning to that; otherwise it wants to put us on the v1.1 branch.

**Comment by rhatdan** [comment]
Ok I just rebased to main branch which seems to be 1.2 RC, and much smaller changes.

**Comment by rhatdan** [comment]
@mheon better?

**Comment by mheon** [comment]
Sure, LGTM on my end

**Review by Luap99 — COMMENTED** [review]
LGTM

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
