### PR TITLE
image lookup: do not match *any* tags

### PR DESCRIPTION
**Pull request by vrothberg**
For reasons buried in the history of Podman, looking up an untagged
image would match *any* tag of matching image.  For instance,
looking up `centos` would match a local image `centos:foobar`.
Docker only looks for `centos:latest`.

Fix: #11964
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan, @giuseppe , I'm seeing some c/storage changes causing failures:
```
[+0026s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+0026s] # #|     FAIL: filter: after
[+0026s] # #| expected: 'sha256:time="2021-11-22T08:59:32-06:00" level=warning msg="Adding metacopy option, configured globally"
[+0026s] # b15eda79d7b4fe94c1b4863ccfbadff0f0ed9b1f84deb8df08b1880e0a51be55--localhost/mynewimage:latest'
[+0026s] # #|   actual: 'sha256:b15eda79d7b4fe94c1b4863ccfbadff0f0ed9b1f84deb8df08b1880e0a51be55--localhost/mynewimage:latest'
```

**Comment by vrothberg** [comment]
https://github.com/containers/storage/pull/1071

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
I think you have to rebase to remove the broken static build test.

**Comment by vrothberg** [comment]
Green and happy, @containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
LGTM
@giuseppe @flouthoc @Luap99 PTAL

**Pull request merged**
