### PR TITLE
Fix handling of podman-remote build --device

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/10614

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
A couple of test failed, but they looked like flakes trying to setup the VMs to test on.  I've restarted.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by edsantiago** [comment]
Followup: this PR does indeed fix the [two previously-failing buildah-bud tests](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5328641128136704/html/bud-remote-fedora-34-root-host.log.html#t--00155) (155, 156).

**Pull request merged**
