### PR TITLE
WireGuard Support

### PR DESCRIPTION
**Pull request by b-m-f**
Draft PR to get https://github.com/containers/netavark/discussions/450 implemented

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by b-m-f** [comment]
This PR is now ready for review.

This feature is spread over 3 PRs:
- https://github.com/containers/podman/pull/16291
- https://github.com/containers/common/pull/1209
- https://github.com/containers/netavark/pull/472

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
assuming happy tests

**Comment by rhatdan** [comment]
@b-m-f are you still interested in this?  If not I will close.

**Comment by b-m-f** [comment]
Hi @rhatdan ,

i sure am. https://github.com/containers/netavark/pull/472 is waiting for official plugin support in netavark. 

Until that is all done i cant say whether the changes in this PR will stay as they are.

**Comment by b-m-f** [comment]
Implemented with netvarks plugin feature and https://github.com/b-m-f/netavark-wireguard-plugin

**Pull request closed without merging**
