### PR TITLE
Fix remote api logs

### PR DESCRIPTION
**Pull request by ashley-cui**
properly returning logs through remote api
Closes: https://github.com/containers/podman/issues/7196
Closes: https://github.com/containers/podman/issues/6628

Signed-off-by: Ashley Cui <acui@redhat.com>

### CODE REVIEW

**Comment by ashley-cui** [comment]
@zhangguanzhang The logs wouldn't show because curl detected it as a binary, not application/json, so it didn't output anything.
The logs look fine, I'm not sure what the cat -a is supposed to show, but using podman logs, it looks fine  
```
$ podman run --name hello  busybox echo 1 
1
$ podman logs hello
1
```

**Comment by zhangguanzhang** [comment]
must try this with the `--tty`

**Comment by ashley-cui** [comment]
@zhangguanzhang still works for me
```
$ podman run --tty --name hello  busybox echo 1 
1
$ podman logs hello
1
```

**Comment by zhangguanzhang** [comment]
with `| cat -A`

**Comment by ashley-cui** [comment]
@zhangguanzhang I'm not sure what the cat -A has to do with the podman logs command, since podman logs works.

**Comment by zhangguanzhang** [comment]
In this case, I may need to open a new issue

**Comment by ashley-cui** [comment]
@zhangguanzhang It might be worthwhile, since this PR is dealing with remote log output, not cli as you have been looking at

**Comment by ashley-cui** [comment]
uh oh looks like i broke something while fixing something..

**Pull request closed without merging**
