### PR TITLE
Remove unused param from utils.Error in pkg/api and clean API handlers

### PR DESCRIPTION
**Pull request by jmguzik**
This commit removes error message string from utils.Error in pkg/api.
Param was not used inside a function for quite a long time
[NO NEW TESTS NEEDED]

Signed-off-by: Jakub Guzik <jguzik@redhat.com>

### CODE REVIEW

**Comment by jmguzik** [comment]
I think that CI-hook's blunderbuss plugin did not work, since there are no reviewers assigned.
/cc @rhatdan @jwhonce

**Comment by rhatdan** [comment]
Thanks Jakub, I noticed this my self a while ago, and thought I should do this, but never got around to it.
LGTM
/approve
@containers/podman-maintainers PTAL

**Comment by jmguzik** [comment]
No problem @rhatdan but actually there is more to this. I found it during looking at compat API "not found" report in comparison to docker.
```
[jguzik@fedora podman]$ curl --unix-socket /run/user/1000/podman/podman.sock http://localhost/v1.40/containers/somecontainer/json | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129  100   129    0     0  59392      0 --:--:-- --:--:-- --:--:-- 64500
{
  "cause": "no such container",
  "message": "no container with name or ID \"somecontainer\" found: no such container",
  "response": 404
}
[jguzik@fedora podman]$ curl --unix-socket /var/run/docker.sock http://localhost/v1.40/containers/somecontainer/json | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    47  100    47    0     0  24633      0 --:--:-- --:--:-- --:--:-- 47000
{
  "message": "No such container: somecontainer"
}
```

In podman you add additional fields in response and the message itself is formatted differently. I don't want to re-invent the wheel again, because you maybe made decisions in the past that it's OK to have inconsistency. If not, would you like me to correct this - in a different PR?

**Comment by rhatdan** [comment]
I am fine with it here.
@vrothberg PTAL

**Comment by jmguzik** [comment]
After having a second look at the problem I think I'll open a second PR in regards to the above. I would need more time to analyze this. Let's get this one done and I will return to 'not found' later.

**Review by vrothberg — COMMENTED** [review]
Thanks, LGTM

Before merging, let's wait for a head nod from @baude and @jwhonce.

**Comment by umohnani8** [comment]
LGTM

**Comment by jwhonce** [comment]
> No problem @rhatdan but actually there is more to this. I found it during looking at compat API "not found" report in comparison to docker.
> 
> ```
> [jguzik@fedora podman]$ curl --unix-socket /run/user/1000/podman/podman.sock http://localhost/v1.40/containers/somecontainer/json | jq
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   129  100   129    0     0  59392      0 --:--:-- --:--:-- --:--:-- 64500
> {
>   "cause": "no such container",
>   "message": "no container with name or ID \"somecontainer\" found: no such container",
>   "response": 404
> }
> [jguzik@fedora podman]$ curl --unix-socket /var/run/docker.sock http://localhost/v1.40/containers/somecontainer/json | jq
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100    47  100    47    0     0  24633      0 --:--:-- --:--:-- --:--:-- 47000
> {
>   "message": "No such container: somecontainer"
> }
> ```
> 
> In podman you add additional fields in response and the message itself is formatted differently. I don't want to re-invent the wheel again, because you maybe made decisions in the past that it's OK to have inconsistency. If not, would you like me to correct this - in a different PR?

@jmguzik The extra fields should not be an issue,  this is JSON after all. The format of the message should be changed to be more compatible. I am fine with an additional PR(s) to better align messages. We didn't understand how many clients scrape these messages.

**Pull request merged**
