### PR TITLE
[skip-ci] Reuse workflows

### PR DESCRIPTION
**Pull request by cevich**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
I am unqualified to do a meaningful review but consider it a LGTM if you want to merge

**Comment by cevich** [comment]
I'm not qualified to review it either :grin: Like all the other github-action crap, we just "merge and pray" :pray:

**Comment by cevich** [comment]
BTW: I have no idea how you got assigned to this issue.  Have you been drinking from the bad-luck fountain recently?

**Comment by cevich** [comment]
Manually triggered test job: https://github.com/containers/podman/actions/runs/3473497963

**Pull request merged**
