### PR TITLE
[NO TESTS NEEDED] Vendor in containers/buildah v1.20.0

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
/lgtm
/hold
hold for tests

**Comment by edsantiago** [comment]
Sorry about that. This is the downside of bud-under-podman.  Suggested [diff](https://github.com/containers/podman/files/6208770/foo.diff.txt) (it looks complicated, it's not. Most of it is git-sha-change noise. The critical part is the "emergency skip" near the end.

**Comment by edsantiago** [comment]
Darn it; looks like git automatically reintroduces the @#$%^ trailing whitespace that my script works so hard to remove.I really despise git some days.

@rhatdan, please try:
```console
$ sed -i -e 's/ \+$//' test/buildah-bud/buildah-tests.diff
$ vim !$ 
[go to bottom of file, and remove the empty last line]
```
I'm really sorry for the hassle.

**Comment by rhatdan** [comment]
I tried it by hand.  BTW I have no idea why this new test was failing by podman.  But we are in a bit of a rush to get podman 3.1 released.

**Comment by edsantiago** [comment]
I know; that's why I'm hanging out here on my day off. Fingers crossed.

**Comment by edsantiago** [comment]
Drat. I think hand-editing the .diff broke something:
```
[+0063s] error: patch fragment without header at line 19: @@ -117,5 +117,6 @@ symlink(subdir)"
[+0063s] hint: Use 'git am --show-current-patch=diff' to see the failed patch
[+0063s] Applying: tweaks for running buildah tests under podman
[+0063s] Patch failed at 0001 tweaks for running buildah tests under podman
```

**Comment by edsantiago** [comment]
@rhatdan I'm confused: the string "emergency" (from my emergency patch) does not appear in the diffs I'm looking at; and in fact the SHA in your diff is different than mine. Did you do anything other than (1) apply my diff to your podman working directory, then (2) hand-edit to remove trailing whitespace? Like, did you somehow run `git diff` and save that? If so, bad things are guaranteed to happen. I would suggest reverting to a clean state of `test/buildah/buildah-tests.diff`, applying my patch from above, and git-commit-amending that. No other steps whatsoever.

**Comment by edsantiago** [comment]
FWIW the patch applies cleanly on my end. I have not run the full bud test suite, but I do believe this patch will apply and tests will pass. (Assuming no veth flakes). Fingers crossed.

**Comment by edsantiago** [comment]
Restarted flake (#9833, the podman-remote race condition). bud is in progress. Fingers still crossed...

**Pull request merged**
