### PR TITLE
[v4.2] Sigstore sign

### PR DESCRIPTION
**Pull request by mtrmac**
This is a backport of #15108 to the 4.2 branch.

It vendors an unreleased version of c/common to be consistent with the original PR; we will get a released c/common 0.49.1 when vendoring the future Buildah release.

#### Does this PR introduce a user-facing change?

```release-note
Added the ability to create sigstore signatures in `podman push` and `podman manifest push`.
Added an option to read image signing passphrase from a file.
```

### CODE REVIEW

**Comment by mtrmac** [comment]
```
Building: 97393d23e Vendor in containers/(storage,image, common, buildah)
…
bin/golangci-lint    size= 23236608  delta=     0
bin/podman           size= 47419720  delta=1146616
***************************************************************************
* bin/podman grew by 1146616 bytes; max allowed is 51200.
*
* Please investigate, and fix if possible.
*
* A repo admin can override by setting the bloat_approved label
***************************************************************************
```

The tip of the 4.2 branch is failing the same way: https://github.com/containers/podman/runs/7544230196

**Comment by vrothberg** [comment]
@mtrmac we can wave that with the label.  For the e2e tests to pass you need to cherry-pick https://github.com/containers/podman/pull/15139/commits/3a05ddfb731d411678522ea38822e059f6e85515.

**Comment by mtrmac** [comment]
Tests have passed now.

**Comment by rhatdan** [comment]
I am going to merge this, but we need to pull in the released version of containers/common and buildah and then RC3 should be ready.

/lgtm

**Comment by TomSweeneyRedHat** [comment]
@mtrmac TYVVM!

**Pull request merged**
