### PR TITLE
test/system: Add support for multipath routes in pasta networking tests

### PR DESCRIPTION
**Pull request by sbrivio-rh**
In some environments, such as the one described in https://github.com/containers/podman/issues/20927, the default route is given as nexthop gateways. That is, it's a multipath routes with multiple gateways.

That means that pasta(1), after commit 6c7623d07bbd ("netlink: Add support to fetch default gateway from multipath routes"), can start and use a default gateway from that route.

Just like in pasta(1), in these tests, the default route indicates which upstream interface we should pick. If we ignore multipath routes, IPv6 addresses and gateway addresses themselves won't be available, so, while pasta is now able to configure the container, IPv6 tests will expect to find no address and no gateway, hence fail due to the mismatch.

Try to get gateway addresses from nexthop objects, in case the selection of a regular default route yields no results.

```release-note

None
```

Link: https://github.com/containers/podman/issues/20927
Closes: #20927
Signed-off-by: Stefano Brivio <sbrivio@redhat.com>

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM I guess?! I have not enough knowledge about the ipv6 setup to really comment on that, @edsantiago because you reported this issue mind testing the change here?

@sbrivio-rh, FYI please add `Fixes #20927` or `Closes #20927` to your commit message/PR description if it solves the linked issue. That will cause github to auto close the issue once the PR is merged.

**Comment by edsantiago** [comment]
Does this require a special version of pasta? I just tried this on 1mt, rawhide, `passt-0^20240220.g1e6f92b-1.fc41.x86_64`:
```
$ hack/bats --rootless 505:IPv6                                                                                                  
--------------------------------------------------                                                                                                              
$ bats --filter IPv6 test/system/505-networking-pasta.bats                                                                                                      
505-networking-pasta.bats                                                                                                                                       
 ✗ [505] IPv6 default address assignment                                                                                                                        
   (from function `bail-now' in file test/system/helpers.bash, line 235,                                                                                        
    from function `assert' in file test/system/helpers.bash, line 929,                                                                                          
    in test file test/system/505-networking-pasta.bats, line 287)                                                                                               
     `assert "${container_address}" = "${host_address}" \' failed                                                                                               
                                                                                                                                                                
   [07:36:44.702331485] $ /root/go/podman/bin/podman rm -t 0 --all --force --ignore                                                                             
                                                                                                                                                                
   [07:36:44.776805592] $ /root/go/podman/bin/podman ps --all --external --format {{.ID}} {{.Names}}                                                            
                                                                                                                                                                
   [07:36:44.848714924] $ /root/go/podman/bin/podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}                                                     
   [07:36:44.916522188] quay.io/libpod/testimage:20240123 1f6acd4c4a1d                                                                                          
                                                                                                                                                                
   [07:36:45.058701631] $ /root/go/podman/bin/podman run --net=pasta quay.io/libpod/testimage:20240123 ip -j -6 address show                                    
   [07:36:45.447530548] [{"ifindex":1,"ifname":"lo","flags":["LOOPBACK","UP","LOWER_UP"],"mtu":65536,"operstate":"UNKNOWN","txqlen":1000,"addr_info":[{"family":
"inet6","local":"::1","prefixlen":128,"scope":"host","protocol":"kernel_lo","valid_life_time":4294967295,"preferred_life_time":4294967295}]},{"ifindex":2,"ifnam
e":"eth0","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":65520,"operstate":"UNKNOWN","txqlen":1000,"addr_info":[{"family":"inet6","local":"2620:52:0:bb
:f816:3eff:fee5:5e3f","prefixlen":64,"scope":"global","tentative":true,"noprefixroute":true,"valid_life_time":4294967295,"preferred_life_time":4294967295},{"fam
ily":"inet6","local":"fe80::8079:5fff:fe75:3609","prefixlen":64,"scope":"link","tentative":true,"protocol":"kernel_ll","valid_life_time":4294967295,"preferred_l
ife_time":4294967295}]}]                                                                                                                                        
   Device "null" does not exist.                                                                                                                                
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv                                                                                                              
   #|     FAIL: Container address not matching host                                                                                                             
   #| expected: = ''                                                                                                                                            
   #|   actual:   2620:52:0:bb:f816:3eff:fee5:5e3f
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   # [teardown]
   
   [07:36:45.486689689] $ /root/go/podman/bin/podman pod rm -t 0 --all --force --ignore
   
   [07:36:45.551645209] $ /root/go/podman/bin/podman rm -t 0 --all --force --ignore
   [07:36:45.653289157] f4c8b3a80456fb935bb57cf6809b75bd65718d34789e7449bb4ceb769d626e4d
   
   [07:36:45.654836243] $ /root/go/podman/bin/podman network prune --force
   
   [07:36:45.719933950] $ /root/go/podman/bin/podman volume rm -a -f
 ✓ [505] IPv6 address assignment                                                 
 ✓ [505] No IPv6                                                                 
 ✓ [505] IPv6 default route                                                      
 ✓ [505] IPv6 default route assignment                                           
 ✓ [505] External resolver, IPv6                                                 
 - [505] Local forwarder, IPv6 (skipped: Currently unsupported)                  
 ✗ [505] Single TCP port forwarding, IPv6, tap                                   
   (from function `bail-now' in file test/system/helpers.bash, line 235,
    from function `die' in file test/system/helpers.bash, line 813,
    from function `run_podman' in file test/system/helpers.bash, line 423,
    from function `pasta_test_do' in file test/system/505-networking-pasta.bats, line 233,
    in test file test/system/505-networking-pasta.bats, line 519)
`pasta_test_do' failed
   
   [07:36:51.416328008] $ /root/go/podman/bin/podman rm -t 0 --all --force --ignore
   
   [07:36:51.478630886] $ /root/go/podman/bin/podman ps --all --external --format {{.ID}} {{.Names}}
   
   [07:36:51.542878002] $ /root/go/podman/bin/podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   [07:36:51.603533119] quay.io/libpod/testimage:20240123 1f6acd4c4a1d
   Device "null" does not exist.
   
   [07:36:51.800460242] $ /root/go/podman/bin/podman run --net=pasta -p []:5025:5025/tcp quay.io/libpod/testimage:20240123 sh -c for port in $(seq 5025 5025); d
o                              socat -u TCP6-LISTEN:${port} STDOUT &                          done; wait
   [07:36:51.859441246] Error: must provide a non-empty container host IP to publish
   [07:36:51.862704159] [ rc=125 (** EXPECTED 0 **) ]
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #| FAIL: exit code is 125; expected 0 
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   # [teardown]
   
   [07:36:51.869953829] $ /root/go/podman/bin/podman pod rm -t 0 --all --force --ignore
   
   [07:36:51.928040901] $ /root/go/podman/bin/podman rm -t 0 --all --force --ignore
   
   [07:36:51.984272720] $ /root/go/podman/bin/podman network prune --force
   
   [07:36:52.043656778] $ /root/go/podman/bin/podman volume rm -a -f
 ✓ [505] Single TCP port forwarding, IPv6, loopback                              
 ✗ [505] TCP port range forwarding, IPv6, tap                                    
   (from function `bail-now' in file test/system/helpers.bash, line 235,
    from function `die' in file test/system/helpers.bash, line 813,
    from function `run_podman' in file test/system/helpers.bash, line 423,
    from function `pasta_test_do' in file test/system/505-networking-pasta.bats, line 233,
    in test file test/system/505-networking-pasta.bats, line 527)
     `pasta_test_do' failed
   
   [07:36:53.981621847] $ /root/go/podman/bin/podman rm -t 0 --all --force --ignore
   
   [07:36:54.045319198] $ /root/go/podman/bin/podman ps --all --external --format {{.ID}} {{.Names}}
   
   [07:36:54.108996086] $ /root/go/podman/bin/podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   [07:36:54.169560706] quay.io/libpod/testimage:20240123 1f6acd4c4a1d
   Device "null" does not exist.
   
   [07:36:54.413019615] $ /root/go/podman/bin/podman run --net=pasta -p []:5635-5637:5635-5637/tcp quay.io/libpod/testimage:20240123 sh -c for port in $(seq 563
5 5637); do                              socat -u TCP6-LISTEN:${port} STDOUT &                          done; wait
   [07:36:54.473427544] Error: must provide a non-empty container host IP to publish
```

**Comment by sbrivio-rh** [comment]
> Does this require a special version of pasta? I just tried this on 1mt, rawhide, `passt-0^20240220.g1e6f92b-1.fc41.x86_64`:

That version is [fine](https://passt.top/passt/commit/?id=6c7623d07bbd44d81beb4aa60b0a1de12b622630), but:
> 
> ```
> $ hack/bats --rootless 505:IPv6                                                                                                  
> --------------------------------------------------                                                                                                              
> $ bats --filter IPv6 test/system/505-networking-pasta.bats                                                                                                      
> 505-networking-pasta.bats                                                                                                                                       
>  ✗ [505] IPv6 default address assignment                                                                                                                        
>    (from function `bail-now' in file test/system/helpers.bash, line 235,                                                                                        
>     from function `assert' in file test/system/helpers.bash, line 929,                                                                                          
>     in test file test/system/505-networking-pasta.bats, line 287)                                                                                               
>      `assert "${container_address}" = "${host_address}" \' failed                                                                                               
>                                                                                                                                                                 
>    [07:36:44.702331485] $ /root/go/podman/bin/podman rm -t 0 --all --force --ignore                                                                             
>                                                                                                                                                                 
>    [07:36:44.776805592] $ /root/go/podman/bin/podman ps --all --external --format {{.ID}} {{.Names}}                                                            
>                                                                                                                                                                 
>    [07:36:44.848714924] $ /root/go/podman/bin/podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}                                                     
>    [07:36:44.916522188] quay.io/libpod/testimage:20240123 1f6acd4c4a1d                                                                                          
>                                                                                                                                                                 
>    [07:36:45.058701631] $ /root/go/podman/bin/podman run --net=pasta quay.io/libpod/testimage:20240123 ip -j -6 address show                                    
>    [07:36:45.447530548] [{"ifindex":1,"ifname":"lo","flags":["LOOPBACK","UP","LOWER_UP"],"mtu":65536,"operstate":"UNKNOWN","txqlen":1000,"addr_info":[{"family":
> "inet6","local":"::1","prefixlen":128,"scope":"host","protocol":"kernel_lo","valid_life_time":4294967295,"preferred_life_time":4294967295}]},{"ifindex":2,"ifnam
> e":"eth0","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":65520,"operstate":"UNKNOWN","txqlen":1000,"addr_info":[{"family":"inet6","local":"2620:52:0:bb
> :f816:3eff:fee5:5e3f","prefixlen":64,"scope":"global","tentative":true,"noprefixroute":true,"valid_life_time":4294967295,"preferred_life_time":4294967295},{"fam
> ily":"inet6","local":"fe80::8079:5fff:fe75:3609","prefixlen":64,"scope":"link","tentative":true,"protocol":"kernel_ll","valid_life_time":4294967295,"preferred_l
> ife_time":4294967295}]}]                                                                                                                                        
>    Device "null" does not exist.                                                                                                                                
>    #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv                                                                                                              
>    #|     FAIL: Container address not matching host                                                                                                             
>    #| expected: = ''                                                                                                                                            
>    #|   actual:   2620:52:0:bb:f816:3eff:fee5:5e3f
>    #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...for some reason, this change isn't enough: the test should now use `eth0` as interface instead of `null`, and therefore expect 2620:52:0:bb:f816:3eff:fee5:5e3f as IPv6 address instead of an empty string.

**Comment by sbrivio-rh** [comment]
> @sbrivio-rh PM/email me for access to the VM

Thanks, I didn't realise that the `default_ifname()` helper needed a similar change, done now.

**Comment by edsantiago** [comment]
pasta tests pass now, so LGTM. I might've liked a little less duplication, but will not block over it.

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
