### PR TITLE
[WIP] Improve logging

### PR DESCRIPTION
**Pull request by weirdwiz**
Progress:
- Add file name and function name to debug log
- Pad text and disable truncation for loglevel to improve readability 

References #4854

### CODE REVIEW

**Comment by vrothberg** [comment]
@weirdwiz, still working on it?  Please let us know in case you ran out of time; we can take over if needed.

**Comment by weirdwiz** [comment]
> @weirdwiz, still working on it? Please let us know in case you ran out of time; we can take over if needed.

Yes, I'm still working on it :D. 
Just got over with the mid terms, so couldn't focus on it for a while.

**Comment by rhatdan** [comment]
@weirdwiz Any time to work on this?

**Comment by weirdwiz** [comment]
> @weirdwiz Any time to work on this?
Unfortunately, I haven't been able to find time to focus on this.
Maybe these changes could be looked at and merged if necessary, and the remaining work could be continued in the future.

**Comment by rhatdan** [comment]
Could you rebase the PR and we can take a look at it.

**Comment by rhatdan** [comment]
@weirdwiz Still working on this?

**Comment by weirdwiz** [comment]
Unfortunately haven't been able to work on this, I don't think I'll be able to work on this in the near future.

**Comment by vrothberg** [comment]
No worries, @weirdwiz!  I am closing the PR for now but feel free to reopen and go back to it later on.

**Pull request closed without merging**
