### PR TITLE
machine applehv: create better error on start failure

### PR DESCRIPTION
**Pull request by mheon**
This is #20738 from @Luap99 but with a no new tests needed annotation

<MH: Added no new tests needed to pass CI>
[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by baude** [comment]
it has been reviewed and LGTM by two maintainers ...

/hold
/lgtm

**Comment by n1hility** [comment]
💯

**Pull request merged**
