### PR TITLE
Adding `-cpu host` for qemu for MacOS

### PR DESCRIPTION
**Pull request by scottschreckengaust**
Fixes https://github.com/containers/podman/issues/11421

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
@ashley-cui @baude @jwhonce PTAL

**Comment by baude** [comment]
excellent PR.  would you mind adding a better commit message for our changelogs?

**Comment by baude** [comment]
LGTM, small ask to update commit message

**Comment by mheon** [comment]
/approve
LGTM once comment from @baude is addressed

**Comment by scottschreckengaust** [comment]
FYI: Before a MacOS release the PR #11449 may need to be merged. I had to patch `pkg/machine/qemu/machine.go` similar to PR #11449 to test locally:

```
@@ -622,10 +622,11 @@ func CheckActiveVM() (bool, string, error) {
 // startHostNetworking runs a binary on the host system that allows users
 // to setup port forwarding to the podman virtual machine
 func (v *MachineVM) startHostNetworking() error {
-       // TODO we may wish to configure the directory in containers common
        binary := filepath.Join("/usr/libexec/podman/", machine.ForwarderBinaryName)
        if _, err := os.Stat(binary); err != nil {
-               return err
+               if binary, err = exec.LookPath(machine.ForwarderBinaryName); err != nil {
+                       return err
+               }
        }
 
        // Listen on all at port 7777 for setting up and tearing
```

**Comment by mheon** [comment]
@baude What's the story with gvproxy lookup on main? It's drastically different from the 3.3 branch. Are we going to unify them at some point?

**Comment by scottschreckengaust** [comment]
> LGTM, small ask to update commit message

Updated commit message.

**Comment by scottschreckengaust** [comment]
This looks like it is in the 3.3.1 release (commit is there) but still showing. Local build and testing of the PR does not show the warning, can I get a confirmation that the warning message is still occurring (other than for me on a brew upgrade)?

**Comment by lazarillo** [comment]
Yes, I am also seeing the warning.

Here are some details:

```
╰─❯ podman --version    
podman version 3.3.1
```
and
```
╰─❯ uname -a           
Darwin c02c2147md6v-c 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
```

I built it with homebrew today (2019-09-28).

Let me know if you need any further details or information.

**Comment by lazarillo** [comment]
I am not sure if this is related, but I also noticed that I am not able to connect to machines unless I am root.

I am just learning `podman`, but have been using Docker for a while.  I was looking at [a nice tutorial](https://github.com/containers/podman/blob/main/docs/tutorials/podman_tutorial.md) to get started and it had this example command to test a web server deployment:

```
podman run -dt -p 8080:8080/tcp -e HTTPD_VAR_RUN=/run/httpd -e HTTPD_MAIN_CONF_D_PATH=/etc/httpd/conf.d \
                  -e HTTPD_MAIN_CONF_PATH=/etc/httpd/conf \
                  -e HTTPD_CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/httpd/ \
                  registry.fedoraproject.org/f29/httpd /usr/bin/run-httpd
```

I could not get that command to "work", unless I ran it with root (`sudo`).  Specifically, the command ran, but the port mapping was useless.

Without `sudo`, I just got:

```
╰─❯ curl localhost:8080                                                                                    
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

But if I ran the command preceded by `sudo`, then I got the proper response:

```
╰─❯ curl localhost:8080                                                                                           
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>Test Page for the Apache HTTP Server on Fedora</title>
.
.
.
```

**Pull request merged**
