### PR TITLE
fix tab formatting in podman machine list

### LINKED ISSUE #12313: podman machine do not use a `tab` but instead `spaces` to list the VM machines
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The format used to stdout the list of the podman machine do not use a `tab` but instead `spaces`.
The list of the machines displayed should respect the format defined and documented and add a tab between the columns result
```
podman machine list --format "{{.Name}}\t{{.VMType}}\t{{.Created}}\t{{.LastUp}}\t{{.CPUs}}\t{{.Memory}}\t{{.DiskSize}}" | awk -F '\t' '{ print $2 }'

podman machine list --format "{{.Name}}\t{{.VMType}}\t{{.Created}}\t{{.LastUp}}\t{{.CPUs}}\t{{.Memory}}\t{{.DiskSize}}" | awk -F '\t' '{ print $1 }'
macvm*      qemu        2 hours ago  About an hour ago  1           2.147GB     10.74GB

OR

podman machine list | head -n 2 | awk -F '\t' '{ print $2 }'


podman machine list | head -n 2 | awk -F '\t' '{ print $1 }'
NAME        VM TYPE     CREATED      LAST UP            CPUS        MEMORY      DISK SIZE
macvm*      qemu        2 hours ago  About an hour ago  1           2.147GB     10.74GB
```

**Additional information**

podman version: 3.4.2
OS: MacOS

### PR DESCRIPTION
**Pull request by Regis-Caelum**
#### Does this PR introduce a user-facing change?

```release-note
No
```

#### Issue
Closes #12313.
 
#### Files Changed
`cmd/podman/machine/list.go`

#### Changes
changed tabs to escaped character `\u0009` in the format string

### CODE REVIEW

**Comment by Regis-Caelum** [comment]
@rhatdan please review the code, and LMK for any changes

**Review by Luap99 — COMMENTED** [review]
What is different between machine list all the other commands that use the same display logic, e.g. podman ps podman image ls, etc...? We should not change a single command for no good reason.

**Comment by TomSweeneyRedHat** [comment]
I'm always leery about changes like this that seem innocuous but then cause unintended issues.   Like @Luap99 , I'd like to learn a little bit more about the need for the change.

**Comment by rhatdan** [comment]
Since we heard no more about the need, I am closing.

**Pull request closed without merging**
