### PR TITLE
auto update: return restart error

### PR DESCRIPTION
**Pull request by vrothberg**
Return the error when restarting the unit failed during an update. The task is correctly marked to have failed but we really need to return the error to the user.

@edsantiago :crossed_fingers: 

[NO NEW TESTS NEEDED] - The flakes in #17607 will reveal errors.

#### Does this PR introduce a user-facing change?

```release-note
Return errors from systemd when restarting a unit failed during an auto update. 
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by edsantiago** [comment]
Well, here's the error message [[source](https://api.cirrus-ci.com/v1/artifact/task/5226743556997120/html/sys-podman-debian-12-root-host.log.html)]:`
```
Error: restarting unit container-c_image_OBvhQIJzmV.service during update: expected "done" but received "failed"
```

**Comment by vrothberg** [comment]
This is really poking in the dark.  I added some more debug logs to the test in hope to get something useful.

Really no idea what's going on on Debian.  It's always the same pattern that restarting the systemd units fails during auto update.

Why is it only flaking on Debian?  @edsantiago have you seen these tests fail on Fedora as well but maybe at such a low frequency that it fell under the (flake) radar?

**Comment by edsantiago** [comment]
There are only two Fedora flakes in auto-update, and both are the "1 vs 2" flake:
```
#|     FAIL: Number of images updated from registry.
#| expected: '2'
#|   actual: '1'
```

* fedora-37 : sys podman fedora-37 root host
  * PR #17707
    * [03-14 10:15](https://api.cirrus-ci.com/v1/artifact/task/4810013886119936/html/sys-podman-fedora-37-root-host.log.html#t--00350) in [sys] podman auto-update with multiple services
* fedora-37-aarch64 : sys podman fedora-37-aarch64 root host
  * PR #17781
    * [03-14 10:35](https://api.cirrus-ci.com/v1/artifact/task/6257284385341440/html/sys-podman-fedora-37-aarch64-root-host.log.html#t--00351) in [sys] podman auto-update with multiple services

**Comment by vrothberg** [comment]
> Still happening, [still debian](https://api.cirrus-ci.com/v1/artifact/task/5084070816776192/html/sys-podman-debian-12-root-host-boltdb.log.html). Is there anything in that log that can help you?

I'd need to clone myself at the moment to find time to look into it, sorry :(  Will take a look as soon as I find time.

**Comment by vrothberg** [comment]
@edsantiago are you cool to merge or shall I remove the echos in the tests?

**Comment by vrothberg** [comment]
Thanks!  My current "feeling" is that after this change we will only see `podman auto-update` failures as we now return the error and exit non-zero.  All other flavors of failures in the tests should disappear.

I will look into the dbus/systemd dependency we use and check whether a bug may linger there.  Other than that, we may try to restart the service another time if the first attempt has failed.  But that would be my last resort as it feels like giving up.

**Pull request merged**
