### PR TITLE
[CI:DOCS] Adds missing . to README.md file.

### PR DESCRIPTION
**Pull request by Landrash**
Adds missing . to README.md file.

Signed-off-by: Fredrik Lindqvist <landrash@mail.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM but CI doesn't like the commit.

I guess you need to have an empty line between the commit title and the "signed off by".

**Comment by rhatdan** [comment]
Thanks @Landrash 
Sadly even for this small change, you have to sign your commit

git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
LGTM
/approve

**Comment by TomSweeneyRedHat** [comment]
LGTM
once signed

**Comment by vrothberg** [comment]
Note that it's signed (https://github.com/containers/podman/pull/7792/commits/c43dce1ec55a865f4c7f08f2de7b559414160125) but there needs to be an empty line.

**Comment by Landrash** [comment]
> Note that it's signed ([c43dce1](https://github.com/containers/podman/commit/c43dce1ec55a865f4c7f08f2de7b559414160125)) but there needs to be an empty line.

Can confirm that it was the problem.
Thanks for helping resolve it :)

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
