### PR TITLE
libpod: cleanup default cache on system reset

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/containers/podman/issues/22825

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
Do you know if there a reason that the blob cache is not located on the actual graphroot but rather hard coded to ~/.local/share/containers/cache? I am asking because this means that running e2e system reset tests (which should run isolated) will now nuke my local blob info cache.
I guess it will not be big deal in practice as it is just a cache but it still seems rather unexpected to me.

**Comment by giuseppe** [comment]
> Do you know if there a reason that the blob cache is not located on the actual graphroot but rather hard coded to ~/.local/share/containers/cache? I am asking because this means that running e2e system reset tests (which should run isolated) will now nuke my local blob info cache.
> I guess it will not be big deal in practice as it is just a cache but it still seems rather unexpected to me.

no idea why we picked that directory.

@mtrmac do you think we should change it to be under `storage`?

**Comment by Luap99** [comment]
> The reason is that it has no direct relationship with the c/storage graph root. It is used, and beneficial, e.g. also for `skopeo copy docker://… docker://…`

Should podman system reset then delete it or not in your opinion?

**Comment by Luap99** [comment]
Ack thanks, as it is just a cache and it is not like many user running podman system reset with non default location anyway I think it is fine then

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by mtrmac** [comment]
I do agree it’s not ideal if Podman tests affect things outside of the test perimeter. I’m tempted to say that should be changed in the tests, _maybe_ by changing `XDG_DATA_HOME`. But that feels like a big and risky hammer.

**Comment by TomSweeneyRedHat** [comment]
Addresses: https://issues.redhat.com/browse/RHEL-40811 and https://issues.redhat.com/browse/RHEL-40814

**Pull request merged**
