### PR TITLE
Makefile: install targets independent of build

### PR DESCRIPTION
**Pull request by lsm5**
Building from source would involve separate `make` and `make install`
steps.

This removes a lot of unnecessary `-nobuild` targets which were
otherwise needed for packaging.

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@mheon @baude @rhatdan @vrothberg @edsantiago @cevich PTAL

/cc @containers/podman-maintainers

### CODE REVIEW

**Comment by lsm5** [comment]
@jnovy PTAL

**Comment by lsm5** [comment]
I'm gonna try to cleanup the older `.copr` stuff in this pr.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 RPM test isn't happy.  I don't see anything off hand to tilt it over though, but not my area of expertise.

**Comment by lsm5** [comment]
> @lsm5 RPM test isn't happy. I don't see anything off hand to tilt it over though, but not my area of expertise.

yup, I need to further adjust Makefile along with that CI job.

**Comment by lsm5** [comment]
@cevich for the `Test build RPM` test, I have changed  `make package` to use `rpkg local` which uses the file `podman.spec.rpkg`. This will need the package `rpkg` to be installed on the CI env. Should that be going in the image itself, or somewhere in the CI setup config in the podman repo?

**Comment by cevich** [comment]
> Should that be going in the image itself, or somewhere in the CI setup config in the podman repo?

Thanks for asking.  The images are fairly bloated, and if I'm not mistaken this is one job for just this repo, ya?  Also, I'm imagining this `rpkg` tool (being newer than rpmbuild) will likely change/update more frequently.  So at the risk of the occasional install-related flake, I'd say go ahead and install it at runtime for now (e.g. in `setup_environment.sh`).  If the situation changes, the tool is needed in every repo., and/or this strategy proves an unreliable/flaky strategy then we can include it into the image.  Sound reasonable?

**Comment by lsm5** [comment]
> > Should that be going in the image itself, or somewhere in the CI setup config in the podman repo?
> 
> Thanks for asking. The images are fairly bloated, and if I'm not mistaken this is one job for just this repo, ya? Also, I'm imagining this `rpkg` tool (being newer than rpmbuild) will likely change/update more frequently. So at the risk of the occasional install-related flake, I'd say go ahead and install it at runtime for now (e.g. in `setup_environment.sh`). If the situation changes, the tool is needed in every repo., and/or this strategy proves an unreliable/flaky strategy then we can include it into the image. Sound reasonable?

Yup, works for now. Eventually we may need it in more repos if we wanna provide copr builds for each package on every PR merge. But that's for later. Thanks a lot!

**Comment by cevich** [comment]
Yep, certainly if it's used far and wide, let's get it into the images.

**Comment by lsm5** [comment]
@cevich is CI stuck or something? This flake https://cirrus-ci.com/task/5633459950452736 went green on re-run, but other tests don't seem to be running.

**Comment by lsm5** [comment]
alright, all green now.

**Comment by mheon** [comment]
LGTM!

**Comment by cevich** [comment]
hang on a sec...need to carefully review the multi-arch build changes...

**Comment by cevich** [comment]
Okay, confirmed the multi-arch binaries are correctly built.  I checked by running the `file` command on the contents of the `s390x` tarball.

**Comment by lsm5** [comment]
thanks all!

**Pull request merged**
