### PR TITLE
Switch all references to github.com/containers/libpod -> podman

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Is this going to break go modules? @vrothberg

**Comment by rhatdan** [comment]
@mheon It took a while to get this to compile.  I had to rename some stuff in homedir.  Mainly move
 ~/go/src/github.com/containers/libpod -> ~/go/src/github.com/containers/podman

**Comment by vrothberg** [comment]
> Is this going to break go modules? @vrothberg

The module has been renamed as well, so we're good.

> module github.com/containers/podman/v2

BUT it will break @lsm5 's blog post. Once merged, @lsm5 you may need to change the references in your bindings blog post. While the redirect works, the go packages are now renamed and don't resolve anymore.

**Comment by vrothberg** [comment]
Needs a rebase

**Comment by vrothberg** [comment]
I just realized that this change could be a rather big disturbance in the force. As we disable go modules for compilation, we need to follow `$GOPATH` and as we are renaming, all existing already checked out clones won't compile anymore - only after renaming the directory it'll work.

**Comment by vrothberg** [comment]
Luckily there's go modules. Let me change the Makefile a bit to make it work.

**Comment by vrothberg** [comment]
The following patch will make it compile again.

```diff
diff --git a/Makefile b/Makefile
index 0c19e9f65e8f..ace773242f76 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,3 @@
-export GO111MODULE=off
 export GOPROXY=https://proxy.golang.org
 
 GO ?= go
@@ -38,11 +37,7 @@ PRE_COMMIT = $(shell command -v bin/venv/bin/pre-commit ~/.local/bin/pre-commit
 
 SOURCES = $(shell find . -path './.*' -prune -o -name "*.go")
 
-GO_BUILD ?= $(GO) build
-# Go module support: set `-mod=vendor` to use the vendored sources
-ifeq ($(shell go help mod >/dev/null 2>&1 && echo true), true)
-	GO_BUILD ?= GO111MODULE=on $(GO) build -mod=vendor
-endif
+GO_BUILD ?= $(GO) build -mod=vendor
 
 BUILDTAGS_CROSS ?= containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper exclude_graphdriver_overlay
 ifneq (,$(findstring varlink,$(BUILDTAGS)))
@@ -185,14 +180,14 @@ ifeq (,$(findstring systemd,$(BUILDTAGS)))
 	@echo "Podman is being compiled without the systemd build tag. Install libsystemd on \
 		Ubuntu or systemd-devel on rpm based distro for journald support."
 endif
-	$(GO_BUILD) $(BUILDFLAGS) -gcflags '$(GCFLAGS)' -asmflags '$(ASMFLAGS)' -ldflags '$(LDFLAGS_PODMAN)' -tags "$(BUILDTAGS)" -o $@ $(PROJECT)/cmd/podman
+	$(GO_BUILD) $(BUILDFLAGS) -gcflags '$(GCFLAGS)' -asmflags '$(ASMFLAGS)' -ldflags '$(LDFLAGS_PODMAN)' -tags "$(BUILDTAGS)" -o $@ ./cmd/podman
 
 .PHONY: podman
 podman: bin/podman
 
 .PHONY: bin/podman-remote
 bin/podman-remote: .gopathok $(SOURCES) go.mod go.sum $(PODMAN_VARLINK_DEPENDENCIES) ## Build with podman on remote environment
-	$(GO_BUILD) $(BUILDFLAGS) -gcflags '$(GCFLAGS)' -asmflags '$(ASMFLAGS)' -ldflags '$(LDFLAGS_PODMAN)' -tags "${REMOTETAGS}" -o $@ $(PROJECT)/cmd/podman
+	$(GO_BUILD) $(BUILDFLAGS) -gcflags '$(GCFLAGS)' -asmflags '$(ASMFLAGS)' -ldflags '$(LDFLAGS_PODMAN)' -tags "${REMOTETAGS}" -o $@ ./cmd/podman
 
 .PHONY: bin/podman-remote-static
 podman-remote-static: bin/podman-remote-static
```

**Comment by rhatdan** [comment]
@vrothberg added your patch.

**Comment by rhatdan** [comment]
As much as I like rebasing. at some point we need to get this merged.

**Comment by vrothberg** [comment]
> As much as I like rebasing. at some point we need to get this merged.

We can only merge when it's green :^)

**Comment by rhatdan** [comment]
Easier said then done.

**Comment by rhatdan** [comment]
@mheon @vrothberg @edsantiago @cevich Any ideas what is going on special test ginkgo tests are failing with permission denied?

**Comment by edsantiago** [comment]
I'm going to bet this is #6822, in particular the global setting of `GOPATH`. I'm trying hard now to figure out how it worked before, and how to get it working again, but I think it's going to be much faster for @cevich to solve.

**Comment by edsantiago** [comment]
Submitting #7064 as a possible fix. @rhatdan care to rebase on that and retry? I know how much you love rebasing.

**Comment by rhatdan** [comment]
@edsantiago Passes the test with your PR.  Thanks
@mheon @vrothberg @giuseppe @edsantiago @ashley-cui @baude @jwhonce 
BTW, once we merge this, backporting fixes to v2.0 branch is going to become a pain.

**Comment by mheon** [comment]
IMO, let's start cutting v2.1.0 release candidates once we have your `podman image mount` PR landed. We have a fair few new features (timezone support, `--preserve-fds` for `podman run`, the `--userns=keepid` password addition) ready.

**Comment by mheon** [comment]
(And then we can stop doing backports for non-critical issues to v2.0 once the v2.1 release happens)

**Comment by mheon** [comment]
This LGTM though

**Comment by giuseppe** [comment]
needs a rebase

**Comment by edsantiago** [comment]
Tests are green. I don't feel comfortable LGTM'ing this but I sure hope someone else does. How many rebases?

**Comment by vrothberg** [comment]
Note we cannot cherry-pick patches after merging the changes here any more; all references have to changed back to "libpod" for the 2.0 branch.

LGTM but I want @mheon to ACK on the cherry-pick issue.

**Comment by mheon** [comment]
@vrothberg Let's do it, we need to get master switched. We'll have to start being a lot more selective about what we backport.

**Comment by lsm5** [comment]
so this ain't ending up in a v2.0.x tag anytime soon, yes?

**Comment by mheon** [comment]
There's no chance we're backporting *this*, but depending on difficulty we could re-create on the 2.0 branch?

**Pull request merged**
