### PR TITLE
Add support for 'podman inspect' on FreeBSD

### PR DESCRIPTION
**Pull request by dfr**
This also helps with support for 'podman cp' which will be in a later PR.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by dfr** [comment]
Looks like I broke something - I'll debug it and update the PR once I figure out what happened

**Comment by dfr** [comment]
> Looks like I broke something - I'll debug it and update the PR once I figure out what happened

Refactoring changed the ordering of the code in generateInspectContainerHostConfig and broke two of the API tests. That should be fixed now.

**Comment by rhatdan** [comment]
/approve
LGTM
@containers/podman-desktop-maintainers PTAL

**Pull request merged**
