### PR TITLE
fix network cleanup flake in play kube

### LINKED ISSUE #21569: podman stop: rootless netns ref counter out of sync, counter is at -1, resetting it back to 0
```
<+012ms> # $ podman pod rm test_pod
<+328ms> # time="2024-02-08T08:28:16-06:00" level=error msg="rootless netns ref counter out of sync, counter is at -1, resetting it back to 0"
         # 2ef9c5c99f00484285a5a7394e9d276d97c436311f197e7d2a0fa05ea78e69b5
```
Seen mostly in system tests, **BUT ALSO IN E2E TESTS WHERE IT IS IMPOSSIBLE TO DETECT**. Because it happens in test cleanup, where `rm` does not trigger a test failure. So I caught all these by accident. **THIS IS HAPPENING A LOT MORE THAN WE ARE AWARE OF**.

* fedora-38 : sys podman fedora-38 rootless host boltdb
  * PR #21535
    * [02-08 09:30](https://api.cirrus-ci.com/v1/artifact/task/6664771953491968/html/sys-podman-fedora-38-rootless-host-boltdb.log.html#t--00621) in [sys] [700] podman play --service-container
* fedora-39 : int podman fedora-39 rootless host sqlite
    * [02-06 08:21](https://api.cirrus-ci.com/v1/artifact/task/6507554541404160/html/int-podman-fedora-39-rootless-host-sqlite.log.html#t--Podman-kube-play-test-with-reserved-init-annotation-in-yaml--1) in Podman kube play test with reserved init annotation in yaml
    * [01-30 09:16](https://api.cirrus-ci.com/v1/artifact/task/5196874873831424/html/int-podman-fedora-39-rootless-host-sqlite.log.html#t--Podman-kube-play-override-with-tcp-should-keep-udp-from-YAML-file--1) in Podman kube play override with tcp should keep udp from YAML file
    * [01-18 08:40](https://api.cirrus-ci.com/v1/artifact/task/6165486266744832/html/int-podman-fedora-39-rootless-host-sqlite.log.html#t--Podman-kube-play-secret-as-volume-support-multiple-volumes--1) in Podman kube play secret as volume support - multiple volumes
* fedora-39β : sys podman fedora-39β rootless host sqlite
  * PR #20161
    * [10-17-2023 15:39](https://api.cirrus-ci.com/v1/artifact/task/4824180621836288/html/sys-podman-fedora-39β-rootless-host-sqlite.log.html#t--00592) in [sys] podman play --service-container
* rawhide : int podman rawhide rootless host sqlite
    * [02-06 11:21](https://api.cirrus-ci.com/v1/artifact/task/6252698094272512/html/int-podman-rawhide-rootless-host-sqlite.log.html#t--Podman-kube-play-secret-as-volume-support-multiple-volumes--1) in Podman kube play secret as volume support - multiple volumes
    * [02-04 12:39](https://api.cirrus-ci.com/v1/artifact/task/5821207593877504/html/int-podman-rawhide-rootless-host-sqlite.log.html#t--Podman-kube-play-test-restartPolicy--1) in Podman kube play test restartPolicy
* rawhide : sys podman rawhide rootless host sqlite
  * PR #21246
    * [01-12 13:11](https://api.cirrus-ci.com/v1/artifact/task/6754094187020288/html/sys-podman-rawhide-rootless-host-sqlite.log.html#t--00616) in [sys] [700] podman play

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| int(5) | podman(8) | rawhide(3) | rootless(8) | host(8) | sqlite(7) |
| sys(3) |  | fedora-39(3) |  |  | boltdb(1) |
|  |  | fedora-39β(1) |  |  |  |
|  |  | fedora-38(1) |  |  |  |

### PR DESCRIPTION
**Pull request by Luap99**
When using service containers and play kube we create a complicated set of dependencies.

First in a pod all conmon/container cgroups are part of one slice, that slice will be removed when the entire pod is stopped resulting in systemd killing all processes that were part in it.

Now the issue here is around the working of stopPodIfNeeded() and stopIfOnlyInfraRemains(), once a container is cleaned up it will check if the pod should be stopped depending on the pod ExitPolicy. If this is the case it wil stop all containers in that pod. However in our flaky test we calle podman pod kill which logically killed all containers already. Thus the logic now thinks on cleanup it must stop the pod and calls into pod.stopWithTimeout(). Then there we try to stop but because all containers are already stopped it just throws errors and never gets to the point were it would call Cleanup(). So the code does not do cleanup and eventually calls removePodCgroup() which will cause all conmon and other podman cleanup processes of this pod to be killed.

Thus the podman container cleanup process was likely killed while actually trying to the the proper cleanup which leaves us in a bad state.

Following commands such as podman pod rm will try to the cleanup again as they see it was not completed but then fail as they are unable to recover from the partial cleanup state.

Long term network cleanup needs to be more robust and ideally should be idempotent to handle cases were cleanup was killed in the middle.

Fixes #21569

#### Does this PR introduce a user-facing change?

```release-note
Fixed a race which could lead to improper network cleanup when using podman play kube.
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
LGTM, and seems to be passing in CI (#17831, #23275)

**Comment by edsantiago** [comment]
Maybe a stupid question, but is it possible that this PR makes the int-test flake worse? My (unscientific) perception is that 17831 is seeing the "unable to clean network" flake a _lot_ more: [debian](https://api.cirrus-ci.com/v1/artifact/task/4522051002695680/html/int-podman-debian-13-rootless-host-sqlite.log.html), [f40](https://api.cirrus-ci.com/v1/artifact/task/6439599281537024/html/int-podman-fedora-40-root-container-sqlite.log.html), and [rawhide](https://api.cirrus-ci.com/v1/artifact/task/6017386816471040/html/int-podman-rawhide-root-host-sqlite.log.html#t--Podman-pod-start-podman-pod-start-single-pod-by-name--1)

**Comment by Luap99** [comment]
> Maybe a stupid question, but is it possible that this PR makes the int-test flake worse? My (unscientific) perception is that 17831 is seeing the "unable to clean network" flake a _lot_ more: [debian](https://api.cirrus-ci.com/v1/artifact/task/4522051002695680/html/int-podman-debian-13-rootless-host-sqlite.log.html), [f40](https://api.cirrus-ci.com/v1/artifact/task/6439599281537024/html/int-podman-fedora-40-root-container-sqlite.log.html), and [rawhide](https://api.cirrus-ci.com/v1/artifact/task/6017386816471040/html/int-podman-rawhide-root-host-sqlite.log.html#t--Podman-pod-start-podman-pod-start-single-pod-by-name--1)

I don't know, it is possible that callers that didn't call cleanup() due the falling stop call now do correctly call cleanup() so the error might appear in more places. But that should only happen on code paths that use pods. If no pods are used this code should never be called and your logs show normal containers without any pods failing too so I don't see how this would be related.

**Comment by mheon** [comment]
I'm going to merge to get this ready for the release.
/lgtm

**Comment by mheon** [comment]
The mergebot appears to be broken?

**Pull request merged**
