### PR TITLE
Bump to v4.0.0-RC1

### PR DESCRIPTION
**Pull request by mheon**
This is the first RC of v4.0.0. Release notes will be published for a subsequent release, once Netavark is ready for testing.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
Uh... Did the bot forget who our approvers are?

**Comment by mheon** [comment]
Slapped the label on manually

**Pull request merged**
