### PR TITLE
remove github.com/docker/libnetwork dependency

### PR DESCRIPTION
**Pull request by tyler92**
Code from this dependency was replaced with a simple version. As a
result Podman's memory consumption has been reduced by ~10%.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

Before changes:

```
    VSZ   RSS COMMAND
1631612 41056 ./podman system service -t 0
```

After (see RSS section):

```
    VSZ   RSS COMMAND
1631344 36012 ./podman-fix system service -t 0
```

### CODE REVIEW

**Comment by tyler92** [comment]
Please let me know if it is micro-optimization and if such a commit won't be considered useful.

**Comment by rhatdan** [comment]
No this is great thank you very much @tyler92 
LGTM
@vrothberg @mheon @Luap99 @giuseppe PTAL

**Comment by tyler92** [comment]
> @mheon added "release-note-none" and removed "lgtm" "approved" labels

Is something wrong or it's a mistake?

**Comment by mheon** [comment]
Don't know how LGTM/approved were removed, only wanted to get rid of the release-note-label-needed hold

**Pull request merged**
