### PR TITLE
Add a Windows Installer patch to avoid unrequested reboots

### LINKED ISSUE #24735: The Windows installer triggers a reboot when upgrading from 5.3.1 and WSL is not installed
### Issue Description

[This change](https://github.com/containers/podman/pull/24624/commits/7162c58ba24f6310a9b1fee52ce83340f4646ea9) introduced in 5.3.1 to the [`ForceReboot` action](https://learn.microsoft.com/en-us/windows/win32/msi/forcereboot-action) in the `InstallExecuteSequence` 

```diff
<InstallExecuteSequence>
--    <ForceReboot Before="StopServices" Condition="(NOT Installed) AND ...
++    <ForceReboot Before="StopServices" Condition="(NOT WIX_UPGRADE_DETECTED) AND (NOT BURNMSIUNINSTALL) AND ... 
</InstallExecuteSequence>
```

has avoided triggering a reboot when upgrading from 5.3.0 to 5.3.1. However, the reboot will be initiated in future releases when upgrading from 5.3.1. 

Adding back the condition `(NOT Installed)` fixes the problem for future releases. But it doesn't help if a user has already installed 5.3.1. 

When upgrading from 5.3.1 to a new version, current bundle features are uninstalled, and the reboot is triggered:

```log
MSI (s) (84:38) [19:05:24:587]: Doing action: UnpublishFeatures
Action ended 19:05:24: ProcessComponents. Return value 1.
Action start 19:05:24: UnpublishFeatures.
MSI (s) (84:38) [19:05:24:589]: Doing action: ForceReboot
Action ended 19:05:24: UnpublishFeatures. Return value 1.
Action start 19:05:24: ForceReboot.
...
```

Image

**Note that when the installer is run in non-interactive mode using `.\podman-5.4.0-dev-setup.exe /install /quiet` the reboot happens automatically, without any user prompt. And that's how podman desktop, winget, scoop etc...install Podman**

### There are a few things that need to be investigated:

- [ ] Can the next release installer avoid the 5.3.1 installer forcing a reboot? [Related discussion in WiX forum](https://github.com/orgs/wixtoolset/discussions/8854) and [PR to fix it](https://github.com/containers/podman/pull/24778).
- [ ] How can `WSL_INSTALL=1` be true in the ForceReboot condition if `WITH_WSL` is set to zero? Is that because `ForceReboot` condition is evaluated before `<SetProperty Id="WSL_INSTALL"...`? 
- [ ] Why isn't the reboot triggered when Hyper-V isn't installed? Does the `CheckHyperV` always set `HAS_HYPERVFEATURE` to `true`, even if `vmms` is not installed?
- [ ] Add automated tests to verify upgrades from `main` branch version to a future version (that we would have helped identify the problem earlier)
- [ ] This problem was first spotted on [PR checks after 5.3.1 release](https://cirrus-ci.com/task/4686343773618176). But isn't WSL pre-installed on the VM where these tests run?

### Steps to reproduce the issue

Steps to reproduce the issue
1. Uninstall WSL if it's locally installed
2. Install Podman version 5.3.1
3. Build the installer from main branch (run `.\winmake.ps1 podman; .\winmake.ps1 win-gvproxy; .\winmake.ps1 docs;  .\winmake.ps1 installer`)
3. Update Podman (run `.\contrib\win-installer\podman-5.4.0-dev-setup.exe /install /log podman-installer.log`)

### PR DESCRIPTION
**Pull request by l0rd**
### The problem

When upgrading from v5.3.1 to a new version on a Windows machine without WSL, the installer asks to reboot. This problem doesn't impact users because v5.3.1 is the last release, but it is blocking the release v5.3.2.

### Why it happens

The `ForceReboot` action in the v5.3.1 package is executed during a "major upgrade" to a new version (if WSL is not installed).

### Changes introduced by this PR

- Fix the `ForceReboot` action condition to avoid it during updates
- Add a [Windows Installer patch](https://wixtoolset.org/docs/tools/patches/) for the already released `v5.3.1` so that updates from that version don't trigger an unrequested reboot.
- Bump the WiX version to 5.0.2
- Add tests for upgrades to next version
- Add tests for upgrades from v5.3.1 (minor upgrade)

⚠️ To build the Windows installer from this PR branch (to test the PR), build the `v5.3.1` locally first because of [this issue](https://github.com/containers/podman/issues/24833) and change the Product ID in `podman.wxs` (as described in this PR `contrib/win-installer/README.md` preparation section).

This PR supersedes #24778

Reference:  https://github.com/orgs/wixtoolset/discussions/8854
Fixes #24735

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by l0rd** [comment]
@inknos @lsm5 @containers/podman-maintainers PTAL

**Comment by l0rd** [comment]
cc @n1hility if you have the chance to give it a look.

**Comment by Luap99** [comment]
I cannot really review any of these changes but please mark this as `Fixes #24735` so this PR will be properly linked and the issue will be closed.

**Comment by baude** [comment]
not a wix SME but LGTM

**Pull request merged**
