### PR TITLE
Refactor podman to use c/common/pkg/report

### PR DESCRIPTION
**Pull request by jwhonce**
All formatting for containers stack moved into one package
This does not correct issue with headers when using custom tables

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by ParkerVR** [comment]
lgtm, does the refactor hit all the cases is podman and/or are there implementations outside of podman for MatchesJson...?

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
but all kinds of red tests.  I'm seeing that in a lot of Podman PR's today, I'm not sure if there's a generic test issue or not.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
