### PR TITLE
Update c/storage to v1.23.2

### PR DESCRIPTION
**Pull request by mheon**
As the title says. Includes an important fix for `podman system service` tests. It doesn't seem to hit us on master, but it bit pretty badly on the v2.0 branch, which suggests a race to me - and while we may not hit it today, we should still fix it.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by giuseppe — COMMENTED** [review]
LGTM

/retest

**Comment by mheon** [comment]
Rebased, CI should go green.

**Pull request merged**
