### PR TITLE
Bump to v2.1.1-dev

### PR DESCRIPTION
**Pull request by mheon**
Bump the development version of the new v2.1 branch

### CODE REVIEW

**Comment by mheon** [comment]
@rhatdan @vrothberg @baude Any ideas on the error in `build_each_commit` here?

**Comment by mheon** [comment]
@cevich Do we need to do anything to set Cirrus base branch on the new v2.1 branch to get CI up?

**Comment by edsantiago** [comment]
```
Failed to start an instance! Failed to pull quay.io/libpod/rpmbuild:v2.1 image! Repository does not exist or may require authentication.
```
@cevich ptal

**Comment by cevich** [comment]
Oh! yes, that...

**Comment by cevich** [comment]
...Okay I tagged that old image with `v2.1`, and re-ran the job.  This is fixed in the new CI setup already.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
