### PR TITLE
DO NOT MERGE Test new CI images

### PR DESCRIPTION
**Pull request by edsantiago**
Source: https://github.com/containers/automation_images/pull/371

@Luap99 FYI

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
NONE
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Ugh. Both are timeouts in a local-registry-related test, and both show this on `stop`:
```
Error: writing blob: adding layer with blob "sha256:xxx": unpacking failed (error: exit status 1; output: archive/tar: invalid tar header)
```
`tar` on rawhide bumped to `1.35-4`.  Not sure if that's coincidental or related. Will try to look later this evening.

**Comment by edsantiago** [comment]
Reproduces 100% on 1mt, rawhide, rootless, both with default tar (`1.35-4`) and `dnf downgrade https://kojipkgs.fedoraproject.org//packages/tar/1.35/3.fc40/x86_64/tar-1.35-3.fc40.x86_64.rpm`, including the `invalid tar header` message. `tar` is not the culprit.

This is starting to sound familiar, like maybe one of the recent containers-something PRs?

**Comment by Luap99** [comment]
I noticed there were no exit code checks for the push commands, I don't think that is the issue but still let's try with that.

I would think something like zstd:chunked without composefs is causing the issues here... but we would need to diff the containers.conf file here.

**Comment by Luap99** [comment]
> Error: writing blob: adding layer with blob "sha256:xxx": unpacking failed (error: exit status 1; output: archive/tar: invalid tar header)

I think this is actually expected, both test should fail here with that error as they did no use `--decryption-key`. So the question is why the timeout?

**Comment by Luap99** [comment]
> I would think something like zstd:chunked without composefs is causing the issues here... but we would need to diff the containers.conf file here.

Nevermind, it is our our other favourite `pasta`, switching the network mode for the registry container to slirp4netns seems to make the test pass. 

And looking again it also failed on debian and f40 this time all using passt 2024-07-26.

**Comment by Luap99** [comment]
Created https://github.com/containers/podman/issues/23517 for it

**Comment by Luap99** [comment]
Closing in favour of https://github.com/containers/podman/pull/23518

**Pull request closed without merging**
