### PR TITLE
[2.0] vendor c/image v5.5.2

### PR DESCRIPTION
**Pull request by vrothberg**
Enable pagination until the search result reaches the limit, instead of
returning default 100 limit from registry API.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1866153
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@baude @mheon @QiWang19 PTAL

**Comment by mheon** [comment]
LGTM

**Comment by QiWang19** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
May have missed the PR in my disaster of an inbox, but is this going into upstream too?

**Comment by QiWang19** [comment]
Do we need  to remove the CLI check in this PR? Or I can open a PR after this vendor PR gets merged.
https://github.com/containers/podman/blob/1deb4d1d70efb6d62f4fe5e735c94523f930b6d7/cmd/podman/images/search.go#L106-L108

**Comment by mheon** [comment]
This needs a rebase on latest master, I think.

**Comment by mheon** [comment]
Ah, wait, this is against 2.0 - interesting.

**Comment by mheon** [comment]
Hm. 
`[+0868s] Error: container_linux.go:349: starting container process caused "error adding seccomp rule for syscall socket: requested action matches default action of filter": OCI runtime error`

Exclusively on runc... I think we solved this with a runc bump on master?

**Comment by rhatdan** [comment]
Yup I am seeing the same failure on my v2.0 tests.

@cevich PTAL

**Comment by vrothberg** [comment]
> Do we need to remove the CLI check in this PR? Or I can open a PR after this vendor PR gets merged.
> 
> https://github.com/containers/podman/blob/1deb4d1d70efb6d62f4fe5e735c94523f930b6d7/cmd/podman/images/search.go#L106-L108

Good catch, @QiWang19! I blindly vendored but can fix it here directly :+1:

**Comment by cevich** [comment]
> Yup I am seeing the same failure on my v2.0 tests.
> @cevich PTAL

Yep, I'm on it.  I think #7365 might fix this, but it's just a guess.  I don't think anyone is aware of the actual underlying cause, but I was told it only affects Ubuntu VMs, Bent tried replacing runc, and so the other main difference is an older golang version (on this branch).  If that doesn't work out...sheesh, I dunno where to turn next :confused:

**Comment by vrothberg** [comment]
Rebased on @baude's fixes. Thanks!

**Pull request merged**
