### PR TITLE
[v4.9] Unmaintained branch - Disable CI

### PR DESCRIPTION
**Pull request by cevich**
This branch is no-longer maintained.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
This will need to be merged manually.  The `Total Success` task will never run for this PR.

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
>This will need to be merged manually.

The "Merge pull request" button is grayed out in my view. I see "tide - In merge pool" but no actual progress.

**Review by Luap99 — CHANGES_REQUESTED** [review]
The reason the merge bot and github merge is blocked because they are configured to block on Total Success and because the task is deleted here it will never pass.

However why are we dropping the v4.9 branch? Didn't we just talked about doing another security release today for fedora 39? What am I missing? https://github.com/containers/podman/pull/22794

Fedora 39 will be supported for another 5-6 months.

**Comment by mheon** [comment]
I thought we were disabling nightlies... We might want on 100% removal until F39 ages out as Paul said

**Comment by cevich** [comment]
Thanks for putting a hold on this.  I'm going to close this PR and re-enable the daily CI-maintenance runs.  It seems we need to keep this branch alive until October-ish.

**Pull request closed without merging**
