### PR TITLE
Update podman_tutorial.md

### PR DESCRIPTION
**Pull request by thilop**
The grep wasn't working because of line breaks etc.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
The grep command is one line, the other lines are showing you the output of said command.

**Comment by thilop** [comment]
Well I get:
```

$ podman inspect -l | export LANG=C grep IPAddress\":
            "SecondaryIPAddresses": null,
            "IPAddress": "",
bash: export: `IPAddress":': not a valid identifier
SecondaryIPAddresses:: Befehl nicht gefunden.
IPAddress:: Befehl nicht gefunden.
```

**Comment by TomSweeneyRedHat** [comment]
@thilop what do you get if you do:

`podman inspect -l | grep IPAddress\":`

**Comment by thilop** [comment]
> @thilop what do you get if you do:
> 
> `podman inspect -l | grep IPAddress\":`

```
$ podman inspect -l | grep IPAddress\":
            "IPAddress": "",
```

**Comment by Luap99** [comment]
So it works as expected then. You should only copy the first line, as said the other lines show you the example output.

**Pull request closed without merging**
