### PR TITLE
Bump to v4.0.0-RC2

### PR DESCRIPTION
**Pull request by mheon**
As the title says.

### CODE REVIEW

**Comment by lsm5** [comment]
Would it be ok to get this in after https://github.com/containers/podman/pull/12966 ?

**Comment by mheon** [comment]
Too late (tag's already created, so commit ordering says that won't be in), but we have at least 2 more RCs so we should be fine

**Comment by Luap99** [comment]
Did you update the minimum API version?

**Comment by lsm5** [comment]
> Too late (tag's already created, so commit ordering says that won't be in), but we have at least 2 more RCs so we should be fine

sounds good. thanks

**Comment by mheon** [comment]
@Luap99 I'm hesitant to do it before final, because we're still appending version tags (`4.0.0-dev`, `4.0.0-rc1`) and I don't know what happens if we specify one of those as a minimum version. I do think that `v4.0.0` will definitely prevent a client with v4.0.0-dev as a version from connecting, so we can't do that.

**Comment by Luap99** [comment]
I thought we fixed that so the -dev/-rc is trimmed from the version @jwhonce Do you remember this?

**Comment by mheon** [comment]
Flake in pprof, restarted

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@mheon @Luap99 @baude Is this ready to go?

**Comment by TomSweeneyRedHat** [comment]
LGTM
and all happy green test buttons.  I'll let @mheon push that big shiny merge button and start a toast!

**Pull request merged**
