### PR TITLE
System tests: setup: better cleanup of stray images

### PR DESCRIPTION
**Pull request by edsantiago**
Fix a corner case in basic_setup(), where we rmi stray images.
If a test tags $IMAGE and fails to rmi by tag name, cleanup
could rmi both tag name and IID, wiping out the desired image:

   podman tag $IMAGE foo
   ...
   cleanup: rmi foo $FOO_IID   [this removes $IMAGE!]

Solution: rmi by name, but only rmi by IID if != $IMAGE.

TOTH to ypu for bringing this to my attention.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
@ypu PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by ypu** [comment]
Thanks @edsantiago LGTM and problem resolved :)

**Pull request merged**
