### PR TITLE
Unify --noheading and -n to be consistent on all commands

### PR DESCRIPTION
**Pull request by rhatdan**
Helps with https://github.com/containers/podman/issues/16536

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Support for -n on all listing commands with --noheading option
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by Luap99** [comment]
`podman ps -n` is already defined as `--last` and for other commands used as `--name`, so it will conflict. I would like to avoid adding a shorthand for it. For me this option is only useful for scripts where people should use the full option name anyway IMO.

**Comment by rhatdan** [comment]
Yup, I would have preferred that the shorthand did not exists at all, but for the non ps commands, I would prefer consistency.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
