### PR TITLE
[CI:DOCS] Revert escaped double dash man page flag syntax

### PR DESCRIPTION
**Pull request by Luap99**
Commit 800a2e2d35 introduced a way to disable the conversion of `--`into
an en dash on docs.podman.io, so the ugly workaround of escaping the
dashes is no longer necessary.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@edsantiago any changes necessary to the PR verification scripts to remove the `\-\-` check in md files?  Or did I miss that being reverted in this or the earlier PR?

**Comment by Luap99** [comment]
@TomSweeneyRedHat I revert this in this PR.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 thx!

**Pull request merged**
