### PR TITLE
CI: completion system test: use safename

### PR DESCRIPTION
**Pull request by edsantiago**
Ongoing efforts to make system tests parallel-safe

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
Don't see this as being safer, but more consistent.
/lgtm

**Comment by edsantiago** [comment]
>Don't see this as being safer, but more consistent.

Good point. Excising the `rmi` is safer in terms of parallelization. The `$(safename)` serves two purposes, one being safety similar to `random_string`, the other is for the `leak_check` at the end of a run. Seeing `Leaked volume v-t123-sdfsdf` makes it easy for a human to track down `test 123` and look for volume leaks there. Full context is in #23275.

Anyone know what's going on with CI? Why it's stuck here and in #23275?

**Comment by Luap99** [comment]
> Anyone know what's going on with CI? Why it's stuck here and in https://github.com/containers/podman/pull/23275?

I don't know try to force push and see if that helps.

**Comment by Luap99** [comment]
> > Anyone know what's going on with CI? Why it's stuck here and in #23275?
> 
> I don't know try to force push and see if that helps.

The macos worker pool is down, thus all `Build for MacOS amd64+arm64` cannot run all task depending on that are blocked. I pinged @cevich about it.

**Review by Luap99 — COMMENTED** [review]
/lgtm

**Pull request merged**
