### PR TITLE
create: support images with invalid platform

### PR DESCRIPTION
**Pull request by vrothberg**
Much to my regret, there is a number of images in the wild with invalid
platforms breaking the platform checks in libimage that want to make
sure that a local image is matching the expected platform.

Imagine a `podman run --arch=arm64 fedora` with a local amd64 fedora
image.  We really shouldn't use the local one in this case and pull down
the arm64 one.

The strict platform checks in libimage in combination with invalid
platforms in images surfaced in Podman being able to pull an image but
failing to look it up in subsequent presence checks.  A `podman run`
would hence pull such an image but fail to create the container.

Support images with invalid platforms by vendoring the latest HEAD from
containers/common.  Also remove the partially implemented pull-policy
logic from Podman and let libimage handle that entirely.  However,
whenever --arch, --os or --platform are specified, the pull policy will
be forced to "newer".  This way, we pessimistically assume that the
local image has an invalid platform and we reach out to the registry.
If there's a newer image (i.e., one with a different digest), we'll pull
it down.

Please note that most of the logic has either already been implemented
in libimage or been moved down which allows for removing some clutter
from Podman.

Fixes: #10682
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
/hold
Vendoring my fork of c/common for now (https://github.com/containers/common/pull/634).

**Comment by vrothberg** [comment]
Also fixes: #10648

**Comment by vrothberg** [comment]
Needs a backport to the v3.2 branch.

**Comment by TomSweeneyRedHat** [comment]
Still fighting the good fight with the CI here @vrothberg

**Comment by vrothberg** [comment]
> Still fighting the good fight with the CI here @vrothberg

This one really unfolds like origami :^)

**Comment by vrothberg** [comment]
In case somebody is restarting the jobs, please don't.  They look like infra problems but I want to see the errors.

**Comment by vrothberg** [comment]
Let's see if it's better now.  Finally managed to get the logs of a failing int remote test.

Had to massage the remote pulling code a bit and wire the pull policy through.

**Comment by vrothberg** [comment]
@containers/podman-maintainers merge me

**Comment by mheon** [comment]
LGTM

**Pull request merged**
