### PR TITLE
WIP: Add sigstore sign option to push command

### PR DESCRIPTION
**Pull request by font**
### TODO:
- [ ] Establish correct UX for Sigstore `--sign` option to differentiate between `--sign-by`.
- [ ] Update manpages once proper UX is defined.

ref https://github.com/containers/common/pull/748
ref https://github.com/containers/image/pull/1364

### CODE REVIEW

**Comment by rhatdan** [comment]
@font Any update on this PR?

**Comment by font** [comment]
> @font Any update on this PR?

@rhatdan The large majority of the work is happening in c/image so not much needs to happen here at this point. This PR was just to show an e2e flow. This could almost be closed until the work in c/image is complete.

**Comment by rhatdan** [comment]
@font Where do we stand on this now?

**Comment by font** [comment]
Closing this for now as it's dependent on c/image.

**Pull request closed without merging**
