### PR TITLE
fix duplicated logs command

### PR DESCRIPTION
**Pull request by Luap99**
#### What this PR does / why we need it:

Podman logs was defined twice, once for container logs and once for pod
logs. This causes problems with the shell completion. Also `podman --help`
showed this command twice.

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago Could you please write a test for this. Something like `hack/xref-helpmsgs-manpages`. Basically you need to check if `podman <SUBCOMMAND> --help` prints the same command twice, .e.g:
```
...
  logs        Fetch logs for pod with one or more containers
  logs        Fetch the logs of one or more containers
...
```

**Comment by edsantiago** [comment]
That's trivial. I never imagined it would be possible, and feel silly for not adding a test in the first place. Feel free to incorporate this into your PR if you need to resubmit for any reason; otherwise I can open a PR later.
```diff
diff --git a/hack/xref-helpmsgs-manpages b/hack/xref-helpmsgs-manpages
index 6a2d627bb..fcc88854c 100755
--- a/hack/xref-helpmsgs-manpages
+++ b/hack/xref-helpmsgs-manpages
@@ -242,6 +242,12 @@ sub podman_help {
             if ($line =~ /^\s{1,4}(\S+)\s/) {
                 my $subcommand = $1;
                 print "> podman @_ $subcommand\n"               if $debug;
+
+                if (exists $help{$subcommand}) {
+                    warn "$ME: 'podman @_ help' lists '$subcommand' twice\n";
+                    ++$Errs;
+                }
+
                 $help{$subcommand} = podman_help(@_, $subcommand)
                     unless $subcommand eq 'help';       # 'help' not in man
             }
```

**Comment by Luap99** [comment]
Thanks @edsantiago, nice and simple.

**Comment by rhatdan** [comment]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
