### PR TITLE
test,push: `--force-compression` invert gzip with zstd

### PR DESCRIPTION
**Pull request by flouthoc**
Rawhide now defaults to `zstd:chunked` so revert test to look for gzip after --force-compression

#### Does this PR introduce a user-facing change?

```release-note
None
```

Helps in https://github.com/containers/podman/pull/20610

### CODE REVIEW

**Comment by flouthoc** [comment]
@edsantiago I think this should help

**Comment by rhatdan** [comment]
Can we just examine the default compression in use an alternative.

```
./bin/podman push --help | grep compression-format
      --compression-format string           compression format to use (default "zstd:chunked")
```

```
func compressionLevel() int {
	if registry.IsRemote() || containerConfig.ContainersConfDefaultsRO.Engine.CompressionLevel == nil {
		return 0
	}

	return *containerConfig.ContainersConfDefaultsRO.Engine.CompressionLevel
}
```

**Comment by flouthoc** [comment]
> Can we just examine the default compression in use an alternative.
> 
> ```
> ./bin/podman push --help | grep compression-format
>       --compression-format string           compression format to use (default "zstd:chunked")
> ```
> 
> ```
> func compressionLevel() int {
> 	if registry.IsRemote() || containerConfig.ContainersConfDefaultsRO.Engine.CompressionLevel == nil {
> 		return 0
> 	}
> 
> 	return *containerConfig.ContainersConfDefaultsRO.Engine.CompressionLevel
> }
> ```

@rhatdan I did not get the comment completely did you mean instead of hardcoding `zstd` in test, I should use default compression configured in CLI ? But If default compression `zstd:chunked` then also layer compression will be `zstd` only. `zstd chunked` uses `zstd` compression under the hood.

**Comment by edsantiago** [comment]
I don't get this, will look later, but please note that [system tests are broken too](https://api.cirrus-ci.com/v1/artifact/task/6536081873567744/html/sys-podman-rawhide-root-host-sqlite.log.html). I think the highest priority right now is to revert that rawhide change.

**Comment by rhatdan** [comment]
I am saying the test should not assume the default is either gzip or zstd, but should check the default and then attempt to change it, and make sure the change takes place.

**Comment by TomSweeneyRedHat** [comment]
Maybe I misunderstood, but I thought zstd:chunked was **NOT** going to be supported until Podman v5.0.  Did I miss a change there?  We do not currently have that in a plan for v4.9 that's landing on the next RHEL train.

**Comment by rhatdan** [comment]
It is not in V4.* it is turned on in Rawhide in a containers.conf file to help us find issues.  Rawhide will become F40 and will be shipped with Podman 5.0. The default will not be changed until after we branch for V5.0.

The issues is that for some reason the Fedora Rawhide package has leaked into our test framework.  On the positive side we are finding some issues with our tests and zstd:chunked.

**Comment by vrothberg** [comment]
> The issues is that for some reason the Fedora Rawhide package has leaked into our test framework.

I don't want to be mean but there is another issue: the zstd default change has not been tested in CI at all.  So I perceive the failing tests as something positive as the alternative would be potentially unknown breaking use cases at user sites.

> On the positive side we are finding some issues with our tests and zstd:chunked.

:100: I see it as positive thing as well.  It was worth a shot but given the low test/user coverage of zstd, it's important to have CI run with that as the default as well.

**Comment by flouthoc** [comment]
Is this PR even needed, I saw two different PR where @edsantiago and @giuseppe are working on a related/similar change.

**Comment by flouthoc** [comment]
Closing in favor of https://github.com/containers/podman/pull/20633

**Pull request closed without merging**
