### PR TITLE
[CI:DOCS] Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@cevich 👀 please

**Comment by TomSweeneyRedHat** [comment]
LGTM
but want a head nod from @cevich

**Comment by umohnani8** [comment]
LGTM
@cevich PTAL

**Pull request merged**
