### PR TITLE
[CI:DOCS] Add troubleshooting tip for open files

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Add a troubleshooting note addressing the
too many open files issues noted in this
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1829596

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
My concern here is this might be covering up a leak?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan just realized this has gone stale.  Any adjustments that could be made to the text for the troubleshooting?  Or should we close and forget?  I'd rather adjust or just merge after I rebase.

**Comment by rhatdan** [comment]
Let's talk about this on Monday.

**Comment by vrothberg** [comment]
@TomSweeneyRedHat @rhatdan did you talk about it?

**Comment by rhatdan** [comment]
Nope, lets do this today at standup. (Which I will be late for.)

**Comment by TomSweeneyRedHat** [comment]
Closing per discussions with @rhatdan and @vrothberg .  They're concerned this issue may be something that should be solved rather than band-aided.  Will look at the underlying issue separately once we get a reproducer, it may have been cured with changes to the CNI already as we've not received other reports.

**Pull request closed without merging**
