### PR TITLE
[Fixes #11089] Switch to a new installer approach using a path manipulation helper

### LINKED ISSUE #11089: cleanup PATH on MSI uninstall
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Right now, podman is added to the PATH in windows on install, but this is left after uninstall

**Steps to reproduce the issue:**

1. Install the MSI

2. Uninstall it

3. Look at the PATH

**Describe the results you received:**
the PATH still includes the INSTALLDIR

**Describe the results you expected:**
the PATH should remove the INSTALLDIR on uninstall, even if the PATH was mutated by something else between install and uninstall

**Additional information you deem important (e.g. issue happens only occasionally):**
lines https://github.com/containers/podman/blob/main/contrib/msi/podman.wxs#L34-L35

This has been the case since initial support and so far no one complained  
https://github.com/containers/podman/pull/3999#discussion_r679661880

** Epilogue on another way **
The windows-only WIX toolset treats environment as a first class feature. For example, there is documentation on how to add and remove the INSTALLDIR here:
https://www.firegiant.com/wix/tutorial/com-expression-syntax-miscellanea/environmentally-friendly/

As far as I can tell, this project sets the floor at wix features supported by [GNOME msitools](https://gitlab.gnome.org/GNOME/msitools). This means it works equally on nix and windows, except there is a lowest common denominator concern. FWI I agree with optimizing for GNOME, though it runs into this.

Another way out would be to help GNOME msitools implement the same `Environment` component element and then do it right.  I don't have the chops to do this quickly, but would help review etc any solution including and ideally this!

### PR DESCRIPTION
**Pull request by n1hility**
#### What this PR does / why we need it:

Improves the Windows installation experience and fixes a few issues:

Fixes #11089 - cleanup PATH on MSI uninstall
Additionally fixes scenarios where the path can be overwritten by setx
Also removes the console flash, since the helper is built as a silent gui
Helper executable can be rerun by user to repair PATHs broken by other tools
Utilizes executable location instead of passed parameters to remove delicate escaping requirements

#### How to verify it

1. Install podman msi
2. Check registry
```
reg query hkcu\environment /v path

HKEY_CURRENT_USER\environment
    path    REG_EXPAND_SZ   %USERPROFILE%\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\RedHat\Podman
```
3. Uninstall 
4. Recheck registry

```
reg query hkcu\environment /v path

HKEY_CURRENT_USER\environment
    path    REG_EXPAND_SZ   %USERPROFILE%\AppData\Local\Microsoft\WindowsApps;

```

#### Which issue(s) this PR fixes:
Fixes #11089 

#### Special notes for your reviewer:

None

### CODE REVIEW

**Comment by rhatdan** [comment]
@ashley-cui @jwhonce @baude PTAL

**Comment by n1hility** [comment]
BTW I forgot to mention in case it comes up. The reason this was done as a separate executable as opposed to podman subcommand is to be able to compile it as a GUI application and get rid of the console that splashes and vanishes immediately after during installation. If we decide we do not want to leave the helper executable on the user FS, we can also embed it as a binary element in the installer (config change + switch to path param approach). Although I thought it would be handy to be able to run it outside of installation if needed (fix broken paths, add a path entry for other users, etc)

**Comment by TomSweeneyRedHat** [comment]
I've rerun the failed test, looks to be a flake

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Review by vrothberg — COMMENTED** [review]
Sorry, I can't really review. I have no expertise in Windows at all, the code isn't executed in CI and there are barely any code comments.

But I am OK to merge as long as I don't have to main it :^)

**Comment by n1hility** [comment]
@vrothberg I added some comments and also a little prompt for standalone usage. Let me know if anything looks confusing and needs additional commenting

**Review by vrothberg — COMMENTED** [review]
LGTM, thank you!

Could you rebase on top of the latest HEAD?  The e2e had a flake that has been fixed in the meantime.

**Comment by rhatdan** [comment]
/approve
/lgtm
Thanks @n1hility

**Pull request merged**
