### PR TITLE
test.system: podman run with FIPS enabled

### PR DESCRIPTION
**Pull request by rhatdan**
This test case is used for covering rhbz#1890707.

Replaces: https://github.com/containers/podman/pull/12094

Signed-off-by: Alex Jia <ajia@redhat.com>
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
but definitely want an @edsantiago head nod here.

**Comment by edsantiago** [comment]
I find this whole PR trouble (not your fault, Dan. The whole original PR).

IIUC this is a runc issue, but it's not clear to me that the issue is actually *fixed* in runc (see https://bugzilla.redhat.com/show_bug.cgi?id=1890707#c7). And, the original bug references an elasticsearch image, this PR uses a different one. Has anyone actually brought up a RHEL system with runc and FIPS and run this test to confirm that it fails with the bad version of runc? If it doesn't fail, then this is not a test, it's a very expensive NOP.

And, why the `skip_fips`? If this is a true bug, wouldn't there be value in testing on a regular setup?

And, why the `-e discovery.etc`? That looks to me like a magic setting relating to the `elasticsearch` image, nothing to do with podman or FIPS or the `registry` image used in this PR, and if so it's just a cargo-cult piece of unnecessarily confusing cruft that could mislead a future developer.

There is actually nothing I like about this PR. I would really like to see it abandoned, and replaced with something confidence-inspiring. Sorry.

**Comment by edsantiago** [comment]
Followup: I can't reproduce the error reported in the BZ. Without being able to reproduce the error, there is no way to confirm that this test does what it claims to do. I recommend closing this PR and #12094.

For posterity:
```console
$ 1minutetip -n 1MT-RHEL-8.3.0-released
...
# dnf -y install podman-tests
# wget .../runc-1.0.0-66.rc10.module+el8.3.0+7084+c16098dd.x86_64.rpm then dnf-install it
# fips-mode-setup --enable
# update-crypto-policies --set FIPS:OSPP
[reboot]
# podman run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --name elasticsearch docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2-amd64
[downloads, pauses ~10s, then starts spitting out JSONy log lines]
```

**Pull request closed without merging**
