### PR TITLE
[CI:DOCS] Add performance tutorial

### LINKED ISSUE #14902: Create a Podman performance tips tutorial
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Add a Podman tutorial that discusses factors that might impact the speed of Podman.

Some sketchy ideas:

* use __--uidmap__ and __--gidmap__ instead of the __--volume__ option `:U`
* use `:O` to avoid local disk
* use a fast OCI runtime (crun)
* use a fast storage driver (native overalyfs)
* reuse the package repository cache with an overlay mount when building container images
* network performance for rootless Podman
  + slirp4netns comes with a performance penalty
  + use socket activation to avoid slirp4netns
  + maybe use rootful Podman with `--user $user` (where __$user != 0__) to avoid slirp4netns
* choosing a host file system (is reflink support important?)
*  whether to use the __podman run__ option __--new__
* use smaller container images
* lazy pulling of container images
* benchmark tip: create a separate account with `sudo useradd testuser &&   sudo machinectl testuser@`

### PR DESCRIPTION
**Pull request by eriksjolund**
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

Closes #14902 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by eriksjolund** [comment]
I wrote a very sketchy draft.  
Currently it's very far from being finished.

**Comment by TomSweeneyRedHat** [comment]
The bane of my existence, trailing white spaces!  Other than that, LGTM.  You might consider having this published on the Enable Sysadmin website too, they'd probably be happy to have it.

**Comment by eriksjolund** [comment]
@TomSweeneyRedHat Whitespaces now removed. The document is more of a sketch right now. 
I'm adding some ideas for how such a performance document could look like.

**Comment by vrothberg** [comment]
@TomSweeneyRedHat PTanotherL

**Comment by eriksjolund** [comment]
I copied in some old text from https://github.com/eriksjolund/using-podman-quick-instructions#example-fedora--speed-up-podman-build-by-reusing-the-dnf-metadata-cache  without much thought. My plan was to clean this up a bit. I could take a look over the weekend.

**Comment by eriksjolund** [comment]
The document is still a work-in-progress. I'm still a bit clueless about what type of contents is meaningful to include. I would like to avoid adding information that should be better placed in a more specific document such as basic_networking.md or socket_activation.md.


------------

A side-note: I moved some text out of this PR into
https://github.com/eriksjolund/podman/blob/performance.md_extra_text/docs/tutorials/performance_unused_text.md

The moved text was a mix of
* too obvious
* too general (building smaller containers)
* too much a special case (using :U volume flag)

**Comment by rhatdan** [comment]
@eriksjolund any update?

**Comment by eriksjolund** [comment]
Please suggest removal of text and sections that could be skipped.
I'm really not convinced that all of the text belong in such a document. 

I remove the draft status of the PR.

**Comment by vrothberg** [comment]
@rhatdan are we good to go?

Apologies @eriksjolund, this one fell under the radar.

**Comment by eriksjolund** [comment]
@vrothberg no worries. Feel free to merge, if you think the text makes sense. Also feel free to close the PR or make major additions/changes/deletions. I don't mind if you make major changes as I believe the document could be improved a lot with input from others.

**Pull request merged**
