### PR TITLE
[WIP] Introduce unix socket proxying for Docker API clients

### PR DESCRIPTION
**Pull request by n1hility**
Consider this PR a proposal to generate discussion. Should everyone decide this is the direction to go I can clean it up and add tests.

### Overview

The main goal of this proposal is to add support for clients (such as testcontainers) that do not support ssh (or if they do (e.g. docker compose), they do not support podman's style of ssh which rightly appends the unix socket path to the URI: docker ~~doesn't support unix domain sockets over ssh, only~~ only supports the usage of the host defined default sock or tcp/tls connections nested under ssh)

To achieve this, this PR introduces a new command `podman system unix-proxy`, which operates similarly to podman system service, but instead creates a unix domain socket that points to the specified connection entry (e.g. via -c or the default), provided that connection entry is an ssh destination.

Additionally, it modifies docker machine start to automatically launch two child processes (one for rootless, one for rootful), unless `--nocompat is specified`. It then prints the DOCKER_HOST settings to the screen, so that the user can cut and paste (assumes bash atm). 

Additionally, `init` and `start` will create a symlink to the root socket. This acquires root privileges via sudo on the first usage (reusing thereafter until moby or some other provider reclaims it). This can be disabled by passing --nolink.

Since the proxy is long-running, there is some logic in this patch to auto-reconnect and retry.

### Challenges / Thoughts

- gvproxy is currently noisy, so in the process of waiting for connection availability, which requires polling the connection, it can generate scary looking logs. The machine start code in this patch adds a 1 second sleep to try to hide some of these, but it's marginally effective at suppressing the noise. 
- I am interested in discussions around the security impact of this. My thinking is that it is no less secure than what is achievable via podman connection entries, since the files are created with a umask of 1777, as is the case with the podman system service handler 
- There seems to be a short delay on the first SSH connections (~1 second), this might be related to /dev/random entropy and key negotiation, but I did not dive into that. 
- **Windows Support** - A future PR will add windows support specifics, and possibly named pipe support since unfortunately moby has not yet added support for Windows AF_UNIX

### Example Output (Using compatibility mode)
 ./bin/darwin/podman machine start
INFO[0000] waiting for clients...                       
INFO[0000] listening tcp://0.0.0.0:7777                 
INFO[0000] new connection from  to /var/folders/5p/1gyddrwn4cj6w3ccfy8bj4kr0000gs/T/podman/qemu_podman-machine-default.sock 
Waiting for VM ...
Waiting on SSH to come up..
Waiting on initial proxy connections..
Machine "podman-machine-default" started successfully!

Podman Clients
--------------
Podman clients can now access this machine using standard podman commands.
For example, to run a date command on a *rootless* container:

    podman run ubi8/ubi-micro date

To bind port 80 using a *root* container:

    podman -c podman-machine-default-root run -dt -p 80:80/tcp docker.io/library/httpd

Docker API Clients
------------------
Compatibility socket link is present. Docker API clients require no special environment for *root* containers.

Docker API clients can also access *rootless* podman with the following environment:

    export DOCKER_HOST=unix:///var/folders/5p/1gyddrwn4cj6w3ccfy8bj4kr0000gs/T/podman/podman-machine-default-api.sock

### CODE REVIEW

**Comment by afbjorklund** [comment]
Surely this needs to be opt-in, for modern clients. And then enabled on-demand, for the legacy clients ?

Only clients before Docker 18.09 (such as Java docker) need this workaround, the rest can use SSH...

https://docs.docker.com/engine/release-notes/18.09/#18090
> Added support for remote connections using SSH 

If using the Podman clients instead of the compatibility socket, then these should _never_ be needed.

I had the same issues with gvproxy and waiting on ssh, when trying to add the virtfs mounting feature.

**Comment by afbjorklund** [comment]
I know that right now CoreOS has a feature to let **Docker** handle the docker socket, instead of Podman...

So that might be another reason for "opting in", but it _still_ doesn't need tunneling (just other workarounds\*)

* uninstall moby-engine

* install podman-docker

**Comment by afbjorklund** [comment]
> I am interested in discussions around the security impact of this.

Note that eventually the VM will have access to **all** files in your home directory, as per design (inherited from Docker).

So the created sockets should probably be restricted to the user. Similar to the podman SSH keys, being stored in `~/.ssh`.

**Comment by n1hility** [comment]
> Surely this needs to be opt-in, for modern clients. And then enabled on-demand, for the legacy clients ?
> 
> Only clients before Docker 18.09 (such as Java docker) need this workaround, the rest can use SSH...

Last I checked docker could not use podman ssh URLs as it only supported TCP over ssh and not Unix socket tunneling. I will double check this tomorrow.  

Although IMHO, as long as the negatives are small defaulting to a mode which maximizes compatibility is a good move when you have a potential mass move of users. 

Another approach if it’s decided to disabled by default would be to print the command to cut and paste fo enable it and set DOCKER_HOST.

> 
> https://docs.docker.com/engine/release-notes/18.09/#18090
> 
> > Added support for remote connections using SSH
> 
> If using the Podman clients instead of the compatibility socket, then these should _never_ be needed.

Absolutely agree. It’s redundant in that scenario. Although it does open the door to a wider array of clients. For example you can curl on a host with docker running locally but you can’t in the docker machine / remote case, without first doing podman machine ssh 
> 
> I had the same issues with gvproxy and waiting on ssh, when trying to add the virtfs mounting feature.

Interesting I wonder if (in addition to sending this stuff to the log) there should be an up event that is tied to systemd status.

**Comment by afbjorklund** [comment]
You can use Docker, as long as you remove the socket path and add the ssh key (to the ssh-agent).

However, if you try this stunt with the new Podman Machine it will be Docker Engine answering!

**Comment by n1hility** [comment]
> You can use Docker, as long as you remove the socket path and add the ssh key (to the ssh-agent).
> 
> However, if you try this stunt with the new Podman Machine it will be Docker Engine answering!

Ah right they support their socke


> You can use Docker, as long as you remove the socket path and add the ssh key (to the ssh-agent).
> 
> However, if you try this stunt with the new Podman Machine it will be Docker (Moby) Engine answering!
> 
> ```
> $ podman system connection ls
> Name                         Identity                                    URI
> podman-machine-default*      /home/anders/.ssh/podman-machine-default  ssh://core@localhost:33475/run/user/1000/podman/podman.sock
> podman-machine-default-root  /home/anders/.ssh/podman-machine-default  ssh://root@localhost:33475/run/podman/podman.sock
> $ export DOCKER_HOST=ssh://root@localhost:33475
> $ docker version
> Client: Docker Engine - Community
>  Version:           20.10.8
>  API version:       1.41
>  Go version:        go1.16.6
>  Git commit:        3967b7d
>  Built:             Fri Jul 30 19:54:27 2021
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server:
>  Engine:
>   Version:          20.10.8
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.16.6
>   Git commit:       75249d8
>   Built:            Sun Aug 15 00:00:00 2021
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.5.5
>   GitCommit:        
>  runc:
>   Version:          1.0.1
>   GitCommit:        06fb178
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        
> ```
> 
> You might have expected a Podman service, rather than the Docker daemon ?
> 
> But for that, you need to hack CoreOS (as per above) to replace `docker.sock`

Ah yes they support their sock location only just not custom ones.  Then the next question for the user doing that is does that point to rootless or rootful.

**Comment by afbjorklund** [comment]
> > You can use Docker, as long as you remove the socket path and add the ssh key (to the ssh-agent).
> > However, if you try this stunt with the new Podman Machine it will be Docker Engine answering
> > You can use Docker, as long as you remove the socket path and add the ssh key (to the ssh-agent).
> > However, if you try this stunt with the new Podman Machine it will be Docker (Moby) Engine answering!
> > ```
> > $ podman system connection ls
> > Name                         Identity                                    URI
> > podman-machine-default*      /home/anders/.ssh/podman-machine-default  ssh://core@localhost:33475/run/user/1000/podman/podman.sock
> > podman-machine-default-root  /home/anders/.ssh/podman-machine-default  ssh://root@localhost:33475/run/podman/podman.sock
> > $ export DOCKER_HOST=ssh://root@localhost:33475
> > $ docker version
> > Client: Docker Engine - Community
> >  Version:           20.10.8
> >  API version:       1.41
> >  Go version:        go1.16.6
> >  Git commit:        3967b7d
> >  Built:             Fri Jul 30 19:54:27 2021
> >  OS/Arch:           linux/amd64
> >  Context:           default
> >  Experimental:      true
> > 
> > Server:
> >  Engine:
> >   Version:          20.10.8
> >   API version:      1.41 (minimum version 1.12)
> >   Go version:       go1.16.6
> >   Git commit:       75249d8
> >   Built:            Sun Aug 15 00:00:00 2021
> >   OS/Arch:          linux/amd64
> >   Experimental:     false
> >  containerd:
> >   Version:          1.5.5
> >   GitCommit:        
> >  runc:
> >   Version:          1.0.1
> >   GitCommit:        06fb178
> >  docker-init:
> >   Version:          0.19.0
> >   GitCommit:        
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You might have expected a Podman service, rather than the Docker daemon ?
> > But for that, you need to hack CoreOS (as per above) to replace `docker.sock`
> 
> Ah yes they support their sock location only just not custom ones. Then the next question for the user doing that is does that point to rootless or rootful.

Adding rootless to the mix as well just makes it worse, but it's basically the same circus in /run/user/1000.

The quick hack is ` sudo ln -sf /run/podman/podman.sock /var/run/docker.sock`, the long way is `rpm-ostree`

**Comment by rhatdan** [comment]
We should change podman machine init to disable moby sockets by default and install docker.sock by default within the VM. 
Podman machine should not be running docker at all within the VM,(In a perfect world we convince Fedora CoreOS to replalce Moby with podman-docker.

**Comment by rhatdan** [comment]
I would want a --compat flag on podman machine start, which would tell it to listen in the standard locations where Docker listens.  So the Docker clients would just work. I would guess this would be with a rootfull podman.

**Comment by rhatdan** [comment]
@ashley-cui @baude @jwhonce @flouthoc WDYT?

**Comment by afbjorklund** [comment]
Doing explicit tunneling of the unix sockets with ssh should be a usable workaround, in the meantime ?
(while waiting for Docker to support paths in their host urls, or CoreOS to stop supporting docker engine)

Some runtimes even _prefer_ tunneling, for instance using containerd / buildkitd are _quite_ horrible to use:
https://minikube.sigs.k8s.io/docs/handbook/pushing/#6-pushing-directly-to-in-cluster-containerd-buildkitd

Lima works around this by running `ssh nerdctl`, instead of remoting.

Minikube has a similar workaround, instead of docker-env/podman-env

**Comment by afbjorklund** [comment]
And if one really really wants to, it is also possible to install rootless docker using good ole curlpipesh.

```console
$ podman machine ssh
[core@localhost ~]$ curl -fsSL https://get.docker.com/rootless | sh
...
[INFO] Creating /var/home/core/.config/systemd/user/docker.service
[INFO] starting systemd service docker.service
...
[INFO] Installed docker.service successfully.
[INFO] To control docker.service, run: `systemctl --user (start|stop|restart) docker.service`
[INFO] To run docker.service on system startup, run: `sudo loginctl enable-linger core`

[INFO] Creating CLI context "rootless"
Successfully created context "rootless"

[INFO] Make sure the following environment variables are set (or add them to ~/.bashrc):

export PATH=/var/home/core/bin:$PATH
export DOCKER_HOST=unix:///run/user/1000/docker.sock

```

**Comment by n1hility** [comment]
> I would want a --compat flag on podman machine start, which would tell it to listen in the standard locations where Docker listens. So the Docker clients would just work. I would guess this would be with a rootfull podman.

Good idea I’ll add that to the draft

**Comment by afbjorklund** [comment]
Totally unrelated, but trying to run rootless docker just results in some epic fail.

```console
$ export DOCKER_HOST=ssh://core@localhost:42759
$ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at http://docker.example.com. Is the docker daemon running?
```

Hmm, nice url there. 😀 Wonder if the debugging logs has any more input...

```
DEBU[0000] commandconn: starting ssh with [-l core -p 42759 -- localhost docker system dial-stdio] 
DEBU[0000] commandconn (ssh):failed to open the raw stream connection: dial unix /var/run/docker.sock: connect: permission denied 
DEBU[0000] commandconn: starting ssh with [-l core -p 42759 -- localhost docker system dial-stdio] 
DEBU[0000] commandconn (ssh):failed to open the raw stream connection: dial unix /var/run/docker.sock: connect: permission denied 
DEBU[0000] commandconn: starting ssh with [-l core -p 42759 -- localhost docker system dial-stdio] 
DEBU[0000] commandconn (ssh):failed to open the raw stream connection: dial unix /var/run/docker.sock: connect: permission denied 
DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
```
----

Apparently one is supposed to tweak the login shell, so that it sets the env var.

> To expose the Docker API socket through SSH, you need to make sure $DOCKER_HOST is set on the remote host.



> [INFO] Make sure the following environment variables are set (or add them to ~/.bashrc):
>
> export PATH=/var/home/core/bin:$PATH
> export DOCKER_HOST=unix:///run/user/1000/docker.sock

So **that** is how you are supposed to make rootless connections work, you change the ~core/.bashrc

**Comment by bsideup** [comment]
> Only clients before Docker 18.09 (such as Java docker) need this workaround, the rest can use SSH...

Note that Docker 18.09 has nothing to do with SSH protocol support in Docker clients in languages other than Golang. Each client library (and docker-java is one of them) needs to support SSH transport, and this is not safe to assume that every other client can use SSH.
AFAIK https://github.com/dotnet/Docker.DotNet is another very popular Docker client library that does not support SSH transport.

Just my 2c, and thank you @n1hility for addressing this! 👍

**Comment by afbjorklund** [comment]
> Note that Docker 18.09 has nothing to do with SSH protocol support in Docker clients in languages other than Golang. Each client library (and docker-java is one of them) needs to support SSH transport, and this is not safe to assume that every other client can use SSH.

Seems more safe to assume that they do **not** support SSH, and that most of them is using the legacy HTTPS (2376) still...

**Comment by matejvasek** [comment]
Speaking of `Go` client: I belive that standard `Go` CLI client does support ssh however the `Go` client library doesn't.

**Comment by afbjorklund** [comment]
So only Python SDK then. 😀

Both (CLI and Python) also require that `docker` (client) is installed on the server, even if you don't have to install `dockerd` (server)

**Comment by rhatdan** [comment]
Theoretically we would need to implement this in the podman cli for docker emulation?

**Comment by afbjorklund** [comment]
Seems that way, there was a reference in the Moby code

**Comment by matejvasek** [comment]
Having something like `podman system unix-proxy unix:///tmp/podman.sock` seems like viable solution, just use know about such a sub-command.

**Comment by matejvasek** [comment]
@afbjorklund I am little bit lost in discussion here (I started looking at in just now):
>For some reason, they lost the path support in the urls on the way - original PR did use it, but it doesn't work in what got merged...

what do you mean by that

**Comment by afbjorklund** [comment]
Currently DOCKER_HOST fails, if you include a socket path

**Comment by matejvasek** [comment]
And even if `moby` supported path part it sill requires additional binary to be present on server (basically `socat`), also as you mentioned we cannot expect that every docker API client support ssh.

**Comment by matejvasek** [comment]
I would be best to automatically proxy socket from the VM into `/var/run/docker.sock` upon `podman machine start`. But I don't know if that's feasible.

**Comment by afbjorklund** [comment]
It will be a flag

See https://github.com/containers/podman/pull/11643#issuecomment-922252507

**Comment by n1hility** [comment]
> I would want a --compat flag on podman machine start, which would tell it to listen in the standard locations where Docker listens. So the Docker clients would just work. I would guess this would be with a rootfull podman.

I finally got around to implementing this. I also updated the notes in the PR.

**Comment by matejvasek** [comment]
```go
	callback := ssh.InsecureIgnoreHostKey()
	if secure {
		host := _url.Hostname()
		if port != "22" {
			host = fmt.Sprintf("[%s]:%s", host, port)
		}
		key := terminal.HostKey(host)
		if key != nil {
			callback = ssh.FixedHostKey(key)
		}
	}
```
Actually it looks like that if the key is not known then `ssh.InsecureIgnoreHostKey()` is used, which doesn't sound much secure.
Yeah I know it's not code from this PR.

**Comment by n1hility** [comment]
> ```go
> ```go
> 	callback := ssh.InsecureIgnoreHostKey()
> 	if secure {
> 		host := _url.Hostname()
> 		if port != "22" {
> 			host = fmt.Sprintf("[%s]:%s", host, port)
> 		}
> 		key := terminal.HostKey(host)
> 		if key != nil {
> 			callback = ssh.FixedHostKey(key)
> 		}
> 	}
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Actually it looks like that if the key is not known then ssh.InsecureIgnoreHostKey() is used, which doesn't sound much secure.
> Yeah I know it's not code from this PR.
> ```

Right there is a secure URL parameter in connection definitions to enable it. In the case of podman machine, and other situations where you have a host in a VM, I think it's not critical since traffic is directed locally.

**Comment by matejvasek** [comment]
>@matejvasek Right there is a secure URL parameter in connection definitions to enable it. In the case of podman machine, and other situations where you have a host in a VM, I think it's not critical since traffic is directed locally.

fair enough

**Comment by n1hility** [comment]
Question for the pile:

Should I add graphical dialog auth support on MacOS when --compat needs to create the link and there is no tty (would support biometric and watch auth)?

**Comment by n1hility** [comment]
> Seems that way, there was a reference in the Moby code
> 
> https://github.com/moby/moby/blob/master/client/client.go#L286

@afbjorklund Just to clarify this point (and not to argue we should not add dial-stdio support). This is only required for podman to support docker clients that use DOCKER_HOST to point to SSH of a podman system. If they point it to a unix socket (e.g. with the proxy, or the default with the compatibility unix socket) this is not required. Is that accurate?

**Comment by afbjorklund** [comment]
That seems accurate, so in that sense it is somewhat off topic. The ssh socket is still needed for other clients.

But the `ssh:` syntax was added in 2018, in order to **not** have to set up manual SSH tunnels, that is the relation.

**Comment by Luap99** [comment]
Why do we need the proxy logic inside podman, this could use ssh to proxy a socket, e.g. `ssh -nNT -L/local/path/podman.sock:/run/user/1000/podman/podman.sock ssh://user@host`

**Comment by matejvasek** [comment]
@Luap99 I believe that having it automatically set up by `podman machine` is much more convenient to user.

**Comment by matejvasek** [comment]
Otherwise there would be each week new issue from some new user asking how to use docker client with `podman` VM, we will have to explain ssh tunneling all over again.

**Comment by Luap99** [comment]
Podman machine can still do this automatically by calling the ssh command. This commit add a lot of logic just to create proxy.

**Comment by matejvasek** [comment]
Ah I see, well there is already ssh logic for libpod so why not to use it?

**Comment by matejvasek** [comment]
Or you mean logic for unix socket serving?

**Comment by n1hility** [comment]
> Why do we need the proxy logic inside podman, this could use ssh to proxy a socket, e.g. `ssh -nNT -L/local/path/podman.sock:/run/user/1000/podman/podman.sock ssh://user@host`

Good question. The benefits of this approach are:

1. Improved Compatibility - we don't have to care what version of ssh is on the box, what bugs it has, what user configuration it has, where it's located, etc
2. Consistency - As @matejvasek mentions this reuses the connection binding ssh client, so 100% equivalent behavior. We don't have to keep redundant sections of code in sync (making sure the ssh command line policy + whatever defaults it currently has semantically match the connection code)
3. Improved  Robustness - If the ssh connection drops for whatever reason (vm pause, service timeout etc) we can hold the line with the unix socket client while reestablishing the connection on the backend. 
4. Improved Error Reporting - Since we control all interconnection points, we get a richer interface with error conditions and can translate them appropriately (vs say parsing an ssh log)

From a cost perspective, since the ssh client code is reused it amounts to just the unix socket handling, which is just a basic accept loop and two trivial io copy goroutines to form a pipe.

**Comment by n1hility** [comment]
FYI I split the last commit off into a separate PR since it's orthogonal.  (#11703)

**Comment by Luap99** [comment]
@n1hility Thanks for the detailed answer, this SGTM.

**Comment by n1hility** [comment]
PR rebased against the commit moved to the other PR.

I will include a test for unix-proxy as the next step and reduce some of the verbosity.

**Comment by n1hility** [comment]
So thinking about this a little bit this morning and I think I should move the docker.sock creation and auth to init and warn on start. It could then be on by default prompt the user if the file exists and points elsewhere to ask if sure and overwrite. Then start could warn to re-run init to fix the link if  docker takes it back.

**Comment by n1hility** [comment]
PR is updated to create the symlinks on init by default. Options were added to disable the proxies/sockets and the link if so desired.

**Comment by n1hility** [comment]
Based on some recent discussions we are looking at putting this logic in gvproxy to avoid having extra daemon processes. An initial draft proposal of this is here: https://github.com/containers/gvisor-tap-vsock/pull/58

Closing this PR since it will be superseded.

**Pull request closed without merging**
