### PR TITLE
Vendor in containers/common v0.22.0

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
@QiWang19 This has your fix for mixed case.
@mheon @TomSweeneyRedHat @baude @jwhonce @ashley-cui PTAL

**Comment by QiWang19** [comment]
LGTM

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Pull request merged**
