### PR TITLE
Add logDriver to podman info

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
@rhatdan, since you're fingers are warm: Could you do the same for the events backend/driver?

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
> LGTM
> @rhatdan, since you're fingers are warm: Could you do the same for the events backend/driver?

The eventLogger is already in the info output

**Comment by vrothberg** [comment]
> > LGTM
> > @rhatdan, since you're fingers are warm: Could you do the same for the events backend/driver?
> 
> The eventLogger is already in the info output

Excellent!  Didn't catch when skimming the output.

**Pull request merged**
