### PR TITLE
Add riscv64 support for cross compilation

### PR DESCRIPTION
**Pull request by michalbiesek**
~~- add riscv64 linux static release build~~
~~- update the release-artifacts with riscv64~~
~~- bump containers/ocicrypt to v1.1.8~~
- adding a cross-compilation option for riscv64
- extending GetFcosArch with the riscv64 architecture parameter

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Review by Luap99 — CHANGES_REQUESTED** [review]
> update the release-artifacts with riscv64

Do you need this? We do not add other arches such as 386 or s390x as well so I don't think we should add riscv to the release assets. Mainly because we should not include stuff that was never tested by us and where we have zero idea if it even works.

**Comment by Luap99** [comment]
Also I think you need to run make vendor to fix your vendoring issues.

**Comment by michalbiesek** [comment]
Thanks, it makes sense. I have limited the changes in this Pull Request to the following:
- adding a cross-compilation option for riscv64
- extending GetFcosArch with the riscv64 architecture parameter

**Comment by rhatdan** [comment]
You need to add [NO NEW TESTS NEEDED] to your github message and repush.

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
