### PR TITLE
[CI:BUILD] Add dedicated DOWNLOAD doc w/ links to bins

### PR DESCRIPTION
**Pull request by cevich**
Fixes: https://github.com/containers/podman/issues/15960

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
@containers/podman-maintainers PTAL, especially the ones working on releases

@mheon @ashley-cui WDYT?

**Comment by ashley-cui** [comment]
LGTM, Looks like its useful but definitely needs to be updated if things change.

**Comment by cevich** [comment]
...Oh! and I should probably link to the downloads document from somewhere :blush: ...

**Comment by cevich** [comment]
Force-push: Rebased, added link in `README.md` and comments regarding maintaince.

**Comment by rhatdan** [comment]
LGTM
/approve

**Review by vrothberg — APPROVED** [review]
LGTM
@containers/podman-maintainers PTAL

**Pull request merged**
