### PR TITLE
Remove references and checks for --gpus

### PR DESCRIPTION
**Pull request by rhatdan**
No way to test this unless running on a nvidia platform.

#### Does this PR introduce a user-facing change?

```release-note
noop
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
@mheon @edsantiago @ashley-cui @baude @giuseppe @vrothberg @l0rd PTAL

**Review by giuseppe — APPROVED** [review]
/lgtm

**Comment by edsantiago** [comment]
LGTM

**Pull request merged**
