### PR TITLE
[v3.4] System tests: fix RHEL8 gating tests

### PR DESCRIPTION
**Pull request by edsantiago**
Add a fix for RHEL8 gating tests. This resolves yet another
journald/file events/logger mismatch bug.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
I'm about 80% sure that I have the right branch for RHEL8.6. Would appreciate confirmation or correction.

@jnovy this should fix the gating-test failure we discussed today

**Comment by jnovy** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by edsantiago** [comment]
[Flake](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5126913235615744/html/int-podman-fedora-33-root-container.log.html#t--podman-make-sure-once-container-is-removed--1) was #11682, which is f33-only, so we're sweeping it under the rug, la la la la

**Pull request merged**
