### PR TITLE
Strip key/values of external quotes

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
quadlet will strips quotes around values in quadlets.
```
Fixes: https://github.com/containers/podman/issues/20992

### CODE REVIEW

**Comment by ygalblum** [comment]
I also looked at this issue. The problem is that some keys do require keeping the double quotes. See the hostname.container test which fails.

**Comment by rhatdan** [comment]
I was wondering that.

**Comment by rhatdan** [comment]
After looking at the failures, I think the new code is correct, stripping the quotes. I believe this matches better with systemd.

**Comment by ygalblum** [comment]
> After looking at the failures, I think the new code is correct, stripping the quotes. I believe this matches better with systemd.

You're right. Not sure why, but when I ran it yesterday without the quotes the hostname was not set. I've tested it again and it even makes more sense now. Don't know what went wrong

**Comment by Luap99** [comment]
But is striping the quotes actually the problem? I would think systemd uses some form of escape logic similar to the shell so just stripping does not sounds right. https://www.freedesktop.org/software/systemd/man/latest/systemd.syntax.html

If you look at pkg/systemd/parser/split.go there is already a bunch of code to take care of thie escaping AFAICT so I would assume you would need to use that to correctly parse values.

**Comment by rhatdan** [comment]
@Luap99 I don't see anything obvious there.  Most of those look like something that splits a string into a series of arguments, similar to shlex.

**Comment by Luap99** [comment]
`extractFirstWord()` for example. `LookupAllStrv()` already handles this correctly because it calls into that.

**Comment by rhatdan** [comment]
I don't have time to work on this and it is a simple enough change, that I think we should just merge, and if  you want to open an issue to create a better fix in the future lets open that.

@vrothberg @giuseppe @Luap99 @ashley-cui @mheon @baude @ygalblum @umohnani8 PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by markstos** [comment]
Thanks for this fix! It seems ready to merge, although some MAc and Windows checks failed.

**Comment by mheon** [comment]
Needs a rebase to fix Windows CI, Mac is an expected failure

**Pull request merged**
