### PR TITLE
[2.0] events parsing fix #7078

### LINKED ISSUE #7078: events Rest API changes in v1.12
Previously this used to work, now it returns this error:

```
# curl -s --unix-socket /run/podman/podman.sock http://d/v1.12/events
{"cause":"unexpected end of JSON input","message":"Failed to parse parameters for /v1.12/events: unexpected end of JSON input","response":400}
```

Tested with podman-2.0.3-1.module+el8.3.0+7450+9ea086fe.x86_64

(breaks RHEL-8-3 gating)

### PR DESCRIPTION
**Pull request by vrothberg**
Backports of #7088

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @mheon PTAL

**Comment by mheon** [comment]
LGTM.

I was really hoping not to do another release on the 2.0 branch, though.

**Comment by vrothberg** [comment]
> I was really hoping not to do another release on the 2.0 branch, though.

Sorry, Matt! This one's on me.

Although I was checking if we test events in the apiv2 ones, and we do (https://github.com/containers/podman/blob/master/test/apiv2/rest_api/test_rest_v1_0_0.py#L94). But the `rest_api` part seems to not be part of the CI...

**Comment by rhatdan** [comment]
@mheon Wishful thinking.  RHEL8.3 is still a ways off.

**Comment by vrothberg** [comment]
static build is down ... @cevich looks like an infra hiccup?

**Comment by cevich** [comment]
@vrothberg the most recent run on [the v2.0 branch was successful, including the static_build task](https://cirrus-ci.com/task/5004158564564992).  I'm also seeing the error message change across you're re-runs of the task, so....and the re-run I just did passed just now.  I didn't write that task, and don't know how it works, but I would guess the problem was some kind of hiccup.

**Comment by cevich** [comment]
@rhatdan thanks.

**Comment by vrothberg** [comment]
Thanks for checking, @cevich!

**Pull request merged**
