### PR TITLE
Fix machine starting state

### PR DESCRIPTION
**Pull request by ashley-cui**
Machine starting now is correctly displayed on podman machine list --format json

[NO NEW TESTS NEEDED]

Signed-off-by: Ashley Cui <acui@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Machine starting now is correctly displayed on podman machine list --format json

```

### CODE REVIEW

**Comment by ashley-cui** [comment]
No tests because this has to do with concurrency and I'm not sure how to test this without potential flakes. Open to ideas, but I have no idea how to test this. 

Fixes: https://github.com/containers/podman/issues/14738

**Comment by rhatdan** [comment]
LGTM

**Comment by ashley-cui** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — APPROVED** [review]
/lgtm

**Comment by benoitf** [comment]
hello, can/will it be backported to 4.3 ?

**Comment by vrothberg** [comment]
Yes, anything that merges into main will be part of v4.3.  The release candidate was cut from the main branch.

**Pull request merged**
