### PR TITLE
EMERGENCY: fix broken CI

### PR DESCRIPTION
**Pull request by edsantiago**
Broken by #20827.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by Luap99** [comment]
How can it be that we keep merging things without passing test?!

**Comment by edsantiago** [comment]
Reason: #20980

**Comment by edsantiago** [comment]
/hold cancel

(Mac job is still in progress, but that takes an hour to time out and fail. I choose to executive-decision merge now in order to get everyone's PRs working)

**Pull request merged**
