### PR TITLE
Not use local image create/add manifest 

### PR DESCRIPTION
**Pull request by QiWang19**
Avoid using the image from load storage for `manifest create` and `manifest add`
since the local image does not include other entries of the list from the registry.
`--all` flag of `manifest create` and `manifest add` can not add all of the lists as expected.

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Manifests tests are failing.

**Comment by QiWang19** [comment]
@containers/podman-maintainers PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
