### PR TITLE
Fix CPU usage limitation in play kube for non integer values

### PR DESCRIPTION
**Pull request by tyler92**
Signed-off-by: Mikhail Khachayants <tyler92@inbox.ru>

#### Does this PR introduce a user-facing change?

```release-note
Fix CPU usage limitation in play kube for non integer values
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Wh is this a WIP?
@umohnani8 @haircommander @saschagrunert @mrunalp PTAL

**Comment by tyler92** [comment]
Just wanted to add test next day

**Comment by tyler92** [comment]
I have no idea why test "podman play kube allows setting resource limits" works in CI and doesn't work locally. I mean without my change. This test should fail without my changes but it doesn't with or without my changes.

**Comment by giuseppe** [comment]
Code LGTM, thanks! Please add a test and a reference in the commit message to the previous commit that caused this bug

**Comment by tyler92** [comment]
> a reference in the commit message to the previous commit that caused this bug

Done. Not sure about format, didn't find any related to this in [the goc](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#submitting-pull-requests).

> Please add a test

I wanted to do it. But I'm surprised that the necessary test already exists - "podman play kube allows setting resource limits". It fails without my changes and is green with my PR on my laptop. But in CI this test is always green. Do you have any idea why?

**Comment by rhatdan** [comment]
/approved
I would guess that the tests is not being run or is being run on a cgroup V1 system?

**Review by giuseppe — APPROVED** [review]

**Pull request merged**
