### PR TITLE
healthcheck: do not leak startup service

### PR DESCRIPTION
**Pull request by Luap99**
The startup service is special because we have to transition from startup to the normal unit. And in order to do so we kill oursleves (as we are run as part of the service). This means we always exited 1 which causes systemd to keep us failure and not remove the transitent unit unless "reset-failed" is called. As there is no process around to do that we cannot really do this, thus make us exit(0) which makes more sense.

Of course we could try to reset-failed the unit later but the code for that seems more complicated than that.

Fixes: 0bbef4b830 ("libpod: rework shutdown handler flow")
Fixes: #24351

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago PTAL

**Comment by edsantiago** [comment]
LGTM and fixes two of the non-quadlet leaks (does not fix the one with `rm` but that might be ok).

Would you mind applying [this diff](https://github.com/user-attachments/files/17505907/foo.patch.txt) as a test? It's from my other PR, and is a better way to test moving forward.

**Comment by Luap99** [comment]
I applied the test but modified it slightly, using `systemctl list-units --quiet "*$cid*"` we can only list the units we want to see and then check `$output == ""` which is better in the error case as the logs otherwise list all system units which makes it hard to find the actual leak

**Comment by edsantiago** [comment]
SGTM. I trust `grep` much more than I trust anything systemd-related, so I was playing it safe.

**Comment by mheon** [comment]
LGTM

**Comment by Luap99** [comment]
please do not press blindly re-run, this clearly failed in the newly added test so the check still seems to be racy
https://api.cirrus-ci.com/v1/artifact/task/6597460926136320/html/sys-podman-fedora-40-root-host-boltdb.log.html

/hold

**Comment by Luap99** [comment]
Ok thanks to my cleanup tracer I have some idea (but no way to test it yet), this issue is likely
```
# So, just force a healthcheck run, then confirm that it's running.
run_podman healthcheck run $ctrname
```

This forces a healthcheck run outside of systemd which then races against the one in systemd. If the outside one wins we kill the timer/service , the hc inside the service just started (most likely waiting on the container lock) at this point and thus did not set the exit code to 1 but then get's killed by the outside process causing the failure to stick around.

Maybe we need to fix the cleanup to always remove both timers.

**Comment by mheon** [comment]
Removing both unconditionally doesn't seem like it can hurt as long as we ignore the systemd equivalent of ENOENT, which we should be doing anyways

**Comment by Luap99** [comment]
pushed the same change again to make sure we do not see a flake

**Review by edsantiago — APPROVED** [review]
LGTM. I'm really swamped today (with BoD work, not RH work) but have had a background loop running and I'm reasonably convinced that this fixes the leak in `055:container rm --force doesn't leave running processes`.

**Pull request merged**
