### PR TITLE
[CI:BUILD] rpm: remove dnsname

### PR DESCRIPTION
**Pull request by lsm5**
With CNI going away in v5, there's no need for dnsname in the rpm.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
> These changes end up in podman-next once merged, right?

Yes

> Is there anything to consider when removing a package?

In this particular case, podman-plugins isn't really affecting any other package. So it can be left alone and we can ask users to manually uninstall it and move on.

If we wanna `force` cni users on to nv/av at all, then that's another story.

> I think it might be better to hold this until we have the CNI build tag work done and disable it on default builds. Only then we should merge this as for now CNI will still work with the podman-next copr.

sgtm

> Unless there is a reason to do it now?

no, this can wait.

**Comment by rhatdan** [comment]
@lsm5 @Luap99 What is going on with this PR?

**Comment by lsm5** [comment]
@ashley-cui @Luap99 remind me please, given that we're not doing podman 5 on F 38/39, do we need to care about enabling cni buildtag in the copr build tasks in CI as well as on `rhcontainerbot/podman-next` copr ?

**Comment by Luap99** [comment]
https://github.com/containers/podman/pull/21410 was just merged so this here should be good to go

We do not want to enable cni for 5.0, this will only be done for RHEL 9 AFAIK so we do not break users there. For upstream builds we really do not want to continue to support CNI.

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by lsm5** [comment]
@Luap99 @rhatdan good for merge.

**Pull request merged**
