### PR TITLE
tests: pasta: Mitigation for socat connect() getting EINTR and two other fixes

### PR DESCRIPTION
**Pull request by sbrivio-rh**
See https://github.com/containers/podman/issues/17287. This is a mitigation I want to check against CI, at the moment.

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
@sbrivio-rh LGTM but please rebase at your convenience; we had a CI emergency.

**Comment by edsantiago** [comment]
Thanks @sbrivio-rh! LGTM. @containers/podman-maintainers PTAL

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
