### PR TITLE
Add --filter pod= autocompletion

### PR DESCRIPTION
**Pull request by rhatdan**
Also sorted all of the options in alphabetic order.

Fixes: https://github.com/containers/podman/issues/19967

#### Does this PR introduce a user-facing change?

```release-note
None
```
[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago @Luap99 PTAL

**Comment by edsantiago** [comment]
Thank you! I _was_ going to take a stab at it, you know... :-)

**Comment by edsantiago** [comment]
Results LGTM: my xref script is much, much happier.

**Comment by rhatdan** [comment]
Shouldn't the xref script run all the time to catch these?

**Comment by edsantiago** [comment]
"Much happier" ≠ "happy", in this case it means 30 errors instead of 45.

**Comment by rhatdan** [comment]
Ok, lets hit those 30 errors.

**Pull request merged**
