### PR TITLE
version bump to 4.3.0-dev

### PR DESCRIPTION
**Pull request by lsm5**
v4.2 has been branched already.

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
@rhatdan @baude PTAL

**Comment by mheon** [comment]
Oh, oops.

**Comment by mheon** [comment]
LGTM, let's get this merged

**Comment by lsm5** [comment]
@edsantiago @cevich seen the apiv2 failures on other PRs? I see it on my local env too.

**Comment by vrothberg** [comment]
> @edsantiago @cevich seen the apiv2 failures on other PRs? I see it on my local env too.

Rebasing will make CI happy again.

**Review by vrothberg — COMMENTED** [review]
/lgtm
/hold

**Pull request merged**
