### PR TITLE
pkg/machine/e2e: do not import from cmd/podman

### PR DESCRIPTION
**Pull request by Luap99**
machine test: fix endless loop in test

The problem is that this could loop forever as long as podman start doe
snot exit (which could happen due bugs). Also since there no timeout
between the machine list calls the test is using the full cpu and this
causes the system to slow down making the machine start command even
slower. IMO it is enough to only check the status every three seconds.

pkg/machine/e2e: do not import from cmd/podman

It should be avoided to import cmd/podman/... packages from outside of
cmd/podman. This can lead in weird hard to debug import paths but also
can have negative consequences when imported in unit tests. In this case
it will set XDG_CONFIG_HOME and thus the machine tests this dir over the
tmp HOME env variable which is set at a later point. This caused machine
files to be leaked into the actual users home dir.

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where podman machine start failed to start the qemu VM when the machine name starts with a number. 
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
Restarted one flake

**Comment by baude** [comment]
thanks @Luap99 

/lgtm

**Pull request merged**
