### PR TITLE
Quadlet Kube - add support for PublishPort key

### PR DESCRIPTION
**Pull request by ygalblum**
Move the handling of Publish key to a method
use --publish instead of -p
Use the new method for both .container and .kube files Adjust .container tests
Add .kube tests
Update the man page

Signed-off-by: Ygal Blum <ygal.blum@gmail.com>

#### Does this PR introduce a user-facing change?
No

```release-note
None
```

Resolves: #16595

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM
@containers/podman-maintainers PTAL
@Luap99 @mheon @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@ygalblum Needs a rebase.

**Review by vrothberg — APPROVED** [review]
/hold cancel

**Pull request merged**
