### PR TITLE
[v2.0.5-rhel] System tests: new test for 'pull @sha' + 'images -a'

### PR DESCRIPTION
**Pull request by edsantiago**
Regression test for rhbz1879622, in which 'podman pull' of
an image by @sha would cause subsequent 'podman images -a'
to crash and burn.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Thanks, Ed! I will look at it first thing Monday morning with a fresh pair of eyes.

**Comment by mheon** [comment]
@edsantiago Can you use the `--sort` flag to guarantee ordering?

**Comment by edsantiago** [comment]
>Can you use the --sort flag

TIL, thank you!

**Comment by rhatdan** [comment]
/approve
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by vrothberg** [comment]
Note that the output is always sorted :) I'll take a look at the failing GH action (sorry for that!)

**Pull request merged**
