### PR TITLE
Add support for networking on FreeBSD

### PR DESCRIPTION
**Pull request by dfr**
This adds networking support for FreeBSD containers, including shared networking for containers in a pod (although pod support for FreeBSD will be in a later PR). To allow for this, we create a jail to own the networking resources and the runtime will use that as a parent jail for the containers.

This PR follows a similar pattern to #15632, first adding an implementation derived from the podman-on-freebsd prototype and then iteratively reducing duplication with the linux implementation by moving shared code to networking_common.go.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@Luap99 @mheon @flouthoc @baude PTAL

**Comment by mheon** [comment]
LGTM, though I'm not enough of a FreeBSD expert to comment much on the new FreeBSD network code

**Comment by baude** [comment]
LGTM, in same spot as @mheon

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
@dfr once you have this fully working on FreeBSD I would love to have you demonstrate it as a Podman Cabal meeting, and write a blog on it.

**Comment by dfr** [comment]
> @dfr once you have this fully working on FreeBSD I would love to have you demonstrate it as a Podman Cabal meeting, and write a blog on it.

Thats a great idea.

**Pull request merged**
