### PR TITLE
Revert "Enable win podman-machine test failure"

### PR DESCRIPTION
**Pull request by cevich**
This reverts commit f9e8585c5354748b2a77ed65d214adfe7c6ae5fe.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
@mheon marked a `WIP` as requested.

**Comment by mheon** [comment]
Still waiting on #21339

**Comment by mheon** [comment]
/approve
Oops

**Pull request merged**
