### PR TITLE
utils: takes the longest path on cgroup v1

### PR DESCRIPTION
**Pull request by giuseppe**
now getCgroupProcess takes the longest path on cgroup v1, instead of
complaining if the paths are different.

This should help when --cgroups=split is used on cgroup v1 and the
process cgroups look like:

$ cat /proc/self/cgroup
11:pids:/user.slice/user-0.slice/session-4.scope
10:blkio:/
9:cpuset:/
8:devices:/user.slice
7:freezer:/
6:memory:/user.slice/user-0.slice/session-4.scope
5:net_cls,net_prio:/
4:hugetlb:/
3:cpu,cpuacct:/
2:perf_event:/

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks @giuseppe 

This will fix https://bugzilla.redhat.com/show_bug.cgi?id=1726442

**Comment by vrothberg** [comment]
CI is not yet happy:
>[+1203s] Error: mkdir /sys/fs/cgroup/memory/machine.slice/libpod-bf1e2a75367731b3cf893e42daf86675d1f7b99d22ab1b487795705a328ca07c.scope/supervisor: no such file or directory
[+1203s] output:

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons.

**Comment by TomSweeneyRedHat** [comment]
Ugh, thought this had been merged and backported into v3.0... This solves an 8.4 potential blocker BZ....

**Comment by rhatdan** [comment]
/hold cancel
podman 3.0.* will be what we release to RHEL8.4 so this should get in.

**Comment by giuseppe** [comment]
backport to 3.0: https://github.com/containers/podman/pull/9332

**Comment by chuanchang** [comment]
@giuseppe the tests "podman run with cgroups=split" is failed for downstream podman on RHEL 8.4.

**1:name=systemd:/user.slice/user-0.slice/session-11.scope/supervisor**

```
[root@ibm-x3650m4-01-vm-02 podman]# rpm -q podman crun
podman-3.0.1-1.module+el8.4.0+10073+30e5ea69.x86_64
crun-0.18-1.module+el8.4.0+10073+30e5ea69.x86_64
[root@ibm-x3650m4-01-vm-02 podman]# ll bin/podman
lrwxrwxrwx. 1 root root 15 Feb 23 11:24 bin/podman -> /usr/bin/podman
[root@ibm-x3650m4-01-vm-02 podman]# git rev-parse HEAD
96fc9d983e0fc5bae48c3cec3acce86cdb6e1059

[root@ibm-x3650m4-01-vm-02 podman]# ginkgo -v --focus "podman run with cgroups=split" test/e2e
...ignore...
unning: /root/go/src/github.com/containers/podman/bin/podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/podman_test131803001/crio --runroot /tmp/podman_test131803001/crio-run --runtime crun --conmon /usr/bin/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager systemd --tmpdir /tmp/podman_test131803001 --events-backend file --storage-driver vfs rm -fa
output: 

• Failure [1.709 seconds]
Podman run
/root/go/src/github.com/containers/podman/test/e2e/run_test.go:21
  podman run with cgroups=split [It]
  /root/go/src/github.com/containers/podman/test/e2e/run_test.go:1217

  Expected
      <string>: "...cope/contai..."
  to equal               |
      <string>: "...cope/superv..."

  /root/go/src/github.com/containers/podman/test/e2e/run_test.go:1244
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSintegration timing results
podman run with cgroups=split		1.709453


Summarizing 1 Failure:

[Fail] Podman run [It] podman run with cgroups=split 
/root/go/src/github.com/containers/podman/test/e2e/run_test.go:1244

Ran 1 of 1389 Specs in 199.272 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 1388 Skipped
--- FAIL: TestLibpod (199.41s)
FAIL

Ginkgo ran 1 suite in 3m44.979875003s
Test Suite Failed

[root@ibm-x3650m4-01-vm-02 ~]# podman run --rm --cgroups=split quay.io/libpod/alpine cat /proc/self/cgroup
Trying to pull quay.io/libpod/alpine:latest...
Getting image source signatures
Copying blob 9d16cba9fb96 done  
Copying config 9617696764 done  
Writing manifest to image destination
Storing signatures
12:hugetlb:/user.slice/user-0.slice/session-11.scope/container
11:rdma:/
10:devices:/user.slice/user-0.slice/session-11.scope/container
9:memory:/user.slice/user-0.slice/session-11.scope/container
8:freezer:/user.slice/user-0.slice/session-11.scope/container
7:cpu,cpuacct:/user.slice/user-0.slice/session-11.scope/container
6:net_cls,net_prio:/user.slice/user-0.slice/session-11.scope/container
5:cpuset:/user.slice/user-0.slice/session-11.scope/container
4:perf_event:/user.slice/user-0.slice/session-11.scope/container
3:pids:/user.slice/user-0.slice/session-11.scope/container
2:blkio:/user.slice/user-0.slice/session-11.scope/container
1:name=systemd:/user.slice/user-0.slice/session-11.scope/supervisor
```

**Comment by vrothberg** [comment]
@chuanchang, could you open bugzilla against RHEL 8.4?  We need that for backports now.

**Pull request merged**
