### PR TITLE
Add missing -l equivalent option for --log-level

### PR DESCRIPTION
**Pull request by rhatdan**
Needed for Docker compatibility.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
podman now supports -l as a shorthand option for --log-level

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Found with https://github.com/containers/podman/issues/14917

**Comment by rhatdan** [comment]
Ok, I was wondering if this would conflict. Cobra can not handle it.

**Comment by Luap99** [comment]
> Ok, I was wondering if this would conflict. Cobra can not handle it.

I think you can make it work if you define it as local flag but then it would only accept it as podman --log-level ... command and not podman  command  --log-level ... and therefore could break people. I am sure there is a way to make it work but likely not worth the time unless someone complains loud enough.

**Comment by rhatdan** [comment]
I would doubt people use podman command --log-level (And I would prefer that they didn't) But I agree this is not important enough to catch anyones attention up to now.

**Pull request closed without merging**
