### PR TITLE
Bump to Buildah v1.27.0

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

Vendor Buildah v1.27.0 into Podman in preparation for Buildah v4.2

[No New Tests Needed]

Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
vendor: bump buildah to v1.27.0 ( https://github.com/containers/buildah/releases/tag/v1.27.0 )
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@flouthoc @mheon FYI

**Comment by flouthoc** [comment]
@TomSweeneyRedHat This is atleast need two more commits similar to https://github.com/containers/podman/pull/15234 , i.e implementing new  build options `--cache-from`, `--cache-to` and `--cache-ttl` after that tests deltas must be tweaked to honor newly added tests.

**Comment by flouthoc** [comment]
@TomSweeneyRedHat Pushed two additional commits to this branch using maintainer access in order to save some time.

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Thanks for the assist @flouthoc , much appreciated.
@mheon, happy green test buttons, wanna press the big shiny merge button?

**Pull request merged**
