### PR TITLE
Cirrus: Provide gpg2 in Ubuntu images

### LINKED ISSUE #7347: CI: gpg2: not found in $PATH
One of those "Action recommended" IRC messages. Starting point link is https://cirrus-ci.com/build/5933219147153408

Two of those failures are the horrible nasty Monday 2020-08-17 timeout, but one looks like a different problem: [test ubuntu-20](https://cirrus-ci.com/task/5322509090291712) ([highlighted log](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5322509090291712/html/integration_test.log.html#t--podman-image-trust-show--1)):
```
  podman image trust show
 ...
Running: podman [options] image trust show --registrypath /var/tmp/go/src/github.com/containers/podman/test --policypath /var/tmp/go/src/github.com/containers/podman/test/policy.json
         time="2020-08-17T19:43:46Z" level=error msg="error getting key identity: exec: \"gpg2\": executable file not found in $PATH"
```
I imagine this should be very easy for @cevich to figure out. Probably some sort of difference between the VMs used in testing master vs those used in testing PRs.

### PR DESCRIPTION
**Pull request by cevich**
Fixes #7347

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
@cevich Sadly ubuntu tests failing.

**Comment by cevich** [comment]
sigh, still waiting for a fix I guess.

**Comment by vrothberg** [comment]
@cevich, could you rebase?

**Comment by cevich** [comment]
Yep, just saw that fix go in.  rebasing now...

**Comment by cevich** [comment]
...actually, since the image-building stuff has changed, I need to port this PR over to the "new-way".

**Comment by cevich** [comment]
I've moved this to https://github.com/containers/automation_images/pull/19

**Comment by cevich** [comment]
...actually, on second-thought.  I'll use this PR to reference the newly built images (from other PR).

**Comment by cevich** [comment]
rebased  / force-pushed.

**Comment by cevich** [comment]
@mheon reminder: This is the one w/ images having both crun and runc installed

**Comment by mheon** [comment]
LGTM
@baude @rhatdan @TomSweeneyRedHat PTAL

**Pull request merged**
