### PR TITLE
Fix handling of remote --log-rusage param

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/9889

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by edsantiago** [comment]
Passes the buildah `with-rusage` test in `bud.bats`. LGTM. Thanks for the quick work.

**Comment by edsantiago** [comment]
Tests green. @containers/podman-maintainers PTAL

**Pull request merged**
