### PR TITLE
[CI:DOCS] Update gitleaks baseline w/ harmless findings

### PR DESCRIPTION
**Pull request by cevich**
This should prevent false-positives on any PRs which reference these commits.

For example: https://github.com/containers/podman/actions/runs/7190206757

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
Will-it-work (i.e. test changes using gitleaks container) check passed: https://cirrus-ci.com/task/6007663574646784?logs=prebuild#L103

**Comment by rhatdan** [comment]
@edsantiago @baude PTAL

**Comment by edsantiago** [comment]
@cevich how is this file generated? How will it be updated, maintained, documented?

**Comment by cevich** [comment]
> @cevich how is this file generated? How will it be updated, maintained, documented?

It's documented in `.gitleaks/README.md`, though perhaps not very clear(?)

The process is really simple: Review the github-action workflow run in question (i.e. from notification mail) and ensure there's nothing "bad".  Then you download the "report" artifact attached to the workflow run.  Add it's JSON into the baseline JSON.  All or in part.

Note: The items are commit-specific, so if there's a chance a commit ID could change, don't put that into the baseline.  In other words, it's best to stick to commits already on main.

**Comment by cevich** [comment]
@edsantiago @baude @mheon PTAL.  A few more alerts fired over the holidays that I believe this update would have prevented.

**Comment by mheon** [comment]
LGTM

**Pull request merged**
