### PR TITLE
Quadlet - Support setting UID and GID for --userns=keep-id

### PR DESCRIPTION
**Pull request by ygalblum**
#### Does this PR introduce a user-facing change?
Yes

```release-note
Quadlet - Support setting UID and GID for --userns=keep-id
```

Resolves: #17908

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
@giuseppe @rhatdan PTAL

**Comment by rhatdan** [comment]
Why not just support
RemapUsers=keep-id:uid=100:gid200?

I would rather just see us support this syntax then adding the new Remap classes.  

@giuseppe WDYT?

**Comment by ygalblum** [comment]
> Why not just support
> RemapUsers=keep-id:uid=100:gid200?

Initially that's what I implemented. But, then I looked at how `RemapUsers=auto`  is implemented (using `KeyRemapUID` and `KeyRemapGID`) and decided to align with the same convention

**Comment by giuseppe** [comment]
> Initially that's what I implemented. But, then I looked at how `RemapUsers=auto` is implemented (using `KeyRemapUID` and `KeyRemapGID`) and decided to align with the same convention

I am fine this way if you prefer it, my only concern is that it makes it more difficult to extend the feature in the future if we decide to add more options to `keep-id`.  For example, `userns=auto` supports already quite a few knobs, would these need to be exposed as well?

**Comment by ygalblum** [comment]
> For example, userns=auto supports already quite a few knobs, would these need to be exposed as well?

Quadlet does not have a key that is a one to one assignment to the `userns` argument. So, yes, additional nobs would require new keys.

Keep in mind that the initial thought was that Quadlet would not provide a dedicated key for each and every `podman run` argument or value. Instead, the `Container` section supports a `PodmanArgs` key that is passes as is to `podman run`.

**Comment by vrothberg** [comment]
Should we revisit this design decision and just add a `UserNS` key and deprecate/remove the other ones?

The `--userns` flag is already something very advanced, so it may be more complicated for users having to decompose the `--userns` arguments into multiple Quadlet fields.

**Comment by giuseppe** [comment]
I agree, let's avoid another abstraction

**Pull request merged**
