### PR TITLE
[CI:DOCS] Document update for docker network options via CLI

### PR DESCRIPTION
**Pull request by hasan4791**
Doc update to support docker-specific network create options via CLI

Closes: https://github.com/containers/podman/issues/15830

Signed-off-by: T K Chandra Hasan <t.k.chandra.hasan@ibm.com>

#### Does this PR introduce a user-facing change?
Yes

```
Support for following docker network options via CLI
1. com.docker.network.bridge.name
2. com.docker.network.driver.mtu
```

### CODE REVIEW

**Comment by hasan4791** [comment]
Waiting for the common dep version to be updated.
https://github.com/containers/common/releases/tag/v0.51.0

**Comment by hasan4791** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM
@Luap99 PTAL
/approve

**Comment by TomSweeneyRedHat** [comment]
LGTM
but would like a @Luap99 head nod

**Comment by rhatdan** [comment]
yup

**Pull request merged**
