### PR TITLE
gomod: Update containers/psgo to latest release

### PR DESCRIPTION
**Pull request by cfergeau**
This solves an issue with a non-existing module:

```
$ go mod tidy
[...]
github.com/mitchellh/osext@v0.0.0-20151018003038-5e2d6d41470f: invalid version
```

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
I will cut a new version of psgo with updated dependencies :+1:

**Comment by cfergeau** [comment]
> I will cut a new version of psgo with updated dependencies 👍

Was about to suggest a new release of psgo would be good to have ;) thanks!

**Comment by vrothberg** [comment]
Can you update to https://github.com/containers/psgo/releases/tag/v1.9.0?

**Comment by cfergeau** [comment]
Done :)

**Review by vrothberg — APPROVED** [review]
LGTM
Thank you!

**Comment by cfergeau** [comment]
"Build Each Commit" fails because of
```
* bin/podman grew by 155080 bytes; max allowed is 51200.
```
which can be related to this PR.

The "compose test" failure is unrelated to this PR 
```
Curl error (23): Failed writing received data to disk/application
```

Not sure about "remote rawhide root host sqlite" failures.

**Comment by vrothberg** [comment]
The test failures were (network) flakes, so I restarted the jobs.

The binary growth is something to look into.  Note sure we can trim much but it is very surprising.

**Comment by cfergeau** [comment]
The binary growth is caused by
```
-	github.com/go-logr/logr v1.3.0 // indirect
+	github.com/go-logr/logr v1.4.1 // indirect
```

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
