### PR TITLE
CI: podman farm tests cleanup

### PR DESCRIPTION
**Pull request by edsantiago**
Followup from #20050. Lots of tiny problems in tests, all of
them adding up to significant maintainability problems.

These tests are currently impossible to run in a dev environment,
and super-painful to set up in 1mt, so I've just done a few hours
of cleanup and am giving up for the week.

This is ready for merge, in the sense that it's much better than
what exists now, but it still needs boatloads more work.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
[No more red noise](https://api.cirrus-ci.com/v1/artifact/task/6258383985049600/html/farm-podman-fedora-39%CE%B2-rootless-host-boltdb.log.html)

**Comment by lsm5** [comment]
> Ephemeral COPR build failed. @containers/packit-build please check.

passed on rerun

**Comment by rhatdan** [comment]
/approve
LGTM
@umohnani8 PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
but would like a head nod from @umohnani8

**Comment by umohnani8** [comment]
Late to the party but LGTM. Thanks @edsantiago for fixing these!

**Pull request merged**
