### PR TITLE
Fixes generate kube incorrect when bind-mounting "/" and "/root"

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Fixes https://github.com/containers/podman/issues/9764
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@haircommander @umohnani8 @vrothberg PTAL

**Comment by haircommander** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM, but tests are unhappy

**Comment by zhangguanzhang** [comment]
all had done

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons

**Pull request merged**
