### PR TITLE
use 4.0.2 as version - this is a maintenance branch

### PR DESCRIPTION
**Pull request by jnovy**
[NO NEW TESTS NEEDED]

Signed-off-by: Jindrich Novy <jnovy@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
/approve

**Comment by Luap99** [comment]
Shouldn't there be a 4.0-rhel branch?
I think the 4.0 branch should be used for normal upstream usage.

**Comment by rhatdan** [comment]
I am fine with that also, although I am not sure we are going to differentiate between the two of them, especially once 4.1 is released.

**Comment by vrothberg** [comment]
NACK from my side.  RHEL should use a `-rhel` suffixed branch - which does not exist yet.

**Comment by vrothberg** [comment]
> I am fine with that also, although I am not sure we are going to differentiate between the two of them, especially once 4.1 is released.

RHEL should always use a `-rhel` branch for us not having to ask (or answer) this questions :^) This way, we'll make sure not to screw things up.

**Comment by lsm5** [comment]
How about we create a new branch from commit https://github.com/containers/podman/commit/342c8259381b63296e96ad29519bd4b9c7afbf97 and call it `v4.0-rhel`

**Comment by jnovy** [comment]
The new v.4.0-rhel branch must be at the state of tip of v4.0 (ec2fdb1350c12b2df6aae8189ab97f3b0e94bb8e) without https://github.com/containers/podman/commit/0f626c377aac8f469c8889bdce3ca366ca7ff121

**Comment by lsm5** [comment]
> The new v.4.0-rhel branch must be at the state of tip of v4.0 ([ec2fdb1](https://github.com/containers/podman/commit/ec2fdb1350c12b2df6aae8189ab97f3b0e94bb8e)) without [0f626c3](https://github.com/containers/podman/commit/0f626c377aac8f469c8889bdce3ca366ca7ff121)

I pushed a v4.0-rhel branch upstream with this change. PTAL.

**Comment by lsm5** [comment]
> > The new v.4.0-rhel branch must be at the state of tip of v4.0 ([ec2fdb1](https://github.com/containers/podman/commit/ec2fdb1350c12b2df6aae8189ab97f3b0e94bb8e)) without [0f626c3](https://github.com/containers/podman/commit/0f626c377aac8f469c8889bdce3ca366ca7ff121)
> 
> I pushed a v4.0-rhel branch upstream with this change. PTAL.

@vrothberg @Luap99 @mheon @rhatdan PTAL at the new branch as well.

**Comment by lsm5** [comment]
https://github.com/containers/podman/commits/v4.0-rhel

**Comment by lsm5** [comment]
> LGTM I've rerun the failing test, some kind of network timeout looking for a gateway.

Closing this PR. The v4.0-rhel branch should be good to go for rhel builds.  Please reopen if that was a mistake.

**Comment by vrothberg** [comment]
I just realized that one thing's off: the RHEL branch should be named `v4.0.2-rhel` to be consistent with other branches but I don't think it's a big deal.

**Comment by lsm5** [comment]
> I just realized that one thing's off: the RHEL branch should be named `v4.0.2-rhel` to be consistent with other branches but I don't think it's a big deal.

ack, I created the new branch being under the impression that rhel could get future v4.0 releases, my bad. I could push a new `v4.0.2-rhel` if *need* it.

**Comment by jnovy** [comment]
I'd leave it as it is @lsm5 - based on previous experience maintaining older branches. It might happen that we introduce higher version to v4.0.2, e.g. 4.0.3 (we did that). Then the branch name would start to be confusing. Maybe we should reconsider the upstream RHEL branch naming policy to only vX.Y-rhel @vrothberg ? I can't possibly see any benefit of vX.Y.Z off top on my head at the moment. Let's discuss it.

**Comment by mheon** [comment]
Yeah, let's leave it. Misnamed branches aren't really a problem.

**Pull request closed without merging**
