### PR TITLE
docs: context is not optional for build

### PR DESCRIPTION
**Pull request by vyasgun**
#### Does this PR introduce a user-facing change? Yes

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @vyasgun 
LGTM
/approve

**Comment by edsantiago** [comment]
/hold

Sorry, I don't believe this is correct. Context *can be* optional: the `-f` option removes the need.
```console
$ printf "FROM quay.io/libpod/testimage:20221018\nRUN date\n" | bin/podman build -f - 
```

**Comment by rhatdan** [comment]
That removes the need for a Containerfile, not a context directory.

**Comment by edsantiago** [comment]
I'm having a lot of trouble understanding that sentence, so I will focus my comments on the effects of this PR.

This PR removes the brackets around `[CONTEXT]` in the help message and man page synopsis. The effect of removing those brackets is to suggest to readers that `CONTEXT` is a required argument. (I don't care about "context directory". I am talking purely about command-line arguments). This is not an accurate perception, because it is possible to invoke `podman build` with a set of options that eliminate the need for a `CONTEXT` argument. I don't believe this is disputable.

This PR also removes what I believe is a helpful statement, about defaulting to cwd if no `CONTEXT` arg is given.

This is a subtle corner case, and perhaps instead of removing that short paragraph, it could be improved instead?
>When invoked with `-f` and a path to a Containerfile, with no explicit CONTEXT directory, Podman will use the Containerfile's parent directory as its build context.

(This is actually not the same as "current working directory", and I have verified that my assertion above is correct. Podman ignores cwd, it uses the Containerfile parent directory. Trivial to prove.)

**Comment by edsantiago** [comment]
And, side note: @vyasgun, THANK YOU for addressing this! My comments are intended as material for reflection, to find a way to more accurately document the behavior of `podman build` in what is actually a pretty common usage. Your PR and initiative are much appreciated.

**Comment by rhatdan** [comment]
Agree, I was not familiar with that corner case, and I don't know what happens with it is `-f -` Since there really is no directory for the Contanerfile in this case.  Is it the CWD or /tmp?

**Comment by vyasgun** [comment]
@edsantiago Thank you for the review :) I agree, this would have been incorrect without the `-f` being mentioned in the docs and I should have covered it. Should I add back the square brackets around CONTEXT as the newly added description about `-f` flag covers the case when it is optional?

**Comment by edsantiago** [comment]
@rhatdan for the `-f -` case, podman creates a scratch context directory `$TMPDIR/buildahXXXXXXX`. I would like to consider that a corner case of a corner case, stick my head in the sand, la-la-la, pretend it doesn't exist. For `-f /path/to/Containerfile`, I have confirmed multiple times that podman uses `/path/to` as its context directory. (I have not tested podman-remote).

@vyasgun, good question, and I may not be the right person to answer that. I have a moderate (70-80%) predilection for keeping the square brackets because to me seeing `ARG` in help/manpage is strongly indicative that `ARG` is mandatory: that there is no situation in which `ARG` can be skipped. Seeing brackets does not tell me "you can omit it", it tells me "_there are situations_ in which you can omit it". A subtle distinction but, I think, an important one for a reader.

But that's just my preference. Others in the @containers/podman-maintainers team may have different opinions, and theirs will carry more weight than mine.

**Comment by rhatdan** [comment]
I agree with @edsantiago keep the `[]` brackets to indicate that  it can be optional.  But fix the documentation to say when it is optional

**Comment by vyasgun** [comment]
@rhatdan @edsantiago I have made changes as per the comments.

**Comment by flouthoc** [comment]
LGTM

My original take on this was that we keep man page in compat with docker https://docs.docker.com/engine/reference/commandline/build/, i.e make `context` or `file` mandatory so new users who refer to podman's man page have no confusion but after looking at @edsantiago's argument I agree with him that we must document podman's current behavior as is no it does not breaks and old new users both.

**Comment by edsantiago** [comment]
LGTM too. Thank you @vyasgun!

**Pull request merged**
