### PR TITLE
Remove unused code from libpod

### PR DESCRIPTION
**Pull request by Luap99**
The libpod package should only compile on linux. The remote client
should never try to import this package.

Since these files do not add any value we should remove them, this
prevents people from accidentally importing this package because it would
fail to compile on windows/macos.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM should help us from accidently sucking it into the podman-remote code base.

**Comment by mheon** [comment]
LGTM!

**Comment by mheon** [comment]
`[+1771s] [Fail] Podman unshare [It] podman unshare exit codes `

Been seeing this one failing on a bunch of PRs. @edsantiago Potential new flake?

**Comment by Luap99** [comment]
> `[+1771s] [Fail] Podman unshare [It] podman unshare exit codes `
> 
> Been seeing this one failing on a bunch of PRs. @edsantiago Potential new flake?

Yes definitely a new flake, the actual problem is this warning message `time="2021-09-17T09:29:20-05:00" level=warning msg="Failed to add pause process to systemd sandbox cgroup: mkdir /sys/fs/cgroup/devices/user.slice/user-2604.slice: permission denied"` added in https://github.com/containers/podman/pull/11606
@giuseppe PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the tests are hip

**Comment by rhatdan** [comment]
@edsantiago we have a new flake caused by the podman unshare exit code test.

[+1604s]       <string>: time=\"2021-09-17T16:07:41-05:00\" level=warning msg=\"Failed to add pause process to systemd sandbox cgroup: mkdir /sys/fs/cgroup/pids/user.slice/user-9141.slice/user@9141.service/user.slice: permission denied\"

For some reason once in a while the cgroups  are failing to be checked.
@giuseppe Thoughts.

**Comment by giuseppe** [comment]
> [+1604s] : time="2021-09-17T16:07:41-05:00" level=warning msg="Failed to add pause process to systemd sandbox cgroup: mkdir /sys/fs/cgroup/pids/user.slice/user-9141.slice/user@9141.service/user.slice: permission denied"
> 
> For some reason once in a while the cgroups are failing to be checked.
> @giuseppe Thoughts.

opened a PR: https://github.com/containers/podman/pull/11648

**Pull request merged**
