### PR TITLE
vendor latest containers/common

### PR DESCRIPTION
**Pull request by vrothberg**
We had a couple of regressions in containers/common in the last release.
Before cutting a new release, let's vendor it here.  Since 3.0 has been
branched, we can vendor a non-release commit of c/common.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@ashley-cui PTAL. Ideally this turns green before you sit at the keyboard.  A rebase ontop should turn your PR green.

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by ashley-cui** [comment]
LGTM

**Comment by vrothberg** [comment]
> LGTM

Can you "/lgtm"?

**Pull request merged**
