### PR TITLE
Move golang requirement from 1.18 to 1.20

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @vrothberg @baude @mheon @n1hility @ashley-cui @umohnani8 @lsm5 @Luap99 PTAL

**Comment by ashley-cui** [comment]
LGTM

**Comment by mheon** [comment]
Is there a reason for this beyond the simplification? And are we going to lock any distros out of support by hard-requiring 1.20?

**Comment by edsantiago** [comment]
I think the justification is in #21048. TL;DR 1.18 and 1.19 are EOL, and it looks like podman won't even build with 1.18 anyway.

**Comment by rhatdan** [comment]
Yes some of the vendor packages now require podman 1.20.

**Comment by mheon** [comment]
Ack, LGTM then

**Comment by edsantiago** [comment]
Awful lot of noise on this PR coming from people who ought to be celebrating birthdays and, in one case, PTO...

/lgtm
/hold

**Pull request merged**
