### PR TITLE
[v5.2-rhel] Add --health-max-log-count, --health-max-log-size, --health-log-destination flags

### PR DESCRIPTION
**Pull request by Honny1**
These flags can affect the output of the HealtCheck log. Currently, when a container is configured with HealthCheck, the output from the HealthCheck command is only logged to the container status file, which is accessible via `podman inspect`. It is also limited to the last five executions and the first 500 characters per execution.

This makes debugging past problems very difficult, since the only information available about the failure of the HealthCheck command is the generic `healthcheck service failed` record.

- The `--health-log-destination` flag sets the destination of the HealthCheck log.
  - `none`: (default behavior) `HealthCheckResults` are stored in overlay containers. (For example: `$runroot/healthcheck.log`)
  - `directory`: creates a log file named `<container-ID>-healthcheck.log` with JSON `HealthCheckResults` in the specified directory.
  - `events_logger`: The log will be written with logging mechanism set by events_loggeri. It also saves the log to a default directory, for performance on a system with a large number of logs.

- The `--health-max-log-count` flag sets the maximum number of attempts in the HealthCheck log file.
  - A value of `0` indicates an infinite number of attempts in the log file.
  - The default value is `5` attempts in the log file.
- The `--health-max-log-size` flag sets the maximum length of the log stored.
  - A value of `0` indicates an infinite log length.
  - The default value is `500` log characters.

Add --health-max-log-count flag

Add --health-max-log-size flag

Add --health-log-destination flag

(cherry picked from commit de856dab99ef8816392972347678fcb49ae57e50)

Fixes: https://issues.redhat.com/browse/RHEL-61962

#### Does this PR introduce a user-facing change?

```release-note
Added --health-log-destination, --health-max-log-count and --health-max-log-size flags that affect HealtCheck log output.
```

### CODE REVIEW

**Comment by Honny1** [comment]
cc: @jnovy

**Comment by TomSweeneyRedHat** [comment]
I have put a hold on this as I don't want this merged until after October 21.  That's when the RHEL ZeroDay packaging will occur.  The card this will address is: https://issues.redhat.com/browse/RHEL-61962

@Luap99 thanks for the eagle eye on that!

**Comment by lsm5** [comment]
@TomSweeneyRedHat is this good to go?

**Comment by TomSweeneyRedHat** [comment]
@lsm5 Yes, it's GTG!  I thought the hold removal would have moved it along, let's try:
/lgtm

**Comment by Luap99** [comment]
You need to approve it as well
/approve

**Pull request merged**
