### PR TITLE
Fix `podman system connection` panic

### PR DESCRIPTION
**Pull request by jwhonce**
Restored local identity flag

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
https://github.com/containers/podman/pull/6937 closed due to GitHub Issue.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by jwhonce** [comment]
@vrothberg This is a bandaid, https://github.com/containers/podman/pull/6938 is a refactor of this code and includes better test coverage.

**Comment by edsantiago** [comment]
I still see an identity flag in `cmd/podman/root.go`, should that be removed?

**Pull request merged**
