### PR TITLE
[v4.0] Cirrus: Update VM Images for 4.0 release

### PR DESCRIPTION
**Pull request by cevich**
This is to ensure VM images for CI, which contain the
intended dependency versions to support the podman
4.0 release.

Ref: https://github.com/containers/automation_images/pull/114

### CODE REVIEW

**Comment by cevich** [comment]
@mheon [I backported a fix](https://github.com/containers/podman/pull/13214) from main here to (hopefully) address failing tests.  Hope this doesn't mess up your release-notes or anything.  Either way, I'm still seeing similar problems (test failures) as in https://github.com/containers/podman/pull/13055

**Comment by cevich** [comment]
Rebased onto https://github.com/containers/podman/pull/13255 (version-bump PR)

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
but I'll let @mheon decide about the merge button press

**Pull request merged**
