### PR TITLE
Merge  `Remove hello multi-arch image build` again with fixed buildah tests.

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago @vrothberg @Luap99 @cevich PTAL

**Comment by Luap99** [comment]
No, please do not remove that!

It is used in countless of maintenance branches, we should not waste time backporting these fixes. There is no problem with keeping this directory here for the time being.

**Review by vrothberg — COMMENTED** [review]
This will break stable branches of Podman and Buildah which still need `./contrib/hello` to be present.

**Comment by edsantiago** [comment]
What they said.

@rhatdan this cannot merge until every single active buildah branch has incorporated your fix, **AND** then every active podman branch has vendored in a buildah that includes your fix. I do not think that is worth anyone's effort. Let's go with #19736 instead. Please do not merge this.

**Comment by cevich** [comment]
Suggest this instead: https://github.com/containers/podman/pull/19736

**Pull request closed without merging**
