### PR TITLE
[v4.9] [skip-ci] Packit: only keep relevant jobs

### PR DESCRIPTION
**Pull request by lsm5**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
I guess I could remove the `epel` targets from here too if we don't care about rhel buildability on this branch.

**Comment by lsm5** [comment]
@TomSweeneyRedHat @mheon @containers/podman-maintainers PTAL

**Review by Luap99 — COMMENTED** [review]
LGTM

**Pull request merged**
