### PR TITLE
Man pages: refactor common options: cert-dir

### PR DESCRIPTION
**Pull request by edsantiago**
...and, tweak markdown-process-review so it can detect and
remove identical files, making review easier.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
more man page deduplication
```

### CODE REVIEW

**Comment by edsantiago** [comment]
This should be reviewable using `./hack/markdown-preprocess-review`

Only 120 options left to go. At two per week, we should be finished by mid-2024...

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by mheon** [comment]
System tests flaked, restarted
/lgtm
/hold

**Pull request merged**
