### PR TITLE
[ci:docs] Update rootless_tutorial.md

### PR DESCRIPTION
**Pull request by rlukin**

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks, but you have to sign your commits.

git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
Adding a little comment about what you are fixing also, would be helpful.

**Comment by edsantiago** [comment]
Thanks for your PR, @rlukin! 

Would you mind running:
```console
$ git commit --amend -s
[add a commit message describing the problem you're addressing with this]
$ git push --force
```
The `-s` will add a `Signed-off-by` footer as required by our [contributing guidelines](https://github.com/containers/podman/blob/master/CONTRIBUTING.md#user-content-sign-your-prs). The commit message will help a future maintenance programmer scrolling through the commit history.

**Comment by rlukin** [comment]
@rhatdan @edsantiago done

**Comment by rhatdan** [comment]
Thanks @rlukin 
LGTM
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
