### PR TITLE
System tests: assert(): friendlier failure messages

### PR DESCRIPTION
**Pull request by edsantiago**
...safer, too: the big change is using 'mapfile' to split
multiline strings; this preserves empty lines, making it
easy to see spurious (or missing) blank lines in output.

Another change is to indent the expected-output string
consistently, for readability.

Then, to handle \r (CR) and other control characters, use
bash %q to format special chars. But %q makes\ it\ hard\ to
read\ lines\ with\ spaces, so strip off those backslashes.
This makes assert() much larger and uglier, but this is
code that shouldn't be touched often.

Finally, because these are big changes to critical code,
write a complicated regression test suite for assert().

Closes: #17509 

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
@Luap99 PTAL. I encourage you to recreate the problems you were seeing (if that's easy) and see if the new error message is easier to understand.

**Review by vrothberg — APPROVED** [review]
LGTM

**Review by Luap99 — APPROVED** [review]
LGTM, thanks
I tested it by adding some special chars to podman logs and the test failure clearly showed them

**Pull request merged**
