### PR TITLE
[WIP] Final backports and release notes updates for v2.0.5

### PR DESCRIPTION
**Pull request by mheon**
Latest batch of backports.

This is not going to pass CI - some `github.com/containers/podman/v2` paths leaked in. I can't figure out how to use `build-each-commit` locally to get find them, so I'm going to let upstream CI do it.

### CODE REVIEW

**Comment by mheon** [comment]
Alright, it's not worth fighting CI. Renamed `github.com/containers/libpod/v2` to `github.com/containers/podman/v2`.

**Comment by mheon** [comment]
```
[+0026s] cmd/podman/containers/stop.go:74:12: cannot use containerStopCommand (variable of type *cobra.Command) as *cobra.Command value in struct literal (typecheck)
```

Thank you, Golint - that's such a helpful message, that.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM over all, but I'm leery about the libpod to podman change.  I think it's OK, but IDK.  @vrothberg any concerns in you mind with that?

**Comment by mheon** [comment]
It looks like I'm missing something necessary to get Cirrus building with the new import paths. Will investigate further tomorrow.

Also, this is still missing the `system connection` patches, which will need more work to get landed.

**Comment by vrothberg** [comment]
> Changes LGTM overall, but I'm leery about the libpod to podman change. I think it's OK, but IDK. @vrothberg any concerns in your mind with that?

We just published the [bindings blog](https://podman.io/blogs/2020/08/10/podman-go-bindings.html) which is using `libpod`. If we want to do the renaming, we could do the same in the blog after the release.

**Comment by vrothberg** [comment]
I want to get https://github.com/containers/image/pull/1025 in as well to close a BZ against podman-search.

**Comment by mheon** [comment]
Given the difficulties CI is giving us, you should have time. Plenty of
time!

**Comment by mheon** [comment]
Build each commit is going to take prohibitively long to fix. I see two options:
- Completely disable it
- Squash every commit in this PR down to one, so the fixes are all included
@rhatdan @baude @vrothberg Opinions?

**Comment by rhatdan** [comment]
Disable check just for this PR.

**Comment by mheon** [comment]
@cevich 
```
[+0146s] go: writing go.mod cache: mkdir /var/tmp/go/pkg: permission denied
[+0146s] go: writing go.mod cache: mkdir /var/tmp/go/pkg: permission denied
```

Any idea what's going on here?

**Comment by cevich** [comment]
ewww, hmmm, that's a new one (to me)...

**Comment by cevich** [comment]
...Not sure why we're just seeing this now/here (and not on master), [but perhaps chown'ing `$GOPATH` instead ](https://github.com/containers/podman/blob/05f98f03fb504d1684c933dbadd4253a5d533684/contrib/cirrus/lib.sh#L319 )might fix it (it would be owned by root otherwise).

**Comment by mheon** [comment]
Closing in favor of #7363

**Pull request closed without merging**
