### PR TITLE
Quadlet - prefer "param val" over "param=val" to allow env expansion

### PR DESCRIPTION
**Pull request by ygalblum**
When possible use a generic function to add strings and booleans
Adjust tests

#### Does this PR introduce a user-facing change?
No

```release-note
None
```

Resolves: #24105

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM, I really like the map approach.

I think for future work we should consider splitting the maps with common options between pod/container out so they both can use the same thing and we do not need to add such option in both places all the time, especially as pod untis currently only supported limed keys. Of course there will still be a bunch of work in adding tests/docs then but hopefully that can be improved as well at some point

**Comment by rhatdan** [comment]
LGTM 
But tests not happy.

**Comment by ygalblum** [comment]
@rhatdan The tests are fine, it's the packit service that's been acting out for a while now. I can see that it's getting 503 when trying to create the build root

**Comment by ygalblum** [comment]
@Luap99 you are right. There is more common code in the `Convert` functions, especially in their beginning.

**Pull request merged**
