### PR TITLE
[CI:DOCS] Update release notes for v2.1.0 Final Release

### PR DESCRIPTION
**Pull request by mheon**
As the title says.

### CODE REVIEW

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by mheon** [comment]
Should be good to merge

**Comment by mheon** [comment]
@baude @rhatdan Anyone want to whack this in?

**Comment by zhangguanzhang** [comment]
need this https://github.com/containers/podman/pull/7675

**Comment by mheon** [comment]
Didn't include it because it fixed a bug we introduced in this release - the release notes only track 2.0 -> 2.1 changes, and that fixed a bug we introduced after 2.0.6 was released.

**Pull request merged**
