### PR TITLE
Fix more "podman-default-kube-network" flakes

### PR DESCRIPTION
**Pull request by edsantiago**
...in "built using Dockerfile" test.

References: Issue #17946, PR #18085

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Link to the [CI failure](https://api.cirrus-ci.com/v1/artifact/task/5407598556479488/html/int-podman-fedora-36-root-host-sqlite.log.html#t--Check-that-image-is-built-using-Dockerfile--1)

**Comment by edsantiago** [comment]
Link to the [second failure that made me edit and repush](https://api.cirrus-ci.com/v1/artifact/task/6700340385415168/html/int-podman-fedora-36-rootless-host-sqlite.log.html#t--podman-play-kube-fail-with-custom-selinux-label--1)

**Review by vrothberg — APPROVED** [review]
LGTM
@Luap99 PTAL

**Review by Luap99 — CHANGES_REQUESTED** [review]
No, this is not the right way to fix it. It will cause a lot more flakes. I just looked at the first two logs and see this: https://api.cirrus-ci.com/v1/artifact/task/4592789598502912/html/int-podman-fedora-36-root-host-boltdb.log.html

Please see https://github.com/containers/podman/pull/17975#issuecomment-1490525106 again. We cannot ever use a custom config when you run containers.

To be explicit:
 As root you can only use a custom network dir when you never run a container with it. Having the same network dir is important to avoid conflict in subnets and interface names which will cause problems at runtime in one way or another. The only exception here is containers that use the default `podman` network, they can be used with a custom network dir because the default network as this is built from memory with always the same values.

**Comment by Luap99** [comment]
To fix these flakes you need to find the test actually deleting the configs. #18085 tried to do it, looks like there are more.

**Pull request closed without merging**
