### PR TITLE
Reuse timezone code from containers/common

### PR DESCRIPTION
**Pull request by rhatdan**
Replaces: https://github.com/containers/podman/pull/21077

[NO NEW TESTS NEEDED] Existing tests should handle this.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM but you have build failures

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the tests get hip

**Comment by rhatdan** [comment]
@dfr PTAL Won't work on freebsd?

**Comment by dfr** [comment]
> @dfr PTAL Won't work on freebsd?

I think this should work on FreeBSD - it uses /etc/localtime in the same way as Linux.

**Comment by dfr** [comment]
I tested this on FreeBSD and it doesn't work correctly - I think the /etc/localtime symlink is wrong:
```
$ sudo ./bin/podman run -ti --rm --tz=America/New_York localhost/freebsd14.0-minimal sh
ERRO[0000] unexpected OS version: 14.0-RELEASE-p4
# date
Thu Jan 25 15:50:25 UTC 2024
# TZ=America/New_York date
Thu Jan 25 10:50:33 EST 2024
# ls -l /etc/localtime
lrwxr-xr-x  1 root wheel 137 Jan 25 15:49 /etc/localtime -> /var/db/containers/storage/zfs/graph/3d995d201f15d80cd00eb481c480da43afd7d7c5bc0e77fce240252dfaddcfef/usr/share/zoneinfo/America/New_York
#
```
(ignore the 'unexpected OS' error - l think thats a bug in one of my PRs from last year)

**Comment by rhatdan** [comment]
@umohnani8 Looks like your filter changes are breaking when containers/common tries to get vendored in.

**Comment by dfr** [comment]
> I tested this on FreeBSD and it doesn't work correctly - I think the /etc/localtime symlink is wrong:

Does the symlink option work correctly on Linux? For me, it includes the full host path to the container's usr/share/zoneinfo directory. Perhaps we should always copy since these files are tiny?

**Comment by rhatdan** [comment]
@dfr working on another fix.

**Comment by dfr** [comment]
The latest iteration with the relative symlink works fine on FreeBSD

**Pull request merged**
