### PR TITLE
Cirrus: Rotate keys post repo. rename

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
`*sigh*` I screwed this all up...got to start over again :cry:

**Comment by edsantiago** [comment]
Would you mind adding this link to your commit message, for the next time this needs to happen?

https://cirrus-ci.org/guide/writing-tasks/#encrypted-variables

**Comment by cevich** [comment]
> Would you mind adding this link to your commit message

Oh sure, good idea.  Though I pray nobody has to do it again, it's a PITA.  Especially when the you need to re-do it all again because you went to *containers/libpod repository settings* like a mindless drone :sob:

**Comment by cevich** [comment]
@mheon @baude okay, this is ready to go pass or fail.  I'll check the other keys after it starts running on the branch.

**Comment by mheon** [comment]
@cevich Can we get this in the v2.0 branch as well?

**Comment by mheon** [comment]
Or, can I just cherry-pick it in myself?

**Comment by edsantiago** [comment]
Per cevich_smoulderi on IRC this morning:  I need to fix it on every branch :S

**Pull request merged**
