### PR TITLE
Vendor in latest containers/image

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @Luap99 @mtrmac We have an issue with the updated containers/image being a little chubby.

**Comment by Luap99** [comment]
I think the problem is the import of `gopkg.in/yaml.v3` which is now included in the binary. Previously it was only a testing dependency.
Now we have both `gopkg.in/yaml.v3` `gopkg.in/yaml.v2` in the binary and thus the extra bloat. I have no idea if we can just update everything to v3, v2 is used in dependencies that we do not control.

**Comment by rhatdan** [comment]
I went down this rabbit whole last week to figure out, lets cleanup our house and then work to get rid of yaml.v2 from upstream packages.

**Comment by rhatdan** [comment]
IE Allow the bloat for now.
WDYT?

**Comment by vrothberg** [comment]
SGTM

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by mtrmac** [comment]
> We have an issue with the updated containers/image being a little chubby.

@rhatdan could you point at what specifically you are looking at, please? I don’t know what needs fixing / how to tell that it was fixed. 

I also don’t understand how the later later conversation about yaml.v3 relates — looking at the `vendor/modules.txt` diff, nothing changes about the presence of that package.

**Comment by mtrmac** [comment]
For reference about yaml.v2 / yaml.v3: https://github.com/containers/skopeo/pull/1656#discussion_r883457586 .

At a fairly quick glance it seems likely that we could completely remove `ghodss/yaml` (which is what brings in `yaml.v2`) and use only `yaml.v3` directly — it would require _some_ investigation / testing / work; not enough to be prohibitive, but enough for me to prioritize other work right now. So we might not need to convince the `ghodss/yaml` upstream — but we would then have to update the `sigstore/rekor` upstream instead, in a short order.

**Pull request merged**
