### PR TITLE
Revert "ginkgo: install on demand via `go get -u`"

### PR DESCRIPTION
**Pull request by vrothberg**
This reverts commit de05e5816869073600ae8e851093b4b9a9d7fab0.

Running `go get -u` will change the local Go module causing CI to fail
as the local git tree is being changed.  Reverting the change for now
until we have a better idea.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

@giuseppe @Luap99 PTAL

### CODE REVIEW

**Comment by vrothberg** [comment]
For the record: an example CI failur is https://cirrus-ci.com/task/6667608495751168

Not sure why that didn't happen in the PR.

**Review by Luap99 — COMMENTED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
