### PR TITLE
[CI:DOCS] man pages: remove non-existent option builtin-volume

### LINKED ISSUE #14906: The command-line option builtin-volume mentioned in podman-create.1.md does not exist
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The documentation mentions the command-line option __builtin-volume__ 

https://github.com/containers/podman/blob/4d111fa9af0352d25d4c9ecc7d203f20f5727d09/docs/source/markdown/podman-create.1.md?plain=1#L452

but when I try it out Podman fails

```
$ podman create --name test --builtin-volume=bind docker.io/library/fedora:36
Error: unknown flag: --builtin-volume
See 'podman create --help'
$ podman --version
podman version 4.1.1
```

### PR DESCRIPTION
**Pull request by eriksjolund**
Closes #14906

Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks!

**Comment by edsantiago** [comment]
>@edsantiago Is this something your man page validation script could catch in the future?

Sigh. The script was designed to catch that, but two subtleties in the way the man page was written:
```
#### **--image-volume**, **builtin-volume**=*bind|tmpfs|ignore*
                           ^-- no dashes         ^-----^---- or-signs
```
...made my script ignore that portion. I'm now looking into a way to fix that by being stricter.

**Pull request merged**
