### PR TITLE
CI:DOCS: Add troublshooting info on podman machine remove followed by podman machine init

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces: https://github.com/containers/podman/pull/12912

**Comment by rhatdan** [comment]
@bazhang87 Thanks for your PR, I will take it over to push it over the finish line, for podman 4.0 release.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
