### PR TITLE
pkg/specgen: allow pasta when running inside userns

### PR DESCRIPTION
**Pull request by Luap99**
pasta doesn't switch to nobody when we already run in a userns so we can use it there. The unshare package checks the same condition and returns true even if uid 0 in this case so we can directly call this.

ref https://github.com/containers/podman/issues/17840#issuecomment-2343251014

#### Does this PR introduce a user-facing change?

```release-note
Allow the pasta network mode to be used when running as uid 0 but already ina userns (container). 
```

### CODE REVIEW

**Comment by Luap99** [comment]
cc @sbrivio-rh @dgibson

@vuori Can you test if this works for you?

**Comment by vuori** [comment]
I'll try to get this tested Tue/Wed.

**Comment by dgibson** [comment]
LGTM

**Review by giuseppe — APPROVED** [review]
/lgtm

**Comment by vuori** [comment]
Looks like I'm a bit late but anyway my problem with pasta inside a rootless container is fixed by this change.

**Pull request merged**
