### PR TITLE
Use configuration value for ExitCommandDelay

### PR DESCRIPTION
**Pull request by rvandernoort**
This PR resolves issue #13222. It is still blocked by [PR941](https://github.com/containers/common/pull/941), since it requires a vendor update. Still needs to be tested therefore.

Signed-off-by: Rover van der Noort <s.r.vandernoort@student.tudelft.nl>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rvandernoort thanks for the PR, but the tests are not terribly happy....

**Comment by rvandernoort** [comment]
Yes I know since [941](https://github.com/containers/common/pull/941) is merged now I can fix this, if I'm correct!

**Comment by rvandernoort** [comment]
Alright, so I vendored the common library as explained in the issue, but this leaves me with a few questions:
- Other library's also seem to have updated because of this action. I pushed everything that changed now, or should I only update the common package?
- I can't seem to find the correct `containers.conf` file that my local build uses, I tried the /usr/share/ one and the vendon/common one, but both don't result in a changed delay time.

**Comment by rvandernoort** [comment]
I'll fix the commits after I succesfully tested the feature

**Pull request closed without merging**
