### PR TITLE
update and remove parameter settings in `.golangci.yml`

### PR DESCRIPTION
**Pull request by qianxi0410**
#### Does this PR introduce a user-facing change?

```release-note
None
```

1. Replace the deadline parameter with the timeout parameter. see https://github.com/golangci/golangci-lint/pull/793
2. Remove useless parameters. https://golangci-lint.run/usage/linters/#errcheck & https://golangci-lint.run/usage/linters/#nolintlint

### CODE REVIEW

**Comment by mheon** [comment]
/approve
LGTM on my end
@Luap99 @cevich PTAL

**Comment by cevich** [comment]
(I restarted the machine-linux test, failure is unrelated to this PR)

**Comment by Luap99** [comment]
@qianxi0410 Thanks for the links in the PR description, for the future please add them to the actual commit message as well.

**Pull request merged**
