### PR TITLE
Revert the custom cobra vendor

### PR DESCRIPTION
**Pull request by Luap99**
Vendor in the latest cobra release v1.1.1

This will hurt the completion experience but is required for
proper packaging, see: #8528.

The best solution is to keep the current scripts since they
work fine with cobra v1.1.1.

### CODE REVIEW

**Comment by vrothberg** [comment]
I suggest to wait before merging.  Reverting would be sad.  Your work is fantastic and I am optimistic we can keep it.

I dropped a comment in https://github.com/spf13/cobra/pull/1258 to pull in Eric who can help us speed things up upstream.  Vendoring a non-release commit is already a huge improvement over vendoring a fork.

**Comment by vrothberg** [comment]
I like this approach.  We keep the great bash completions but use the upstream cobra!

LGTM

**Comment by Luap99** [comment]
The best thing is to keep the current scripts, they work fine with cobra v1.1.1

One problem with that is that `podman completion` will not generate the best possible scripts. However this is fine since we store the best scripts in `./completions/` and these are used for packaging. I don't think many users want to use this command anyway.
And we would also add one small bug: https://github.com/spf13/cobra/pull/1258

**Comment by umohnani8** [comment]
LGTM
@baude @rhatdan @mheon PTAL

**Pull request merged**
