### PR TITLE
Fix `podman images...` missing headers in table templates

### PR DESCRIPTION
**Pull request by jwhonce**
Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Comment by mheon** [comment]
Tests appear very angry

**Comment by zhangguanzhang** [comment]
this broke this:
```
         # # podman-remote --url unix:/tmp/podman.vkaVWN images --sort repository --format table {{.Repository}} {{.Tag}} {{.ID}}
         # REPOSITORY                      TAG              IMAGE ID
         # a.b/c                           d                766ff5a3a7e4
         # quay.io/libpod/testimage        20200929         766ff5a3a7e4
         # zzzzzzzzzz.yyyyyyyyy/xxxxxxxxx  QTaFGG7HKApGQX8  766ff5a3a7e4
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #|     FAIL: podman images, table, line 0
         # #| expected: 'a.b/c                           d                766ff5a3a7e4'
         # #|   actual: 'REPOSITORY                      TAG              IMAGE ID'
```

**Pull request merged**
