### PR TITLE
Handle timezone on server containers.conf

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/11124

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
@containers/podman-maintainers PTAL

**Review by Luap99 — COMMENTED** [review]
/lgtm
/hold

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by saschagrunert** [comment]
Ou, the integration test does not seem to be happy:
```
[+1614s] output: host: arch: amd64 buildahVersion: 1.22.0-dev cgroupControllers: - cpuset - cpu - io - memory - hugetlb - pids cgroupManager: systemd cgroupVersion: v2 conmon: package: 'conmon: /usr/libexec/podman/conmon' path: /usr/libexec/podman/conmon version: 'conmon version 2.0.27, commit: ' cpus: 2 distribution: distribution: ubuntu version: "21.04" eventLogger: journald hostname: cirrus-task-4669329217159168 idMappings: gidmap: null uidmap: null kernel: 5.11.0-1007-gcp linkmode: dynamic memFree: 2382647296 memTotal: 4114534400 ociRuntime: name: crun package: 'crun: /usr/bin/crun' path: /usr/bin/crun version: |- crun version 0.19.1.3-9b83-dirty commit: 33851ada2cc9bf3945915565bf3c2df97facb92c spec: 1.0.0 +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL os: linux remoteSocket: exists: true path: /run/podman/podman-b6f1db3888ee0f06eff69ac7904dce01a22a3873f3b009eefd4c263e87dc19c9.sock security: apparmorEnabled: true capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT rootless: false seccompEnabled: true seccompProfilePath: /usr/share/containers/seccomp.json selinuxEnabled: false serviceIsRemote: true slirp4netns: executable: "" package: "" version: "" swapFree: 0 swapTotal: 0 uptime: 28m 37s registries: docker.io: Blocked: false Insecure: false Location: mirror.gcr.io MirrorByDigestOnly: false Mirrors: null Prefix: docker.io docker.io/library: Blocked: false Insecure: false Location: quay.io/libpod MirrorByDigestOnly: false Mirrors: null Prefix: docker.io/library search: - docker.io - quay.io - registry.fedoraproject.org store: configFile: /etc/containers/storage.conf containerStore: number: 0 paused: 0 running: 0 stopped: 0 graphDriverName: vfs graphOptions: vfs.imagestore: /tmp/podman/imagecachedir graphRoot: /tmp/podman_test627720548/crio graphStatus: {} imageStore: number: 12 runRoot: /tmp/podman_test627720548/crio-run volumePath: /tmp/podman_test627720548/crio/volumes version: APIVersion: 4.0.0-dev Built: 1628078517 BuiltTime: Wed Aug 4 12:01:57 2021 GitCommit: 2da8cc7c6ecf70f2c55311aeba2693ca9b67af4e GoVersion: go1.15.11 OsArch: linux/amd64 Version: 4.0.0-dev
[+1614s] "unlinkat /tmp/podman/imagecachedir: directory not empty"
```

**Pull request merged**
