### PR TITLE
Cleanup man pages

### PR DESCRIPTION
**Pull request by rhatdan**
Format md files to work properly when converted to man pages.
Add sed command to cleanup table in podman man page.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon Author is in the bottom of the man page.

**Comment by TomSweeneyRedHat** [comment]
Dates too, are they present at the bottom on the pages that used to have them?  Otherwise LGTM

**Comment by rhatdan** [comment]
Yes the date of the creation/modification is recorded at the bottom of the man pages.
For some reason travis is not completing.

**Comment by giuseppe** [comment]
the failure is a flake.  Fine to merge this PR?

**Comment by mheon** [comment]
Yeah, I think we're safe to merge if Travis is just flaking.
@rh-atomic-bot r+

**Pull request closed without merging**
