### PR TITLE
DO NOT MERGE make mac make nicer

### PR DESCRIPTION
**Pull request by edsantiago**
...and on all other platforms, too.
    
BINSFX has grown beyond its original intention, and is now
misleading and unmaintainable. Replace it with more natural
target names DEFAULTBIN and REMOTEBIN.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Review by baude — APPROVED** [review]

**Comment by baude** [comment]
will test now ...

**Comment by baude** [comment]
the update here is that `make podman` is not being "trapped" with this patch ... it is not obvious to me why not, but i can try to keep poking at this

**Comment by edsantiago** [comment]
Re: `$(warning` -- yes, totally, for `make docs`.

For `bin/podman`, though, I'm leaning more and more toward just silently redirecting it to `$(MAKE) bin/podman-remote` or something that quietly works. No warnings, no echo, just make it happen. It just seems kinder in every sense.

**Comment by edsantiago** [comment]
> the update here is that `make podman` is not being "trapped" with this patch ... 

Can you paste or link to the full output?

**Comment by edsantiago** [comment]
OH! I think I got it. Gimme a while to confirm and look for a fix...

**Comment by edsantiago** [comment]
Try this. (Relevant change involves recognizing `$(SRCBINDIR)`. I think this will work on Linux as well as Mac, but this is a trickier change that I need to test a lot more. ITM, please see if it helps on Mac.

**Comment by edsantiago** [comment]
`sys` failure is a flake, #10927, one of our oldest most beloved ones. No point in rerunning it though, my goal here was to confirm that `make` still works with these changes.

**Comment by edsantiago** [comment]
This never got any traction. I don't know if the original problem is still a problem, and without a Mac I don't even have any way to test this. I'll just assume the problem has been fixed.

**Pull request closed without merging**
