### PR TITLE
Fix typo in tests

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
My goal today is to make @edsantiago life a little happier.

**Comment by edsantiago** [comment]
Looks great, thank you!

**Comment by umohnani8** [comment]
LGTM

**Comment by edsantiago** [comment]
Looks like you missed `test/utils` (podmansession_test.go and utils.go)

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons

**Pull request merged**
