### PR TITLE
Add IPVLAN network support to podman network.

### PR DESCRIPTION
**Pull request by ananthb**
podman network learns the modified `--driver=ipvlan` option which will create an ipvlan network using the relevant CNI plugin.\
Additionally, both macvlan and ipvlan drivers gain the ability to set network mode via the `macvlan_mode` and `ipvlan_mode` driver options.

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
It looks like there is no difference between a macvlan config and ipvlan config other than the plugin name. I think it is better to just add a new parameter to createMacvlan() and set PluginType to `ipvlan`

**Comment by TomSweeneyRedHat** [comment]
It would be nice to have at least a little bit of description on what this PR does in the description.  You'll eventually need to add some tests too so the CI won't bark at you.

**Comment by ananthb** [comment]
Yep @TomSweeneyRedHat, I'm working on it.

**Comment by ananthb** [comment]
@Luap99 yeah that makes sense. I also want to add macvlan_mode and ipvlan_mode support like docker. These will go in `podman network create -d ipvlan -o ipvlan_mode=l2` or `podman network create -d macvlan -o mode macvlan_mode=...`. The modes will be different between ipvlan and macvlan but that should be easy to account for with one function creating both.

**Comment by ananthb** [comment]
Hey @Luap99, I'm re-using code from macvlan networks for ipvlan. If this seems ok, I'll add tests to validate macvlan and ipvlan network options similar to how bridge network options are being validated right now. Does this make sense?

**Comment by Luap99** [comment]
Thanks @ananthb. Sorry for not getting back earlier. I am currently reworking the network code (see #11232) and this code will go away soon so I am not sure if this worth merging. I think we can easily add support for the IPVLAN driver to new code once #11232 is merged.

**Comment by ananthb** [comment]
Oh! I'll close this PR then.

**Pull request closed without merging**
