### PR TITLE
CI: update to F34: pass enforced short-name mode

### PR DESCRIPTION
**Pull request by vrothberg**
Continuation of https://github.com/containers/podman/pull/9554 to help move things forward.

### CODE REVIEW

**Comment by rhatdan** [comment]
Looks like you included a whole bunch of PRs with this?

**Comment by vrothberg** [comment]
> Looks like you included a whole bunch of PRs with this?

That's intentional (see commit message): it's continuation of the PR to run F34.

**Comment by vrothberg** [comment]
Oh, more things were pulled in. Those commits are in master already. Will do an exact rebase with the next push.

**Comment by cevich** [comment]
@vrothberg I appreciate your help here, and word-of-warning:  There are likely to be many more stumbling tests past this one.  Since F34 _just_ started official beta, I'll also likely be rolling freshly built images into #9554.  Including my commits here is fine for testing, but come merge-time I would suggest not including them.  I'll pick them up by rebase in #9554 eventually.

**Comment by vrothberg** [comment]
@cevich, agreed.  I'll continue here trying to get the unit tests to pass. Guess we need to go step by step.

**Pull request closed without merging**
