### PR TITLE
Switch to 5.x WSL machine os stream using new automation

### PR DESCRIPTION
**Pull request by n1hility**
- Switches from the current wsl-fedora images used by the 4.x stream to a 5.x WSL machine os stream produced by https://github.com/containers/podman-machine-wsl-os
- Adds subscription-manager and qemu-user-static
- Also Includes a switch from XZ to ZSTD for significantly improved fetch performance 
   + The increase in packages brought  xz extraction to almost 10 minutes (the xz golang is significantly less efficient than xz utils) , now 10 secs with zstd

The ultimate goal is to move from http to an oci pull, but this is targeted for 5.1

```release-note
none
```

### CODE REVIEW

**Comment by n1hility** [comment]
/hold 

Need to address one other issue

**Comment by n1hility** [comment]
PTAL @containers/podman-maintainers

cc  @mheon @baude ( as discussed, last one needed for 5.0 )

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
/cherry-pick v5.0
@containers/podman-maintainers PTAL

**Review by Luap99 — APPROVED** [review]
seems like pkg/machine/e2e/machine_wsl_test.go is hard-coding xz as file extension.
I am not familiar with the code but if I read this right it is entirely "optional" (i.e. only part of the name and no real logic). As such I think this is fine to merge but the test should be updated at some point to remove this confusing reference

/lgtm
/hold

**Pull request merged**
