### PR TITLE
Vendor in containers/common v0.30.0

### PR DESCRIPTION
**Pull request by ashley-cui**
As per title 

Signed-off-by: Ashley Cui <acui@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
The change LGTM, my only question is this for v2.2 or v3.0?

**Comment by ashley-cui** [comment]
@TomSweeneyRedHat the only changes in common are for this issue: https://github.com/containers/podman/issues/7888, not sure if this is 2.2 or 3.0, but it shouldn't affect anything outside this one issue. I can hold this and vendor it in with the completed issue too if that's better

**Comment by rhatdan** [comment]
@ashley-cui Every new feature is 3.0 Only bug fixes for 2.2.

**Comment by ashley-cui** [comment]
hmm.. replaced by https://github.com/containers/podman/pull/8489

**Pull request closed without merging**
