### PR TITLE
podman-remote does not support signature-policy

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/12357

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
This will probably cause a lot of breakage in testing.

**Review by vrothberg — COMMENTED** [review]
LGTM

I restarted the flaked job

**Comment by vrothberg** [comment]
Restarted another time.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
Test still isn't hip after several restarts....

**Comment by mheon** [comment]
It's definitely a flake, but a very persistent one, restarted again

**Comment by rhatdan** [comment]
Saving the planet.

**Pull request merged**
