### PR TITLE
Update CI VMs

### PR DESCRIPTION
**Pull request by edsantiago**
Mostly to get pasta 08-14 but also a ton more changes elsewhere.

   https://github.com/containers/automation_images/pull/383

Fixes: #23517 

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
https://github.com/containers/podman/commit/1912dd4bf68a567648aee96d10784fb49eacacd0 should be reverted before merging this

**Comment by Luap99** [comment]
and then we can close https://github.com/containers/podman/issues/23517

**Comment by edsantiago** [comment]
Done. One flake, unrelated to pasta

**Review by Luap99 — APPROVED** [review]
LGTM

**Pull request merged**
