### PR TITLE
e2e: use isRootless() instead of rootless.IsRootless()

### PR DESCRIPTION
**Pull request by sstosh**
Unify the functions used to detect rootless to "isRootless()".
This function can detect to join the user namespace by mistake.

Signed-off-by: Toshiki Sonoda <sonoda.toshiki@fujitsu.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
/approve
@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
> Doesn't that mean that the ginkgo processes run inside the user NS?
> Why is that the case?

Because the podman user namespace was already created and importing pkg/rootless will automatically join it by default. All ginkgo test must be run with the remote build tag.
read https://github.com/containers/podman/pull/16322 for more details
 
In short the tests should never join the userns. So this patch fixes the symptom but not the cause.

**Comment by vrothberg** [comment]
@sstosh how are you running the tests?

**Comment by sstosh** [comment]
Thanks for your reply.
I verified that `os.Geteuid()` returns '1000' and a test is successed.
<details>
<summary>os.Geteuid() returns '1000' and a test is successed</summary>

```
$ PODMAN_BINARY=$(which podman) PODMAN_REMOTE_BINARY=$(which podman-remote) GOPATH=~/go ginkgo -tags "remote" -v test/e2e/.

Podman pod create
  podman pod create --sysctl test
  /home/test/podman-sstosh/test/e2e/pod_create_test.go:1044
1000
Running: /usr/local/bin/podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/podman_test2884809651/root --runroot /tmp/podman_test2884809651/runroot --runtime crun --conmon /usr/bin/conmon --network-config-dir /home/test/.config/cni/net.d --network-backend cni --cgroup-manager cgroupfs --tmpdir /tmp/podman_test2884809651 --events-backend file --storage-driver vfs pod rm -fa -t 0
output:
Running: /usr/local/bin/podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/podman_test2884809651/root --runroot /tmp/podman_test2884809651/runroot --runtime crun --conmon /usr/bin/conmon --network-config-dir /home/test/.config/cni/net.d --network-backend cni --cgroup-manager cgroupfs --tmpdir /tmp/podman_test2884809651 --events-backend file --storage-driver vfs rm -fa -t 0
output:

S [SKIPPING] [0.096 seconds]
Podman pod create
/home/test/podman-sstosh/test/e2e/pod_create_test.go:23
  podman pod create --sysctl test [It]
  /home/test/podman-sstosh/test/e2e/pod_create_test.go:1044

  [rootless]: Network sysctls are not available root rootless
```
</details>

I changed a commit message.
In addition, I added a description of `-tags "remote"` to `test/README.md`.

**Comment by sstosh** [comment]
I have the same opinion as @giuseppe does.
I unified the function with `isRootless()` instead of `rootless.IsRootless()`.

**Review by vrothberg — APPROVED** [review]
LGTM thanks!

@giuseppe PTAL

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by vrothberg** [comment]
@containers/podman-maintainers TAL

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.
WOuld like a head nod from @giuseppe before merging.

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
