### PR TITLE
container kill: handle stopped/exited container

### PR DESCRIPTION
**Pull request by vrothberg**
The container lock is released before stopping/killing which implies
certain race conditions with, for instance, the cleanup process changing
the container state to stopped, exited or other states.

The (remaining) flakes seen in #16142 and #15367 strongly indicate a
race in between the stopping/killing a container and the cleanup
process.  To fix the flake make sure to ignore invalid-state errors.
An alternative fix would be to change `KillContainer` to not return such
errors at all but commit c77691f06f61 indicates an explicit desire to
have these errors being reported in the sig proxy.

[NO NEW TESTS NEEDED] as it's a race already covered by the system
tests.

Fixes: #16142
Fixes: #15367
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Fix a race condition when stopping/killing a container that has already been stopped or has exited.
```

@mheon PTAL
@edsantiago I am convinced this will fix both linked flakes.

### CODE REVIEW

**Comment by mheon** [comment]
Code LGTM

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
