### PR TITLE
pkg/specgen/generate/security: fix error message text

### PR DESCRIPTION
**Pull request by kolyshkin**
This should be Network Namespace, not Host Namespace.

Fixes: 0d70df11

### CODE REVIEW

**Comment by kolyshkin** [comment]
Found in https://github.com/containers/crun/pull/856/commits/8ff965217c2d6cf23c4edb1b6894afe6642eb6d6#r790090399

**Comment by rhatdan** [comment]
Thanks @kolyshkin 
LGTM
Please add [NO NEW TESTS NEEDED] to get by the validation step.

**Comment by mheon** [comment]
LGTM once tests issue is resolved
/approve

**Pull request merged**
