### PR TITLE
[CI:DOCS] Rewrite --env docs

### PR DESCRIPTION
**Pull request by eriksjolund**
* Add docs about trailing * functionality in podman-exec.1.md

* Rewrite --env description in podman-create.1.md and podman-run.1.md

* Rewrite the --env examples in podman-create.1.md and podman-run.1.md

Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat PTAL
/approve

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
It helps when I hit the right button

**Pull request merged**
