### PR TITLE
V4reverts

### PR DESCRIPTION
**Pull request by baude**
Reverting two previous commits as one causes an error and one was not published.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
UGH, this should not have been merged until we go approval from RHEL.  Please do NOT merge anything into this branch with our first verifying with me.

**Comment by baude** [comment]
either way these commits needed to happen.  whether it is 4.0.2 now or something else later.

**Pull request merged**
