### PR TITLE
Pass DefaultMountsFile to podman build

### PR DESCRIPTION
**Pull request by rhatdan**
The --default-mounts-file path was not being handled in
podman build.  This will enable it to use for testing.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago Do you want to throw me a test for this?

**Comment by edsantiago** [comment]
@rhatdan that was fast, thank you! #9091 already has the test written, just commented out with FIXMEs. If it passes and merges, you could rebase then enables lines 191-192, 204-205 in 070-build.bats

**Comment by edsantiago** [comment]
Followup: I pulled your PR, ran my tests against it (with changes as described in my previous comment): it passes. I confirmed that the test is really running by adding `sdfsdf` to the `is` line that checks for the secret, and confirming that it fails, and that the command log shows the true secret. In short: your code works, and my test works. Thanks again.

**Comment by edsantiago** [comment]
@rhatdan #9091 is merged. At your convenience feel free to rebase and apply [the following diff](https://github.com/containers/podman/files/5870042/cat-secret.diff.txt)

```diff
diff --git a/test/system/070-build.bats b/test/system/070-build.bats
index 9e5e3ee1d..05518d8fc 100644
--- a/test/system/070-build.bats
+++ b/test/system/070-build.bats
@@ -188,8 +188,7 @@ ADD mycmd /bin/mydefaultcmd
 RUN chmod 755 /bin/mydefaultcmd
 RUN chown 2:3 /bin/mydefaultcmd

-#FIXME FIXME FIXME: enable if/when 'podman build' passes mounts.conf to buildah
-#RUN $CAT_SECRET
+RUN $CAT_SECRET

 CMD ["/bin/mydefaultcmd","$s_echo"]
 EOF
@@ -201,8 +200,7 @@ EOF
     local iid="${lines[-1]}"

     # Make sure 'podman build' had the secret mounted
-    #FIXME FIXME: enable if/when 'podman build' passes mounts.conf to buildah
-    #is "$output" ".*$secret_contents.*" "podman build has /run/secrets mounted"
+    is "$output" ".*$secret_contents.*" "podman build has /run/secrets mounted"

     if is_remote; then
         ENVHOST=""
```

**Comment by edsantiago** [comment]
Restarted flake, #9026. LGTM. All new tests pass.

/lgtm
/hold

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
