### PR TITLE
Revert "Add support for 'podman pod' on FreeBSD"

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: Brent Baude <bbaude@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note

NONE

```

PR #16083 breaks pod creation

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Review by ashley-cui — COMMENTED** [review]
/lgtm
/hold

**Comment by mheon** [comment]
How does it break pod creation?

**Comment by baude** [comment]
> How does it break pod creation?

run it  ... but the point is it breaks things.  Figure out why later

**Comment by baude** [comment]
this is no longer the case.  closing

**Comment by dfr** [comment]
I am not sure exactly what happened here - what was the problem here?

These refactoring PRs do come with risk and that risk is greatly reduced by the excellent test coverage in podman. In cases like this, backing out the PR is the right move but please also capture details of the problem in an issue, ideally including reproduction steps. This can help to improve test coverage and avoid similar problems in future.

**Pull request closed without merging**
