### PR TITLE
Add missing events to podman-events man page

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Follow up to https://github.com/containers/podman/issues/13919

**Review by Luap99 — COMMENTED** [review]
LGTM but could you update the shell completion as well: https://github.com/containers/podman/blob/712c3bb226a84c8a5593d62648975611cea7839d/cmd/podman/common/completion.go#L1060

**Comment by rhatdan** [comment]
@Luap99 Done

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
