### PR TITLE
[CI:DOCS] VOLUME needs to be declared after CHOWN

### PR DESCRIPTION
**Pull request by jnovy**
are set. Not doing do will cause:
https://bugzilla.redhat.com/show_bug.cgi?id=2009266

Signed-off-by: Jindrich Novy <jnovy@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Could you make sure you have the latest image?

**Comment by jnovy** [comment]
$ podman unshare
# mnt=`podman image mount quay.io/podman/stable`
# ls -ld $mnt/home/podman/.local/share/containers
drwxr-xr-x. 2 jnovy jnovy 6 Oct 17 10:05 /home/jnovy/.local/share/containers/storage/overlay/de38dbe0d42b232b16a8e290d6860d657d4010f237f727d29884e74f52f2f15b/merged/home/podman/.local/share/containers

**Comment by rhatdan** [comment]
Could you attach the Dockerfile you are using?

**Comment by jnovy** [comment]
The original Dockerfile showing this bug in RHEL8.5:
[Dockerfile.txt](https://github.com/containers/podman/files/7487033/Dockerfile.txt)

The fixed Dockerfile for RHEL8.5:
[Dockerfile-fixed.txt](https://github.com/containers/podman/files/7487067/Dockerfile-fixed.txt)

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
@rhatdan Do we still need this?

**Comment by rhatdan** [comment]
Nope.

**Pull request closed without merging**
