### PR TITLE
test/system: make some tests faster part 3

### PR DESCRIPTION
**Pull request by Luap99**
Like the others please see individual commits.

Part 2 https://github.com/containers/podman/pull/22826
Part 1 https://github.com/containers/podman/pull/22821
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
/lgtm

Thanks for doing this. It seems like a lot of effort, I hope the gains are worth it.

**Comment by Luap99** [comment]
/hold
Do not merge or restart tests, a changed test flaked https://api.cirrus-ci.com/v1/artifact/task/6270902646603776/html/sys-podman-fedora-39-root-host-boltdb.log.html

I take a look tomorrow at the cause.

**Comment by edsantiago** [comment]
Yeah, I was just looking at that. Failure does not make sense to me.

**Comment by Luap99** [comment]
> Yeah, I was just looking at that. Failure does not make sense to me.

Given the test took 10s I think the issue is that the container unit got stop before it installed the sigterm handler. I think the fix is to do the trap before the unit sends the ready message.

**Comment by Luap99** [comment]
rebased + changed the "quadlet - pod simple" and "quadlet - basic" to do the trap before the ready message. Hopefully that is enough.

**Comment by Luap99** [comment]
... still flaking for some reason, I don't get it.

**Comment by Luap99** [comment]
@edsantiago good to merge?

**Comment by edsantiago** [comment]
/lgtm

thanks again

**Pull request merged**
