### PR TITLE
Update vendor or containers/common moving pkg/cgroups there

### PR DESCRIPTION
**Pull request by rhatdan**
[NO NEW TESTS NEEDED] This is just moving pkg/cgroups out so
existing tests should be fine.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg Lots of failure caused by the docker reference fix in containers-common.  Is this actually a bug in tests or in containers-common?

**Comment by vrothberg** [comment]
> @vrothberg Lots of failure caused by the docker reference fix in containers-common. Is this actually a bug in tests or in containers-common?

The reference filter works now identically to the one in Docker, so I'd argue that the previous behavior was buggy. Apologies for not cleaning up directly here, I will take a look.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/12505 to take care of the tests.

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/12514 fixed the issues.  Can you rebase?

**Comment by umohnani8** [comment]
LGTM

**Review by vrothberg — COMMENTED** [review]
Can you also remove `pkg/cgroups` from Podman?

**Comment by rhatdan** [comment]
Yikes that was the big purpose of this PR.

**Review by vrothberg — COMMENTED** [review]
/lgtm
/hold

**Review by flouthoc — APPROVED** [review]

**Pull request merged**
