### PR TITLE
Fix regression in CI artifacts script introduced by legacy msi removal

### LINKED ISSUE #19383: CI Artifacts task failing & Windows download link broken
### Issue Description

The https://github.com/containers/podman/pull/19349 PR made changes to output files.  However, it missed making corresponding changes to the `artifacts` CI script and a link in the documentation pointing at the file.

### Steps to reproduce the issue

Steps to reproduce the issue
1. [Observe artifacts task failure on `main` (log)](https://cirrus-ci.com/task/5193709495517184)
2. Click "Windows podman-remote for x86_64 only." link [on DOWNLOADS page](https://github.com/n1hility/podman/blob/2f21df7b3a767f1efabe5ef16031d5d61e61a5bd/DOWNLOADS.md)

### Describe the results you received

1. Daily CI runs on `main` fail in artifacts task
2. Get 404 when clicking download link

### Describe the results you expected

1. Daily CI runs on `main` should always pass
2. Documentation should not contain bad links

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

N/A

### Additional information

Both these items were added as a potential aid to downstream users or automation.  However, I am unaware of, and doubtful that anybody/anything actually depends on the windows binary CI artifact.  I'm totally fine if the fix here is to simply remove the broken things.

### PR DESCRIPTION
**Pull request by n1hility**
Fixes #19383 (regression introduced by #19349)

[NO NEW TESTS NEEDED]
```release-note
none
```

### CODE REVIEW

**Comment by n1hility** [comment]
PTAL @cevich

**Comment by rhatdan** [comment]
LGTM

**Review by cevich — APPROVED** [review]
LGTM.  Thanks!

**Pull request merged**
