### PR TITLE
Updating container names with Two Indian Warriors

### PR DESCRIPTION
**Pull request by Saurabh-Thakre**
As suggested above, updating the file with names of Two great Indian Warriors.

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Thanks for contributing!

The `./vendor` directory should only be updated by bumping a dependency in `go.mod`.  Has this patch already been submitted to docker?

**Comment by Saurabh-Thakre** [comment]
> Thanks for contributing!
> 
> The `./vendor` directory should only be updated by bumping a dependency in `go.mod`. 

My Apologies, this is the first time I'm pushing to this repo, should I have to update [go.mod](https://github.com/containers/podman/blob/main/go.mod) with `github.com/docker/docker/pkg/` ?

> Has this patch already been submitted to docker?

You mean I have to first submit the patch to `https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go` ?

**Comment by rhatdan** [comment]
Yes

**Comment by Saurabh-Thakre** [comment]
> Yes

Made the suggested changes here [Updating it with names of Two Indian Warriors #42590
](https://github.com/moby/moby/pull/42590) and #10846 

I hope I did not mess it up this time :|

**Comment by baude** [comment]
please also add a commit message

**Comment by mheon** [comment]
I don't think this is going to pass CI since this is modifying vendored code - since this code is maintained by folks who are not us, CI will not allow changes to it. The change will need to be made in the moby/moby upstream and then we can vendor a version with it.

**Comment by baude** [comment]
... when moby cuts a release

**Comment by Saurabh-Thakre** [comment]
Looks like, on the moby side, no one got assigned to the PR. I think we have to wait till then

**Comment by eriksjolund** [comment]
How historic warriors are portrayed often depends on political opinion. I think it is better leaving that out.

**Comment by Saurabh-Thakre** [comment]
Sorry, @eriksjolund I have little different thoughts on this. The reason I wanted this PR to get merge is that I see there are so many names with great persons on the list, and I would like to have two Indian names so we could show that We're keeping as diverse as we can. I believe in diversity, and practices that we can follow to ensure that.

Personally, I don't think there is any political opinion needed to make sure these are the true warriors and I didn't know that political role occupies important space here.
I'm fine if it's not getting merged, I just want to speak out about what I felt. Thank you for your inputs.

**Comment by Shivkumar13** [comment]
+1 @Saurabh-Thakre 

I really don't think this is something that depends upon a political opinion. We should definitely follow good diversity practices. Thanks for bringing this up!

**Comment by hsirsulw** [comment]
+1 @Saurabh-Thakre
I agree with Saurabh, and don't think it will become a political matter, We have already added many warriors and leaders names to the list.

**Comment by milindw96** [comment]
+1 @Saurabh-Thakre

@eriksjolund I feel u should plz have a look to have some idea on it

https://mr.wikipedia.org/wiki/%E0%A4%B6%E0%A4%BF%E0%A4%B5%E0%A4%BE%E0%A4%9C%E0%A5%80_%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%B0%E0%A4%BE%E0%A4%9C

**Comment by Saurabh-Thakre** [comment]
Closing https://github.com/moby/moby/pull/42590

**Pull request closed without merging**
