### PR TITLE
Tidy duplicate log tests

### PR DESCRIPTION
**Pull request by ashley-cui**
Some log tests were duplicated, and some didn't need to be repeated for
every driver. Also, added some comments

Signed-off-by: Ashley Cui <acui@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
F32 test failure seems consistent. I restarted, but I suspect it's a real issue.

**Comment by ashley-cui** [comment]
A rebase did the trick :)

**Pull request merged**
