### PR TITLE
CI: fix search-test flakes

### PR DESCRIPTION
**Pull request by edsantiago**
Seeing constant e2e test failures today, in search tests.

Reason: tests are searching for "alpine", which is common,
and we're hitting pollution.

Solution: search for "testdigest_v2s<x>", an image in quay
under the libpod namespace. And, in other tests that rely
on docker.io, switch to quay.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
I was wrong in scrum today. Today's test storm is NOT related to registry.redhat, it's another instance where searching for "alpine" returns hits that are not under our control. We keep hitting this (eg #14196), so try to reduce our risk.

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
I left two instances of `docker.io` in the tests, because I can't find a way to do them in quay:
* search --filter stars=10
* search --filter is-official

Both are flaking.

@containers/podman-maintainers: can someone with superuser access to `quay.io/podman` please see if there's a way to add "stars" or set the "official" bit on the `stable` image? I have access to `libpod` but don't see a way to set either. I don't know if quay supports those?

**Comment by Luap99** [comment]
> @containers/podman-maintainers: can someone with superuser access to `quay.io/podman` please see if there's a way to add "stars" or set the "official" bit on the `stable` image? I have access to `libpod` but don't see a way to set either. I don't know if quay supports those?

AFAIK both of these options are dockerhub specific and not support by other registries, at least the man page says
> --compatible
>
>After the name and the description, also show the stars, official and automated descriptors as Docker does. Podman does not show these descriptors by default since they are not supported by most public container registries.

**Comment by edsantiago** [comment]
Fair enough. Then we remain at the mercy of `docker.io`. There is still some value to this PR, in the sense that searching for `alpine` is fragile, but outages like today's will still block us.

**Pull request merged**
