### PR TITLE
Update dependency golangci/golangci-lint to v1.55.0

### PR DESCRIPTION
**Pull request by Luap99**
see commits for new linter fixes

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

really impressive to see how more and more things are reported with each bump of the linter(s)

**Comment by Luap99** [comment]
> really impressive to see how more and more things are reported with each bump of the linter(s)

impressive yes, but I could argue it is a failure of the ecosystem if so many linters are needed to catch bugs and performance problems.

**Comment by vrothberg** [comment]
> impressive yes, but I could argue it is a failure of the ecosystem if so many linters are needed to catch bugs and performance problems.

What would be the alternative?  I recall LLVM getting better on each release as well.  Writing such static analyzers is quite difficult and sometimes require expensive compiler techniques/transformations.

**Comment by Luap99** [comment]
I don't want to get into this discussion right now and I am not saying I know better, there is no such things as the one right way. All I say I prefer the compiler to prevent me from compiling known buggy code instead of having to rely on third party linters to that.

**Review by ashley-cui — COMMENTED** [review]
/lgtm

**Pull request merged**
