### PR TITLE
test/e2e: improve command timeout handling

### PR DESCRIPTION
**Pull request by Luap99**
Basically commit ada4e1a8c1 for e2e tests. The timeout does not kill the process so if it is stucked it hangs forever. So make sure we kill it via SIGABRT.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@mheon @edsantiago PTAL
This might help for https://github.com/containers/podman/issues/22246 but regardless I think we need this as otherwise the process is not killed and keeps running.

**Comment by edsantiago** [comment]
LGTM in principle. Cherrypicked & pushed onto #17831

**Comment by mheon** [comment]
LGTM

**Pull request merged**
