### PR TITLE
[4.6] vendor c/common v0.55.3

### PR DESCRIPTION
**Pull request by vrothberg**
#### Does this PR introduce a user-facing change?

```release-note
Bump github.containers/common to v0.55.3.
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@TomSweeneyRedHat PTAL

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
@rhatdan PTAL

**Comment by ashley-cui** [comment]
/lgtm

TY!

**Comment by TomSweeneyRedHat** [comment]
12 minutes late, but LGTM, thanks for the snappy turn around @vrothberg

**Pull request merged**
