### PR TITLE
Cirrus: Make use of shared get_ci_vm container

### PR DESCRIPTION
**Pull request by cevich**
***Note***: An updated version of common automation tooling required, also included in new VM images.

Depends on:
    https://github.com/containers/automation_images/pull/57
    https://github.com/containers/automation/pull/64
    https://github.com/containers/automation/pull/66
    https://github.com/containers/automation/pull/67
    https://github.com/containers/automation/pull/68

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by lsm5** [comment]
need to ensure we have `libcap2 100:2.48-1` and `crun 100:0.18-3`

**Comment by cevich** [comment]
```
root@cevich-ubuntu-c4882372358307840:/# dpkg -l libcap2 crun
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-====================================
ii  crun           100:0.18-3   amd64        OCI runtime written in C
ii  libcap2:amd64  100:2.48-1   amd64        POSIX 1003.1e capabilities (library)
```

**Comment by cevich** [comment]
rebased and force-pushed w/ a minor safety-related change to the get_ci_vm interface.

**Comment by cevich** [comment]
rebased and added minor update to support debugging.

**Comment by cevich** [comment]
Pushed with new images with updated crun (needed to pass tests).

**Comment by cevich** [comment]
@containers/podman-maintainers PTAL, this is ready now (please try it out, if you're able)

**Pull request merged**
