### PR TITLE
Add missing criu symbols to criu_unsupported.go

### PR DESCRIPTION
**Pull request by dfr**
Signed-off-by: Doug Rabson <dfr@rabson.org>

#### Does this PR introduce a user-facing change?

No

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Instead of duplicating the constants can you move the functions out of criu.go into criu_linux.go?
Then the constants can be shared?

**Comment by dfr** [comment]
Done. This one was a product of a rather intense couple of days where I was working through getting podman to at least compile. I also fixed a spelling mistake which was bothering me - not sure if thats used outside of podman so that part can be dropped if necessary.

**Comment by dfr** [comment]
rebased

**Review by vrothberg — COMMENTED** [review]
LGTM
Please make sure to add meaningful descriptions to the commit next time. That'll help keep the commit history clean for future generations.

/lgtm
/hold

**Comment by mheon** [comment]
Restarted one flake

**Pull request merged**
