### PR TITLE
Cirrus: Execute docker-py tests on a VM

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Did this PR actually turn on the test?

**Comment by jwhonce** [comment]
@rhatdan Turning on the tests is scheduled for next week.  This provides the VM to run the test.

**Comment by jwhonce** [comment]
LGTM

**Review by jwhonce — APPROVED** [review]

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
