### PR TITLE
Add support for 'podman pod' on FreeBSD

### PR DESCRIPTION
**Pull request by dfr**
This one is fairly straightforward, mainly moving cgroup management out of the common code.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
/lgtm
/approve

Today I discovered `SavePod()` exists, when it really ought not to - that functionality should not be externally exposed. I'll fix that in a separate PR once this merges.

**Pull request merged**
