### PR TITLE
[CI:DOCS] Bump to v4.1.0-RC2

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
Since we now have a v4.1 branch can you create a new entry here: https://github.com/containers/podman/blob/main/docs/source/Reference.rst

**Comment by mheon** [comment]
In main, I assume?

**Comment by Luap99** [comment]
both, it has to be part of the tag as well

**Comment by mheon** [comment]
Added to PR. Won't be in the RC2 tag but will be in final.

**Pull request merged**
