### PR TITLE
[CI:BUILD] [v4.5] cleanup unwanted tasks

### PR DESCRIPTION
**Pull request by lsm5**
- Remove downstream and on-commit copr build tasks
- Remove windows installer build task
- Packit copr builds are only for C8S and C9S on aarch64 and x86_64
    
[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

@cevich PTAL

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@cevich PTAL

**Comment by lsm5** [comment]
ignore el9 failures for now.

**Comment by Luap99** [comment]
Isn't the 4.5 branch dead with the release of 4.6.0? cc @mheon 
So I think we can nuke all CI here.

**Comment by mheon** [comment]
Yeah, 4.5 was upstream-only, so we have no support guarantees on it since a newer release is out. 4.6 will hang around longer, being a RHEL release.

**Review by vrothberg — COMMENTED** [review]
+1 for nuking CI entirely on this branch

**Comment by rhatdan** [comment]
SGTM

**Comment by lsm5** [comment]
> Isn't the 4.5 branch dead with the release of 4.6.0? cc @mheon So I think we can nuke all CI here.

SGTM. @cevich ^

**Comment by lsm5** [comment]
closing in favor of #19360

**Pull request closed without merging**
