### PR TITLE
`podman machine rm` removes the mounted socket file on macOS

### LINKED ISSUE #13301: `podman machine rm` should remove the mounted host socket as well on macOS
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

With podman 4.0 it's pretty cool that we have podman socket mounted on the macOS host.

I can create machines with `init` command and then I've socket mounted on
`$HOME/.local/share/containers/podman/machine/<machine-name>/podman.sock`

But removing the machine should also remove this socket file

**Steps to reproduce the issue:**

1. podman machine init --now

2. Check that there is a file `$HOME/.local/share/containers/podman/machine/<machine-name>/podman.sock`

3. podman machine rm

4. File at `$HOME/.local/share/containers/podman/machine/<machine-name>/podman.sock` should be removed

**Describe the results you received:**

local socket is still there

**Describe the results you expected:**

local socket should be removed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

4.0.0-dev
```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by tricktron**
Fixes #13301.

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @tricktron 
LGTM
@n1hility @baude @ashley-cui PTAL
@containers/podman-maintainers PTAL

**Review by flouthoc — APPROVED** [review]

**Comment by n1hility** [comment]
Lgtm thanks!

**Pull request merged**
