### PR TITLE
Run codespell

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```
Replaces: https://github.com/containers/podman/pull/14793

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm
/hold

Restarted the flaked job

**Pull request merged**
