### PR TITLE
Add hidden trust command to alias existing trust commands

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
podman trust hidden command added for docker compatibility.
```

### CODE REVIEW

**Review by Luap99 — CHANGES_REQUESTED** [review]
I don't see how this helps.
If you actually care for compatibility you need to match the actual commands with their input and output.

Per https://docs.docker.com/engine/reference/commandline/trust/
there is the inspect, key, revoke, sign, signer command, but no set or show which you add here.

**Comment by rhatdan** [comment]
It makes it more discoverable. We can look at fixing up the others. But for now users who do podman trust see no failure.

**Comment by rhatdan** [comment]
Let's discuss at the next standup, and get consensus.  My goal was to allow users to discover how Podman defines trust.
```
podman trust
Error: unrecognized command `podman trust`
Try 'podman --help' for more information
```
Versus
```
 $ ./bin/podman trust
Manage container image trust policy

Description:
  Manages which registries you trust as a source of container images based on their location.
  The location is determined by the transport and the registry host of the image.  Using this container image docker://quay.io/podman/stable as an example, docker is the transport and quay.io is the registry host.

Usage:
  podman trust [command]

Available Commands:
  set         Set default trust policy or a new trust policy for a registry
  show        Display trust policy for the system

Error: missing command 'podman trust COMMAND'
```

**Comment by vrothberg** [comment]
Friendly ping. @rhatdan do you want to kick it over the finish line?

**Comment by vrothberg** [comment]
Friendly ping, @rhatdan :^)

**Comment by rhatdan** [comment]
Closing for now, since I have no time to work on it, and it would be complicated to implement.

**Pull request closed without merging**
