### PR TITLE
Vendor

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Red tests.  Could you change the title please to include the packages vendored?  And/or add them to the description.

**Comment by vrothberg** [comment]
The merge commit seems odd.  Did you rebase?

**Comment by vrothberg** [comment]
I'll open a PR to fix the c/common fart.

**Comment by vrothberg** [comment]
-> https://github.com/containers/podman/pull/13945

**Review by flouthoc — APPROVED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
