### PR TITLE
remove `pkg/registries`

### PR DESCRIPTION
**Pull request by vrothberg**
Pull the trigger on the `pkg/registries` package which acted as a proxy
for `c/image/pkg/sysregistriesv2`.  Callers should be using the packages
from c/image directly, if needed at all.

Also make use of libimage's SystemContext() method which returns a copy
of a system context, further reducing the risk of unintentionally
altering global data.

[NO TESTS NEEDED]

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM, although tests are not happy.

**Comment by TomSweeneyRedHat** [comment]
changes LGTM, test not so much.

**Comment by mheon** [comment]
LGTM once green

**Comment by vrothberg** [comment]
Ready to merge

**Pull request merged**
