### PR TITLE
[CI:DOCS] [4.6] Update Release Notes

### PR DESCRIPTION
**Pull request by ashley-cui**
```release-note
None
```

Closes https://github.com/containers/podman/issues/19594

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM, thank you!

**Review by Luap99 — COMMENTED** [review]
Shouldn't this be part of 4.6.0?

**Comment by ashley-cui** [comment]
@Luap99 You're right, thanks!

**Review by Luap99 — COMMENTED** [review]
/lgtm
/hold

**Comment by TomSweeneyRedHat** [comment]
LGTM
I think @Luap99 was holding for the right branch, I'll let him cancel the hold if he's satisfied.

**Review by vrothberg — APPROVED** [review]
/hold cancel

**Pull request merged**
