### PR TITLE
[CI:DOCS] Improve podman-{tag,build} man pages

### PR DESCRIPTION
**Pull request by rahilarious**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Thanks for contributing!

The changes LGTM.  In order to pass the tests, your commits need a signature (i.e., the `Signed-off-by`) which you can add via `git commit --amend -s` (must be done for both commits).

**Comment by rahilarious** [comment]
> our commits need a signature

Oops. Done. I always forget that. Is there anyway to always --signoff all commit globally in git? Can't find it in git-config.

**Comment by rhatdan** [comment]
Thanks @rahilarious

**Pull request merged**
