### PR TITLE
System tests: cleanup in --format test

### PR DESCRIPTION
**Pull request by edsantiago**
Followup to #15673 (--format with newlines). I cobbled up a test
for it, but I was sloppy, so the test had issues that I kept
having to band-aid. This is a cleaner way to handle podman-machine.

...and, another unexpected surprise with podman stats. It
fails under rootless cgroupsv1. We can't sweep it under the
rug via skip_if_ubuntu because tests will then fail on RHEL8.
So, add a similar mechanism for testing podman stats.
    
...plus a non-surprise, the 'search' test flakes. Try minimizing
that by searching only $IMAGE. If quay.io is down, other tests
will certainly fail.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by edsantiago** [comment]
/hold

The `search` test is [flaking](https://api.cirrus-ci.com/v1/artifact/task/4517455476293632/html/sys-podman-fedora-36-aarch64-root-host.log.html). I was afraid of that, because `search` means network which means flakes. Is there any way to call `podman search --format` without actually trying to ping a registry?

**Comment by Luap99** [comment]
> The `search` test is [flaking](https://api.cirrus-ci.com/v1/artifact/task/4517455476293632/html/sys-podman-fedora-36-aarch64-root-host.log.html). I was afraid of that, because `search` means network which means flakes. Is there any way to call `podman search --format` without actually trying to ping a registry?

No the code has to search before it can display the results. Maybe use a local registry?

**Comment by edsantiago** [comment]
Went with `search $IMAGE`, which should (I assume) hit only `quay.io`, and if `quay.io` is broken, then all tests will fail anyway.

**Pull request merged**
