### PR TITLE
move k8s deps into podman

### PR DESCRIPTION
**Pull request by Luap99**
We only need a small part of the k8s dependencies but they are the
biggest dependencies in podman by far. Moving into podman allows us to
remove the unnecessary parts.

This is just a quick skim over the code which removes a lot of the
generated code and many packages that are now unused.
I know that this will be impossible to properly review. I will try to
make smaller changes in follow up work.

Right now this reduces about 8 MB in binary size!!!

[NO NEW TESTS NEEDED] Hopefully existing tests will catch any problems.

### CODE REVIEW

**Comment by rhatdan** [comment]
@Luap99 Is this still a draft?

**Comment by Luap99** [comment]
Should be ready for review now.

**Comment by Luap99** [comment]
We would need to update this manually. We discussed this in the team last week, the thing is that we already need to handle this manually. Adding a field to a struct does nothing unless someone actually implements this in play/generate kube.

**Comment by baude** [comment]
code lgtm.  lets do it

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
