### PR TITLE
Migrate container images to automation_images

### PR DESCRIPTION
**Pull request by cevich**
Migrated images to: https://github.com/containers/automation_images/pull/25
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
I guess we need to change the auto-build targets on Quay as well. Did that happen already?

**Comment by cevich** [comment]
> I guess we need to change the auto-build targets on Quay as well. Did that happen already?

The publishing model is flipped with the new `containers/automation_images`.  As in, CI in that repo builds the images and pushes them up to quay.  This makes it impossible for an image-build to fail with nobody noticing.

**Comment by cevich** [comment]
Note: I'm waiting for the `podman logs` [failure to be fixed in `crun`, ](https://github.com/containers/crun/issues/496)then I'll rebase/force push this again.

**Comment by rhatdan** [comment]
/approve
lgtm
@containers/podman-maintainers PTAL
@vrothberg @baude PTAL

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
