### PR TITLE
make localunit: record coverage

### PR DESCRIPTION
**Pull request by vrothberg**
Inspirsed by CRI-O's coverage logic.  Initial coverage is at 15.7
percent.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Initial coverage is really low as we test large parts of the code via integration tests.

Shall we enable codecov here as well to display the coverage of the unit tests? Or shall we first work on getting the coverage to a point that we feel comfortable with?

**Comment by rhatdan** [comment]
LGTM. I am fine with displaying it here.

**Comment by TomSweeneyRedHat** [comment]
@vrothberg needs rebase
LGTM for a start, once rebased, I say get this in then deal with codecov.  I'd a bear of a time getting codecov to accept our data from our repos.

**Comment by mheon** [comment]
I think coverage for E2E is more valuable, the way things are now.

This LGTM though

**Comment by vrothberg** [comment]
> I think coverage for E2E is more valuable, the way things are now.

I looked into it. There are ways to instrument a go binary for coverage but I am not yet sure how far we can get that.

Ready to merge

**Comment by vrothberg** [comment]
> I looked into it. There are ways to instrument a go binary for coverage but I am not yet sure how far we can get that.

Currently experimenting with `github.com/confluentinc/bincover` on github.com/vrothberg/vgrep and it's looking quite promising. I guess it would be great to get the coverage from the e2e and maybe even the system tests in case @edsantiago is interested.

**Pull request merged**
