### PR TITLE
Get WSL disk as an OCI artifact

### LINKED ISSUE #22927: Podman-machine default installer, won't resolve/progress on a download issue (lost connection, incomplete file...)
### Bug description

When initializing podman-desktop, the installer is building a default-machine.

A file download process took long (maybe a connection issue), so I exit it. On the next retry, it results in: `error: exit code 125`

In terminal executing `podman machine init`  resulted in `unable to extract and unexpected EOF` error.  

This lead me to find-delete downloaded file, which solved the issue, and installer completed on the next try.  

My assumption is podman or podman-desktop app not making a download completion/verification record, and therefore not deleting/overwriting it on next attempts, instead it tries to extract the incomplete file.

Is best if the file is checked and verified, before extraction, and if not retry overwrite invalid file. 

Thanks.

### Operating system

Windows 10 x64 (ver 22H2 / Build 19045.4412)

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Steps to reproduce

Break the download in default machine install process. (or corrupt the file)

### Relevant log output

```shell
$ podman machine init
time="2024-05-28T10:11:56+03:30" level=error msg="Error extracting compressed file: \"unexpected EOF\""
Error: unexpected EOF
```
```


### Additional context

_No response_

### PR DESCRIPTION
**Pull request by l0rd**
[Since a few days](https://github.com/containers/podman-machine-wsl-os/pull/6) WSL disk releases are also pushed to [quay.io/podman/machine-os-wsl](https://quay.io/repository/podman/machine-os-wsl?tab=tags). This PR updates `podman machine init` mechanism to download WSL disk images. The WSL disk images are now pulled from quay.io as for the rest of the providers.

Fixes #22927 and [RUN-2177](https://issues.redhat.com/browse/RUN-2177)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by ericcurtin** [comment]
Just noticed this PR as a drive-by... Does this mean in future podman-machine will be able to run any available WSL image?

Even on x86_64 Linux and aarch64 macOS.

If yes, I am really excited for this features :)

**Comment by ericcurtin** [comment]
But this is probably wishful thinking on my end...

I guess it's more WSL disk image specifically designed for Windows/WSL2

**Comment by inknos** [comment]
@l0rd could you please add Fixes https://github.com/containers/podman/issues/22927 as well?

**Comment by l0rd** [comment]
> Just noticed this PR as a drive-by... Does this mean in future podman-machine will be able to run any available WSL image?
> 
> Even on x86_64 Linux and aarch64 macOS (via Rosetta if an x86_64 vm).
> 
> If yes, I am really excited for this features :)

No, unfortunately this PR doesn't fix that. It doesn't any user visible impact. We are just changing the way the disk image for WSL is distributed.

**Comment by l0rd** [comment]
> @l0rd could you please add Fixes #22927 as well?

@inknos sure, I have updated the description.

**Review by Luap99 — COMMENTED** [review]
Please make sure to add the information from the PR description also to the commit message.
Also for the `Since a few days WSL...` sentence it would be great to add a link to the commit/PR over there which added support for it.

code wise LGTM

**Comment by l0rd** [comment]
@Luap99 thank you for the review. I have updated the description and the commit message as suggested.

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by l0rd** [comment]
@benoitf and @containers/podman-desktop-reviewers this may have an impact on Podman Desktop because we are publishing the WSL disk image to [quay.io/podman/machine-os-wsl](https://quay.io/repository/podman/machine-os-wsl?tab=tags) and we should stop doing GitHub releases after the release of Podman 5.3.

**Pull request merged**
