### PR TITLE
[2.0] Switch references from libpod.conf to containers.conf

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
This is a cherrypick from master.

**Comment by rhatdan** [comment]
@mheon @vrothberg @baude @TomSweeneyRedHat @ashley-cui @QiWang19 @jwhonce PTAL

**Comment by QiWang19** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
