### PR TITLE
DO NOT MERGE: try to figure out the preserve-fds bug

### PR DESCRIPTION
**Pull request by edsantiago**
Add "ls -l /proc/self/fd" before running the test.
Might be useful to also run "lsof -p $$", what's the
right Go incantation for getting my own pid?

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
none
```

### CODE REVIEW

**Comment by mheon** [comment]
@edsantiago https://pkg.go.dev/os#Getpid

**Comment by edsantiago** [comment]
Yay, [the flake triggered](https://api.cirrus-ci.com/v1/artifact/task/5116209468276736/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-run-preserve-fds-invalid-fd--1)! Boo, there are no extra open fds. Unless `exec.Command()` closes fds??? That would be weird. I'll continue playing with this tomorrow.

**Comment by edsantiago** [comment]
Sigh. Failed, with both `ls` and `lsof` results... but I'm darned if I can figure out a useful difference between the [failed ubuntu log](https://api.cirrus-ci.com/v1/artifact/task/5795147463000064/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-run-preserve-fds-invalid-fd--1) and the [passing one on fedora](https://api.cirrus-ci.com/v1/artifact/task/4669247556157440/html/int-podman-fedora-36-rootless-host.log.html#t--podman-run-preserve-fds-invalid-fd--1).

**Comment by Luap99** [comment]
@edsantiago Yes exec.Command closes all fds, see my comment on the issue:
> We use os/exec to start podman in the tests, it should not matter how many fds we leak in the test since os/exec will always unset all fds.
https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/os/exec/exec.go;l=506-517
That makes me think the leak or bug must be somewhere in podman itself.

It does not matter how many open fds the test has, in fact we cannot control this at all since they run in parallel.
So either the golang lib has a bug and does not close the fds in all cases or we have a bug in podman.

**Comment by edsantiago** [comment]
Ugh, you're right. I guess closing fds is user-friendly in some respects, it's just counterintuitive for someone who grew up on UNIX and C. Thanks for the reminder.

Do you have any suggestions on how else to track this down? Since this is consistently ubuntu-only, could it be something that ubuntu changed in the Go libraries, as a distro patch? Or a too-old version of Go?

Again, this is easy to fix in the test, I just don't want to hide a real bug.

**Comment by Luap99** [comment]
I don't really know, all I see is that we have some custom c code which checks the fds:
https://github.com/containers/podman/blob/84c85f4d9457fb35849fa93ba04814df681b9093/pkg/rootless/rootless_linux.c#L299-L338 
https://github.com/containers/podman/blob/84c85f4d9457fb35849fa93ba04814df681b9093/pkg/rootless/rootless_linux.c#L274-L281

**Comment by edsantiago** [comment]
I notice there's no matching `closedir()` for the `opendir()` on line 300. Should there be?

**Comment by edsantiago** [comment]
Unable to reproduce the flake if I use `-focus` on the ginkgo tests.

**Comment by rhatdan** [comment]
@edsantiago is this still valid, needs a rebase.

**Comment by edsantiago** [comment]
This is an Ubuntu-only flake. We haven't run CI on Ubuntu in a month, so I'll just close this and reopen if we ever get Ubuntu back.

**Pull request closed without merging**
