### PR TITLE
Make binding util internal

### PR DESCRIPTION
**Pull request by matejvasek**
The functions are supposed to be called only from generated code

Signed-off-by: Matej Vasek <mvasek@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by matejvasek** [comment]
rebased

**Review by vrothberg — COMMENTED** [review]
/lgtm
/hold

@baude @mheon, I vote to backport to v3. Since we need to bump the go module to v3 in any case, we're in theory not breaking :^)

**Comment by matejvasek** [comment]
Note that making those functions private is potentially braking for some users. Still the package is out one or two weeks so I doubt anybody is using them. We did more severe change between `3.0.0` and `3.0.1` https://github.com/containers/podman/pull/9414.

**Comment by vrothberg** [comment]
> Note that making those functions private is potentially braking for some users. Still the package is out one or two weeks so I doubt anybody is using them. We did more severe change between `3.0.0` and `3.0.1` #9414.

Currently, Podman 3.0.X is still shipping a `go module v2`.  So we need to update the go module to v3 which would allow for getting this change in without really breaking users.

**Comment by mheon** [comment]
Backport to v3 SGTM.

**Comment by mheon** [comment]
Restarted two flakes.

**Pull request merged**
