### PR TITLE
podman-remote debloat: remove libimage dependency

### PR DESCRIPTION
**Pull request by Luap99**
The podman-remote binary size decreases from 44788 KB to 39424 KB (not stripped).

see commits for details

```release-note
podman build supports to new options: --layer-label and --cw.
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Looks like you have problems finding Get/SetImage

**Comment by Luap99** [comment]
This is because the linter is reading files it should lint under remote mode. Both podman and podman-remote build just fine. Properly need to clutter the whole repo with `!remote` tags to prevent the linter from doing this.

**Comment by Luap99** [comment]
So podman get bloated by buildah, I assume this is caused by the confidential image work by @nalind
```
bin/podman           size= 58380296  delta=285440
```

But this PR is only for podman-remote anyway and that seems to work as expected:
```
bin/podman-remote    size= 40357944  delta=-5485392
```

**Review by mtrmac — COMMENTED** [review]
The libimage changes LGTM. Thanks for working on that!

(I didn’t carefully read the part dealing with the new confidential workload features.)

**Comment by mtrmac** [comment]
@Luap99 Thanks!

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
