### PR TITLE
CI:IMG Backport VM Images with go 1.13

### PR DESCRIPTION
**Pull request by cevich**
A persistent flake occurring only/ever on Ubuntu VMs has thwarted many minutes of debugging time fixing.  A hack update of packages was added in but failed to address the issue.  Becides always being on Ubuntu, the main flaky-test symptom is the error message:

Error: container_linux.go:349: starting container process caused "error adding seccomp rule for syscall socket: requested action matches default action of filter": OCI runtime error

Since this problem does not seem to be present on the master branch at the time of this commit, attempt to fix the problem by using VM images with newer golang on Ubuntu, as well as updated packages.  This is almost purely a speculative fix, as the exact failure mechanism has not been fully debugged.

### CODE REVIEW

**Comment by cevich** [comment]
--force pushed with rebase ontop of #7345

**Comment by mheon** [comment]
@cevich #7345 is so hopelessly broken I have abandoned it in favor of https://github.com/containers/podman/pull/7363 which does not do any chowning

**Comment by mheon** [comment]
Sorry, renaming not chowning

**Comment by cevich** [comment]
Well crap...new images and golang v1.13 doesn't fix the Ubuntu problem:

```
Error: container_linux.go:349: starting container process caused "error adding seccomp rule for syscall socket: requested action matches default action of filter": OCI runtime error
```

**Comment by cevich** [comment]
trying  #7363 and golang 1.14 now...

**Comment by cevich** [comment]
...#7363 and golang 1.13 [fails to build/install ginkgo.](https://cirrus-ci.com/task/5393388008636416?command=build_vm_images#L1511) :confounded:

**Comment by cevich** [comment]
trying #7345 + golang 1.13...

**Comment by cevich** [comment]
@mheon I'm finding #7345 + golang 1.13 (on Ubuntu) is what builds for me.  I'm unable to get past ginkgo failing to find modules, when I rebase on #7363 :confused:

**Comment by mheon** [comment]
Wait - you have #7345 *passing* in CI? Because if that works, I am not really opposed to it...

**Comment by cevich** [comment]
Closing as this does not solve the problem.

**Pull request closed without merging**
