### PR TITLE
[CI:BUILD] Revert "CI: Temporarily disable all AWS EC2-based tasks"

### PR DESCRIPTION
**Pull request by cevich**
This reverts commit 7f8bc6f510979cc3787cd57fb8b06b86efd1833c.

Ref: https://github.com/containers/podman/issues/17537

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
huh, weird :man_shrugging:

**Comment by ashley-cui** [comment]
Bot is confused LOL

/cherry-pick v4.4.1-rhel

**Comment by ashley-cui** [comment]
LGTM

**Review by ashley-cui — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
