### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rhatdan**
Copied from @TeeVenDick patch https://github.com/containers/podman/pull/9072

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @TeeVenDick

**Comment by mheon** [comment]
LGTM, but you really should have CI:DOCS'd this.

@edsantiago Does CI:DOCS also stop your tests check?

**Comment by edsantiago** [comment]
Yes. The presence of `CI:DOCS` (no brackets needed) will bypass the test.

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Pull request merged**
