### PR TITLE
Scrub podman commands to use report package

### PR DESCRIPTION
**Pull request by jwhonce**
Refactor podman commands that have drifted from using
c/common report pkg. Report pkg is needed to implement
go template functions.

Removed obsolete code from podman which exists in c/common.

Latest template library added default newlines and method to
remove them. Incorporated needed changes in c/common PR below.

**Depends on https://github.com/containers/common/pull/624**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1855983

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Comment by jwhonce** [comment]
@edsantiago The failing bats test runs on my laptop. Ideas?

https://github.com/containers/podman/pull/10688/files#diff-dac412933400f230fab7fbc15c36a294e495d77dfcc2f0c4037da3eae4e47928R23

**Comment by edsantiago** [comment]
One of our standard local networking flakes. Restarted. (I didn't look at the int one)

**Comment by jwhonce** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
