### PR TITLE
TODO: Refactor container config

### PR DESCRIPTION
**Pull request by ldelossa**
This commit handle the TODO task of breaking the Container
config into smaller sub-configs.

Signed-off-by: ldelossa <ldelossa@redhat.com>

### CODE REVIEW

**Comment by ldelossa** [comment]
/assign @baude

looks like test failed, but a gating test on a file not affiliated with this change.

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
Ah, I think you broke some test functions that want to make Container structs - looks like `container_internal_test.go` `container_internal_linux_test.go` and `common_test.go` will need a few fields renamed.

**Comment by ldelossa** [comment]
@mheon 

Will take a look at fixing 👍

**Comment by ldelossa** [comment]
@mheon 

friendly ping, all tests fixed.

**Comment by rhatdan** [comment]
@ldelossa needs a rebase.

**Comment by ldelossa** [comment]
Done. Updated a few `Container` method comments for completeness along the way.

**Comment by mheon** [comment]
We really need to do a pass over comments on individual fields in the structs, but that's a lot of work and can happen later.
LGTM once things go green.
/approve

**Comment by ldelossa** [comment]
@mheon As I am just getting acquainted with this code base, if you have an idea of a good starting point for a maintenance task like that, creating an issue and assigning it to me would be welcome on my end. 

thanks for approval.

**Comment by ldelossa** [comment]
looks like all tests passed aside from one, maybe a flake?

**Comment by mheon** [comment]
```
[+0261s] # error opening file `/sys/fs/cgroup//system.slice/buildah-buildah715212271-541317.scope/cgroup.freeze`: No such file or directory
[+0261s] # kill container: No such process
```

Out of a `podman build` system test.
@edsantiago Is this a known flake?

**Comment by edsantiago** [comment]
Aaaaargh! Yes, it is. A bug in crun which I had hoped would be fixed in CI after #6822 got merged yesterday. 

Looking at the failing results, I see `crun-0.13-2.fc31-x86_64` which is the known-bad version. What I can't tell is when this run was made, the timestamp is 11:01:48 but (SIGH) there's no date so I don't know if that was yesterday or today. Is there any chance that the failure happened yesterday? Because that would be good. Or at least OK. If it failed today, I will need to dig a lot deeper into this.

**Comment by ldelossa** [comment]
@edsantiago 

 Cirrus CI / test fedora-31 TEST_REMOTE_CLIENT:false started 23m 8s ago 

So ~23m ago it failed.

**Comment by edsantiago** [comment]
No, that's just the time when the test was restarted. It's still running. I'll check it when it finishes.

**Comment by ldelossa** [comment]
got it, my bad.

**Comment by edsantiago** [comment]
Test passed, but [package versions](https://cirrus-ci.com/task/4638157155074048) shows crun 0.13. Looks like crun 0.14 made it only into f32, not f31. I'll pursue that.

**Comment by ldelossa** [comment]
This good to get merged?

**Comment by mheon** [comment]
Sure, LGTM.
@rhatdan @vrothberg @giuseppe @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
Thanks @ldelossa LGTM
/lgtm

**Pull request merged**
