### PR TITLE
Add missing return after utils.Error()

### PR DESCRIPTION
**Pull request by eriksjolund**
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

[NO NEW TESTS NEEDED}

### CODE REVIEW

**Comment by baude** [comment]
@eriksjolund TYVM!

**Comment by baude** [comment]
LGTM

**Comment by baude** [comment]
I removed the API change label as it does not impact the API but rather is a bug fix on both accounts.

**Comment by eriksjolund** [comment]
@baude In the PR I added another possible missing return. (I hope you noticed that)

> _Does this PR introduce a user-facing change?_

I wrote "none". Please advice me if something else should be written as user-facing change.

**Comment by baude** [comment]
I did see it; LGTM. But that is why it takes 2 reviewers to merge stuff.

**Comment by eriksjolund** [comment]
> But that is why it takes 2 reviewers to merge stuff.
That's a good thing. (Reducing the chance for mistakes).

I added 8 more "missing return" candidates.

**Comment by Luap99** [comment]
Sounds like we could need a linter for this. Very easy to miss in review otherwise.

You have to add `[NO NEW TESTS NEEDED]` to your commit message to pass CI. Change LGTM

**Comment by eriksjolund** [comment]
> Sounds like we could need a linter for this. 

Yes, it would be great if such missing returns could be caught automatically.

I added `[NO NEW TESTS NEEDED]` to the commit message.

**Comment by rhatdan** [comment]
LGTM
Could you rebase your commit, to fix the CI/CD system.

**Comment by eriksjolund** [comment]
Now rebased.

**Pull request merged**
