### PR TITLE
[CI:BUILD] RPM: Fix koji and ELN issues

### PR DESCRIPTION
**Pull request by lsm5**
- build dnsname the old way otherwise it fails on koji
- use the binary path for go-md2man for successful ELN builds

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
would be good to have this in v4.6 before rc1. but not a blocker. I'm not sure yet if packit can do pre-releases, so might have to be a manual task.

**Comment by lsm5** [comment]
aarch64 builds are taking longer because of copr infra issues. We can ignore those for now.

**Comment by lsm5** [comment]
@containers/podman-maintainers PTAL, safe to merge.

**Comment by rhatdan** [comment]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
