### PR TITLE
[CI:DOCS] Fix fish completion issue if the command is prefixed with a space

### LINKED ISSUE #8829: Fish completion not working as expected
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Fish completion will not work if the command is prefixed with a space.

**Steps to reproduce the issue:**

1. In fish shell, type `<SPACE>podman<SPACE>`

2. Press TAB

**Describe the results you received:**

Fish shows file completion
```
❯  podman
bspwm_0_0-socket  fcitx-socket-:0  nvimgPYgkx/  tmux-1000/
```

**Describe the results you expected:**

Fish shows command completion
```
❯ podman
attach                                      (Attach to a running container)
auto-update  (Auto update containers according to their auto-update policy)
build               (Build an image using instructions from Containerfiles)
commit                    (Create new image based on the changed container)
…and 51 more rows
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.6
Git Commit:   a0d478edea7f775b7ce32f8eb1a01e75374486cb
Built:        Thu Dec 24 19:42:33 2020
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
❯ fish --version
fish, version 3.1.2
```

### PR DESCRIPTION
**Pull request by Luap99**
Update the completion script like https://github.com/spf13/cobra/pull/1249.

Fixes #8829

### CODE REVIEW

**Comment by edsantiago** [comment]
Well, this sure brings up an interesting monkey wrench!

As I interpret it, this PR is a manually-done commit, cherrypicking specific cobra fixes but not bringing in the new cobra itself. The obvious question then is, won't the automatically-generated completions override this change?

Ha ha, joke's on me. There are no automatically-generated completions. We're shipping old completion files with no updates.

Effective this week, this will change. I will be adding a CI test that will (1) implement a `make completions` target; (2) run it in CI; (3) fail if any completion file differs from what is checked in. I'll also fix `completions/Readme.md`. The goal is to prevent completion files from getting out of sync with podman or cobra.

@Luap99 I'm afraid that my proposed change will undo your PR. Since mine is just a proposal, not yet implemented or even agreed-upon by the team, I'm OK with this PR merging; but we need to start the conversation right now re: bringing in new cobra.

Thanks as always for raising great questions that improve our code base!

**Comment by Luap99** [comment]
>  Effective this week, this will change. I will be adding a CI test that will (1) implement a make completions target; (2) run it in CI; (3) fail if any completion file differs from what is checked in. I'll also fix completions/Readme.md. The goal is to prevent completion files from getting out of sync with podman or cobra.

Ed, I already had this done when we originally merged my completions PR #6442. 

The problem is that upstream cobra does not have the nice features and bug fixes that I want. There are a lot of open completion PRs. #6442 was merged with my cobra fork. This was not sustainable as pointed out in #8528. So I reverted this #8534. I concluded that it is the best user experience to keep the new (unmerged) scripts.

I was really hoping that this issue would have been resolved by now, but none of the PRs have been merged.

I just got the reminder about #8829 and said whatever, I will fix this issue myself. I do not like to maintain this but I rather give a better user experience than waiting for upstream to merge the fixes.

**Comment by Luap99** [comment]
To give some more context. I am talking about the following cobra PRs:
- https://github.com/spf13/cobra/pull/1258
- https://github.com/spf13/cobra/pull/1249
- https://github.com/spf13/cobra/pull/1213
- https://github.com/spf13/cobra/pull/1146

Except https://github.com/spf13/cobra/pull/1258 because this one needs changes in the go code all of the other PRs are already included in our completions files in the `completions` directory. The `podman completion` command creates old scripts with several problems addressed in those PRs.

**Comment by edsantiago** [comment]
Point taken, thank you. I will hold off on my CI checks.

I can't think of any way to track this problem, other than for a human to watch for a new upstream release, then vendor it in, then alert me to go ahead with the new checks. Can you think of a better way?

**Comment by Luap99** [comment]
> I can't think of any way to track this problem, other than for a human to watch for a new upstream release, then vendor it in, then alert me to go ahead with the new checks. Can you think of a better way?

That's what I am doing. I follow upstream closely.

**Comment by TomSweeneyRedHat** [comment]
LGTM
but I'm not at all a fish expert.
Happy green test buttons.

**Comment by mheon** [comment]
/lgtm

I wonder if we should bring more attention to this upstream - would be nice to finally get those PRs merged

**Pull request merged**
