### PR TITLE
Add podman manifest create -a. Alias for --amend:Docker compatibility

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
podman manifest create -a alias for --amend added, compatible with Docker CLI.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Additional fix for https://github.com/containers/podman/issues/14917

**Comment by rhatdan** [comment]
@nalind @flouthoc PTAL

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
