### PR TITLE
Backports and release notes for v2.1.2

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by Luap99** [comment]
What about 393120c13567ef1b6d42bac357eddf44cfa74d16 and 343a10e25fb12685f18ed3600c567397c01a7cc8? See: #8014

**Comment by mheon** [comment]
@Luap99 I was on the fence as to whether that could be considered a feature/breaking change reserved to v2.2.0 - it's definitely a significant behaviour change (but we already have a few of those)

**Comment by Luap99** [comment]
@mheon I'm fine with just including 343a10e this one is only a bug fix.

**Comment by mheon** [comment]
@Luap99 SGTM - I'll spin up a new PR once this merges so I don't have to restart the tests here again.

**Comment by mheon** [comment]
Ah, `build-each-commit` is failing because it takes substantially longer than the timeout there to rebase + build 70-odd commits.

I'll turn it off for this PR tomorrow, and include the extra commit @Luap99 mentioned.

**Comment by mheon** [comment]
Re-pushed

**Comment by mheon** [comment]
Closing, we're going straight to 2.2

**Pull request closed without merging**
