### PR TITLE
play kube: fix args/command handling

### LINKED ISSUE #8803: `podman play kube` (rootless) does not set `command` and `args` as specfied at the k8s specs
/kind bug

**Description**

https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes describes how pods started by k8s are expected to behave when `CMD` and `ENTRYPOINT` are (possibly) defined at the image and `command` and `args` passed (optionally) from the pod declaration.

When assuming that `podman kube play` should behave as k8s and podman 2.1 do, this is a bug.

If it should not, which I have difficulties understanding, but, missing deeper insights into the project, cannot rule out, it is a breaking change from 2.1 to 2.2 and should be documented as such.

I have suggested a resolution at #8666, which currently and from my perspective, is stalling. I can only guess for the reasons  (hoping not to hurt feelings), but I feel it is not being recognized as either being a bug or being a breaking change.

Personally, I feel that discussing about a fortnight about the resolution of either a bug or a breaking change is too long.
If I have trodden on any feet, I ask to be excused, I do not mean to be disrespectful.

**Steps to reproduce the issue:**

The problem is that containers from images, which have both `ENTRYPOINT` and `CMD` set at the image level, and pod declarations which (legitimately, IMHO) omit `command` and `args`, the container does not and cannot start.

Consider the following pod definition:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: try
spec:
  containers:
    - name: try
      image: docker.io/library/redis:6
```

**Describe the results you received:**

With podman 2.2, on the other hand, it crashes, exhibiting
```bash
./bin/podman-v2.2 inspect try_pod-try \
| jq '.[] | {"args": .Args, "cmd": .Config.Cmd, "entrypoint": .Config.Entrypoint }'
{
  "args": [
    "docker-entrypoint.sh"
  ],
  "cmd": [
    "docker-entrypoint.sh"
  ],
  "entrypoint": "docker-entrypoint.sh"
}
```

**Describe the results you expected:**

With podman 2.1, the pod generating mechanism takes both `command` and `args` from the image and starts just fine, which I would expect to continue with 2.2 deriving from my assumption above. If my assumption is false, I'd like to have a loud and clear warning in the changelogs and be grateful for an explanation.

**Additional information you deem important (e.g. issue happens only occasionally):**

#8666 has further details.

### PR DESCRIPTION
**Pull request by haircommander**
when neither yaml.Args nor yaml.Command are specified, we should use the entrypoint and cmd from the image.

update the tests to cover this and another case (both args and command are specified).
use the registry image instead of redis, as it has both an entrypoint and command specified.
update the documentation around this handling to hopefully prevent regressions and confusion.

fixes #8803

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
lgtm

**Comment by bziemons** [comment]
this does not use the spec's entrypoint (`s.Entrypoint`) at all - I am guessing that can be seen on `podman inspect` and that would be irritating?

**Comment by haircommander** [comment]
> this does not use the spec's entrypoint (`s.Entrypoint`) at all - I am guessing that can be seen on `podman inspect` and that would be irritating?

it seems to be a more invasive change of behavior to start using entrypoint. I'm investigating that now

**Comment by haircommander** [comment]
> > this does not use the spec's entrypoint (`s.Entrypoint`) at all - I am guessing that can be seen on `podman inspect` and that would be irritating?
> 
> it seems to be a more invasive change of behavior to start using entrypoint. I'm investigating that now

I will address this in a follow up, it may need more conversation

/hold cancel

**Review by zhangguanzhang — APPROVED** [review]

**Comment by rhatdan** [comment]
Not sure what is going on here.  Manually merging.

**Comment by AlbanBedel** [comment]
This bug is quiet a severe break of functionality, can this PR be backported for v2.2.2?

**Comment by rhatdan** [comment]
We are doing RC1 for podman 3.0 today.

**Pull request merged**
