### PR TITLE
Remove redundant log message

### PR DESCRIPTION
**Pull request by eriksjolund**
Fixes: https://github.com/containers/podman/issues/15925

Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by Luap99** [comment]
You have to put `[NO NEW TESTS NEEDED]` in your commit message body to pass CI.

**Comment by edsantiago** [comment]
LGTM
/hold cancel

**Pull request merged**
