### PR TITLE
[v5.2-rhel] cirrus: remove functional tests

### PR DESCRIPTION
**Pull request by Luap99**
As discussed at the cabal October 8, 2024 we have no need for these tests on RHEL branches. The work to maintain them is higher than it is worth it. We also do not test RHEL but rather some outdated frozen fedora image build from the time we created the branch.

Therefore we gain little value from them especially as all the internal Red Hat QE is testing it anyways again on the proper RHEL builds.

So simply delete all the stuff we no longer need:
 - alt builds, no point in windows/macos testing and other arches
 - all the functional tests
 - the build success task (not needed as there is nothing after it anymore)
 - the swagger task, we do not use the swagger from the rhel branches

Fixes: https://issues.redhat.com/browse/RUN-2315

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
```
pr-should-link-jira: PR does not include required references to Jira issues

Please add a reference to the related Jira ticket(s) by adding to the
description of the PR something like:

Fixes: https://issues.redhat.com/browse/RHEL-50507
```

And to confirm the jira link check also worked https://cirrus-ci.com/task/5660043243159552

**Comment by Luap99** [comment]
@edsantiago @mheon PTAL, this one is a bit more complicated due the moving of the yaml anchors and the minor yaml test fixes required.

**Review by edsantiago — APPROVED** [review]
LGTM. Again, I only looked at end result, not diffs. I also ran task-map for grins. How's this for a CI task matrix? 
cirrus-map-pr24355

**Pull request merged**
