### PR TITLE
[CI:DOCS] Remove experimental mac tutorial

### PR DESCRIPTION
**Pull request by baude**
This doc is no longer applicable.

[NO NEW TESTS NEEDED]

Signed-off-by: Brent Baude <bbaude@redhat.com>

```release-note
none
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by Luap99** [comment]
podman.io links to that site here: https://podman.io/getting-started/installation#macos
We need to remove the link from there as well.

**Comment by baude** [comment]
deprecation pr -> https://github.com/containers/podman.io/pull/580

**Pull request merged**
