### PR TITLE
Vendor in latest containers/(image,ocicrypt)

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
Restarted flaked jobs.  The bloat comes from sigstore; not much we can do at the moment.

**Comment by mheon** [comment]
/lgtm
/hold

Restarted 4 more flakes

**Comment by mheon** [comment]
(At least, I think they're flakes... no matching tests between all the failures)

**Comment by vrothberg** [comment]
And two more restarts.  Looks like quay.io is having CDN issues.

**Comment by vrothberg** [comment]
And more ...
> [+1529s] # Error: creating build container: initializing source docker://alpine:latest: reading manifest latest in quay.io/libpod/alpine: received unexpected HTTP status: 502 Bad Gateway

**Comment by vrothberg** [comment]
https://status.quay.io/incidents/h993c5nwlnj1 indicates that the Quay team is aware of the CDN issues and that they're working on it.  Let's keep an eye on it.

**Comment by baude** [comment]
how much bloat was added?

**Comment by vrothberg** [comment]
> how much bloat was added?

Nothing anymore since c/image has already been merged. In comparison to v4.3.1, Podman grew by 1 MB.  The sigstore stuff added 3MB IIRC.

**Pull request merged**
