### PR TITLE
[CI:DOCS] Add response to /libpod/containers/stats documentation

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by Luap99** [comment]
Thanks @jelly, can you please squash the commit into one, also the `Signed-off-by` line is missing in the commits.

**Comment by jelly** [comment]
> Thanks @jelly, can you please squash the commit into one, also the `Signed-off-by` line is missing in the commits.

Sorry about that, I've now changed my config to sign off for the podman repo by default :)

**Review by vrothberg — COMMENTED** [review]
Thanks for contributing!

Changes LGTM

To pass CI, the commit message must include the magic string `[NO TESTS NEEDED]`.  CI is enforcing tests for code changes.

**Comment by Luap99** [comment]
I added CI:DOCS to the title if you force push it should work now. We don't need to run all tests for such a change.

**Pull request merged**
