### PR TITLE
Return StatusNotFound when multiple volumes matching occurs

### LINKED ISSUE #22616: podman-remote volume rm ambiguous-name: unmarshalling error
```console
$ bin/podman-remote volume create myvol1
myvol1
$ bin/podman-remote volume create myvol2
myvol2

$ bin/podman-remote volume rm myv
Error: unmarshalling error into &errorhandling.ErrorModel{Because:"", Message:"", ResponseCode:0}, data "{\"cause\":\"volume already exists\",\"message\":\"more than one result for volume name myv: volume already exists\",\"response\":500}\n{\"cause\":\"volume already exists\",\"message\":\"more than one result for volume name myv: volume already exists\",\"response\":404}\n": invalid character '{' after top-level value
```

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes #22616

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@edsantiago PTAL
@mheon PTAL
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
Good catch.
/lgtm

**Comment by rhatdan** [comment]
@edsantiago found the issue, I just found the cure.

**Pull request merged**
