### PR TITLE
WIP: Vendor https://github.com/containers/storage/pull/473 for testing

### PR DESCRIPTION
**Pull request by saschagrunert**
To verify that https://github.com/containers/storage/pull/473 works (or not)

### CODE REVIEW

**Comment by rhatdan** [comment]
https://github.com/containers/libpod/pull/5700 Should help fix this.

**Comment by TomSweeneyRedHat** [comment]
@saschagrunert looks like some lint errors in the unshare package.

**Comment by rhatdan** [comment]
Rebase and this should at least compile now.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master.

**Comment by rhatdan** [comment]
@saschagrunert Needs a rebase again.

**Comment by saschagrunert** [comment]
Hm this issue does not seem reproducible locally to me:
```
Error: error committing container for step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[apk add bash] Flags:[] Attrs:map[] Message:RUN apk add bash Original:RUN apk add bash}: error copying layers and metadata for container "e1d34b849fc5ef59630cebd2a5a7d146604e09db3de35e40d41e4d94c68f69a3": Error reading blob sha256:c82ab33dce84c975f00a42224fa2914b27a943c1175175f67483f4eebdaaf198: error opening file "/var/tmp/buildah155921171/sha256:c82ab33dce84c975f00a42224fa2914b27a943c1175175f67483f4eebdaaf198" to buffer layer blob: open /var/tmp/buildah155921171/sha256:c82ab33dce84c975f00a42224fa2914b27a943c1175175f67483f4eebdaaf198: no such file or directory
```

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by saschagrunert** [comment]
This PR should be green now with the latest changes in https://github.com/containers/storage/pull/473

**Comment by saschagrunert** [comment]
Look how (partially) green! :)

**Comment by rhatdan** [comment]
@saschagrunert Are you getting back to this one?

**Comment by saschagrunert** [comment]
@rhatdan yes, can we move forward with the related PR in containers/storage? (https://github.com/containers/storage/pull/473)

**Comment by rhatdan** [comment]
@saschagrunert Could you update this PR to prove that the containers/storage PR still works?

**Comment by saschagrunert** [comment]
Rebased the referencing PR as well as this one on top of their latest master branches. :+1:

**Comment by saschagrunert** [comment]
Sooo there seems to be an issue now…

**Comment by saschagrunert** [comment]
Hmmm…
```
[+0331s] not ok 50 podman exec - with keep-id
         # (from function `die' in file test/system/helpers.bash, line 287,
         #  from function `run_podman' in file test/system/helpers.bash, line 170,
         #  in test file test/system/075-exec.bats, line 105)
         #   `run_podman exec --user=$(id -un) $cid touch /stop' failed with status 255
         # # podman rm --all --force
         # # podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
         # quay.io/libpod/alpine_labels:latest 4fab981df737
         # # podman run -d --userns=keep-id quay.io/libpod/alpine_labels:latest sh -c echo READY;while [ ! -f /stop ]; do sleep 1; done
         # 396f4537b154ca0d86d607a66f7520c88e271d3619a2b0d2ddeedcaac4d1db2b
         # # podman logs 396f4537b154ca0d86d607a66f7520c88e271d3619a2b0d2ddeedcaac4d1db2b
         # READY
         # # podman exec 396f4537b154ca0d86d607a66f7520c88e271d3619a2b0d2ddeedcaac4d1db2b id -un
         # root
         # # podman exec --user=root 396f4537b154ca0d86d607a66f7520c88e271d3619a2b0d2ddeedcaac4d1db2b touch /stop
         # Error: unable to find user root: no matching entries in passwd file
         # [ rc=255 (** EXPECTED 0 **) ]
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #| FAIL: exit code is 255; expected 0
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         # # [teardown]
         # # podman pod rm --all --force
         # # podman rm --all --force
         # 396f4537b154ca0d86d607a66f7520c88e271d3619a2b0d2ddeedcaac4d1db2b
```

**Comment by rhatdan** [comment]
@saschagrunert Please rebase this PR.

**Comment by saschagrunert** [comment]
I've switched forks, continuing in a new PR: https://github.com/containers/podman/pull/7603

**Pull request closed without merging**
