### PR TITLE
[CI:DOCS] List /etc/containers/certs.d as default for --cert-path

### PR DESCRIPTION
**Pull request by rhatdan**
Helps Document https://github.com/containers/podman/issues/10116

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces: https://github.com/containers/podman/pull/12411

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by jonyhy96** [comment]
Can u show any code ref that really use `/etc/containers/certs.d/` as default? I tried deploy a registry with self-signed certification, it will only work when i do pull with --cert-dir specific to `/etc/containers/certs.d/`.

**Comment by vrothberg** [comment]
https://github.com/containers/image/blob/main/docker/docker_client.go#L188

Do you have a `$HOME/.config/containers/certs.d`?  If that exists, rootless Podman will use that.

**Comment by jonyhy96** [comment]
> https://github.com/containers/image/blob/main/docker/docker_client.go#L188
> 
> Do you have a `$HOME/.config/containers/certs.d`? If that exists, rootless Podman will use that.

After reading through source code of `podman pull`, i can't found any code ref point to `docker_client.go#L188`.

[Pull](https://github.com/containers/podman/blob/main/cmd/podman/images/pull.go#L162) => [abi.Pull](https://github.com/containers/podman/blob/main/pkg/domain/infra/abi/images.go#L243) => [r.copyFromRegistry](https://github.com/containers/podman/blob/main/vendor/github.com/containers/common/libimage/pull.go#L145) => [copySingleImageFromRegistry](https://github.com/containers/podman/blob/main/vendor/github.com/containers/common/libimage/pull.go#L335) => [r.newCopier](https://github.com/containers/podman/blob/main/vendor/github.com/containers/common/libimage/pull.go#L548)

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@umohnani8 when you give the second LGTM, could you add a / in front to merge please.

**Comment by jonyhy96** [comment]
@rhatdan @umohnani8 Have time to take a look at https://github.com/containers/podman/pull/12412#issuecomment-979706223?

**Comment by rhatdan** [comment]
@jonyhy96 Please open a new issue. @vrothberg PTAL

**Comment by rhatdan** [comment]
@mtrmac WDYT?

**Comment by mtrmac** [comment]
> #### What this PR does / why we need it:
? The last comment of #10116 shows this was an user error, but _not_ in the path.

Meanwhile

> Do you have a `$HOME/.config/containers/certs.d`? If that exists, rootless Podman will use that.

so the `/etc/containers/certs.d` value is not “the default”, at least not without further qualification/explanation.

So I think the short paragraph for `--cert-dir` should primarily be a bit more prominent about pointing to the man page to understand the specific directory structure and naming convention — and if users understand that more difficult part, they are also going to find the default paths in the same man page.

**Comment by mtrmac** [comment]
> After reading through source code of `podman pull`, i can't found any code ref point to `docker_client.go#L188`.
> 
> [Pull](https://github.com/containers/podman/blob/main/cmd/podman/images/pull.go#L162) => [abi.Pull](https://github.com/containers/podman/blob/main/pkg/domain/infra/abi/images.go#L243) => [r.copyFromRegistry](https://github.com/containers/podman/blob/main/vendor/github.com/containers/common/libimage/pull.go#L145) => [copySingleImageFromRegistry](https://github.com/containers/podman/blob/main/vendor/github.com/containers/common/libimage/pull.go#L335) => 

No, https://github.com/containers/podman/blob/295a6f7dd086731448a1168a349f62d3035258ca/vendor/github.com/containers/common/libimage/pull.go#L558 (or another way to get a `c/image/docker.dockerReference`) is how it is connected.

**Comment by jonyhy96** [comment]
> > After reading through source code of `podman pull`, i can't found any code ref point to `docker_client.go#L188`.
> > [Pull](https://github.com/containers/podman/blob/main/cmd/podman/images/pull.go#L162) => [abi.Pull](https://github.com/containers/podman/blob/main/pkg/domain/infra/abi/images.go#L243) => [r.copyFromRegistry](https://github.com/containers/podman/blob/main/vendor/github.com/containers/common/libimage/pull.go#L145) => [copySingleImageFromRegistry](https://github.com/containers/podman/blob/main/vendor/github.com/containers/common/libimage/pull.go#L335) =>
> 
> No,
> 
> https://github.com/containers/podman/blob/295a6f7dd086731448a1168a349f62d3035258ca/vendor/github.com/containers/common/libimage/pull.go#L558
> 
> (or another way to get a `c/image/docker.dockerReference`) is how it is connected.

Thanks for explanation! for each sourceReference it will new a docker-client which will actually use `perHostCertDirs`

**Pull request merged**
