### PR TITLE
[CI:DOCS] docs: specify `rmi` removes dangling parents

### PR DESCRIPTION
**Pull request by kwshi**
Same documentation change as containers/buildah#3306, resolving containers/buildah#3302.

### CODE REVIEW

**Comment by rhatdan** [comment]
You have to sign your PRs

git commit -a --amend -s
git push --force

**Review by vrothberg — COMMENTED** [review]
Please remove the empty new lines that were added.

At least one is breaking CI and the others should conceptually be a separate commit.

Other than that, LGTM.

**Comment by kwshi** [comment]
> Please remove the empty new lines that were added.

Oops--those were added by my editor's autoformatting (I didn't realize they were there); I have removed them now.

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm
Thank you :)

**Pull request merged**
