### PR TITLE
Fix flake on failed podman-remote build

### PR DESCRIPTION
**Pull request by rhatdan**
We have a race condition where podman build can fail
but still return an exit code of 0.  This PR ensures
that as soon as the build fails, the failed flag is set
eliminating the race.

Fixes: https://github.com/containers/podman/issues/10029

[NO TESTS NEEDED] Tests of failed builds are already in place, and
the elimination of the race should be enough.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago I ran your tests for a few minutes and could not get this PR to fail.

**Comment by edsantiago** [comment]
@rhatdan I'm sorry... no-go. I'm still seeing it fail, anywhere from 7 seconds to 208 seconds. New reproducer shows how long it takes:
```console
$ t0=$SECONDS;while :;do echo $(($SECONDS - $t0));../bin/podman-remote build -t build_test --pull-never . && break;done
```

**Comment by edsantiago** [comment]
@Luap99 we got a [compose flake!](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4855067355381760/html/compose-podman-fedora-34beta-rootless-host.log.html) Rootless, and `curl` shows one ECONNRESET followed by consistent ECONNREFUSED. To me that implies that the container has died. The timestamps are consistent with that. I don't think any amount of retrying is going to help here; we need a different way to debug.

(Sorry to hijack the thread, Dan)

**Comment by mheon** [comment]
This LGTM, even if it's not a complete fix for the problem - the change on its own does seem to make things better.

**Comment by edsantiago** [comment]
/lgtm
/hold
Le mieux est l'ennemi du bien

**Pull request merged**
