### PR TITLE
Cleanup handling of podman mount/unmount

### PR DESCRIPTION
**Pull request by rhatdan**
We should default to the user name unmount rather then the internal
name of umount.

Also User namespace was not being handled correctly. We want to inform
the user that if they do a mount when in rootless mode that they have
to be first in the podman unshare state.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1857542

**Comment by rhatdan** [comment]
This is a back port from upstream

**Comment by mheon** [comment]
I just built master and tried to `podman mount` in a `podman unshare` shell (both obviously as rootless) and got:
```Error: cannot run command "podman mount" in rootless mode```

I am pretty certain that this is still broken and these patches will not improve the situation.

**Comment by mheon** [comment]
Nevermind. I'm an idiot - used the wrong Podman binary.

LGTM, but CI is red.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
