### PR TITLE
handle play kube with pod.spec.hostAliases

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Fixes: https://github.com/containers/podman/issues/7442
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

### CODE REVIEW

**Comment by zhangguanzhang** [comment]
😢Some errors are in ci, I will fix them when I have time

**Comment by zhangguanzhang** [comment]
@rhatdan @mheon PTAL

**Comment by mheon** [comment]
LGTM, but I'd like @haircommander to do a review before we merge.

**Comment by haircommander** [comment]
LGTM, though you've got a merge conflict

**Comment by zhangguanzhang** [comment]
I will resolve this soon

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by haircommander** [comment]
/lgtm


(could use an approval)

**Pull request merged**
