### PR TITLE
[CI:DOCS] Unify examples section across several man pages: pod rm/start/unpause

### PR DESCRIPTION
**Pull request by patrycja-guzik**
This commit adjusts example sections across several man pages to the format seen in other pages.
Follow up PR #13682 and #13771

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM, thank you!

@containers/podman-maintainers PTAL

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by patrycja-guzik** [comment]
Thanks!

**Pull request merged**
