### PR TITLE
libpod: pass down NoPivotRoot to Buildah

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/containers/podman/issues/24546

```release-note
Now `podman build` honors the `no_pivot_root` setting from `containers.conf` file
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
Can you add a test?

**Comment by giuseppe** [comment]
> Can you add a test?

I've not managed yet to find any reliable way to detect whether `--no-pivot-root` was used or not, the only way I've found is using `strace`

**Comment by Luap99** [comment]
Mhh yeah I guess is not trivial to check and we do not seem to have any test for it on podman run either.
One idea could be to run podman from within a seccomp profile that blocks pivot_root but I guess that isn't easy to setup either.

**Comment by rhatdan** [comment]
LGTM

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
