### PR TITLE
Correct compat images/create?fromImage response

### PR DESCRIPTION
**Pull request by mlegenovic**
#7857

Signed-off-by: Milivoje Legenovic <m.legenovic@gmail.com>

### CODE REVIEW

**Comment by mheon** [comment]
Linter seems to be throwing errors. Nice work, though, glad to see someone take this one!

**Comment by mlegenovic** [comment]
@mheon Do you (or anyone else) have idea how to fix these two tests:

`t POST "images/create?fromImage=alpine" '' 200 .error=null .status~".*Download complete.*"`
`t POST "images/create?fromImage=alpine" '' 200 .error=null .status~".*$old_iid.*"`

Is it possible to handle multi-json result in this test template, or do I need to move these tests to python?

**Comment by mheon** [comment]
I'll defer to @edsantiago for an answer, but I suspect that they'll need to be moved to Python.

**Comment by edsantiago** [comment]
```diff
diff --git a/test/apiv2/10-images.at b/test/apiv2/10-images.at
index a650cf958..f866422e2 100644
--- a/test/apiv2/10-images.at
+++ b/test/apiv2/10-images.at
@@ -41,7 +41,7 @@ t GET images/$iid/json 200 \
   .Id=sha256:$iid \
   .RepoTags[0]=$IMAGE

-t POST "images/create?fromImage=alpine" '' 200 .error=null .status~".*Download complete.*"
+t POST "images/create?fromImage=alpine" '' 200 .error~null .status~".*Download complete.*"

 t POST "images/create?fromImage=alpine&tag=latest" '' 200

@@ -49,7 +49,7 @@ t POST "images/create?fromImage=alpine&tag=latest" '' 200
 old_iid=$(podman image inspect --format "{{.ID}}" docker.io/library/alpine:latest)
 podman rmi -f docker.io/library/alpine:latest
 podman tag $IMAGE docker.io/library/alpine:latest
-t POST "images/create?fromImage=alpine" '' 200 .error=null .status~".*$old_iid.*"
+t POST "images/create?fromImage=alpine" '' 200 .error~null .status~".*$old_iid.*"
 podman untag $IMAGE docker.io/library/alpine:latest

 t POST "images/create?fromImage=quay.io/libpod/alpine&tag=sha256:fa93b01658e3a5a1686dc3ae55f170d8de487006fb53a28efcd12ab0710a2e5f" '' 200
```
(Rats; I thought github would colorize the relevant character diff. `s/=/~/` in the `.error` check)

**Comment by mlegenovic** [comment]
@edsantiago Thanks for the hint, it works.

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
