### PR TITLE
Bump to v2.1.0-RC2

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by jwhonce** [comment]
LGTM

**Comment by rhatdan** [comment]
I think we have a bad version of containers/image in this release.

go.mod still has this line in it.
replace github.com/containers/image/v5 => github.com/containers/image/v5 v5.5.2-0.20200902171422-1c313b2d23e0

**Comment by mheon** [comment]
Alright. We definitely need that fixed for 2.1.0 final.

**Pull request merged**
