### PR TITLE
Backport #20329 to v4.6.1-rhel

### PR DESCRIPTION
**Pull request by mheon**
Backported #20329 to v4.6.1-rhel per RH Jira RHEL-20910 and RHEL-20911.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Addresses: https://issues.redhat.com/browse/RHEL-20910 and https://issues.redhat.com/browse/RHEL-20910
Adding links for easier access.

**Comment by mheon** [comment]
Seems like network issues? Rerunning test

**Review by Luap99 — COMMENTED** [review]
/lgtm
/hold

**Pull request merged**
