### PR TITLE
Revert "container stop: kill conmon"

### PR DESCRIPTION
**Pull request by giuseppe**
the code was added 5 years ago.  It is safe to assume such ancient conmon versions are not used anymore.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by giuseppe** [comment]
looks like conmon is still affected

**Comment by mheon** [comment]
LGTM

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
> [+0452s] # [12:32:29.065179259] $ minikube delete
[+0452s] # [12:32:29.254456746] * Deleting "minikube" in qemu2 ...
[+0452s] # * Removed all traces of the "minikube" cluster.
[+0452s] #
[+0452s] # [12:32:29.333574320] $ podman rmi --ignore localhost/podman-pause:5.1.0-dev-1715288324
[+0452s] # [12:32:29.433581325] Error: image used by dc47524eb166a95023d8e5085683ae8722f88ce0ed88bdf4c6d01e9d7dae5272: image is in use by a container: consider listing external containers and force-removing image

The flake looks like a legit race condition.

**Comment by giuseppe** [comment]
> > [+0452s] # [12:32:29.065179259] $ minikube delete
> > [+0452s] # [12:32:29.254456746] * Deleting "minikube" in qemu2 ...
> > [+0452s] # * Removed all traces of the "minikube" cluster.
> > [+0452s] #
> > [+0452s] # [12:32:29.333574320] $ podman rmi --ignore localhost/podman-pause:5.1.0-dev-1715288324
> > [+0452s] # [12:32:29.433581325] Error: image used by dc47524eb166a95023d8e5085683ae8722f88ce0ed88bdf4c6d01e9d7dae5272: image is in use by a container: consider listing external containers and force-removing image
> 
> The flake looks like a legit race condition.

I've restarted it.  I don't understand how killing conmon would have prevented this error (if anything, it prevents the podman cleanup process to run).

**Comment by vrothberg** [comment]
> I've restarted it. I don't understand how killing conmon would have prevented this error (if anything, it prevents the podman cleanup process to run).

Totally agree that PR doesn't cause the flake 👍

**Pull request merged**
