### PR TITLE
Bump bundled krunkit to 0.1.2

### PR DESCRIPTION
**Pull request by slp**
Bump the bundled krunkit version from 0.1.1 to 0.1.2.

Fixes: #23194

#### Does this PR introduce a user-facing change?

None yet, as this is a fix for a feature that isn't present in a release.

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM
@baude @mheon @giuseppe @Luap99 @ashley-cui PTAL

**Comment by mheon** [comment]
LGTM, but someone more familiar with Mac should review before merge

**Review by Luap99 — APPROVED** [review]
/lgtm

Tested on my mac and seems to work. of course the podman error is useless
`Error: krunkit exited unexpectedly with exit code 1` but that is podman's fault not krun.

**Comment by Luap99** [comment]
Somewhat related, the way we just bump version in the installer without testing them in CI concerns me. I don't think CI is using any of these versions which means it is possible that we include broken versions in the installer and not notice.

@baude @ashley-cui Not sure if you have considered this or if I am missing something?

**Pull request merged**
