### PR TITLE
Use ActiveServiceDestination in ssh remoteConnectionUsername

### PR DESCRIPTION
**Pull request by cgiradkar**
Small fix, which was missed initially in [PR #19997](https://github.com/containers/podman/pull/19997)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
`podman machine ssh ` should really take an option of an URI.  Since you could have multiple machines running at the same time. (Perhaps in the future)

**Comment by vrothberg** [comment]
> `podman machine ssh ` should really take an option of an URI. Since you could have multiple machines running at the same time. (Perhaps in the future)

That works already via the root flags.  While parsing the flags will override the settings in containers.conf.

**Comment by rhatdan** [comment]
/approve
/lgtm
Thanks @cgiradkar

**Comment by vrothberg** [comment]
Thanks, @cgiradkar !

**Pull request merged**
