### PR TITLE
[v3.0.1-rhel] Backport #14321

### PR DESCRIPTION
**Pull request by mheon**
Backport of #14321  to v3.0.1-rhel per https://bugzilla.redhat.com/show_bug.cgi?id=2126937

```release-note
NONE
```

### CODE REVIEW

**Comment by vrothberg** [comment]
Unhappy tests @mheon

**Comment by mheon** [comment]
Looks like infra issues, restarted them all

**Comment by mheon** [comment]
This is ready @containers/podman-maintainers

**Pull request merged**
