### PR TITLE
stats: get mem limit from the cgroup

### PR DESCRIPTION
**Pull request by giuseppe**
b25b330306782019d7aaf7618cd4598a9ae87250 introduced this behaviour.

It was fine at the time because we didn't support "container update", so the limit could not be changed at runtime.  Since it is not possible to change the memory limit at runtime, read the limit as reported from the cgroup.

https://github.com/containers/crun/pull/1217 is required for crun.

[NO NEW TESTS NEEDED] needs a new crun release

Closes: https://github.com/containers/podman/issues/18621

#### Does this PR introduce a user-facing change?

```release-note
podman stats reads the memory limit from the cgroup
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
Can you add a test and add something like `SkipIfCrun("crun x.y.z required")` then someone could enable it at a later point instead of having no test at all.

**Comment by giuseppe** [comment]
> Can you add a test and add something like `SkipIfCrun("crun x.y.z required")` then someone could enable it at a later point instead of having no test at all.

yes that is a better idea.  Added

**Comment by rhatdan** [comment]
LGTM

**Review by Luap99 — COMMENTED** [review]
/lgtm
/hold

**Pull request merged**
