### PR TITLE
fix APIv2 pods top of non-exist pod gets two response value

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Fixes: https://github.com/containers/podman/issues/6514
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@vrothberg @mheon @giuseppe @baude @jwhonce @QiWang19 @ashley-cui @TomSweeneyRedHat PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
