### PR TITLE
Improve podman docker image

### PR DESCRIPTION
**Pull request by StarpTech**
This PR will address #15451

#### Does this PR introduce a user-facing change?

```release-note
No
```

### CODE REVIEW

**Comment by StarpTech** [comment]
Based on the changes, I opened a discussion on how to benefit from all storage features.

**Comment by baude** [comment]
you need to sign your commit(s).  Please do a `git commit --amend -s`

**Comment by StarpTech** [comment]
Done. Is it enough?

**Comment by TomSweeneyRedHat** [comment]
@StarpTech unfortunately not enough,  You need to do the commit, fetch, rebase and push.  https://github.com/containers/podman/pull/15514/checks?check_run_id=8052263971 for details.

**Comment by rhatdan** [comment]
@StarpTech Why not just update the existing Containerfiles to use fedora-minimal

**Comment by vrothberg** [comment]
> > @StarpTech Why not just update the existing Containerfiles to use fedora-minimal
> 
> This would be a breaking change since many important binaries would be missing from the image, i.e. dnf.

I don't consider it a breaking change as we do not give any promises on any packages being installed other than podman.  We should just not backport and override existing images.

I am also in favor of simply updating the existing Containerfiles rather than adding a new image.

**Comment by vrothberg** [comment]
@rhatdan @Luap99, can we settle on a way forward?

**Comment by Luap99** [comment]
Consider this:
```
FROM quay.io/containers/podman
RUN dnf install <extra packages>
```
If somebody is using podman as base it will likely break them. I understand that we do not give any promises. If you think this is fine then do it.

**Comment by rhatdan** [comment]
@Luap99 Makes a good point.  How much size savings to we get and how can we fix the issue that dnf is not installed?

Isn't there an effort to make dnf not require python?, which would make microdnf and dnf the same?

**Comment by vrothberg** [comment]
> Isn't there an effort to make dnf not require python?

@fatherlinux may know

**Comment by vrothberg** [comment]
I begin to think that it's probably not worth risking a breaking change.  The size difference is smaller when downloading the images since the layers are compressed.  We have 38MiB for fedora-minimal and 68MiB for Fedora.

@Luap99 @rhatdan @StarpTech what do you think?

**Comment by rhatdan** [comment]
I agree this is not worth the risk.  We can look at this when/if dnf support gets added to fedora-minimal.

**Comment by rhatdan** [comment]
@StarpTech Thanks for the effort.

**Comment by vrothberg** [comment]
We've been reaching out to the Fedora folks who shared to plan dropping python dependencies of dnf with Fedora 38.

**Pull request closed without merging**
