### PR TITLE
Test podman-remote logs works the same as podman logs

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/7942

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
LGTM, whenever you fix the unprintable characters issue

**Comment by rhatdan** [comment]
@edsantiago @jwhonce fixed this issue with a different PR, but I added this test to make sure that we don't regress.

**Comment by edsantiago** [comment]
I can't entirely be sure that this test is valid, because I don't know if Go `OutputToStringArray()` works the same way as tty output and/or shell pipeline would Did you test this against a pre-jhonce-fix build to make sure it fails? If not, I'll try to figure out what PR that was and will test on my end.

**Comment by rhatdan** [comment]
@edsantiago yes this was failing badly before @jwhonce fix.  I wrote it with my fix, and then found that my fix was not good enough.  My original fix looked good from a human perspective, IE When you ran with a terminal.  But when you ran through this test it would blow up.  Digging deeper we saw that podman-remote was trimming control chars.

**Comment by edsantiago** [comment]
I got your reply after I had already started testing; and I still think there's something missing. I don't think this test is actually testing what you think it's testing. I checked out 8f33751b5, which is the commit immediately prior to @jwhonce's #8282. I built podman and podman-remote, confirmed that `./bin/podman-remote logs foo`  gives me the (erroneous) multi-line output. Then I tried patching `test/e2e/logs_test.go` and running:
```console
$ ~/go/bin/ginkgo -trace -tags remote -debug -progress -r -focus "logs match expected length" test/e2e
...
Running: podman-remote [...] run -t --name test quay.io/libpod/alpine:latest sh -c echo 1; echo 2
output: 1 2
Running: podman-remote [...] wait test
output: 0
Running: podman-remote [...] logs test
output: 1 2
```
...and it passes. That is against what I would expect. I really think that the e2e framework, or Go, or something is silently stripping the `^M`s away, so this test will pass no matter what.

I would be very grateful if someone could confirm my findings by testing against a pre-#8282 commit, and either tell me where I went wrong, or (if I'm correct) suggest a way to make this test do what it claims to do.

Am placing hold on this because I really think it's a NOP test.

/hold

**Comment by edsantiago** [comment]
Found it. The problem is that `OutputToStringArray()` splits on newline, so (of course) it's always going to return two array elements.

The following patch makes the test fail on 8f33751b5 (pre-8282) and pass on 1491b20f0 (post-8282):
```diff
diff --git a/test/e2e/logs_test.go b/test/e2e/logs_test.go
index db48e50ad..a749a86ff 100644
--- a/test/e2e/logs_test.go
+++ b/test/e2e/logs_test.go
@@ -350,6 +350,9 @@ var _ = Describe("Podman logs", func() {
                results := podmanTest.Podman([]string{"logs", "test"})
                results.WaitWithDefaultTimeout()
                Expect(results).To(Exit(0))
-               Expect(len(results.OutputToStringArray())).To(Equal(2))
+               outlines := results.OutputToStringArray()
+               Expect(len(outlines)).To(Equal(2))
+               Expect(outlines[0]).To(Equal("1\r"))
+               Expect(outlines[1]).To(Equal("2\r"))
        })
 })
```
I find it counterintuitive, because I was expecting the opposite (pre-8282 = `^M`, post-8282 = no `^M`) but I haven't looked closely enough at #8282. So please double- and triple-check my logic.

**Pull request merged**
