### PR TITLE
chore: fix function names in comment

### PR DESCRIPTION
**Pull request by findnature**
#### Does this PR introduce a user-facing change?

No

```release-note
 fix function names in comment
```

### CODE REVIEW

**Comment by mheon** [comment]
/approve
Code LGTM

**Comment by mheon** [comment]
Does not appear to have worked, unfortunately.

**Comment by mheon** [comment]
Probably Github gating the merge - branch protection says Total Success must pass.

**Comment by Luap99** [comment]
> Probably Github gating the merge - branch protection says Total Success must pass.

yeah, was just playing around. I did not expect it to work tbh.

**Comment by mheon** [comment]
`# Error: initializing source docker://quay.io/libpod/testimage@sha256:17823456328e5f38b2c0dc7f9453aee0196654dba39ae2220f869717f159159a: can't talk to a V1 container registry`

What a shock, the registry is flaking. Restarted all.

**Comment by mheon** [comment]
/hold
Bit concerned this may be blocking the merge pool.

**Comment by mheon** [comment]
@findnature Mind rebasing to fix the failing tests?

**Pull request merged**
