### PR TITLE
Fix flakey machine starts

### PR DESCRIPTION
**Pull request by ashley-cui**
When starting a podman machine, we rely on SSH-ing into the machine in order to mount volumes. This requires the the machine to be running and listening to SSH connections. Just being able to connect to the SSH port is not a sufficient enough check to ensure the machine is listening to connections - we now check that the connection returns a string - which openSSH does by default on opening a connection.

Fixes: https://github.com/containers/podman/issues/17403

Thanks to @laurent-martin for inspiration on this solution! 

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where occasionally the podman machine start command would fail to mount volumes with a 255 error.
```

### CODE REVIEW

**Comment by ashley-cui** [comment]
@baude @benoitf Try this out - This seemed to work for me on my linux box when I tested it

**Comment by benoitf** [comment]
I tried with a loop but it failed again after few tries :-/

```
$ for i in {0..50};  do echo "trying test number $i"; ./bin/darwin/podman machine stop; ./bin/darwin/podman machine start; done
trying test number 0
Machine "podman-machine-default" stopped successfully
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users:/Users
Mounting volume... /private:/private
Mounting volume... /var/folders:/var/folders

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

	podman machine set --rootful

API forwarding listening on: /Users/benoitf/.local/share/containers/podman/machine/qemu/podman.sock

The system helper service is not installed; the default Docker API socket
address can't be used by podman. If you would like to install it run the
following commands:

	sudo /Users/benoitf/git/containers/podman/bin/darwin/podman-mac-helper install
	podman machine stop; podman machine start

You can still connect Docker API clients by setting DOCKER_HOST using the
following command in your terminal session:

	export DOCKER_HOST='unix:///Users/benoitf/.local/share/containers/podman/machine/qemu/podman.sock'

Machine "podman-machine-default" started successfully
trying test number 1
Waiting for VM to exit...
Machine "podman-machine-default" stopped successfully
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users:/Users
Error: exit status 255

```

**Comment by benoitf** [comment]
```
$ ./bin/darwin/podman --version
podman version 4.6.0-dev

$ git --no-pager log --decorate=short --pretty=oneline -n1
775d24bcb0adb4e41cdd4fa5e19ca29fa851d0df (HEAD -> 255, ashley-cui/255) Fix flakey machine starts
```

**Comment by ashley-cui** [comment]
Thanks for trying it out, @benoitf! I'll see if I have any other ideas..

**Comment by benoitf** [comment]
I don't know if in the ignition script, you could have ready service being only ready after ssh service is listening instead of just having it started

https://unix.stackexchange.com/questions/583054/systemd-wait-till-port-is-open-to-start-service-or-to-declare-a-service-as-star

**Pull request closed without merging**
