### PR TITLE
[v3.4.2-rhel] Fix intermittently missing files in merged directory du…

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
…ring llistxattr

Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2008997 in the
v3.4.2-rhel branch. Bumps c/storage to v1.36.1 that includes this PR:
containers/storage#1037

Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
OK, this one looks much better.  It has the right version for c/storage and best yet, it didn't drag in the json files which I was unsure of in the prior PR.

**Review by vrothberg — COMMENTED** [review]
LGTM, thank you @TomSweeneyRedHat !

**Pull request merged**
