### PR TITLE
Don't panic if a runtime was configured without paths

### PR DESCRIPTION
**Pull request by WxNzEMof**
https://github.com/containers/podman/issues/22561

#### Does this PR introduce a user-facing change?

```release-note
Fix panic when a runtime was configured without executable paths.
```

### CODE REVIEW

**Comment by lsm5** [comment]
@WxNzEMof is your fork rebased on the latest main branch? Any case, ignore the `epel-next-8` branch failures and the `epel-next-9` is a FIPS issue that's being worked on separately.

Also please sign-off on your commit: https://github.com/containers/podman/pull/22640/checks?check_run_id=24729084861

**Comment by WxNzEMof** [comment]
Thanks, I have done this.

**Comment by mheon** [comment]
/approve
LGTM

**Review by lsm5 — COMMENTED** [review]
LGTM

@Luap99 PTAL

**Pull request merged**
