### PR TITLE
Temporarily Revert "Packit: Enable scratch build testing for Fedora 36, 37 and Rawhide"

### PR DESCRIPTION
**Pull request by lsm5**
Packit will probably be brought back soon after including
fix-spec-file-action. See: PR #15457

This reverts commit d45a5d4aa0d04b97ce8a6ad7467e85be870c8d7a.

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### Does this PR introduce a user-facing change?

```release-note
None
```

@vrothberg @edsantiago PTAL

### CODE REVIEW

**Comment by edsantiago** [comment]
In answer to your question on the other thread: packit is not a blocker. slash-lgtm works just fine even with red packit.

**Comment by lsm5** [comment]
> In answer to your question on the other thread: packit is not a blocker. slash-lgtm works just fine even with red packit.

@edsantiago thanks.

@vrothberg i'm hoping you can continue to ignore it :) . It does bother me too, but I'd rather it stare us (me) in the face than only get noticed during actual distro builds. Either way, I'm working on a fix on the other PR, should be in soon. I'm fine if we go ahead with this PR, until then

**Comment by edsantiago** [comment]
Yeah, packit red status is ugly-scary, but it's temporary and I think we can learn from it. I still have grave concerns about packit, but would like to see what other failure modes it has before we disable it (or improve it).

**Comment by vrothberg** [comment]
Yes, I am cool with that.  I implied that it's blocking since some PRs were force merged after the lgtm.

Feel free to close and apologies for the noise.

**Comment by lsm5** [comment]
> Yes, I am cool with that. I implied that it's blocking since some PRs were force merged after the lgtm.

I wonder if that was merge bot being way slower than usual. I've often noticed that on some PRs.
 
> Feel free to close and apologies for the noise.

Not at all. On second thoughts, let's get this in since the packit fix PR might take a while to get fully baked.

**Comment by edsantiago** [comment]
Yep, came here to say that. mergebot has been hanging for O(many minutes) lately, sometimes O(hour).

**Comment by lsm5** [comment]
@vrothberg @edsantiago good to go

**Comment by edsantiago** [comment]
/lgtm

Thanks @lsm5

**Pull request merged**
