### PR TITLE
Fix test flakes caused by improper podman-logs

### PR DESCRIPTION
**Pull request by edsantiago**
This one has been a thorn in my side: it's a podman-log issue, but not remote, so I _almost_ retitled #16132 (removing "remote").

Nope, it's a bug in the tests themselves. One solution would be to podman-wait, but I see no reason for logs to be involved, so I went with podman start -a instead. This removes the k8s-log stuff which is no longer necessary. Cleanup all around.

Signed-off-by: Ed Santiago <santiago@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
/hold cancel

I think this serves as a belated confirmation of #16401 : tests were skipped, but Windows didn't fail.

**Comment by vrothberg** [comment]
Nice catch, @edsantiago !

**Pull request merged**
