### PR TITLE
[CI:DOCS] Update release notes on Main to v5.1.0

### PR DESCRIPTION
**Pull request by mheon**
Also adds in 5.0.1 - 5.0.3 which were missing.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tnk4on** [comment]
This environment variable is not implemented. Only containers.conf.
It needs to be removed.
`you can use the CONTAINERS_MACHINE_ROSETTA environment variable`

**Comment by mheon** [comment]
Updated to remove reference to the environment variable

**Comment by rhatdan** [comment]
LGTM

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
