### PR TITLE
[CI:DOCS] hack/bats - new helper for running system tests

### PR DESCRIPTION
**Pull request by edsantiago**
Well, new to you. It's been something I've used for years.
Simple, but it takes care of a lot of housekeeping, and
makes it ever-so-much-more pleasant to invoke bats tests.
And when it's easier to run tests, tests get run.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

I absolutely adore the `--filter` option.  Super helpful when debugging.

**Comment by TomSweeneyRedHat** [comment]
LGTM
I'll let @mheon press the shiny merge button.

**Comment by edsantiago** [comment]
Poor mheon has no shiny buttons, only email access until tomorrow. (This can obviously wait, but I worry about his backlog)

**Pull request merged**
