### PR TITLE
vendor containers/psgo@v1.7.3

### PR DESCRIPTION
**Pull request by vrothberg**
Add three new capabilities that would otherwise be reported as unknown.

Also add an e2e test making sure that `podman top` knows all
capabilities of the current kernel.  I refrained from adding a system
test since this may blow up in gating tests.

Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug in `podman top` reporting new capabilities as unknown.
```

### CODE REVIEW

**Comment by lsm5** [comment]
ugh, I read the podman-docker.conf path wrong twice. Let me check if it can be easily handled.

**Comment by lsm5** [comment]
@edsantiago @cevich @vrothberg I talked with packit people and I'm working on a fix for the `installed but unpackaged files` issue for packit. Please continue to ignore packit failures until then :smile:

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
