### PR TITLE
Handle hard links in remote builds

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/9893

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Test LGTM, but I'm seeing a weird flake on my laptop (both root and rootless):
```
# podman-remote run --rm build_test stat -c %i /test/Dockerfile
35364677
time="2021-05-20T15:23:26-06:00" level=warning msg="Container 41fd5ed359ae351c1f021d0a7e57ca81576e3b193d8568d135febf79ee38daf0 does not exist: container 41fd5ed359ae351c1f021d0a7e57ca81576e3b193d8568d135febf79ee38daf0 does not exist in database: no such container"
```
Sometimes it happens on the first `podman run`, sometimes on the second. Once even on both.

**Comment by edsantiago** [comment]
Flake filed as #10423

**Comment by rhatdan** [comment]
Requiers https://github.com/containers/storage/pull/916 to be merged before we can merge this.

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by edsantiago** [comment]
[Flake](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5321092370792448/html/sys-podman-ubuntu-2010-rootless-host.log.html) looks like #7139 again

**Pull request merged**
