### PR TITLE
Missing import causing main branch to ftbfs

### PR DESCRIPTION
**Pull request by baude**
Somehow we ended up with a main branch that cannot be built.  A import for strings is missing.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mtrmac** [comment]
See also #21621. I don’t care which one merges.

**Comment by mheon** [comment]
/lgtm
/hold
This one will pass validate

**Comment by mtrmac** [comment]
“Build Each Commit” starts by building the commit before this PR, and that (understandably) fails.

**Comment by mheon** [comment]
Force-pushed to fix main. Closing as this is no longer necessary.

**Pull request closed without merging**
