### PR TITLE
chore: fix some function names in comment

### PR DESCRIPTION
**Pull request by shenpengfeng**
#### Does this PR introduce a user-facing change?

```release-note
 fix some function names in comment
```

### CODE REVIEW

**Comment by Luap99** [comment]
Thanks for the PR but you need to sign off your commit, see https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs

**Comment by baude** [comment]
lgtm

**Comment by mheon** [comment]
LGTM once DCO'd

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
