### PR TITLE
remove contrib/gate

### PR DESCRIPTION
**Pull request by vrothberg**
Remove references on contrib/gate.  The gating image is currently not
maintained and was replaced in the CI rewrite.  We can disable builds
in Quay once the change is merged.

Note that running `make validate` in a container is still desired.
A similar approach may be re-added in the future.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@cevich PTAL

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
but want a cevich head nod.

**Pull request merged**
