### PR TITLE
buildah treadmill: documentation and process updates

### PR DESCRIPTION
**Pull request by edsantiago**
Many small improvements (reviewable as individual commits).

Fixes: RUN-2217

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
This is what the task map looks like in the treadmill (see orange-yellow block in middle) cirrus-map-vendor_buildah_latest

**Review by Luap99 — COMMENTED** [review]
I don't think changes should skip ci, we have basic checks that apply to all files, spell checker, trailing whitspaces/newlines, etc...
Bypassing them can cause a fatal CI failure on the next PR. I don't see this as high risk here but I think it is a bad habit in general.

**Comment by edsantiago** [comment]
I actually agree, and spent a long time thinking about it. Decided to skip CI because:
1. treadmill script is not run anywhere in CI
2. run-buildah-bud-tests only changed wording inside quotes, and I tested (locally) that there are no errors introduced.

Given that, would you still like me to repush and run CI?

**Comment by Luap99** [comment]
If you also made sure the pre-commit hook with the spell checker and trailing whitespace/newline check, etc... pass then I can accept it, changes LGTM.

**Pull request merged**
