### PR TITLE
check memory test based on range

### PR DESCRIPTION
**Pull request by baude**
when verifying that the memory was set correctly for a podman machine instance, we check if the number is between a range because based on architecture, operating system, and memory itself this number can differ significantly.

```release-note
None
```

### CODE REVIEW

**Comment by baude** [comment]
ok, this passed the machine tests.  @lsm5 is checking on aarch64.

**Comment by lsm5** [comment]
#15031 passed with this change.

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by baude** [comment]
folks, @lsm5 needs this to progress on the aarch64 machine tests.  please consider and merge.

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Pull request merged**
