### PR TITLE
podman ps: fix racy pod name query

### LINKED ISSUE #23282: completion: container diff: no such pod
Seen when running system tests in parallel:
```
# [12:02:39.744447467] $ bin/podman __completeNoDesc  container diff
# [12:02:40.521000319] [Debug] [Error] no such pod
# :4
# Completion ended with directive: ShellCompDirectiveNoFileComp
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: container diff: actual container listed in suggestions
# #| expected: '.*-ctrt111_bcqa22xf
# ' (using expr)
# #|   actual: '[Debug] [Error] no such pod'
# #|         > ':4'
# #|         > 'Completion ended with directive: ShellCompDirectiveNoFileComp'
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I've been unable to reproduce

### PR DESCRIPTION
**Pull request by Luap99**
The pod name was queried without holding the container lock, thus it was possible that the pod was deleted in the meantime and podman just failed with "no such pod" as the errors.Is() check matched the wrong error.

Move it into the locked code this should prevent anyone from removing the pod while the container is part of it. Also fix the returned error, there is no reason to special case one specific error just wrap any error here so callers at least know where it happened.

Fixes #23282

#### Does this PR introduce a user-facing change?

```release-note
Fixed a race condition that could make podman ps --pod fail.
```

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago another one

**Comment by Luap99** [comment]
@edsantiago please try this version, seems to work for me now (of course there are still other flakes)

**Comment by edsantiago** [comment]
Looks good - I'm now seeing the `system connection remove` flake and no others. New push on #23275.

**Comment by edsantiago** [comment]
The flake is refusing to manifest on my laptop now.

LGTM!

**Pull request merged**
