### PR TITLE
[CI:DOCS] Remove disused Containerfile and docs

### PR DESCRIPTION
**Pull request by cevich**
Fixes: #21574

The documentation for this image references a quay repository that doesn't exist.  It doesn't appear any of these files have been touched since late 2022, let's just remove them.

Users needing to access remote podman can simply use the `podman` binary present in existing images `quay.io/containers/podman`, `quay.io/podman/stable`, etc.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
> Users needing to access remote podman can simply use the podman binary present in existing images quay.io/containers/podman, quay.io/podman/stable, etc.

This is not an alternative as they are not static remote binaries and don't help for windows/macos at all. 

Either way my best guess looking at the git history is that this was added here but no actual builds were ever made so removing this shouldn't hurt but maybe @praveenkumar and @cfergeau should comment here if they use it somewhere since they added/modifed these files.

**Comment by cevich** [comment]
Thanks Paul.  That was my interpretation of the history as well.  For the record, I'm not opposed to adding an automated build for this.  But the Containerfile will need quite a bit of work to shape it into something the current build system will accept (and be performant).  I am planning on touching this automation soon, so if that's the direction we want to go I can add it into my planning.

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by cevich** [comment]
Marking as a draft to prevent merging, in case further discussion is needed.

**Comment by cevich** [comment]
I think we're good to go ahead and remove these files.  The original reporter has found a suitable solution for their needs.

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
