### PR TITLE
[release-4.2] vendor: bump buildah to `v1.27.0`

### PR DESCRIPTION
**Pull request by flouthoc**
Prepare buildah for `v1.27.0` bump when tag is out.
/hold this till this is pointed to actual tag.

#### Does this PR introduce a user-facing change?

```release-note
vendor: bump buildah to v1.27.0
```

### CODE REVIEW

**Comment by flouthoc** [comment]
Wait for `1.27.0` which will be created after: https://github.com/containers/buildah/pull/4152

**Comment by flouthoc** [comment]
@TomSweeneyRedHat @mheon @nalind @containers/podman-maintainers PTAL

**Review by vrothberg — APPROVED** [review]
LGTM

**Pull request merged**
