### PR TITLE
Add support for a --user flag to allow the user to be passed in to pod…

### PR DESCRIPTION
**Pull request by Mitch9378**
…man-mac-helper

#### Does this PR introduce a user-facing change?

```release-note
Added --user flag to podman-mac-helper cli tool to allow the helper to be installed for a specific user other than the user running the tool. This will allow admin users to install the helper on behalf of a standard user.
```
[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by Mitch9378** [comment]
Documentation PR: https://github.com/containers/podman-desktop/pull/1428

**Review by vrothberg — COMMENTED** [review]
@n1hility PTAL

**Comment by vrothberg** [comment]
In order to pass CI, please add the magic `'[NO NEW TESTS NEEDED]'` string to your commit message.

**Comment by n1hility** [comment]
/approve 

LGTM PR is passing

**Comment by rhatdan** [comment]
Could you fix the commit message to say `support` and repush.
git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
@Mitch9378 are you still out there?

**Comment by rhatdan** [comment]
@n1hility Mind taking this over?

**Comment by vrothberg** [comment]
Closing the PR then.  Thanks, @Mitch9378 and @n1hility !

**Pull request closed without merging**
