### PR TITLE
e2e: show command and output when a timeout happens

### PR DESCRIPTION
**Pull request by Luap99**
To make debugging easier we should see the command and its output when a
failure happens.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
That was the first thing I tried yesterday (except for the `s.Command.Args`, which I did not know about, thank you!)

Unfortunately, in my testing, it appears that the right-hand side is evaluated at call time, not fail time, therefore stdout and stderr are blank. I ended up solving it by using a loop (this did not seem like thread-critical code) and that actually worked in my testing but does not give anything useful in the containerized-checkpoint test timeouts. Possibly I need to `kill` the process so its stdout/err get flushed?

Anyhow, try testing this by running a podman command like `run alpine top -b`, and `WaitWithTimeout(10)`, and see if you get any output.

**Comment by edsantiago** [comment]
This was my "fix" https://github.com/containers/podman/pull/14972/files#diff-b498e3ebab8752c4d5d5efc559e9e0ac50ab2cb1243de2b8666cf7a6c3f21771

**Comment by Luap99** [comment]
@edsantiago Ok I tried this locally and now it should work, we have to change it to a function

**Comment by Luap99** [comment]
Test output:
```
  Timed out after 5.000s.
  command [/home/pholzing/go/src/github.com/containers/podman/bin/podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/podman_test1969136265/root --runroot /tmp/podman_test1969136265/runroot --runtime crun --conmon /usr/bin/conmon --network-config-dir /home/pholzing/.config/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp/podman_test1969136265 --events-backend file --network-backend cni --storage-driver vfs run quay.io/libpod/alpine:latest top -b] timed out
  STDOUT: Mem: 28031604K used, 4489828K free, 5996084K shrd, 4200K buff, 19537524K cached
  CPU:   5% usr   0% sys   0% nic  93% idle   0% io   0% irq   0% sirq
  Load average: 2.06 1.76 1.64 3/1945 1
    PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
      1     0 root     R     1560   0%   6   0% top -b
  
  STDERR: 
  Expected process to exit.  It did not.
```

**Comment by Luap99** [comment]
Tests are green. I like this better than your fix, @edsantiago WDYT?

**Comment by edsantiago** [comment]
This is 1E6 times better than mine, thank you! One quibble: I would prefer:
```diff
- Command %v timed out
+ Command timed out after %ds: %v
```
(i.e., include timeout value, and show command _after_, not before, to make 'Command timed out' a searchable in-page string).

I'm happy to merge this now and address those changes in my neverending #14972 if that's OK with you. Feel free to unhold but continue discussion here.

/lgtm
/hold

**Comment by Luap99** [comment]
/hold cancel

Fell free to make those changes in your PR

**Pull request merged**
