### PR TITLE
clean up: remove unused file

### PR DESCRIPTION
**Pull request by yyzxw**
#### Does this PR introduce a user-facing change?

```release-note
clean up useless files, it duplicates with https://github.com/containers/podman/blob/main/cmd/podman/diff/diff.go
```
[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by giuseppe** [comment]
please add `[NO NEW TESTS NEEDED]` to the commit message

**Comment by rhatdan** [comment]
Thanks @yyzxw 
Please repush your commit, I added [NO NEW TESTS NEEDED]

**Comment by mheon** [comment]
LGTM once re-pushed with no tests needed message.

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the tests are hip

**Comment by rhatdan** [comment]
You need to repush to trigger CI to see [NO NEW TESTS NEEDED] flag.

git commit -a --amend -s
git push --force

**Comment by mheon** [comment]
Last test remaining is an allowed failure, this is good.

**Comment by mheon** [comment]
/lgtm
/approve

Thanks @yyzxw

**Pull request merged**
