### PR TITLE
podman cp: /dev/std{in,out} fixes

### PR DESCRIPTION
**Pull request by vrothberg**
They shouldn't be treated specially to remain compatible with Docker.

Fixes: #9362

### CODE REVIEW

**Comment by mheon** [comment]
I'm a little concerned by the potential for breaking existing users - it's unlikely, but this did work before. I suppose we can say it was never intentional and this is a bugfix?

**Comment by mheon** [comment]
Code changes LGTM

**Comment by vrothberg** [comment]
> I'm a little concerned by the potential for breaking existing users - it's unlikely, but this did work before. I suppose we can say it was never intentional and this is a bugfix?

Agreed.  It's not compatible with Docker's behavior, so it can be seen as a bug.

**Pull request merged**
