### PR TITLE
add netavark plugin support

### PR DESCRIPTION
**Pull request by Luap99**
Add netavark plugins and netavark macvlan dhcp support (was already merged with c/common but this fixes tests and docs).

#### Does this PR introduce a user-facing change?

```release-note
Netavark plugin support is added, the netavark network backend now allows users to create custom network drivers. `podman network create -d <plugin>` can be used to create a network config for your plugin and then podman will use it like any other config and takes care of setup/teardown on container start/stop. This requires at least netavark version 1.6.
```

### CODE REVIEW

**Comment by nalind** [comment]
Try adding this?
```diff
diff --git a/libpod/storage.go b/libpod/storage.go
index dc19a5d4f..8994641fd 100644
--- a/libpod/storage.go
+++ b/libpod/storage.go
@@ -164,8 +165,8 @@ func (r *storageService) CreateContainerStorage(ctx context.Context, systemConte
 	logrus.Debugf("Container %q has run directory %q", container.ID, containerRunDir)
 
 	return ContainerInfo{
-		UIDMap:       options.UIDMap,
-		GIDMap:       options.GIDMap,
+		UIDMap:       container.UIDMap,
+		GIDMap:       container.GIDMap,
 		Dir:          containerDir,
 		RunDir:       containerRunDir,
 		Config:       imageConfig,
```

**Comment by Luap99** [comment]
@mheon @baude PTAL

**Comment by mheon** [comment]
LGTM from my end

**Pull request merged**
