### PR TITLE
[4.7] fix: check wsl npipe when executing podman compose

### PR DESCRIPTION
**Pull request by vrothberg**
#### Does this PR introduce a user-facing change?

```release-note
fix podman compose command not working with wsl
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@cevich CI on this branch is sick

**Comment by Luap99** [comment]
> @cevich CI on this branch is sick

Looks like https://github.com/containers/podman/pull/20341 was merged without passing tests.

But the better question is why do we even run validate on more than one disto/arch? Shouldn't one time be enough? Validate checks based on the source code so checking more than once seems wasteful.

**Comment by vrothberg** [comment]
@baude shall we merge and get CI back later?

**Comment by TomSweeneyRedHat** [comment]
Just adding the upstream PR for reference: https://github.com/containers/podman/pull/20478

**Comment by TomSweeneyRedHat** [comment]
LGTM
I'd be fine with pushing the red merge button at this point while @cevich digs at the CI issue. I'll let @bbaude or @mheon make the final decision.

**Comment by cevich** [comment]
The only reason I can think of to run it across multiple platforms is to ensure it also functions if a developer runs it locally (on their random platform).  Maybe we don't care.  I'm fine if someone wants to strip out the aarch64 validate.

**Comment by mheon** [comment]
I think that the test definitely has value so long as we build for Macs, and we aren't planning on dropping that any time soon. Any idea what's going on - is it just this branch?

**Comment by mheon** [comment]
@Luap99 I think the multiple validates is mostly about build tags - we have a lot of things (esp. in machine) build-tagged for a single architecture or OS

**Comment by cevich** [comment]
> I think the multiple validates is mostly about build tags

Aaaahhh, that sounds like a good reason.  Otherwise those files would all just be ignored.

In any case, the python failure here I'm clueless about.  The pre-commit (python) check has no use across multiple arches (that I'm aware of).  Unfortunately this is an item that does runtime installs as well, so...well...there you go.

It's been a long while since I looked at these CI codepaths, but IIRC they're all lumped in together under a single make target :S

**Comment by mheon** [comment]
Alright, I'm just going to press the button. I would say we should investigate further, but we only have to maintain this branch for another ~3 weeks, so it's probably not worth it.

**Comment by cevich** [comment]
> maintain this branch for another ~3 weeks

Oh forget it, definitely not worth it.  And we don't see this happening on `main` so :man_shrugging:

**Pull request merged**
