### PR TITLE
entities: change the VolumeInfo CreatedAt type to time.Time

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
@mheon The intent is to make the CreatedAt attribute type similar to the other CreatedAt so that they can be easily compared. If I understand correctly, the json encoding converts this to a string and this shouldn't break the API (unless CreatedAt is not a date).

**Comment by rhatdan** [comment]
Looks like you need a go.fmt.

You also need to add a test.

**Comment by rhatdan** [comment]
/approve 
LGTM

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
Thanks! LGTM but I want a final head nod from @mheon or @jwhonce/@baude.  Does it impact the compat API?

**Review by jwhonce — CHANGES_REQUESTED** [review]
I need to dig deeper into all the code, but it appears the VolumeInfo structure was abandoned in favor of github.com/docker/docker/api/types/volume/Volume and libpod/define/InspectVolumeData.

If that is true, I would suggest we delete the orphaned structs and current the swagger documentation. This does not resolve the data type/format issue.

**Comment by rhatdan** [comment]
@mheon WDYT?

**Comment by mheon** [comment]
The abandoning sounds correct - I did that as part of the volume driver work (we have reimplemented inspecting volumes, completely parallel implementations, in at least five places, which I replaced with Libpod's version). I didn't remove this because I suspected it was still in use, but if we still compile cleanly after, the struct can be torn out without concern.

**Comment by rhatdan** [comment]
@TristanCacqueray @mheon @What is the state of this PR?

**Comment by mheon** [comment]
Needs to be replaced with a new PR that removes this struct, at a minimum (it's currently unused) and possibly adjusts the types used by volume inspect.

**Pull request closed without merging**
