### PR TITLE
[CI:BUILD] Packit: remove pre-sync action

### PR DESCRIPTION
**Pull request by lsm5**
The pre-sync action constantly breaks and is currently not possible to reliably test until the subsequent upstream release due to limitations in packit.

The lines being added by the action script to the downstream Fedora spec were only meant to keep Fedora happy. But given that they provide no tangible benefit as github notifies us of security issues in libraries mentioned in go.mod and go.sum, along with redhat prodsec's own magic for creating security alerts, there's absolutely no point to having the pre-sync action run and add a layer of uncertainty.

This commit removes the pre-sync action and
`rpm/update-spec-provides.sh`.

Ref: https://github.com/containers/podman/issues/19232

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

Does not affect upstream.

### CODE REVIEW

**Comment by lsm5** [comment]
safe to merge once green.

**Comment by lsm5** [comment]
@podman-maintainers PTAL

**Comment by lsm5** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by lsm5** [comment]
merge-me.

**Comment by lsm5** [comment]
@ashley-cui could you please slash-merge this? i'd like this cherrypicked into v4.6 before v4.6.0.

**Review by ashley-cui — COMMENTED** [review]
/lgtm

**Pull request merged**
