### PR TITLE
Vendor in containers/common v0.46.0

### PR DESCRIPTION
**Pull request by vrothberg**
Fixes: https://github.com/containers/podman/issues/11745

[NO TESTS NEEDED] Since this is just a revendor and a one line
change for the revendor

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
Please use https://github.com/containers/podman/pull/11741/commits/413b9f74894c3a5eb09d77fc62ee67ea718a4522

**Comment by vrothberg** [comment]
> Please use [413b9f7](https://github.com/containers/podman/commit/413b9f74894c3a5eb09d77fc62ee67ea718a4522)

Done.

**Review by Luap99 — APPROVED** [review]
LGTM

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
