### PR TITLE
Bump to v3.1.0-RC2

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by mheon** [comment]
@cevich FYI, new branch here.

**Comment by mheon** [comment]
There's a test failure that seems consistent, but I have no idea how it could be related. Going to retry one more time before I look further.

**Comment by mheon** [comment]
Finally green.

@containers/podman-maintainers PTAL

**Comment by cevich** [comment]
Opened https://github.com/containers/podman/pull/9793 which should probably merge before this PR.

Also, @mheon does this mean I should start up daily cirrus-cron builds on this branch, and gut v3.0 `.cirrus.yml` down to minimal testing?

**Comment by mheon** [comment]
Yes to both.

**Comment by mheon** [comment]
I think we need to merge this as-is, though. I can't really rebase as the commit and tag are both signed.

**Comment by cevich** [comment]
> I think we need to merge this as-is, though. I can't really rebase as the commit and tag are both signed.

Okay, the branch and tag testing might fail w/o that `$DEST_BRANCH=v3.1` update, but should clear up after #9793 merges.  I'm pretty sure I specified this in the release-process, **so somebody** isn't following the documentation :smile: 

I'll add v3.1 into the cron mix, and work on a PR to gut the v3.0 testing.

**Comment by mheon** [comment]
Eh, it's just an RC. We just need to get it right on Thursday for the final release.

**Comment by cevich** [comment]
> Eh, it's just an RC

Yep, it's fine for an RC, I was just teasing.

I opened #9794 to dial-back the v3.0 testing, and a cirrus-cron job is setup for v3.1.  Any failures should start showing up in tomorrow's report, otherwise "no news is good news".

**Comment by jwhonce** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
