### PR TITLE
test/system: run tests in parallel where possible

### PR DESCRIPTION
**Pull request by Luap99**
This is part 1 of major work to try to parallelize as much system tests
as we can do speed overall test time up.

Problem is we can no longer perfom any leaks check or removal after each
run which could be an issue. However as of commit https://github.com/containers/podman/commit/81c90f51c242ecb082c71cb53e80c5cbb89b2a6f we no longer
do the leak check anyway in CI.

There will be tests that cannot be parallelized as they touch global
state, i.e. image removal.

This commits used the bats -j option to run tests in parallel but also
sets --no-parallelize-across-files to make sure we never run parallel
across files. This allows us to disable parallel on a per file basis via
the BATS_NO_PARALLELIZE_WITHIN_FILE=true option.

Right now only 001 and 005 are setup to run in parallel and this alone
gives me a 30s total time improvement locally when running both files.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
I don't see this being possible. For instance, any test in `120-load.bats` is going to conflict with anything in `build` or `systemd`.

**Comment by Luap99** [comment]
> I don't see this being possible. For instance, any test in `120-load.bats` is going to conflict with anything in `build` or `systemd`.

That is what --no-parallelize-across-files is for different files are never executed in parallel, then we just set the BATS_NO_PARALLELIZE_WITHIN_FILE=true option in any file that cannot run in parallel which is what I do right now.
This is really just following your suggestions https://github.com/containers/podman/pull/22698#issuecomment-2115129093 and see where we go from here 

So now I just go over all the file and see where I can make it work in parallel, the potential savings are huge. If it turns out to be not worth it or to complex we can abandon this effort and look into other solutions.

**Comment by Luap99** [comment]
| type | distro              | user     | DB     |    local |   remote | container |
| ---- | --------            | ----     | --     |    ----: |   -----: | --------: |
| sys  | rawhide             | root     |        |    29:26 |    20:56 |
| sys  | rawhide             | rootless |        |    32:39 |          |
| sys  | fedora-40-aarch64   | root     |        |    25:45 |    17:31 |
| sys  | fedora-40           | root     |        |    30:20 |    19:31 |
| sys  | fedora-40           | rootless |        |    28:34 |    20:55 |
| sys  | fedora-39           | root     | boltdb |    31:30 |    21:15 |
| sys  | fedora-39           | rootless | boltdb |    33:24 |          |
| sys  | debian-13           | root     |        |    30:50 |    22:23 |
| sys  | debian-13           | rootless |        |    34:11 |          |

Just as a base where we are right now. I will push some more changes to see if there is a noticeable speed-up compared to that.

**Comment by Luap99** [comment]
| type | distro              | user     | DB     |    local |   remote | container |
| ---- | --------            | ----     | --     |    ----: |   -----: | --------: |
| sys  | rawhide             | root     |        |    29:19 |    18:37 |
| sys  | rawhide             | rootless |        |    31:04 |          |
| sys  | fedora-40-aarch64   | root     |        |    22:39 |    16:40 |
| sys  | fedora-40           | root     |        |    28:58 |    20:04 |
| sys  | fedora-40           | rootless |        |    28:59 |    19:04 |
| sys  | fedora-39           | root     | boltdb |    31:06 |    22:30 |
| sys  | fedora-39           | rootless | boltdb |    29:56 |          |
| sys  | debian-13           | root     |        |    29:07 |    21:13 |
| sys  | debian-13           | rootless |        |    34:25 |          |

Looks better an average I would say. Although not by much, I think the run to run variance is still very high I think I need to cut into the slower tests more to make a noticeable impact and maybe up the cpu cores so we can actually take advantage of the parallel runs.

**Comment by edsantiago** [comment]
>That is what --no-parallelize-across-files is for

Grrr, I deserve that for trying to do a quick sloppy review on my way out the door. I will be more careful today.

**Comment by Luap99** [comment]
| type | distro              | user     | DB     |    local |   remote | container |
| ---- | --------            | ----     | --     |    ----: |   -----: | --------: |
| sys  | rawhide             | root     |        |    28:20 |    17:40 |
| sys  | rawhide             | rootless |        |    27:47 |          |
| sys  | fedora-40-aarch64   | root     |        |    24:37 |    15:53 |
| sys  | fedora-40           | root     |        |    27:54 |    17:53 |
| sys  | fedora-40           | rootless |        |    29:02 |    16:28 |
| sys  | fedora-39           | root     | boltdb |    30:52 |   !19:47 |
| sys  | fedora-39           | rootless | boltdb |    28:38 |          |
| sys  | debian-13           | root     |        |    28:31 |    20:24 |
| sys  | debian-13           | rootless |        |    29:59 |          |

Current timings, the time is going down but not as much as I would have hoped. Many slow tests cannot be run in parallel without major changes and our VMs currently only have two cores. I try to use 4 core VM like the int tests next.

**Comment by Luap99** [comment]
Also one selinux test seem to have flaked which I need to figure out.

**Comment by Luap99** [comment]
So the one things I am trying to understand is when running locally (12 threads) I see a huge delta from run to run, i.e. running the selinux file is around ~13s most of the times but then there are outliers where it is 45-50s.

I like to understand this before I continue pushing more changes into this PR.

**Comment by edsantiago** [comment]
Are you running with `-T`? Can you post sample results?

**Comment by Luap99** [comment]
Yes always with `-T` (I wonder if we should have this by default in hack/bats?)

```
$ hack/bats -T --rootless --remote  410
--------------------------------------------------
$ bats  test/system/410-selinux.bats
410-selinux.bats
 ✓ [410] podman selinux: confined container [1680]
 ✓ [410] podman selinux: container with label=disable [2259]
 ✓ [410] podman selinux: privileged container [2432]
 ✓ [410] podman selinux: privileged --userns=host container [2120]
 ✓ [410] podman selinux: --ipc=host container [2808]
 ✓ [410] podman selinux: init container [2241]
 ✓ [410] podman selinux: init container with --security-opt type [2794]
 ✓ [410] podman selinux: init container with --security-opt level&type [3211]
 ✓ [410] podman selinux: init container with --security-opt level [2869]
 ✓ [410] podman selinux: pid=host [3577]
 ✓ [410] podman selinux: container with overridden range [2342]
 - [410] podman selinux: inspect kvm labels (skipped: runtime flag is not passed over remote) [1076]
 ✓ [410] podman selinux: inspect multiple labels [2645]
 ✓ [410] podman selinux: shared context in (some) namespaces [6962]
 ✓ [410] podman selinux: containers in pods share full context [4999]
 ✓ [410] podman selinux: containers in --no-infra pods do not share context [3368]
 ✓ [410] podman with nonexistent labels [2159]
 ✓ [410] podman selinux: check relabel [5928]
 ✓ [410] podman selinux nested [3569]
 ✓ [410] podman EnableLabeledUsers [3553]
 - [410] podman selinux: check unsupported relabel (skipped: not applicable under rootless podman) [959]

21 tests, 0 failures, 2 skipped in 12 seconds

$ hack/bats -T --rootless --remote  410
--------------------------------------------------
$ bats  test/system/410-selinux.bats
410-selinux.bats
 ✓ [410] podman selinux: confined container [1791]
 ✓ [410] podman selinux: container with label=disable [1867]
 ✓ [410] podman selinux: privileged container [40455]
 ✓ [410] podman selinux: privileged --userns=host container [2177]
 ✓ [410] podman selinux: --ipc=host container [2532]
 ✓ [410] podman selinux: init container [2242]
 ✓ [410] podman selinux: init container with --security-opt type [1877]
 ✓ [410] podman selinux: init container with --security-opt level&type [2923]
 ✓ [410] podman selinux: init container with --security-opt level [2824]
 ✓ [410] podman selinux: pid=host [3192]
 ✓ [410] podman selinux: container with overridden range [2505]
 - [410] podman selinux: inspect kvm labels (skipped: runtime flag is not passed over remote) [1205]
 ✓ [410] podman selinux: inspect multiple labels [3443]
 ✓ [410] podman selinux: shared context in (some) namespaces [6226]
 ✓ [410] podman selinux: containers in pods share full context [5480]
 ✓ [410] podman selinux: containers in --no-infra pods do not share context [4180]
 ✓ [410] podman with nonexistent labels [2511]
 ✓ [410] podman selinux: check relabel [6003]
 ✓ [410] podman selinux nested [3538]
 ✓ [410] podman EnableLabeledUsers [3821]
 - [410] podman selinux: check unsupported relabel (skipped: not applicable under rootless podman) [723]

21 tests, 0 failures, 2 skipped in 44 seconds
```

Note I am using remote here as I have been using it all day to reproduce selinux remote flake I saw but I am pretty sure I have seen this with local and other files as well.

**Comment by Luap99** [comment]
>  ✓ [410] podman selinux: privileged container [40455]

It is always a different tests that is slow so not sure where the pattern is

**Comment by edsantiago** [comment]
#22886 enabled `-T` in Makefile, but I didn't include hack/bats because I couldn't (quickly) think of a way to add a disable-T option. That no longer seems as important now. If you feel like enabling `-T` in hack/bats here, I'm fine with that.

>It is always a different tests that is slow so not sure where the pattern is

Weird. My first assumption was a lock, but that seems unlikely if only one test is hiccuping. I've skimmed the source file and see nothing obvious.

**Comment by Luap99** [comment]
Cherry-picked commits from https://github.com/containers/podman/pull/22831. Given it runs in parallel here maybe IO is a bigger bottleneck so I like to try it out.

**Comment by Luap99** [comment]
```
<+     > # # podman rmi -f quay.io/libpod/systemd-image:20240124
<+115ms> # Untagged: quay.io/libpod/systemd-image:20240124
         # Deleted: 77def021e71fdab2c91a22b49cba046d8b1e62842583d2509305c70bec48e36f
         #
<+159ms> # # podman ps -a --external
<+043ms> # CONTAINER ID  IMAGE                         COMMAND     CREATED             STATUS      PORTS       NAMES
         # 65fb253e2a2f  quay.io/libpod/alpine:latest  top -d 120  About a minute ago  Removing                c__B1jcHj6XA0
         #
<+009ms> # # podman system df
<+043ms> # time="2024-07-01T10:41:39Z" level=error msg="failed to get root file system size of container 65fb253e2a2fc055c2eaec94241c9a60f02a2381ee1b16783ac8768c0405a47f: container not known"
         # time="2024-07-01T10:41:39Z" level=error msg="failed to get read/write size of container 65fb253e2a2fc055c2eaec94241c9a60f02a2381ee1b16783ac8768c0405a47f: container not known"
         # TYPE           TOTAL       ACTIVE      SIZE        RECLAIMABLE
         # Images         1           0           13.14MB     13.14MB (100%)
         # Containers     1           0           0B          0B (0%)
         # Local Volumes  0           0           0B          0B (0%)
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #| FAIL: Command succeeded, but issued unexpected warnings
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         # # [teardown]
```

Ok finally captured the issue, something in auto-update seems to leak a container (stucked in removing state for some reason). Auto-update runs them in system units so I guess systemd killing the podman process in the wrong moment for whatever reasons, that will be fun to debug :(

**Comment by Luap99** [comment]
| type | distro              | user     | DB     |    local |   remote | container |
| ---- | --------            | ----     | --     |    ----: |   -----: | --------: |
| sys  | rawhide             | root     |        |    23:11 |    15:25 |
| sys  | rawhide             | rootless |        |    22:35 |          |
| sys  | fedora-40-aarch64   | root     |        |    18:48 |    12:34 |
| sys  | fedora-40           | root     |        |    23:19 |    14:53 |
| sys  | fedora-40           | rootless |        |    22:39 |    14:02 |
| sys  | fedora-39           | root     | boltdb |    26:14 |    16:01 |
| sys  | fedora-39           | rootless | boltdb |   !24:39 |          |
| sys  | debian-13           | root     |        |    24:22 |   !17:18 |
| sys  | debian-13           | rootless |        |    27:48 |          |

current timings, but it is still a bit to flaky overall

```
[+0189s] not ok 109 [030] podman run --restart=always -- wait in 21330ms
         # tags: distro-integration
         # (from function `run_podman' in file test/system/[helpers.bash, line 499](https://github.com/containers/podman/blob/777a051af0300238afb7568441fe230ec9b0390a/test/system/helpers.bash#L499),
         #  in test file test/system/[030-run.bats, line 1272](https://github.com/containers/podman/blob/777a051af0300238afb7568441fe230ec9b0390a/test/system/030-run.bats#L1272))
         #   `PODMAN_TIMEOUT=20 run_podman wait $ctr' failed
         #
<+     > # # podman-remote --url unix:///tmp/CI_5VDR/podman_tmp_tDHa run -d --restart=always --name=cHNEvaUbH8 quay.io/libpod/testimage:20240123 false
<+187ms> # c2d3116c1519fd3d99717780c6e7b1c24c619f12032c0425775200020b6d7fe5
         #
<+010ms> # # podman-remote --url unix:///tmp/CI_5VDR/podman_tmp_tDHa wait cHNEvaUbH8
<+0020s> # timeout: sending signal TERM to command ‘/var/tmp/go/src/github.com/containers/podman/bin/podman-remote’
<+006ms> # [ rc=124 (** EXPECTED 0 **) ]
         # *** TIMED OUT ***
         # # [teardown]
         #
<+011ms> # # podman-remote --url unix:///tmp/CI_5VDR/podman_tmp_tDHa pod rm -t 0 --all --force --ignore
         #
<+046ms> # # podman-remote --url unix:///tmp/CI_5VDR/podman_tmp_tDHa rm -t 0 --all --force --ignore
<+390ms> # c2d3116c1519fd3d99717780c6e7b1c24c619f12032c0425775200020b6d7fe5
         #
<+002ms> # # podman-remote --url unix:///tmp/CI_5VDR/podman_tmp_tDHa network prune --force
         #
<+030ms> # # podman-remote --url unix:///tmp/CI_5VDR/podman_tmp_tDHa volume rm -a -f
         #
<+029ms> # # podman-remote --url unix:///tmp/CI_5VDR/podman_tmp_tDHa ps --all --external --format {{.ID}} {{.Names}}
         #
<+028ms> # # podman-remote --url unix:///tmp/CI_5VDR/podman_tmp_tDHa images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
``` 
https://api.cirrus-ci.com/v1/artifact/task/4782324846428160/html/sys-remote-debian-13-root-host-sqlite.log.html

This seems to be a consistent one, I tried reproducing locally for quite some time without luck.

**Comment by Luap99** [comment]
For the record, first run without seeing any flake. However I still know there are some flakes here
1. podman selinux remote tests are flaky (I found the cause and have a fix planned)
2. podman run --restart=always -- wait (timeout sometimes, cause unknown and I am unable to reproduce)
3. podman run --cgroups=disabled --cgroupns=host as root (fix in https://github.com/containers/podman/pull/23206)

The leaking containers flake in systemd df tests is already fixed (https://github.com/containers/podman/pull/23203)

As I don't like to merge any known flakes I would like to get 1 and 2 fixed first before we can merge this here.

**Comment by Luap99** [comment]
On a single core system I get: 
```
The flag --no-parallelize-across-files requires at least --jobs 2
```

So I guess that needs fixing too, that raises the question should we not use parallel in this case or maybe given many tests do sleeps maybe we could benefit from `nproc * 2`, time to measure how this behaves.

**Comment by Luap99** [comment]
| type | distro              | user     | DB     |    local |   remote | container |
| ---- | --------            | ----     | --     |    ----: |   -----: | --------: |
| sys  | rawhide             | root     |        |    22:00 |    14:21 |
| sys  | rawhide             | rootless |        |    23:59 |          |
| sys  | fedora-40-aarch64   | root     |        |    18:52 |    11:55 |
| sys  | fedora-40           | root     |        |    23:02 |    14:27 |
| sys  | fedora-40           | rootless |        |    21:42 |    14:05 |
| sys  | fedora-39           | root     | boltdb |    26:45 |    15:40 |
| sys  | fedora-39           | rootless | boltdb |    24:24 |          |
| sys  | debian-13           | root     |        |    25:34 |    16:41 |
| sys  | debian-13           | rootless |        |    27:02 |          |

Timings right now with bats jobs == nproc

**Comment by Luap99** [comment]
```
[+1365s] not ok 619 [505] UDP/IPv4 large transfer, loopback in 5008ms
         # (from function `bail-now' in file test/system/[helpers.bash, line 184](https://github.com/containers/podman/blob/925786465ee42f66d40057f60f5f9ca83fc1dd59/test/system/helpers.bash#L184),
         #  from function `assert' in file test/system/[helpers.bash, line 1020](https://github.com/containers/podman/blob/925786465ee42f66d40057f60f5f9ca83fc1dd59/test/system/helpers.bash#L1020),
         #  from function `pasta_test_do' in file test/system/[505-networking-pasta.bats, line 239](https://github.com/containers/podman/blob/925786465ee42f66d40057f60f5f9ca83fc1dd59/test/system/505-networking-pasta.bats#L239),
         #  in test file test/system/[505-networking-pasta.bats, line 720](https://github.com/containers/podman/blob/925786465ee42f66d40057f60f5f9ca83fc1dd59/test/system/505-networking-pasta.bats#L720))
         #   `pasta_test_do' failed
         #
<+     > # $ podman info --format {{.Host.Pasta.Executable}}
<+754ms> # /usr/bin/pasta
         # 1+0 records in
         # 1+0 records out
         # 53248 bytes (53 kB, 52 KiB) copied, 0.000231262 s, 230 MB/s
         #
<+162ms> # $ podman run --rm --net=pasta -p [127.0.0.1]:5681:5681/udp quay.io/libpod/testimage:20240123 sh -c for port in $(seq 5681 5681); do                              socat -u UDP4-LISTEN:${port},bind=[127.0.0.1],null-eof EXEC:md5sum &                          done; wait
<+2.23s> # 8f8fc9edae69e969df2869e16a5f9f1d  -
         # 2024/07/08 16:19:00 socat[3] W waitpid(0, 0x7ffdee4a798c, 0): No child process
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #|     FAIL: Mismatch between data sent and received
         # #| expected: = 8f8fc9edae69e969df2869e16a5f9f1d  -
         # #|   actual:   8f8fc9edae69e969df2869e16a5f9f1d  -
         # #|         >   2024/07/08 16:19:00 socat\[3\] W waitpid\(0\, 0x7ffdee4a798c\, 0\): No child process
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

That is a new one, https://api.cirrus-ci.com/v1/artifact/task/6162628752441344/html/sys-podman-debian-13-rootless-host-sqlite.log.html

**Comment by Luap99** [comment]
@edsantiago How do you want to proceed here? I can push more commits porting more file to run in parallel here but that just makes the diff bigger and reviewing more complicated. Should I open a smaller PR first with just a few commits so we can start merging some of the code?

**Comment by Luap99** [comment]
> I haven't been reviewing because of all the churn and all the flakes. Are you saying this is ready for review, even with the flakes?

The code is not going to change at this point. I know there is one flake causes in the "parallel selinux test" commit so that one cannot be merged until I get to fix the actual podman bug behind it but the rest should should be fine IMO. I haven't seen the "podman wait" hang flake in recent pushes so maybe that one is good, the pasta test flake no idea I have seen it only once and don't think it related to my changes other than some timing changes.

**Comment by Luap99** [comment]
Also I can try to drop "cirrus: use fastvm for system tests" from the series, I am not sure if is worth until I have ported over more files.

**Comment by edsantiago** [comment]
Can you give me something that passes CI? Either a new subset PR, or this one with parallel SELinux disabled?

**Comment by Luap99** [comment]
Dropped "cirrus: use fastvm for system tests" and "test/system: enable parallel selinux tests" from the series, I am pretty sure this should pass

**Comment by Luap99** [comment]
Well or maybe not, I guess the free port logic is not race free as we just check once so it is causing flakes in the pasta tests.

For the two healthcheck flakes I need to take a deeper look, there are sleeps in the test to wait for healthchecks in the background so I expect it is racy.

**Comment by Luap99** [comment]
dropped "parallel pasta tests" for now. I think we need to teach the random port logic to assign no conflicting ports in parallel case similar to what you did in e2e but I am not sure if bats exposes the "node" number

Also pushed another commit to hopefully fix the healthckeck flake.

**Comment by Luap99** [comment]
Also one thing to consider this makes it very hard to track flakes for you, currently if a test fails we call cleanup which well removes all containers,etc... so everything running in parallel will likely fail as well because of that, i.e. look at https://api.cirrus-ci.com/v1/artifact/task/5497890087370752/html/sys-podman-fedora-39-root-host-boltdb.log.html

I am not sure if there is a way around that, we could try to defer cleanup until the end of the file but it will make the teardown code even more complicated.

**Comment by edsantiago** [comment]
I've been reviewing all day as time allows and I'm feeling a growing concern. This is a lot of complexity, not just for reviewing right now but for all future system-test maintenance. I see new PRs merging with hidden bombs that will cause hard-to-debug flakes: the mere addition of `podman images` to any parallel test will very likely blow up one day. The performance gain, as of this writing, seems to be 30-60s.

You've invested enormous effort into this. I respect that but I need more time to keep looking at this and see if I can justify it.

**Pull request closed without merging**
