### PR TITLE
Fix `podman machine set --rootful` for applehv

### PR DESCRIPTION
**Pull request by jakecorrenti**
Fixes a bug where a user would be unable to change a rootless machine to rootful.

Fixes: #21195

#### Does this PR introduce a user-facing change?

```release-note
Fixes a bug where a user would not be able to change their rootless machine to rootful using `podman machine set --rootful`
```

### CODE REVIEW

**Comment by jakecorrenti** [comment]
@gbraad PTAl

**Comment by ashley-cui** [comment]
LGTM

Any idea why our CI didn't catch this?

**Comment by jakecorrenti** [comment]
No, it's not clear yet to me why this wasn't caught by CI at any point. It definitely should have been

**Comment by mheon** [comment]
LGTM. Restarted a flake.

**Review by gbraad — APPROVED** [review]

**Pull request merged**
