### PR TITLE
Test PR, add a inconsequential period to docs

### PR DESCRIPTION
**Pull request by cevich**
Test PR to see if tide merges regardless of "Total Success" passing status.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
Testing CI misbehavior

**Comment by cevich** [comment]
I just canceled a required Cirrus-CI task.

**Comment by cevich** [comment]
Tide reports "In merge Pool"

**Review by mheon — APPROVED** [review]

**Comment by cevich** [comment]
Ya, everything on [the tide status page](https://prow.ci.openshift.org/pr?query=is%3Apr+repo%3Acontainers%2Fpodman+author%3Acevich+head%3Atest_pr), seems to indicate this PR is about to go in.

Maybe the github-side branch-protection is blocking as a knock-on effect :man_shrugging:

**Pull request merged**
