### PR TITLE
system tests: prevent leading tabs

### PR DESCRIPTION
**Pull request by edsantiago**
Replace existing tab indentations with spaces, and add
a test to CI to prevent new ones from sneaking in.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
```
Checking for leading tabs in system tests
test/system/800-config.bats:65:	is "$output" "Error:.*no such container" "unexpected error from podman wait"
************************************************
ERROR: Found leading tabs in system tests. Use spaces to indent, not tabs.  (contrib/cirrus/prebuild.sh:33 in main())
************************************************
```
This was intentional, as confirmation that the new no-more-tabs check works. It does. Repushed with clean tab-less code.

**Review by Luap99 — COMMENTED** [review]
Yes, please
LGTM!

**Comment by Luap99** [comment]
If we do not want to blow up CI on main, we should properly check other PRs for tabs before we merge this.

**Comment by edsantiago** [comment]
Well, #17386 is the obvious one. If that one merges first, I will rebase mine. But I do hope Dan fixes the whitespace issues before that merges.

 I have no automated way to check in-flight PRs, so if worst comes to worst, it'll have to be fixed in the affected PRs.

**Review by vrothberg — COMMENTED** [review]
/lgtm

Farewell my beloved tabs...

**Pull request merged**
