### PR TITLE
[CI:DOCS] fix default branch links

### PR DESCRIPTION
**Pull request by eriksjolund**
* Replace https://github.com/containers/podman/blob/master
  with https://github.com/containers/podman/blob/main
  to match the new default branch "main". Previously
  the default branch was "master". The substitutions were
  made in the documentation but not the code.

Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by eriksjolund** [comment]
A clarification regarding _The substitutions were made in the documentation but not the code._
One of the edititions was in the file
_contrib/snapcraft/snap/snapcraft.yaml_ 
It was in a comment so I guess it could be described as documentation.

**Comment by rhatdan** [comment]
Thanks @eriksjolund 
/lgtm
/approve

**Pull request merged**
