### PR TITLE
Vendor in containers/image v5.13.1

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @mtrmac Something is very wrong with containers/image as far as Podman is concerned?

**Comment by rhatdan** [comment]
[+0174s] Running: /var/tmp/go/src/github.com/containers/podman/bin/podman --root /tmp/crio --runroot /tmp/crio-run --runtime crun --conmon /usr/bin/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp --events-backend file --storage-driver vfs save -o /tmp/volume-plugin-test-img-latest.tar quay.io/libpod/volume-plugin-test-img:latest
[+0174s] Getting image source signatures
[+0174s] Error: error creating LayerInfosForCopy of image "829026c38bd5a9a33d401c278247c86d5a03e7e6e8e7e172abb884886dcf4c48": used only 2 out of 5 physical layers
[+0174s]

**Comment by vrothberg** [comment]
Sigh. Maybe the early-commit + empty-layer thing again, @mtrmac?

**Comment by vrothberg** [comment]
I may not find time today to look into this. I need to create slides (and a recording) for a presentation on Monday.

**Comment by vrothberg** [comment]
> I may not find time today to look into this. I need to create slides (and a recording) for a presentation on Monday.

Looking into it now.

**Comment by vrothberg** [comment]
Before:
```
image (main) $ podman image tree quay.io/libpod/volume-plugin-test-img                         
Image ID: 829026c38bd5                                                                         
Tags:     [quay.io/libpod/volume-plugin-test-img:latest]                                       
Size:     15.54MB                                                                              
Image Layers                                                                                   
├── ID: 50644c29ef5a Size: 5.845MB                                                             
└── ID: c286ec61ea46 Size: 9.689MB Top Layer of: [quay.io/libpod/volume-plugin-test-img:latest]
```

After:
```
image (main) $ ~/containers/podman/bin/podman image tree quay.io/libpod/volume-plugin-test-img  
Image ID: 829026c38bd5                                                                          
Tags:     [quay.io/libpod/volume-plugin-test-img:latest]                                        
Size:     15.54MB                                                                               
Image Layers                                                                                    
├── ID: 50644c29ef5a Size: 5.845MB                                                              
├── ID: 0b33c3bcf13d Size: 1.024kB                                                              
├── ID: 8ed04084efa0 Size: 9.689MB                                                              
├── ID: f488dbff7b86 Size: 1.024kB                                                              
└── ID: 8a2d4c593daa Size: 1.024kB Top Layer of: [quay.io/libpod/volume-plugin-test-img:latest] 
```

Looks like https://github.com/containers/image/commit/db5fb6ee19daca1e6cb349882cd3a3cacb8da066 was not enough.

**Comment by vrothberg** [comment]
I see the bug now. Ouch, I'll open a PR in c/image in a jiffy.

**Comment by vrothberg** [comment]
https://github.com/containers/image/pull/1262

**Pull request closed without merging**
