### PR TITLE
vendor containers/common@main

### PR DESCRIPTION
**Pull request by vikas-goel**
commit hash 383a7e38444613a572bec0c8937743611a26b92e

[NO TESTS NEEDED]

Signed-off-by: Vikas Goel <vikas.goel@gmail.com>

### CODE REVIEW

**Comment by vikas-goel** [comment]
Hi @vrothberg ,

I noticed that IgnorePlatform variable was removed from containers/common. However, it is being referred in containers/buildah and containers/podman repos. When I am trying to vendor containers/common into containers/podman, the build is failing due to the missing variable.

How can this be fixed?

**Comment by vrothberg** [comment]
Thanks for the ping.

https://github.com/containers/podman/pull/10848 is taking care of doing the changes.  Currently we are blocked since we first need to update the images used in CI.  Once https://github.com/containers/podman/pull/10848 is merged, you can update this PR.

**Comment by vrothberg** [comment]
Closing in favor of https://github.com/containers/podman/pull/10965.

**Pull request closed without merging**
