### PR TITLE
Use request context instead of background context

### PR DESCRIPTION
**Pull request by matejvasek**
This fixes a goroutine leak.
Previously if a request was cancelled the image pulling goroutine kept running regardless.

Signed-off-by: Matej Vasek <mvasek@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Please update the commit message to describe what the problem is and what the solution.  It's very hard to match the code changes to the intention.

**Comment by matejvasek** [comment]
@vrothberg better now?

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks

**Pull request merged**
