### PR TITLE
Add podman volume create -d short option for driver

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
podman volume create -d option now supported.
```

### CODE REVIEW

**Comment by mheon** [comment]
The release note should say `-d` option

**Comment by mheon** [comment]
I don't think the `file` driver actually exists (from the tests). Did you want `local`?

**Comment by baude** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM
/hold

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
