### PR TITLE
[CI:DOCS] Fix test block bypass instructions

### PR DESCRIPTION
**Pull request by SoMuchForSubtlety**
A new string was added in 521c0cb and the old one removed with 2ed31f9

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
I have no idea why the DCO does not like your signature.

**Comment by SoMuchForSubtlety** [comment]
> I have no idea why the DCO does not like your signature.

Maybe because it's not the same as the commit author (`SoMuchForSubtlety <jakob@ahrer.dev>`)?

**Comment by rhatdan** [comment]
Well mine is "Daniel J Walsh <dwalsh@redhat.com>" and I am rhatdan.

@vrothberg Any ideas?

**Comment by rhatdan** [comment]
@edsantiago Do you know what DCO is complaining about?

**Comment by edsantiago** [comment]
```console
$ git log -1
commit 7b365ab73844254d2cb7c0769388f74f86801c70 (HEAD -> pr/14378)
Author: SoMuchForSubtlety <jakob@ahrer.dev>     <<<<<<<<<<<<<<<< SoMuchForSubtlety does not match your human name
Date:   2022-05-26 05:47:16 -0600
 ```
Edit `~/.gitconfig` to have:
```
[user]
    name = Jakob Ahrer
```
and try `git commit --amend`. (I don't think `commit --amend` will do it, but it's worth a shot. I leave the rest to you.)

**Comment by SoMuchForSubtlety** [comment]
`git commit --amend --no-edit --author="Jakob Ahrer <jakob@ahrer.dev>"` did the trick.

The DCO app description[^1] seems to be wrong.

> It requires all commit messages to contain the Signed-off-by line with an **email address** that matches the commit author.

[^1]: https://github.com/apps/dco

**Comment by rhatdan** [comment]
/approve
/lgtm
Thanks @SoMuchForSubtlety

**Pull request merged**
