### PR TITLE
WIP: Test c/common errors wrap PR

### PR DESCRIPTION
**Pull request by saschagrunert**
Testing vendored code from https://github.com/containers/common/pull/1077

### CODE REVIEW

**Comment by Luap99** [comment]
Looks like there is an actual bug:
```
# # podman-remote --url unix:/tmp/podman_tmp_iOxu run --name ignore-me --name my-container quay.io/libpod/testimage:20220615 true
         # Error: error preparing container 44d2fe141087e7dd6cb40123e55c96b42fa5823c82edd0adddc45d2b2ed0631b for attach: install profile containers-default-0.49.0-dev: generate default profile into pipe: execute compiled profile: %!w(<nil>)
```

**Comment by saschagrunert** [comment]
Thanks, updated the PR with a new c/common revision.

**Comment by saschagrunert** [comment]
Found another bug, fixing with the next push.

**Comment by saschagrunert** [comment]
Mostly green now, giving it another test with latest buildah and c/storage.

screenshot

**Pull request closed without merging**
