### PR TITLE
system test image: bump to 20220615

### PR DESCRIPTION
**Pull request by edsantiago**
Changes:
 - use --timestamp option to produce 'created' stamps
   that can be reliably tested in the image-history test

 - podman now supports manifest & multiarch run, so we
   no longer need buildah

 - bump up base alpine & busybox images

This turned out to be WAY more complicated than it should've been,
because:

 - alpine 3.14 fixed 'date -Iseconds' to include a colon in
   the TZ offset ("-07:00", was "-0700"). This is now consistent
   with GNU date's --iso-8601 format, yay, so we can eliminate
   a minor workaround.

 - with --timestamp, all ADDed files are set to that timestamp,
   including the custom-reference-timestamp file that many tests
   rely on. So we need to split the build into two steps. But:

 - ...with a two-step build I need to use --squash-all, not --squash, but:

 - ... (deep sigh) --squash-all doesn't work with --timestamp (#14536)
   so we need to alter existing tests to deal with new image layers.

 - And, long and sordid story relating to --rootfs. TL;DR that option
   only worked by a miracle relating to something special in one
   specific test image; it doesn't work with any other images. Fix
   seems to be complicated, so we're bypassing with a FIXME (#14505).

And, unrelated:

 - remove obsolete skip and workaround in run-basic test (dating
   back to varlink days)
 - add a pause-image cleanup to avoid icky red warnings in logs

Fixes: #14456

Signed-off-by: Ed Santiago <santiago@redhat.com>

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM but it looks like the `podman run --tz` test needs to be updated as well.

**Comment by edsantiago** [comment]
>LGTM but it looks like the podman run --tz test needs to be updated as well.

This (like everything else in this PR) was much more complicated than I had expected. TL;DR my two-stage build solved this, but that broke the `image tree` test. I fixed `image tree` by adding `--squash-all`, but didn't rerun the entire test suite and didn't notice that the TZ test had broken (because `--squash-all` + `--timestamp` apparently clobbers timestamps that it shouldn't; I will look into this later). I've rebuilt the testimage with one `--squash-all` and one `--squash`, and TZ and tree tests now pass on my system, and we will now see what other surprises lurk.

That may have been the longest TL;DR I've ever written. Sorry.

**Comment by edsantiago** [comment]
Okay, looks like I really need to look into this `squash-all` situation.

**Comment by edsantiago** [comment]
Filed #14536

**Comment by edsantiago** [comment]
@containers/podman-maintainers this is ready. As a reminder, it was supposed to be a five-minute fix for test failures seen by the multiarch team.

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
