### PR TITLE
DO NOT MERGE: Tests for https://github.com/containers/storage/pull/1607

### PR DESCRIPTION
**Pull request by mtrmac**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mtrmac** [comment]
This does show failures; this PR now includes #18636, so that one of the failures is correctly reported.

**Comment by edsantiago** [comment]
@mtrmac I cherry-picked this onto #17831 on Friday, and have been rerunning CI as often as I can .... and the failure has not triggered :-(

**Comment by mtrmac** [comment]
Seeing consistent failures:
```
[+0026s] not ok 10 network - restart
[+0026s] # (from function `die' in file test/upgrade/../system/helpers.bash, line 565,
[+0026s] #  from function `run_podman' in file test/upgrade/../system/helpers.bash, line 246,
[+0026s] #  in test file test/upgrade/test-upgrade.bats, line 285)
[+0026s] #   `run_podman stop -t0 myrunningcontainer' failed
[+0026s] # [15:07:53.359508914] # podman network disconnect mynetwork myrunningcontainer
[+0026s] # [15:07:53.618602155] # podman stop -t0 myrunningcontainer
[+0026s] # [15:07:53.785161546] Error: unmounting container 200d6108a677d05cff46ffe6249bd9158c41b3591724e1c1cd095fb3769196f9 storage: cleaning up container 200d6108a677d05cff46ffe6249bd9158c41b3591724e1c1cd095fb3769196f9 storage: unmounting container 200d6108a677d05cff46ffe6249bd9158c41b3591724e1c1cd095fb3769196f9 root filesystem: unmounting "/tmp/pu.wZkoM7/root/overlay/e38a5889292f9972b40b5d96a6427fdf168dc46389dd57ed8c33e66072ae2c06/merged": invalid argument
[+0026s] # [15:07:53.791386689] [ rc=125 (** EXPECTED 0 **) ]
```
Uh, ??

… so adding more logging to see how we got there.

**Comment by mtrmac** [comment]
The c/storage PR was merged (regardless of test failures here…)

**Pull request closed without merging**
