### PR TITLE
oci: terminate all container processes on cleanup

### PR DESCRIPTION
**Pull request by giuseppe**
if the container has no pid namespace, they are not killed when the container process ends.  In this case, attempt to kill them in the same way.

The problem was noticed with toolbox where the exec'ed sessions are not terminated when the container is stopped, blocking the system shutdown.

[NO NEW TESTS NEEDED]

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
When a container that runs with --pid=host is terminated, Podman sends a SIGKILL to all the active exec sessions
```

### CODE REVIEW

**Comment by giuseppe** [comment]
@mheon PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
This will clean --pid=host iff Podman is still running, I guess podman cleanup will also clean them up when conmon exits,

**Comment by giuseppe** [comment]
> This will clean --pid=host iff Podman is still running, I guess podman cleanup will also clean them up when conmon exits,

this is used with "podman container cleanup"

**Comment by mheon** [comment]
Why make this party of cleanup? I would’ve hooked it into the stop() logic
so we always clean exec sessions to avoid leaks.

Otherwise LGTM

**Comment by rhatdan** [comment]
It would also need to be in podman kill and if a random process on the system like systemd comes in and kills conmon.
/lgtm

**Comment by debarshiray** [comment]
Thanks for the fix, @giuseppe !

**Pull request merged**
