### PR TITLE
Add BuilderIdentityAnnotation to identify buildah version

### PR DESCRIPTION
**Pull request by rhatdan**
Record the version of buildah used to build the image as a label
in the image.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Does this resolve an issue?

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by rhatdan** [comment]
Resolves a buildah issue https://github.com/containers/podman/pull/7229

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
Though, I suspect you just broke a number of our tests that check image labels

**Comment by debarshiray** [comment]
> Resolves a buildah issue #7229

#7229 is this pull request. Maybe you meant https://github.com/containers/buildah/issues/1864.

**Comment by rhatdan** [comment]
Closing this as it will be fixed in buildah Vendoring.

**Pull request closed without merging**
