### PR TITLE
Use socat while dial-stdio is not in VM image

### PR DESCRIPTION
**Pull request by matejvasek**
The `podman` version in VM doesn't contain patch with dial-stdio yet.
To workaround we can use `socat`.

Once `podman` containing dial-stdio is in VM image we can revert this.

### CODE REVIEW

**Comment by rhatdan** [comment]
I think I would rather just add the podman containing dial-stdio to the next podman 3.4.3 release, then add something that needs to be removed.  Since this is a hidden feature, I don't see this as a big change.

**Comment by rhatdan** [comment]
@mheon WDYT?

**Comment by mheon** [comment]
I don't think we can, we're feature-frozen as of now and this is definitely a new feature.

**Comment by rhatdan** [comment]
Then let's cut a new release with just this feature, for the MAC. 3.5.

**Comment by rhatdan** [comment]
@matejvasek are you still working on this?

**Comment by matejvasek** [comment]
@rhatdan let me check current VM img, it may or may not be required anymore.

**Comment by matejvasek** [comment]
@rhatdan it looks like the dial-stdio (#11819) still hasn't been merged, so this addition might be worthwhile.

**Comment by afbjorklund** [comment]
It wasn't going to be added until 3.5, and VM has 3.4.2

There also is the issue of host keys (with Docker), so the workaround is tunneling the Unix socket... Also fixes those API clients that don't support `ssh://`

**Comment by afbjorklund** [comment]
I think `unix://` tunneling is needed, the docker `ssh://` support is not up to par.

Also it seemed like temporary hack, and one that was avoided intentionally by docker.

**Comment by matejvasek** [comment]
I wonder why [#11819 ](https://github.com/containers/podman/pull/11819) was added to podman 4.X and not packported to 3.X.
It wasn't breaking any compatibility was it?

**Comment by mheon** [comment]
It's a new feature (new command), and we generally don't backport features

**Comment by afbjorklund** [comment]
It was going to be in podman 3.5, but I don't think it was important enough ?

**Pull request closed without merging**
