### PR TITLE
system tests: fix a system test in proxy environment

### PR DESCRIPTION
**Pull request by sstosh**
When we are using a proxy, 'podman build - basic test' will be failed on remote.
This test needs to add the '--http-proxy' option.

Signed-off-by: Toshiki Sonoda <sonoda.toshiki@fujitsu.com>

<details>
<summary>’podman build - basic test’ is failed</summary>

```
not ok 1 podman build - basic test
# (from function `die' in file helpers.bash, line 595,
#  from function `run_podman' in file helpers.bash, line 215,
#  in test file 070-build.bats, line 23)
#   `PODMAN_TIMEOUT=240 run_podman build -t build_test --format=docker $tmpdir' failed
# # /usr/local/bin/podman-remote rm -t 0 --all --force --ignore
# # /usr/local/bin/podman-remote ps --all --external --format {{.ID}} {{.Names}}
# 7f1e2c9cfe17 testimage-working-container
# # /usr/local/bin/podman-remote rm -f 7f1e2c9cfe17
# 7f1e2c9cfe17
# # /usr/local/bin/podman-remote images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
# quay.io/libpod/testimage:20221018 f5a99120db64
# # /usr/local/bin/podman-remote build -t build_test --format=docker /tmp/podman_bats.Le4P60/build-test
# STEP 1/3: FROM quay.io/libpod/testimage:20221018
# STEP 2/3: RUN apk add nginx
# fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
# ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: DNS lookup error
# WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
# fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
# ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: DNS lookup error
# WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory
# ERROR: unable to select packages:
#   nginx (no such package):
#     required by: world[nginx]
# Error: building at STEP "RUN apk add nginx": while running runtime: exit status 1
# [ rc=1 (** EXPECTED 0 **) ]
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #| FAIL: exit code is 1; expected 0
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# # /usr/local/bin/podman-remote rm -t 0 -a -f
# # /usr/local/bin/podman-remote rmi -f build_test
# # /usr/local/bin/podman-remote image prune -f
# # [teardown]
# # /usr/local/bin/podman-remote pod rm -t 0 --all --force --ignore
# # /usr/local/bin/podman-remote rm -t 0 --all --force --ignore
# # /usr/local/bin/podman-remote network prune --force
# # /usr/local/bin/podman-remote volume rm -a -f
```
</details>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

@edsantiago PTAL

**Comment by rhatdan** [comment]
LGTM
But will wait for @edsantiago

**Comment by edsantiago** [comment]
I don't know anything about proxy environments, so I can't really review. What I'm curious about is why #15639, which also dealt with proxies, used `--http-proxy=false` but this PR uses just `--http-proxy`, which AIUI defaults to true anyway?

OOTO today and completely unreachable from this point on.

**Comment by sstosh** [comment]
#15639 is the problem about the internal container-to-container networking.
This case doesn't need name resolution (--http-proxy=false).
On the other hand, this system test is the problem about the external networking.
This case needs name resolution (--http-proxy=true).

**Comment by sstosh** [comment]
It is possible that this problem is due to a bug.
As shown below, `podman build` is successed.

<details>
<summary>Containerfile</summary>

```
# cat /root/test/Containerfile
FROM quay.io/libpod/testimage:20220615
RUN apk add nginx
```
</details>

<details>
<summary>podman build (Successed)</summary>

```
# podman build -t test /root/test
STEP 1/2: FROM quay.io/libpod/testimage:20220615
STEP 2/2: RUN apk add nginx
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/2) Installing pcre (8.45-r2)
(2/2) Installing nginx (1.22.1-r0)
Executing nginx-1.22.1-r0.pre-install
Executing nginx-1.22.1-r0.post-install
Executing busybox-1.35.0-r13.trigger
OK: 7 MiB in 17 packages
COMMIT test
--> dca0ed3d162
Successfully tagged localhost/test:latest
dca0ed3d162bba6d66194383c985b89434689a620aed736837f20a273d5e714f
```
</details>

<details>
<summary>podman build --http-proxy=false (Failed)</summary>

```
# podman build -t test --http-proxy=false /root/test
STEP 1/2: FROM quay.io/libpod/testimage:20220615
STEP 2/2: RUN apk add nginx
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: DNS lookup error
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: DNS lookup error
(1/2) Installing pcre (8.45-r2)
(2/2) Installing nginx (1.22.0-r0)
ERROR: pcre-8.45-r2: DNS lookup error
ERROR: nginx-1.22.0-r0: DNS lookup error
2 errors; 6 MiB in 15 packages
Error: building at STEP "RUN apk add nginx": while running runtime: exit status 2
```
</details>

However, `podman-remote build` is failed.
I think `podman-remote build` should be successed.

<details>
<summary>podman-remote build (Failed)</summary>

```
# podman-remote build -t test /root/test
STEP 1/2: FROM quay.io/libpod/testimage:20220615
STEP 2/2: RUN apk add nginx
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: DNS lookup error
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: DNS lookup error
(1/2) Installing pcre (8.45-r2)
(2/2) Installing nginx (1.22.0-r0)
ERROR: pcre-8.45-r2: DNS lookup error
ERROR: nginx-1.22.0-r0: DNS lookup error
2 errors; 6 MiB in 15 packages
Error: building at STEP "RUN apk add nginx": while running runtime: exit status 2
```
</details>

<details>
<summary>podman-remote build --http-proxy=true (Successed)</summary>

```
# podman-remote build -t test /root/test
STEP 1/2: FROM quay.io/libpod/testimage:20220615
STEP 2/2: RUN apk add nginx
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: DNS lookup error
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: DNS lookup error
(1/2) Installing pcre (8.45-r2)
(2/2) Installing nginx (1.22.0-r0)
ERROR: pcre-8.45-r2: DNS lookup error
ERROR: nginx-1.22.0-r0: DNS lookup error
2 errors; 6 MiB in 15 packages
Error: building at STEP "RUN apk add nginx": while running runtime: exit status 2
```
</details>

If this problem is a bug, I'll open a issue and fix it.

**Comment by edsantiago** [comment]
@containers/podman-maintainers PTAL, this isn't something I can test or confirm or even look at.

**Comment by vrothberg** [comment]
@flouthoc, time to have a look?

**Review by flouthoc — APPROVED** [review]
I have never used `proxy` in remote setup with podman build before. I can try to setup a proxy and test this somewhere in nextweek.

 But overall since our CI is not using `proxy` anyways and if this flag makes tests happy in @sstosh 's setup I see no issues in getting this PR in.

**Comment by edsantiago** [comment]
/hold

There's some miscommunication going on here. Maybe it's on my end but we need to get it straightened out before this merges.

Based on @sstosh's last comment, I believe the problem is that **podman-remote is not defaulting to --http-proxy**. @sstosh, is that correct? If so, the solution is, as @sstosh indicated, to fix the bug. Merging this PR is the wrong thing to do.

Please correct me if I'm wrong.

**Comment by Luap99** [comment]
@edsantiago I think you are right. But it doesn't look like something we support for remote in general? For podman create/run http-proxy is hidden, https://github.com/containers/podman/blob/388b9500ad64793968c00a0ee0dba8ba189dbfd2/cmd/podman/common/create.go#L576

And see
https://github.com/containers/podman/blob/388b9500ad64793968c00a0ee0dba8ba189dbfd2/cmd/podman/images/build.go#L171-L181

**Comment by edsantiago** [comment]
I am so far out of my element here that I may just be talking nonsense... but I'm going to try anyway. My concern here is for end-user experience, so that's what I'll focus on.

* Scenario 1: podman-remote on my Linux desktop, with server in a datacenter in (somewhere far away). Sending my local proxy settings is probably anti-helpful.
* Scenario 2: podman-remote on my Linux desktop, server also on my Linux desktop.
* Scenario 3: podman-remote on Windows/Mac, server on a Linux VM: I think it makes sense here for podman-remote client to send proxy settings, because the VM is on the same Windows/Mac machine and using the same network?

Given that, and given the increasing popularity of Windows/Mac, I wonder if we could have a code path on Windows/Mac podman-remote that would explicitly pass through proxy settings?

Once again, I don't use Windows nor Macs nor proxies and really have no idea if what I'm saying makes sense. I'm just neurotic about making end-user experience a positive one.

**Comment by sstosh** [comment]
@edsantiago  Yes, I think it is correct.
But, I don't know what is the best solution...

**Comment by rhatdan** [comment]
I believe the PROXY should be on the server side.
On MAC and WINDOWS, the podman machine should be setting those environment variables into the system and the `podman service` should be using them if they are set.

**Comment by TomSweeneyRedHat** [comment]
@n1hility or @mheon thoughts on what should be going on with the proxy settings?  See @edsantiago 's earlier comments.

**Comment by n1hility** [comment]
> Given that, and given the increasing popularity of Windows/Mac, I wonder if we could have a code path on Windows/Mac podman-remote that would explicitly pass through proxy settings?

There’s already support for this for Mac and Windows: ´podman machine start´ looks for the common proxy env settings (http_proxy etc) and mirrors them in the guest so they are picked up by the service

**Comment by edsantiago** [comment]
It sounds like Macs and Windows are taken care of. This addition seems harmless in system-test context, so

/lgtm

**Pull request merged**
