### PR TITLE
podman-image-scp: Load images without the use of a temporary file.

### LINKED ISSUE #21239: podman image scp fails due to ENOSPC on the remote server below /tmp without any error msg
### Issue Description

Copy over an existing image from a RH server to a remote SuSE SLES server with

`podman image scp c87c80c0911a srap57::`

fails without any error message when on the remote host is not enough space below `/tmp`.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman system connection add srap57 ssh://apitzm@srap57dxr1.dev.xxxxxx.org`
2. `podman image scp c87c80c0911a srap57::`
`Copying blob d5c1a9d0b1e5 done`
`Copying blob 6859de28489f done`
`Copying blob 35fb3b1b2123 done`
`...`
`Writing manifest to image destination`
(shell prompt returned)

### Describe the results you received

The above command does not end with something like
`...`
`Loaded image:`
`sha256:9211bbaa0dbd68fed073065eb9f0a6ed00a75090a9235eca2554c62d1e75c58f`

### Describe the results you expected

I expected a message about the loaded image.

### podman info output

```yaml
source host:

Red Hat Enterprise Linux 8.9
podman version
Client:       Podman Engine
Version:      4.6.1
API Version:  4.6.1
Go Version:   go1.20.6
Built:        Mon Oct  9 18:15:55 2023
OS/Arch:      linux/amd64

destination host

SUSE Linux Enterprise Server 15 SP5
podman version
Client:       Podman Engine
Version:      4.7.2
API Version:  4.7.2
Go Version:   go1.21.4
Built:        Wed Nov  1 13:00:00 2023
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

image is around 6.1 GByte and on the destination host space below `/tmp` (where the `sftp-server` stores the temp. data):
```
df -kh /tmp
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/vg_root-lv_root   27G   19G  8.2G  70% /tmp
```

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by gordonmessmer**
This PR fixes #21239 

This change requires changes to the containers-common repo, and I will send that PR shortly.  To support CI, those changes are included in a separate commit which I will remove before this PR is merged.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by gordonmessmer** [comment]
I've opened https://github.com/containers/common/pull/1831 for the ssh library changes that this PR requires.

**Comment by rhatdan** [comment]
@cdoern PTAL

**Comment by cdoern** [comment]
@gordonmessmer can you squash into one commit?

**Review by cdoern — APPROVED** [review]
looks good once you squash into one commit. I think this is a requirement for this repo. I do wonder if there is a limit to the stdin size `podman image load` can read. If not, then this is a good solution.

**Comment by gordonmessmer** [comment]
I can squash if that's the right thing to do, but I notice that some of the CI builds fail and the error suggests that those builds aren't using the files in vendor/github.com/containers/common/pkg/ssh from my PR.  

I'm not sure where that workflow is defined... Is it replacing those files with http://github.com/containers/common/pkg/ssh ?  My PR against that repo seems like it's acceptable, but the CI builds there are also failing for unclear reasons (the unmodified "main" branch doesn't pass, and the error doesn't seem to be related to my changes.)

If you want these squashed, and can merge them despite the CI failures, just say so and I'll squash them.  Otherwise, I'll wait on getting things sorted out in the containers/common repo.

**Comment by rhatdan** [comment]
No the changes to common have to be merged their first and then we can vendor them into this PR. Keeping the PR for the common/vendor separate from the podman changes is correct.

**Comment by gordonmessmer** [comment]
I'll remove 9232edca218e043fa52568930f54166a660ea3d9 later today, now that the supporting changes have been merged in containers/common.  Does the main branch require work to import those changes, before we can test this one in CI?

**Comment by gordonmessmer** [comment]
Manual tests of this change are successful.  I've dropped the commit that modified vendor/ (which didn't work anyway), and rebased to the current main branch.

**Comment by rhatdan** [comment]
Did you forget to add a file to your PR?

**Comment by gordonmessmer** [comment]
You said that you needed to "vendor them into this PR" after the supporting changes were merged into https://github.com/containers/common/

**Comment by gordonmessmer** [comment]
Just to check that I understand the process for this PR: I think that this PR is waiting on a release of containers-common v 0.58, at some point in the future.  Once that's released, it can be vendored in to the podman main branch.  And after that, this PR can be rebased, and tests should pass.

Does that sound right?

**Comment by rhatdan** [comment]
No the vendoring should have already happened, you do not need to wait for a release.  Should rebase now and then re-push.  If the latest code has not been vendored from common yet, then we can vendor it in now.

**Comment by gordonmessmer** [comment]
OK, rebased.  "Build for fedora-39" completes successfully, and I can locally build podman without patching the vendor dir.

**Comment by rhatdan** [comment]
Thanks @gordonmessmer 
/lgtm
/approve

**Comment by gordonmessmer** [comment]
Thanks, @rhatdan (and everyone who helped review both PRs.)

**Pull request merged**
