### PR TITLE
podman events: fix error race

### LINKED ISSUE #23165: podman events --since="nonsense" is nondeterministic
It will sometimes succeed!
```console
$ t0=$SECONDS;i=0;while :;do i=$((i+1));bin/podman events --since="the dawn of time...ish" && break;done;printf "%d seconds, %d tries\n" $((SECONDS-$t0)) $i
...
Error: failed to parse event filters: unable to convert since time of the dawn of time...ish: unable to interpret time value
74 seconds, 3674 tries
```
And sometimes that will continue looping forever (or five minutes, which is ~equivalent). I have no idea what makes it "succeed". And, given a loop exit, no idea what to do to investigate.

### PR DESCRIPTION
**Pull request by Luap99**
The events code makes use of two channels, one for the events and one for the resulting error. Then in the main file we have a loop reading from both channels that should exit on first error it gets.

However in case the event channel is closed before the error channel cotains the error it could caused an early exit as it looked like all events were done. Commit c46884aa93 fixed that somewhat by checking for an error in the error channel before exiting. This however was still racy as it added a default case in the select which means the channel check is non blocking. Thus the error was not yet send into the channel.

To fix this we should make it a blocking read to wait for the error in the channel. Also the err != nil check can be removed as we either return err or nil anyway.

And as last step make sure the error channel is closed, that prevents us from blocking forever in case the main select already processed the nil error.

Fixes #23165

#### Does this PR introduce a user-facing change?

```release-note
Fix a rare race where podman events was unable to report an error.
```

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago PTAL

**Review by edsantiago — APPROVED** [review]
This is way above my ability to review: my brain has never figured out Go channels.

The obvious question of course is: are there any other places in the code base where this pattern is used? Is there any way to check?

Nice work finding this one.

**Comment by edsantiago** [comment]
My `while` loop has run for almost two hours without triggering. I call this good. LGTM!

**Comment by Luap99** [comment]
> My while loop has run for almost two hours without triggering. I call this good. LGTM!

I also ran it for over an hour before I stopped it.

**Comment by mheon** [comment]
LGTM

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
