### PR TITLE
[CI:DOCS] correct numbering typo

### PR DESCRIPTION
**Pull request by rhatdan**
Based on PR from @sethjones.

Replaces: https://github.com/containers/podman/pull/8222

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
The CI/CD System is boloxed.  Forcing merge.

**Comment by rhatdan** [comment]
@cevich CI/CD is not in a good state.

**Comment by edsantiago** [comment]
Cirrus error, in big red block, is:
```
Failed to start: Invalid value for field 'resource.machineType': 'https://www.googleapis.com/compute/v1/projects/libpod-218412/zones/us-central1-a/machineTypes/'. The URL is malformed.
```
Grepping in my workdir, I find some instances of `machineType` but only in logs, never (AFAICT) in any source files. It always looks like the above URL, except the above is missing `/custom-something-something` at the end. 

What I find most intriguing is that, in my logs, the `machineType` line in json comes right after one called `labelFingerprint` ... and the last podman PR is #8337 which touched `.cirrus.yml` in something called `fingerprint_script`. Could just be coincidence, but I wonder if it's worth backing out #8337? I expect that PR would have to be force-merged as well and I don't know how to do that.

**Pull request merged**
