### PR TITLE
Migrate machine configs

### PR DESCRIPTION
**Pull request by baude**
If podman detects a Machinev1 config, it will automatically migrate it
to the new format.

Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
@containers/podman-maintainers ptal and merge.  it fixes a current breakage issue in main.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
