### PR TITLE
Fixci

### PR DESCRIPTION
**Pull request by baude**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
but thought @vrothberg had a PR for this earlier?

**Comment by mheon** [comment]
LGTM once this goes green. 
On the assumption it does:
/lgtm
/hold

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by vrothberg** [comment]
> but thought @vrothberg had a PR for this earlier?

I am closing mine :) I asked for someone to take over since my workday was about to end.

**Pull request merged**
