### PR TITLE
Switch to containers/common for seccomp

### PR DESCRIPTION
**Pull request by saschagrunert**
The seccomp/containers-golang library is not maintained any more and we
should stick to containers/common.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by baude** [comment]
i dont understand this PR and what it is doing ... why do we need to add the seccomp.json to podman?  It should be provided by a more common package.  Again, this was just a glance, and i might be missing something very obvious.

**Comment by saschagrunert** [comment]
> i dont understand this PR and what it is doing ... why do we need to add the seccomp.json to podman? It should be provided by a more common package. Again, this was just a glance, and i might be missing something very obvious.

Nono, I just removed the `github.com/seccomp/containers-golang` dependency in favor of a bumped containers/common, because we moved all the source code from seccomp/containers-golang to containers/common. It should not change any behavior at all.

**Pull request merged**
