### PR TITLE
Change error message for compatibility with docker

### PR DESCRIPTION
**Pull request by mscherer**
Fixes #12315

Signed-off-by: Michael Scherer <misc@redhat.com>

[ NO NEW TESTS NEEDED ]

### CODE REVIEW

**Comment by Luap99** [comment]
I do not think this is the right approach. `utils.Error()` is used for all error in the API. We should not change this. This will also  impact the libpod api. To fix this only the compat api has to return the correct error struct. I assume this will affect all docker compat endpoints not just this one.

**Comment by mscherer** [comment]
Indeed. So I tested that PR, and it seems to fix my initial problem. Not sure if that fix all instance of the same issue.

**Comment by mscherer** [comment]
(when I say "test that PR", I mean, the latest iteration, where the error is wrapped, and only for the compat API, sorry if that's not clear)

**Comment by rhatdan** [comment]
@Luap99 @mheon @jwhonce utils.Error currently takes in an APIMessage and then does nothing with it.  Should we change the API to drop this or should we wrap the error message with the API Message?

**Comment by jwhonce** [comment]
@rhatdan The initial implementation had `Cause` as the error.Error() text while `Message` was a human readable message for presentation. That got lost over time. Now we have `Cause` == error.Cause().Error() and `Message` == error.Error(). I am okay with removing the parameter `apiMessage` as it is meaningless and unused at this time.

**Comment by rhatdan** [comment]
@jwhonce Are you ok with merging this PR?

**Pull request merged**
