### PR TITLE
[CI:DOCS] Fix spacing on --userns options in docs

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/podman/issues/11483

**Comment by zhangguanzhang** [comment]
LGTM

**Review by zhangguanzhang — APPROVED** [review]

**Comment by flouthoc** [comment]
LGTM

**Review by saschagrunert — APPROVED** [review]

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
