### PR TITLE
Remove changelog.txt from the repository

### PR DESCRIPTION
**Pull request by jesperpedersen**
as it isn't been kept in sync with release tags, especially on main.

The release notes will be featured in RELEASE_NOTES.md.

Signed-off-by: jesperpedersen <jesper.pedersen@redhat.com>

[NO TESTS NEEDED]

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Controversial, so

/assign mheon
/assign rhatdan

**Comment by mheon** [comment]
I'm fine with this. One less step to do as part of the release process.

/approve

**Comment by mheon** [comment]
Gitvalidation is complaining:

`  - FAIL - commit subject exceeds 90 characters`

**Comment by rhatdan** [comment]
/lgtm
Fine with me.

**Pull request merged**
