### PR TITLE
Container rename bindings

### PR DESCRIPTION
**Pull request by Luap99**
Add bindings and podman-remote support for container rename.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM, thanks @Luap99

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
@Luap99 Looks like this PR stalled/cancelled, can you repush to trigger the CI.

**Comment by Luap99** [comment]
CI is not stalled.
/hold cancel

**Pull request merged**
