### PR TITLE
podman service: close duplicated /dev/null fd

### PR DESCRIPTION
**Pull request by Luap99**
Since we open /dev/null to set it as STDIN we can close it after the dup2() call. Using defer is not good enough since this function will never exit since the http server will block. This is not a problem but it reduces the open fds from the service by one.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@vrothberg @giuseppe @flouthoc @containers/podman-maintainers PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Pull request merged**
