### PR TITLE
vendor test dependencies instead of installing via network

### PR DESCRIPTION
**Pull request by Luap99**
We can vendor the test dependencies such as go-md2man, git-validation
and goimports. This allows us to always install the same version as
specified in go.mod. Also we do not rely on a network connection for
this.

The advantage with this method is that dependabot will also update the
dependencies for us and we do not have to hardcode versions in the
Makefile.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by Luap99** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
I'd prefer to not add (more) test dependencies into main `go.mod`.  Instead, I suggest to declare a sub-module as we do in Buildah: https://github.com/containers/buildah/tree/main/tests/tools

This way, downstream packagers don't have to figure out whether they need to package the new dependencies or not.

**Comment by Luap99** [comment]
We can do this but then we also likely ship many dependencies twice thus bloating the git repo.

**Comment by vrothberg** [comment]
> We can do this but then we also likely ship many dependencies twice thus bloating the git repo.

Thanks! If they're identical, git is good at deduplicating and compressing.

**Comment by Luap99** [comment]
updated to use a submodule

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by Luap99** [comment]
tests are green, @vrothberg @rhatdan please merge

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
