### PR TITLE
[CI:DOCS] Update basic_networking.md

### PR DESCRIPTION
**Pull request by markzhang1996**
Correct a missing link in basic networking tutorial.

#### What this PR does / why we need it:
To correct a missing link in docs/tutorials/basic_networking.md.

#### How to verify it
Just change docs. No need to verify.

#### Which issue(s) this PR fixes:

None

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by umohnani8** [comment]
@markzhang1996 please sign your commit with `git commit --amend -s` so that CI is happy and we can get this in
LGTM

**Comment by markzhang1996** [comment]
> @markzhang1996 please sign your commit with `git commit --amend -s` so that CI is happy and we can get this in LGTM

Sorry, I'm not familiar with signing a commit (I never do it before). I see the commit is verified and signed with GitHub’s verified signature because I edit file and commit on GitHub. Doesn't it mean that the commit is already signed?

**Comment by markzhang1996** [comment]
@umohnani8 It seems like I need a reviewer to type /lgtm in comment?

**Comment by giuseppe** [comment]
> @umohnani8 It seems like I need a reviewer to type `/lgtm` in comment?

first you need sign your commit.

As @umohnani8 pointed out, you need to run `git commit --amend -s` then push again the change.  I don't think you can use the web UI to do it (unless you can modify the commit message and add a "Signed-off-by: $NAME <$EMAIL>" line to it.

**Comment by rhatdan** [comment]
If you did this via the WEB UI, you could just add the following to your commit message

    Signed-off-by:  Mark Zhang <markzhang1994@gmail.com>

If you use git to make this request then, you need to do 

$ git commit -a --amend -s
$ git push --force

**Comment by umohnani8** [comment]
/lgtm
Thanks @markzhang1996!

**Pull request merged**
