### PR TITLE
[CI:DOCS] hierarchical issues with userns parameters

### PR DESCRIPTION
**Pull request by paomian**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by paomian** [comment]
can we add more example? I wrote the parameter as I understood it, but it reported an error.https://github.com/containers/podman/discussions/21552

**Review by lsm5 — CHANGES_REQUESTED** [review]
LGTM, but I'll defer to @edsantiago .

@paomian please squash commits

**Review by edsantiago — APPROVED** [review]
Nice catch, thank you! Approving but with hold because merging is frozen temporarily.

/hold

And, reminder to self: add `host` to the table above.

**Review by edsantiago — CHANGES_REQUESTED** [review]
Okay, merges are open again. Please rebase and please squash your commits. 

If it's not too much trouble, would you mind copy/pasting the `host` line from `options/userns.container.md`? https://github.com/containers/podman/blob/cb1bac73318be05428907435fda5f4ba3a6278bd/docs/source/markdown/options/userns.container.md#L24

**Comment by paomian** [comment]
I have something going on right now.  I'll deal with it later today.

**Comment by paomian** [comment]
@edsantiago Is this okay now?

**Review by lsm5 — APPROVED** [review]

**Comment by lsm5** [comment]
> Okay, merges are open again. Please rebase and please squash your commits.
> 
> If it's not too much trouble, would you mind copy/pasting the `host` line from `options/userns.container.md`?
> 
> https://github.com/containers/podman/blob/cb1bac73318be05428907435fda5f4ba3a6278bd/docs/source/markdown/options/userns.container.md#L24

@edsantiago I'll do a followup PR, let's get this one in.

**Pull request merged**
