### PR TITLE
Bump to v5.2.0-rc1

### PR DESCRIPTION
**Pull request by mheon**
This is off a branch to ensure our automation works, but I do not consider v5.2 branched at this time; we'll merge main back into it at least once more before RC2.

No release notes this time, either, those will wait for RC2.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mheon** [comment]
Because we're merging main back in, we should avoid setting main to v5.3.0-dev until next RC

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

**Comment by edsantiago** [comment]
Well, we discovered an interesting little feature of Cirrus: `changesInclude('version/rawversion/*`)` does not trigger when it's a two-commit NOP PR. I [don't see any way to solve this](https://cirrus-ci.org/guide/writing-tasks/).

**Comment by edsantiago** [comment]
I guess one way to solve it could be to add a step to the release procedures, "make a tiny whitespace or other silly nonsense to version.go"

**Comment by mheon** [comment]
I'm going to push the manual merge button as I accidentally pushed the tag early

**Pull request merged**
