### PR TITLE
fix missing completion in podman run

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Fixes: https://github.com/containers/podman/issues/7668
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @mheon @giuseppe @vrothberg @jwhonce @baude @ashley-cui @QiWang19 PTAL

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
some of the tests are looking reddish....

**Pull request merged**
