### PR TITLE
vendor of containers/(common, storage, image)

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Preparing for release.

**Review by ashley-cui — COMMENTED** [review]
LGTM, but before the RC is cut we probably need released versions of common, storage, image.

**Comment by rhatdan** [comment]
Not before RC, but before final.

**Comment by ashley-cui** [comment]
I think in our release process doc we said that RC's were intended to be fully stable and ready for release, which means we probably want a versioned common, storage, image.  In any case, we can do another dance on the branch when it's cut.

**Comment by rhatdan** [comment]
Sure, the problem with that is it does not allow for bug fixes in any level without requiring a complete vendor dance.  I have no problem doing it, but I don't believe we have dones this in the past.

**Comment by mheon** [comment]
We really need to go over the release doc again and finalize it to have a solid answer here, but the goal was to make RCs more stable - IIRC, so we would be comfortable if one somehow ended up in Fedora Stable.

**Comment by mheon** [comment]
That being said, I have no objections about merging this now and figuring out details later, we have a few days.

**Comment by mheon** [comment]
Adding bloat label

```

* bin/podman grew by 65544 bytes; max allowed is 51200.
*
* Please investigate, and fix if possible.
*
* A repo admin can override by setting the bloat_approved label
```

**Comment by rhatdan** [comment]
I think the bloat is all in the Windows code paths.  But does that affect the size of the linux app or the Mac Client?

**Pull request merged**
