### PR TITLE
Bump CNI to v1.0.1

### LINKED ISSUE #10926: podman network create/rm: please ignore ENOENT
There's a race condition between the time podman reads its CNI directory and the time it tries to read conflist files. Trivial reproducer (requires two shells):
```console
! window 1
$ while :;do bin/podman network create aaa;bin/podman network rm -f aaa;done

! window 2
$ while :;do bin/podman network create bbb;bin/podman network rm -f bbb;done
```
Within less than ten seconds, one or the other will spit out:
```
ERRO[0000] Error loading CNI config list file /home/esm/.config/cni/net.d/xxx.conflist: error reading /home/esm/.config/cni/net.d/xxx.conflist: open /home/esm/.config/cni/net.d/xxx.conflist: no such file or directory
```
...where `xxx` is the name of the other window (e.g. you will see "bbb" in the aaa window and vice-versa).

(Note: even though it says ERRO, it's not an error and does not cause a nonzero exit status).

This is really annoying to me when looking at integration-test logs, because they all show up in bright scary orange that makes me think there's an error (and, in some cases, hides real errors because of the cry-wolf thing).

To normal-people users, this is probably kind of alarming, and would presumably cause them to waste an indeterminate amount of time looking into it.

Easy/obvious solution is to just ignore ENOENT, ¿que no?

### PR DESCRIPTION
**Pull request by Luap99**
Update CNI so we can match wrapped errors. This should silence ENOENT
warnings when trying to read the cni conflist files.

Fixes #10926

Because CNI v1.0.0 contains breaking changes we have to change some
import paths. Also we cannot update the CNI version used for the
conflist files created by `podman network create` because this would
require at least containernetwork-plugins v1.0.1 and a updated dnsname
plugin. Because this will take a while until it lands in most distros
we should not use this version. So keep using v0.4.0 for now.

The update from checkpoint-restore/checkpointctl is also required to
make sure it no longer uses CNI to read the network status.

Signed-off-by: Paul Holzinger <pholzing@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Failure looks unrelated, LGTM

**Comment by Luap99** [comment]
Blocked until https://github.com/checkpoint-restore/checkpointctl/pull/7 merges.

**Comment by Luap99** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
/lgtm
/hold

Feel free to merge when ready.

**Pull request merged**
