### PR TITLE
Support lookup of intermediate ID for uidmapping and gidmapping in `--userns=auto`

### PR DESCRIPTION
**Pull request by kaivol**
In rootless mode, the host IDs in the `uidmapping` and `gidmapping` options of `--userns=auto` are mapped from an intermediate namespace, just like when using the `--uidmap` and `--gidmap` options.
This means that for a given _host ID_, the user first has to look up the _intermediate ID_ manually. 

The `--uidmap` and `--gidmap` options also support prefixing the _host ID_ in the mapping with the `@` symbol, which means that podman will look up the _intermediate ID_ corresponding to the given _host ID_ and it will map the found _intermediate ID_ to the given _container ID_.

This PR adds the functionality mentioned above to the `uidmapping` and `gidmapping` options in `--userns=auto`.

```release-note
`uidmapping` and `gidmapping` options of `--userns=auto` in rootless mode: 
Added the possibility to map actual host IDs (instead of intermediate IDs) by prefixing the host ID 
with the `@` symbol. 
```

### CODE REVIEW

**Comment by giuseppe** [comment]
the build is failing

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
code LGTM, but can we please add a system test?

You can add more tests along the lines of:

```diff
diff --git a/test/system/170-run-userns.bats b/test/system/170-run-userns.bats
index 667648e5f..c4fcac3ed 100644
--- a/test/system/170-run-userns.bats
+++ b/test/system/170-run-userns.bats
@@ -147,3 +147,12 @@ EOF
     is "${output}" "$user" "Container should run as the current user"
     run_podman rmi -f $(pause_image)
 }
+
+@test "podman userns=auto with id mapping" {
+    skip_if_not_rootless
+    run_podman unshare awk '{if(NR == 2){print $2}}' /proc/self/uid_map
+    first_id=$output
+    mapping=1:@$first_id:1
+    run_podman run --rm --userns=auto:uidmapping=$mapping $IMAGE awk '{if($1 == 1){print $2}}' /proc/self/uid_map
+    assert "$output" == 1
+}
```

to run it, you can use the command:

`$ PODMAN=bin/podman bats -f "podman userns=auto with id mapping" test/system/170-run-userns.bats`

**Comment by edsantiago** [comment]
>to run it, you can use the command:
>
>$ PODMAN=bin/podman bats -f "podman userns=auto with id mapping" test/system/170-run-userns.bats

...or, even quicker/safer/better:
```console
$ hack/bats 170:"auto with id mapping"
```
Better for infinite reasons, among them: it runs as root & rootless, and does a lot of invisible setup. Also obviously much more friendly.

**Comment by kaivol** [comment]
Added system test as suggested by @giuseppe. 
I'm not sure if I should add more tests..?

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
/lgtm
Thanks @kaivol

**Comment by edsantiago** [comment]
This broke CI.

**Comment by kaivol** [comment]
Just for my understanding, it was only the test that was erroneous, and that was fixed in #20979, right?

**Comment by edsantiago** [comment]
@kaivol yes, absolutely. You did nothing wrong, and the problem is (I think) now fixed. I spoke hastily this morning because I was rushing to a commitment. I apologize for leaving you in suspense like that.

 Thank you again for your PR and your patience.

**Pull request merged**
