### PR TITLE
Fixes errors from 'manifest push' being dropped in remote case

### LINKED ISSUE #13650: Error from remote 'manifest push' is hidden
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Errors from 'podman manifest push' are silently dropped, no output returned of what went wrong.
This was seen while looking into issue #13629 

**Steps to reproduce the issue:**

1.  podman machine init --cpus 2 -m 8192
2. podman machine start
3. podman machine ssh sudo rpm-ostree install qemu-user-static
4. podman machine ssh sudo systemctl reboot
5. git clone https://github.com/jwmatthews/case_watcher.git
6. cd case_watcher
7. podman build -f Dockerfile --manifest quay.io/jwmatthews/case_watcher:latest --platform linux/amd64,linux/arm64 .
8. podman manifest push quay.io/jwmatthews/case_watcher:latest docker://quay.io/jwmatthews/case_watcher:latest

**Describe the results you received:**
```
$ podman manifest push quay.io/jwmatthews/case_watcher:latest docker://quay.io/jwmatthews/case_watcher:latest

$ echo $?
0

```

**Describe the results you expected:**

```
$ podman manifest push quay.io/jwmatthews/case_watcher:latest docker://quay.io/jwmatthews/case_watcher:latest
Error: invalid image name quay.io/jwmatthews/case_watcher:latest/registry/docker://quay.io/jwmatthews/case_watcher:latest: invalid reference format
$ echo $?
125
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I assume I have something wrong with my workflow, ignoring that detail for now and focusing just on that I hit an error but nothing was printed.  As I debugged I saw we were getting back a 400 response from the remote call, but the status code and the response text were ignored.  

Think we just need to make a 1-line change to:
https://github.com/containers/podman/blob/main/pkg/bindings/manifests/manifests.go#L206

Will follow up with a short PR to potentially address.

**Output of `podman version`:**

```
$ podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.8

Built:      Wed Mar  2 09:04:36 2022
OS/Arch:    darwin/arm64

Server:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.16.14

Built:      Thu Mar  3 09:58:50 2022
OS/Arch:    linux/arm64

```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: arm64
  buildahVersion: 1.24.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 5.15.18-200.fc35.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 7932325888
  memTotal: 8299716608
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.aarch64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 11h 13m 24.76s (Approximately 0.46 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 23
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1646319530
  BuiltTime: Thu Mar  3 09:58:50 2022
  GitCommit: ""
  GoVersion: go1.16.14
  OsArch: linux/arm64
  Version: 4.0.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ brew info podman
podman: stable 4.0.2 (bottled), HEAD

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, compiled latest 'main' branch as of today and confirmed same behavior

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on an Mac - Apple M1Max (arm64)

### PR DESCRIPTION
**Pull request by jwmatthews**
Signed-off-by: John Matthews <jwmatthews@gmail.com>

Fixes #13650

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL
@jwhonce PTAL

**Comment by mheon** [comment]
PR is complaining about a lack of tests. You can add a test, or add `[NO NEW TESTS NEEDED]` somewhere in your commit message

**Comment by jwmatthews** [comment]
@Luap99 ok, I will work on adding a test for this.

I wasn't sure how to execute the tests from mac, but I have them running now on Linux.
Will add a test to this PR.

**Comment by jwmatthews** [comment]
@Luap99 I've updated the commit with a test

**Comment by rhatdan** [comment]
@jwmatthews Needs a rebase.

**Comment by jwmatthews** [comment]
Rebased after #13651 https://github.com/containers/podman/pull/13653 was merged

**Pull request merged**
