### PR TITLE
fix e2e sign tests

### PR DESCRIPTION
**Pull request by vrothberg**
The key used in the tests has expired.  Remove the expiration date to
turn CI happy and green.

Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

@Luap99 @flouthoc PTAL

### CODE REVIEW

**Comment by vrothberg** [comment]
image

sigh ... looks like an infra fart now

**Comment by vrothberg** [comment]
save tests need some love :)

**Review by flouthoc — APPROVED** [review]
LGTM, but some of the CI tests failed with same error I have restarted failing tests just to confirm

**Comment by vrothberg** [comment]
merge me

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Pull request merged**
