### PR TITLE
[CI:DOCS] Fix documentation link and typo

### PR DESCRIPTION
**Pull request by stefanrua**
Signed-off-by: Stefan Rua <stefan.rua@iki.fi>

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @stefanrua 
I am no expert on the syntax but this seems to make sense
LGTM

**Comment by stefanrua** [comment]
I'm not familiar with the syntax either, I just imitated the working links. I hope that someone familiar with it can confirm.

**Comment by TomSweeneyRedHat** [comment]
LGTM
the Underscore turns the listed command into a link to the manpage.

**Comment by TomSweeneyRedHat** [comment]
and TYVM @stefanrua !

**Comment by stefanrua** [comment]
No problem :)

**Pull request merged**
