### PR TITLE
WIP - remote build: fix streaming and error handling

### PR DESCRIPTION
**Pull request by vrothberg**
Address a number of issues in the streaming logic in remote build, most
importantly an error in using buffered channels on the server side.

The pattern below does not guarantee that the channel is entirely read
before the context fires.
```
for {
        select {
                case <- bufferedChannel:
                ...
                case <- ctx.Done():
                ...
        }
}
```
Fixes: #10154
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@edsantiago, it looks like we were masking errors before.  I think this will help but it's hard to reproduce.

**Comment by edsantiago** [comment]
"Hard to reproduce"? Hold my beer. I rebased #9887 on top of this PR and ran it through CI. [It failed](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4760266962370560/html/bud-remote-fedora-34-root-host.log.html). Looks like exactly the same failure pattern, except the error message is now "server probably quit" instead of "stream dropped".

**Comment by vrothberg** [comment]
> "Hard to reproduce"? Hold my beer. I rebased #9887 on top of this PR and ran it through CI. [It failed](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4760266962370560/html/bud-remote-fedora-34-root-host.log.html). Looks like exactly the same failure pattern, except the error message is now "server probably quit" instead of "stream dropped".

Thanks, Ed! I will give it another shot tomorrow.

**Comment by vrothberg** [comment]
@edsantiago one round without flakes. Let's try another time.

I noticed that we need to distinguish between EOF and unexpected EOF.  Not yet sure if that's the key or not.

**Comment by edsantiago** [comment]
Ah, you rebased on my buildah-bud PR, clever. Why do you say "without flakes" though? I see [the same old same old])https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4907054650359808/html/bud-remote-fedora-34-root-host.log.html)

**Comment by vrothberg** [comment]
> Ah, you rebased on my buildah-bud PR, clever. Why do you say "without flakes" though? I see [the same old same old](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4907054650359808/html/bud-remote-fedora-34-root-host.log.html)

I think this one happened in "another time".  First run went fine.  The hunt continues...

**Comment by vrothberg** [comment]
Ed will cherry-pick my commit here into his PR, so I am closing.

**Pull request closed without merging**
