### PR TITLE
Quadlet test - Split between success, warning and error cases

### PR DESCRIPTION
**Pull request by ygalblum**
Split the table to three based on the expected outcome
Use helper functions to reduce the amount of parameter required in each entry

#### Does this PR introduce a user-facing change?
No

```release-note
None
```

### CODE REVIEW

**Comment by ygalblum** [comment]
@Luap99 PTAL

**Review by Luap99 — APPROVED** [review]
LGTM, this looks much cleaner

**Comment by ygalblum** [comment]
@Luap99 sorry for the mess with #23427. I've rebased this PR on top of the new main and will soon open another PR to support all unit files

**Comment by ygalblum** [comment]
I've opened #23449 as draft on top of this PR. I still need to add tests to it and I will also rebase it on main once this one is merged

**Pull request merged**
