### PR TITLE
e2e networking test: better way to get host IP

### PR DESCRIPTION
**Pull request by edsantiago**
uber/jaeger-client-go library is deprecated. Remove it.

Only place it's used is in one e2e test, a test that is flaking
in a way that suggests that the HostIP() weighting heuristic from
that module was not actually getting the best outgoing IP address.
So, switch to using what seems to be the current best practice.
No need to make it reusable, since it's only used in one place.

Oh, also remove undesired "-dt" from two "podman run"s. In one
it's harmless, in the other it would cause a test failure under
some circumstances.

Closes: #18269   (optimistic, aren't I?)

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Justification: [jaeger is deprecated](https://github.com/jaegertracing/jaeger-client-go#-this-library-is-deprecated).

**Comment by edsantiago** [comment]
Woot! On the very first CI run, on [debian](https://api.cirrus-ci.com/v1/artifact/task/6304821318254592/html/int-podman-debian-12-root-host-boltdb.log.html#t--podman-run-network-bind-to-HostIP--1), the flaky test ran with a `10.128.0` address and passed! Obviously that doesn't mean the flake is fixed (I haven't sifted passing-CI logs for `10.128.0`) but at least it means my PR hasn't caused any major breakage.

**Review by giuseppe — APPROVED** [review]
`+7 −12,712` is impressive

LGTM

**Review by Luap99 — APPROVED** [review]
The flake likely depends on the ordering of interfaces. The real reason why you see the wrong IP is because the podman bridge interfaces are NAT-ed to allow external communication for all containers without complex routing rules. So ncat sees the IP after NAT was applied which is the external ip and not the bridge ip thus the missmatch.

It is trivial to reproduce locally. Just set the outbound-addr to the podman bridge ip.
So yes this patch should definitely fix the flake is it always uses the external ip and not the bridge ip.

I also doubled check that the output-addr is not a NOP in this scenario, without it ncat shows the connection coming from 127.0.0.1 so it definitely tests what it should.

LGTM

**Pull request merged**
