### PR TITLE
Update common and buildah vendor

### PR DESCRIPTION
**Pull request by umohnani8**
Bump up the buildah and common vendors to pick up the move of the libimage/platform code.

This is needed for https://github.com/containers/podman/pull/20050

#### Does this PR introduce a user-facing change?

```release-note
Bump up common and buildah to pick up libimage/platform code move
```

### CODE REVIEW

**Comment by umohnani8** [comment]
Will remove the replace in go.mod once https://github.com/containers/common/pull/1693 and https://github.com/containers/buildah/pull/5085 are merged in.

**Comment by lsm5** [comment]
> Ephemeral COPR build failed. @containers/packit-build please check.

ignore eln

**Comment by umohnani8** [comment]
Tests are green, can I please get a lgtm here @rhatdan @vrothberg @mheon @flouthoc

**Comment by mheon** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
