### PR TITLE
podman build --force-rm defaults to true in code

### PR DESCRIPTION
**Pull request by rhatdan**
The man page and code should match for what is the default settings.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@ millerthegorilla  PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
