### PR TITLE
Remove legacy msitools based msi installer

### PR DESCRIPTION
**Pull request by n1hility**
This was replaced by the setup.exe burn installer several releases ago, and only kept around as a fallback. Remove it since it is no longer maintained and not recommended for use.

[NO NEW TESTS NEEDED]

```release-note
none
```

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM
@mheon @vrothberg @baude @Luap99 PTAL

**Comment by mheon** [comment]
LGTM
FYI @ashley-cui @lsm5

**Review by vrothberg — APPROVED** [review]
LGTM

**Pull request merged**
