### PR TITLE
[CI:DOCS] Clarify uid range requirements

### PR DESCRIPTION
**Pull request by rzlourenco**
See https://github.com/containers/podman/issues/8592

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @rzlourenco But you need to sign your commits.

git commit -a -s --amend
git push --force

LGTM
/approve
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
once signed, thanks for the contribution @rzlourenco !

**Comment by rzlourenco** [comment]
It is signed, I think.

**Pull request merged**
