### PR TITLE
Makefile: do not prefix /etc

### PR DESCRIPTION
**Pull request by vrothberg**
Revert commit 3d0e08f04e9c67dd8136acd54adabd077dbbd633. `/etc/` does not need a prefix and can be customized with the `ETCDIR` env variable.

Fixes: #18250

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by edsantiago** [comment]
@tobwen PTAL, this reverts your PR #10786. I never understood the point of that PR, but if you have a compelling reason for insisting that it remain in place, please speak now.

**Comment by tobwen** [comment]
I will be home in some minutes and will have a look then.

**Comment by edsantiago** [comment]
ping, to let everyone know that @tobwen has responded (but did so via an edit, not a post, so it didn't go to anyone's email). Read above.

Also, I'm waffling a lot on this PR. I believe we need to keep `$PREFIX/etc` because there are an unknown number of users out there, with no root access but permissions to install into `/usr/local`, and for those it would be impossible to install into `/etc`.  But then: will podman read `/usr/local/etc/` on those systems? I don't think so, because this is just `make`, not `./configure && make`, and I see no mechanism for overriding `/etc` in podman itself. So then removing `$PREFIX` is the correct thing to do.

Out of time. This can continue tomorrow.

**Comment by vrothberg** [comment]
>  But then: will podman read /usr/local/etc/ on those systems?

Not consistently, no.  It may work for containers.conf but for this config only.  But the `docker.in` is sensitive to it.

Since commit 1edada477dbd we no longer install `87-podman-bridge.conflist`, so we can scratch that off the list.  I don't think anything is installed to /etc anymore.

With respect to `docker.in`: Wouldn't `PREFIX=/foo ETCDIR=/foo/etc make ...` get the desired behavior?  I wonder whether this path needs to configurable at all.  Which brings me to the next question: Do we still need a configurable /etc?

**Comment by Luap99** [comment]
Whenever we need a customizable ETCDIR should not be the discussion here. The binaries never respected it anyway. The original problem as @vrothberg points out is fixed we no longer install anything into /etc so this change should not cause problems.

**Comment by vrothberg** [comment]
> Whenever we need a customizable ETCDIR should not be the discussion here. The binaries never respected it anyway. 

I am not that sure.  The behavior of `docker.in` is sensitive to this setting.

> The binaries never respected it anyway. 

Podman did to some degree. `containers.conf` is the only one AFAICS.

I am not advertising for doing it but I also don't want this conversation to be shot down too quickly.

**Comment by Luap99** [comment]
I am not saying we shouldn't have this discussion, but this PR is not the place to have it IMO.
We caused a regression this fixes it. The `docker.in` is the only file using ETCDIR so I see no problem with this patch.
The alternative would be to revert the docker.in change which is IMO much worse.
 

> Podman did to some degree. containers.conf is the only one AFAICS.

containers.conf is defined in c/common. The podman build command sets `X github.com/containers/podman/v4/libpod/config._etcDir=/usr/local/etc` which does not exist. So I do not see how any config file ever used this path. Maybe the libpod.conf, this was before my time?

**Comment by vrothberg** [comment]
@rhatdan PTAL

**Comment by vrothberg** [comment]
So, can we merge?

**Comment by Luap99** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
