### PR TITLE
WIP: Cirrus: Add Ubuntu to rootless integration testing

### LINKED ISSUE #9508: RFC: CI rootless ubuntu tests
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Is there a reason why rootless is only tested on fedora? I think it would help to also test rootless ubuntu when working on PRs like #9423 for example.

### PR DESCRIPTION
**Pull request by cevich**
Fixes #9508

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
I like more tests.

**Comment by cevich** [comment]
> Sadly test are breaking.

That's a matter of perspective; One *could* say the tests have freshly uncovered previously hidden problems :grin: 

* [int podman ubuntu-2004 rootless host](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6259580062662656/html/int-podman-ubuntu-2004-rootless-host.log.html)
* [int podman ubuntu-2010 rootless host](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5133680155820032/html/int-podman-ubuntu-2010-rootless-host.log.html)

Let's see what we got going on here...

**Comment by cevich** [comment]
...okay, these appear like fairly clear problems:

* For Ubuntu 20.10 (crun), [only one test failed with a pretty clear error](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5133680155820032/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-play-kube-allows-setting-resource-limits--2): `error starting container a7a...6c2: the requested cgroup controller `cpu` is not available: OCI runtime error`.  Assuming that means some thing like "The kernel is too old", maybe this is a test we can simply skip on Ubuntu 20.10?
* For Ubuntu 20.04 (runc), [all the errors are capability related](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6259580062662656/html/int-podman-ubuntu-2004-rootless-host.log.html#t--podman-network-prune--2), so again perhaps a "kernel is too old" issue.  @rhatdan what do we do in case of `Error: OCI runtime error: container_linux.go:367: starting container process caused: unknown capability "CAP_PERFMON"`?

**Comment by Luap99** [comment]
The `Error: OCI runtime error: container_linux.go:367: starting container process caused: unknown capability "CAP_PERFMON"` error only happens in network tests. I completely rework rootless networking in #9423. Maybe it will work with the new networking logic. I added this commit to my PR lets see if it will work there.

**Comment by cevich** [comment]
@Luap99 thanks!  I also have two PRs to update the VM images, both are stuck waiting for an updated `crun`, which could (maybe) have some bearing here, esp. on the first (Ubuntu 20.10) problem.

**Comment by Luap99** [comment]
Ubuntu 20.04 works with myPR https://github.com/containers/podman/pull/9423/checks?check_run_id=2238965171.

**Comment by edsantiago** [comment]
New map: cirrus-map-pr9905

**Comment by cevich** [comment]
@Luap99 excellent news, does it also pass standalone and/or do you want me to rebase this?

@giuseppe or @rhatdan any ideas on the `error starting container a7a...6c2: the requested cgroup controller 'cpu' is not available: OCI runtime error`?

**Comment by Luap99** [comment]
@cevich I think the fix for the cpu cgroup controller failure is just to skip the test, see:
https://github.com/containers/podman/blob/5798102679cc6e7def72c33f1a6ec0782ff195ee/test/e2e/play_kube_test.go#L1830-L1833
However the `SkipIfUnprivilegedCPULimits` only skips when rootless on fedora
https://github.com/containers/podman/blob/5798102679cc6e7def72c33f1a6ec0782ff195ee/test/e2e/common_test.go#L608-L613

So I guess we have to add ubuntu 20.10 there as well.

**Comment by cevich** [comment]
> So I guess we have to add ubuntu 20.10 there as well.

Ahh perfect.  @giuseppe or @rhatdan un-ping, and sorry for the noise.  Let's see if we can just remove `&& info.Distribution == "fedora"`...

**Comment by cevich** [comment]
Rebased onto #9423 then again onto master.

**Comment by cevich** [comment]
Rebased on master

**Comment by cevich** [comment]
Rebased on master

**Comment by cevich** [comment]
Blocked by https://github.com/containers/podman/issues/9997

**Comment by cevich** [comment]
Rebased on master

**Pull request closed without merging**
