### PR TITLE
[CI:DOCS] troubleshooting: mention overlay option for --rootfs

### PR DESCRIPTION
**Pull request by eriksjolund**
* Mention overlay option for --rootfs. Overlay description text
  is from commit 020d81f113ea1e11398ea77495cc4b8e05a91d38
  by Qi Wang

Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

### CODE REVIEW

**Comment by flouthoc** [comment]
@eriksjolund Should this be in troubleshooting ? I remember adding it in man pages here: https://github.com/containers/podman/pull/11170

**Comment by eriksjolund** [comment]
@flouthoc The text in the troubleshooting guide was already mentioning "overlay file system":
```
Another option would be to create an overlay file system on the directory as a lower and then
then allow podman to create the files on the upper.
```
I thought it would be better to replace that sentence with the something that mentioned `:O`

**Comment by flouthoc** [comment]
> @flouthoc The text in the troubleshooting guide was already mentioning "overlay file system":
> 
> ```
> Another option would be to create an overlay file system on the directory as a lower and then
> then allow podman to create the files on the upper.
> ```
> 
> I thought it would be better to replace that sentence with the something that mentioned `:O`

@eriksjolund Oh i see. Yes I think it would be good. Thanks for editing.

**Review by flouthoc — APPROVED** [review]

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
