### PR TITLE
Journald log driver test

### PR DESCRIPTION
**Pull request by Luap99**
Test that the journald log driver writes to journald and
that we can read it with journalctl.

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago PTAL

**Comment by edsantiago** [comment]
LGTM. I was concerned that we might run CI on non-systemd hosts, but it looks like we're OK in that respect. Thanks for the PR.

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Pull request merged**
