### PR TITLE
Vendor in containers/common v0.46.0

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/11745

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by zhangguanzhang** [comment]
maybe need NO-TEST-NEEDED title?

**Review by aniruddhabagal — APPROVED** [review]

**Comment by vrothberg** [comment]
@rhatdan the error changes broke test/system/330-corrupt-images.bats.  We need to adjust the check there.

**Comment by vrothberg** [comment]
I'm taking over to speed things up.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/11753

> @rhatdan the error changes broke test/system/330-corrupt-images.bats. We need to adjust the check there.

It was actually the load error, fixed  now.

**Pull request closed without merging**
