### PR TITLE
Add PodName to ContainerConfig to be exposed in inspect

### LINKED ISSUE #15374: Add labels on containers that are started within pods
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

When I create podman pods, I have very few information in the container directly that this container is part of a pod
Inspecting the pod (not using compat mode) I've a single field (but no name as well)
```
"Pod": "140e94e830b192325d4f6778f2a59de255611f8cd776efd9728af9066e1f7e5d",
```
but then I need to go to list of pods, etc

**What I would like:**

1. Add some annotations with `Labels` on the container

2. Then when displaying info of a container (even using compat mode) I will clearly see that this container is part of a pod and the pod name will be part of the Label

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by boaz0**
closes #15374 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Please add a test to inspect for it,

**Review by vrothberg — COMMENTED** [review]
I am not exactly sure which parts of https://github.com/containers/podman/issues/15374 this PR addresses.  Podman/libpod inspect already include the Pod ID.

I'd expected a PR that adds the Pod ID as a label for the compat endpoint.  @mheon WDYT?

**Comment by boaz0** [comment]
@vrothberg I probably misunderstood. I thought `PodName` was supposed to be added to the container metadata.

**Comment by Luap99** [comment]
> I'd expected a PR that adds the Pod ID as a label for the compat endpoint. @mheon WDYT?

This sounds problematic. Labels should only be set by external users/tools.
Docker-compose and ansible and possible more tools would think that the container was changed and will try to recreate it because the labels no longer match their expected ones.

**Comment by boaz0** [comment]
@Luap99 @vrothberg what about adding `PodName` to annotations?

**Comment by vrothberg** [comment]
> @Luap99 @vrothberg what about adding `PodName` to annotations?

I do not object adding that to annotations but I think we need to agree on what problem we want to solve.

**Comment by boaz0** [comment]
How about displaying annotations in `/containers/{name}/json`? This information is shown when we do `inspect <container-name>`. 
It will be available both on `compat` and `podman inspect` and won't interfere `Ansible`/`DockerCompose`/etc.

@vrothberg

**Comment by vrothberg** [comment]
Yes, the Docker API does not know annotations.  I think there's nothing we can do.  I am not against adding a the PodName but it does not really address the initial problem.

**Comment by mheon** [comment]
Why do we care about the Docker-compat endpoint, again? Is there a reason the Desktop folks aren't using the Libpod endpoints, which expose a lot more of the Podman-specific bits?

**Comment by rhatdan** [comment]
@mheon @boaz0 @vrothberg what should we do with this PR?

**Comment by vrothberg** [comment]
I think we can close it.  The original issue isn't needed anymore.

**Pull request closed without merging**
