### PR TITLE
Change podman.service.in to only log at notice level and above

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
Podman.service will no longer log debug messages into the journal.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
```
man systemd.exec
...
       LogLevelMax=
           Configures filtering by log level of log messages generated by this
           unit. Takes a syslog log level, one of emerg (lowest log level,
           only highest priority messages), alert, crit, err, warning, notice,
           info, debug (highest log level, also lowest priority messages). See
           syslog(3) for details. By default no filtering is applied (i.e. the
           default maximum log level is debug). Use this option to configure
           the logging system to drop log messages of a specific service above
           the specified level. For example, set LogLevelMax=info in order to
           turn off debug logging of a particularly chatty unit. Note that the
           configured level is applied to any log messages written by any of
           the processes belonging to this unit, as well as any log messages
           written by the system manager process (PID 1) in reference to this
           unit, sent via any supported logging protocol. The filtering is
           applied early in the logging pipeline, before any kind of further
           processing is done. Moreover, messages which pass through this
           filter successfully might still be dropped by filters applied at a
           later stage in the logging subsystem. For example, MaxLevelStore=
           configured in journald.conf(5) might prohibit messages of higher
           log levels to be stored on disk, even though the per-unit
           LogLevelMax= permitted it to be processed.
```

**Comment by martinpitt** [comment]
This completely breaks cockpit-podman, looks like podman.service does not send any events any more? AFAIUI, these events are synthesized based on journal watching. Quick theory: these are logged at level "info"?

The description also isn't consistent; The unit sets `LOGGING="--log-level=info`, so it doesn't appear that podman.service logs *debug* level messages by default anyway?

**Comment by Luap99** [comment]
> This completely breaks cockpit-podman, looks like podman.service does not send any events any more? AFAIUI, these events are synthesized based on journal watching. Quick theory: these are logged at level "info"?

Yes correct

@rhatdan What are your trying to fix here exactly? There should not be any debug messages logged by default only info.

**Review by Luap99 — CHANGES_REQUESTED** [review]
This breaks event logging

**Comment by rhatdan** [comment]
There is a big discussion on over logging by Podman in RHEL AI.  I thought this might be the culprit.

Closing.

**Comment by rhatdan** [comment]
Specifically on Systemd logging starting and stopping of containers.  We could drop this down to info, but it the RHEL AI issue might be unrelated.

**Pull request closed without merging**
