### PR TITLE
Swap out json-iterator for golang default

### LINKED ISSUE #8366: Bug: podman network inspect wrong ident
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.
```
$  podman network inspect podman
[
     {
          "cniVersion": "0.4.0",
          "name": "podman",
          "plugins": [
     {
          "bridge": "cni-podman0",
          "hairpinMode": true,
          "ipMasq": true,
          "ipam": {
     "ranges": [
     [
          {
               "gateway": "10.88.0.1",
               "subnet": "10.88.0.0/16"
          }
     ]
],
     "routes": [
     {
          "dst": "0.0.0.0/0"
     }
],
     "type": "host-local"
},
          "isGateway": true,
          "type": "bridge"
     },
     {
          "capabilities": {
     "portMappings": true
},
          "type": "portmap"
     },
     {
          "type": "firewall"
     },
     {
          "type": "tuning"
     }
]
     }
]

```
2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
the master code to compile
```

### PR DESCRIPTION
**Pull request by jwhonce**
json-iterator library failed to pretty print json for all inspection
types.

Fixes #8366

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
jhonce, I assume it's too late to request tests. Can you offer me suggestions on how I can confirm this, including the erroneous behavior prior to this fix?

**Comment by jwhonce** [comment]
@edsantiago I didn't add tests as they would be brittle. Previous behavior the output was randomly indented, now each embedded stanza is indented as expected. Easy visual check, very hard to do programmatically as any new field or stanza in output would could change indentation.

**Comment by mheon** [comment]
LGTM but I'll defer merge until the tests discussion is settled

**Pull request merged**
