### PR TITLE
docs: clarify systemd cgroup mount

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/containers/podman/issues/20521

[CI:DOCS]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by adelton** [comment]
As noted in https://github.com/containers/podman/issues/20521, there is also a read-only / read-write difference, that should be noted as well.

**Comment by giuseppe** [comment]
> As noted in #20521, there is also a read-only / read-write difference, that should be captured in the docs as well.

thanks.  Fixed now

**Review by Luap99 — APPROVED** [review]
LGTM

**Pull request merged**
