### PR TITLE
vendor: update c/common + libhvee to latest main and use pkg/strongunits from c/common

### PR DESCRIPTION
**Pull request by Luap99**
The code has been moved to c/common so it can be shared with libhvee.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

**Comment by mheon** [comment]
TYTY, been so busy I haven't been able to work with this.

**Comment by mheon** [comment]
Both Buildah tests failed, same test. Doesn't look like a network flake.

**Comment by Luap99** [comment]
@nalind PTAL I think you changed the manifest code in c/common.

**Comment by nalind** [comment]
> @nalind PTAL I think you changed the manifest code in c/common.

Indeed, this is fixed by https://github.com/containers/common/pull/1844.

**Pull request merged**
