### PR TITLE
 Improve container filenname ambiguity.

### PR DESCRIPTION
**Pull request by wLMEB**
Fixes: #23039

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by wLMEB** [comment]
Initially opened this fix with https://github.com/containers/podman/pull/23188 
which I've closed in favor of this PR. Please review this PR.

**Comment by mheon** [comment]
LGTM. @nalind @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
/lgtm
Thanks @wLMEB

**Pull request merged**
