### PR TITLE
rootless: avoid zombie process on first launch

### PR DESCRIPTION
**Pull request by giuseppe**
avoid a zombie process if on the first launch Podman creates a long
living process, such as "podman system service -t 0".

The `r` variable was overriden thus causing the waitpid to fail and
not clean up the intermediate process.

Closes: https://github.com/containers/podman/issues/10575

[NO TESTS NEEDED]

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM, thank you @giuseppe !

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
/lgtm
/hold
Don't know what is going on with the CI system.

**Comment by PavelSosin-320** [comment]
@giuseppe Hopefully, PR 10575 will calm the following issue:
 
_systemd[133]: Starting PodmanAPI Service for Rootless users...
podman[279]: 2021-08-03 08:19:42.6111998 +0300 IDT m=+0.180908901 system refresh
systemd[133]: podman.service: Got notification message from PID 279, but reception only permitt>_
that appears when rootless user starts podman using systemd unit as "Notify" type service:
[Service]
Type=notify
...
Indeed, the main process is Main PID: 269 (podman), So systemd doesn't expect any other notifications.

**Pull request merged**
