### PR TITLE
Cirrus: use dnf instead of rpm to install packages

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### Does this PR introduce a user-facing change?

```release-note
None
```

@cevich PTAL

### CODE REVIEW

**Review by cevich — APPROVED** [review]
/lgtm
/hold

**Comment by lsm5** [comment]
@cevich skipped the `pod resource limit` test on aarch64. Flakes a lot. PTAL once again.

**Comment by lsm5** [comment]
machine test passed on x86_64, so looks like the `s/rpm/dnf/g` actually helps

**Pull request merged**
