### PR TITLE
[CI:DOCS] fix indentation for userns modes

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/containers/podman/issues/11364

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
@giuseppe, could you repush?  The deadlock is hitting us again.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by eriksjolund** [comment]
The auto options could also be indented to make it clear that they only belong to the auto keyword:

https://github.com/eriksjolund/podman/blob/fix_userns_doc/docs/source/markdown/podman-run.1.md#--usernsmode

**Comment by eriksjolund** [comment]
Aha, I think the layout change was aiming to remove the outer bullet list (but forgot __keep-id__, __ns__ and __host__)

https://github.com/eriksjolund/podman/blob/fix_userns_doc_adjust_keep-id_ns_private/docs/source/markdown/podman-run.1.md#--usernsmode

My preference would be a two-level bullet list:

https://github.com/eriksjolund/podman/blob/fix_userns_doc/docs/source/markdown/podman-run.1.md#--usernsmode

or alternatively to lift out the inner bullet list (i.e. the auto options) and put it as a separate section after the section that lists all --userns options.

Something like this:
https://github.com/eriksjolund/podman/blob/fix_userns_doc_move_auto_option_documentation/docs/source/markdown/podman-run.1.md#--usernsmode

**Comment by rhatdan** [comment]
Test failures, have nothing to do with this PR. Forcing merge.

**Pull request merged**
