### PR TITLE
podman manifest add: support creating artifact manifest on the fly

### PR DESCRIPTION
**Pull request by nalind**
Add a `--artifact` flag to `podman manifest add` which can be used to create an artifact manifest for one or more files and attach it to a manifest list.  Corresponding `--artifact-type`, `--artifact-config-type`, `--artifact-config`, `--artifact-layer-type`, `--artifact-subject`, and `--artifact-exclude-titles` flags can be used to fine-tune the fields in the artifact manifest that don't refer to the files themselves.

Add `--index` and `--subject` flags to `podman manifest annotate` that will cause values passed to the `--annotation` flag to be applied to the manifest list as a whole instead of to an entry in the list, and which will add a reference to the manifest for the `--subject` argument.

Add a `--annotation` flag to `podman manifest create` that will cause annotations to be added to the new image index, which has the side-effect of forcing its format to be OCI from the start.

#### Does this PR introduce a user-facing change?

```release-note
`podman manifest add` now supports `--artifact` and related flags which will create an artifact manifest for one or more files and add them to the specified manifest list.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
[0002-Add-man-page-content-for-artifacts.patch](https://github.com/containers/podman/files/14301118/0002-Add-man-page-content-for-artifacts.patch.txt)

**Comment by mheon** [comment]
Code LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons on this 5.0 PR.

**Comment by nalind** [comment]
Reduced the number of flag combinations, added `--artifact-config` to the flags tested, and added a cleanup of the test-specific registry to the "manifest list --add --artifact" test.

**Comment by TomSweeneyRedHat** [comment]
@nalind now you have red tests kicking up their heels.

**Comment by nalind** [comment]
Give it a minute.  Also needs a "/approve" from someone listed as an approver in the OWNERS file.

**Pull request merged**
