### PR TITLE
test: enable test_wait_next_exit

### PR DESCRIPTION
**Pull request by matejvasek**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Seems like it is still broken in CI.

**Comment by vrothberg** [comment]
@matejvasek did you find time to analyze what's up?

**Comment by matejvasek** [comment]
@rhatdan @vrothberg the test runs on `fedora-37` I would expect that it has `container-selinux v2.193.0+`.

**Comment by matejvasek** [comment]
It has `container-selinux-2.201.0-1.fc37-noarch` so I have no idea why this is failing.

**Comment by matejvasek** [comment]
Before the error was different:
**OLD ERROR:**
```
dfbd.scope - libcrun container.
Mar 28 21:41:13 bellatrix audit[16005]: AVC avc:  denied  { read write } for  pid=16005 comm="systemd-journal" path=2F6465762F73686D2F6A6F75726E616C2E585858585833373730313431383132202864656C6574656429 dev="tmpfs" ino=459577 scontext=system_u:system_r:syslogd_t:s0 tcontext=unconfined_u:object_r:container_runtime_tmpfs_t:s0 tclass=file permissive=0
Mar 28 21:41:13 bellatrix audit[16005]: SYSCALL arch=c000003e syscall=47 success=yes exit=0 a0=5 a1=7ffdcca48de0 a2=40000040 a3=7ffdccb67080 items=0 ppid=1 pid=16005 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-journal" exe="/usr/lib/systemd/systemd-journald" subj=system_u:system_r:syslogd_t:s0 key=(null)
Mar 28 21:41:13 bellatrix audit: SOCKADDR saddr=0100003934356431
Mar 28 21:41:13 bellatrix audit: PROCTITLE proctitle="/usr/lib/systemd/systemd-journald"
Mar 28 21:41:13 bellatrix systemd-journald[16005]: Got message with truncated control data (too many fds sent?), ignoring.
Mar 28 21:41:13 bellatrix audit[16005]: AVC avc:  denied  { read write } for  pid=16005 comm="systemd-journal" path=2F6465762F73686D2F6A6F75726E616C2E585858585833373833353031303335202864656C6574656429 dev="tmpfs" ino=459578 scontext=system_u:system_r:syslogd_t:s0 tcontext=unconfined_u:object_r:container_runtime_tmpfs_t:s0 tclass=file permissive=0
Mar 28 21:41:13 bellatrix audit[16005]: SYSCALL arch=c000003e syscall=47 success=yes exit=0 a0=5 a1=7ffdcca48de0 a2=40000040 a3=7ffdccb67080 items=0 ppid=1 pid=16005 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-journal" exe="/usr/lib/systemd/systemd-journald" subj=system_u:system_r:syslogd_t:s0 key=(null)
Mar 28 21:41:13 bellatrix audit: SOCKADDR saddr=0100003934356431
Mar 28 21:41:13 bellatrix audit: PROCTITLE proctitle="/usr/lib/systemd/systemd-journald"
Mar 28 21:41:13 bellatrix systemd-journald[16005]: Got message with truncated control data (too many fds sent?), ignoring.
Mar 28 21:41:13 bellatrix audit[16005]: AVC avc:  denied  { read write } for  pid=16005 comm="systemd-journal" path=2F6465762F73686D2F6A6F75726E616C2E585858585832353039323238323333202864656C6574656429 dev="tmpfs" ino=459579 scontext=system_u:system_r:syslogd_t:s0 tcontext=unconfined_u:object_r:container_runtime_tmpfs_t:s0 tclass=file permissive=0
Mar 28 21:41:13 bellatrix systemd-journald[16005]: Got message with truncated control data (too many fds sent?), ignoring.
Mar 28 21:41:13 bellatrix audit[16005]: SYSCALL arch=c000003e syscall=47 success=yes exit=0 a0=5 a1=7ffdcca48de0 a2=40000040 a3=7ffdccb67080 items=0 ppid=1 pid=16005 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-journal" exe="/usr/lib/systemd/systemd-journald" subj=system_u:system_r:syslogd_t:s0 key=(null)
```

**Comment by matejvasek** [comment]
@rhatdan  Maybe some other global SELinux policies changed?

**Comment by matejvasek** [comment]
cc @edsantiago

**Comment by edsantiago** [comment]
Whoosh. Way over my head, sorry.

**Comment by rhatdan** [comment]
Can you get this to fail outside of the CI/CD system?

**Comment by rhatdan** [comment]
What do I need to do to test this locally?

**Comment by matejvasek** [comment]
@rhatdan 
```sh
# in podman project
python3 -m venv venv
source ./venv/bin/activate
pip3 install -r test/python/requirements.txt
export PODMAN=/path/to/podman
python -m unittest test.python.docker.compat.test_containers.TestContainers.test_wait_next_exit
```

**Comment by matejvasek** [comment]
Sometimes the testing podman service hangs:
```
subprocess.CalledProcessError: Command 'podman system service' returned non-zero exit status 125.
```
in such a case kill it manually.

**Comment by matejvasek** [comment]
@rhatdan or just run a container with an image with 200k long labels an look into syslog.

**Comment by matejvasek** [comment]
@rhatdan try this:
`podman run --rm quay.io/mvasek/long-label:latest` and then check `journalctl -f`.

**Comment by matejvasek** [comment]
@rhatdan I don't know if it helps but: the AVC denied error happens when `len(labels)` around 104k-105k characters. For instance 100k label does work all right.

**Comment by matejvasek** [comment]
Before https://github.com/containers/container-selinux/pull/196 the limit was just few 10k IIRC.

**Comment by matejvasek** [comment]
The good news for me is the image we use has labels just very little bit above 100k so it working for my use-case.
Still I with there were some reserve hence the test uses 250k labels.

**Comment by rhatdan** [comment]
I really have no idea what is going on here.

**Comment by matejvasek** [comment]
Something more from investigation:

Larges message that can be sent to log is `212940` bytes.

What is most likely happening:
* Try send log entry by `ssize_t send(int sockfd, const void *buf, size_t len, int flags)`, if succeeded we are done.
* If the above fails due to `EMSGSIZE` try `ssize_t sendmsg(int sockfd, const struct msghdr *msg, int flags)`,
the `msghdr` struct contains contains file-descriptor to temp file created by `podman` in `/dev/shm`.
The call succeeds, however `systemd-journald` cannot access the temp file and it gets AVC.

The SELinux labels of the temp file `unconfined_u:object_r:container_runtime_tmpfs_t:s0`.
The SELinux labels of the `systemd-journald` daemon `system_u:system_r:syslogd_t:s0`.

**Comment by matejvasek** [comment]
@rhatdan @edsantiago I added some new findings above.

**Comment by matejvasek** [comment]
simple reproducer:
```go
var err error
msgLen := 212_940 + 1
data := make([]byte, msgLen)
for i := range data {
	data[i] = '0'
}
err = journal.Send(string(data[:msgLen]), journal.PriInfo, nil)
if err != nil {
	t.Fatal(err)
}
```
don't forget to set `chcon` on the testing binary.

**Comment by edsantiago** [comment]
There's a new CI VM build in progress, expected for next week maybe. [f37 includes container-selinux-209](https://cirrus-ci.com/task/5590987553112064?logs=main#L117) but unfortunately [f36 does not](https://cirrus-ci.com/task/6716887459954688?logs=main#L97)

**Comment by matejvasek** [comment]
The `Docker-py Compat.` test runs on F37, support for F36 ends mid May so I think it's fine.

**Comment by edsantiago** [comment]
@matejvasek re-pushing isn't going to do any good if you don't rebase. The magic you need is in `.cirrus.yml` and was merged in #18124.

**Comment by matejvasek** [comment]
@rhatdan @edsantiago Thanks. It should be all right now.

**Comment by edsantiago** [comment]
I think [this is the test in question?](https://cirrus-ci.com/task/6335531097784320). It passed (all tests pass), and shows `container-selinux-2.209` present, so I guess this is good to go?

/approve

@rhatdan PTAL.

**Comment by rhatdan** [comment]
/lgtm
Thanks @matejvasek

**Pull request merged**
