### PR TITLE
Update VM images

### PR DESCRIPTION
**Pull request by Luap99**
from https://github.com/containers/automation_images/pull/396

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
Checkpoint/restore is completely broken on rawhide: https://bugzilla.redhat.com/show_bug.cgi?id=2328985
So I guess we have to skip all checkpoint tests here for this to pass CI.

**Comment by lsm5** [comment]
> Checkpoint/restore is completely broken on rawhide: https://bugzilla.redhat.com/show_bug.cgi?id=2328985 So I guess we have to skip all checkpoint tests here for this to pass CI.

can we either skip all checkpoint tests on rawhide or maybe defer rawhide image update?

**Comment by Luap99** [comment]
Ok finally all rawhide regressions are fixed and tests are green.

@giuseppe @lsm5 PTAL and merge

**Pull request merged**
