### PR TITLE
[v4.1.1-rhel] fix e2e sign tests

### PR DESCRIPTION
**Pull request by vrothberg**
The key used in the tests has expired.  Remove the expiration date to
turn CI happy and green.

Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```
@containers/podman-maintainers PTAL

### CODE REVIEW

**Comment by vrothberg** [comment]
*sigh* these and others will fail since the k8s pause image is now signed via cosign.

Need to add commit 6ddccd94f69d to the backports.

**Comment by vrothberg** [comment]
Ready to go in

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve
/hold cancel

**Pull request merged**
