### PR TITLE
Warn on failing to update container status

### PR DESCRIPTION
**Pull request by mheon**
failed to send a signal to the container's PID1, but ignored the results of that update. That's generally bad practice, since even
if we can't directly take action on an error, we should still make an effort to report it for debugging purposes. I used Infof instead of something more serious to avoid duplicate reporting to the user if something has gone seriously wrong.

[NO TESTS NEEDED] this is just adding additional error reporting.

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon [NO NEW TESTS NEEDED] is required now.

**Comment by mheon** [comment]
Ark. Repushing.

**Comment by flouthoc** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]

**Comment by rhatdan** [comment]
Force pushing.

**Pull request merged**
