### PR TITLE
Add support for 'podman system service' on FreeBSD

### PR DESCRIPTION
**Pull request by dfr**
This adds the 'system service' command to the build and includes small refactors to enable the build and conform to local conventions for unix domain socket paths.

#### Does this PR introduce a user-facing change?

```release-note
Add support for the podman remote API on FreeBSD.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL
@vrothberg @giuseppe @Luap99 @mheon PTAL

**Comment by mheon** [comment]
Sure, seems fine.
/lgtm

**Comment by dfr** [comment]
I see this PR is tagged for 4.6 - does that mean it will be automatically merged to the v4.6 branch or should I make a cherry-pick PR?

**Comment by dfr** [comment]
I realised after trying this that @ashley-cui had already merged it in #19072

**Pull request merged**
