### PR TITLE
Add completion for --init-ctr

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
--init-ctr completions now work.
```
[NO NEW TESTS NEEDED] Since I don't know how to test completions.

### CODE REVIEW

**Comment by rhatdan** [comment]
@Luap99 Is there any way to test completions?

**Comment by Luap99** [comment]
> @Luap99 Is there any way to test completions?

Depends, we test argument completion in test/system/600-completion.bats but this is only for things like image or container names that we know exist. We also test that all options and commands have a completion function set in cmd/podman/shell_completion_test.go

We do not test for simple flag values like this PR implements and I don't see a strong reason to do it.

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
