### PR TITLE
Add progress bar for decompress image

### LINKED ISSUE #19240: podman machine image decompression needs a progress bar
### Feature request description

There is a progress bar for the download, but not for the decompression.

```
Downloading VM image: fedora-coreos-38.20230709.2.0-qemu.x86_64.qcow2.xz: done  
Extracting compressed file
```

Even though it might take an equally long time, and could use a progressbar.

### Suggest potential solution

The same progress bar should be used, also for the decompression.

It can be done, by looking at the input stream before it is fed to `unxz`

### Have you considered any alternatives?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by afbjorklund**
#### Does this PR introduce a user-facing change?

```release-note
Show progress bar when decompressing podman machine image
```

Closes #19240

### CODE REVIEW

**Comment by Luap99** [comment]
You need to add `[NO NEW TESTS NEEDED]` to your commit message in order to pass CI, I don't think we can test progress bars.

**Review by vrothberg — APPROVED** [review]
Code LGTM.  Tested it locally and I think it's a very nice improvement. Thanks!

@ashley-cui PTAL

**Comment by afbjorklund** [comment]
> I don't think we can test progress bars.

The way to test would be to have a machine readable output (from machine), with events and progress etc.

Currently it is just random prints, for humans.

**Review by ashley-cui — COMMENTED** [review]
Code and progress bar LGTM, though it looks like it breaks one of our tests - we pass in /dev/null as an imagepath for one of our tests and the progress bar hangs because it's trying to copy 0b/0b.

**Comment by afbjorklund** [comment]
Looks like it is a known issue: (with workaround)

* https://github.com/vbauerster/mpb/issues/7

**Comment by TomSweeneyRedHat** [comment]
LGTM
looks like the Windows test (known issue), is the only hangup here.

**Pull request merged**
