### PR TITLE
Refactor podman image command output

### PR DESCRIPTION
**Pull request by jwhonce**
Leverage new report.Formatter allowing better compatibility from
podman command output.

Follow on PR's will cover containers, etc.

See #10974
Depends on containers/common#831

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@vrothberg PTAL

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by TomSweeneyRedHat** [comment]
All kinds of red test unhappiness @jwhonce

**Pull request merged**
