### PR TITLE
fix restart always with rootlessport

### PR DESCRIPTION
**Pull request by Luap99**
When a container is automatically restarted due its restart policy and
the container uses rootless cni networking with ports forwarded we have
to start a new rootlessport process since it exits with conmon.

remove rootlessport socket to prevent EADDRINUSE

When we restart a container via podman restart or restart policy the
rootlessport process fails with `address already in use` because the
socket file still exists.
This is a regression and was introduced in commit abdedc3.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
This sounds like something we should aim towards RHEL 8.5.0.2
LGTM

**Comment by TomSweeneyRedHat** [comment]
/lgtm
/hold   
Hold for test completion.

**Comment by Luap99** [comment]
The test was not working, should be fixed now.

**Comment by Luap99** [comment]
@edsantiago Can you please look at the system test, I don't understand why it is failing for remote. It passes locally on my laptop.

**Comment by edsantiago** [comment]
This reproduces 100% for me. To run tests using podman-remote:
```console
$ PODMAN=$(pwd)/bin/podman-remote ./hack/bats --root network:restart
```
(assumes you have `podman system service` running as root).

I instrumented the code as follows, and get no useful output:
```diff
index e184bdb1d..548c4ae1c 100644
--- a/test/system/500-networking.bats
+++ b/test/system/500-networking.bats
@@ -490,6 +490,8 @@ load helpers
             sleep 0.5
             retries=$((retries - 1))
             if [[ $retries -eq 0 ]]; then
+                run_podman ps -a
+                run_podman container logs $cid
                 die "Timed out waiting for container to restart"
             fi
         done
```
output:
```
   # /home/esm/src/atomic/2018-02.podman/libpod/bin/podman-remote ps -a
   CONTAINER ID  IMAGE                              COMMAND               CREATED         STATUS                       PORTS                 NAMES
   acd26450d890  quay.io/libpod/testimage:20210610  /bin/busybox-extr...  11 seconds ago  Exited (137) 11 seconds ago  0.0.0.0:5658->80/tcp  myweb
   # /home/esm/src/atomic/2018-02.podman/libpod/bin/podman-remote container logs acd26450d890731370a70ab3a02c1c29af3267d32bdb0db7945e3b2a9cc4fe66
  (nothing)
```
I'm actually surprised that this works at all: I didn't think `-v` worked with `podman-remote`. Maybe this is a test that needs to be skipped.

BTW could you change `podman` to `run_podman` in lines 508-509?

**Comment by Luap99** [comment]
-v works just fine on remote.
I found the issue. The podman container cleanup process fails with `cannot listen on the TCP port: listen tcp4 :5275: bind: address already in use`. This is a race, it fail 9/10 times for me. I guess I was lucky on my first try.

**Comment by Luap99** [comment]
The problem should be fixed now. I set `SO_REUSEPORT` for the ports, so we should not longer run into EADDRINUSE for a rootful container restart.

**Comment by Luap99** [comment]
OK, SO_REUSEPORT didn't work because we no longer prevent another container with the same ports from starting.
I think I understand it now. The podman service keeps the connection open and thus leaking it. Once we got the fd passed to conmon, podman has to close the connection and fd.

**Comment by Luap99** [comment]
Tests are green. @mheon @rhatdan PTAL again

**Comment by mheon** [comment]
LGTM

**Pull request merged**
