### PR TITLE
CI: system tests: instrument to allow failure analysis

### PR DESCRIPTION
**Pull request by edsantiago**
Two tests failing in gating but never CI; add some debug
instrumentation to make it possible to find out what
is going on

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
@lsm5 FYI. Too late for this round of gating tests, but when it fails again we'll be ready

**Comment by rhatdan** [comment]
LGTM

**Review by Luap99 — APPROVED** [review]
/lgtm

I always forget the "run" doesn't actually log anything by default...
I wonder if we should add a generic run_command wrapper like run_podman that we can use instead

**Comment by edsantiago** [comment]
> I wonder if we should add a generic run_command wrapper like run_podman that we can use instead

I submitted a PR years ago. They rejected it, but accepted some parts of it (automatic error checking) and I thought they were considering the logging parts. Looks like not. I've put this on my TODO list.

**Pull request merged**
