### PR TITLE
chore: Enable codeql action

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This action runs GitHub's industry-leading semantic code analysis engine, CodeQL, against a repository's source code to find security vulnerabilities.

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast

### CODE REVIEW

**Comment by baude** [comment]
not sure I love a security analysis tool that reports publicly. @containers/podman-maintainers PTAL

**Comment by naveensrinivasan** [comment]
> not sure I love a security analysis tool that reports publicly. @containers/podman-maintainers PTAL

I understand. But anyone can fork and run this. So this report is technically available to everyone!

**Comment by Luap99** [comment]
I do not see the value of this. It is complaining about the use paths that the user can influence? That just doesn't make any sense to me. We expect paths from users and that is a completely valid use case.

If want this we could enable this as linter in golangci-lint and do not need an extra github actions job for this.

**Comment by mheon** [comment]
As is, I also suspect this is non-blocking - the only blocking job, AFAIK, is Cirrus "Total Success"

**Comment by rhatdan** [comment]
I am for adding to linter, if we can tamp it down to allow users to input paths.

**Pull request closed without merging**
