### PR TITLE
Add the `Status` field in the ps --format=json

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>
Fixes: https://github.com/containers/podman/issues/6980

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
All kinds of test timeout and unable to remove container errors in the CI tests. I'm not sure how this change would do that.

**Comment by zhangguanzhang** [comment]
> All kinds of test timeout and unable to remove container errors in the CI tests. I'm not sure how this change would do that.
```
[+0215s] # $ /var/tmp/go/src/github.com/containers/podman/bin/podman-remote --url unix:/tmp/podman.nUsXlU wait f99281f82ea12b5d50e5374a5925dd48f96f09e4f42c4bb50df939c3860f6b13
[+0215s] # timeout: sending signal TERM to command ‘/var/tmp/go/src/github.com/containers/podman/bin/podman-remote’
[+0215s] # [ rc=124 (** EXPECTED 0 **) ]
```
These lines did not work as expected for some reason https://github.com/containers/podman/blob/master/test/system/075-exec.bats#L31-L33
can come here to discuss this issue https://github.com/containers/podman/issues/7241

**Comment by edsantiago** [comment]
@zhangguanzhang please rebase on master, to fix the constantly-failing CI errors. I am sorry about the inconvenience.

**Comment by zhangguanzhang** [comment]
@vrothberg  PTAL

**Comment by vrothberg** [comment]
Thanks, @zhangguanzhang !

**Pull request merged**
