### PR TITLE
Replace old RESTful tutorial with updated README

### PR DESCRIPTION
**Pull request by baude**
Remove outdated information on go bindings.  Moved the tips for
debugging into the REAME and tidied up relevant links.

Fixes: #9334
[CI_DOCS]
[NO TESTS NEEDED]

Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Would it make sense to remove the outdated tutorial?

**Comment by baude** [comment]
> Would it make sense to remove the outdated tutorial?

Yes of course.  Meant to do that as well.

**Review by vrothberg — COMMENTED** [review]
LGTM
@Luap99 PTAL

**Pull request merged**
