### PR TITLE
pod: ps does not race with rm

### PR DESCRIPTION
**Pull request by giuseppe**
the "pod ps" command first retrieves the list of all pods, then
iterates over the list to inspect each pod.  This introduce a race
since a pod could be deleted in the meanwhile by another process.

Solve it by ignoring the define.ErrNoSuchPod error.

Closes: https://github.com/containers/podman/issues/14736

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Now podman ps doesn't race with podman pod rm
```

### CODE REVIEW

**Comment by ydayagi** [comment]
excellent

**Review by vrothberg — COMMENTED** [review]
LGTM
@edsantiago PTAL

**Comment by mheon** [comment]
Restarting two flakes, LGTM

**Review by edsantiago — APPROVED** [review]
Test LGTM: fails reliably on main. The `compose` test failure is disturbing. The other one is #14744 which is also disturbing.

**Comment by edsantiago** [comment]
Uh-oh. Did you miss a place where this could fail?
```
[+1003s] not ok 259 podman pod ps doesn't race with pod rm
# # podman pod create
....
# # podman pod ps -q
# Error: no pod with ID blahblah found in database: no such pod
```
Failure is in [ubuntu root](https://api.cirrus-ci.com/v1/artifact/build/5020509002792960/sys%20podman%20ubuntu-2110%20root%20host/html/sys-podman-ubuntu-2110-root-host.log.html)

**Comment by giuseppe** [comment]
> Uh-oh. Did you miss a place where this could fail?

I think the failure is coming from the `pod rm -a`.  I need to add the same fix there

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
