### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**
Also backport changes from https://github.com/cri-o/cri-o/pull/4065/files#diff-1d37e48f9ceff6d8030570cd36286a61R189-R197

Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
@saschagrunert PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
@hswong3i tyvm for all your work in this arena, it's very much appreciated.

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
