### PR TITLE
bump go module to version 4

### PR DESCRIPTION
**Pull request by vrothberg**
Automated for .go files via gomove [1]:
`gomove github.com/containers/podman/v3 github.com/containers/podman/v4`

Remaining files via vgrep [2]:
`vgrep github.com/containers/podman/v3`

[1] https://github.com/KSubedi/gomove
[2] https://github.com/vrothberg/vgrep

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM, but this will probably break a few PRs.

**Comment by vrothberg** [comment]
> LGTM, but this will probably break a few PRs.

Once merged we need to be careful to not merge PRs importing `/v3` dependencies.

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by vrothberg** [comment]
Green and ready to merge.

**Pull request merged**
