### PR TITLE
docs: remove usage of deprecated `--storage` in the doc of podman-build

### PR DESCRIPTION
**Pull request by ruihe774**
```release-note
None
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
You can remove external containers with podman rm --force see the docs there. So the last sentence should stay otherwise users do not know how to remove them

**Comment by baude** [comment]
agree with @Luap99 ... if you repush, we should be good. Thanks!

**Comment by ruihe774** [comment]
> You can remove external containers with podman rm --force see the docs there. So the last sentence should stay otherwise users do not know how to remove them

I think #7891 has already allowed users to remove external containers directly. No need for `--force`.

**Comment by Luap99** [comment]
> > You can remove external containers with podman rm --force see the docs there. So the last sentence should stay otherwise users do not know how to remove them
> 
> I think #7891 has already allowed users to remove external containers directly. No need for `--force`.

If they are not mounted it seems to work without so yes.

**Comment by mheon** [comment]
LGTM on my end

**Pull request merged**
