### PR TITLE
e2e: clean up kube, to avoid error in teardown

### PR DESCRIPTION
**Pull request by edsantiago**
Minor. Found by temporarily enabling #18442.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Oops, forgot to link to [the error itself](https://api.cirrus-ci.com/v1/artifact/task/5684977854054400/html/int-podman-fedora-37-root-container-sqlite.log.html#t--Podman-play-kube-podman-play-kube-test-with-reserved-volumes-from-annotation-in-yaml--1).

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
I agree this should be a warning not an error.  Lets open a different issue and fix there.

**Comment by edsantiago** [comment]
/hold

Leaving this open, since I assume the message will remain regardless (at different severity)

**Comment by Luap99** [comment]
If the volume is still being used we should just ignore that. It makes no sense to print a warning or error in such a case. IMO the volume should only be removed if nothing else depends on that.
cc @mheon

**Comment by mheon** [comment]
I can see the case for a warning. It's a resource created by `kube play` that is not being torn down properly by `kube down`; warning the user that we failed to remove all resources created seems sensible.

**Comment by Luap99** [comment]
But the volume was created when ctr1 was created so play kube just reuses that. I don't think it is sane to attempt to remove volumes that are still in use by others containers, i.e. ctr1 and ctr2 in this case. If ctr1/2 were removed then I agree the volume should be removed.

**Comment by mheon** [comment]
Sure, not disagreeing, I just feel it's worth warning the user that we tried to remove a volume, but it was still in use.

**Comment by rhatdan** [comment]
Shouldn't the only problem here be if a third container outside of podman kube play got started and used the volume?

**Comment by edsantiago** [comment]
What I'm hearing in this discussion is that #18442 would be *really* nice to have enabled in CI. Some of us already know this; I hope the conversation is swaying others.

**Comment by rhatdan** [comment]
@edsantiago what should we do with this PR?

**Comment by edsantiago** [comment]
From the discussion, I get the sense that someone should file an issue to ... I have no idea. @mheon, @Luap99, you seem to have the strongest ideas about what should happen here. (My strong idea is that there should be no warning whatsoever, but I might be in the minority). Could one of you please file an issue with the appropriate details? We can then close this PR.

**Comment by vrothberg** [comment]
@mheon @Luap99 ping (https://github.com/containers/podman/pull/19637#issuecomment-1722464797)

**Comment by Luap99** [comment]
IMO there should be no warning in such case as this is expected for such configurations. I can open a PR for that if others agree.

**Comment by vrothberg** [comment]
> IMO there should be no warning in such case as this is expected for such configurations. I can open a PR for that if others agree.

SGTM :+1:

**Comment by Luap99** [comment]
PR https://github.com/containers/podman/pull/20100

**Pull request closed without merging**
