### PR TITLE
bump to v3.1.0-dev

### PR DESCRIPTION
**Pull request by vrothberg**
Given we branched for 3.0 already, bumping the version in the main
branch will help prevent confusion in case users report issues on main
versus the v3.0 branch.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

@mheon PTAL

### CODE REVIEW

**Comment by mheon** [comment]
Good catch, LGTM

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
Ready to merge

**Pull request merged**
