### PR TITLE
[CI:DOCS] Fix spelling "read only" -> "read-only"

### PR DESCRIPTION
**Pull request by eriksjolund**
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
I am not sure there is a "correct" way to spell read-only but being consistent in the way we talk about it in the code makes sense.

LGTM.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by edsantiago** [comment]
LGTM. All of those fixes are correct.

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
