### PR TITLE
[v4.6] Backports and updated release notes

### PR DESCRIPTION
**Pull request by ashley-cui**
Bugfix backports and release notes. I think we're missing a couple more but I'll fold those into the release cut PR tomorrow. 

```release-note
None
```

### CODE REVIEW

**Comment by ashley-cui** [comment]
Got it, I'll drop that commit for now, I believe we're cutting a new common tomorrow so once that's done, I'll grab that commit and backport it with the version bump. Thanks @TomSweeneyRedHat !

**Comment by vrothberg** [comment]
https://github.com/containers/common/pull/1505 just merged, so I'll cut a new patch release and drop the info here once it's done :)

**Comment by vrothberg** [comment]
Ready https://github.com/containers/common/releases/tag/v0.55.2 :checkered_flag:

**Comment by vrothberg** [comment]
@ashley-cui, can you also cherry-pick https://github.com/containers/podman/pull/19210?

**Comment by ashley-cui** [comment]
@containers/podman-maintainers looks like this will go green, PTAL :)

**Review by Luap99 — COMMENTED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
