### PR TITLE
Sort quadlet keys to make it easier to read

### PR DESCRIPTION
**Pull request by rhatdan**
[NO NEW TESTS NEEDED]
Since this is just sorting keys.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

Needs a '[NO NEW TESTS NEEDED]'

**Comment by vrothberg** [comment]
Restarted flakes
@containers/podman-maintainers PTAL

**Comment by ygalblum** [comment]
LGTM
/lgtm
/hold

**Pull request merged**
