### PR TITLE
machine applehv: create better error on start failure

### PR DESCRIPTION
**Pull request by Luap99**
If gvproxy or vfkit exit we can error right away, so while we wait for the socket to get ready we also keep checking the process status with wait4() and WNOHANG so it does not block forever. This is completely untested as I do not have acces to apple machine.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@baude @ashley-cui @jakecorrenti @n1hility PTAL, as discussed early this should help us to check if the processes are still alive while we wait for the sockets. If the process exited then it will return early with a better error as there is no point in keeping waiting for the socket.

**Comment by baude** [comment]
LGTM -- and I verified by intentionally injecting something that gvproxy would barf on ...

```brentbaude@Brents-Mac-mini podman % ./bin/darwin/podman --log-level debug machine start
INFO[0000] ./bin/darwin/podman filtering at log level debug
DEBU[0000] Using Podman machine with `applehv` virtualization provider
DEBU[0000] connection refused: http://localhost:8081/vm/state
Starting machine "podman-machine-default"
DEBU[0000] connection refused: http://localhost:8081/vm/state
DEBU[0000] gvproxy binary being used: /usr/local/bin/gvproxy
DEBU[0000] [-debug -mtu 1500 -ssh-port 49337 -listen-vfkit uunixgram:///var/folders/hy/70c48zyx1g14f1fk2hbmqszc0000gn/T/podman/gvproxy.sock -forward-sock /Users/brentbaude/.local/share/containers/podman/machine/applehv/podman.sock -forward-dest /run/user/501/podman/podman.sock -forward-user core -forward-identity /Users/brentbaude/.ssh/podman-machine-default -pid-file /var/folders/hy/70c48zyx1g14f1fk2hbmqszc0000gn/T/podman/gvproxy.pid]
DEBU[0000] gvproxy unixgram socket "/var/folders/hy/70c48zyx1g14f1fk2hbmqszc0000gn/T/podman/gvproxy.sock" not found: stat /var/folders/hy/70c48zyx1g14f1fk2hbmqszc0000gn/T/podman/gvproxy.sock: no such file or directory
Error: gvproxy exited unexpectedly with exit code 1
DEBU[0000] Shutting down engines```

**Comment by jakecorrenti** [comment]
LGTM, just needs the [NO NEW TESTS NEEDED] message in your commit to get rid of the validate errors

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Pull request closed without merging**
