### PR TITLE
[v3.0.1-rhel] update json-iterator/go for golang-1.18

### PR DESCRIPTION
**Pull request by baude**
the current version of json-iterator/go and modern-go/reflect have a
bug? in them where the code will compile but upon use will segv.

Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
CHanges LGTM, but lots of red unhappy tests.....

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
