### PR TITLE
[apiv2] don't ignore the ENV and WorkDir from the image

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Fixes: https://github.com/containers/podman/issues/7235#issuecomment-699472724
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
CI flake is #7139, restarted

**Review by edsantiago — CHANGES_REQUESTED** [review]
Could you include a descriptive commit message? A future maintainer may not completely understand what problem this commit addresses.

**Comment by zhangguanzhang** [comment]
> Could you include a descriptive commit message? A future maintainer may not completely understand what problem this commit addresses.

done

**Comment by edsantiago** [comment]
Hmmm, can you double-check? I'm still not seeing a commit message. What do you see when you click the `Commits` tab and then click the `...` expander?

**Comment by zhangguanzhang** [comment]
> Hmmm, can you double-check? I'm still not seeing a commit message. What do you see when you click the `Commits` tab and then click the `...` expander?

My mistake, the edit was wrong when rebase 😥

**Comment by rhatdan** [comment]
Thanks @zhangguanzhang

**Pull request merged**
