### PR TITLE
feature: Podman image set the temporary load directory

### PR DESCRIPTION
**Pull request by cubxxw**
#### Does this PR introduce a user-facing change?

Set the temporary load directory

```release-note

```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
Thanks for contributing, @cubxxw!

Are you aware of `image_copy_tmp_dir` in `man containers.conf`?  You may also override it via the `TMPDIR` environment variable.

Would that work for your use case?

**Comment by cubxxw** [comment]
> Thanks for contributing, @cubxxw!
> 
> Are you aware of `image_copy_tmp_dir` in `man containers.conf`? You may also override it via the `TMPDIR` environment variable.
> 
> Would that work for your use case?

oh, sorry, because I happened to see podman some buildah has necessary features such as setting temporary loading directory, I think it is necessary, so I have this RP, but I don't understand what you mean

**Comment by vrothberg** [comment]
> oh, sorry, because I happened to see podman some buildah has necessary features such as setting temporary loading directory, I think it is necessary, so I have this RP, but I don't understand what you mean

What I mean is that this functionality already exists, for instance, when you set `$ TMPDIR=/my/tmpdir podman load` or the field in containers.conf above.  Would that work for you or do you need a flag?

**Comment by vrothberg** [comment]
Can you elaborate why the env variable or the containers.conf config file don't work in your scenario?

I am a bit reluctant to add a flag because no other command exposes such a flag.  I am afraid that we would need to add a `--tmp*` flag to pull/push/create/... and all the other commands who may be loading/pulling an image.

**Comment by cubxxw** [comment]
Ok, I'll go back to an issue and describe it

**Pull request closed without merging**
