### PR TITLE
compat api: fix regressions from "Swagger refactor/cleanup"

### PR DESCRIPTION
**Pull request by Luap99**
For some reason commit 5b79cf15a022 moved the container create options
parsing from cmd/podman/common to pkg/api/handlers. However it did not
remove the old code. Unfortunately  it moved the code from an outdated
version and did not update it before this commit was merged.
Therefore a couple of regressions were introduced. I manually compared
both versions and found three missing bugfixes.

I fixed the network test again that was changed in bce97a3b5dd1. We
want bridge as default even as rootless. Sine the test is not run as
rootless in CI the regression was not caught.
Also the no hosts test never worked since it was missing the import
check if the hosts file exists.

I don't think we can check for the volume parsing change since this only
works on windows/wsl.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@cdoern PTAL

**Review by cdoern — APPROVED** [review]
LGTM. As long as no other functions in cmd/... used `ContainerCreateToContainerCLIOpts` (Which I do not think they do) this is good.

**Comment by mheon** [comment]
Lint needs fixing and we can merge

**Comment by edsantiago** [comment]
LGTM. That was a good catch; thank you for taking the time to look at #14543 and notice it. I will look into enabling rootless APIv2 tests.

**Pull request merged**
