### PR TITLE
podman generate kube ignores --network=host

### PR DESCRIPTION
**Pull request by mlegenovic**
Signed-off-by: Milivoje Legenovic <m.legenovic@gmail.com>

This should solve #9077

### CODE REVIEW

**Comment by rhatdan** [comment]
Could you add a test?

**Comment by mlegenovic** [comment]
@rhatdan Added two new tests, one for pod with host network, and another one for container (without pod) with host network. Two existing tests extended with checks pod.spec.hostNetwork to be false (if network-mode is not host).

**Comment by rhatdan** [comment]
Tests are failing.

**Comment by rhatdan** [comment]
LGTM
/approve
@containers/podman-maintainers PTAL

**Comment by zhangguanzhang** [comment]
LGTM

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
