### PR TITLE
Bump to v5.0.3

### PR DESCRIPTION
**Pull request by mheon**
As the title says

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by lsm5 — APPROVED** [review]
/lgtm
/approve
/hold

**Comment by lsm5** [comment]
ignore packit `centos-stream-*` failures.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mheon** [comment]
Looks like it'll pass
/hold cancel

**Pull request merged**
