### PR TITLE
Kube Play: fix the handling of the optional field of SecretVolumeSource

### LINKED ISSUE #16636: Kube Play mishandles the Optional field in Volume of type Secret
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Kube Play has two issues when it handles a Volume with SecretVolumeSource:

1. The field `Optional` in the `SecretVolumeSource` structure is an optional field with a default value of `false`. However, not setting the field causes a segmentation fault. The reason for the segmentation fault is that since the field is optional its type it `*bool`, but the code derefereneces it without checking if it is not nil
2. Setting the `Optional` to `true` causes Podman to disregard the secret even if it exists

**Steps to reproduce the issue:**

1. Create a Secret
2. Use the secret as the source to a volume
3. Do not set the `optional` field or set it to `true`

**Describe the results you received:**
When not setting `optional`, Podman crashes
When setting `optional` to `true` the container is created but the secret is not mounted into it

**Describe the results you expected:**
In both cases, since the secret exists, it should be mounted into the container

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.18.7
Built:        Fri Oct 21 11:16:35 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-3.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 92.53
    systemPercent: 1.36
    userPercent: 6.11
  cpus: 12
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.0.8-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1310138368
  memTotal: 33400233984
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.7-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7
      commit: 40d996ea8a827981895ce22886a9bac367f87264
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4194123776
  swapTotal: 8589930496
  uptime: 243h 21m 43.00s (Approximately 10.12 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/ygal/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 6
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ygal/.local/share/containers/storage
  graphRootAllocated: 510389125120
  graphRootUsed: 132883378176
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 18
  runRoot: /run/user/1000/containers
  volumePath: /home/ygal/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.0
  Built: 1666340195
  BuiltTime: Fri Oct 21 11:16:35 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman-4.3.0-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

### PR DESCRIPTION
**Pull request by ygalblum**
If the secret exists, set optional in the KubeVolume to false to always use it
If the secret does not exist, if optional, set the same in the KubeVolume to skip it, otherwise fail

Signed-off-by: Ygal Blum <ygal.blum@gmail.com>

#### Does this PR introduce a user-facing change?
No
```release-note
Fix the handling of the optional field of SecretVolumeSource
```

Fixes #16636

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Changes LGTM, thanks!

Can you add a test, @ygalblum?

**Comment by ygalblum** [comment]
@vrothberg I've already started working on them. I'll add them to the PR later today

**Comment by rhatdan** [comment]
Looks like this needs to be gofmt

**Comment by rhatdan** [comment]
LGTM
Will merge once tests pass.

**Comment by ygalblum** [comment]
@rhatdan All tests passed, waiting for you to remove the hold

**Comment by rhatdan** [comment]
@ygalblum You can remove the hold yourself, with
/hold cancel

**Pull request merged**
