### PR TITLE
Final Backports and Bump to v4.2.0

### PR DESCRIPTION
**Pull request by mheon**
As the title says.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon all kinds of test unhappiness....

**Comment by mheon** [comment]
It's all checkpoint/restore stuff, in a test that AFAIK has not changed for 2 years...

**Comment by mheon** [comment]
Aha, nevermind. I backported a commit that enabled more tests; must not be working yet on this branch.

**Comment by mheon** [comment]
Re-pushed, hopefully will work now

**Comment by mheon** [comment]
I don't see the machine tests running. @baude @cevich Am I just missing them?

**Comment by cevich** [comment]
`machine podman fedora-36 rootless host ` is what you're looking for (in the big list).  The [current task](https://cirrus-ci.com/task/5911427520135168) appears like it will kick off once all the dependencies are met.  If not, double-check the task doesn't have a 'trigger' button on it.  Lokesh noticed this, even after adding the required PR label.

***Note***: The label is now gone on main, too much of a pain.  I'm completely okay if we want to turn that "feature" off here, should it start causing any trouble.  It's a one-line change (IIRC).

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
