### PR TITLE
remote stats

### PR DESCRIPTION
**Pull request by vrothberg**
I want to throw it at CI. I'm on F33 (and need to setup a F32 VM for testing).

### CODE REVIEW

**Comment by vrothberg** [comment]
I am positively surprised that only docs are breaking and the rests worked on first try :^)

**Comment by vrothberg** [comment]
Open for reviews from my side.

Added stats for podman-remote, a new endpoint, and refactored quite a bit to make the code simpler and hopefully easier to maintain.

@baude @mheon @jwhonce @rhatdan PTAL

**Comment by baude** [comment]
lgtm

**Review by jwhonce — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
