### PR TITLE
[CI:DOCS] Cirrus: Support EC2 instances in hack/get_ci_vm.sh

### PR DESCRIPTION
**Pull request by cevich**
***Depends on:***
https://github.com/containers/automation_images/pull/160

Signed-off-by: Chris Evich <cevich@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
***HOW TO TEST:***

**Comment by cevich** [comment]
@lsm5 @edsantiago @baude PTAL when you have a moment.  The changes here are pretty simple, the stuff over in https://github.com/containers/automation_images/pull/160 is ***VERY*** scary-complex.  I commented it as best as I could but at this point I'm really mostly interested in "does it work for you"

@edsantiago I don't think you have any AWS creds yet, myself or @lsm5 or @baude can get you some, just ping one of us.

**Comment by cdoern** [comment]
@cevich going to look into this now. I am going to try and see if I can find any glaring issues in c/common before I have you make an AWS account for me

**Comment by cevich** [comment]
Thanks Charlie.  Pushing a quick fix now for that `mkdir` problem you found...

**Pull request merged**
