### PR TITLE
Speedup static build by utilizing CI cache on `/nix` folder

### PR DESCRIPTION
**Pull request by hswong3i**
Also see:
- https://github.com/containers/crun/pull/428
- https://github.com/containers/conmon/pull/189
- https://github.com/containers/skopeo/pull/973
- https://github.com/containers/buildah/pull/2428
- https://github.com/containers/podman/pull/7076
- https://github.com/cri-o/cri-o/pull/4012

Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@saschagrunert PTAL

**Comment by hswong3i** [comment]
@rhafer @saschagrunert I am checking why the reuse of cache result as "Cache miss", but reupload of cache result as "Already uploaded", see https://github.com/cirruslabs/cirrus-ci-docs/issues/681

**Comment by saschagrunert** [comment]
> @rhafer @saschagrunert I am checking why the reuse of cache result as "Cache miss", but reupload of cache result as "Already uploaded", see [cirruslabs/cirrus-ci-docs#681](https://github.com/cirruslabs/cirrus-ci-docs/issues/681)

Hm yeah it seems not working at all :thinking:

**Comment by hswong3i** [comment]
@rhatdan  @saschagrunert as https://github.com/cirruslabs/cirrus-ci-docs/issues/681 get fixed now static binary build phase reduce from ~40mins to ~4mins (https://cirrus-ci.com/task/5522320095707136), by caching and reuse previous dependency build result ;-)

**Pull request merged**
