### PR TITLE
system tests: new test for run --log-driver

### PR DESCRIPTION
**Pull request by edsantiago**
Tests all (current) values for --log-driver=X, and one test
for invalid value. For those drivers that write a local
file (json-file, k8s-file), test that the file exists and
contains results of the expected form (timestamp, stdout,
'F' for 'F'ull line, and the expected string output.

For json-file, confirm that podman issues a "Choosing k8s-file"
warning (only on local. On podman-remote, the warning goes only
to the server's stderr).

Written in response to #7754 in which driver=json-file was
falling through to 'none' instead of 'k8s-file'.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
To bring this explicitly to everyone's attention: there is a bug somewhere in which `podman-remote run --log-driver=json-file ...` emits the warning line **on the server**, not the client.

**Comment by rhatdan** [comment]
LGTM

**Comment by Luap99** [comment]
@edsantiago journald driver could be tested with something like this:
```
$ podman run --log-driver journald --conmon-pidfile /tmp/conmonpid alpine echo teststring
teststring
$ journalctl --output cat  _PID=$(cat /tmp/conmonpid)
teststring

```

**Comment by edsantiago** [comment]
@Luap99 thank you - that may be a TBD for a future test, but not this one: it would make it more complicated and fragile.

**Pull request merged**
