### PR TITLE
[NO TESTS NEEDED] pkg/bindings/images.Build(): fix a race condition in error reporting

### PR DESCRIPTION
**Pull request by nalind**
In nTar(), don't return the error value when the goroutine that's populating the error value can continue running long after nTar() returns.  Instead, wrap the Close() method of the pipe that we're returning in a function that collects those errors, along with any error we get from closing the pipe, and returns them from Close() wrapper.
In Build(), if the Close() method returns an error, at least log it.

Should help with https://github.com/containers/podman/issues/9379.

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
Thank you!

**Comment by edsantiago** [comment]
Thank you @nalind! You may need to force-push to rerun CI; looks like Cirrus can't pick up my title change.

**Comment by nalind** [comment]
@edsantiago no problem, looks like I needed to rebase anyway.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by nalind** [comment]
Rebased.

**Pull request merged**
