### PR TITLE
[CI:DOCS] swagger: removes the schema type for PodSpecGenerator $ref

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by mheon** [comment]
@TristanCacqueray Recommend adding `[CI:DOCS]` to your title, adding a signoff to the commit, and force-pushing to fix CI.

Otherwise LGTM.
/approve
@baude @jwhonce PTAL

**Comment by TristanCacqueray** [comment]
@mheon thank you for the feedback.

**Comment by TomSweeneyRedHat** [comment]
Still fighting fedora-33 test, IDK if that's an issue with the test system or not.

**Comment by mheon** [comment]
That looks network-related. Restarted it.

**Pull request merged**
