### PR TITLE
Examine all SkipIfRemote functions

### PR DESCRIPTION
**Pull request by rhatdan**
Remove ones that are not needed.
Document those that should be there.
Document those that should be fixed.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan all kinds of  test unhappiness, but I think you were expecting that.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Hoping for the best, but expecting failures. So far they have been self induced.

**Comment by rhatdan** [comment]
This looks like it is ready to merge.
@edsantiago @vrothberg @giuseppe @saschagrunert @TomSweeneyRedHat @baude @mheon @ashley-cui @QiWang19 @jwhonce PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by vrothberg** [comment]
> /lgtm

That was a bit too quick :) We need two LGTMs to merge. No biggy, just a reminder.

**Pull request merged**
