### PR TITLE
[CI:BUILD] Cirrus: remove copr rpm build task

### PR DESCRIPTION
**Pull request by lsm5**
Packit copr build tasks take care of this already so this can be safely removed.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

@cevich PTAL
cc @containers/podman-maintainers

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
but definitely want @cevich eyeballs on it

**Review by cevich — APPROVED** [review]
/lgtm

**Pull request merged**
