### PR TITLE
Bump to v5.2.5

### PR DESCRIPTION
**Pull request by mheon**
As the title says

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Review by lsm5 — APPROVED** [review]
/lgtm
/hold

**Comment by TomSweeneyRedHat** [comment]
Can you remove the last commit?  We're not adding `-dev` tags to release branches.

**Comment by mheon** [comment]
I don't think that is necessary, this is not a RHEL branch

**Pull request merged**
