### PR TITLE
[v4.2.0-rhel] vendor: bump to c/common v0.49.3

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
do not start up a dbus daemon if it is not already running.
```

### CODE REVIEW

**Comment by Luap99** [comment]
Can you add the link to the bz here as well.

**Comment by giuseppe** [comment]
here is the link: https://bugzilla.redhat.com/show_bug.cgi?id=2153894

**Comment by TomSweeneyRedHat** [comment]
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2154004 and https://bugzilla.redhat.com/show_bug.cgi?id=2154015

**Pull request merged**
