### PR TITLE
[CI:DOCS] Minor: Remove unhelpful comment

### PR DESCRIPTION
**Pull request by cevich**
Likely a copy-paste error, it doesn't apply here.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
LGTM. Is there any way (other than cli-pulling the PR) to get rid of the Cirrus noise?

**Comment by cevich** [comment]
> get rid of the Cirrus noise?

Yes.  In the "files" tab, for the `.cirrus.yml` file, click the "...".  Then on the RHS, un-check "show annotations".

**Comment by edsantiago** [comment]
THANK YOU!!

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
