### PR TITLE
Fixes secret marshaling for kube play. Merge stringData with data for secrets.

### LINKED ISSUE #16269: play kube: invalid character 'a' looking for beginning of value
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Kubernetes secrets broken

**Steps to reproduce the issue:**

1. `podman kube play test-secret.yaml`
2. `podman kube play test-pod.yaml`

**Describe the results you received:**
`Error: cannot set env TOKEN: secret secret-token-secret is not valid JSON: invalid character 'a' looking for beginning of value`

**Describe the results you expected:**
`A pod with the secret env`

**Additional information you deem important (e.g. issue happens only occasionally):**
Ever time

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.19.2
Git Commit:   ad42af94903ce4f3c3cd0693e4e17e4286bf094b-dirty
Built:        Wed Oct 19 23:09:30 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon ist in conmon 1:2.1.4-1 enthalten
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: bd1459a3ffbb13eb552cc9af213e1f56f31ba2ee'
  cpuUtilization:
    idlePercent: 39.96
    systemPercent: 8.45
    userPercent: 51.59
  cpus: 8
  distribution:
    distribution: endeavouros
    version: unknown
  eventLogger: journald
  hostname: deus-ex-machina
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.0.2-zen1-1-zen
  linkmode: dynamic
  logDriver: journald
  memFree: 1092579328
  memTotal: 33373282304
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun ist in crun 1.6-1 enthalten
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns ist in slirp4netns 1.2.0-1 enthalten
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 29080649728
  swapTotal: 36722176000
  uptime: 168h 4m 30.00s (Approximately 7.00 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/martin/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /home/martin/.local/share/containers/storage
  graphRootAllocated: 962850717696
  graphRootUsed: 861402361856
  graphStatus:
    Build Version: Btrfs v6.0
    Library Version: "102"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/martin/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.0
  Built: 1666213770
  BuiltTime: Wed Oct 19 23:09:30 2022
  GitCommit: ad42af94903ce4f3c3cd0693e4e17e4286bf094b-dirty
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.0

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman 4.3.0-1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
[test-pod.yaml.txt](https://github.com/containers/podman/files/9847360/test-pod.yaml.txt)
[test-secret.yaml.txt](https://github.com/containers/podman/files/9847361/test-secret.yaml.txt)

### LINKED ISSUE #16625: Kubernetes secret and base64 data
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Mounting/using a kubernetes secret does not behave the same as kubernetes.

A kubernetes secret value is is usually encoded in base64:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  foo: YmFy
``` 

Mouting the above volume in a pod results in a file called "foo" with the conents "YmFy" instead of "bar".

Now there is a way to define non-base64 secret data by using `stringData` instead of  `data`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
stringData:
  foo: bar
``` 

In this case podman ignores `stringData` entirely and no file gets created.

Podman is dealing with `data` as if it was `stringData` and ignoring `stringData` entirely, which is not the expected behaviour if your compare it to kubernetes.

**Steps to reproduce the issue:**

1. Create a kubernetes secret in podman:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  foo: YmFy
```

3. Create a pod.yaml file that mounts the above secret in a volume:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: app
      image: fedora
      command: ["/usr/bin/sleep", "infinity"]
      volumeMounts:
        - name: mysecret
          mountPath: "/etc/mysecret"
          readOnly: true
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret
        optional: false
```

5. Run `podman kube play --replace pod.yaml`

6.  "Get into the container": `odman exec -it mypod-app /bin/bash`

7. Run `cat /etc/mysecret/foo`

**Describe the results you received:**

```
[root@mypod /]# cat /etc/mysecret/foo 
YmFy
```

This is what I get, the encoded base64 string, the expected value would be the decoded base64 value "bar".

**Describe the results you expected:**

This is the output I get from kubernetes (deploying the same yaml files):

```
$ kubectl exec -it mypod -- cat /etc/mysecret/foo
bar
```

I get the decoded value in my secret file which is what I would expect to happen in podman.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.7
Built:        Fri Nov 11 12:24:13 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 98.5
    systemPercent: 0.33
    userPercent: 1.16
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: 192.168.1.16
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.0.9-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 16167878656
  memTotal: 33395277824
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.7-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7
      commit: 40d996ea8a827981895ce22886a9bac367f87264
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 19327344640
  swapTotal: 19327344640
  uptime: 20h 21m 33.00s (Approximately 0.83 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/lrossett/.config/containers/storage.conf
  containerStore:
    number: 14
    paused: 0
    running: 2
    stopped: 12
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/lrossett/.local/share/containers/storage
  graphRootAllocated: 417295147008
  graphRootUsed: 209961308160
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 34
  runRoot: /run/user/1000/containers
  volumePath: /home/lrossett/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668180253
  BuiltTime: Fri Nov 11 12:24:13 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman-4.3.1-1.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, I built it from the main branch and got the same results.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by andrei-n-cosma**
Fixes secret (un)marshaling for kube play.

Merges stringData into data for secrets as in k8s.
Fixes e2e tests, remove '\n' from base64 encoded data.
Correct test to check that data in secret mounted file is decoded.

Closes #16269
Closes #16625

Signed-off-by: Andrei Natanael Cosma <andrei@intersect.ro>

#### Does this PR introduce a user-facing change?
NO

```release-note
Fixes secret unmarshaling for kube play.
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Thanks for contributing!

Changes LGTM
@cdoern PTAL

**Comment by rhatdan** [comment]
@odra PTAL

**Comment by rhatdan** [comment]
@ygalblum  PTAL

**Comment by rhatdan** [comment]
@ashley-cui @umohnani8 PTAL

**Comment by ygalblum** [comment]
This change mixes `data` and `stringData` together. But, according to the spec for `Secret`, the field `data` is base64 encoded while `stringData` isn't. Furthermore, in K8S `stringData` is used to create a secret, but its content is merged into `data` after the values are base64 encoded. In addition, when mounted as a volume, all values are decoded back. So, the application can read them as is. 

I can see that you changed the test so that it looks for the decoded value, but I don't understand what made it work now

**Comment by odra** [comment]
I tried to run the pr locally but I got the following error:

```
$ ./bin/podman play kube --replace pod.yaml 
Error: failed to create volume "mysecret": invalid character 'a' looking for beginning of value
```

secret.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  foo: YmFy
```

pod.yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: app
      image: fedora
      command: ["/usr/bin/sleep", "infinity"]
      volumeMounts:
        - name: mysecret
          mountPath: "/etc/mysecret"
          readOnly: true
            # envFrom:
            # - secretRef:
            # name: mysecret
            # env:
            #   - name: FOO
            #     valueFrom:
            #       secretKeyRef:
            #         name: mysecret
            #         key: foo
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret
        optional: false
```

**Comment by andrei-n-cosma** [comment]
> This change mixes `data` and `stringData` together. But, according to the spec for `Secret`, the field `data` is base64 encoded while `stringData` isn't. Furthermore, in K8S `stringData` is used to create a secret, but its content is merged into `data` after the values are base64 encoded. In addition, when mounted as a volume, all values are decoded back. So, the application can read them as is.
> 
> I can see that you changed the test so that it looks for the decoded value, but I don't understand what made it work now

The base64 decoding happens on unmarshaling.
https://github.com/containers/podman/blob/main/pkg/domain/infra/abi/play.go#L268

The problem was that the entire secret object was serialized and stored in the (podman) secret while only the data of it was expected to be loaded when using it to fill env vars or volumes - hence the error. Also K8s states that content of secrets in volumes and environment variables should be decoded and also that stringData will be put on top of data (which was no the case previously).
Since decoding on base64 data happens during unmarshaling, adding stringData on top doesn't have to be base64 encoded before adding it. We only store podman secret as storage medium for values of K8s secret (data and stringData) - we could store the entire secret yaml, but then the code has to be changed since it mixed storing the yaml and loading json (data).

**Comment by andrei-n-cosma** [comment]
@odra 
I've tried it and no issue. Please make sure that you run podman from the build and not local one (did same mistake while testing it previously).

`podman on  fix-secret-unmarshal [?] via 🐹 v1.19.3 via 🐍 v3.10.8 via ⍱
❯ bin/podman kube play secret.yaml

podman on  fix-secret-unmarshal [?] via 🐹 v1.19.3 via 🐍 v3.10.8 via ⍱
❯ bin/podman kube play pod.yaml
Pod:
4dd786023d2a7c717b025d6cb97177f34c3bd1051566bfb88f660944d0ea3ef7
Container:
3f3e8a5033a595b91d611142773d4ee24f2ed8c9ad7ee261ec418dec13dc8396

podman on  fix-secret-unmarshal [?] via 🐹 v1.19.3 via 🐍 v3.10.8 via ⍱
❯ bin/podman exec -it mypod-app ls /etc/mysecret/
foo

podman on  fix-secret-unmarshal [?] via 🐹 v1.19.3 via 🐍 v3.10.8 via ⍱
❯ bin/podman exec -it mypod-app cat /etc/mysecret/foo
bar
`

**Comment by andrei-n-cosma** [comment]
Ran it with --replace and no issue.
podman on  fix-secret-unmarshal [?] via 🐹 v1.19.3 via 🐍 v3.10.8 via ⍱
❯ bin/podman kube play --replace pod.yaml
Pods stopped:
4dd786023d2a7c717b025d6cb97177f34c3bd1051566bfb88f660944d0ea3ef7
Pods removed:
4dd786023d2a7c717b025d6cb97177f34c3bd1051566bfb88f660944d0ea3ef7
Volumes removed:
Pod:
2ed36a9f4b51467e07fa60ef127808ed236256c43ce8150e62d83261446b8335
Container:
48114384883ca0d04442c9fa36055913d56b251b348211293c7aa2f81b03898a

**Comment by ygalblum** [comment]
Sorry for nagging, I'm just trying to understand why before the change the values in the container were encoded and now they are not.

Your change I understand. Instead of storing the entire K8S secret object as Podman secret, you store only its data by combining `data` and `stringData` into a single map and marshaling it into a json.

Furthermore, I now understand that the decoding is handled by the `Unmarshal` method and as a result when you merge `data` and `stringData` the values in both maps are decoded and hence there is no issue in combining them.

But, what I fail to understand is why before this change the values mounted into the container were encoded and now they are decoded. Now, don't get me wrong, I agree they should be decoded to align with K8S. I just don't understand how it happened.

Thanks in advance

**Comment by andrei-n-cosma** [comment]
I haven't really checked it but might come from the fact that play used "github.com/ghodss/yaml" for marshaling while volume used "gopkg.in/yaml.v3" for unmarshaling.

**Comment by ygalblum** [comment]
> I haven't really checked it but might come from the fact that play used "github.com/ghodss/yaml" for marshaling while volume used "gopkg.in/yaml.v3" for unmarshaling.

OK, thanks

**Comment by ygalblum** [comment]
LGTM, but I guess @odra should first see what's not working for him

**Comment by ashley-cui** [comment]
Will this break existing kube secrets? Since this changes the secret storage schema?

**Comment by ygalblum** [comment]
I think @ashley-cui is right. K8S secrets are stored into Podman secrets and hence persist. Since this change breaks the schema, podman will fail to load secrets that were created with an older version

**Comment by odra** [comment]
Yeah, that's the issue I had, storing secrets with "play kube" works wihile storing a raw kubernetes secret with "podman secret create.." breaks it (altough that was working before this change) but creating it wth "play kube" works.

I thought that creating a k8s secret using "play kube" would store the raw yaml/json secret as podman secret but that doesn't seem to be the case right?

Using "play kube" to store kubernetes secrets sound a bit weird to me since there but I may not have the full context of a podman secret.

**Comment by rhatdan** [comment]
If the kube.yaml file includes a secret then the secret should be created for the run of the podman kube play command and removed when the command exits, which I believe follows the k8s standard.

**Comment by andrei-n-cosma** [comment]
IMO maintaining compatibility of kube secret with secrets created directly in podman doesn't make much sense - they will quickly diverge. For example, if we plan to support k8s namespace the only viable solution to not have conflicts would be to add namespace as part of the secret name: my-secret.my-namespace. As @rhatdan said, the only requirement would be that if something is created by kube play it should be possible to be modified/deleted by kube play. Kube play should be built on top of podman but compatibility with it should not be a target, the target is compatibility with k8s. I see the kube play as equivalent to 'kubectl apply'.
I personally see only one reason to have the entire k8s secret marshaled completely in podman secret - to know if some data is coming from data or stringData of the Secret (info which is lost if we merge and store only the content of these 2) but AFAIK it doesn't matter to much to reconstruct original Secret from it's data stored in podman.

**Comment by andrei-n-cosma** [comment]
@rhatdan There is a pipeline failure unrelated to my change. Is someone already looking into that? Is it a known issue or should I report it?

**Comment by vrothberg** [comment]
> I personally wouldn't care much about backward compatibility since the secrets were not usable in the last versions of podman. If needed I can modify it to store/load the entire K8s secret instead of only the data, not sure if make sense.

Yes, let's restore to the previous behavior.  We must remain backwards compatible unless there's an urgent need not to (e.g., security fix).  Thanks for pointing that out, @ashley-cui! (And sorry for not spotting that in my earlier review)

**Comment by andrei-n-cosma** [comment]
@vrothberg Previous behavior restored for backward compatibility.

**Comment by andrei-n-cosma** [comment]
@vrothberg Fixed the read of k8s secret from podman secret to support both JSON and YAML. Should pass now.

**Comment by ashley-cui** [comment]
LGTM, thanks @andrei-n-cosma!

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

I restarted the flaked job.

**Comment by MartinX3** [comment]
will there be a v4.3.2 bugfix release?
I sadly don't see a podman roadmap or a milestone anywhere.

**Comment by vrothberg** [comment]
There are no plans to cut a v4.3.2. But 4.4 is scheduled early next year.

**Comment by MartinX3** [comment]
Thank you for the info
But also it's sad to hear, that bug fixes don't get backported to patch releases until the next feature release comes :(

**Comment by vrothberg** [comment]
> Thank you for the info But also it's sad to hear, that bug fixes don't get backported to patch releases until the next feature release comes :(

They do get backported. v4.3 had two bug-fix releases already. We didn't plan for another patch-release in this specific case as we're close to the end of the year; many folks are on vacation or shortly going to be.

**Pull request merged**
