### PR TITLE
Fix podman-remote build --rm=false ...

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/9869

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
I sort-of have tests for it, in #9887 (enable podman-remote for buildah-bud tests). But I can't merge that until #10154 (flake: stream dropped) is fixed, because that's a very-easy-to-trigger flake and it would cause failures in pretty much every single  CI run.

**Comment by mheon** [comment]
LGTM with a test

**Comment by rhatdan** [comment]
@mheon Since @edsantiago Thinks he has tests for this, and it is clearly correct, I am going to merge, then we can work on fixing the blockage to @edsantiago tests.

**Comment by edsantiago** [comment]
There's only one `bud.bats` test that triggers this, `bud with --rm flag`. I've pulled Dan's PR, removed the `skip` from my podman-remote buildah-bud tests, and confirmed that the test now passes.

If we can get some love for #10154, I can then push to merge #9887, and we'll have tests. I'm OK with merging this PR as it is.

**Comment by rhatdan** [comment]
@edsantiago I have given more hate then love to #10154, and have no idea why this is dropping.  I will attempt to take another look, but could probably use some help from @nalind and @jwhonce To see if they have any ideas.

**Comment by edsantiago** [comment]
>more hate then love

Ah, there's your problem: hate leads to the dark side. Before you know it you'll be hobnobbing with Sith lords and zipping around in a TIE fighter. (Which, come to think of it, sounds kind of neat).

**Comment by TomSweeneyRedHat** [comment]
LGTM
will let @mheon press the shiny merge button.

**Comment by mheon** [comment]
Only have email even

**Pull request merged**
