### PR TITLE
[CI:DOCS] Update notes on java TZ in man page

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

#### What this PR does / why we need it:
Follow up from https://github.com/containers/podman/pull/12373/files.

### CODE REVIEW

**Comment by umohnani8** [comment]
@rhatdan PTAL

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Thx for cleaning up my mess @umohnani8 !

**Pull request merged**
