### PR TITLE
[CI:DOCS] Man pages: refactor common options: --security-opt

### PR DESCRIPTION
**Pull request by edsantiago**
This was a horrible one. I basically went with the podman-run
version, with a few minor changes. See PR for discussion of
diff review.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
more man-page deduplication
```

### CODE REVIEW

**Comment by edsantiago** [comment]
This one is probably impossible to review: the changes are mostly formatting-related. Here is what I did to review:
```bash
#!/bin/bash

declare -a subcommands
subcommands=(build create pod-clone pod-create run)

git co main
make docs
rm -rf docs-save
mkdir docs-save
for i in ${subcommands[*]}; do
    man docs/build/man/podman-$i.1 > docs-save/podman-$i.txt
done

git co docs_dedup_secopt
make docs
for i in ${subcommands[*]}; do
    clear
    echo
    echo podman-$i
    echo
    man docs/build/man/podman-$i.1 | cdif -uw docs-save/podman-$i.txt -
    echo
    echo -n "ENTER to continue: "
    read ok
done
```
That will not work for you unless you have `cdif`, a diff-colorizing tool, so here is the most important diff:
```diff
podman-build

--- docs-save/podman-build.txt  2022-11-02 11:22:55.301062676 -0600
+++ -   2022-11-02 11:22:56.526763566 -0600
@@ -572,11 +572,27 @@                                                                                                                                          
 
               • label=disable       : Turn off label separation for the container
 
-              • no-new-privileges   : Not supported
+       Note: Labeling can be disabled for all containers by setting label=false  in  the  containers.conf  (/etc/containers/containers.conf  or  $HOME/.con‐
+       fig/containers/containers.conf) file.
 
-              • seccomp=unconfined : Turn off seccomp confinement for the container
+              • mask=/path/1:/path/2: The paths to mask separated by a colon. A masked path cannot be accessed inside the container.
 
-              • seccomp=profile.json :  White listed syscalls seccomp Json file to be used as a seccomp filter
+              • no-new-privileges: Disable container processes from gaining additional privileges.
+
+              • seccomp=unconfined: Turn off seccomp confinement for the container.
+
+              • seccomp=profile.json: JSON file to be used as a seccomp filter. Note that the io.podman.annotations.seccomp annotation is set with the spec‐
+                ified value as shown in podman inspect.
+
+              • proc-opts=OPTIONS : Comma-separated list of options to use for the /proc mount. More details for the possible mount options are specified in
+                the proc(5) man page.
+
+              • unmask=ALL  or  /path/1:/path/2,  or shell expanded paths (/proc/*): Paths to unmask separated by a colon. If set to ALL, it will unmask all
+                the paths that are masked or made read-only by default.  The  default  masked  paths  are  /proc/acpi,  /proc/kcore,  /proc/keys,  /proc/la‐
+                tency_stats, /proc/sched_debug, /proc/scsi, /proc/timer_list, /proc/timer_stats, /sys/firmware, and /sys/fs/selinux.  The default paths that
+                are read-only are /proc/asound, /proc/bus, /proc/fs, /proc/irq, /proc/sys, /proc/sysrq-trigger, /sys/fs/cgroup.
+
+       Note: Labeling can be disabled for all containers by setting label=false in the containers.conf(5) file.
 
    --shm-size=number[unit]
        Size of /dev/shm. A unit can be b (bytes), k (kibibytes), m (mebibytes), or g (gibibytes).  If the unit is omitted, the system  uses  bytes.  If  the
```
That is: my changes bring in a LOT of new stuff into the `podman-build` man page, like `no-new-privileges` which as of this moment is called "Not supported" but if this PR merges will have a different description; and all the other `seccomp` and `proc-opts` and `unmask` options that I have no idea if they'll work in podman-build or not. Some expert needs to really look at those. If  this documentation is not applicable to podman-build, I will revert that man page and leave it alone.

All other diffs were minor, like an extra period I removed and now they all say `containers.conf(5)` instead of the long path version. Oh, and the "Whitelisted blah blah / io.podman.annotations.seccomp" difference, "Whitelist" is gone, all pages now have the "annotations" version.

**Comment by rhatdan** [comment]
Can you just add (Not supported for podman build) in the shared man page?

I no that the undocumented ones will not work, or most likely will be ignored.
We could work to implement some of them in Buildah, and having them listed in the man page, could spur some work to make it happen.

**Comment by edsantiago** [comment]
My gut screamed "nooooo" so I stepped away, let it simmer, thought again, and still prefer not to: first because I think it's squicky to type `man podman-run` and see an option with "not supported in podman build". As a user, I would spend brain cells trying to figure out why it was telling me that (because as a user, I'm not aware of the common option refactoring). Second, because I'd screw it up: I don't have the knowledge to figure out which options work in podman-build and which don't.  (And third, because let's be honest our backlog is overwhelming enough already. A note in some man pages isn't going to speed up adding those options to podman-build).

So I've just reverted podman-build to the way it was, and re-pushed.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
