### PR TITLE
Release v5.2.2

### PR DESCRIPTION
**Pull request by lsm5**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
Ignore for now. Other commits will be added.

**Comment by lsm5** [comment]
cc @TomSweeneyRedHat

**Comment by TomSweeneyRedHat** [comment]
@lsm5
LGTM
I think you just need to rebase and this should be GTG

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
