### PR TITLE
Remove unused script file

### PR DESCRIPTION
**Pull request by yzxiu**
#### Does this PR introduce a user-facing change?

```release-note
None
```
Signed-off-by: yaozhenxiu <946666800@qq.com>

### CODE REVIEW

**Comment by yzxiu** [comment]
@Luap99 Today is the first time to read the code of podman,I saw this script and used it to initialize an environment for debug code

**Comment by Luap99** [comment]
Sure your contribution is welcome but I think there is not much value in providing this script. The dependencies should all be available via package manager. If building from source is required it is best to check out the projects directly, at least in my opinion.
But lets wait what other maintainers think.

Btw you have to sign your commits, see https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs

**Comment by edsantiago** [comment]
History suggests that this was created for something called "papr", which AFAICT we ended up not using. Let's just nuke it.

**Comment by mheon** [comment]
Papr was our CI solution prior to Cirrus, which makes it... Three years old? Concur that this is unused and should just be removed.

**Comment by rhatdan** [comment]
Nuke it

**Comment by yzxiu** [comment]
i have removed it

**Comment by edsantiago** [comment]
LGTM but you still need to sign your commit: 
```console
$ git commit --amend -s
...
$ git push --force
```
Thank you!

**Comment by yzxiu** [comment]
@edsantiago Thankyou, is it okay now?

**Review by vrothberg — COMMENTED** [review]
Thanks! Changes LGTM.

In order to pass CI, you need to add the magic string `[NO NEW TESTS NEEDED]` to your commit message.

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
