### PR TITLE
document CAP_SYS_ADMIN required for systemd PrivateNetwork

### PR DESCRIPTION
**Pull request by rhatdan**
Replaces https://github.com/containers/podman/pull/6682

Signed-off-by: James Cassell <code@james.cassell.me>
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @jamescassell I will take care of getting this merged.

**Comment by rhatdan** [comment]
@mheon @TomSweeneyRedHat @baude @ashley-cui @QiWang19 @jwhonce @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Pull request merged**
