### PR TITLE
Fix images since/after tests

### PR DESCRIPTION
**Pull request by baude**
For the since and after imagve filter tests, instead of using the
read-only cache of images, we just use the empty r/w store.  We then
build three images that are strictly predictable.

Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
Should we combine both tests into one since they do basically the same.

**Comment by mheon** [comment]
Combining SGTM. Otherwise, LGTM

**Comment by baude** [comment]
merge me

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/13244 to merge the two tests.

**Comment by cevich** [comment]
Looks like this needs to be backported to `v3.3.1-rhel`, `v3.4.2-rhel`, and `v3.4`?

**Pull request merged**
