### PR TITLE
Bump github.com/containernetworking/plugins to v0.9.1 v3.0.1-rhel

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

As the title says

[NO TESTS NEEDED]

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1942753 for RHEL 8.4

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Addresses  https://bugzilla.redhat.com/show_bug.cgi?id=1942753 for RHEL 8.4

**Comment by mheon** [comment]
Please link the BZ in the commit message.

**Comment by TomSweeneyRedHat** [comment]
@mheon, pushed with the BZ noted in the commit message.

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

Restarted flaked job.

**Pull request merged**
