### PR TITLE
Vendor c/common for filters

### PR DESCRIPTION
**Pull request by rvandernoort**
Vendor common to introduce the filters from PR https://github.com/containers/common/pull/971 such that we can mege the docs update in PR https://github.com/containers/podman/pull/13607 originally from issue #13270.

Signed-off-by: rvandernoort <s.r.vandernoort@student.tudelft.nl>

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

Note that you could have also added another commit to https://github.com/containers/podman/pull/13607 which would vendor c/common.

**Comment by rvandernoort** [comment]
Ah yes ofc I could have also done that and changed the title i guess, but I thought this needed a CI check so therefore I created a new PR.

**Comment by rvandernoort** [comment]
@rhatdan I think some of the tests are failing here, because I also vendored in this commit https://github.com/containers/common/commit/83015b56e92d9f447245156d201b0976b915e336 . Do you know how we can fix this?

**Comment by rhatdan** [comment]
Add this patch
[Uploading 0002-Add-support-for-Sharable.patch.txt…]()

**Comment by rvandernoort** [comment]
Unfortuately the link seems to direct me to this PR's page?

**Comment by rhatdan** [comment]
@rvandernoort Fixed.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, test do not

**Comment by rvandernoort** [comment]
@rhatdan I applied the patch. But do we need tests for the changes or should I add no tests needed to the commit msg?

**Comment by rhatdan** [comment]
/lgtm
/hold
@rvandernoort This looks good.

**Pull request merged**
