### PR TITLE
test/apiv2: support netavark

### PR DESCRIPTION
**Pull request by Luap99**
Since netavark does not support dhcp yet we have to create a macvlan
network with a static subnet. Since we do not use the network to run
containers the actual subnet does not matter.

### CODE REVIEW

**Comment by cevich** [comment]
FWIW, when I rebased my F36 PR onto this one, I'm seeing [these annotated failures.](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6356379140096000/html/apiv2-podman-fedora-36-root-host.log.html)

**Comment by Luap99** [comment]
/hold
@cevich Thanks, some more tweaks are needed. CNI has predictable network ids (hash of the network name). With netavark they are random so we cannot hardcode them anymore.

**Comment by Luap99** [comment]
/hold cancel
@cevich Can you try again with this version?

**Comment by cevich** [comment]
Yep np.

**Comment by Luap99** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
