### PR TITLE
[v4.4] Add … push --sign-by-sigstore

### PR DESCRIPTION
**Pull request by mtrmac**
This is a backport of (as yet unmerged) #17088.

`podman push` and `podman manifest push sync` now support `--sign-by-sigstore=param-file`,
using the `containers-sigstore-signing-params.yaml(5)` file format.

That notably adds support for Fulcio and Rekor signing.

Depends on <s>unmerged</s> https://github.com/containers/image/pull/1787 ; see that PR for documentation of the YAML file format, as well as example files.

See also https://github.com/containers/common/pull/1288 for more discussion about where the interactive prompting pieces should be.

<s>Untested so far.</s>

#### Does this PR introduce a user-facing change?

```release-note
`podman push` and `podman manifest push` now support a `--sign-by-sigstore` option, which allows using Fulcio and Rekor.
```

### CODE REVIEW

**Comment by mtrmac** [comment]
@TomSweeneyRedHat @mheon @ashley-cui I’m afraid this feature didn’t get merged before cutting the 4.4 branch. I’m sorry I didn’t notice earlier.

**Comment by ashley-cui** [comment]
Adding bloat-approved for testing.

**Comment by mtrmac** [comment]
Tests passed, please merge (targeting _before_ 4.4 final)

**Comment by rhatdan** [comment]
LGTM

**Comment by mtrmac** [comment]
(Compare previous reviews are in https://github.com/containers/podman/pull/17088 )

**Comment by mheon** [comment]
Can we get #17088 in first? I'd prefer not to have a situation where the branch is more up to date than main

**Comment by mheon** [comment]
(If time becomes an issue, we can definitely merge this before release, though)

**Comment by mtrmac** [comment]
> Can we get #17088 in first? I'd prefer not to have a situation where the branch is more up to date than main

Sure, that makes sense. Both #17088 and this PR are now rebased and tests are passing.

**Comment by ashley-cui** [comment]
Gave https://github.com/containers/podman/pull/17088 a slash lgtm, going to slash lgtm this PR and hold it. Once the other PR merges, feel free to un-hold.

/lgtm
/hold

**Comment by mtrmac** [comment]
Thanks everyone!

**Pull request merged**
