### PR TITLE
Make the hello image leaner

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
[NO TESTS NEEDED]

Change from using a bash script to a c file
for running the image.  With thanks to discussions
with @afbjorklund, the Containerfile was rigged
up to make the final image be only KB's in size.

Also add USER 1000 to make the image test/run as
non-root, and update the README.md

Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@afbjorklund Thanks! and PTAL if you've a minute

**Comment by rhatdan** [comment]
LGTM, not sure what Validate is complaining about.

**Comment by TomSweeneyRedHat** [comment]
I'd a blank line at the end of the Containerfile.  Removed, should be happy now.

**Comment by jwhonce** [comment]
/hold 
Pending test results

/lgtm

**Pull request merged**
