### PR TITLE
[CI:DOCS]  Unify examples section across several man pages

### PR DESCRIPTION
**Pull request by patrycja-guzik**
This commit adjusts example sections across several man pages
to the format seen in other pages.

Signed-off-by: Patrycja Guzik <patrycja.k.guzik@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
@patrycja-guzik TYVM!  I love these types of PRs.
LGTM

**Review by vrothberg — APPROVED** [review]
LGTM
/approve

**Comment by patrycja-guzik** [comment]
Glad to help!

**Pull request merged**
