### PR TITLE
[CI:DOCS] network-create: document new bclim option

### PR DESCRIPTION
**Pull request by Luap99**
see https://github.com/containers/common/pull/1474

#### Does this PR introduce a user-facing change?

```release-note
podman network create supports a new option called `bclim` for the `macvlan` driver.
```

### CODE REVIEW

**Comment by Luap99** [comment]
Marked as draft because we need to vendor in c/common first but this seems to be still broken. https://github.com/containers/podman/pull/18510

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by Luap99** [comment]
@containers/podman-maintainers PTAL
This is good to go, the new c/common is now already vendored in.

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
