### PR TITLE
inspect, image: alias `.Config.HealthCheck` to `.HealthCheck` for compatibility

### PR DESCRIPTION
**Pull request by flouthoc**
Support inspecting image healthcheck using docker supported
`.Config.HealthCheck` by aliasing field to `.HealthCheck`

Now supports

```Console
podman image inspect -f "{{.Config.Healthcheck}}" imagename
```

Closes: https://github.com/containers/podman/issues/14661

```release-note
inspect,image: now supports filter "{{.Config.Healthcheck}}"
```

### CODE REVIEW

**Comment by flouthoc** [comment]
@vrothberg @containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
Tests aren't happy
> [+0008s] time="2022-08-23T02:59:01-05:00" level=error msg="Printing inspect output: template: all inspect:1:25: executing \"all inspect\" at <.HealthCheck.Test>: can't evaluate field HealthCheck in type interface {}"

**Comment by flouthoc** [comment]
I did it for all type as well it was only needed for `image` type lets see if CI passes now.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
