### PR TITLE
oci: use /proc/self/fd/FD to open unix socket

### PR DESCRIPTION
**Pull request by giuseppe**
instead of opening directly the UNIX socket path, grab a reference to
it through a O_PATH file descriptor and use the fixed size string
"/proc/self/fd/%d" to open the UNIX socket.  In this way it won't hit
the 108 chars length limit.

Closes: https://github.com/containers/podman/issues/8798

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Cool idea, why is it draft?

**Comment by giuseppe** [comment]
> Cool idea, why is it draft?

just to make sure it solves the reported issue before we merge

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
Change LGTM, but I'd like verification from someone actually seeing the issue.

**Comment by haircommander** [comment]
if you run rootless with a UID > like 10000 you run into this issue pretty easily.

I have tested and it fixes the issue for me:
```
 $ sudo su - hello
Last login: Tue Jan  5 16:06:21 EST 2021 on pts/0
[hello@localhost ~]$ cd ../pehunt/go/src/github.com/containers/libpod/
[hello@localhost libpod]$ ./bin/podman run --rm -ti alpine 
ERRO[0000] The storage 'driver' option must be set in /etc/containers/storage.conf, guarantee proper operation. 
ERRO[0000] The storage 'driver' option must be set in /etc/containers/storage.conf, guarantee proper operation. 
WARN[0000] Failed to add podman to systemd sandbox cgroup: dial unix /run/user/0/bus: connect: permission denied 
/ # exit
[hello@localhost libpod]$ podman run --rm -ti alpine 
Error: failed to connect to container's attach socket: /tmp/run-205013812/libpod/tmp/socket/d023d0895bce04d8b00aa33fe85f96389b2024c8c76e3c88626661e97a6f88c8/attac: dial unixpacket /tmp/run-205013812/libpod/tmp/socket/d023d0895bce04d8b00aa33fe85f96389b2024c8c76e3c88626661e97a6f88c8/attac: connect: no such file or directory
[hello@localhost libpod]$ id
uid=205013812(hello) gid=1002(hello) groups=1002(hello) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[hello@localhost libpod]$
```
where bin/podman is this fork

**Comment by rhatdan** [comment]
Ok we can merge once @giuseppe changes this to not draft and it actually passes the tests.

**Comment by giuseppe** [comment]
ready to merge!

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
