### PR TITLE
v5.0.0 release

### PR DESCRIPTION
**Pull request by lsm5**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
@Luap99 @mheon @ashley-cui @TomSweeneyRedHat @containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Review by Luap99 — COMMENTED** [review]
AFAIK @baude and @mheon wanted to sync to ensure the correct podman machine images are build before the release is published or something along the lines so we should wait for them before merging this and pushing the tag.

Changes itself LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
cokpit-revdeps is not happy though.

**Comment by Luap99** [comment]
> cokpit-revdeps is not happy though.

yeah rawhide is broken at the moment (https://github.com/containers/podman/issues/22052) but this is outside of our control so it doesn't block the release. f39/40 work so we are good.

**Comment by mheon** [comment]
Waiting until after lunch so we can get image builds going at the same time

**Comment by martinpitt** [comment]
> > cokpit-revdeps is not happy though.
> 
> yeah rawhide is broken at the moment (#22052) but this is outside of our control so it doesn't block the release. f39/40 work so we are good.

Update: With the latest [podman-5.0.0~rc7-1.fc40 ](https://bodhi.fedoraproject.org/updates/FEDORA-2024-9c9174f3dd) and [passt-0^20240319.gd35bcbe-1.fc40](https://bodhi.fedoraproject.org/updates/FEDORA-2024-3deab8ca81), user podman now also fails on F40. These aren't "visible" to dnf in normal runs yet, but I pulled them directly from koji in https://github.com/cockpit-project/cockpit-podman/pull/1636 . So you may want to hold off on these?

**Comment by Luap99** [comment]
> > > cokpit-revdeps is not happy though.
> > 
> > 
> > yeah rawhide is broken at the moment (#22052) but this is outside of our control so it doesn't block the release. f39/40 work so we are good.
> 
> Update: With the latest [podman-5.0.0~rc7-1.fc40 ](https://bodhi.fedoraproject.org/updates/FEDORA-2024-9c9174f3dd) and [passt-0^20240319.gd35bcbe-1.fc40](https://bodhi.fedoraproject.org/updates/FEDORA-2024-3deab8ca81), user podman now also fails on F40. These aren't "visible" to dnf in normal runs yet, but I pulled them directly from koji in [cockpit-project/cockpit-podman#1636](https://github.com/cockpit-project/cockpit-podman/pull/1636) . So you may want to hold off on these?

I don't think we should block on this stuff because AFAICT these are pasta bugs and must be fixed there. It is unfortunate timing for sure but we have a lot of other things that we like to get out sooner than later.

**Pull request merged**
