### PR TITLE
Add shell pipe support for "play kube"

### LINKED ISSUE #8996: "podman play kube" pipe input
/kind feature

It would be great if `podman play kube` could use input from pipe. I try to use kustomize with podman and would like to do something like `kustomize build my-overlay | podman play kube`.

### PR DESCRIPTION
**Pull request by ADIX7**
Closes #8996

Similar to `cat pod.json | kubectl apply -f -` this commit adds support
for input from shell pipe (ex `cat pod.json | podman play kube -`).
To use input form pipe one may use '-' as file name, the same way as
`kubectl apply -f -`

Signed-off-by: Ádám Kovács <kovacsadam07@outlook.hu>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks for contributing!

@containers/podman-maintainers

**Comment by TomSweeneyRedHat** [comment]
LGTM
Needs to be unset as a WIP before merging

**Comment by ADIX7** [comment]
Your welcome! The documentation and tests are still needed. I guess they should be done before merging, right?

**Comment by Luap99** [comment]
> The documentation and tests are still needed. I guess they should be done before merging, right?

Yes, please

**Review by Luap99 — COMMENTED** [review]
This does not work with `podman-remote`. You have to make a similar change in `pkg/domain/infra/tunnel/play.go`

**Comment by ADIX7** [comment]
What should be the new usage syntax? `kube [options] KUBEFILE|-` ? Or it should remain `kube [options] KUBEFILE` ?

**Comment by rhatdan** [comment]
I think we can just leave this as kube [options] KUBEFILE  and then explain in the decription that "-" can be used as a kubefile name.

**Comment by ADIX7** [comment]
I see https://github.com/containers/podman/pull/9420 went in, closing this one.

**Pull request closed without merging**
