### PR TITLE
Update sigstore/rekor after https://github.com/sigstore/rekor/pull/1469

### PR DESCRIPTION
**Pull request by mtrmac**
```sh
go get github.com/sigstore/rekor@ad288b385a44bc45d328627679988e2c99cd5e0f
make vendor
```

+218-35242 lines of code in `vendor`.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
Thanks _a lot_, @mtrmac !

Could you repush?  For some reason the GitHub UI doesn't show that the CI jobs ran.

**Comment by vrothberg** [comment]
@Luap99, this PR should make you happy :)

**Comment by rhatdan** [comment]
Nice weight loss.

**Comment by mtrmac** [comment]
I personally don’t think this is important enough to risk the force-push, but that’s of course up to you.

**Comment by vrothberg** [comment]
Let's play is safe and repush.

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by mtrmac** [comment]
```
bin/podman           size= 57464648  delta=-1357392
bin/podman-remote    size= 42050056  delta=-1712272
```
(vs. the recent https://github.com/containers/podman/pull/18496 at +715592 and +1080592 )

**Pull request merged**
