### PR TITLE
Fix progress bar for decompressGzWithSparse and vendor CopySparse 

### PR DESCRIPTION
**Pull request by l0rd**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Looks like this needs a rebase.

**Comment by l0rd** [comment]
> Looks like this needs a rebase.

Done

**Comment by baude** [comment]
LGTM but i would prefer #21508 to merge first ... it looks like it also flaked, so i'll restart that job

**Comment by l0rd** [comment]
@baude it looks like everything is green

**Pull request merged**
