### PR TITLE
Adjust some tests to work with Zstd in containers.conf

### PR DESCRIPTION
**Pull request by mtrmac**
These are immediately-applicable parts of #21571 , so that tests which require gzip compression to be used don’t rely on the `containers.conf` default.

That this does work with Zstd can be verified in #21571.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM. All build tasks are Quay flakes. Restarted

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
