### PR TITLE
Refactor python tests to run against python3.9

### PR DESCRIPTION
**Pull request by jwhonce**
* Introduce sub-package compat to meet packaging and import requirements
* Update documenation for running tests
* Add requirements.txt to improve IDE support

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
Timing comparison:

| type | distro     | user     |    local |   remote | container |
| ---- | ------     | ----     |    ----: |   -----: | --------: |
| int | fedora-33   | root     |    33:54 |    39:55 |     31:38 |
| int | ubuntu-2004 | root     |    44:44 | 01:10:12 |
| int | ubuntu-2010 | root     |    41:04 |    46:28 |
| int | fedora-33   | rootless |    34:26 |          |
| sys | fedora-33   | root     |    18:33 |    13:09 |
| sys | ubuntu-2004 | root     |    25:24 |    32:09 |
| sys | ubuntu-2010 | root     |    24:38 |    18:13 |
| sys | fedora-33   | rootless |    15:56 |          |

**Comment by edsantiago** [comment]
I extended my timing-compare script to handle system tests. Results for podman-remote tests are interesting. Boldface indicates a number that is more than 50% off from a different result. Only results over 5 seconds are listed, anything less than that is ignored. @baude @vrothberg PTAL

 |                                                                        | fedora<br/>33  | ubuntu<br/>2004  | ubuntu<br/>2010 |
 | ---------------------------------------------------------------------    | -----:    | -----:    | -----: |
 | 1 podman version emits reasonable output                               |     6.00  |  **12.00** |    11.00  |
 | 19 podman untag all                                                    |     3.00  |   **5.00** |     5.00  |
 | 20 podman run - basic tests                                            |     4.00  |     5.00  |     4.00  |
 | 24 podman run --rm                                                     |     5.00  |     5.00  |     6.00  |
 | 25 podman run --name                                                   |     6.00  |     8.00  |     7.00  |
 | 27 podman run --rmi                                                    |    11.00  |    12.00  |    12.00  |
 | 28 podman run --conmon-pidfile --cidfile                               |    10.00  |    13.00  |    11.00  |
 | 32 podman run : --userns=keep-id: passwd file is modifiable            |     4.00  |   **9.00** |     5.00  |
 | 33 podman run --log-driver                                             |     2.00  |   **5.00** |     3.00  |
 | 46 podman logs over journald                                           |     6.00  |     7.00  |     6.00  |
 | 47 podman ps - basic tests                                             |     2.00  |   **7.00** |     4.00  |
 | 48 podman ps --filter                                                  |     6.00  |     8.00  |     7.00  |
 | 49 podman ps -a --external                                             |    12.00  |    12.00  |    11.00  |
 | 50 podman stop - basic test                                            |     5.00  |   **9.00** |     6.00  |
 | 52 podman stop --ignore                                                |     5.00  |   **9.00** |     6.00  |
 | 55 podman rm                                                           |     6.00  |     7.00  |     6.00  |
 | 56 podman rm - running container, w/o and w/ force                     |    12.00  |    13.00  |    12.00  |
 | 58 podman rm <-> run --rm race                                         |    14.00  |    15.00  |    14.00  |
 | 59 podman rm -f                                                        |    14.00  |    21.00  |    16.00  |
 | 63 podman run --mount image inspection                                 |    20.00  |  **77.00** |  **26.00** |
 | 65 podman cp file from host to container                               |    15.00  |  **95.00** |  **25.00** |
 | 66 podman cp file from container to host                               |    17.00  |  **142.00** |  **35.00** |
 | 67 podman cp dir from host to container                                |    14.00  |  **107.00** |  **28.00** |
 | 68 podman cp dir from container to host                                |     1.00  |  **34.00** |   **6.00** |
 | 69 podman cp file from host to container volume                        |     2.00  |  **29.00** |   **6.00** |
 | 70 podman cp file from host to container mount                         |     1.00  |  **18.00** |   **5.00** |
 | 71 podman cp * - wildcard copy multiple files from container to host   |     1.00  |  **14.00** |   **5.00** |
 | 72 podman cp - will not recognize symlink pointing into host space     |     1.00  |  **13.00** |   **4.00** |
 | 73 podman cp - will not expand globs in host space (#3829)             |     1.00  |  **13.00** |   **5.00** |
 | 74 podman cp - will not expand wildcard                                |     3.00  |  **28.00** |  **13.00** |
 | 75 podman cp into container: weird symlink expansion                   |     3.00  |  **22.00** |   **8.00** |
 | 76 podman cp into a subdirectory matching GraphRoot                    |    13.00  |  **41.00** |    24.00  |
 | 77 podman cp from stdin to container                                   |    12.00  |  **38.00** |    21.00  |
 | 78 podman cp from container to stdout                                  |     5.00  |  **35.00** |  **15.00** |
 | 79 podman build - basic test                                           |     5.00  |  **36.00** |  **15.00** |
 | 82 podman build - cache (#3920)                                        |     2.00  |  **15.00** |   **6.00** |
 | 83 podman build - URLs                                                 |    17.00  |  **129.00** |  **58.00** |
 | 84 podman build - workdir, cmd, env, label                             |     4.00  |  **17.00** |    14.00  |
 | 85 podman build - stdin test                                           |     2.00  |   **7.00** |     7.00  |
 | 86 podman build - does not gobble stdin that does not belong to it     |     6.00  |  **13.00** |    16.00  |
 | 87 podman build --layers test                                          |    12.00  |    18.00  |    21.00  |
 | 90 podman exec - basic test                                            |     3.00  |     4.00  |     5.00  |
 | 93 podman exec - with keep-id                                          |    16.00  |    18.00  |    19.00  |
 | 98 podman save to pipe and load                                        |     2.00  |   **5.00** |     6.00  |
 | 99 podman load - by image ID                                           |     3.00  |   **6.00** |     6.00  |
 | 100 podman load - by image name                                        |     4.00  |   **9.00** |     8.00  |
 | 102 podman load - multi-image archive                                  |     4.00  |   **8.00** |     7.00  |
 | 103 podman load - multi-image archive with redirect                    |     9.00  |    12.00  |    11.00  |
 | 104 podman kill - test signal handling in containers                   |     2.00  |   **6.00** |     6.00  |
 | 106 podman diff                                                        |     4.00  |     5.00  |     4.00  |
 | 107 podman diff with buildah container                                 |     3.00  |   **9.00** |     9.00  |
 | 119 podman volume create / run                                         |     2.00  |   **5.00** |     5.00  |
 | 120 podman volume: exec/noexec                                         |     4.00  |   **7.00** |     6.00  |
 | 121 podman volume, implicit creation with run                          |     3.00  |   **8.00** |     8.00  |
 | 124 podman pod top - containers in different PID namespaces            |     3.00  |   **8.00** |     7.00  |
 | 125 podman pod - communicating between pods                            |     2.00  |   **6.00** |     6.00  |
 | 126 podman pod - communicating via /dev/shm                            |    18.00  |    24.00  |    23.00  |
 | 127 podman pod create - hashtag AllTheOptions                          |     5.00  |     7.00  |     6.00  |
 | 134 podman system df - basic functionality                             |     3.00  |   **5.00** |     5.00  |
 | 135 podman system df - with active containers and volumes              |     1.00  |  **27.00** |    16.00  |
 | 144 podman selinux: shared context in (some) namespaces                |    11.00  |   **0.00** |     0.00  |
 | 150 podman networking: port with --userns=keep-id                      |    66.00  |  **204.00** |   143.00  |
 | 153 podman shell completion test                                       |    13.00  |    16.00  |    14.00  |
 | 154 podman play with stdin                                             |    13.00  |    16.00  |    14.00  |

**Pull request merged**
