### PR TITLE
[3.2] vendor containers/common@v0.38.13

### PR DESCRIPTION
**Pull request by vrothberg**
* libimage: events: deferred write

Fixes: bugzilla.redhat.com/show_bug.cgi?id=1977673
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL.  We can merge without ACK at this point.  Just need a BZ for tracking.

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
FYI @jnovy

**Pull request merged**
