### PR TITLE
feat: Change host from meaningless 'd' to given hostname from --url parameter when using tcp scheme

### PR DESCRIPTION
**Pull request by takutakahashi**
### Background

A request to podman REST API is used character 'd' as a hostname.
When it will add it from --url parameter dynamically, we will be able to handle request via host header.
For example, we can use nginx as a reverse proxy and use host header as consistent hashing seed.

### Question

I can't find some of test code for `pkg/bindings/connection.go` .
Which should I add test for this changes?

Thanks.

### CODE REVIEW

**Comment by mheon** [comment]
@jwhonce @baude PTAL

**Comment by jwhonce** [comment]
@takutakahashi "d" was used as the host name since it is a placeholder. The name is never resolved and connections via the ssh tunnel never expose the name. For this change to be made, all API tests that do not use tcp:// will need to be updated.

**Comment by baude** [comment]
exactly what @jwhonce said, it could be `foorbar` or `podman` and the behavior would not different.  This is true for similar RESTfull APIs including docker.

**Comment by takutakahashi** [comment]
@jwhonce 
I understood as you say that tcp:// url will not be affected with that changes and need to check the compatibility of other protocol (ex: ssh:// ).
I'm going to mod some of tests that does not tcp:// .

**Comment by takutakahashi** [comment]
I couldn’t work for this PR.
I’m very sorry to close it.

**Pull request closed without merging**
