### PR TITLE
[CI:DOCS] Remove experimental warning from podman-remote rpm

### PR DESCRIPTION
**Pull request by Luap99**
podman-remote is considered stable and follows the same semver as
podman.

Fixes a question on the podman mailing list.
https://lists.podman.io/archives/list/podman@lists.podman.io/thread/2DVCU5Z54U4PI5ROTBQXHDBLQSAXAHFU/

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM.

**Review by vrothberg — COMMENTED** [review]
/lgtm
/hold

FWIW, I find the following paragraph also confusing: "version 2 API" seems ambiguous when using Podman 4.  Shall we rephrase to `libpod REST API`?

**Comment by Luap99** [comment]
> FWIW, I find the following paragraph also confusing: "version 2 API" seems ambiguous when using Podman 4. Shall we rephrase to `libpod REST API`?

Good idea, done

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
