### PR TITLE
e2e tmpdir cleanup

### PR DESCRIPTION
**Pull request by edsantiago**
My initial goal was to allow caching the e2e images in a directory other than /tmp.
In the process of doing so I discovered some very confusing and/or unnecessary code.
I took the liberty of cleaning it up.

These are three separate easily-reviewed commits, I recommend reviewing each separately:

- Rename CrioRoot as just Root
- Image caches: allow overriding cache dir
- remove ARTIFACT_DIR and ArtifactPath

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
BTW CRIO is just because Podman came out of the original CRIO effort as kpod, and we stole CRIO test suite and never changed the name.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, now to get the test happy.

**Comment by edsantiago** [comment]
It's just #9597, one of our most popular flakes

**Pull request merged**
