### PR TITLE
Backports for v3.2.0-RC3

### PR DESCRIPTION
**Pull request by mheon**
Backports and release notes updates for v3.2.0-RC3

### CODE REVIEW

**Comment by Luap99** [comment]
@mheon If you have to repush, could you add #10408 please.

**Comment by mheon** [comment]
@Luap99 Don't think it will make this RC but I can definitely get it in the final 3.2.0 release

**Comment by rhatdan** [comment]
And we are stuck on the flake from hell.

**Comment by mheon** [comment]
Restarted again

**Comment by mheon** [comment]
On restart 5 of the flaked test.

**Pull request merged**
