### PR TITLE
Cirrus: Bump Fedora to release 35

### PR DESCRIPTION
**Pull request by cevich**
#### What this PR does / why we need it:

Update the "Fedora" VM used in testing to version `35` (beta), and the "Prior Fedora" version to `34`.  Stop testing with Fedora `33`.  Also resolve a `TODO` in setup - the needed packages are now bundled into the images.

***NOTE:*** The Fedora 35 image is now based on a BTRFS root filesystem.

#### How to verify it

CI will pass

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Depends on: #11955 and #11979 and ##12110 and #12121 or #12120 and #12060 and #12162 and #12342 and #12343 and https://github.com/containers/automation_images/pull/93

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by cevich** [comment]
Sorry, forgot to mark this as WIP/Draft.  There are some major challenges that need solving: Namely the kernel shouldn't panic when compiling podman :cry:

**Comment by cevich** [comment]
@lsm5 [I'm getting test-rpm build errors on the new F35 VM.](https://cirrus-ci.com/task/5781764963565568?logs=main#L361-L371)  Do you know how to fix these?

**Comment by cevich** [comment]
[For `int podman fedora-35` root and rootless](https://cirrus-ci.com/task/6415083661164544), the tests are hanging.  Both appear to be [getting stuck on a `checkpoint` test (log)](https://api.cirrus-ci.com/v1/artifact/task/5992871196098560/ginkgo_node_logs/test/e2e/ginkgo-node-3.log).

**Comment by cevich** [comment]
@adrianreber ping - any insights on the checkpoint hang?

**Comment by adrianreber** [comment]
> @adrianreber ping - any insights on the checkpoint hang?

rootless tests should not run any checkpoint tests at all. The root test hangs while trying to establish a TCP connection to the container. I can run it locally on f35 tomorrow to see if I can reproduce it.

Not sure why it should hang with f35 right now:
```
                // Open a network connection to the redis server via initial port mapping
                conn, err := net.Dial("tcp", "localhost:1234")
                if err != nil {
                        os.Exit(1)
                }
                conn.Close()
```

Most checkpoint tests seem to be running. Just as an FYI, if all checkpoint tests start to fail: CRIU needs something like `chattr +C /var/lib/containers` to work with BTRFS.

**Comment by cevich** [comment]
> CRIU needs something like chattr +C /var/lib/containers to work with BTRFS.

BTRFS will be the stock/default for F35 VMs, so should we preemptively change that at the packaging level?  Or is that just a caution / might happen warning?

**Comment by lsm5** [comment]
> @lsm5 [I'm getting test-rpm build errors on the new F35 VM.](https://cirrus-ci.com/task/5781764963565568?logs=main#L361-L371) Do you know how to fix these?

disable debuginfo in specfile, set `%global debug_package %{nil}` .

**Comment by adrianreber** [comment]
> > CRIU needs something like chattr +C /var/lib/containers to work with BTRFS.
> 
> BTRFS will be the stock/default for F35 VMs, so should we preemptively change that at the packaging level?  Or is that just a caution / might happen warning?

Just that it might happen. If it works without the chattr, you can leave it as it is.

**Comment by Luap99** [comment]
> disable debuginfo in specfile, set `%global debug_package %{nil}` . I thought this was disabled already in a prior PR from @Luap99 . But maybe not?

My PR is not merged yet (#11565).

**Comment by cevich** [comment]
Okay great, thanks @lsm5 and @Luap99, and no rush merging that, there are plenty of other issues to address in this PR in the meantime.

**Comment by cevich** [comment]
Darn.

**Comment by adrianreber** [comment]
> @adrianreber I[ instrumented the test with a bunch of `fmt.Printf()`](https://github.com/containers/podman/commit/9744f900217bcdaffcc5ecdd40a60351e49de078#diff-e9325abde05ad8a2d00b6073f229cb4d2599abdf6965e03721f9c6ea216380a2R950) and ran it manually. It seems to be hanging on the `conn, err := net.Dial("tcp", "localhost:1234")`. Should that be wrapped in some kind of timeout, and shouldn't it be connecting to port `6379`?

The timeout would be a good idea. The port is correct with 1234 because that test is trying to handle different port mappings after restore. I am confused, however, I do not see the broken test being run. There is still a timeout but I am also not sure why.

Can you also try a change like this (in addition to your timeout change):
```
                conn, err := net.Dial("tcp", "localhost:1234")
-               if err != nil {
-                       os.Exit(1)
-               }
+               Expect(err).To(BeNil())
```
The `Exit(1)` is probably a bad idea anyway. I also had a look at the audit log but it does not seem to be a SELinux denial.

**Comment by adrianreber** [comment]
> @adrianreber as is the nature of these things, fixing the hang seems to have revealed [another one in `podman checkpoint container with established tcp connections` (useless log)](https://api.cirrus-ci.com/v1/artifact/task/5956019621724160/ginkgo_node_logs/test/e2e/ginkgo-node-1.log). I'll poke around and see if I can duct-tape a similar fix in with my white-belt golang kung-fu. But I'm not hopeful. Let me know if you need a VM to debug.

This test probably needs the same fix. Wait for container to be ready and use random port numbers.

**Comment by cevich** [comment]
Ref: [Historical Logs](https://cirrus-ci.com/build/5579852192415744)

**Comment by cevich** [comment]
> Do we have information about how long the test is taking to run?

Possibly/probably.  Are you looking for overall runtime or specific tests? (sorry, I'm a scatter-brain - I can't keep track of what problem/context we're talking about)

**Comment by nalind** [comment]
> > Do we have information about how long the test is taking to run?
> 
> Possibly/probably. Are you looking for overall runtime or specific tests? (sorry, I'm a scatter-brain - I can't keep track of what problem/context we're talking about)

The specific journal-related tests that are failing.  We try to obtain a cursor, and if we fail to do so, we wait 100ms and try again, twice.  If it's a matter of needing to wait longer so that a test running in CI will be able to succeed there, that's easy.  Anything else would require more debugging.

**Comment by cevich** [comment]
.. @nalind this issue readily reproduces so I opened https://github.com/containers/podman/issues/12029

Timing does not matter, there was maybe 3-minutes between commands listed in that issue (as I read, and copy-pasted parts of them from the logs).

**Comment by mtrmac** [comment]
@cevich From a quick skim the `podman image trust show --json` and `podman image trust show --raw` tests, which verify form of the output, assume what the surrounding environment (`/etc/containers/policy.json`) is (unless there are some environment overrides I’m not aware of; I can’t find anything of that kind).

Did the default contents of `/etc/containers/policy.json` change between F34 to F35 to add `registry.redhat.io` and `r.a.rh.com` policies enforcing signatures? If not, I’d need to dig in deeper.

If this is explained by the distribution default config changing, there are about three ways to handle it:
- Update the tests to expect the new system-wide default policy contents (but the tests would start failing on other systems / versions)
- Modify the system-wide OS configuration to have a specific `policy.json` content, e.g. the old one (or better, the new one and update the tests, which gets us more coverage); probably not something tests should require
- Almost certainly the best option: modify the tests to be similar to the `podman image trust show` test above, which passes a `--policypath` option pointing to a test-specific policy file with fixed contents, instead of making assumptions about the surrounding environment. (A quick fix: Make that file with F34-like contents. A better fix: Make that file with more complex contents, closer to F35, and adjust expected output to match that. E.g. the existing `https://github.com/containers/podman/blob/3c1d9910afaee21050ecbf058b5eddffc74c7abe/test/policy.json` is a pretty good example policy, and using that for all the `podman image trust show` tests would be elegantly consistent.)

**Comment by cevich** [comment]
> Did the default contents of /etc/containers/policy.json change between F34 to F35

I believe this default file would have come from [containers-common-1-32.fc35-noarch (log)](https://cirrus-ci.com/task/6614426968129536?logs=package_versions#L6).  I looked, and didn't see any place where we replace this file at runtime (unless that test/suite does it - I didn't look).

> If this is explained by the distribution default config changing, there are about three ways to handle it:
>
> * Update the tests to expect the new system-wide default policy contents (but the tests would start failing on other systems / versions)

Damn.

> * Modify the system-wide OS configuration to have a specific policy.json content, e.g. the old one (or better, the new one and update the tests, which gets us more coverage); probably not something tests should require

This would decouple podman testing from what users actually see (since we install the distro's containers-common package).

> Almost certainly the best option: modify the tests to be similar to the podman image trust show test above, which passes a --policypath option pointing to a test-specific policy file with fixed contents, instead of making assumptions about the surrounding environment. (A quick fix: Make that file with F34-like contents. A better fix: Make that file with more complex contents, closer to F35, and adjust expected output to match that. E.g. the existing https://github.com/containers/podman/blob/3c1d9910afaee21050ecbf058b5eddffc74c7abe/test/policy.json is a pretty good example policy, and using that for all the podman image trust show tests would be elegantly consistent.)

I agree this is probably the best option.  For reference, I've attached the F35 policy.json file copied from a CI VM.
[policy.json.txt](https://github.com/containers/podman/files/7391020/policy.json.txt)

If this fix will take a while to implement, I'm okay with opening an issue on it and marking the tests to skip, temporarily.

**Comment by mtrmac** [comment]
> > To be explicit, would you prefer for me (or someone else) to work on updating the tests?
> 
> Yes please

Something vaguely like the new commits in #12060 — note that that code is absolutely untested at this point, the CI run will be the first run ever. I’ll continue working on that, for now just recording this to have a pointer.

**Comment by cevich** [comment]
[Example log of Test Bindings hanging](https://cirrus-ci.com/task/4627523322511360?logs=main#L253) when trying to start a container

@jwhonce (reminder/I know you're feeling unwell) Have you had a chance to peek at this?

**Comment by edsantiago** [comment]
Fix for the hang is:
```diff
diff --git a/pkg/bindings/test/common_test.go b/pkg/bindings/test/common_test.go
index d996595bf..233666a48 100644
--- a/pkg/bindings/test/common_test.go
+++ b/pkg/bindings/test/common_test.go
@@ -151,7 +151,7 @@ func createTempDirInTempDir() (string, error) {
 }

 func (b *bindingTest) startAPIService() *gexec.Session {
-       cmd := []string{"--log-level=debug", "--events-backend=file", "system", "service", "--timeout=0", b.sock}
+       cmd := []string{"--log-level=debug", "system", "service", "--timeout=0", b.sock}
        session := b.runPodman(cmd)

        sock := strings.TrimPrefix(b.sock, "unix://")
```
I'm pretty upset at having wasted so much time on this. Something somewhere is not doing proper error checking, because podman is very clearly failing but this failure is not being caught:
```
time="2021-11-03T18:28:15-04:00" level=info msg="Request Failed(Internal Server Error): failed to obtain logs for Container '04e6c2bacbe6c275776c3fc93ed8de553cec02914f5eb6840b173141a50ff8a3': using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported"
```
I'm also pretty upset at this new journald/file change that seems to be causing a lot of breakage everywhere. But I will call it a day now, and come back to revisit this in the morning.

**Comment by edsantiago** [comment]
And, may I suggest this change, to make it possible to see which tests are running and where things are hanging?
```diff
diff --git a/contrib/cirrus/runner.sh b/contrib/cirrus/runner.sh
index 8ef2a6e64..501e42208 100755
--- a/contrib/cirrus/runner.sh
+++ b/contrib/cirrus/runner.sh
@@ -84,7 +84,7 @@ function _run_bindings() {

     # Subshell needed so logformatter will write output in cwd; if it runs in
     # the subdir, .cirrus.yml will not find the html'ized log
-    (cd pkg/bindings/test && ginkgo -trace -noColor -debug  -r) |& logformatter
+    (cd pkg/bindings/test && ginkgo -trace -noColor -debug  -r -v) |& logformatter
 }

 function _run_docker-py() {
```

**Comment by cevich** [comment]
@edsantiago thank you so much for taking the time to hunt that down, that sounds really tricky!  Yes, it's sooo frustrating when you dig and dig and dig through all the muck, only to find out less "basic human laziness" could have saved most of of effort.  And yes I've seen by this PR, many new logging/output related bumbles.  

> And, may I suggest this change

Of course that's no trouble at all, why I/we/someone didn't think of that earlier...

**Comment by cevich** [comment]
...both suggestions applied.

**Comment by cevich** [comment]
Status:  This PR is getting really close to being complete now.  I've identified one instability problem recently that needs addressing (via new VM images) relating to a random failure to expand the root filesystem on boot.

**Comment by cevich** [comment]
[Re-running `int podman fedora-35 rootless host` again](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6026833767432192/html/int-podman-fedora-35-rootless-host.log.html#t--podman-run-with-cgroups-split--1), seeing "new" failures of `podman run with cgroups=split`:

```
[+0851s] Running: systemd-run --scope --user /var/tmp/go/src/github.com/containers/podman/bin/podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/podman_test076439696/crio --runroot /tmp/podman_test076439696/crio-run --runtime crun --conmon /usr/bin/conmon --cni-config-dir /home/some30150dude/.config/cni/net.d --cgroup-manager systemd --tmpdir /tmp/podman_test076439696 --events-backend file --storage-driver vfs run --rm --cgroups=split quay.io/libpod/alpine:latest cat /proc/self/cgroup
[+0851s] Job failed. See "journalctl -xe" for details.
[+0851s] output: 
[+0851s] [AfterEach] Podman run
```

Sorry for a shotgun-mention, @edsantiago @giuseppe @mheon @rhatdan this is "brand-new" (as in wasn't failing like this two days ago).  It also appears to be very bad.  Searching the journal for `podman_test076439696` finds this:

```
Nov 11 14:16:17 cirrus-task-6026833767432192 systemd[4466]: podman-84481.scope: Failed with result 'resources'.
Nov 11 14:16:17 cirrus-task-6026833767432192 systemd[4466]: Failed to start podman-84481.scope.
Nov 11 14:16:18 cirrus-task-6026833767432192 systemd[4466]: run-rcdfd55d6809d4984a35e71b8b9e26018.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 11 14:16:18 cirrus-task-6026833767432192 systemd[4466]: run-rcdfd55d6809d4984a35e71b8b9e26018.scope: Failed with result 'resources'.
Nov 11 14:16:18 cirrus-task-6026833767432192 systemd[4466]: Failed to start /var/tmp/go/src/github.com/containers/podman/bin/podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/podman_test076439696/crio --runroot /tmp/podman_test076439696/crio-run --runtime crun --conmon /usr/bin/conmon --cni-config-dir /home/some30150dude/.config/cni/net.d --cgroup-manager systemd --tmpdir /tmp/podman_test076439696 --events-backend file --storage-driver vfs run --rm --cgroups=split quay.io/libpod/alpine:latest cat /proc/self/cgroup.
Nov 11 14:16:18 cirrus-task-6026833767432192 systemd[4466]: podman-84508.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 11 14:16:18 cirrus-task-6026833767432192 systemd[4466]: podman-84508.scope: Failed with result 'resources'.
Nov 11 14:16:18 cirrus-task-6026833767432192 systemd[4466]: Failed to start podman-84508.scope.
Nov 11 14:16:18 cirrus-task-6026833767432192 systemd[4466]: podman-84511.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 11 14:16:18 cirrus-task-6026833767432192 systemd[4466]: podman-84511.scope: Failed with result 'resources'.
Nov 11 14:16:18 cirrus-task-6026833767432192 systemd[4466]: Failed to start podman-84511.scope.
```

That `No PIDs left to attach to the scope's control group, refusing: Success` message is all throughout the journal, up and down.  Are we running out of FDs or something really bad like that?  Any idea what might be going wrong?

This F35 VM is running:

```
Fedora release 35 (Thirty Five)
Kernel:  5.14.17-301.fc35.x86_64
Cgroups:  cgroup2fs
conmon-2.0.30-2.fc35-x86_64
containernetworking-plugins-1.0.1-1.fc35-x86_64
containers-common-1-32.fc35-noarch
container-selinux-2.170.0-2.fc35-noarch
criu-3.16.1-2.fc35-x86_64
crun-1.3-1.fc35-x86_64
golang-1.16.8-2.fc35-x86_64
libseccomp-2.5.3-1.fc35-x86_64
podman-3.4.1-1.fc35-x86_64
runc-1.0.2-2.fc35-x86_64
skopeo-1.5.1-1.fc35-x86_64
slirp4netns-1.1.12-2.fc35-x86_64
```

**Comment by cevich** [comment]
I didn't see any recent commits that appear to address this, but attempting a rebase anyway [and to bring in the Ubuntu update].

**Comment by edsantiago** [comment]
This is slightly, but not entirely, reminiscent of #9752. I wonder if "No PIDs left" is a newfangled way of saying "the requested cgroup controller 'pids' is not available"?

**Comment by cevich** [comment]
Interesting thought, it seems plausible.  If true and causing `podman run with cgroups=split` to fail, the good news is now it's 100% reproducible with these images in F35.

**Comment by cevich** [comment]
Rebased to include #12218

**Comment by edsantiago** [comment]
Flake is #12306, restarting.

**Comment by edsantiago** [comment]
Flake is #9597, restarting.

**Comment by edsantiago** [comment]
Tests are green. I'm uncomfortable with how many flakes we're seeing in f35, flakes that we thought were fixed... but more flakes means more incentives for everyone to fix them. PR LGTM.

**Comment by TomSweeneyRedHat** [comment]
LGTM
once that last test passes.

**Comment by edsantiago** [comment]
Flake is #12065 (again) (I was mistaken in my earlier attribution to 9597. There are so many flakes here that I can't keep them straight).

**Comment by cevich** [comment]
Well :hankey: thanks for trying.

**Comment by edsantiago** [comment]
@cevich please rebase and try again, I sent you email about it hours ago

**Comment by cevich** [comment]
You did? Hmmm, I don't see it for some reason.  Oh, maybe it got filtered into my hoard of messages from github.  Anyway, rebasing...

**Comment by edsantiago** [comment]
@vrothberg, are you still around? [test failures](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5825307493007360/html/int-remote-fedora-34-root-host.log.html) are all in podman-remote checkpoint, which look kind of alarming given the recent commit of #12281

**Comment by edsantiago** [comment]
Test failure looks real; filed #12334.

**Comment by cevich** [comment]
Thanks for all the help @edsantiago - Another thing to consider is...these current VM images I built last week, it's possible they have some outdated dependencies causing issues vs podman compiled from source.  I'll start an image rebuild just in case (and also to pick up the new Ubuntu `catatonit 0.1.7` Lokesh built for us).

**Comment by cevich** [comment]
Rebased + added commit to undo the catatonit `--force` install.  Also removed commit eed1d6b03 as #12304 reportedly is fixed by the newer systemd.

**Comment by edsantiago** [comment]
Speaking of `fedora-minimal:latest`, looks like the most recent one (de6653dd060f) [no longer includes useradd](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4788205296812032/html/int-podman-fedora-35-root-container.log.html#t--podman-exec-with-user-only-in-container--1)

**Comment by cevich** [comment]
> Speaking of fedora-minimal:latest, looks like the most recent one (de6653dd060f) no longer includes useradd

Lovely.  Though we can deal with that in our `Dockerfile` (maybe?).

We have a `test/e2e/config.go` that the majority/all tests use to reference images.  I modified the quay builder to tag images based on the branch they came from.  So the trick then is, can we get `config.go` to use the compile-time `$CIRRUS_BRANCH` value for the tag.  That will make (for example) the release branches much more stable, since they're not using an ever-changing `latest` image.  I'm sure something similar can be done for the system-tests, if required.

**Comment by edsantiago** [comment]
I vote for completely eliminating the entire autobuild concept.

**Comment by cevich** [comment]
> I vote for completely eliminating the entire autobuild concept.

Yep, it's been done.  This image was a vestige of the past, (clearly) easy to overlook and neglect.  I think we have a good (and simple) plan in vrothberg's PR.

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/12342 should fix the checkpoint farts

**Comment by edsantiago** [comment]
Some of the flakes are the usual search-registry ones; others need a rebase on top of #12342 as mentioned by @vrothberg; but there's [one new one](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5009013457813504/html/int-remote-fedora-34-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes--1):
```
Running: podman-remote [options] exec 4aafbb38b394ca777d9dbc771d2b4499268046dcf9fc370b453a3bf2ed77bbcd cat /test.output
time="2021-11-18T11:06:24-06:00" level=error msg="error attaching to container 4aafbb38b394ca777d9dbc771d2b4499268046dcf9fc370b453a3bf2ed77bbcd exec session e3ebd3e10b7f88e717542d8e77439ff27b9569b520bc9d1801ff78d12b07663e: dial unixpacket /proc/self/fd/20: connect: permission denied"
Error: dial unixpacket /proc/self/fd/20: connect: permission denied
```
I see no point in restarting.

**Comment by cevich** [comment]
Thanks for the help @vrothberg I appreciate your taking the initiative.

---

Note: I'm re-running the failed F34 tests to verify the 'podman search' failures are flakes.

**Comment by edsantiago** [comment]
They're flakes. One of the common ones. Every so often registry.redhat.io goes into a mode where it demands a login even for search. It's usually fixed in a few hours.

**Comment by cevich** [comment]
> They're flakes. One of the common ones. Every so often registry.redhat.io goes into a mode where it demands a login even for search. It's usually fixed in a few hours.

Yeah I've seen that before too, and guessed it's what we were seeing.  Thanks for confirming.

Hey, on that topic: What's your opinion on me adding a check to the `Ext. services` task (runs very early), to verify this? It would save people wasting time re-running due to a known issue we literally can't do anything about (AFAIK).  I'm on the fence about it vs getting "some" useful testing completed.

**Comment by edsantiago** [comment]
Well, it doesn't fit into the host/port model, so some hackery would be needed to try "podman search", which gets us into chicken/egg territory.

Thinking on it some more, though, I rarely see all `int` tests failing because of this. It's more typical to see just one or two. I don't know what that means about the nature of the flake, but from the perspective of CI, I think an early check would not be accurate enough: it could easily false-negative as well as false-positive.

**Comment by cevich** [comment]
Y'okay! Rebased/force-pushed "once last time" (note: this may not be the *real* "last time") :grin:

**Comment by vrothberg** [comment]
Fingers crossed :crossed_fingers: Thanks for your patience and your long breath pushing this forward, @cevich !

**Comment by cevich** [comment]
> Thanks for your patience and your long breath pushing this forward

I absolutely could not have done this without the support from...basically everybody.  So thank YOU!

I pray we never have to upgrade any OS, ever again...or at least for another 6 months :sob: 

Seriously though, I've been wondering recently if all these fresh-new gray-hairs are worth it:  Concentrating all the pain into one PR for the stability of all/most other PRs.  Or maybe we should just run with rawhide and continuous runtime updates to share the instability "love" to every PR - but with rapid "fixes" available (in theory).

Seems to me, no matter how we do CI...everyone still always hates it :laughing:

**Comment by cevich** [comment]
Ugh, two Ubuntu failures.  Naively assuming they're flakes and re-running.

**Comment by edsantiago** [comment]
/lgtm
/hold

Quick, before CI changes its mind! (Tests are green as of the moment I'm writing this. I would not be in the least bit surprised if they turn red somehow in the next few minutes, just out of orneriness).

**Comment by cevich** [comment]
> just out of orneriness

They are imbibed with the pure essence nature of "ornery" and will require every magic spell to be set right :disappointed:

**Pull request merged**
