### PR TITLE
Revert "Refactor common options in man pages"

### PR DESCRIPTION
**Pull request by vrothberg**
This reverts commit 56039cffd7923d682bd620e5a5a974aabc94dd1b as it does
not pass the OSX Cross job in CI [1].

[1] https://github.com/containers/podman/pull/15175/checks?check_run_id=7666443981

Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by gbraad — APPROVED** [review]
/lgtm

**Comment by vrothberg** [comment]
If https://github.com/containers/podman/pull/15188/files works, we can close this PR here.

**Comment by Luap99** [comment]
lets wait if https://github.com/containers/podman/pull/15188 works before merging

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/15188 works, so I am closing this PR here.

**Pull request closed without merging**
