### PR TITLE
generate systemd: drop ExecStop

### PR DESCRIPTION
**Pull request by vrothberg**
Drop the ExecStop step to simplify the generated units a bit.

The extra ExecStopPost step was added by commit e5c343294424. If the main PID (i.e., conmon) is killed, systemd will not execute ExecStop (since the main PID is already down) but only execute the *Post steps. Credits to the late Ulrich Obergfell for tracking this issue down; he is missed.

The ExecStop step can safely be dropped since the Post step will take care of stopping (and removing) in any case.

Context: #15686
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Simplify the systemd units generated via `podman generate systemd` by dropping the redundant `ExecStop` step.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
Isn't the problem with this that systemd is not using the correct stop signal when something other then SIGTERM is configured for the container?

**Comment by Luap99** [comment]
I am looking at https://github.com/containers/podman/pull/11315, we tried this before and it failed. Is something different here, do I miss something?

**Comment by vrothberg** [comment]
The `ExecStopPost` is still there which we seemed to have dropped before https://github.com/containers/podman/pull/11315

**Comment by Luap99** [comment]
But the main problem was that systemd does not consider the unit successfully stopped which seems to cause problems for users: #11304

Also if the user sets a specific stop signal they likely do not want their application to get SIGTERM from systemd.

Note: I am not saying this change won't work but it likely causes problems for containers using custom stop signals.

**Comment by vrothberg** [comment]
Isn't systemd jumping directly to ExecStopPost in the absence of ExecStop?

**Comment by vrothberg** [comment]
> Isn't systemd jumping directly to ExecStopPost in the absence of ExecStop?

In case it doesn't, we need to revert this PR.

**Comment by Luap99** [comment]
> Isn't systemd jumping directly to ExecStopPost in the absence of ExecStop?

I am not 100% but I interpret the docs that it will try to stop via signal before runing post commands:

> Additional commands that are executed after the service is stopped. This includes cases where the commands configured in ExecStop= were used, where the service does not have any ExecStop= defined, or where the service exited unexpectedly. This argument takes multiple command lines, following the same scheme as described for ExecStart=. Use of these settings is optional. Specifier and environment variable substitution is supported. Note that – unlike ExecStop= – commands specified with this setting are invoked when a service failed to start up correctly and is shut down again.

From systemd.service(5)

Unfortunately I do not have time right now to test this behaviour

**Comment by vrothberg** [comment]
> If this option is not specified, the process is terminated by sending the signal specified in KillSignal= or RestartKillSignal= when service stop is requested.

From the man pages. Thanks for spotting this, @Luap99. I feel more comfortable reverting this PR in this case.  We could add `KillSignal=` but I feel more comfortable letting Podman take care of that.

**Pull request merged**
