### PR TITLE
[CI:DOCS] github: label issues based on os fix regex

### PR DESCRIPTION
**Pull request by Luap99**
Good news the github action works, however I noticed that we cannot use
a multiline regex so we have to use serviceIsRemote to detect if this is
a remote client. Also change the os regex so that it matches both the
output of podman version and podman info.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
@cevich ?

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by cevich** [comment]
LGTM (FWIW)

**Pull request merged**
