### PR TITLE
[CI:DOCS] Quadlet - add note about relative path resolution

### PR DESCRIPTION
**Pull request by ygalblum**
#### Does this PR introduce a user-facing change?
No

```release-note
None
```
Resolves: #19125

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by Luap99** [comment]
@ygalblum Please rebase, the rawhide validate problem should be fixed on main

**Review by Luap99 — COMMENTED** [review]
/lgtm

**Pull request merged**
