### PR TITLE
[CI:DOCS] Implement secrets/credential scanning

### PR DESCRIPTION
**Pull request by cevich**
As an effort to catch potential secrets and/or credential leaks, add a github-actions workflow which is untouchable in a PR context. To additionally guard against accidents, also check recent branch history.  This is especially important on newly created release-branches, which may begin with content from who-knows-where.

Finally, since the new workflow bypasses PR-level changes to the scanner config and base-line.  Add a Cirrus-CI invocation of the scanning tool to help catch tool-breaking changes from being merged.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
**TODO:** I'm wondering if I should add an "escape-hatch" where the check (or maybe just the e-mail alert) is bypassed in a PR when a certain label is set.  Mainly to prevent spam.

**Comment by cevich** [comment]
This is ready for initial review.

**Comment by rhatdan** [comment]
LGTM

**Review by flouthoc — COMMENTED** [review]
There are bunch of `CirrusCI` warning in changes are they relevant ?

**Comment by flouthoc** [comment]
See: https://github.com/containers/podman/pull/20136/checks?check_run_id=17155277272

**Comment by cevich** [comment]
> There are bunch of CirrusCI warning in changes are they relevant ?

The `but their only_if conditions are different` things are very minor warnings.  Most of them are related to support for magic PR description strings like `[CI:DOCS]`, `[CI:BUILD]`, etc.  Fixing them all is probably not worth the effort needed.

When the `only_if` vs deps. /are/ genuinely broken, the effect will be seen as artifact-passing breakage (curl 404 errors).  I'm not aware of us hitting those with any frequency though, so it's probably fine.

Thanks for checking.

**Comment by cevich** [comment]
Flipping this back to `[WIP]` so it doesn't get merged yet.  Review can continue.  I need to ask an internal group some questions related to GitLeaks, before this can get merged.

**Comment by cevich** [comment]
Update: Concluded necessary internal discussion.  Removed `[WIP]`, this can be merged when appropriate (maybe not right before I go on PTO?).  It covers several important security-scanning contexts not protected by other tooling.  

Assuming/once this is working, I plan to make it into a reusable workflow that can be called from Buildah and Skopeo.

**Comment by cevich** [comment]
Force-push: Fixed missing recipient notification address var.  Rebased on upstream.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by cevich** [comment]
Note: Intending to merge this around Wednesday the 25th, assuming that's a good time to quickly fix any mass-PR CI breakage.

**Comment by cevich** [comment]
Argh, of course it broke.  Looks like Ubuntu hasn't updated podman to support `--userns=keep-id` yet.  I'll open a PR to fix this.

**Comment by cevich** [comment]
Opened https://github.com/containers/podman/pull/20533

**Pull request merged**
