### PR TITLE
Vendor in latest containers/common

### PR DESCRIPTION
**Pull request by sstosh**
Signed-off-by: Toshiki Sonoda <sonoda.toshiki@fujitsu.com>

#17463 contains changes to common/libimage.
Need to update common package.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by sstosh** [comment]
## system test: Adapt to image pull/load events chenges

`image events` and `events with events_logfile_path in containers.conf` are failed.
This issue related to containers/common#1325

<details>
<summary>NG log</summary>

```
not ok 1 events with events_logfile_path in containers.conf
# (from function `assert' in file helpers.bash, line 643,
#  in test file test.bats, line 17)
#   `assert "$(< $events_file)" =~ "\"Name\":\"$IMAGE\"" "Image found in events"' failed
# # podman rm -t 0 --all --force --ignore
# # podman ps --all --external --format {{.ID}} {{.Names}}
# # podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
# quay.io/libpod/testimage:20221018 f5a99120db64
# # podman --events-backend=file pull quay.io/libpod/testimage:20221018
# Trying to pull quay.io/libpod/testimage:20221018...
# Getting image source signatures
# Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
# Copying blob sha256:578f06cc66c59303d36e0c83b8c7fd9b2da35cca97118700cb4a373677c01dca
# Copying config sha256:f5a99120db6452661930a1db3bf7390eec9b963f5f62c068fa32dc1d550afad3
# Writing manifest to image destination
# Storing signatures
# f5a99120db6452661930a1db3bf7390eec9b963f5f62c068fa32dc1d550afad3
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: Image found in events
# #| expected: =~ '"Name":"quay.io/libpod/testimage:20221018"'
# #|   actual:    '{"ID":"f5a99120db6452661930a1db3bf7390eec9b963f5f62c068fa32dc1d550afad3","Name":"f5a99120db6452661930a1db3bf7390eec9b963f5f62c068fa32dc1d550afad3","Status":"pull","Time":"2023-02-17T15:43:24.219814576+09:00","Type":"image","Attributes":null}'
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# # [teardown]
# # podman pod rm -t 0 --all --force --ignore
# # podman rm -t 0 --all --force --ignore
# # podman network prune --force
# # podman volume rm -a -f
```
</details>

The name field of the image pull event is ID instead of Name.
Is this change expected?

## e2e: update CDI device test

If we update vendor, we cannot use the CDI spec
files with versions less than v0.3.0.
This issue related to container-orchestrated-devices/container-device-interface#93

How should we address this incompatibility?

**Comment by rhatdan** [comment]
@sstosh could you squash your commits.

**Comment by rhatdan** [comment]
Sadly this needs a rebase.

**Comment by edsantiago** [comment]
#17591 brought in a newer containers-common (852ca05a1fbb)  so I believe this PR can be closed.

**Pull request closed without merging**
