### PR TITLE
vendor: update to docker 27

### PR DESCRIPTION
**Pull request by Luap99**
Fixes compile issues with new docker changes.
Also there seem to be larger pre-existing problems with the /containers/json API output as the HostConfig field seems to be missing but I don't have time to deal with that currently.

Note this does not include changes for the new docker API 1.46.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@mheon @containers/podman-maintainers PTAL
I found a way to make the swagger validation happy, see second commit.

**Comment by rhatdan** [comment]
LGTM

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
