### PR TITLE
[CI:DOCS] Bump to v3.1.0

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by edsantiago** [comment]
APIv2 tests: don't track each precise version bump, but to at least confirm major version
```diff
diff --git a/test/apiv2/01-basic.at b/test/apiv2/01-basic.at
index 82c31f660..a43c5659b 100644
--- a/test/apiv2/01-basic.at
+++ b/test/apiv2/01-basic.at
@@ -18,7 +18,7 @@ t HEAD libpod/_ping 200
 for i in /version version; do
     t GET  $i      200                           \
       .Components[0].Name="Podman Engine"        \
-      .Components[0].Details.APIVersion=3.1.0    \
+      .Components[0].Details.APIVersion~3[0-9.-]\\+  \
       .Components[0].Details.MinAPIVersion=3.0.0 \
       .Components[0].Details.Os=linux            \
       .ApiVersion=1.40                          \
```

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL and merge

**Pull request merged**
