### PR TITLE
[CI:DOCS] Add schema for ImageCreate 200 response.

### PR DESCRIPTION
**Pull request by tmds**
Attempt at fixing https://github.com/containers/podman/issues/12927.

@jwhonce ptal.

### CODE REVIEW

**Comment by rhatdan** [comment]
You need to sign your commit, and add a tests or [NO NEW TEST NEEDED] flag.

**Comment by jwhonce** [comment]
LGTM, see https://github.com/containers/podman/pull/13142#issuecomment-1030002550 for process requirements. :+1:

**Comment by tmds** [comment]
@rhatdan I tried to sign my commit. The DCO test does not approve.

I ran `gpg --gen-key` since I didn't have a key yet, and then signed my commit using `-S`.

```
$ git log --show-signature -1
commit 1d98a36ea6b4ea29cccbe057099e959cfc439de1 (HEAD -> ImageCreate_200_schema, origin/ImageCreate_200_schema)
gpg: Signature made Mon 07 Feb 2022 10:49:02 AM CET
gpg:                using EDDSA key 23FDF28B72B23CF4C11C0B57E0DE26F32851AEE4
gpg:                issuer "tom.deseyn@gmail.com"
gpg: Good signature from "Tom Deseyn <tom.deseyn@gmail.com>" [ultimate]
Author: Tom Deseyn <tom.deseyn@gmail.com>
Date:   Mon Feb 7 10:49:02 2022 +0100

    Add schema for ImageCreate 200 response.
```

What is missing?

> and add a tests or [NO NEW TEST NEEDED] flag.

@jwhonce I've added this flag. If this is not ok, let me know where I should add a test.

**Comment by Luap99** [comment]
@tmds You do not have to sign your commits via gpg. You just have to add the Sign-off-by line to your commit message, see https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs

**Comment by tmds** [comment]
I've added `[NO NEW TEST NEEDED]` to the title of this PR. From CI failure, it looks like the wrong place. Where should I add this?

**Comment by flouthoc** [comment]
@tmds `[NO NEW TEST NEEDED]` is also needed somewhere in your commit message.

**Pull request merged**
