### PR TITLE
More /var/run -> /run

### PR DESCRIPTION
**Pull request by edsantiago**
PR #8851 broke CI: it included "/var/run" strings that,
per #8771, should have been just "/run".

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
@Luap99 PTAL

**Comment by mheon** [comment]
LGTM

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by edsantiago** [comment]
For posterity, the failure is:
```
=== RUN   TestCreatePodSystemdUnit/pod_with_root_args
    pods_test.go:246: 
        	Error Trace:	pods_test.go:246
        	Error:      	Not equal: 
        	            	expected: "# pod-123abc.service\n# autogenerated by Podman CI\n\n[Unit]\nDescription=Podman pod-123abc.service\nDocumentation=man:podman-generate-systemd(1)\nWants=network.target\nAfter=network-online.target\nRequires=container-1.service container-2.service\nBefore=container-1.service container-2.service\n\n[Service]\nEnvironment=PODMAN_SYSTEMD_UNIT=%n\nRestart=always\nTimeoutStopSec=102\nExecStart=/usr/bin/podman start jadda-jadda-infra\nExecStop=/usr/bin/podman stop -t 42 jadda-jadda-infra\nExecStopPost=/usr/bin/podman stop -t 42 jadda-jadda-infra\nPIDFile=/run/containers/storage/overlay-containers/639c53578af4d84b8800b4635fa4e680ee80fd67e0e6a2d4eea48d1e3230f401/userdata/conmon.pid\nType=forking\n\n[Install]\nWantedBy=multi-user.target default.target\n"
        	            	actual  : "# pod-123abc.service\n# autogenerated by Podman CI\n\n[Unit]\nDescription=Podman pod-123abc.service\nDocumentation=man:podman-generate-systemd(1)\nWants=network.target\nAfter=network-online.target\nRequires=container-1.service container-2.service\nBefore=container-1.service container-2.service\n\n[Service]\nEnvironment=PODMAN_SYSTEMD_UNIT=%n\nRestart=always\nTimeoutStopSec=102\nExecStart=/usr/bin/podman start jadda-jadda-infra\nExecStop=/usr/bin/podman stop -t 42 jadda-jadda-infra\nExecStopPost=/usr/bin/podman stop -t 42 jadda-jadda-infra\nPIDFile=/var/run/containers/storage/overlay-containers/639c53578af4d84b8800b4635fa4e680ee80fd67e0e6a2d4eea48d1e3230f401/userdata/conmon.pid\nType=forking\n\n[Install]\nWantedBy=multi-user.target default.target\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -18,3 +18,3 @@
        	            	 ExecStopPost=/usr/bin/podman stop -t 42 jadda-jadda-infra
        	            	-PIDFile=/run/containers/storage/overlay-containers/639c53578af4d84b8800b4635fa4e680ee80fd67e0e6a2d4eea48d1e3230f401/userdata/conmon.pid
        	            	+PIDFile=/var/run/containers/storage/overlay-containers/639c53578af4d84b8800b4635fa4e680ee80fd67e0e6a2d4eea48d1e3230f401/userdata/conmon.pid
        	            	 Type=forking
        	Test:       	TestCreatePodSystemdUnit/pod_with_root_args
```
Reference: [log](https://cirrus-ci.com/task/5886546412830720?command=main#L2024) (Source: #8951)

**Comment by mheon** [comment]
Tests are failing with 503s on registry.redhat.com

**Comment by edsantiago** [comment]
Yeah, we had a ton of failures earlier, like 8 or so. I restarted them all, looks like some of them passed. I just restarted the new crop.  I hate flakes.

**Pull request merged**
