### PR TITLE
pkg,libpod: remove `pkg/hooks` and use `hooks` from `c/common` 

### PR DESCRIPTION
**Pull request by flouthoc**
PR https://github.com/containers/common/pull/1071 moved `pkg/hooks` to
`c/common` hence remove that from podman and use `pkg/hooks` from
`c/common`

[NO NEW TESTS NEEDED]
[NO TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
pkg: hooks has been removed from podman to github.com/containers/common ( https://github.com/containers/common/tree/main/pkg/hooks )
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Please add a release note for packagers since the location of the man page has changed and where they can find it now.

**Comment by flouthoc** [comment]
Is failing test related to this PR.
`install: missing destination file operand after 'podman_tmp_wXKL/podman-v4.2.0-dev/usr/share/man/man5'`

**Comment by Luap99** [comment]
> Is failing test related to this PR. `install: missing destination file operand after 'podman_tmp_wXKL/podman-v4.2.0-dev/usr/share/man/man5'`

Yes you need to update the makefile with the removed man page

**Comment by flouthoc** [comment]
@Luap99 Did you mean https://github.com/containers/podman/blob/main/Makefile ? There was only a reference to `pkg/hooks` in `podman.spec.rpkg` I have removed it already can't see any reference in Makefile :\

**Comment by Luap99** [comment]
```diff
diff --git a/Makefile b/Makefile
index 32de58856..ef91b5071 100644
--- a/Makefile
+++ b/Makefile
@@ -77,7 +77,7 @@ BUILDTAGS_CROSS ?= containers_image_openpgp exclude_graphdriver_btrfs exclude_gr
 CONTAINER_RUNTIME := $(shell command -v podman 2> /dev/null || echo docker)
 OCI_RUNTIME ?= ""
 
-MANPAGES_MD ?= $(wildcard docs/source/markdown/*.md pkg/*/docs/*.md)
+MANPAGES_MD ?= $(wildcard docs/source/markdown/*.md)
 MANPAGES ?= $(MANPAGES_MD:%.md=%)
 MANPAGES_DEST ?= $(subst markdown,man, $(subst source,build,$(MANPAGES)))
 
```

**Comment by flouthoc** [comment]
@Luap99 wouldn't it stop processing `docs` from other packages as well since its `pkg/*/docs/*.md` ?

**Comment by flouthoc** [comment]
@Luap99 Nope patch did not work looks like something else. Trying to check..

**Comment by Luap99** [comment]
Looks like you have to remove the .5 install comand as well since there are no longer any .5 pages in the podman repo.
```diff
diff --git a/Makefile b/Makefile
index 32de58856..f15b61efe 100644
--- a/Makefile
+++ b/Makefile
@@ -776,9 +776,7 @@ install.modules-load: # This should only be used by distros which might use ipta
 .PHONY: install.man
 install.man:
        install ${SELINUXOPT} -d -m 755 $(DESTDIR)$(MANDIR)/man1
-       install ${SELINUXOPT} -d -m 755 $(DESTDIR)$(MANDIR)/man5
        install ${SELINUXOPT} -m 644 $(filter %.1,$(MANPAGES_DEST)) $(DESTDIR)$(MANDIR)/man1
-       install ${SELINUXOPT} -m 644 $(filter %.5,$(MANPAGES_DEST)) $(DESTDIR)$(MANDIR)/man5
        install ${SELINUXOPT} -m 644 docs/source/markdown/links/*1 $(DESTDIR)$(MANDIR)/man1
 
 .PHONY: install.completions
```

**Comment by flouthoc** [comment]
> Weird it looks like old buildah and c/common are not happy together, bumping buildah as well since new `c/common` passes test with buildah on main.
> 
> Edit: verified locked buildah version `e66309ebde8c` in podman is not working with latest `c/common` so will need a buildah bump for this.

Will rebase this when podman gets new buildah.

**Comment by flouthoc** [comment]
@containers/podman-maintainers PTAL. Would it be possible to get this in before the release ? I think this should get in.

**Review by Luap99 — COMMENTED** [review]
LGTM, -40k binary size

Although I would would prefer to squash the commits but that is not worth the repush.

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by vrothberg** [comment]
@flouthoc +1 on backporting it to the v4.2 branch - assuming the c/common there ships these man pages.

**Comment by vrothberg** [comment]
@flouthoc please update the release for downstream packagers.  I'd expect an explicit note where these man pages should be built from now.

**Comment by flouthoc** [comment]
> @flouthoc please update the release for downstream packagers. I'd expect an explicit note where these man pages should be built from now.

@vrothberg I added a release note on the PR for this. Is there some place else other than this where we have to update this ? Could you please let me know if there is any other place as well so I can update that.

**Pull request merged**
