### PR TITLE
Fix use of infra image to clarify default

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Testing: https://github.com/containers/common/pull/910

**Comment by vrothberg** [comment]
Note: The consensus on the current behavior was driven by the fact that we'd otherwise keep on pulling the k8s image on existing machines after an update since it was mentioned in containers.conf.

@rhatdan can you extend the docs and mention that users need to comment out the infra_image line in containers.conf if they want to build the local image?

**Comment by rhatdan** [comment]
It is not on by default in the containers.conf.  It is commented out.  So it will NOT pull the image.  Nothing by default is commented out.  If the user commented it out, then that indicates that they wanted to pull the image.

**Comment by vrothberg** [comment]
Excellent!

**Review by vrothberg — COMMENTED** [review]
LGTM, nice work @rhatdan !

@containers/podman-maintainers PTAL

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
