### PR TITLE
[v4.4.1-rhel] builds try to write to additionalImageStore

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
... read-only locataion

This vendors in c/storage v1.45.7 to address this issue in RHEL 8.8/9.2: containers/storage#1733

This addresses: https://issues.redhat.com/browse/RHEL-41079 and https://issues.redhat.com/browse/ACCELFIX-243

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Capturing the initial error.  I think I've worked around it with the added test pick commits, but just in case, here's the starting one.

```
[+0217s] Caching k8s.gcr.io/pause:3.2 at /tmp/k8s.gcr.io-pause-3.2.tar...
[+0217s] Running: /var/tmp/go/src/github.com/containers/podman/bin/podman --root /tmp/root --runroot /tmp/runroot --runtime crun --conmon /usr/bin/conmon --network-config-dir /etc/cni/net.d --network-backend cni --cgroup-manager systemd --tmpdir /tmp --events-backend file --storage-driver vfs pull k8s.gcr.io/pause:3.2
[+0217s] Trying to pull k8s.gcr.io/pause:3.2...
[+0217s] Error: initializing source docker://k8s.gcr.io/pause:3.2: invalid character '<' looking for beginning of value
[+0217s] 
[+0217s] 
[+0217s] Failure [64.355 seconds]
[+0217s] [BeforeSuite] BeforeSuite 
[+0217s] /var/tmp/go/src/github.com/containers/podman/test/e2e/common_test.go:104
[+0217s] 
[+0217s]   Expected
[+0217s]       <int>: 125
[+0217s]   to match exit code:
[+0217s]       <int>: 0
[+0217s] 
[+0217s]   /var/tmp/go/src/github.com/containers/podman/test/e2e/common_test.go:368
[+0217s] 
[+0217s]   Full Stack Trace
[+0217s]   github.com/containers/podman/v4/test/e2e.(*PodmanTestIntegration).createArtifact(0x1377080?, {0x158eb44, 0x14})
[+0217s]   	/var/tmp/go/src/github.com/containers/podman/test/e2e/common_test.go:368 +0x266
[+0217s]   github.com/containers/podman/v4/test/e2e.glob..func7()
[+0217s]   	/var/tmp/go/src/github.com/containers/podman/test/e2e/common_test.go:120 +0x285
[+0217s]   reflect.Value.call({0x136bf00?, 0x1623c18?, 0xc0004ea780?}, {0x156fa1e, 0x4}, {0xc000023458, 0x0, 0xc000023460?})
[+0217s]   	/usr/lib/golang/src/reflect/value.go:556 +0x845
[+0217s]   reflect.Value.Call({0x136bf00?, 0x1623c18?, 0xc0000234b0?}, {0xc000023458, 0x0, 0x0})
[+0217s]   	/usr/lib/golang/src/reflect/value.go:339 +0xbf
[+0217s]   github.com/containers/podman/v4/test/e2e.TestLibpod(0x0?)
[+0217s]   	/var/tmp/go/src/github.com/containers/podman/test/e2e/common_test.go:101 +0xbc
[+0217s]   testing.tRunner(0xc0004909c0, 0x16237d0)
[+0217s]   	/usr/lib/golang/src/testing/testing.go:1439 +0x102
[+0217s]   created by testing.(*T).Run
[+0217s]   	/usr/lib/golang/src/testing/testing.go:1486 +0x35f
[+0217s] ------------------------------
[+0217s] Failure [64.412 seconds]
```

**Comment by TomSweeneyRedHat** [comment]
@edsantiago, if this passes, could you please take a good eyeball at the third commit, "Change images_test expect from 10 to 9," and let me know if that's problematic? I'm just slightly leary that we might have introduced a change that would break something elsewhere in this release.

**Comment by Luap99** [comment]
Looks like you also need to get https://github.com/containers/podman/pull/21875 here like you did in the 4.9 PR (https://github.com/containers/podman/pull/23255)

**Comment by Luap99** [comment]
> @edsantiago, if this passes, could you please take a good eyeball at the third commit, "Change images_test expect from 10 to 9," and let me know if that's problematic? I'm just slightly leary that we might have introduced a change that would break something elsewhere in this release.

@TomSweeneyRedHat That is fine you cherry-pick cleanup was incorrect. If you look at the original commit it changed from 9 -> 10, you changed the commit to go from 8 -> 10 thus failing the test.
https://github.com/containers/podman/pull/20452/commits/85cc4092fc8b73b5e3f962c2305e00acd02cb734

Therefore 8 -> 9 is correct here.

**Comment by edsantiago** [comment]
Thanks, @Luap99. Yes, both comments are correct.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 @edsantiago Thanks!  I added the mount test fix and it's all happy green test buttons now.  Merge me please!

**Pull request merged**
