### PR TITLE
Fix AssertionError: 'alpine' not found in 'docker.io/docker/desktop-kubernetes'

### PR DESCRIPTION
**Pull request by cevich**
Backport of #13239 and #13241

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
test redness does not.

**Comment by edsantiago** [comment]
>         AssertionError: 'alpine' not found in 'docker.io/docker/desktop-kubernetes kubernetes binaries for desktop. compiled fr...'

Who is doing the truncation (`fr...`)? Is that python or podman?

**Comment by edsantiago** [comment]
Answered my own question: it's podman:
```
$ bin/podman image search alpine|grep -v alpine
INDEX       NAME                                           DESCRIPTION                                      STARS       OFFICIAL    AUTOMATED
docker.io   docker.io/docker/desktop-kubernetes            Kubernetes binaries for Desktop. Compiled fr...  12
docker.io   docker.io/puppet/r10k                          r10k on a Docker image. Based on Alpine          4
docker.io   docker.io/armswdev/c-hello-world               Simple hello-world C program on Alpine Linux...  0
```
(v3.4 truncates the Description. v4.0 does not).

This approach will therefore not work in v3.4. It might work with `--no-trunc`, but I don't know how to pass that in python-land. @baude any reason not to just remove this test entirely in v3.4?

**Comment by cevich** [comment]
Good eye @edsantiago.  @mheon since this test is relying on external inputs we have no control over, and it's a long-term maintenance branch, disabling it is probably the better choice...

**Comment by cevich** [comment]
...disabled with a comment explaining why.

**Review by edsantiago — APPROVED** [review]
logformatter and py changs lgtm. I'd like @baude's confirmation on the other one.

**Pull request merged**
