### PR TITLE
No longer support deprecated legacy QEMU machine structures

### PR DESCRIPTION
**Pull request by jakecorrenti**
Removes the `MachineVMV1` and `MonitorV1` structures that have been deprecated for a long enough period of time that it makes sense to no longer support them.

Results in the removal of deprecated `getSocketAndPid` as well.

The migration code was added in commit `6e0e1cbddd5e1c5dff51215ad2b41a99d890fad8` and made it into release `v4.1.0`

#### Does this PR introduce a user-facing change?

```release-note
Warning (action required): Users running a `podman` version earlier than `v4.1.0` will have machines using a now unsupported internal structure as of `v5.0.0`. There will be no way to migrate unless using a version of `podman` from `v4.1.0` to `v4.5.1` to do the migration. If a migration is not done, the user will not be able to remove the machine files using `podman machine rm` and will have to manually remove all files for the out-of-date machines.
```

### CODE REVIEW

**Comment by jakecorrenti** [comment]
Only action that would be needed by the user for this removal would be to migrate their existing machines with the old structures to the new structures, but considering the `migrateVM` function was merged into upstream last year I don't foresee that being a problem

**Comment by rhatdan** [comment]
@baude @ashley-cui PTAL

**Comment by Luap99** [comment]
In principle I am fine with this but can you be specific, i.e. what version was this added? It is very useful to know what upgrade path will be broken by this.

**Comment by jakecorrenti** [comment]
> In principle I am fine with this but can you be specific, i.e. what version was this added? It is very useful to know what upgrade path will be broken by this.

I adjusted the commit message, but it was added in commit `6e0e1cbddd5e1c5dff51215ad2b41a99d890fad8` which made it into `4.1.0`

**Review by ashley-cui — COMMENTED** [review]
LGTM, thanks!

**Comment by Luap99** [comment]
Is there a specific reason to remove it now? Or can we hold it for podman 5.0? That at lest gives a valid excuse if somebody is broken. Can we really expect all machine users to not directly update from 4.0 to 4.6 or later?

I am not blocking this but at the very least this definably needs a warning in the release notes. So please add a proper entry under: `Does this PR introduce a user-facing change?`

**Comment by jakecorrenti** [comment]
That's a valid point I didn't think of. @ashley-cui @baude what are your thoughts on this?

**Comment by ashley-cui** [comment]
I think the rules of semver say that we should wait until 5.0, and the only impact waiting would have would be some mostly rarely used code in machine. Technically would be a breaking upgrade, but at the same time I'm not sure if many users would make such a large jump from 4.0 to 4.6, and be mad about having to rm their machine since many of our solutions to a broken machine is "try re-creating it" anyway.

I think it's mostly up to how we want to follow semver.

**Comment by Luap99** [comment]
But can a user rm the machine in this case, I assume the json unmarshal will fail and podman is unable to remove the files because of it? So a user would need to figure out where all files are and remove them by hand.
But if a simple machine rm still works on an old config file I agree that this is not a bid deal.

**Comment by jakecorrenti** [comment]
afaik that would be an issue. The remove command currently migrates an old machine to the new format, so it would fail

**Comment by ashley-cui** [comment]
Oops, you're correct, this would break rm as well.

**Comment by jakecorrenti** [comment]
Should I close this for the time being

**Comment by rhatdan** [comment]
We can just mark it for 5.0

**Comment by TomSweeneyRedHat** [comment]
I could be dropping brain bits, but have we written a deprecation notice for this?  I concur, this should come out in Podman v5.0.  Please update the release note comment in the description to reflect that.

**Comment by jakecorrenti** [comment]
> I could be dropping brain bits, but have we written a deprecation notice for this? I concur, this should come out in Podman v5.0. Please update the release note comment in the description to reflect that.

Updated the release note comment. Where would I look to find or write the deprecation notice?

**Comment by TomSweeneyRedHat** [comment]
Hopefully, the deprecation notices are in our release announcements, if not there, then the RHEL docs which is more fun to track down.

**Comment by baude** [comment]
this can go into 4.x.  The format was very old and it has been many many generations since the new one is introduced.  I'd like to see it rebased and merged.  I am willing to bet there are no installs out there with this; also will to take the complaints if there is one.

**Comment by jakecorrenti** [comment]
rebased

**Comment by rhatdan** [comment]
@jakecorrenti Please rebase

**Review by vrothberg — COMMENTED** [review]
@baude what should we do this PR?  Is this being tracked in Jira?

**Comment by jakecorrenti** [comment]
> @baude what should we do this PR? Is this being tracked in Jira?

It is tracked under RUN-1955

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by jakecorrenti** [comment]
failed tests just need a restart (which I don't have the perms for)

**Comment by TomSweeneyRedHat** [comment]
@jakecorrenti I've just restarted the failed tests, :crossed_fingers:

**Pull request merged**
