### PR TITLE
WIP: [DO NOT MERGE] pick up storage#1560

### PR DESCRIPTION
**Pull request by nalind**
#### Does this PR introduce a user-facing change?

Quite the opposite: if it works, additional image stores will act slightly less weird.

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
All green.

I restarted the flaked machine job.

**Comment by nalind** [comment]
Rebased, in part because #18090 has been merged, in part hoping that a reset will help CI launch that failing job.

**Comment by mheon** [comment]
I've seen the machine error on other PRs, so I doubt it's specific to these changes. Restarted anyways.

**Comment by TomSweeneyRedHat** [comment]
And all happy green test buttons here.  Do we start dancing the vendor dance?

**Pull request closed without merging**
