### PR TITLE
Revert "Expose as-tested Mac/Windows repository state"

### PR DESCRIPTION
**Pull request by cevich**
Fix [artifacts task error](https://cirrus-ci.com/task/6595797815394304):

```
Failed to upload artifacts:
rpc error: code = FailedPrecondition
desc = Artifacts size is too big!
```

This reverts commit 698219cf9882ff0d229cd10bab0afd03ba09884b.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
@mheon @baude @edsantiago PTAL.  This will fix the "artifacts too big" error causing daily cron jobs to fail.  The group that needs the `repo.tbz` can simply download a copy from the relevant task name directly.  So nothing is really lost.

**Comment by edsantiago** [comment]
I know nothing about Podman Desktop. However, (1) our nightly cron is broken, and (2)  this looks like a clean revert of #21674, which (3) has been in existence for only one week, so:

/lgtm

**Comment by mheon** [comment]
Sure
/approve

**Comment by cevich** [comment]
> I know nothing about Podman Desktop

They asked for this feature originally.  I'll talk to them on Thursday about this and the workaround.

**Pull request merged**
