### PR TITLE
[v4.9] Remove gitleaks scanning

### PR DESCRIPTION
**Pull request by cevich**
Ref: #21588

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by lsm5 — APPROVED** [review]
/lgtm
/approve
/hold

**Comment by lsm5** [comment]
tests aren't happy with the removal

**Comment by cevich** [comment]
Oh woops, I missed a spot.

**Comment by mheon** [comment]
Validate is angry

**Comment by cevich** [comment]
Ugh, thanks.  It's never easy.  One more time...

**Comment by cevich** [comment]
This is ready finally.

**Pull request merged**
