### PR TITLE
Prepare tests for better reuse with zstd:chunked pulls

### PR DESCRIPTION
**Pull request by mtrmac**
- Fix a test of encrypted pulls to actually test the right thing
- Update tests to be ready for future https://github.com/containers/image/pull/2321 , so that we can later vendor c/image without seeing test failures.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mtrmac** [comment]
Compare #23348 testing the future c/changes.

**Comment by rhatdan** [comment]
LGTM
@giuseppe PTAL

**Comment by rhatdan** [comment]
@mheon @Luap99 @baude @ashley-cui @l0rd PTAL

**Comment by mheon** [comment]
@edsantiago PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
