### PR TITLE
Add support for podman remote build -f - .

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/10621

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, some unhappy tests on this one.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by edsantiago** [comment]
/lgtm

Thank you!

**Comment by edsantiago** [comment]
Confirmed: The [bud-from-stdin](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6556734480187392/html/bud-remote-fedora-34-root-host.log.html#t--00085) test (85) now passes under podman-remote.

**Pull request merged**
