### PR TITLE
[v4.6] Bump c/common to v0.55.3

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@ashley-cui FYI and PTAL

**Comment by ashley-cui** [comment]
Thanks! Unhappy go.mod :(

**Comment by TomSweeneyRedHat** [comment]
@vrothberg PTAL.  Any suggestions on how to clean the dirtiness?  I redid the vendoring, and still the same.  On my very first vendor attempt, it failed part way due to a hardware error, should I just restart from scratch?

**Comment by vrothberg** [comment]
> @vrothberg PTAL. Any suggestions on how to clean the dirtiness? I redid the vendoring, and still the same. On my very first vendor attempt, it failed part way due to a hardware error, should I just restart from scratch?

It works on my end.  Try resetting your branch to `upstream/v4.6` and redo the `go get` and `make vendor`.  Alternatively, there's `make vendor-in-container`. 

But in the interest of time, I close this PR and open a new one.

**Comment by TomSweeneyRedHat** [comment]
Thanks @vrothberg it must not have been happy with the unexpected failure part way through the original vendoring.  FWIW, I tried both the vendor-in-container and plain vendor with no joy.

**Pull request closed without merging**
