### PR TITLE
WIP: Volume Plugins

### PR DESCRIPTION
**Pull request by mheon**
For now, only the skeleton which we use to contact individual plugins. The bits that actually connect to Libpod are going to be exceedingly difficult to get right, given the volumes only "sort of" exist in Libpod and the database (primary management is delegated elsewhere, which is something that was definitely not in mind we we originally wrote Libpod).

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon You still working on this?

**Comment by mheon** [comment]
Less actively - I'm switching over to APIv2 to unblock Brent and Jhon

**Comment by filak-sap** [comment]
Guys, any progress on this? The lack of NFS volumes blocks us from deploying our ABAP systems.

**Comment by mheon** [comment]
NFS volumes are a separate issues and have been working for a while (Podman 1.7 or 1.8, I forget which)

**Comment by jfilak** [comment]
Oh, yeah, sorry, I had old information from colleagues of mine and I didn't bother to re-test.

**Comment by mheon** [comment]
Closing in favor of #8357

**Pull request closed without merging**
