### PR TITLE
When determining systemd mode, use full command

### LINKED ISSUE #6920: podman 2.0.1 on Fedora 32 Failed to mount tmpfs on /run: Operation not permitted
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
podman 2.0.1 on Fedora 32 cannot run systemd based containers
**Steps to reproduce the issue:**

1. `podman run --entrypoint /sbin/init centos:8`

2.

3.

**Describe the results you received:**

```
# podman run -it --rm  --entrypoint /sbin/init --name testing centos:8
Failed to mount tmpfs at /run: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```

**Describe the results you expected:**
Container runs with systemd as PID 1

**Additional information you deem important (e.g. issue happens only occasionally):**

Works with 1.8.2

**Output of `podman version`:**

```
# podman version
Version:      2.0.1
API Version:  1
Go Version:   go1.14.3
Built:        Thu Jan  1 07:30:00 1970
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:                      
  arch: amd64             
  buildahVersion: 1.15.0
  cgroupVersion: v2
  conmon:                                                          
    package: conmon-2.0.18-1.fc32.x86_64         
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 6e8799f576f11f902cd8a8d8b45b2b2caf636a85'
  cpus: 8 
  distribution:                                                    
    distribution: fedora
    version: "32"    
  eventLogger: file  
  hostname: podman.localhost
  idMappings:
    gidmap: null  
    uidmap: null
  kernel: 5.7.7-200.fc32.x86_64
  linkmode: dynamic
  memFree: 4131205120
  memTotal: 33607065600
  ociRuntime:
    name: crun
    package: crun-0.14-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14
      commit: ebc56fc9bcce4b3208bb0079636c80545122bf58
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock 
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 44h 34m 36.62s (Approximately 1.83 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 14
    paused: 0
    running: 1
    stopped: 13
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 29
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 07:30:00 1970
  GitCommit: ""
  GoVersion: go1.14.3
  OsArch: linux/amd64
  Version: 2.0.1


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman crun
podman-2.0.1-1.fc32.x86_64
crun-0.14-2.fc32.x86_64

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- No SELinux AVCs; still doesn't work if `setenforce 0`
- tried 2.0.2 from koji, same issue

### PR DESCRIPTION
**Pull request by mheon**
We were only using the Command field in specgen when determining whether to enable systemd if systemd=true (the default) was used. This does not include the entrypoint, and does not include any entrypoint/command sourced from the image - so an image could be running systemd and we'd not correctly detect this. Using the full, final command resolves this and matches Podman v1.9.x behavior.

Fixes #6920

### CODE REVIEW

**Comment by mheon** [comment]
Hold this until after lunch, I want to add some tests

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
Tests added

**Comment by mheon** [comment]
`[+0287s] Error: unable to pull registry.access.redhat.com/ubi8-minimal: Error reading blob sha256:396754cf27f9e418ecbecce2f78b337f7bae4b1cd33a7d1c8926c54898cadf2f: Error fetching blob: invalid status code from registry 503 (Service Unavailable)`

You know, I was really hoping the RH official registries would be a little more reliable...

**Comment by rhatdan** [comment]
@baude @giuseppe @vrothberg @TomSweeneyRedHat @jwhonce @ashley-cui @QiWang19 PTAL

**Comment by QiWang19** [comment]
LGTM

**Pull request merged**
