### PR TITLE
[v4.0-rhel backport] bump to race-free `c/image` and `c/storage` along with test to verify `concurrent/parallel` builds

### PR DESCRIPTION
**Pull request by flouthoc**
Commits explained in bullet points.
* Bump `c/storage` to `v1.38.3` released here: https://github.com/containers/storage/pull/1174 
* Bump `c/image` to `v5.19.2` released here: https://github.com/containers/image/pull/1503

New Names API in `c/storage` and `c/image` ensures that Name modification operations are `race-free`.

* Adds a test to verify parallel/concurrent builds via podman don't race against each other.

For reference actual upstream PR: https://github.com/containers/image/pull/1480 and https://github.com/containers/storage/pull/1153

### CODE REVIEW

**Comment by flouthoc** [comment]
@mheon @TomSweeneyRedHat fixes for `v4.0-rhel`

**Comment by TomSweeneyRedHat** [comment]
Won't we need Buildah bumped too?  Otherwise LGTM.

**Comment by TomSweeneyRedHat** [comment]
And we'll need this in the 4.0 branch.

**Comment by TomSweeneyRedHat** [comment]
At least partially addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2066519  RHEL 8.6 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2055487

**Comment by flouthoc** [comment]
> Won't we need Buildah bumped too? Otherwise LGTM.

@TomSweeneyRedHat Buildah vendor is not necessary needed to fix this in podman ( i.e for `podman build ..` commands ), since only dependencies are updated. 

But if we are also planning to release a new back-ported binary of buildah then `c/image` and `c/storage` can be back-ported to older version of buildah as well but no reason to block this PR.

**Comment by flouthoc** [comment]
> And we'll need this in the 4.0 branch.

Just created a PR for that in `v4.0` branch https://github.com/containers/podman/pull/13630

**Comment by TomSweeneyRedHat** [comment]
Exceptions approved:  RHEL 9.0 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2066519  RHEL 8.6 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2055487

**Comment by TomSweeneyRedHat** [comment]
@mheon @bbaude care to add your lgtm and merge this?

**Comment by flouthoc** [comment]
@mheon @rhatdan Any idea why `/lgtm` is not reacting.

**Pull request merged**
