### PR TITLE
[CI:DOCS] docs/build_osx.md: Describe external gvproxy

### PR DESCRIPTION
**Pull request by cgwalters**
I think many podman-MacOS developers will fit into what this doc section describes.

```release-note
None
```

### CODE REVIEW

**Comment by baude** [comment]
LGTM, but I thought this very recently changed and may not be needed any more ?

**Comment by rhatdan** [comment]
@gbraad @ashley-cui PTAL

**Review by vrothberg — COMMENTED** [review]
I think it's easier/more straight-forward to change `helper_binaries_dir=` in containers.conf.

**Comment by cgwalters** [comment]
> I think it's easier/more straight-forward to change helper_binaries_dir= in containers.conf.

Hmm.  Some different tradeoffs there; that would affect the main podman binary too (which is fine) but logically the goal here is to have two podman setups.

So I'm not totally sure it's universally better; to avoid debate I ended up just documenting that in addition too.

**Pull request merged**
