### PR TITLE
[CI:BUILD] Packit: Disable until proved in other repos

### PR DESCRIPTION
**Pull request by lsm5**
There are concerns with Packit causing flakes and delays on Podman so
let's have Packit prove itself in other repos and only then make its way
into Podman.

See: https://github.com/containers/podman/pull/15549#issuecomment-1233230573

[NO NEW TESTS NEEDED]

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### Does this PR introduce a user-facing change?

```release-note
None
```

@edsantiago PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
hmm, guess it's best I just delete the packit files to stop packit bot complaints.

**Comment by lsm5** [comment]
@edsantiago good to go

**Comment by edsantiago** [comment]
@lsm5 it's a hold -- you have the power. ("You've always had the power"). On a hold, you can just type `slash-hold-space-cancel`

**Pull request merged**
