### PR TITLE
Fix machine ssh login failed in rootless mode

### PR DESCRIPTION
**Pull request by pendulm**
add option to not read system ssh configurations
Fixes: #11731

Signed-off-by: pendulm <lonependulm@gmail.com>

[NO TESTS NEEDED]

### CODE REVIEW

**Comment by vrothberg** [comment]
Let's wait a bit until there's consensus on how to address the issue.  As mentioned in https://github.com/containers/podman/issues/11731#issuecomment-926460869 I am not sure whether `podman machine` should join the user NS.

**Comment by pendulm** [comment]
podman machine command should not join userns, I think this is logically true.

`ssh -F none` is a quick fix, assume machine ssh should not use configuration from host. But this may have compatibility issue if -F option is not available in all version of ssh client.

I had test this on my Fedora and Mac, it seems OK.

**Comment by rhatdan** [comment]
@ashley-cui @baude @jwhonce PTAL

**Comment by rhatdan** [comment]
@afbjorklund  PTAL

**Comment by afbjorklund** [comment]
Should you be running `Podman-remote machine ssh` ?

**Comment by pendulm** [comment]
> `ssh`

no this binary installed by default

**Pull request closed without merging**
