### PR TITLE
Allow creating anonymous volumes with --mount

### LINKED ISSUE #13756: Unable to create anonymous volumes with --mount
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. When running a tool which is provided as a Docker image (in my case, jetbrains/qodana-gradle-plugin)

2. The tool attempts to start a container with an anonymous volume mount: `--mount type=volume,dst=/data/project/.gradle`
    The full command executed is:

```
docker run --rm --name idea-inspections -p 8080:8080 -v /home/axa/dev/github.com/andrewaylett/asmble:/data/project -v /home/axa/dev/github.com/andrewaylett/asmble/build/results:/data/results --mount type=volume,dst=/data/project/.gradle jetbrains/qodana:latest
```

3. This fails

**Describe the results you received:**

Podman reports:

```
Error: must set source volume
```

**Describe the results you expected:**

The container is created with an anonymous volume

**Additional information you deem important (e.g. issue happens only occasionally):**

This has been reported against Qodana in https://youtrack.jetbrains.com/issue/QD-2325

I have a local fix for this issue and intend to raise a PR for it shortly.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by andrewaylett**
This fixes #13756.

All the mechanics to create anonymous volumes is already present, but
there's still a validation preventing that path from being taken.  We
remove the validation, which allows the volume to be created
successfully.

Signed-off-by: Andrew Aylett <andrew@aylett.co.uk>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
The changes as you have them look fine, but I'm can't recall if there was or was not a reason put in to require the source volume.
One of the test died, I think but don't know that it's a flake.  I've re-reun.
LGTM, assuming removing this test for the source volume is valid.

**Review by flouthoc — APPROVED** [review]
LGTM
@mheon PTAL

**Comment by umohnani8** [comment]
Changes LGTM

**Comment by andrewaylett** [comment]
@TomSweeneyRedHat, I'm fairly sure this is how the `--volumes` flag already handles this case: https://github.com/andrewaylett/podman/blob/3cee85531c43e7c66a6428b60b73925b2fcefcac/pkg/specgen/volumes.go#L78

It looks like the `--mount` code predates the current behaviour for `--volumes` -- I'm assuming that it was missed rather than being deliberately left as-was.

I don't think I mentioned that I've at least briefly validated this locally: the Qodana invocation that I mentioned in #13756 succeeds (with an selinux caveat) when I have this patch applied.  That's no guarantee that it's _correct_ of course.

**Pull request merged**
