### PR TITLE
update docs for network-cmd-path

### PR DESCRIPTION
**Pull request by Sativarsainath-26**
Fixes: #23711 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
Thanks for the PR but this option cannot be removed as stated in https://github.com/containers/podman/issues/23711#issuecomment-2304193623 this will break any user still using it and we can only do breaking changes for major releases.

I suggest you simply update the docs and code comment.

**Comment by Sativarsainath-26** [comment]
> Thanks for the PR but this option cannot be removed as stated in [#23711 (comment)](https://github.com/containers/podman/issues/23711#issuecomment-2304193623) this will break any user still using it and we can only do breaking changes for major releases.
> 
> I suggest you simply update the docs and code comment.

Sure @Luap99 , I have updated it to reflect that the change will be implemented in Podman 6.0, the next major version. Hope this is okay.

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by Sativarsainath-26** [comment]
@Luap99 could you please help here to fix this pipeline failure ?  Not sure why it is failing... as i didn't touch that part of code only.

**Pull request merged**
