### PR TITLE
[skip-ci] Packit/rpm: remove el8 jobs and spec conditionals

### PR DESCRIPTION
**Pull request by lsm5**
EL8 will go EOL soon and nothing on main will be shipped to el8.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
@Luap99 @mheon PTAL. figured this would make life easier even though we have over a month to go before el8 is actually EOL
cc @containers/podman-maintainers

**Comment by mheon** [comment]
5.0 is never reaching EL8, so honestly we could have done this earlier.

**Comment by mheon** [comment]
LGTM on my end.

**Pull request merged**
