### PR TITLE
Correct intermittent failures in pasta port range forwarding tests

### PR DESCRIPTION
**Pull request by dgibson**
Fix for #17287.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by sbrivio-rh** [comment]
`Reviewed-by: Stefano Brivio <sbrivio@redhat.com>`

**Comment by edsantiago** [comment]
Sigh. We need an "active review in progress" semaphore. Oh well, I will submit a cleanup PR another day.

**Comment by edsantiago** [comment]
(But that came off as ungrateful. Thank you @dgibson for your time investigating and fixing!)

**Comment by Luap99** [comment]
Sorry @edsantiago

**Pull request merged**
