### PR TITLE
Bump to v3.0.0-rc1

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
I thought we'd create an RC before?

**Comment by rhatdan** [comment]
@vrothberg @mheon @baude @TomSweeneyRedHat PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
Yay, LGTM! :)

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
