### PR TITLE
[CI:DOCS] Remove a note that the HTTP API is not yet stable.

### PR DESCRIPTION
**Pull request by mheon**
It's been out for quite a while now, I think we can safely call it stable.

### CODE REVIEW

**Comment by mheon** [comment]
@cevich Did we disable ci:docs?

**Comment by mheon** [comment]
/hold

We have flakes

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by cevich** [comment]
> @cevich Did we disable ci:docs?

In a way yes...it was never re-implemented.  In a pinch, you can use `[ci skip]` for largely the same effect.  I'll work up a PR to add it back in...

**Comment by cevich** [comment]
...https://github.com/containers/podman/pull/7998

**Pull request merged**
