### PR TITLE
[skip-ci] [CI:BUILD] FCOS+podman-next: correct GHA conditional syntax

### PR DESCRIPTION
**Pull request by lsm5**
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
I guess won't be a bad idea to build twice a day at least until the wait-for-copr stuff is fixed.

**Review by cevich — APPROVED** [review]
/lgtm

**Comment by cevich** [comment]
> Wonder if we should do something like cancel all prior jobs older than 2 hours if a new one is triggered given the GHA takes 1+ hour to complete.

These are some of the risks with 'latest' tagged images.  I wouldn't worry about it, I think you've had enough followup PRs for this, no reason to tempt that dragon more :rofl:

**Review by cevich — APPROVED** [review]
/lgtm

**Pull request merged**
