### PR TITLE
Bump to containers/common v0.34.2

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by ashley-cui** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
All kinds of test unhappiness @rhatdan

**Comment by vrothberg** [comment]
`[+0776s] Error: OCI runtime error: unknown cap: `CAP_PERFMON``

We need to be more careful in c/common and test certain PRs here first before merging.

**Comment by vrothberg** [comment]
I opened https://github.com/containers/common/pull/444 to revert the runc bump.

**Pull request closed without merging**
