### PR TITLE
Move podman build opts to common file

### PR DESCRIPTION
**Pull request by umohnani8**
Move the podman build opts to cmd/common so that
it can be used by podman build and podman farm build

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
@umohnani8 please rebase on 9554022ce to get CI working.

**Comment by mheon** [comment]
Code LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by Luap99** [comment]
The changes from https://github.com/containers/podman/pull/19951/commits/6b7f718b4b97779c0f0107dd19d5a7b4df13f3be conflict with this change so do not forget to add them to the moved code when you rebase.

**Comment by rhatdan** [comment]
@umohnani8 Needs a rebase.

**Pull request merged**
