### PR TITLE
Add support for 'podman cp' on FreeBSD

### PR DESCRIPTION
**Pull request by dfr**
This shares most of the implementation with Linux but handling of running containers is simpler due to the single global mount namespace.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by dfr** [comment]
Lint fixes

**Comment by dfr** [comment]
The failing test seems related to copy so I'll debug that

**Comment by dfr** [comment]
> The failing test seems related to copy so I'll debug that

Now I'm confused. I haven't been able to reproduce this locally, assuming that 'make remotesystem' on a fedora host as non-root is the same as 'sys remote fedora-36 rootless host'. I'll try rebasing to force the tests to re-run.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
