### PR TITLE
Use UNMERGED vbauerster/mpb PR to fix a pull deadlock

### PR DESCRIPTION
**Pull request by mtrmac**
```
go mod edit -replace github.com/vbauerster/mpb/v7=github.com/mtrmac/mpb/v7@abort-deadlock
make vendor
```

See https://github.com/vbauerster/mpb/issues/100 and https://github.com/vbauerster/mpb/pull/101 .

### CODE REVIEW

**Comment by mheon** [comment]
LGTM
@containers/podman-maintainers PTAL

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

Thank you, @mtrmac

**Comment by vrothberg** [comment]
@mtrmac, can you rerun `make vendor`? CI isn't happy with it it seems.

**Comment by vrothberg** [comment]
/hold cancel

Thanks again

**Pull request merged**
