### PR TITLE
[2.0] search: allow wildcards

### PR DESCRIPTION
**Pull request by vrothberg**
Allow wildcards in the search term.  Note that not all registries
support wildcards and it may only work with v1 registries.

Note that searching implies figuring out if the specified search term
includes a registry.  If there's not registry detected, the search term
will be used against all configured "unqualified-serach-registries" in
the registries.conf.  The parsing logic considers a registry to be the
substring before the first slash `/`.

With these changes we now not only support wildcards but arbitrary
input; ultimately it's up to the registries to decide whether they
support given input or not.

Fixes: bugzilla.redhat.com/show_bug.cgi?id=1846629
Cherry-pick-of: commit b05888a97dbb
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@mheon, I have missed backporting it. We need that in 2.0 to address the BZ.

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
2.0 branch CI is still broken

**Comment by vrothberg** [comment]
CI is turning healthy again (see the backport). Thanks, @baude for the pointers!

**Comment by mheon** [comment]
Are we sure this is OK to backport? It's technically a feature.

**Comment by vrothberg** [comment]
> Are we sure this is OK to backport? It's technically a feature.

I think so. We only backported the parts to update the new IDs and secrets.

**Comment by rhatdan** [comment]
I think this is fine to back port.

**Comment by vrothberg** [comment]
Cherry picked a couple more commits that turned the main branch green.

**Comment by vrothberg** [comment]
Aaaah, also had to update the in_podman:v2.0 image on quay.

**Comment by vrothberg** [comment]
@baude @giuseppe @mheon @rhatdan ... merge me!

**Comment by vrothberg** [comment]
\o/ we're green again

**Pull request merged**
