### PR TITLE
play kube: set defaults to container resources

### PR DESCRIPTION
**Pull request by ydayagi**
this fixes https://github.com/containers/podman/issues/13115

the change tries to imitate k8s behavior.
when limits are not set the container's limits are all CPU and all RAM
when requests are missing then they are equal to limits

Signed-off-by: Yaron Dayagi <ydayagi@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @ydayagi the linter does not like your tests.
@cdoern @vrothberg @umohnani8 PTAL

**Comment by TomSweeneyRedHat** [comment]
All kinds of red test unhappiness @ydayagi

**Comment by rhatdan** [comment]
I told it to retest, will see how it does.

**Comment by ydayagi** [comment]
@TomSweeneyRedHat I think it is related to
https://github.com/containers/podman/blob/main/troubleshooting.md#26-running-containers-with-cpu-limits-fails-with-a-permissions-error

**Comment by ydayagi** [comment]
@TomSweeneyRedHat @rhatdan 
looking at [troubleshooting-cpu-limits](https://github.com/containers/podman/blob/main/troubleshooting.md#26-running-containers-with-cpu-limits-fails-with-a-permissions-error)....
could it be that Podman tests do not take into account memory and cpu limits? perhaps we don't test 'play kube' with limits?
or maybe, we should avoid setting limits [(here)](https://github.com/containers/podman/blob/6ffd59828dd3c58c0927bd715e0a5a7b0c3baf2f/pkg/specgen/generate/kube/kube.go#L187) if user does not have permissions for it?

**Comment by rhatdan** [comment]
@cdoern @mheon PTAL

**Comment by Luap99** [comment]
Is a limit really what most people want by default? I don't have a opinion on that but I just want to make us aware that this will be a breaking change for users.

**Comment by cdoern** [comment]
I am pretty sure for most of these fields a limit of 0 is the default which mean no limit, why would we place a resource limit that users aren't aware of?

**Comment by haircommander** [comment]
I'm actually having a bit of trouble finding the default limits here. mostly because poking around the documentation keeps pointing to [limit ranges](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/) which allow you to customize the default limits and requests. @ydayagi do you have a pointer to where the defaults are specified in kube

**Comment by ydayagi** [comment]
> I'm actually having a bit of trouble finding the default limits here. mostly because poking around the documentation keeps pointing to [limit ranges](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/) which allow you to customize the default limits and requests. @ydayagi do you have a pointer to where the defaults are specified in kube

thank you all for your replies. I did not check the documentation. I tested a few times with an existing cluster. I think that as Dan mentioned we have to match the k8s behavior. Another reason to set default is the env var. If env var references the limit field but the field has no value then var value is wrong.

**Comment by ydayagi** [comment]
@rhatdan ?

**Comment by ydayagi** [comment]
> If you generate a Pod with this, what does the podman generate kube YAML look like? Do we need to strip all of these fields back out?

indeed the result of 'generate kube' changed. I will fix that.

**Comment by ydayagi** [comment]
@rhatdan I removed the default setting in the container object. Instead, I use default values when setting the env var value (func envVarValue).

**Comment by ydayagi** [comment]
@rhatdan
1. I could not figure out the reason for the failed tests. Can we restest?
2. I think I'll have to rename the PR and bug to something like: defaults for env from resource

**Pull request merged**
