### PR TITLE
[v3.0] fix RHEL gating test: the /sys thing

### PR DESCRIPTION
**Pull request by edsantiago**
Backport one component of #9091 in hopes of fixing RHEL8
gating test failures.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
/lgtm
/hold
until tests pass

**Pull request merged**
