### PR TITLE
Modify the pod name suffix '_pod' to '-pod'

### PR DESCRIPTION
**Pull request by aonoa**
Fixes: #13985 

Signed-off-by: wufan <1991849113@qq.com>

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM, whoops I created a similar PR

**Review by vrothberg — COMMENTED** [review]
Thanks for contributing!

Please update the `Signed-off-by` line in the commit message to include your real name. The guidelines do not allow pseudonyms (see https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs).

**Review by zhangguanzhang — APPROVED** [review]

**Comment by rhatdan** [comment]
Thanks @aonoa 
Putting the new book `Podman in Action` to good use, finding bugs.

**Comment by vrothberg** [comment]
> Please update the `Signed-off-by` line in the commit message to include your real name. The guidelines do not allow pseudonyms (see https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs).

My comment remained unaddressed.

**Comment by aonoa** [comment]
> > 请更新`Signed-off-by`提交消息中的行以包含您的真实姓名。该指南不允许使用假名（请参阅https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs）。
> 
> 我的评论仍未得到解决。

I've revised it.This is the Pinyin of my Chinese name

**Comment by vrothberg** [comment]
Apologies, I was unaware. Thank you!

**Pull request merged**
