### PR TITLE
[NO NEW TESTS NEEDED] Refactor podman container command output

### PR DESCRIPTION
**Pull request by jwhonce**
Leverage new report.Formatter allowing better compatibility from
podman command output.

See #10974
See #12455

Depends on containers/common#831

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@ashley-cui WDYT?

**Review by ashley-cui — COMMENTED** [review]
/lgtm

**Pull request merged**
