### PR TITLE
[CI:DOCS] update api versions on docs.podman.io

### LINKED ISSUE #16300: need doc updates on podman.io
The docs on podman.io do not list Podman v4.2 and v4.3. (see https://docs.podman.io/en/latest/Reference.html).

### PR DESCRIPTION
**Pull request by Luap99**
Fixes #16300

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@vrothberg PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks @Luap99 !

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
