### PR TITLE
[CI:DOCS] tag podmansh as tech preview in RELEASE_NOTES.md

### PR DESCRIPTION
**Pull request by lsm5**
#### Does this PR introduce a user-facing change?

```release-note
None
```

@ashley-cui @rhatdan @mheon PTAL

### CODE REVIEW

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Comment by lsm5** [comment]
ignore packit failures. Some issues with name resolution in fedora infra.

**Comment by mheon** [comment]
LGTM

**Comment by lsm5** [comment]
all set. mergeme

**Review by Luap99 — COMMENTED** [review]
Tech Preview is a RHEL term and should be in the RHEL release notes not upstream.
I doubt that normal users know what this means. And what does it even mean for us upstream? Are you planning to change the command later and do not want to call this stable? If this is the case it should be made explicit!

**Comment by vrothberg** [comment]
I think we did something similar for auto-updates at the beginning.  I don't think that "tech preview" is RHEL (only) term but used more widely to indicate that something is ready to try out but may change in the future until being marked as stable.

If that's the intention, we should mention that in that docs.

**Comment by lsm5** [comment]
> I think we did something similar for auto-updates at the beginning. I don't think that "tech preview" is RHEL (only) term but used more widely to indicate that something is ready to try out but may change in the future until being marked as stable.
> 
> If that's the intention, we should mention that in that docs.

`docs` meaning in the release notes entry or manpage or both?

/cc @rhatdan

**Comment by Luap99** [comment]
I would say both

**Comment by lsm5** [comment]
updated manpage and RELEASE_NOTES.md. PTAL

**Pull request merged**
