### PR TITLE
Better assert for test

### LINKED ISSUE #10948: APIv2 test: test_copy_to_container: False is not true
I'm seeing this flake on almost every PR:
```
[+0215s] ======================================================================
[+0215s] FAIL: test_copy_to_container (compat.test_containers.TestContainers)
[+0215s] ----------------------------------------------------------------------
[+0215s] Traceback (most recent call last):
[+0215s]   File "/var/tmp/go/src/github.com/containers/podman/test/python/docker/compat/test_containers.py", line 232, in test_copy_to_container
[+0215s]     self.assertTrue(out.startswith(b'1042:1043'), "assert correct uid/gid")
[+0215s] AssertionError: False is not true : assert correct uid/gid
[+0215s] 
[+0215s] ----------------------------------------------------------------------
```
For example: [here](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5246553477611520/html/apiv2-podman-fedora-34-root-host.log.html) 

When fixed, could you please make the error message a little bit more helpful than "false is not true"?

### PR DESCRIPTION
**Pull request by matejvasek**
resolves #10948

Signed-off-by: Matej Vasek <mvasek@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@jwhonce PTAL

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by matejvasek** [comment]
@edsantiago is working on different solution

**Comment by rhatdan** [comment]
@matejvasek @edsantiago What should we do with this PR?

**Pull request closed without merging**
