### PR TITLE
podman-play system test: refactor

### PR DESCRIPTION
**Pull request by edsantiago**
The test file was a rat's nest of long complicated yaml strings
all differing only slightly. Clean it up, by adding a helper
function with optional parameters.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Waiting for #17058; I will rebase once that merges. I just want to see if there are any gotchas I missed in my local testing.

**Comment by edsantiago** [comment]
@vrothberg PTAL (low priority)

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks!

@containers/podman-maintainers PTAL

**Comment by vrothberg** [comment]
@giuseppe @flouthoc can we merge it?  I need to touch the test file and want to avoid merge conflicts.

**Comment by vrothberg** [comment]
Thanks, Paul!

**Pull request merged**
