### PR TITLE
Add support for host keys for non-22 ports (v2.1)

### LINKED ISSUE #8139: Host key validation doesn't work when not using port 22
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The retrieval of the HostKey doesn't account for ports, and fails to find the proper host key.

Unfortunately the fallback for FixedHostKey is InsecureIgnoreHostKey, so no error is shown.

**Steps to reproduce the issue:**

1. `# run "minikube podman-env" to set up the podman environment for connecting to podman`

2. `export CONTAINER_HOST="ssh://docker@127.0.0.1:32811/run/podman/podman.sock?secure=True"`

3. `podman-remote version`

**Describe the results you received:**

Happily connects, even when the host key has been changed (or not properly updated)

So the "secure" parameter doesn't have any effect, behaves the same as without "secure"

**Describe the results you expected:**

`Error: Failed to create sshClient: Connection to bastion host (ssh://docker@127.0.0.1:32811/run/podman/podman.sock?secure=True) failed.: ssh: handshake failed: ssh: host key mismatch`

Using a regular `ssh` connection rightfully complains about the connection not being secure:

```console
$ ssh -p 32811 docker@127.0.0.1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:Mk7G0Bq+dUQ72wgtkb+gG4brTiI0+diQIR6Y0aFlhRs.
Please contact your system administrator.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Only happens when using a ssh port other than 22.

**Output of `podman version`:**

```
Client:
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64

Server:
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04

### PR DESCRIPTION
**Pull request by afbjorklund**
For #8139

Patch against release version (2.1.1), can be rebased against master.

### CODE REVIEW

**Comment by mheon** [comment]
Master is probably better if you can wait a week or so - we're going to start cutting RCs for 2.2 this week, release hopefully early next week.

**Comment by afbjorklund** [comment]
> Master is probably better if you can wait a week or so - we're going to start cutting RCs for 2.2 this week, release hopefully early next week.

No problem, can do a rebase in a PR (just that 2.1.1 was the one that I tested with...)

**Comment by afbjorklund** [comment]
Seems like the "merge conflicts" were only in the version files anyway

**Pull request merged**
