### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**

### CODE REVIEW

**Comment by vrothberg** [comment]
The CI is enforcing changes to tests for commits.  Can you add `[NO TESTS NEEDED]` to the body of your commit message and repush?

@edsantiago, `nix/*` may be a candidate for the positive list.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM
Once you sign your PR.
/approve

**Comment by edsantiago** [comment]
@hswong3i instead of adding `NO TESTS NEEDED`, I think we're all totally fine if you include this as part of your PR:
```diff
diff --git a/contrib/cirrus/pr-should-include-tests b/contrib/cirrus/pr-should-include-tests
index caf27cf83..a3b4847a7 100755
--- a/contrib/cirrus/pr-should-include-tests
+++ b/contrib/cirrus/pr-should-include-tests
@@ -39,6 +39,7 @@ filtered_changes=$(git diff --name-status $base $head |
                        egrep -v  '^contrib/'          |
                        egrep -v  '^docs/'             |
                        egrep -v  '^hack/'             |
+                       egrep -v  '^nix/'              |
                        egrep -v  '^vendor/'           |
                        egrep -v  '^version/')
 if [[ -z "$filtered_changes" ]]; then
```

**Comment by cevich** [comment]
> nix/* may be a candidate for the positive list.

Hrmmm...I *swore* I added that already in one of my PRs....yep, it's already there.  Probably just need to rebase this PR.

**Comment by hswong3i** [comment]
> > nix/* may be a candidate for the positive list.
> 
> Hrmmm...I _swore_ I added that already in one of my PRs....yep, it's already there. Probably just need to rebase this PR.

rebased ;-)

**Pull request merged**
