### PR TITLE
ci: force scratch build for crun

### PR DESCRIPTION
**Pull request by giuseppe**
force a version with this fix: https://github.com/containers/crun/pull/819

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
Should this be marked as a [WIP]

**Comment by vrothberg** [comment]
> Should this be marked as a [WIP]

I think this get in ASAP. Once an updated crun made it into F35, we can revert the change.

**Pull request merged**
