### PR TITLE
[CI:DOCS] Cirrus: Update meta-task for EC2 image

### PR DESCRIPTION
**Pull request by lsm5**
Copied from: https://github.com/containers/aardvark-dns/pull/207

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
need to add secrets

**Review by cevich — APPROVED** [review]
/lgtm
/hold

**Comment by cevich** [comment]
If the new image is causing problems, feel free to omit that.  Also, if all you're updating is the meta-task, doing a `[CI:DOCS]` PR is perfectly fine.

**Pull request merged**
