### PR TITLE
I believe that these tests will now run with crun.

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@adrianreber @giuseppe These are still broken on crun?

**Comment by adrianreber** [comment]
> @adrianreber @giuseppe These are still broken on crun?

Yes, the PR to fix it is open but I am waiting for CRIU PRs to merge and then we also need a CRIU release for the crun changes to work.

This cannot work yet in Podman.

**Comment by rhatdan** [comment]
@giuseppe Any movement on this?

**Comment by giuseppe** [comment]
the changes are already included in a crun release

**Comment by cevich** [comment]
> a crun release

Any idea of the version number of the package?

**Comment by giuseppe** [comment]
> Any idea of the version number of the package?

1.4.2 has all the changes we need in Podman

**Comment by adrianreber** [comment]
CRIU 3.17 is not yet released, so this will not yet work. Once 3.17 is released crun needs to be rebuilt and then Podman can use crun for these tests.

**Comment by cevich** [comment]
Thanks for the info guys.  Someone please just @mention me once CRIU & crun are available at least in the `updates-testing` channel for Fedora (probably F36 I'm guessing).

**Comment by vrothberg** [comment]
Release is still pending.

**Comment by baude** [comment]
@rhatdan @adrianreber do we want this in 4.1?

**Comment by cevich** [comment]
> latest runc is not released to ubuntu.

:disappointed: our ubuntu images are out of date.  They need bumping up to 22.04 - which probably has newer versions.

**Comment by rhatdan** [comment]
@cevich Are you going to make this happen?

**Comment by cevich** [comment]
> @cevich Are you going to make this happen?

Thanks for reminding me. I'm currently loaded up with this AWS stuff, and it would be useful and good test of the docs to see if someone else can do it.  I realize that's probably a big ask.  Let me craft an e-mail and see if anyone bites (unless you have a better idea).

**Comment by cevich** [comment]
@lsm5 FYI - this PR is driving the need for new images (including Ubuntu).

**Comment by lsm5** [comment]
new ubuntu happening at https://github.com/containers/automation_images/pull/134

**Comment by vrothberg** [comment]
Are we ready to go?

**Comment by cevich** [comment]
It would be informative to try this PR with the updated image ID in #14397 Though there is currently an outstanding issue with the Ubuntu VMs, the Fedora ones should work.  So if they fail for this PR, it could be an indicator `runc-1.1.1-1.fc36` still isn't new enough (I'm guessing).

**Comment by cevich** [comment]
> the issue here is with crun not runc.

Before you commented:

    No this is just adding tests, which should work on latest runc, problem is latest runc is not released to ubuntu.

In any case, you might try rebasing onto https://github.com/containers/podman/pull/14397 as it has updated images all around.  Looks like:

* F35: `crun-1.4.5-1.fc35-x86_64` and `runc-1.1.1-1.fc35-x86_64`
* F36: `crun-1.4.5-1.fc36-x86_64` and `runc-1.1.1-1.fc36-x86_64`
* U21104: `crun-1.4.5-0ubuntu22.04+obs31.1-amd64` and `runc-1.1.0-0ubuntu1-amd64`

**Comment by rhatdan** [comment]
Miracle of Miracle, this finally past tests. Only started on this back in January 14

@giuseppe @cevich @edsantiago @vrothberg PTAL
@containers/podman-maintainers PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
Congrats on getting in :partying_face:

**Pull request merged**
