### PR TITLE
Cirrus: Update for v2.2 branch

### PR DESCRIPTION
**Pull request by cevich**
Update the internal reference to the base-branch name to support behavior divergence vs master branch.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

**Comment by cevich** [comment]
Note: I've updated the release google-doc to reflect this `.cirrus.yml` change.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
