### PR TITLE
Bump github.com/containers/buildah to v1.26.4

### PR DESCRIPTION
**Pull request by nalind**
#### What is all this?

Bump github.com/containers/buildah from an arbitrary commit on its main branch to v1.26.4, bumping github.com/containers/common slightly to v0.49.1.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@edsantiago, any advice on how to make the tests happy?

**Comment by edsantiago** [comment]
Yes, the [treadmill](https://github.com/containers/podman/wiki/Buildah-Vendor-Treadmill#for-vendoring-buildah-start-here). That is literally the exact point of the treadmill and why I spend time every day managing it.

**Comment by edsantiago** [comment]
oh..... this is 4.2. Sorry, no idea. The errors look exactly the same as others that have been resolved in the treadmill, so I would _guess_ that you need to cherry-pick parts of the treadmill PR or perhaps parts of main that have already been merged.

**Comment by edsantiago** [comment]
okay, this is getting weirder. How certain are we that this is a good thing to do? It looks like `v1.26.4` actually removes stuff that was in `v1.26.1-0.20220716095526`. Like, tests that existed in the old version, no longer exist in the new one.

**Comment by edsantiago** [comment]
If it is confirmed that this is a proper version of buildah to include here, even with all the removals, [pr15180.diff.txt](https://github.com/containers/podman/files/9255267/pr15180.diff.txt) should at least get the bud tests to run. I have not checked if they will pass.

**Comment by flouthoc** [comment]
All of the tests pass except two and they are failing because of wrong error message I think reason for two of them is below and one tests need to be skipped for remote:

I pushed @edsantiago's diff but it looks like we would also need https://github.com/containers/buildah/pull/4096 to be backported and following diff on top of @edsantiago 's patch since I think in https://github.com/containers/buildah/pull/4162 env variable test is merged with `bud with Containerfile.in` and we don't pass env variable on remote, on buildah upstream this is a different test afaics i.e `bud with Containerfile.in, via envariable`
```diff
diff --git a/test/buildah-bud/apply-podman-deltas b/test/buildah-bud/apply-podman-deltas
index 1f6bf4e1b..f76fba760 100755
--- a/test/buildah-bud/apply-podman-deltas
+++ b/test/buildah-bud/apply-podman-deltas
@@ -196,6 +196,9 @@ skip_if_remote "--build-context option not implemented in podman-remote" \
                "build-with-additional-build-context and COPY, additional context from host" \
                "build-with-additional-build-context and RUN --mount=from=, additional-context not image and also test conflict with stagename" \
 
+skip_if_remote "env-variable for Containerfile.in pre-processing is not propagated on remote" \
+               "bud with Containerfile.in" \
+
 # Requires a local file outside context dir
 skip_if_remote "local keyfile not sent to podman-remote" \
                "bud with encrypted FROM image"
```

**Comment by flouthoc** [comment]
and I think this is needed for `not ok 177 bud without any arguments should fail when no Dockerfile exist`

```diff
diff --git a/test/buildah-bud/apply-podman-deltas b/test/buildah-bud/apply-podman-deltas
index 1f6bf4e1b..04adf71de 100755
--- a/test/buildah-bud/apply-podman-deltas
+++ b/test/buildah-bud/apply-podman-deltas
@@ -134,6 +134,10 @@ errmsg "is not a file" \
        "Error: containerfile: .* cannot be path to a directory" \
        "bud with specified context should fail if assumed Dockerfile is a directory"
 
+errmsg "no such file or directory" \
+       "Error: no context directory and no Containerfile specified" \
+       "bud without any arguments should fail when no Dockerfile exists"
+
 errmsg "no such file or directory" \
        "context must be a directory" \
        "bud with specified context should fail if context contains not-existing Dockerfile"
```

**Comment by rhatdan** [comment]
We need to be releasing buildah 1.27 and updating podman 4.2 to use it.  I don't understand why we are using an older version of Buildah?  We never cut a v1.27 release.  But we were using pre-releases of this in previous RC candidates.  I believe the correct thing to do is cut a new Buildah release and vendor it into podman 4.2.

**Comment by edsantiago** [comment]
Thanks @rhatdan, I think that explains it. Yes, `1.26.4` truly is older than what we had. I think we need to step back and figure out if we truly want an older buildah here or not.

**Comment by nalind** [comment]
> We need to be releasing buildah 1.27 and updating podman 4.2 to use it. I don't understand why we are using an older version of Buildah?

You expressed a preference for doing so in https://github.com/containers/buildah/pull/4152.

**Comment by edsantiago** [comment]
I've never found any good tools for simplifying git forks, so I'm having to do this by hand, so this may not make sense.

Buildah `v1.26.0` is forked on May 4. Podman `v4.2` is forked July 11, but is vendoring buildah from its *main* branch, not the `1.26` one. La la la, move along, more vendoring, but still from *main*.

Now this PR comes along and switches everything to buildah `v1.26` branch, which does not have the stuff that is on buildah main. This is a big revamp. And I think it is wrong, more so given the late stage of podman v4.2. I don't think we can switcheroo like that. But I'm feeling really lost here. Who has good tools for visualizing git trees with focus on specific branches and commits?

**Comment by flouthoc** [comment]
> > We need to be releasing buildah 1.27 and updating podman 4.2 to use it. I don't understand why we are using an older version of Buildah?
> 
> You expressed a preference for doing so in [containers/buildah#4152](https://github.com/containers/buildah/pull/4152).

cc @TomSweeneyRedHat

**Comment by edsantiago** [comment]
This has really been bothering me all day... so here is the cleanest, simplest way I can find to show what happened. This is the buildah repo, with tags I've added (locally) showing *podman* PRs that vendored in new buildah.
```console
$ git log --graph --simplify-by-decoration --pretty=format:'%h %d' v1.26.0^..main v1.26.0^..v1.26.4
* 981f8017  (tag: v1.26.4)
* ad138d8e  (tag: v1.26.3)
* 19159983  (tag: v1.26.2)
* 6e2ec2eb  (tag: v1.26.1, tag: pr14118_dan_may05)
| * 053d7808  (HEAD -> main)
| * d31d27c3  (tag: podman_v4.2_rc2)
| * e66309eb  (tag: pr14561_dan_jun14)
| * 005447be  (tag: pr14526_valentin_jun10)
| * 5500333c  (tag: pr14320_adi_may27)
|/  
* 0a9d6e6e  (tag: v1.26.0)
```
Following that chronologically, what seems to have happened is:
| date | PR | what |
|---|---|---|
| 05-04 | - | buildah v1.26.0 tagged |
| 05-05 | #14118 | vendor buildah v1.26.1 into podman main |
| 05-27 | #14320 | vendor buildah v1.26.1-0.20220524184833-5500333c2e06 into podman main |
| ..... etc .... |

I think #14230 is where things started to go wrong. Although the tag _says_ v1.26.1, 5500333c is a commit on the `buildah main` branch, not `release-1.26`. From here on out, all subsequent vendor-buildah-into-podman PRs pulled in `buildah main`, which is the `1.27` track, not `1.26`.

This PR (this one, the one I'm commenting on) reverts back to `buildah 1.26` track. I am not informed enough to know if that's a good thing or a bad thing. What I can say is that it's a big thing, because podman hasn't been using nor testing anything on the `buildah v1.26` track since May 27.

I truly hope this helps.

**Comment by flouthoc** [comment]
@edsantiago ah I see what happened here now, thanks for sharing this. I wonder why go modules is still resolving `main` to older version if I do `go mod edit -replace github.com/containers/buildah=github.com/containers/buildah@main` it keeps resolving to `go: downloading github.com/containers/buildah v1.26.1-0.20220803165559-053d7808c144` where release is the old one but commit on the `main` or is there someway else to update this dep and point to unreleased branch ?. But I guess podman `main` should always be using commit from buildah `main`.

**Review by flouthoc — APPROVED** [review]
PR is green, LGTM if we are tweaking `apply-podman-deltas` and don't want to do a bump for https://github.com/containers/buildah/pull/4166 now but since its just error message change I don't have any strong opinion and we can do this later on if we vendor `1.26.5` into `4.2` branch.

**Comment by vrothberg** [comment]
> @edsantiago ah I see what happened here now, thanks for sharing this. I wonder why go modules is still resolving `main` to older version if I do `go mod edit -replace github.com/containers/buildah=github.com/containers/buildah@main` it keeps resolving to `go: downloading github.com/containers/buildah v1.26.1-0.20220803165559-053d7808c144` where release is the old one but commit on the `main` or is there someway else to update this dep and point to unreleased branch ?

That is a bug in `go mod`.  _Never_ trust go's "guess" when vendoring a commit or from a branch. `v1.26.1` means exactly that but `v1.26.1-....-$commit` means "anything after v1.26.1 and exactly $commit`.

**Comment by TomSweeneyRedHat** [comment]
OK, quite the quandary here.  Normally I'd say let's stick with v1.26.* for Podman v4.2 as that is what we committed to, and I thought we had been testing with.

However, we have apparently been testing with v1.27, although called v1.26, and it would be cleaner long-term support-wise to create a release-1.27 branch for use in the future for changes for RHEL 8.7 and 9.1.  

So given all that, let's plan to create v1.27 ASAP and then vendor that into RHEL 4.2.  If anyone has strong countering opinions, please holler.

**Comment by TomSweeneyRedHat** [comment]
And apologies to all for the hoops hopped through to get this PR together.  I'm going to close this one for now.

**Comment by rhatdan** [comment]
If I committed to an older buildah, then I screwed up.  We release new versions of Buildah Skopeo Podman at approximately the same time.  We have lots of new features in Buildah that we want to get into podman build.  I see no reason to update a version of Buildah that was cut back in May.  Podman 4.2 should have the latest of everything storage, image, common, and buildah.

**Comment by mheon** [comment]
I completely concur with going with 1.27, if we've been using a newer version in RCs we should not downgrade.

**Comment by flouthoc** [comment]
Reopening this: https://github.com/containers/buildah/pull/4152 and preparing vendor PR for podman[4.2] here https://github.com/containers/podman/pull/15234

**Pull request closed without merging**
