### PR TITLE
fix: Container.cGroupPath() skip empty line to avoid false error logging

### PR DESCRIPTION
**Pull request by ttys3**
fixup https://github.com/containers/podman/issues/14146

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by giuseppe** [comment]
CI failures are unrelated, I've opened a PR to address them: https://github.com/containers/podman/pull/14152

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
LGTM once CI goes green

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the CI errors are happy
#14152 merged about 10 hours ago, if you have not rebased since then, you probably should.

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
