### PR TITLE
[CI:DOCS] Fix: broken links in transfer doc

### PR DESCRIPTION
**Pull request by Kiritow**
Fix broken `podman healthcheck` link

### CODE REVIEW

**Comment by mheon** [comment]
LGTM, but missing a sign off. You can run ‘git commit --amend -s’ and force
push to fix CI.

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
once signed

**Review by vrothberg — COMMENTED** [review]
/lgtm

Thank you!

**Pull request merged**
