### PR TITLE
Remove the unused machine volume-driver

### PR DESCRIPTION
**Pull request by afbjorklund**
The driver is now hardcoded again, and there can only be one type of mounts at a time (which one changes over time)

Revert "Make it possible to select the volume driver" This reverts commit 6630e5cf66cf76aefcfe9caebe5df4f37dd0bdd5.

The driver is now always virtiofs(d).

Previously it was always virtfs (9p).

#### Does this PR introduce a user-facing change?

```release-note
Remove the --volume-driver flag from podman machine init.
```

/cc @baude 

----

The flag was introduced, so that users could choose between sshfs and virtfs drivers:

* https://github.com/containers/podman/pull/12584

Mostly because some operating systems do not support 9p filesystems, such as RHEL

The real name should have been "reverse-sshfs", since it is calling back (to sftp on host)

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@baude @ashley-cui PTAL

**Review by ashley-cui — COMMENTED** [review]
Does this count as a breaking change, should we deprecate this first?

**Comment by afbjorklund** [comment]
> Does this count as a breaking change, should we deprecate this first?

It was a breaking change already in 5.0, when the flag got disconnected...

commit 9bb191df51c7f2d242835e2af0bfa19d781b2256

But there were never any options for the flag anyway, so it was a no-op.

```go
       var volumeType string
       switch opts.VolumeDriver {
       // "" is the default volume driver
       case "virtfs", "":
               volumeType = VolumeTypeVirtfs
       default:
               return fmt.Errorf("unknown volume driver: %s", opts.VolumeDriver)
       }
```
```

**Comment by mheon** [comment]
Maybe mark the flag as hidden for a few releases (print a warning on use) and remove in ~5.4 timeframe later this year?

**Comment by afbjorklund** [comment]
> Maybe mark the flag as hidden for a few releases (print a warning on use) and remove in ~5.4 timeframe later this year?

Wouldn't you have to change the value of it then? It would be weird to continue using `--volume-driver=virtfs` in 5.2

**Comment by rhatdan** [comment]
@mheon @ashley-cui PTANL?

**Review by ashley-cui — COMMENTED** [review]
Could you add a warning if someone tries to set the flag? Maybe mention that it's a no-op and the flag will be removed in a future release?

**Comment by afbjorklund** [comment]
I marked it as "deprecated" instead, even though it was removed in Podman 5.0 already. 

It is still hidden (and the docs removed), but now you get a warning if you try to use it:

`Flag --volume-driver has been deprecated, will be ignored`

**Review by ashley-cui — COMMENTED** [review]
Perfect, thanks! LGTM

**Pull request merged**
