### PR TITLE
pkg/domain: Add terminal support for FreeBSD

### PR DESCRIPTION
**Pull request by dfr**
This just moves the code to files which can be shared with freebsd.

[NO NEW TESTS NEEDED]

Signed-off-by: Doug Rabson <dfr@rabson.org>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
Restarted two test failures, probably flakes.

LGTM

**Comment by dfr** [comment]
A few tests are still failing - I'll take a look over the weekend.

**Comment by dfr** [comment]
I rebased to trigger a retest and that seems to work. I don't think the rebase fixed anything - the failing tests were all 'podman search' tests which depend on the health of external services such as docker.io and quay.io so hard to avoid flakiness.

**Pull request merged**
