### PR TITLE
Cleanup build scratch dir if remote end disconnects while passing the context

### PR DESCRIPTION
**Pull request by garthy**
So if the remote ends discoonects then the scratch dir with context can be lefter around.

This moves the defered cleanup func to stop this happening.

#### Does this PR introduce a user-facing change?

None

```release-note
Make sure we always clean up the remote build context on error  
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Can you add a test for this?

**Comment by garthy** [comment]
Yeah I'm not sure how as I'm pretty new to the podman code base (few days)
and this sort of test where we cancel while a remote context is being
transferred can be racy if not done correctly.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
I don't think we need a new test.

**Review by Luap99 — APPROVED** [review]
Agreed, trying to test this without races is way to complicated. 
/lgtm

**Pull request merged**
