### PR TITLE
Bump to v4.0.0 final

### PR DESCRIPTION
**Pull request by mheon**
As the title says. Final backports, release notes updates, and the version bump.

### CODE REVIEW

**Comment by mheon** [comment]
Failures are real. It's related to the minimum API version bump to v4.0.0, and it's somewhere in the manifest endpoints. Tests look sane, code is suspicious - https://github.com/containers/podman/blob/main/pkg/bindings/manifests/manifests.go#L110 references API versions under v4.0?

Will continue looking but I am not an expert on this part of the code

@jwhonce PTAL

**Comment by TomSweeneyRedHat** [comment]
I suspect it has to do with the wrapper to support v3.2 with 4.x libpod.  My brain is too fried however.  I've pinge @jwhonce @flouthoc and @Luap99 to PTAL

https://github.com/containers/podman/commit/8a7e70919f4bab0757523ae97c170396cb13c83d#diff-044d310f157316ea3de231effda8f6822c587dd263482131fc09b6a2c12b0ddaR167

**Review by flouthoc — COMMENTED** [review]
@TomSweeneyRedHat I am not a lot familiar with recent changes that went into `manifests list operations` API, I think @jwhonce can tell this better but here is what i think is causing the issues.

With operations for service version greater than or equal to `4.0.0` now libpod uses a common `PUT` to `/manifests` with operation selected in `payload` and new flow calls `func ManifestModify(` in the end.

I think there might be issue in the way we are handling error here https://github.com/containers/podman/blob/main/pkg/api/handlers/libpod/manifests.go#L399. 
It could use `utils.Error(` to write error as it looks like in some cases error is being returned correctly but for some cases it is not writing error payload and also ignoring actual status. 

But this is just my suspect I'm sure @jwhonce can tell this better.

**Comment by mheon** [comment]
Repushed with Jhon's fixes included

**Comment by mheon** [comment]
Two flakes. Rerunning.

**Pull request merged**
