### PR TITLE
Fixes automated WSL installation on ARM

### PR DESCRIPTION
**Pull request by n1hility**
This PR builds on #16987, although the merge order does not matter, since it simply updates the installer.

This PR changes the custom action used to check the need for WSL installation to be a simple native C based win32 implementation as opposed to the cgo c-shared DLL approach used previously. This change is necessary to resolve compatibility problems with the Windows x86_64 emulation layer on ARM, which struggles with hot-loading a translated goruntime into an existing process (in contrast, standard executables and hard-linking work fine).  Once this issue is resolved, this could be converted back to cgo for project consistency.

While the language has changed for the podman-msihooks.dll artifact, the existing process, pre-requisites, and build steps remain the same (cgo already required we had a win32 c compiler toolchain installed)

As mentioned in #16987, future PRs will update the installer to bundle arm64 podman remote client binaries. However, this is not necessary at this stage. 

The installer itself, and it's supporting code will remain x86, even though it will eventually also package ARM binaries, for two reasons:

1. We can have one installer download, no matter the platform (prevents picking the wrong one)
2. Since the incentives are low (no discernable perf difference for an installer), it will be some time before the mainstream Windows installer toolchains (e.g. Wix) fully support the option.

```release-note
Fixes WSL auto-installation when run under Windows ARM x86_64 emulation
```
[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@gbraad PTAL

**Comment by edsantiago** [comment]
All PRs are failing CI today:
```
Downloading https://api.cirrus-ci.com/v1/artifact/build/5589793266991104/Windows Cross/repo/repo.tbz to repo.tbz2
arc : The term 'arc' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\contrib\c
irrus\win-installer-main.ps1:42 char:1
+ arc unarchive repo.tbz2 .; CheckExit
+ ~~~
    + CategoryInfo          : ObjectNotFound: (arc:String) [], ParentContainsE 
   rrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

@n1hility could this be related, or is it just coincidence?

**Comment by n1hility** [comment]
> All PRs are failing CI today:
> 
> ```
> Downloading https://api.cirrus-ci.com/v1/artifact/build/5589793266991104/Windows Cross/repo/repo.tbz to repo.tbz2
> arc : The term 'arc' is not recognized as the name of a cmdlet, function, 
> script file, or operable program. Check the spelling of the name, or if a path 
> was included, verify that the path is correct and try again.
> At C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\contrib\c
> irrus\win-installer-main.ps1:42 char:1
> + arc unarchive repo.tbz2 .; CheckExit
> + ~~~
>     + CategoryInfo          : ObjectNotFound: (arc:String) [], ParentContainsE 
>    rrorRecordException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```
> 
> @n1hility could this be related, or is it just coincidence?

@edsantiago i think this is unrelated. Will take a look,

**Pull request merged**
