### PR TITLE
e2e create same-IP: try to fix flake

### PR DESCRIPTION
**Pull request by edsantiago**
Our friend #7096 is still not fixed: it continues to flake,
singletons only, and only in the "create" test (not "run").

My guess: maybe there's a race somewhere in IP assignment,
such that container1 can have an IP, but not yet be running,
and a container2 can sneak in and start with that IP, and
container1 is the one that fails?

Solution: tighten the logic so we wait for container1 to
truly be running before we start container2. And, when we
start container2, do so with -a so we get to see stdout.
(Am not expecting it to be helpful, but who knows).

Also very minor cleanup

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
Recent failures:

* fedora-36 : int podman fedora-36 root container sqlite
    * [03-28 22:06](https://api.cirrus-ci.com/v1/artifact/task/6579579771420672/html/int-podman-fedora-36-root-container-sqlite.log.html#t--Podman-create-two-containers-with-the-same-IP--1) in Podman create with --ip flag [It] Podman create two containers with the same IP
    * [03-28 11:11](https://api.cirrus-ci.com/v1/artifact/task/5157108782465024/html/int-podman-fedora-36-root-container-sqlite.log.html#t--Podman-create-two-containers-with-the-same-IP--1) in Podman create with --ip flag [It] Podman create two containers with the same IP
* fedora-36 : int remote fedora-36 root host sqlite [remote]
    * [04-24 12:44](https://api.cirrus-ci.com/v1/artifact/task/6286884284923904/html/int-remote-fedora-36-root-host-sqlite.log.html#t--Podman-create-two-containers-with-the-same-IP--1) in Podman create with --ip flag [It] Podman create two containers with the same IP

All of them in my no-flake-retries PR, which means this is almost certainly happening in production CI, but my flake logger is not seeing those.

**Comment by Luap99** [comment]
I don't think this is possible, start should block until the container is started which means it also has to wait for the complete network setup. The whole loop here wait for the ip address to be assigned makes no sense to me. If this is needed podman start is seriously broken.

**Comment by edsantiago** [comment]
@Luap99 if what you say is correct, the test will continue to flake. Here's a question I've long wondered about: does ginkgo have a mechanism for running code on failure? Like:
```go
    Expect("this").ButIfItFailsThen("podman exec container1 ip a or podman logs or something")
```

**Comment by Luap99** [comment]
> @Luap99 if what you say is correct, the test will continue to flake. Here's a question I've long wondered about: does ginkgo have a mechanism for running code on failure? Like:
> 
> ```go
>     Expect("this").ButIfItFailsThen("podman exec container1 ip a or podman logs or something")
> ```

So I assume you want to execute further commands to debug in this case? I don't think this is directly supported. However what could work is using the extra annotations and pass a function that executes the commands.
https://onsi.github.io/gomega/#annotating-assertions (last example)

**Comment by edsantiago** [comment]
Well, [phooey](https://api.cirrus-ci.com/v1/artifact/task/4968190518755328/html/int-podman-fedora-37-root-container-sqlite.log.html#t--Podman-create-two-containers-with-the-same-IP--1)

**Comment by Luap99** [comment]
> Well, [phooey](https://api.cirrus-ci.com/v1/artifact/task/4968190518755328/html/int-podman-fedora-37-root-container-sqlite.log.html#t--Podman-create-two-containers-with-the-same-IP--1)

Not sure if I should be happy that I was right or hate the fact that something super strange is going on, maybe both? 
In any case the network code is 100% locked I have no doubt there. Also based on the links above failure is happening with both netavark and CNI so the error is not inside the ip allocation logic (unless both CNI are netavark have the same bug despite using completely different implementations).

One thing that could cause the behavior is when the first container dies after inspect but before the start test2 call. Not that I belive that this is the case but you are right we need to instrument the tests to gather more data after the failure.

Please reopen the issue I can take a look tomorrow.

**Pull request merged**
