### PR TITLE
Add podman(1) to the list of man pages on docs.podman.io

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

Addresses: #7219

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
I like simple solutions.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan The proof will be in the pudding.  Right now the "ubuntu-20 root host" test is timing out.  I tried restarting. 

But yeah, almost too simple.  I spent more time than I'd like to admit to looking for how that file was generated....

**Comment by TomSweeneyRedHat** [comment]
@baude @mheon @edsantiago any ideas on how to restart the failing test?  It just seems to not re-run for me when I press the link.

**Comment by edsantiago** [comment]
@TomSweeneyRedHat I see a bunch of re-runs all started within what looks like a few minutes of each other; maybe it was a Cirrus feedback hiccup? Anyway, the last one failed (with what looks like the usual Toolbox flake), so I did a re-run of my own.

**Comment by edsantiago** [comment]
Hey, this has a slash-l-g-t-m while CI is still running. Isn't there some sort of problem with that? Adding hold in case it makes CI stop flaking.

/hold

**Comment by mheon** [comment]
Yes, that will cause the bot to spin until a merge is possible so we want to avoid it.

**Pull request merged**
