### PR TITLE
pkg/rootless: simplify reexec for container code

### PR DESCRIPTION
**Pull request by Luap99**
The code currently tried to avoid joining the userns from conmon directly and rather joined to only read the pid file and then send this back to use so we could join the userns. From the comment this was done because we could not read the pid file. However this is no longer true as of commit 49eb5af301 and file is no always owned by the real user.

This means we can just remove this special logic and join the namespace directly there. A test has been added to check the rejoin logic with a custom uidmapping.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@giuseppe PTAL

I am seeing a weird flake
```
podman run --cgroups=disabled --cgroupns=host --rm quay.io/libpod/testimage:20240123 cat /proc/self/cgroup
level=error msg="invalid internal status, try resetting the pause process with \"/var/tmp/go/src/github.com/containers/podman/bin/podman system migrate\": cannot read \"/run/containers/storage/overlay-containers/ff09de79252dfa141b10052ab324660e0f0099c06e7a63d2c2f2b699dcb2ab06/userdata/conmon.pid\": EOF"
```
https://api.cirrus-ci.com/v1/artifact/task/4669127560790016/html/sys-podman-fedora-40-root-host-sqlite.log.html

The error was part of the here removed code so I hope it fixes something. But even if it does not fix the flake this seems simpler now and we can remove a bunch of (almost never used) code.

**Comment by giuseppe** [comment]
> @giuseppe PTAL
> 
> I am seeing a weird flake

I think I've introduced the issue with 1322f3193b8903fef1d0ccb21ead85ba2678eb64

We should not attempt to join any user namespace if we already have CAP_SYS_ADMIN and running with euid == 0.

What do you think about adding the following change?

```diff
diff --git a/pkg/domain/infra/abi/system_linux.go b/pkg/domain/infra/abi/system_linux.go
index db51f4d4d..29dda42c2 100644
--- a/pkg/domain/infra/abi/system_linux.go
+++ b/pkg/domain/infra/abi/system_linux.go
@@ -30,15 +30,16 @@ func (ic *ContainerEngine) SetupRootless(_ context.Context, noMoveProcess bool,
                }
        }
 
+       hasCapSysAdmin, err := unshare.HasCapSysAdmin()
+       if err != nil {
+               return err
+       }
+
        configureCgroup := cgroupMode != "disabled"
-       if configureCgroup {
+       // check for both euid == 0 and CAP_SYS_ADMIN because we may be running in a container with CAP_SYS_ADMIN set.
+       if os.Geteuid() == 0 && hasCapSysAdmin {
                // do it only after podman has already re-execed and running with uid==0.
-               hasCapSysAdmin, err := unshare.HasCapSysAdmin()
-               if err != nil {
-                       return err
-               }
-               // check for both euid == 0 and CAP_SYS_ADMIN because we may be running in a container with CAP_SYS_ADMIN set.
-               if os.Geteuid() == 0 && hasCapSysAdmin {
+               if configureCgroup {
                        ownsCgroup, err := cgroups.UserOwnsCurrentSystemdCgroup()
                        if err != nil {
                                logrus.Infof("Failed to detect the owner for the current cgroup: %v", err)
@@ -55,8 +56,8 @@ func (ic *ContainerEngine) SetupRootless(_ context.Context, noMoveProcess bool,
                                        }
                                }
                        }
-                       return nil
                }
+               return nil
        }
 
        pausePidPath, err := util.GetRootlessPauseProcessPidPath()
```

**Comment by Luap99** [comment]
looks good, but I assume we can also keep my change here as the code is no longer needed?

**Comment by giuseppe** [comment]
> looks good, but I assume we can also keep my change here as the code is no longer needed?

yes of course, I think the snippet above can be applied on top of yours

**Comment by Luap99** [comment]
I think the actual regression is from 900e29549afaaec32dbb807a30352632eeb0bd52

**Comment by baude** [comment]
code LGTM; @giuseppe you have final say I think.

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
