### PR TITLE
Consolidate the dependencies for the IsTerminal() API

### PR DESCRIPTION
**Pull request by debarshiray**
The rest of the code has been using `golang.org/x/*` for the `IsTerminal()` API for a long time, not `github.com/mattn/go-isatty`.  It seems better to stick to packages from the `golang.org` domain, whenever possible, and one less dependency is always a good thing.

The modules were not cleaned up with `make vendor` because `go mod tidy` was running into:
```
go: error loading go 1.16 module graph:
  github.com/containers/image/v5@v5.23.1-0.20221015133641-1921a1993c67
  requires
      github.com/honeycombio/beeline-go@v1.9.0 requires
      github.com/mattn/go-sqlite3@v2.0.3+incompatible: reading
        github.com/mattn/go-sqlite3/go.mod at revision v2.0.3: unknown
        revision v2.0.3

If reproducibility with go 1.16 is not needed:
    go mod tidy -compat=1.17
```

Since `go.mod` already requires Go 1.17, the following commands were manually run:
```
$ go mod tidy -compat=1.17
$ go mod vendor
$ go mod verify
```

Further modifications to `go.sum` were done manually based on the complaints from `postbuild.sh` run by the CI.

Fixes: 85db895012bead6b ("logging: new mode -l passthrough")

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Nice
-307 lines of code.
LGTM
/approve

**Comment by mheon** [comment]
Code LGTM.Tests red. Restarted in case it's a flake.

**Comment by edsantiago** [comment]
buildah bud test failures are not flakes, but they have nothing whatsoever to do with this PR: something seems to have changed in the `ubi8` image.

I'm just going to drop this here and step away for the day: https://github.com/containers/buildah/issues/4318. Good luck.

**Pull request merged**
