### PR TITLE
[CI:DOCS] Bump to v2.1.0

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by mheon** [comment]
@rhatdan @baude @vrothberg @TomSweeneyRedHat @QiWang19 @ashley-cui @vrothberg PTAL

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by ashley-cui** [comment]
LGTM

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Pull request merged**
