### PR TITLE
vendor c/common@852ca05a1fbb

### PR DESCRIPTION
**Pull request by vrothberg**
@edsantiago PTAL
@containers/podman-maintainers PTAL

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
In the title, don't you mean `852ca05a`? Because that's the c-c commit (AFAICT) that incorporates your change, and that's the commit I see in your `go.mod` diffs. LGTM aside from the commit title.

**Comment by vrothberg** [comment]
> In the title, don't you mean `852ca05a`? Because that's the c-c commit (AFAICT) that incorporates your change, and that's the commit I see in your `go.mod` diffs. LGTM aside from the commit title.

Updated. Thanks for catching! I updated the commit but forgot to reflect that in the commit title.

**Comment by edsantiago** [comment]
Tests pass, so LGTM

**Pull request merged**
