### PR TITLE
[CI:MACHINE] Podman5 qemu

### PR DESCRIPTION
**Pull request by baude**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by cevich** [comment]
***Important***: I understand this topic of PR is a priority.  But that must not become an excuse for careless merging.  This PR should **not** have been merged as-is, despite the failing secrets-scan check (details at the end).

[The `Total Success` task](https://cirrus-ci.com/task/6050398692179968) is red for a very good reason.  It's spelled out [clearly in the failure message](https://github.com/containers/podman/pull/21326/checks?check_run_id=20778803475):

    Error: Risk of untested change merge.
    Please remove [CI:MACHINE] from title.

Merging `[CI:MACHINE]` PRs w/o a full CI runthrough seriously risks accepting a change that entirely breaks CI.  Worse, maintainers will be almost completely blind to this fact.  When's the last time you checked CI runs on a branch?

Everyone, please, slow down, take some breaths.  Sometimes we have workflows in place to save us from our selves.

---

Secondarily, the secret-scan failure should be considered advisory.  If it's a maintainer's PR, I don't care if it fails.  That check also sends mail to the podman-monitor list so it has built-in visibility.

If the secrets check is constantly failing, any maintainer is empowered to [follow the documentation](https://github.com/containers/podman/blob/main/.gitleaks/README.md#baseline) to update the baseline (in separate PR).  I promise it's really easy: download a file, append it into another file, commit then push.

**Pull request merged**
