### PR TITLE
[skip-ci] add cpp to podman images

### PR DESCRIPTION
**Pull request by iluminae**
#### Does this PR introduce a user-facing change?

```release-note
Added cpp utility to support building `.in` from upstream images
```

### CODE REVIEW

**Comment by rhatdan** [comment]
This does not effect CI/ but you need to sign your commit.

**Comment by rhatdan** [comment]
git commit -a --amend -s
git push --force

**Comment by iluminae** [comment]
ah it must be signed off on - I thought it meant it must be _signed_ (like gpg). Well I pushed that signed-off addendum but its not showing up here in the PR for some reason.

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by edsantiago** [comment]
/hold

I think this functionality is moving to a different repo? @cevich?

**Comment by cevich** [comment]
Thanks Ed.  Yes it is moving, and proper testing is now enabled [in the new home](https://github.com/containers/image_build/pull/5).  If you wouldn't mind, could you move this PR over there?  It will be a good test of the CI setup.

**Comment by cevich** [comment]
This PR needs to be re-opened under https://github.com/containers/image_build if it's still desired.

**Pull request closed without merging**
