### PR TITLE
vendor c/psgo@v1.7.1

### PR DESCRIPTION
**Pull request by vrothberg**
psgo added support for listing supplementary groups via
two new descriptors:

* `groups` for supplementary groups inside the container
* `hgroups` for the counterpart on the host

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

@rhatdan @giuseppe PTAL

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
@giuseppe, can you give guidance on the following error from `int podman fedora-33 root container`?

> [+0470s] Running: /var/tmp/go/src/github.com/containers/podman/bin/podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/podman_test709780861/crio --runroot /tmp/podman_test709780861/crio-run --runtime runc --conmon /usr/bin/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp/podman_test709780861 --events-backend file --storage-driver vfs container top test groups hgroups
[+0470s] Error: open /sys/fs/cgroup/pids//machine.slice/libpod-2e954a6918bce8bd321dac17449f6a1a12788d15c8ca350ef84513381b901b01.scope/libpod_parent/libpod-bb585469390d51168311b7a81b266125dd93f5fd6b9a8d1bc1b489d7f3bbb85a/cgroup.procs: no such file or directory

**Comment by giuseppe** [comment]
> @giuseppe, can you give guidance on the following error from `int podman fedora-33 root container`?

the cgroup seems strange:
```
[+0607s] Error: open /sys/fs/cgroup/pids//machine.slice/libpod-ec327f89e8ce48877bfd1316b867b047efa7bce87eafbbcf8ee5a882e922f8aa.scope/libpod_parent/libpod-029c7c0e8aa8fa941368dcb6e45b3160c093d3b538a6afa4e1a57bf927f2f5da/cgroup.procs: no such file or directory
```

When I run manually the same commands on a cgroup v1 machine I get a cgroup like:

```
12:hugetlb:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
11:rdma:/
10:pids:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
9:freezer:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
8:devices:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
7:cpuset:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
6:perf_event:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
5:memory:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
4:net_cls,net_prio:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
3:blkio:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
2:cpu,cpuacct:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
1:name=systemd:/machine.slice/libpod-e8166fb1c1d9e0ba7946982feb3d6f3bdfaf1fef5c9038d3947ac6794c9004a6.scope
```

Race condition with some other tests (not sure how it can happen though..)?

Could we use `session.OutputToString()` from the `container run` command to get the cid instead of using its name?

**Comment by vrothberg** [comment]
It always happens on `fedora-33 root container`.  The tests look good to me, a name conflict cannot happen since the containers get nuked in between.

I may just skip it in the containerized tests.

**Comment by giuseppe** [comment]
> It always happens on `fedora-33 root container`. The tests look good to me, a name conflict cannot happen since the containers get nuked in between.

ah right that is on containerized cgroup v1 and now it makes sense.  It is happening because on cgroup v1 runc breaks what `/proc/PID/cgroup` shows and where to read the cgroup (crun has the same issue to be compatible :cry: )

We can add a fallback when the path doesn't exist, to read from the root cgroup: https://github.com/containers/psgo/pull/90

I'll open a new PR to test it with Podman

**Comment by giuseppe** [comment]
> I'll open a new PR to test it with Podman

here: https://github.com/containers/podman/pull/11679

**Comment by vrothberg** [comment]
Now vendoring v1.7.1 with @giuseppe's changes, thank you

**Pull request merged**
