### PR TITLE
make podman play use ENVs from image

### LINKED ISSUE #8608: podman-rootless 2.2 eats ENV variables from the packaging process
/kind bug

**Description**

On Ubuntu 20.04, after upgrading to 2.2.0 (or freshly installing, it is a version issue), inside containers in pods created with `podman kube play`, environment variables from the packaging process (`ENV`) are missing / invsibile.

**Steps to reproduce the issue:**

1. Package with

```Containerfile
FROM debian:buster
ENV ISTHERE=ANYBODYOUTTHERE
```
and `podman build -t try --format=docker -f Containerfile .`

2. Create a pod with
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: try
spec:
  containers:
    - name: try
      image: try
      command:
        - /bin/sleep
        - "3600"
```
and `podman play kube try.yaml`.

**Describe the results you received:**

With 2.1.1 (is podman-rootless=2.1.1~2)
```bash
$ podman exec try_pod-try env | sort
HOME=/root
HOSTNAME=try_pod
ISTHERE=ANYBODYOUTTHERE
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TERM=xterm
```

With 2.2.0 (is podman-rootless=2.2.0~2)
```bash
$ podman exec -ti try_pod-try env | sort
container=podman
HOME=/root
HOSTNAME=try_pod
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TERM=xterm
```

**Describe the results you expected:**

I'd rather like to have environment variables from the packaging process left intact.

**Output of `podman version`:**

Working
```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64

```

Broken
```
Version:      2.2.0
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**
(Freshly upgraded vbox)
```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 1
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: morgue
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-56-generic
  linkmode: dynamic
  memFree: 1447694336
  memTotal: 2020876288
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  swapFree: 0
  swapTotal: 0
  uptime: 40m 13.2s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/hal9000/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/hal9000/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 6
  runRoot: /run/user/1000/containers
  volumePath: /home/hal9000/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/unknown 2.2.0~2 amd64
podman/unknown 2.2.0~2 arm64
podman/unknown 2.2.0~2 armhf
podman/unknown 2.2.0~2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes, regrettably for several hours, initially thought I broke sth, until I understood what's happening here.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Same behaviour on physical as well as on VirtualBox. 2.1 works, 2.2 doesn't.

### PR DESCRIPTION
**Pull request by cruwe**
Closes #8608

### CODE REVIEW

**Comment by zhangguanzhang** [comment]
git commit messages should sign , and should add some test units

**Comment by cruwe** [comment]
@zhangguanzhang : added signed-off.  Yes, I completely agree that the feature could use some unit tests. The breaking change from 2.1 to 2.2 would probably not have happened then. I myself, however, do not understand the test framework sufficiently, so I do not feel confident to do that correctly. I just would like to have `podman play` back to the working state it had in 2.1.

**Comment by rhatdan** [comment]
thanks @cruwe 
LGTM

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
