### PR TITLE
container.conf: support attributed string slices

### PR DESCRIPTION
**Pull request by vrothberg**
All `[]string`s in containers.conf have now been migrated to attributed string slices which require some adjustments in Buildah and Podman.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, tests aren't buying it though.

**Comment by vrothberg** [comment]
bloat comes from the k8s yaml bump.  Marking as approved for now.  Conversation in https://github.com/containers/podman/pull/20474

**Comment by vrothberg** [comment]
Last step of the vendor dance.

Ready to go from my side.

**Comment by vrothberg** [comment]
@rhatdan PTAL at the bud failures:
```
[+1522s] not ok 317 bud with --no-hostname
[+1522s] # (from function `assert' in file tests/helpers.bash, line 521,
[+1522s] #  in test file tests/bud.bats, line 5305)
[+1522s] #   `assert "${lines[2]}" == "localhost" "Should be set to localhost"' failed
[+1522s] # /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.32.1-0.20231026190652-11e3b2132761/tests /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.32.1-0.20231026190652-11e3b2132761
[+1522s] # # [checking for: docker.io/library/alpine]
[+1522s] # # [restoring from cache: /var/tmp/buildah-image-cache.3727 / docker.io/library/alpine]
[+1522s] # Getting image source signatures
[+1522s] # Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
[+1522s] # Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
[+1522s] # Writing manifest to image destination
[+1522s] # # podman-remote build --force-rm=false --layers=false --no-cache -t testbud --signature-policy /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.32.1-0.20231026190652-11e3b2132761/tests/policy.json /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.32.1-0.20231026190652-11e3b2132761/tests/bud/no-hostname
[+1522s] # STEP 1/2: FROM alpine
[+1522s] # STEP 2/2: run cat /etc/hostname
[+1522s] # 977eb04bf07a
[+1522s] # COMMIT testbud
[+1522s] # --> 7817043baf4b
[+1522s] # Successfully tagged localhost/testbud:latest
[+1522s] # 7817043baf4b7df16f1255482becfc05f06e1a45cbdf15748ed6bb9b165e2ecf
[+1522s] # # podman-remote build --force-rm=false --layers=false --no-hostname --no-cache -t testbud --signature-policy /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.32.1-0.20231026190652-11e3b2132761/tests/policy.json /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.32.1-0.20231026190652-11e3b2132761/tests/bud/no-hostname
[+1522s] # STEP 1/2: FROM alpine
[+1522s] # STEP 2/2: run cat /etc/hostname
[+1522s] # f988dbf33acf
[+1522s] # COMMIT testbud
[+1522s] # --> 17f5be3223d6
[+1522s] # Successfully tagged localhost/testbud:latest
[+1522s] # 17f5be3223d6641000b7950a68276c1100092489617d7186c3fbe35ed734a346
[+1522s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+1522s] # #|     FAIL: Should be set to localhost
[+1522s] # #| expected: 'localhost'
[+1522s] # #|   actual: 'f988dbf33acf'
[+1522s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+1522s] # teardown: stopping podman server 114474
```

I'll skip the test for now as I really just want to get the containers.conf job done.

**Comment by vrothberg** [comment]
The test passes locally on my machine.

**Comment by rhatdan** [comment]
Looks like --no-hostname is not being pushed to the server side.

**Comment by vrothberg** [comment]
> Looks like --no-hostname is not being pushed to the server side.

I can take a look once this PR is merged.  I really want to get it in as it would otherwise block c/common (and buildah) vendoring.

**Comment by vrothberg** [comment]
Ready to go

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons

**Pull request merged**
