### PR TITLE
Extra backports for v2.0.4

### PR DESCRIPTION
**Pull request by mheon**
Smaller batch, this time - these are things that we missed with the Backport label (have to get better about applying that).

### CODE REVIEW

**Comment by mheon** [comment]
@rhatdan @giuseppe @TomSweeneyRedHat @vrothberg @QiWang19 @ashley-cui PTAL

**Comment by vrothberg** [comment]
LGTM

**Comment by QiWang19** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
/lgtm
/hold
remove the hold on happy tests

**Pull request merged**
