### PR TITLE
Reduce qemu machine function sizes

### PR DESCRIPTION
**Pull request by jakecorrenti**
The functions for QEMU's `VM` interface implementation (`machine.go`) had quite large functions. Pulls out some code that could be moved to its own function for easier readability.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by jakecorrenti** [comment]
The goal here is to run through the different hypervisor implementations and identify places where we can reduce function size. The functions here are quite large and have some pretty distinct "chunks" that could be broken up. 

By doing this, the hope is it will aid in the effort to identify duplicate code across the different implementations and make it easier to find some common code to have a central location for.

**Comment by jakecorrenti** [comment]
@ashley-cui @vrothberg PTAL

**Review by vrothberg — COMMENTED** [review]
Changes LGTM

It would be easier to review with smaller commits.  For instance, a commit when moving code into a separate function.

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
