### PR TITLE
test: use `T.TempDir` to create temporary test directory

### PR DESCRIPTION
**Pull request by Juneezee**
#### Does this PR introduce a user-facing change?

```release-note
None
```

A testing cleanup. 

This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 

This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.

Reference: https://pkg.go.dev/testing#T.TempDir

```go
func TestFoo(t *testing.T) {
	// before
	tmpDir, err := ioutil.TempDir("", "")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(dir)

	// now
	tmpDir := t.TempDir()
}
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
Thanks for contributing!

@containers/podman-maintainers PTAL

**Review by Luap99 — COMMENTED** [review]
LGTM

**Pull request merged**
