### PR TITLE
machine: Refactor Ready socket flow to be more generic

### PR DESCRIPTION
**Pull request by jakecorrenti**
Implement generic `CreateReadySock`, `DeleteReadySock`, and `ListenReadySock` functions for the `VirtProvider` interface. The intent of this is to enforce a more generic flow for the ready socket across the providers (except WSL which does not use a ready socket). 

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by jakecorrenti** [comment]
Would love to get some suggestions for the `ListenReadySocket` design. The fact that the different providers use different functions, which in turn have different parameters and return types, resulted in a less than ideal function signature

**Review by Luap99 — COMMENTED** [review]
Maybe I am missing something but so far I see more code and complexity added than it solves.
Using `interface{}` here is IMO a bad thing as it doe snot guard against any misuse nor can the IDE give me any type hints on what to pass to these functions so it is very easy to to the wrong thing. If we really want this I think it would make more sense to have a septate interface for this. Then create a struct which implements such interface for each hypervisor. 

Also wouldn't it make more sense to wait for @baude's major refactor to land before doing further changes to the old code like this?

**Comment by jakecorrenti** [comment]
@Luap99 I agree with everything you said. 

My only question is how does having a separate interface solve the issue of how HyperV doesn't represent a ready socket the same way as AppleHV and QEMU? That is really the source of all this complexity in my eyes

**Comment by mheon** [comment]
IMO: the methods should probably accept no arguments. IMO, you want three functions:

`CreateReadySocket() error`
`WaitForReady() error`
`TeardownReadySocket() error`

Any information necessary for this to work should be put in the config file, in the provider-specific bits. No `interface{}` as it's all in the config and not an argument.

**Comment by jakecorrenti** [comment]
Closing.

**Pull request closed without merging**
