### PR TITLE
[CI:BUILD] [v4.0-rhel] Cleanup CI tasks

### PR DESCRIPTION
**Pull request by lsm5**
- Use packit copr tasks for rpm builds

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
CI is red

**Comment by vrothberg** [comment]
@lsm5 what's up with this PR?

**Comment by lsm5** [comment]
> @lsm5 what's up with this PR?

same as v4.1.1 https://github.com/containers/podman/pull/19344#issuecomment-1677382623

**Comment by lsm5** [comment]
Closing for now. unlikely to be worth the effort to bring the rpm to a buildable state.

**Comment by flouthoc** [comment]
@lsm5 Is this PR still needed ?

**Pull request closed without merging**
