### PR TITLE
Enable more golangci-lint linters

### PR DESCRIPTION
**Pull request by Luap99**
Enable the stylecheck, golint and whitespace linter.

### CODE REVIEW

**Comment by mheon** [comment]
Should we exclude the generated code in the bindings? I am concerned we'll overwrite all the changes there once the generator is re-run.

Maybe the generator should add a per-file nolint when it generates?

Otherwise LGTM

**Comment by Luap99** [comment]
@mheon I fixed the lint issues in the generator and run make generate-bindings afterwards. I don't think we should add nolint unless there is a important reason.

**Comment by mheon** [comment]
Works for me

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks!

**Pull request merged**
