### PR TITLE
[CI:DOCS] fix: add missing space

### PR DESCRIPTION
**Pull request by rugk**
Fixes a small typo in the man page. :slightly_smiling_face:

### CODE REVIEW

**Comment by zhangguanzhang** [comment]
The git commit messages should sign like the command:
```
git commit -s -m 'xxx'
```

**Comment by rugk** [comment]
That's a thing you cannot do on GitHub. Anyway, if you think this is important even for such a minor pull request/change, well… I now did the inconvenient way of cloning the repo and force-pushing.

Next time, you can maybe just squash-merge the PR and there adjust the commit message as you like. That's way easier for anyone involved and would likely make it easier for contributors.

BTW, your PR docs exclusion does not seem to work:
> In case you're only changing docs, make sure to prefix the pull-request title with "[CI:DOCS]".  That will prevent functional tests from running and save time and energy.

The PR has this title, but all tests are still triggered, are not they?

**Comment by Luap99** [comment]
> BTW, your PR docs exclusion does not seem to work:
> 
> The PR has this title, but all tests are still triggered, are not they?

It does work, normal PRs run the full test suite with 50+ tests. CI:DOCS will only run the essential tests.

The sign-off-by line is a legal requirement, see https://github.com/containers/podman/blob/master/CONTRIBUTING.md#sign-your-prs

**Comment by Luap99** [comment]
LGTM

**Pull request merged**
