### PR TITLE
[v4.3] Update c/image from release-5.23 branch

### PR DESCRIPTION
**Pull request by mtrmac**
#### Does this PR introduce a user-facing change?

```release-note
Fixes reads/writes of sigstore signatures/attachments in quay.io and registry.redhat.io
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM. We'll want an actual release tag before we cut Podman 4.3.1, but I don't have a timeframe on that release yet so no need to hurry things.

**Comment by mtrmac** [comment]
Sure. Podman 4.3 is currently the only known user of the 5.23 branch of c/image, so tagging releases is going to be Podman-driven.

**Comment by ashley-cui** [comment]
@mtrmac Looks the time has come to cut 4.3.1 on Podman, which means we need a new c/image. Could you cut c/image and vendor it into Podman? Thanks!

**Pull request merged**
