### PR TITLE
List volumes before pruning

### LINKED ISSUE #8913: RFE: Let `podman volume prune` show the volumes that are going to be removed
/kind feature

**Description**

Running `podman volume prune` you have to confirm the operation but you don't see which volumes actually will be removed after you confirm the command:

```
$ podman volume prune
WARNING! This will remove all volumes not used by at least one container.
Are you sure you want to continue? [y/N]
```

I was trapped by the issue #7862. This could have been avoided by showing the volumes that are going to be removed before you confirm the removal. Because the user would have the chance that there is a volume going to be removed that's currently in use by a running container instance. Possible data loss could be prevented this way.

Or at least add an option to the command that will show the volumes that are going to be removed.

**Steps to reproduce the issue:**

1. `podman volume prune`

2. Hit 'y'

3.

**Describe the results you received:**

```
$ podman volume prune
WARNING! This will remove all volumes not used by at least one container.
Are you sure you want to continue? [y/N]
```

**Describe the results you expected:**

```
$ podman volume prune
WARNING! This will remove all volumes not used by at least one container. The following volumes will be removed:
volume1
volume2
...
Are you sure you want to continue? [y/N]
```

**Output of `podman version`:**

```
podman version 3.0.0-dev
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

### PR DESCRIPTION
**Pull request by iwita**
This commit lists the volumes that are going to be removed when the command podman volume prune is issued.
It is applied only in the cases when --force flag is not enabled.
Closes #8913

### CODE REVIEW

**Comment by rhatdan** [comment]
You are going to need to add some kind of tests.

Also could you squash your commits.

**Review by TomSweeneyRedHat — COMMENTED** [review]
Any man page tweaks needed?

**Comment by iwita** [comment]
> Any man page tweaks needed?

There is an additional flag `unused=0/1` added.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
This should go in Post 3.0 release.

**Comment by iwita** [comment]
Just thought that I should use the already defined filter `dangling` instead of creating a new one. Thus, I will update this PR.

**Comment by TomSweeneyRedHat** [comment]
LGTM
should this be cherry-picked to the release-3.0 branch?

**Comment by rhatdan** [comment]
No we want this in podman 3.1
/lgtm
/approve
Thanks @iwita 
Nice work.

**Comment by iwita** [comment]
> No we want this in podman 3.1
> /lgtm
> /approve
> Thanks @iwita 
> Nice work.

@rhatdan thank you for your guidance.

**Comment by rhatdan** [comment]
Now we expect you do fix some other issues, if you want.  Look for good first issues.

**Comment by iwita** [comment]
> Now we expect you do fix some other issues, if you want. Look for good first issues.

@rhatdan Yes of course. I will check good first issues in order to find something that I could help with!

**Pull request merged**
