### PR TITLE
machine: Enable console autologin by default

### PR DESCRIPTION
**Pull request by cgwalters**
There are no security concerns here; this is a convenience for people debugging things.  Some podman-machine developers were manually setting a password over SSH for example, but this is just better than that.

[NO NEW TESTS NEEDED]

(Also marking no release note as we don't expose a console by default, only when launched with --debug right now)
```release-note
None
```

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
Needs a rebase.

**Comment by cgwalters** [comment]
Rebased.
It looks like the machine-(hyperv|mac) CI checks are broken generally?

**Comment by cgwalters** [comment]
OK rebased 🏄 - let's see what happens with the hyper CI run on this.  I don't know what we do for a console on hyper actually, I'd expect this to be a no-op but perhaps it is somehow breaking something.

**Comment by Luap99** [comment]
```
  > Enter [It] simple init with username - C:/Users/Administrator/AppData/Local/cirrus-ci-build/repo/pkg/machine/e2e/init_test.go:124 @ 01/09/24 00:47:44.738
  C:\Users\Administrator\AppData\Local\cirrus-ci-build\repo\bin\windows\podman.exe machine init --disk-size 11 --username remoteuser --image-path C:\Users\ADMINI~1\AppData\Local\Temp\podman_test872248153\fedora-coreos-39.20240104.2.0-hyperv.x86_64.vhdx e2d282390af6
  Error: EOF
  [FAILED] Expected
      <int>: 125
  to match exit code:
      <int>: 0
  In [It] at: C:/Users/Administrator/AppData/Local/cirrus-ci-build/repo/pkg/machine/e2e/init_test.go:129 @ 01/09/24 00:48:15.905
```

Just a guess but you seem to hardcode the username and this test uses a different one so that might cause the failure? So I think agetty fails because you call it on a non existing user. That does however not explain why only hyperV fails but not qemu.

**Comment by cgwalters** [comment]
> Just a guess but you seem to hardcode the username and this test uses a different one so that might cause the failure? 

Thanks yep, that appears to be right.  @baude and I agreed for this use case it's simplest to just hardcode autologin to root (this is always a recovery scenario today anyways so might as well be root).

**Comment by cgwalters** [comment]
btw @Luap99 thanks for all the reviews and work you do!

**Comment by cgwalters** [comment]
Changed to just autologin as root since there's no reason not to, and it gets us out of interlock with the ignition user config.

**Pull request merged**
