### PR TITLE
[2.0] Vendor in containers/storage v1.20.4

### PR DESCRIPTION
**Pull request by rhatdan**
This will allow the passing down of the ignore_chown_errors flag from
/etc/containers/storage.conf for rootless containers.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon @vrothberg @baude @giuseppe @TomSweeneyRedHat @QiWang19 @ashley-cui @jwhonce PTAL

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/podman/issues/7513

**Review by vrothberg — APPROVED** [review]
LGTM

I think this calls for tests to prevent future regressions (Cc @edsantiago). @rhatdan, do you have an idea how we could easily test it? I guess we had to set up a new uid/gid mapping ideally with a range of 1.

**Comment by rhatdan** [comment]
@vrothberg the problem with testing this is we would need to modify the host system that is running the test to make it work, which @edsantiago frowns upon.

**Comment by vrothberg** [comment]
> @vrothberg the problem with testing this is we would need to modify the host system that is running the test to make it work, which @edsantiago frowns upon.

That's what I feared. Couldn't we run it in a container?

**Comment by rhatdan** [comment]
Yes doing this in a privileged container might make sense.  Do we have any examples of this though?

**Comment by vrothberg** [comment]
> Yes doing this in a privileged container might make sense. Do we have any examples of this though?

I think we could reuse the podman images from Quay.io and mount a handcrafted /etc/sub{g,u}id? Then we'd need an image with more than one uids/gids.

**Comment by mheon** [comment]
Let's keep this as just a vendor update. If we want to add tests, we should do it against master first.

**Pull request merged**
