### PR TITLE
machine/qemu: use extra gvproxy socket

### PR DESCRIPTION
**Pull request by Luap99**
Right now the code used the same socket for gvproxy and the qemu qmp socket, this was racy and no correct as the later overwrote the former. The correct thing is to use to separate socket paths, just use the GVProxySocket() helper like applehv does.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@ashley-cui @baude @n1hility PTAL

**Comment by ashley-cui** [comment]
LGTM

**Pull request merged**
