### PR TITLE
systests: quadlet: fixes for RHEL8

### PR DESCRIPTION
**Pull request by edsantiago**
Some quadlet tests are failing on RHEL8: test code was
using journalctl to check output from containers. This
fails on RHEL8, where default log driver is k8s-file.

Solution: use 'podman logs' instead. To do so, we need to
keep the containers alive (otherwise, quadlet seems to
delete them on exit). Do so by running 'top -b' (batch);
the currently-used 'top' was failing because not-a-tty.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Tested on RHEL-8.9.0-20230712.20. @sstosh if you have the time, could you please see if this fixes the problems you're seeing?

**Comment by sstosh** [comment]
I checked the tests and `quadlet - rootfs` test is only failed.

<details>
<summary>test log</summary>

```
not ok 14 quadlet - rootfs
# (from function `assert' in file helpers.bash, line 812,
#  from function `service_setup' in file 252-quadlet.bats, line 95,
#  in test file 252-quadlet.bats, line 640)
#   `service_setup $QUADLET_SERVICE_NAME' failed with status 124
# [09:45:20.009951806] # podman rm -t 0 --all --force --ignore
# [09:45:20.061489256] # podman ps --all --external --format {{.ID}} {{.Names}}
# [09:45:20.109010612] # podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
# [09:45:20.156861631] quay.io/libpod/testimage:20221018 f5a99120db64
# # /usr/libexec/podman/quadlet  /run/systemd/system
#
# # Automatically generated by /usr/libexec/podman/quadlet
# #
# [X-Container]
# Rootfs=/:O
# Exec=sh -c "echo STARTED CONTAINER; echo "READY=1" | socat -u STDIN unix-sendto:$NOTIFY_SOCKET; top -b"
# Notify=yes
#
# [Unit]
# SourcePath=/tmp/podman_bats.CV3KMI/quadlet.UrtXcy/basic_fyKmFuzM1W.container
# RequiresMountsFor=%t/containers
#
# [Service]
# Environment=PODMAN_SYSTEMD_UNIT=%n
# KillMode=mixed
# ExecStop=/usr/bin/podman rm -f -i --cidfile=%t/%N.cid
# ExecStopPost=-/usr/bin/podman rm -f -i --cidfile=%t/%N.cid
# Delegate=yes
# Type=notify
# NotifyAccess=all
# SyslogIdentifier=%N
# ExecStart=/usr/bin/podman run --name=systemd-%N --cidfile=%t/%N.cid --replace --rm --cgroups=split --sdnotify=container -d --rootfs /:O sh -c "echo STARTED CONTAINER; echo READY=1 | socat -u STDIN unix-sendto:$NOTIFY_SOCKET; top -b"
# # systemctl  start basic_fyKmFuzM1W.service
# timeout: sending signal TERM to command ‘systemctl’
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: Error starting systemd unit basic_fyKmFuzM1W.service
# #| expected: -eq 0
# #|   actual:     124
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# # [teardown]
# [09:48:20.937301499] # podman pod rm -t 0 --all --force --ignore
# [09:48:20.989860591] # podman rm -t 0 --all --force --ignore
# [09:48:21.039760921] # podman network prune --force
# [09:48:21.090129102] # podman volume rm -a -f
ok 15 quadlet - selinux disable
ok 16 quadlet - selinux labels
ok 17 quadlet - secret as environment variable
ok 18 quadlet - secret as a file
```
</details>

**Comment by edsantiago** [comment]
Timeout in `systemctl start`??? 

Very stupid question, please forgive me, but do you have 100% sync between `/usr/bin/podman` and the tests you are running? Is it possible that you're running `/usr/bin/podman` from an RPM, and tests checked out from source? The `rootfs` test had some recent changes that perhaps aren't reflected in RPM-podman. Would it be possible for you to try:
```console
# make
...
# hack/bats 252
```
The `hack/bats` script takes care to use `bin/podman` and `bin/quadlet` and make other useful settings.

Thank you so much for your help in tracking this down.

**Comment by sstosh** [comment]
Thank you for your suggestion.
I checked the test also failed with `hack/bats`.

<details>
<summary>Log</summary>

```
# make
if [ ! -f bin/podmansh ]; then ln -s podman bin/podmansh; fi
if [ ! -x "./test/tools/build/go-md2man" ]; then \
        make -C test/tools build/go-md2man ; \
fi
mkdir -p docs/build/man

# hack/bats 252
# bats  test/system/252-quadlet.bats
 ? quadlet - basic
 ? quadlet - envvar
 ? quadlet - ContainerName
 ? quadlet - labels
 ? quadlet - oneshot
 ? quadlet - volume
 ? quadlet - volume dependency
 ? quadlet - named volume dependency
 ? quadlet - network
 ? quadlet - network dependency
 ? quadlet - named network dependency
 ? quadlet kube - basic
 ? quadlet kube - named network dependency
 ? quadlet - rootfs
   (from function `assert' in file test/system/helpers.bash, line 812,
    from function `service_setup' in file test/system/252-quadlet.bats, line 95,
    in test file test/system/252-quadlet.bats, line 640)
     `service_setup $QUADLET_SERVICE_NAME' failed with status 124
   [11:54:42.007958422] # /root/libpod/bin/podman rm -t 0 --all --force --ignore
   [11:54:42.047725540] # /root/libpod/bin/podman ps --all --external --format {{.ID}} {{.Names}}
   [11:54:42.086140835] # /root/libpod/bin/podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   [11:54:42.122068022] quay.io/libpod/testimage:20221018 f5a99120db64
   # /root/libpod/bin/quadlet  /run/systemd/system

   # Automatically generated by /root/libpod/bin/quadlet
   #
   [X-Container]
   Rootfs=/:O
   Exec=sh -c "echo STARTED CONTAINER; echo "READY=1" | socat -u STDIN unix-sendto:$NOTIFY_SOCKET; top -b"
   Notify=yes

   [Unit]
   SourcePath=/tmp/podman_bats.ih2B7Q/quadlet.sAALN6/basic_jIlM7PHlcs.container
   RequiresMountsFor=%t/containers

   [Service]
   Environment=PODMAN_SYSTEMD_UNIT=%n
   KillMode=mixed
   ExecStop=/root/libpod/bin/podman rm -f -i --cidfile=%t/%N.cid
   ExecStopPost=-/root/libpod/bin/podman rm -f -i --cidfile=%t/%N.cid
   Delegate=yes
   Type=notify
   NotifyAccess=all
   SyslogIdentifier=%N
   ExecStart=/root/libpod/bin/podman run --name=systemd-%N --cidfile=%t/%N.cid --replace --rm --cgroups=split --sdnotify=container -d --rootfs /:O sh -c "echo STARTED CONTAINER; echo READY=1 | socat -u STDIN unix-sendto:$NOTIFY_SOCKET; top -b"
   # systemctl  start basic_jIlM7PHlcs.service
   timeout: sending signal TERM to command ‘systemctl’
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: Error starting systemd unit basic_jIlM7PHlcs.service
   #| expected: -eq 0
   #|   actual:     124
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   # [teardown]
   [11:57:42.907634618] # /root/libpod/bin/podman pod rm -t 0 --all --force --ignore
   [11:57:42.944399623] # /root/libpod/bin/podman rm -t 0 --all --force --ignore
   [11:57:42.976814967] # /root/libpod/bin/podman network prune --force
   [11:57:43.010380065] # /root/libpod/bin/podman volume rm -a -f
 ? quadlet - selinux disable
 ? quadlet - selinux labels
 ? quadlet - secret as environment variable
 ? quadlet - secret as a file
 ? quadlet - volume path using specifier
 ? quadlet - tmpfs
 ? quadlet - userns
 ? quadlet - exit-code propagation
```
</details>

**Comment by ygalblum** [comment]
LGTM

**Comment by edsantiago** [comment]
I could not reproduce the `systemctl start` hang on a new RHEL-8.9 VM.

In the interests of getting this into v4.6 to address (at least some) gating-test failures, and accepting the mieux-bien tradeoff, could we get this merged please?

**Review by vrothberg — COMMENTED** [review]
LGTM

Restarted the flaked rpm-build jobs.

**Comment by vrothberg** [comment]
@Luap99 do you know what's up with the rpm builds?

**Comment by Luap99** [comment]
```
+ go build -buildmode pie -compiler gc '-tags=rpm_crashtraceback seccomp exclude_graphdriver_devicemapper systemd libsubid  ' -ldflags '  -B 0x71b57a6a1b75208b7126436e105beadf006e40b0 -compressdwarf=false -linkmode=external -extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  '\''' -a -v -x -o bin/gvproxy ./cmd/gvproxy
WORK=/tmp/go-build1365953410
package github.com/containers/gvisor-tap-vsock/cmd/gvproxy
	imports github.com/containers/gvisor-tap-vsock/pkg/virtualnetwork
	imports github.com/containers/gvisor-tap-vsock/pkg/services/dhcp
	imports github.com/containers/gvisor-tap-vsock/pkg/tap
	imports gvisor.dev/gvisor/pkg/tcpip/stack
	imports gvisor.dev/gvisor/pkg/sync/locking
	imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /builddir/build/BUILD/podman-4.5.0.rc1/gvisor-tap-vsock-407efb5dcdb0f4445935f7360535800b60447544/vendor/gvisor.dev/gvisor/pkg/gohacks
```

Gvproxy does not build with go 1.21? Nothing we can do on the podman end, we should ignore it for now.
https://github.com/containers/gvisor-tap-vsock/issues/232 looks relevant

**Comment by sstosh** [comment]
I tested on the RHEL8.9NB and all quadlet tests passed.
systemctl timeout did not occurred.

<details>
<summary>Log</summary>

```
# QUADLET_BINARY=/usr/libexec/podman/quadlet bats 252-quadlet.bats
 ? quadlet - basic
 ? quadlet - envvar
 ? quadlet - ContainerName
 ? quadlet - labels
 ? quadlet - oneshot
 ? quadlet - volume
 ? quadlet - volume dependency
 ? quadlet - network
 ? quadlet - network dependency
 ? quadlet kube - basic
 ? quadlet - rootfs
 ? quadlet - selinux disable
 ? quadlet - selinux labels
 ? quadlet - secret as environment variable
 ? quadlet - secret as a file
 ? quadlet - volume path using specifier
 ? quadlet - tmpfs
 ? quadlet - userns
 ? quadlet - exit-code propagation

19 tests, 0 failures
```
</details>

**Pull request merged**
