### PR TITLE
Ensure that container still exists when removing

### PR DESCRIPTION
**Pull request by mheon**
After #8906, there is a potential race condition in container removal of running containers with `--rm`. Running containers must first be stopped, which was changed to unlock the container to allow commands like `podman ps` to continue to run while stopping; however, this also means that the cleanup process can potentially run before we re-lock, and remove the container from under us, resulting in error messages from `podman rm`. The end result is unchanged, the container is still cleanly removed, but the `podman rm` command will seem to have failed.

Work around this by pinging the database after we stop the container to make sure it still exists. If it doesn't, our job is done and we can exit cleanly.

[NO TESTS NEEDED] because the race doesn't trigger easily and I can't make a test to reproduce it on demand anywhere.

### CODE REVIEW

**Comment by rhatdan** [comment]
Is this to fix THE race?
LGTM

**Comment by mheon** [comment]
Nope. Separate BZ, unfortunately.

Would not be surprised if it fixes some races in CI, though.

**Comment by TomSweeneyRedHat** [comment]
FWIW, addresses https://bugzilla.redhat.com/show_bug.cgi?id=1964852
LGTM

**Review by vrothberg — COMMENTED** [review]
/hold cancel

LGTM

**Pull request merged**
