### PR TITLE
Vendor in containers/(buildah,common, image)

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```
[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by edsantiago** [comment]
FYI, buildah tests will fail, see treadmill #13808:
```
[+1358s] not ok 269 bud pull never
         # (from function `die' in file tests/[helpers.bash, line 423](https://github.com/containers/podman/blob/8e7313524563c527808dd1f134416a8fdac05430/test/system/helpers.bash#L423),
         #  from function `run_buildah' in file tests/[helpers.bash, line 410](https://github.com/containers/podman/blob/8e7313524563c527808dd1f134416a8fdac05430/test/system/helpers.bash#L410),
         #  in test file tests/[bud.bats, line 4218](https://github.com/containers/podman/blob/8e7313524563c527808dd1f134416a8fdac05430/test/system/bud.bats#L4218))
         #   `run_buildah 125 build $WITH_POLICY_JSON -t ${target} --pull=false $BUDFILES/pull' failed
         # /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d
         # # podman build --force-rm=false --layers=false --signature-policy /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/policy.json -t pull --pull-never /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/bud/pull
         # STEP 1/1: FROM busybox
         # Error: creating build container: busybox: image not known
         # [ rc=125 (expected) ]
         # # podman build --force-rm=false --layers=false --signature-policy /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/policy.json -t pull --pull=false /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/bud/pull
         # STEP 1/1: FROM busybox
         # Resolved "busybox" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
         # Trying to pull docker.io/library/busybox:latest...
         # Getting image source signatures
         # Copying blob sha256:9758c28807f21c13d05c704821fdd56c0b9574912f9b916c65e1df3e6b8bc572
         # Copying config sha256:f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f
         # Writing manifest to image destination
         # COMMIT pull
         # --> f0b02e9d092d
         # Successfully tagged localhost/pull:latest
         # Successfully tagged docker.io/library/busybox:latest
         # f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #| FAIL: exit code is 0; expected 125
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         # /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d
[+1360s] not ok 270 bud pull false no local image
         # (from function `die' in file tests/[helpers.bash, line 423](https://github.com/containers/podman/blob/8e7313524563c527808dd1f134416a8fdac05430/test/system/helpers.bash#L423),
         #  from function `run_buildah' in file tests/[helpers.bash, line 410](https://github.com/containers/podman/blob/8e7313524563c527808dd1f134416a8fdac05430/test/system/helpers.bash#L410),
         #  in test file tests/[bud.bats, line 4230](https://github.com/containers/podman/blob/8e7313524563c527808dd1f134416a8fdac05430/test/system/bud.bats#L4230))
         #   `run_buildah 125 build $WITH_POLICY_JSON -t ${target} --pull=false $BUDFILES/pull' failed
         # /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d
         # # podman build --force-rm=false --layers=false --signature-policy /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/policy.json -t pull --pull=false /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/bud/pull
         # STEP 1/1: FROM busybox
         # Resolved "busybox" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
         # Trying to pull docker.io/library/busybox:latest...
         # Getting image source signatures
         # Copying blob sha256:9758c28807f21c13d05c704821fdd56c0b9574912f9b916c65e1df3e6b8bc572
         # Copying config sha256:f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f
         # Writing manifest to image destination
         # COMMIT pull
         # --> f0b02e9d092d
         # Successfully tagged localhost/pull:latest
         # Successfully tagged docker.io/library/busybox:latest
         # f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #| FAIL: exit code is 0; expected 125
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by edsantiago** [comment]
Also fails remote:
```
[+2132s] not ok 400 build test default ulimits
         # (from function `assert' in file tests/[helpers.bash, line 521](https://github.com/containers/podman/blob/8e7313524563c527808dd1f134416a8fdac05430/test/system/helpers.bash#L521),
         #  from function `expect_output' in file tests/[helpers.bash, line 548](https://github.com/containers/podman/blob/8e7313524563c527808dd1f134416a8fdac05430/test/system/helpers.bash#L548),
         #  in test file tests/[bud.bats, line 6669](https://github.com/containers/podman/blob/8e7313524563c527808dd1f134416a8fdac05430/test/system/bud.bats#L6669))
         #   `expect_output --substring "$podman_files"' failed
         # /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d
         # # [checking for: docker.io/library/alpine]
         # # [restoring from cache: /var/tmp/buildah-image-cache.3735 / docker.io/library/alpine]
         # Getting image source signatures
         # Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
         # Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
         # Writing manifest to image destination
         # # podman-remote build --force-rm=false --layers=false --no-cache --pull=false --signature-policy /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/policy.json -t foo/bar /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/bud/bud.limits
         # STEP 1/3: FROM alpine
         # STEP 2/3: RUN echo -n "Files="; awk '/open files/{print $4 "/" $5}' /proc/self/limits
         # Files=500/500
         # STEP 3/3: RUN echo -n "Processes="; awk '/processes/{print $3 "/" $4}' /proc/self/limits
         # Processes=4194304/4194304
         # COMMIT foo/bar
         # --> 7df1a799420e
         # Successfully tagged localhost/foo/bar:latest
         # 7df1a799420e43d74e11eb5d974960fbc600ea4a5cade065f59a8d0c7dbba65e
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #|     FAIL: podman-remote build --force-rm=false --layers=false --no-cache --pull=false --signature-policy /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/policy.json -t foo/bar /var/tmp/go/src/github.com/containers/podman/test-buildah-v1.34.1-0.20240228191450-d80ec964ad1d/tests/bud/bud.limits
         # #| expected: =~ 'Error: unknown flag: --events-backend'
         # #|   actual:    'STEP 1/3: FROM alpine'
         # #|         >    'STEP 2/3: RUN echo -n "Files="; awk '/open files/{print $4 "/" $5}' /proc/self/limits'
         # #|         >    'Files=500/500'
         # #|         >    'STEP 3/3: RUN echo -n "Processes="; awk '/processes/{print $3 "/" $4}' /proc/self/limits'
         # #|         >    'Processes=4194304/4194304'
         # #|         >    'COMMIT foo/bar'
         # #|         >    '--> 7df1a799420e'
         # #|         >    'Successfully tagged localhost/foo/bar:latest'
         # #|         >    '7df1a799420e43d74e11eb5d974960fbc600ea4a5cade065f59a8d0c7dbba65e'
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by rhatdan** [comment]
Thanks, I will look into this.

**Comment by TomSweeneyRedHat** [comment]
Red tests.
I'm surprised that common didn't get bumped too, but I could be off on that.  However, we'll need to get @ashley-cui changes to c/common vendored in later today/tomorrow before the RC gets cut.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
fwiw

**Comment by martinpitt** [comment]
Cockpit failures are due to #21563, I just landed the test adjustment in c-podman. Tests from now on should be green again.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL
@vrothberg @giuseppe @Luap99 @flouthoc PTAL

**Pull request merged**
