### PR TITLE
[podman-remote] Fix closed connection on pull causes service panic

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Fixes: https://github.com/containers/podman/issues/7896
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
but want a head nod from @mheon

**Comment by jwhonce** [comment]
LGTM, I'll defer to @mheon but I think this is the best way out given I couldn't find where in the low level code anyone was checking the context expiring.

**Comment by vrothberg** [comment]
I don't see how this is fixing #7896.

The service is still going down.

**Comment by vrothberg** [comment]
Apologies. I used the wrong binary for testing.

The `recover` is perfectly fine!

**Pull request merged**
