### PR TITLE
[v3.4] backport: utils: reintroduce moveToCgroup

### PR DESCRIPTION
**Pull request by edsantiago**
commit ee62711136339c5daf38e38859227d85b06fc32a introduced the
regression.

It was mistakenly removed as part of a cleanup, but this code is
needed by another code path, where we move conmon for the exec session
to the same cgroup used by conmon for the process.

Closes: https://github.com/containers/podman/issues/12535

[NO NEW TESTS NEEDED] it fixes a regression in the CI

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by jnovy** [comment]
LGTM

**Comment by edsantiago** [comment]
If this branch is going to see more activity, we may want to backport #12519

**Comment by edsantiago** [comment]
@containers/podman-maintainers CI is now green after two restarted flakes. PTAL. 

Even if approved, **we still can't cut a new release until #10710 is addressed**.

**Review by vrothberg — COMMENTED** [review]
LGTM, thank you.

**Comment by mheon** [comment]
@edsantiago That's going to be problematic because the current read on that is that we need Conmon changes as well - and not exactly small ones.

**Comment by edsantiago** [comment]
@mheon for purposes of this release, "skip the stty test" is a perfectly valid resolution. We just can't ship as-is, because the stty bug is no longer a flake, it's failing way too often and will never pass gating.

**Comment by mheon** [comment]
Disabling this test for the v3.4 (and, if required, v3.4-2-rhel) branches SGTM. I do not see us creating a fix for this that also backports cleanly.

**Pull request merged**
