### PR TITLE
Use containers/storage/pkg/regexp in place of regexp

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
The changes LGTM but there are still some candidates left in the code:
```
podman (regexp) $ vgrep --no-ripgrep --no-git -w regexp --exclude-dir=vendor --exclude-dir=.git --exclude-dir=test
Index File                                Line Content
    0 cmd/podman/images/trust_set.go         6 "regexp"
    1 cmd/podman/images/trust_set.go        76 reg := regexp.MustCompile(`^[a-zA-Z0-9-_\.]+\/?:?[0-9]*[a-z0-9-\/:]*$`)
    2 cmd/podman/images/trust_set.go        81 reg = regexp.MustCompile(`^[a-z0-9-:\./]*$`)
    3 cmd/podman/inspect/inspect.go          9 "regexp"
    4 cmd/podman/inspect/inspect.go        265 m := regexp.MustCompile(`{{\s*\.Id\s*}}`)
    5 cmd/podman/parse/net.go               13 "github.com/containers/storage/pkg/regexp"
    6 cmd/podman/parse/net.go               26 alphaRegexp  = regexp.Delayed(`[a-zA-Z]`)
    7 cmd/podman/parse/net.go               27 domainRegexp = regexp.Delayed(`^(:?(:?[a-zA-Z0-9]|(:?[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]))(:?\.(:?[a-zA-Z0-9]|(:?[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])))*)\.?\s*$`)
    8 cmd/podman/system/connection/add.go    8 "regexp"
    9 cmd/podman/system/connection/add.go  109 if match, err := regexp.Match("^[A-Za-z][A-Za-z0-9+.-]*://", []byte(dest)); err != nil {
   10 cmd/podman/system/connection/add.go  206 if match, err := regexp.Match("^[A-Za-z][A-Za-z0-9+.-]*://", []byte(dest)); err != nil {
   11 cmd/podman/machine/machine.go         11 "regexp"
   12 cmd/podman/machine/machine.go        104 re := regexp.MustCompile(`machine_events.*\.sock`)
   13 cmd/podman-mac-helper/main.go         12 "regexp"
   14 cmd/podman-mac-helper/main.go        117 re := regexp.MustCompile(`\r?\n`)
   15 libpod/oci_util.go                     7 "regexp"
   16 libpod/oci_util.go                   141 if match := regexp.MustCompile("(?i).*permission denied.*|.*operation not permitted.*").FindString(runtimeMsg); match != "" {
   17 libpod/oci_util.go                   148 if match := regexp.MustCompile("(?i).*executable file not found in.*|.*no such file or directory.*").FindString(runtimeMsg); match != "" {
   18 libpod/oci_util.go                   155 if match := regexp.MustCompile("`/proc/[a-z0-9-].+/attr.*`").FindString(runtimeMsg); match != "" {
   19 libpod/networking_common.go            9 "regexp"
   20 libpod/networking_common.go          175 b, rerr := regexp.MatchString("Couldn't load target `CNI-[a-f0-9]{24}':No such file or directory|Chain 'CNI-[a-f0-9]{24}' does not exist", err.Error())
   21 libpod/options.go                     26 "github.com/containers/storage/pkg/regexp"
   22 libpod/options.go                     32 var umaskRegex = regexp.Delayed(`^[0-7]{1,4}$`)
   23 pkg/util/utils.go                     12 "regexp"
   24 pkg/util/utils.go                     92 m, err := regexp.MatchString(r, s)
   25 pkg/bindings/images/build.go          27 "github.com/containers/storage/pkg/regexp"
   26 pkg/bindings/images/build.go          39 var iidRegex = regexp.Delayed(`^[0-9a-f]{12}`)
   27 pkg/domain/filters/volumes.go          6 "regexp"
   28 pkg/domain/filters/volumes.go         20 nameRegexp, err := regexp.Compile(val)
   29 pkg/ps/ps.go                           8 "regexp"
   30 pkg/ps/ps.go                         322 reg := regexp.MustCompile(`.*\[|\].*`)
   31 pkg/specgen/generate/kube/kube.go     12 "regexp"
   32 pkg/specgen/generate/kube/kube.go    870 fieldPathLabelRegex := regexp.MustCompile(fieldPathLabelPattern)
   33 pkg/specgen/generate/kube/kube.go    872 fieldPathAnnotationRegex := regexp.MustCompile(fieldPathAnnotationPattern)
   34 pkg/systemd/quadlet/quadlet.go         9 "github.com/containers/storage/pkg/regexp"
   35 pkg/systemd/quadlet/quadlet.go        77 validPortRange = regexp.Delayed(`\d+(-\d+)?(/udp|/tcp)?$`)
```

**Comment by vrothberg** [comment]
Just to throw out the idea:

It may be worth exploring whether some of the regexes are actually needed.  When writing the first version of [vgrep](https://github.com/vrothberg/vgrep) (in Python) I noticed that regex were a _major_ performance bottle neck.  Regexes can be powerful for parsing but if they're used for filtering, a `string.Contains` is usually much faster - extremes excluded.

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by giuseppe** [comment]
> The changes LGTM but there are still some candidates left in the code:
> 
> ```
> podman (regexp) $ vgrep --no-ripgrep --no-git -w regexp --exclude-dir=vendor --exclude-dir=.git --exclude-dir=test
> Index File                                Line Content
>     0 cmd/podman/images/trust_set.go         6 "regexp"
>     1 cmd/podman/images/trust_set.go        76 reg := regexp.MustCompile(`^[a-zA-Z0-9-_\.]+\/?:?[0-9]*[a-z0-9-\/:]*$`)
>     2 cmd/podman/images/trust_set.go        81 reg = regexp.MustCompile(`^[a-z0-9-:\./]*$`)
>     3 cmd/podman/inspect/inspect.go          9 "regexp"
>     4 cmd/podman/inspect/inspect.go        265 m := regexp.MustCompile(`{{\s*\.Id\s*}}`)
>     5 cmd/podman/parse/net.go               13 "github.com/containers/storage/pkg/regexp"
>     6 cmd/podman/parse/net.go               26 alphaRegexp  = regexp.Delayed(`[a-zA-Z]`)
>     7 cmd/podman/parse/net.go               27 domainRegexp = regexp.Delayed(`^(:?(:?[a-zA-Z0-9]|(:?[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]))(:?\.(:?[a-zA-Z0-9]|(:?[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])))*)\.?\s*$`)
>     8 cmd/podman/system/connection/add.go    8 "regexp"
>     9 cmd/podman/system/connection/add.go  109 if match, err := regexp.Match("^[A-Za-z][A-Za-z0-9+.-]*://", []byte(dest)); err != nil {
>    10 cmd/podman/system/connection/add.go  206 if match, err := regexp.Match("^[A-Za-z][A-Za-z0-9+.-]*://", []byte(dest)); err != nil {
>    11 cmd/podman/machine/machine.go         11 "regexp"
>    12 cmd/podman/machine/machine.go        104 re := regexp.MustCompile(`machine_events.*\.sock`)
>    13 cmd/podman-mac-helper/main.go         12 "regexp"
>    14 cmd/podman-mac-helper/main.go        117 re := regexp.MustCompile(`\r?\n`)
>    15 libpod/oci_util.go                     7 "regexp"
>    16 libpod/oci_util.go                   141 if match := regexp.MustCompile("(?i).*permission denied.*|.*operation not permitted.*").FindString(runtimeMsg); match != "" {
>    17 libpod/oci_util.go                   148 if match := regexp.MustCompile("(?i).*executable file not found in.*|.*no such file or directory.*").FindString(runtimeMsg); match != "" {
>    18 libpod/oci_util.go                   155 if match := regexp.MustCompile("`/proc/[a-z0-9-].+/attr.*`").FindString(runtimeMsg); match != "" {
>    19 libpod/networking_common.go            9 "regexp"
>    20 libpod/networking_common.go          175 b, rerr := regexp.MatchString("Couldn't load target `CNI-[a-f0-9]{24}':No such file or directory|Chain 'CNI-[a-f0-9]{24}' does not exist", err.Error())
>    21 libpod/options.go                     26 "github.com/containers/storage/pkg/regexp"
>    22 libpod/options.go                     32 var umaskRegex = regexp.Delayed(`^[0-7]{1,4}$`)
>    23 pkg/util/utils.go                     12 "regexp"
>    24 pkg/util/utils.go                     92 m, err := regexp.MatchString(r, s)
>    25 pkg/bindings/images/build.go          27 "github.com/containers/storage/pkg/regexp"
>    26 pkg/bindings/images/build.go          39 var iidRegex = regexp.Delayed(`^[0-9a-f]{12}`)
>    27 pkg/domain/filters/volumes.go          6 "regexp"
>    28 pkg/domain/filters/volumes.go         20 nameRegexp, err := regexp.Compile(val)
>    29 pkg/ps/ps.go                           8 "regexp"
>    30 pkg/ps/ps.go                         322 reg := regexp.MustCompile(`.*\[|\].*`)
>    31 pkg/specgen/generate/kube/kube.go     12 "regexp"
>    32 pkg/specgen/generate/kube/kube.go    870 fieldPathLabelRegex := regexp.MustCompile(fieldPathLabelPattern)
>    33 pkg/specgen/generate/kube/kube.go    872 fieldPathAnnotationRegex := regexp.MustCompile(fieldPathAnnotationPattern)
>    34 pkg/systemd/quadlet/quadlet.go         9 "github.com/containers/storage/pkg/regexp"
>    35 pkg/systemd/quadlet/quadlet.go        77 validPortRange = regexp.Delayed(`\d+(-\d+)?(/udp|/tcp)?$`)
> ```

but these are already created when needed and not at "init" time, so it should not be a problem?

**Comment by vrothberg** [comment]
> but these are already created when needed and not at "init" time, so it should not be a problem?

D'oh ... you're absolutely right.  I'll grab a fresh coffee.

/lgtm

**Pull request merged**
