### PR TITLE
test,manifest-run: declare `TARGETPLATFORM` in test containerfile.

### PR DESCRIPTION
**Pull request by flouthoc**
As part of fix for https://github.com/openshift/imagebuilder/issues/231
`FROM` does not expands `ARGS` which are not declared so declare
`TARGETPLATFORM`

Note: I think a patch should be added at imagebuilder to allow using
inbuilt ARGS  in `FROM` without declaring it as well but it is something
to be discussed so lets declare it manually in our tests anyways since following test
does not exercises that.

[NO NEW TESTS NEEDED]
[NO TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by flouthoc** [comment]
@edsantiago PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM
@rhatdan PTAL

**Comment by vrothberg** [comment]
@flouthoc just to be extra sure.  Is the assumption correct that updating Buildah just revealed this bug (i.e., the Dockerfile should never have worked in the first place)?

**Comment by flouthoc** [comment]
@vrothberg Yes since imagebuilder got updated in buildah today: https://github.com/containers/buildah/pull/4061, I still think this dockerfile is valid without declaring and should allow pre-built args but need to check against buildkit once and all of tests in buildah already declare `ARG` in containerfile as well so it works.

**Comment by edsantiago** [comment]
/lgtm

I'll run treadmill once this merges, and we'll see how it goes.

**Pull request merged**
