### PR TITLE
Changed permission of .ubuntu_prepare.sh to 755

### PR DESCRIPTION
**Pull request by stefins**
Signed-off-by: Stefin <stefin@pm.me>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Please add [NO NEW TESTS NEEDED] github message and repush.

Does this fix something?

**Review by Luap99 — COMMENTED** [review]
Commit message does not match the change, the file is changed to 755 but your commit message states 775. IMO 755 is correct so please update the commit message.

**Comment by stefins** [comment]
@Luap99 Sorry my bad!

**Comment by TomSweeneyRedHat** [comment]
@stefins you need to add `[NO NEW TESTS NEEDED]` to your commit description and push again.
Changes LGTM otherwise

**Comment by stefins** [comment]
@TomSweeneyRedHat I already did it

**Pull request merged**
