### PR TITLE
Vendor in containers/(common, storage, image)

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Vendor dance without Buildah.

**Comment by TomSweeneyRedHat** [comment]
It would be good to complete the dance by getting Buildah in here too.

**Comment by rhatdan** [comment]
Yup, Buildah is not ready yet.

**Comment by rhatdan** [comment]
@flouthoc @vrothberg @giuseppe @Luap99 PTAL

**Review by flouthoc — APPROVED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by edsantiago** [comment]
Interesting that this did not trigger the bloat alert.

**Comment by edsantiago** [comment]
It just barely squeaked past the bloat check:
```
bin/podman           size= 45134512  delta= 45192
bin/podman-remote    size= 34175984  delta= 45384
bin/rootlessport     size=  4597736  delta=   192
```

**Pull request merged**
