### PR TITLE
Update to use gopkg.in/yaml.v3

### PR DESCRIPTION
**Pull request by rhatdan**
[NO NEW TESTS NEEDED]

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
Also opened PR https://github.com/kubernetes-sigs/yaml/pull/80
And need 
https://github.com/ghodss/yaml/pull/62 to be merged.

**Comment by Luap99** [comment]
> Also opened PR [kubernetes-sigs/yaml#80](https://github.com/kubernetes-sigs/yaml/pull/80) And need [ghodss/yaml#62](https://github.com/ghodss/yaml/pull/62) to be merged.

Note both packages are basically the same, if possible it would be good if we can just use one of them.

**Comment by rhatdan** [comment]
@Luap99 firstone to move to yaml.v3.  :^)

**Comment by edsantiago** [comment]
LGTM

**Pull request merged**
