### PR TITLE
[CI:DOCS] [4.2] Backport MacOS pkginstaller 

### PR DESCRIPTION
**Pull request by ashley-cui**
#### Does this PR introduce a user-facing change?

```release-note
None

```

### CODE REVIEW

**Comment by ashley-cui** [comment]
@anjannath @gbraad PTAL, Did I get all the commits we need?

**Comment by gbraad** [comment]
Looks good to me, but prefer @anjannath to verify as I can't test this now. PTO.

**Comment by anjannath** [comment]
> @anjannath @gbraad PTAL, Did I get all the commits we need?

yes it has all the commits, thanks

**Comment by ashley-cui** [comment]
@containers/podman-maintainers PTAL and merge

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
I'm going to lead the charge here, save a few bits, and merge this.

/lgtm

**Pull request merged**
