### PR TITLE
[CI:DOCS] Some distros do not default to docker.io for shortname searches

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/18910

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM, but CI is very angry. I restarted tests, but we may need a restart.

**Comment by mheon** [comment]
Sorry, a rebase, not a restart.

**Comment by baude** [comment]
needs rebase i think

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
Tests are still very red though.

**Comment by vrothberg** [comment]
> Tests are still very red though.

All infra flakes.  We can restart those.

**Comment by vrothberg** [comment]
Ah, "The referenced image resource cannot be found" ... it really needs a rebase

**Comment by rhatdan** [comment]
Yikes I accidently overrode this

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons.

**Pull request merged**
