### PR TITLE
[v1.9] Update golang.org/x/text

### PR DESCRIPTION
**Pull request by mheon**
As the title says.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
If this addresses a BZ, could you included the BZ number  in the description please?

**Comment by mheon** [comment]
Ah, v1.9 CI is still hosed after the libpod->podman move.

**Comment by mheon** [comment]
@TomSweeneyRedHat I'm hesitant to do that for internal-only BZs.

**Comment by TomSweeneyRedHat** [comment]
@mheon, that's a very good point and I'd forgotten that BZ was one.  SGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@mheon Is the CI broken for 1.9?

**Comment by rhatdan** [comment]
I don't see us ever updating 1.9 branch so closing.

**Pull request closed without merging**
