### PR TITLE
Report Download complete in Compatibility mode

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/10258

[NO TESTS NEEDED] Difficult to create tests for this.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon Should we just always return "Download complete"?

**Comment by mheon** [comment]
I'm fine with always returning "Download complete". What the Java library is doing here is honestly nonsensical, IMO - string-arsing human readable output should not be expected to produce sane results.

**Comment by jwhonce** [comment]
@mheon Comes from a poor API

/lgtm
/hold

**Pull request merged**
