### PR TITLE
benchmarks: push/pull

### PR DESCRIPTION
**Pull request by vrothberg**
Polish the push and pull benchmarks.  In particular, make sure to not be
network bound during these benchmarks by running a local registry and
pushing a local image that can later on be pulled.

Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@edsantiago PTAL

**Comment by edsantiago** [comment]
I still can't test anything due to the `Timed out after 90.001s.` issue.

**Comment by vrothberg** [comment]
@edsantiago can you share where you get the timeout?

**Comment by edsantiago** [comment]
```
• Failure [104.078 seconds]                                                                                                                                     
Podman Benchmark Suite                                                                                                                                          
/home/esm/src/atomic/2018-02.podman/libpod/test/e2e/benchmarks_test.go:66                                                                                       
  Podman Benchmark Suite [Measurement]                                                                                                                          
  /home/esm/src/atomic/2018-02.podman/libpod/test/e2e/benchmarks_test.go:121                                                                                    
                                                                                                                                                                
  Timed out after 90.001s.                                                                                                                                      
  Expected process to exit.  It did not.                                                                                                                        
                                                                                                                                                                
  /home/esm/src/atomic/2018-02.podman/libpod/test/utils/utils.go:368         
```

**Comment by vrothberg** [comment]
Very curious, thanks! Does it work with the following diff?
```diff
diff --git a/test/e2e/benchmarks_test.go b/test/e2e/benchmarks_test.go
index 0e7bc8a69c6c..0321190a1a68 100644
--- a/test/e2e/benchmarks_test.go
+++ b/test/e2e/benchmarks_test.go
@@ -181,7 +181,12 @@ var _ = Describe("Podman Benchmark Suite", func() {
                        session := podmanTest.Podman([]string{"push", "--tls-verify=false", "--creds", user + ":" + pass, UBI_INIT, "localhost:" + port + "/repo/image:tag"})
                        session.WaitWithDefaultTimeout()
                        Expect(session).Should(Exit(0))
-               }, &newBenchmarkOptions{needsRegistry: true})
+               }, &newBenchmarkOptions{
+                       needsRegistry: true,
+                       init: func() {
+                               podmanTest.AddImageToRWStore(UBI_INIT)
+                       },
+               })
 
                newBenchmark("podman pull", func() {
                        port, user, pass := getPortUserPass()
@@ -191,6 +196,7 @@ var _ = Describe("Podman Benchmark Suite", func() {
                }, &newBenchmarkOptions{
                        needsRegistry: true,
                        init: func() {
+                               podmanTest.AddImageToRWStore(UBI_INIT)
                                port, user, pass := getPortUserPass()
                                session := podmanTest.Podman([]string{"push", "--tls-verify=false", "--creds", user + ":" + pass, UBI_INIT, "localhost:" + port + "/repo/image:tag"})
                                session.WaitWithDefaultTimeout()
```

**Comment by edsantiago** [comment]
nope, looks like same error:
```
• Failure [109.763 seconds]
Podman Benchmark Suite
/home/esm/src/atomic/2018-02.podman/libpod/test/e2e/benchmarks_test.go:66
  Podman Benchmark Suite [Measurement]
  /home/esm/src/atomic/2018-02.podman/libpod/test/e2e/benchmarks_test.go:121

  Timed out after 90.001s.
  Expected process to exit.  It did not.

  /home/esm/src/atomic/2018-02.podman/libpod/test/utils/utils.go:368
```

**Comment by vrothberg** [comment]
Aaaah, I begin to believe it's the `podman-registry` script pulling.

**Comment by vrothberg** [comment]
Okay, now I tested it without network and it's working.  My suspicion of `podman-registry` pulling down the image was correct.  I extended the go-bindings for it to support passing custom images which is now the tar file.

Once merged, I will apply the same changes to other e2e tests using `podman-registry` to use the local tar file instead of pulling the image down. Should help in the ongoing test speedups.

@edsantiago, mind taking another look?

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

Ed is out and I tested it locally disconnected from the network.

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
@flouthoc @Luap99 mind merging? I'll polish the e2e tests after.

**Review by giuseppe — APPROVED** [review]
/lgtm

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm

**Pull request merged**
