### PR TITLE
applehv: return socket path from setupAPIForwarding

### PR DESCRIPTION
**Pull request by cfergeau**
When starting podman machine with applehv, this warning is printed: 
WARN[0025] API socket failed ping test

This is due to a bug in applehv.setupAPIForwarding which is not returning
the path to the socket, which causes `WaitAndPingAPI` to be called with
`""` as the socket path, triggering the warning.

This commit changes setupAPIForwarding to be similar to the implementation
in the other machine implementations.

#### Does this PR introduce a user-facing change?
```release-note
none
```

### CODE REVIEW

**Comment by mheon** [comment]
Needs a test or `[NO NEW TESTS NEEDED]`

**Comment by cfergeau** [comment]
> Needs a test or `[NO NEW TESTS NEEDED]`

I don't know how to add a test for it, if you have pointers I can look into it.
However, it's more usefully tested in an end-to-end podman-machine scenario, as this bug means there's always a warning when running `podman machine start` with applehv, so I'd lean towards just adding `[NO NEW TESTS NEEDED]`

**Pull request merged**
