### PR TITLE
Update to go 1.21

### PR DESCRIPTION
**Pull request by Luap99**
So that we can continue updating our dependencies.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
`toolchain` is now affecting epel builds.

**Comment by Luap99** [comment]
Uh yes, they only ship go 1.20 there?

>  golang                   x86_64 1.20.12-4.el9_3        appstream         616 k

**Comment by lsm5** [comment]
> @lsm5 Can we ignore the epel-9 error? How is golang sourced there, I see much newer versions in centos 9 stream?

the `epel` targets on copr are actually `rhel + epel`, so they are behind actual centos stream. We could ignore the epel failures.

An alternative would be that I could update our copr with a golang build from centos-stream and that could be used for these `epel` build jobs.

**Comment by lsm5** [comment]
> An alternative would be that I could update our copr with a golang build from centos-stream and that could be used for these `epel` build jobs.

@Luap99 I'm building it at https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/7340248/ . Once that's ready, I think we can retrigger the epel build jobs here.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
