### PR TITLE
Cirrus: Workaround F32 BFQ Kernel bug

### LINKED ISSUE #8068: Cirrus CI: agent stopped responding
This is now far and away the most common CI flake.

* fedora : Test Bindings
  * PR #7961
    * [10-08 00:33]()
  * PR #7940
    * [10-06 13:43]()
  * PR #7853
    * [10-12 10:08]()
* fedora : int podman fedora-32 root host
  * PR #8061
    * [10-19 11:39]()
  * PR #8044
    * [10-17 10:28]()
  * PR #8039
    * [10-15 23:50]()
  * PR #8028
    * [10-15 05:41]()
  * PR #8021
    * [10-14 15:19]()
    * [10-14 14:39]()
  * PR #8013
    * [10-14 17:57]()
    * [10-14 17:31]()
  * PR #7996
    * [10-12 13:50]()
  * PR #7992
    * [10-16 05:53]()
  * PR #7987
    * [10-13 21:22]()
  * PR #7977
    * [10-09 07:08]()
    * [10-09 06:45]()
  * PR #7969
    * [10-08 15:56]()
  * PR #7967
    * [10-13 12:29]()
  * PR #7949
    * [10-07 13:22]()
  * PR #7919
    * [10-05 11:35]()
    * [10-05 11:12]()
  * PR #7904
    * [10-05 14:39]()
  * PR #7891
    * [10-09 07:29]()
    * [10-09 06:57]()
* fedora : int remote fedora-32 root host
  * PR #8030
    * [10-15 07:58]()
    * [10-15 06:55]()
  * PR #8018
    * [10-14 13:30]()
  * PR #8003
    * [10-13 17:33]()
  * PR #7987
    * [10-13 21:17]()
  * PR #7969
    * [10-08 16:09]()
  * PR #7966
    * [10-08 14:06]()
  * PR #7961
    * [10-08 01:07]()
  * PR #7690
    * [10-09 23:26]()
* fedora : sys podman fedora-32 root host
  * PR #8061
    * [10-19 12:40]()
  * PR #7980
    * [10-12 04:01]()
  * PR #7966
    * [10-08 14:07]()
  * PR #7910
    * [10-07 12:04]()
  * PR #7904
    * [10-05 15:26]()
  * PR #7845
    * [10-07 12:06]()
  * PR #7382
    * [10-07 11:12]()
* fedora : sys remote fedora-32 root host
  * PR #8030
    * [10-15 09:49]()
    * [10-15 09:30]()
    * [10-15 09:11]()
    * [10-15 08:40]()
    * [10-15 08:20]()
  * PR #8028
    * [10-15 08:12]()
    * [10-15 07:50]()
    * [10-15 06:58]()
    * [10-15 06:36]()
  * PR #8025
    * [10-14 18:52]()
  * PR #8021
    * [10-14 16:14]()
  * PR #8018
    * [10-14 13:14]()
    * [10-14 12:53]()
  * PR #8009
    * [10-13 14:24]()
  * PR #8003
    * [10-13 18:30]()
    * [10-13 18:26]()
    * [10-13 18:05]()
  * PR #7992
    * [10-16 07:06]()
    * [10-16 06:48]()
  * PR #7984
    * [10-09 20:55]()
    * [10-09 20:37]()
    * [10-09 20:35]()
    * [10-09 20:35]()
    * [10-09 20:33]()
    * [10-09 18:02]()
    * [10-09 17:28]()
    * [10-09 17:08]()
  * PR #7977
    * [10-09 11:59]()
    * [10-09 11:41]()
  * PR #7973
    * [10-08 21:09]()
    * [10-08 20:51]()
    * [10-08 19:28]()
    * [10-08 19:09]()
  * PR #7971
    * [10-08 17:35]()
  * PR #7969
    * [10-08 17:06]()
    * [10-08 16:46]()
  * PR #7968
    * [10-09 14:58]()
    * [10-09 14:36]()
  * PR #7937
    * [10-07 11:04]()
    * [10-07 10:39]()
  * PR #7926
    * [10-05 14:42]()
  * PR #7853
    * [10-12 11:52]()
  * PR #7845
    * [10-07 12:06]()
  * PR #7588
    * [10-05 17:21]()
  * PR #7382
    * [10-07 11:11]()
* prior-fedora : int podman fedora-31 root host
  * PR #8061
    * [10-19 11:41]()
  * PR #8035
    * [10-15 12:16]()
    * [10-15 11:42]()
  * PR #8030
    * [10-15 06:58]()
  * PR #8029
    * [10-15 13:56]()
  * PR #8003
    * [10-13 17:13]()
  * PR #8000
    * [10-12 17:28]()
    * [10-12 16:48]()
  * PR #7995
    * [10-12 12:36]()
    * [10-12 11:57]()
  * PR #7992
    * [10-16 05:55]()
  * PR #7986
    * [10-09 19:22]()
  * PR #7983
    * [10-09 21:00]()
  * PR #7977
    * [10-09 06:56]()
  * PR #7974
    * [10-08 19:38]()
  * PR #7967
    * [10-13 12:36]()
  * PR #7931
    * [10-05 18:33]()
  * PR #7908
    * [10-15 10:59]()
  * PR #7853
    * [10-12 10:56]()
    * [10-12 10:19]()
  * PR #7836
    * [10-09 12:30]()
* prior-fedora : int remote fedora-31 root host
  * PR #8044
    * [10-17 10:36]()
  * PR #8003
    * [10-13 18:12]()
    * [10-13 17:46]()
  * PR #7996
    * [10-12 14:22]()
  * PR #7940
    * [10-06 14:03]()
  * PR #7931
    * [10-05 19:22]()
  * PR #7924
    * [10-05 15:16]()
    * [10-05 14:47]()
  * PR #7904
    * [10-05 14:54]()
  * PR #7845
    * [10-07 11:33]()
  * PR #7588
    * [10-05 16:57]()
* prior-fedora : sys podman fedora-31 root host
  * PR #7904
    * [10-05 15:25]()
  * PR #7891
    * [10-09 07:46]()
* prior-fedora : sys remote fedora-31 root host
  * PR #8061
    * [10-19 13:01]()
    * [10-19 12:39]()
  * PR #8044
    * [10-17 17:34]()
    * [10-17 11:40]()
    * [10-17 11:20]()
  * PR #8039
    * [10-16 00:41]()
  * PR #8035
    * [10-15 14:08]()
    * [10-15 13:48]()
  * PR #8021
    * [10-14 16:16]()
  * PR #8018
    * [10-14 12:54]()
  * PR #7996
    * [10-12 14:57]()
    * [10-12 14:39]()
  * PR #7995
    * [10-12 12:42]()
  * PR #7992
    * [10-16 07:55]()
    * [10-16 07:06]()
    * [10-16 06:44]()
  * PR #7987
    * [10-13 22:12]()
  * PR #7986
    * [10-09 20:10]()
  * PR #7977
    * [10-09 11:57]()
    * [10-09 11:39]()
  * PR #7975
    * [10-09 06:33]()
    * [10-09 06:05]()
    * [10-08 23:51]()
    * [10-08 23:33]()
    * [10-08 23:30]()
    * [10-08 23:00]()
    * [10-08 22:39]()
  * PR #7955
    * [10-07 16:43]()
  * PR #7943
    * [10-07 12:13]()
  * PR #7940
    * [10-06 14:22]()
  * PR #7920
    * [10-05 11:21]()
  * PR #7910
    * [10-07 12:22]()
    * [10-07 12:02]()
  * PR #7908
    * [10-15 12:03]()
    * [10-15 11:45]()
  * PR #7904
    * [10-05 15:23]()
  * PR #7845
    * [10-07 12:04]()
  * PR #7836
    * [10-09 13:45]()
    * [10-09 13:24]()
  * PR #7382
    * [10-07 11:26]()

### PR DESCRIPTION
**Pull request by cevich**
Fixes #8068

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once you're ready

**Comment by cevich** [comment]
I've rebased my instrumented/testing PR on this: #8169 to help confirm the problem is ***only*** on F32 and that the previous workaround functions.

**Comment by cevich** [comment]
Update: Given the "lively" discussion in https://bugzilla.redhat.com/show_bug.cgi?id=1851783 I'm considering if we aught to simply and globally use the *deadline* scheduler.  Also seeing (from other bugs) as this is the second time BFQ has broken for people.

**Comment by cevich** [comment]
Update: I'm investigating additional cases of agent-stopped-responding in F31.  May need to include the fix there as well, until we can get up to F33 (#8074)

**Comment by rhatdan** [comment]
LGTM
@cevich ready to get this in.  I think you can work on other changes in a different PR,  we need to get this in now.

**Comment by cevich** [comment]
> I think you can work on other changes in a different PR

No, not true.  I'm still seeing remarkably similar failures on F31.  I'm testing out application of the 'deadline' scheduler workaround for all VMs, and also to "even the playing field".  Should be finished shortly...

**Comment by cevich** [comment]
Update: Rebased + deadline workaround for all platforms: Testing in parallel with #8169 (instrumented)

**Comment by cevich** [comment]
***Important Observation***: I'm noticing a significant increase in runtime for the all the "remote", especially Ubuntu.  Unf. I'm also seeing (in other PRs) what appear like general google-cloud networking hiccups/slowdowns.  There's no way I can separate these two (or more) affects on test runtime.

If the problem persists, we should consider following the [google recommendations for increasing storage performance.](https://cloud.google.com/compute/docs/disks/optimizing-pd-performance)

**Comment by cevich** [comment]
@mheon @rhatdan okay, I feel comfortable with merging this now.

**Comment by mheon** [comment]
/approve
LGTM

**Pull request merged**
