### PR TITLE
[v4.9] [skip-ci] packit: update fedora downstream branches

### PR DESCRIPTION
**Pull request by lsm5**
v4.9 only for Fedora 38 and 39. Fedora rawhide and 40 will move to v5.

#### Does this PR introduce a user-facing change?

```release-note
None
```

Don't need ci for this.

### CODE REVIEW

**Comment by lsm5** [comment]
@mheon @ashley-cui let's get this in if possible before v4.9.3 . Not a blocker for the release though, just nice to have.

**Comment by lsm5** [comment]
let's merge this manually. No point wasting CI resources for this.

**Comment by lsm5** [comment]
actually now i'm not too sure if this would work, given i'm hearing that for downstream Fedora tasks, packit will use the config in the rawhide branch. Regardless, this change doesn't hurt upstream and should be safe to merge.

**Review by ashley-cui — COMMENTED** [review]
/lgtm

**Pull request merged**
