### PR TITLE
[v4.6.1-rhel] Bump c/* projects for RHEL 8.9/9.3

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
In preparation for RHEL 8.9/9.3 bump:

c/image v5.26.2
c/common v0.55.4
c/buildah v.1.31.3

c/image was bumped prior to 1.48.1

[NO NEW TESTS NEEDED]
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@ashley-cui if you're around, PTAL
Turns out my sandbox had some ugly bits in it, I'd to wipe it and restart from scratch.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 @vrothberg @flouthoc @rhatdan PTAL and merge if it LGTY when you get in on Friday.

**Comment by edsantiago** [comment]
LGTM. And on my end, I treadmilled the new buildah into #13808 and everything passed.

**Pull request merged**
