### PR TITLE
play kube envVar.valueFrom.resourceFieldRef

### PR DESCRIPTION
**Pull request by ydayagi**
add support for env vars values from container resources
see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#envvarsource-v1-core

relates to issue https://github.com/containers/podman/issues/12756
relates to bug https://github.com/containers/podman/issues/13115

Signed-off-by: Yaron Dayagi <ydayagi@redhat.com>

### CODE REVIEW

**Comment by ydayagi** [comment]
@umohnani8 @rhatdan PR is ready for your review.
There's a [bug](https://github.com/containers/podman/issues/13115) related to it as well.
I'll be happy to fix it.

**Comment by rhatdan** [comment]
You are failing lint, and need a tests.

**Comment by ydayagi** [comment]
> You are failing lint, and need a tests.

oops. although....there are other lint errors in the file prior to my changes. weird.
what do u mean by tests? you mean pass the CI tests/checks?

**Comment by rhatdan** [comment]
/approve
LGTM
@haircommander @saschagrunert @umohnani8 @mrunalp PTAL

**Pull request merged**
