### PR TITLE
fix the .Path and .Args when use the infra-command

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Fixes: https://github.com/containers/podman/issues/7673
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@zhangguanzhang Remote tests do not seem to be happy

**Comment by zhangguanzhang** [comment]
I will fix this when I have time

**Comment by edsantiago** [comment]
All tests are unhappy; but FWIW it now passes my (new, unsubmitted) `--infra-image + --infra-command` test. You're on the right track, thank you!

**Comment by edsantiago** [comment]
I have a system test (BATS) that tests this fairly thoroughly, so don't feel any need to write one. I will submit my PR as soon as yours merges (because, obviously, it will not pass on master right now).

**Comment by zhangguanzhang** [comment]
> 我有一个系统测试（BATS），可以对它进行全面的测试，因此不需要编写任何文件。您的合并后，我会立即提交我的PR（因为显然，它现在不会继续通过Master）。

Does this mean I should remove the e2e I wrote？

**Comment by edsantiago** [comment]
No, those are a good idea - multiple levels of testing are good. What I meant was, if you were thinking of writing a system test, you don't need to :grin:

**Comment by zhangguanzhang** [comment]
My local test is normal, I don’t know why Args is empty in ci

**Comment by edsantiago** [comment]
You are using `Expect(check1` when you should be using `check2` :wink:

**Comment by zhangguanzhang** [comment]
> You are using `Expect(check1` when you should be using `check2` 😉

oops, wrong copy😅

**Review by edsantiago — APPROVED** [review]
I tested against my new BATS pod infra tests; all passes. Nice work.

**Comment by rhatdan** [comment]
Thanks @zhangguanzhang 
/lgtm

**Pull request merged**
