### PR TITLE
[NO NEW TESTS NEEDED] Fix destination branch for v3.4.2-rhel

### PR DESCRIPTION
**Pull request by mheon**
Necessary to make Cirrus happy.

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by mheon** [comment]
@edsantiago Where is the [NO NEW TESTS NEEDED] tag recognized, again? Commit title, PR title, commit description...?

**Comment by mheon** [comment]
@cevich PTAL

**Comment by edsantiago** [comment]
Magic string not needed for `/cirrus.yml` - only changes. But the preferred place is git commit message.

**Comment by mheon** [comment]
Uh-oh. The static build task is pulling an image from docker.io, and I think it might be rate-limiting us now.

**Comment by TomSweeneyRedHat** [comment]
LGTM
all happy green tests.  @mheon, is this gtg?

**Comment by cevich** [comment]
LGTM

**Comment by mheon** [comment]
Ready to merge

**Pull request merged**
