### PR TITLE
Bump to v3.2.0

### PR DESCRIPTION
**Pull request by mheon**
Two final backports, final release notes update, and version bump.

### CODE REVIEW

**Comment by jwhonce** [comment]
LGTM

**Comment by mheon** [comment]
Had to force-push again to fix release notes.

**Comment by mheon** [comment]
Also, apparently branch protection isn't set up for this branch yet. Let me fix that.

**Comment by edsantiago** [comment]
Needs a tweak here https://github.com/containers/podman/blob/a53251e1c670b15d3368c0b2396b723a4c3aa266/test/apiv2/01-basic.at#L22

I thought we had done something in this test to prevent it from failing on each release?

**Comment by mheon** [comment]
I seem to recall us doing that as well...

**Comment by mheon** [comment]
Evidently only for API version, not minimum API version.

**Comment by mheon** [comment]
@containers/podman-maintainers Anyone want to drop an LGTM? Looks like we're going to go green.

**Pull request merged**
