### PR TITLE
Quadlet: Add support for the Secret key in Container group

### PR DESCRIPTION
**Pull request by ygalblum**
Add E2E tests
Add system test
Add to man page

Signed-off-by: Ygal Blum <ygal.blum@gmail.com>

#### Does this PR introduce a user-facing change?
Yes

```release-note
Quadlet: Add support for the Secret key in Container group
```

### CODE REVIEW

**Comment by ygalblum** [comment]
@vrothberg I would like to use this capability in the demo code for the blog post. Can this change be merged to 4.4.x?

**Comment by vrothberg** [comment]
> @vrothberg I would like to use this capability in the demo code for the blog post. Can this change be merged to 4.4.x?

No new features for 4.4 anymore :(  Can you use `PodmanArgs` instead and mention that it'll be 4.5 feature?

**Comment by vrothberg** [comment]
@rhatdan @alexlarsson PTAL

**Comment by ygalblum** [comment]
> > @vrothberg I would like to use this capability in the demo code for the blog post. Can this change be merged to 4.4.x?
> 
> No new features for 4.4 anymore :( Can you use `PodmanArgs` instead and mention that it'll be a 4.5 feature?

I guess I can use PodmanArgs, it just won't be as clean :(. But, rules are rules

**Pull request merged**
