### PR TITLE
Vendor in latest containers/common

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg PTAL
Looks like containers/common and Podman tests suite are out of sync

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but yeah, test suite is not so hip.

**Comment by vrothberg** [comment]
> @vrothberg PTAL Looks like containers/common and Podman tests suite are out of sync

Eugh ... me again :cry: Apologies, I'll take a look immediately.

**Comment by vrothberg** [comment]
- common: https://github.com/containers/common/pull/882
- podman: https://github.com/containers/podman/pull/12821

**Pull request closed without merging**
