### PR TITLE
rootless: use functionalities from c/storage

### PR DESCRIPTION
**Pull request by giuseppe**
[NO NEW TESTS NEEDED] no new functionalities are added.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by martinpitt** [comment]
Same containers-common regression as in https://github.com/containers/podman/pull/20595#issuecomment-1794098183 . This will affect all podman PRs from now on, so I'll shut up about it for the future ones.

**Comment by mtrmac** [comment]
Ref. https://github.com/containers/storage/pull/1740#discussion_r1381969764 for a hint at the relevant concerns (which I know ~nothing about).

---

As a vague meta-comment, I wouldn’t object to ending up with a family of functions (“is not privileged root”, “is running inside a user namespace of any kind, including non-container ones”). Obviously that is not ideal:
- it would complicate the picture
- callers would need to think about which ones to call when
- we would need to ensure that “the same” condition is consistently using the same predicate

having a single predicate _if possible_ would certainly be better; but if there were conflicting trade-offs, but expressing the design concerns explicitly would surface the trade-offs and allow us to make different choices in different places, if warranted.

**Comment by lsm5** [comment]
> Ephemeral COPR build failed. @containers/packit-build please check.

something's up with GOPROXY on c9s. Ignore for now

**Comment by giuseppe** [comment]
ready for review

**Comment by rhatdan** [comment]
LGTM

**Review by mtrmac — COMMENTED** [review]
As linked above, I don’t understand the impact of the various definitions of `IsRootless`.

Given that, I like the consolidation because there will be fewer things I don’t understand :)

Implementation LGTM, as to whether Podman should now check for full user mappings, I have no idea.

**Comment by giuseppe** [comment]
> Implementation LGTM, as to whether Podman should now check for full user mappings, I have no idea.

it would behave differently only when it is running inside a user namespace and has full capabilities.  Even in this case, now Podman will be in "rootless" mode.  But if it is "rootless" mode for c/storage and some features are not available (e.g. idmapped mounts), then I think it should be fine to treat it similarly in Podman and have just one definition for "rootless mode".

**Comment by rhatdan** [comment]
Needs a rebase.

**Comment by giuseppe** [comment]
> Needs a rebase.

rebased

**Comment by Luap99** [comment]
> > Implementation LGTM, as to whether Podman should now check for full user mappings, I have no idea.
> 
> it would behave differently only when it is running inside a user namespace and has full capabilities. Even in this case, now Podman will be in "rootless" mode. But if it is "rootless" mode for c/storage and some features are not available (e.g. idmapped mounts), then I think it should be fine to treat it similarly in Podman and have just one definition for "rootless mode".

The problem with that is that it seriously effects a lot of parts of podman, the network thing were I original noticed this as it will force the much slower rootless network logic with slirp/pasta instead of using the rootful logic which results in much faster networking.
Besides this it will effect how we read config files and what defaults we use (i.e. `/var/lib/containers` vs `$HOME.local/share/containers`). While this does not change anything when running in the init user namespace it will result in different behaviour if you run podman in a container with a usernamespace, heck this likely even breaks as we would try to always setup the pause process and there is no guarantee that there are ids setup for /etc/sub{u,g}id.

Compare this:
```
$ podman run -it --privileged -v ./:/podman   quay.io/podman/stable:latest podman info
vs
$ podman run -it --privileged -v ./:/podman   quay.io/podman/stable:latest /podman/bin/podman info

diff /tmp/podman4.7 /tmp/podman4.8
3c3
<   buildahVersion: 1.32.0
---
>   buildahVersion: 1.33.0-dev
16c16
<   databaseBackend: boltdb
---
>   databaseBackend: sqlite
23c23
<   hostname: 6c2db19960e2
---
>   hostname: ffa25a8a0057
25,26c25,38
<     gidmap: null
<     uidmap: null
---
>     gidmap:
>     - container_id: 0
>       host_id: 1000
>       size: 1
>     - container_id: 1
>       host_id: 100000
>       size: 65536
>     uidmap:
>     - container_id: 0
>       host_id: 1000
>       size: 1
>     - container_id: 1
>       host_id: 100000
>       size: 65536
30c42
<   memFree: 2448211968
---
>   memFree: 2407481344
49c61
<       rundir: /run/crun
---
>       rundir: /run/user/0/crun
65c77
<     path: /run/podman/podman.sock
---
>     path: /run/user/0/podman/podman.sock
69c81
<     rootless: false
---
>     rootless: true
85c97,98
<   uptime: 6h 22m 19.00s (Approximately 0.25 days)
---
>   uptime: 6h 23m 6.00s (Approximately 0.25 days)
>   variant: ""
106c119
<   configFile: /etc/containers/storage.conf
---
>   configFile: /root/.config/containers/storage.conf
126c139
<   graphRootUsed: 169740664832
---
>   graphRootUsed: 169740394496
141,145c154,158
<   APIVersion: 4.7.2
<   Built: 1698762721
<   BuiltTime: Tue Oct 31 14:32:01 2023
<   GitCommit: ""
<   GoVersion: go1.21.1
---
>   APIVersion: 4.8.0-dev
>   Built: 1699633134
>   BuiltTime: Fri Nov 10 16:18:54 2023
>   GitCommit: 5e11c5e50f58f7caac4e8aace9872bafadf8e070
>   GoVersion: go1.20.10
148c161
<   Version: 4.7.2
---
>   Version: 4.8.0-dev
```

This clearly shows that this has an high chance of breaking, just look at all the changed path location if someone would update their podman container image this could very well break backwards compat due chnaged paths.

**Comment by giuseppe** [comment]
thanks for checking that.

The root problem is that we conflated "IsRootless" with too many meanings.

For example, whether using `/var/lib/containers/storage` should be checked IMO simply by testing if the user owns that directory, and this would work well from a user namespace.

Similarly, the check for using slirp4netns or not should be done by checking if the current user has CAP_NET_ADMIN and that the user namespace owns the network namespace.

A single `IsRootless` cannot cover all these different cases.  The one in c/storage is correct since it is really saying whether it is root in the initial user namespace or root in another user namespace.  We could probably rename it to something clearer as `NeedsUserns` to clarify what it is about.

I've pushed a new version where `rootless.IsRootless` is maintained and uses `unshare.IsRootless` internally

**Comment by Luap99** [comment]
Yes I agree it is a bit of mess to try to guard everything by one thing, the new version seems to work as I would expect so LGTM.

**Comment by rhatdan** [comment]
@giuseppe is this still a draft?

**Comment by giuseppe** [comment]
forgot to remove the Draft, ready now

**Pull request merged**
