### PR TITLE
Match Docker pull/push by defaulting to progress write to stdout

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/21181

#### Does this PR introduce a user-facing change?

```release-note
Podman pull and push progress now goes to stdout.
```

### CODE REVIEW

**Comment by Luap99** [comment]
I am not sure how desirable this really is? It would break all scripts doing something like this: https://github.com/containers/podman/discussions/19454#discussioncomment-6604854
And the conclusion there was to not change it. Of course with 5.0 we have the option to break it but I personally don't think we should.

**Comment by rhatdan** [comment]
I guess the question is whether we want better support in "Azure DevOps pipeline" via breaking existing tools.

Azure might do a better job of checking failures, if we ask. We should probably discuss this in a meeting.

**Comment by rhatdan** [comment]
@mheon @vrothberg @baude @nalind @mtrmac WDYT?

**Comment by vrothberg** [comment]
Whatever decision we make, I urge to record it and maybe document it in the man pages.

What I don't want to is to choose between breaking either (class) of users.  Maybe add a new flag instead that allows for switching the behavior?  Maybe Azure can just run with via `--quiet`?  Certainly, Azure pipelines are important and huge but so are existing users and workloads.

**Comment by mtrmac** [comment]
I think @Luap99 is right; we can’t change the stdout format any more.

The argument that Docker does use stdout has _some_ value, but we already differ from Docker in writing the image ID; and that is only really valuable if it is the only output to stdout. (Hypothetically, we could have decided to write it to a separate file, like `podman push --digestfile` does, but we are now stuck with the current output format.)

---

I’m inclined to say the Azure error handling detection , alluded to in #21181 , is just wrong, and we shouldn’t bend over backwards for it. The Unix ~meme of using pipelines to connect programs necessarily implies that progress messages tend to go to stderr, as a _general_ principle. Meanwhile, we have exit codes to _reliably_ indicate outcome of a program.

(Compare https://github.com/containers/podman/discussions/19454#discussioncomment-6608431 .)

Of course any particular software can decide on some other semantics of stdin/out/err, exit codes, or anything else, but I think it’s valuable for all software on a platform to behave consistently, if possible; and I think it’s _completely unsustainable_ to change behavior just because _one_ consumer in the 8-billion-people-universe makes an assumption. If a similarly big company comes around next month, asking for the behavior changed back, are we… going to run an auction? 😈 

(I have no opinion on adding an option to redirect the output.)

**Comment by mheon** [comment]
I tend to agree with @mtrmac and @Luap99 - this has been part of our CLI since 1.0 and seems more correct than what Docker is doing, so I don't see a strong motivation to change.

**Comment by rhatdan** [comment]
Ok Closing.

**Pull request closed without merging**
