### PR TITLE
Build and use a newer systemd image

### PR DESCRIPTION
**Pull request by edsantiago**
...based on f37, not f31. And make it fedora-minimal so it's
smaller. And clean up dnf so it's even smaller. And tag it
with our proper YMD tag, and commit the script that builds it.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Tagging with DO NOT MERGE because I'm leaving on PTO in an hour and this is a wee bit bigger change than I feel comfortable with dropping.

But I'm submitting anyway because @vrothberg might want to use the image in his new something-something tests.

**Review by vrothberg — COMMENTED** [review]
Changes LGTM, thanks @edsantiago !

Enjoy PTO

**Comment by edsantiago** [comment]
Thanks @vrothberg! The term I was looking for is "barrier". I don't know if this image has the magic barrier code, but feel free to play with it at your leisure.

**Comment by vrothberg** [comment]
> Thanks @vrothberg! The term I was looking for is "barrier". I don't know if this image has the magic barrier code, but feel free to play with it at your leisure.

Thank you.  Yes, the new image will somehow magically send the BARRIERS as systemd-notify sends them by default now.  If tests pass with the new image, we're good.

**Comment by edsantiago** [comment]
@vrothberg I think this is ready to go; PTAL when convenient. The generated image has not changed since my initial commit last month; all I've done is fix tests and rebase. The generated image should have the `BARRIERS` functionality, at least as/if implemented in the f37 image.

**Review by vrothberg — APPROVED** [review]
LGTM, thanks ton, @edsantiago!

@containers/podman-maintainers PTAL

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
