### PR TITLE
[CI:DOCS] podman-system-service.1.md: document systemd usage

### PR DESCRIPTION
**Pull request by eriksjolund**
#### Does this PR introduce a user-facing change?

```release-note
None
```

(I didn't document how it works on macOS and Windows)

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by eriksjolund** [comment]
I plan to rewrite it a bit. (No need for reviews right now)

**Comment by eriksjolund** [comment]
I rewrote most parts of the first version.

There was an already existing paragraph about the API that I moved to the top. 
 (I can move it back again if you want)

**Pull request merged**
