### PR TITLE
(Temporary) Emergency CI fix: quay search is broken

### PR DESCRIPTION
**Pull request by edsantiago**
Someone please revert this once quay search is fixed.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Yes, I reported it. No response yet, and no acknowledgment on https://status.quay.io/

**Review by Luap99 — APPROVED** [review]
LGTM, I guess technically speaking there is no real need to revert this? As long as we use an image under our control it should be good enough.

**Comment by edsantiago** [comment]
I have a medium preference for reverting, because it spreads testing over more namespaces ... but then again, the current quay failure was unpredictable, and there's (probably) nothing we can do about it from the podman side, so such testing probably doesn't gain us anything anyway.

**Comment by edsantiago** [comment]
@containers/podman-maintainers mergeme please. Blue-robot builds are still running, I no longer care about them.

**Pull request merged**
