### PR TITLE
fix: respect "--extract" flag for podman cp

### PR DESCRIPTION
**Pull request by matejvasek**
Signed-off-by: Matej Vasek <mvasek@redhat.com>

### CODE REVIEW

**Comment by matejvasek** [comment]
I would expect that `podman cp --extract a.tar "625099cc3ea5:/"` woud extract the tar to root, but instead it just copies the tar to root.

**Comment by rhatdan** [comment]
Could you add a test for this
/approve
LGTM other then tests.

**Comment by matejvasek** [comment]
Integration test added.

**Comment by rhatdan** [comment]
Could you squash your two PRs together, and sign them.

**Comment by matejvasek** [comment]
rebased&squahed

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL
Thanks @matejvasek

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
