### PR TITLE
Return macvlan object in /network REST API response

### PR DESCRIPTION
**Pull request by vikas-goel**
Fixes: #10266

Signed-off-by: Vikas Goel <vikas.goel@gmail.com>

### CODE REVIEW

**Comment by vikas-goel** [comment]
@Luap99 ,
Please review this PR

**Comment by rhatdan** [comment]
/approve
@mheon PTAL

**Comment by mheon** [comment]
LGTM but I think we need a review from @baude before merge

**Review by Luap99 — COMMENTED** [review]
Code LGTM but the test not, you are testing the libpod endpoint and your code fixes a bug in the docker compat api. The test should call the compat api.

**Comment by vikas-goel** [comment]
> Code LGTM but the test not, you are testing the libpod endpoint and your code fixes a bug in the docker compat api. The test should call the compat api.

Sure, @Luap99. Will the following be sufficient?


t GET networks?filters='{"name":["macvlan1"]}' 200 \
  length=1

**Comment by Luap99** [comment]
> t GET networks/macvlan1 200
> length=1

yes but you should check the name at least not only length

**Comment by vikas-goel** [comment]
> > t GET networks/macvlan1 200
> > length=1
> 
> yes but you should check the name at least not only length

Ok. I will add to it.
.[0].Name=macvlan1

**Comment by vikas-goel** [comment]
The test for this PR change is passing.
```
[+0067s] ok 664 [35-networks] GET libpod/networks/macvlan1/json : status=200
[+0067s] ok 665 [35-networks] GET libpod/networks/macvlan1/json : .name=macvlan1
[+0067s] ok 666 [35-networks] GET networks/macvlan1 : status=200
[+0067s] ok 667 [35-networks] GET networks/macvlan1 : .Name=macvlan1
[+0067s] ok 668 [35-networks] DELETE libpod/networks/macvlan1 : status=200
[+0067s] ok 669 [35-networks] DELETE libpod/networks/macvlan1 : .[0].Name ('macvlan1') ~ macvlan1
[+0067s] ok 670 [35-networks] DELETE libpod/networks/macvlan1 : .[0].Err=null
```
The two test suites APIv2 test on fedora-34 and compose test on fedora-34 (root) failing for unrelated reasons. How can we get overcome the failures?

**Comment by Luap99** [comment]
I restarted the failing tests.

**Comment by TomSweeneyRedHat** [comment]
@vikas-goel thanks for the work on this.  @edsantiago is the below a known flake we're chasing?
```
[+0217s] Traceback (most recent call last):
[+0217s]   File "/var/tmp/go/src/github.com/containers/podman/test/python/docker/compat/test_containers.py", line 253, in test_mount_preexisting_dir
[+0217s]     self.assertTrue(out.startswith(b'1042:1043'), "assert correct uid/gid")
[+0217s] AssertionError: False is not true : assert correct uid/gid
```

**Comment by edsantiago** [comment]
@TomSweeneyRedHat yes, "false is not true" is one of the flakes I've been seeing a lot of. I haven't filed an issue for it because the error message is so annoying. I've restarted the test.

**Comment by vikas-goel** [comment]
@Luap99 ,
The PR has all the suggestions incorporated, the approval and the checks passing.

**Comment by Luap99** [comment]
Thanks @vikas-goel

**Comment by mheon** [comment]
@Luap99 @baude PTAL and merge

**Comment by Luap99** [comment]
> @Luap99 @baude PTAL and merge

@mheon I already merged this one!

**Comment by mheon** [comment]
What I get for commenting without refreshing the page. Thanks!

**Comment by vikas-goel** [comment]
Thank you all.

**Pull request merged**
