### PR TITLE
Trim whitespace from unit files while parsing

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/18979

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@bachradsusi  @vrothberg @ygalblum @alexlarsson PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM but note that `strings.TrimSpace` will also left-trim.  We may consider using [TrimRight](https://pkg.go.dev/strings#TrimRight) instead.

**Comment by rhatdan** [comment]
I went back and forth on that.

Should the following be valid:

"   RemapUsers: keep-id    "

**Comment by vrothberg** [comment]
Probably worth checking how `systemd` deals with such cases.  I am currently flooded and won't find time until Monday to dig into it.

**Comment by bachradsusi** [comment]
This PR fixes my issue. Thanks!

**Comment by rhatdan** [comment]
```
# cat /etc/systemd/system/test.service
[Unit]
Description=skeeo

[Service]
Delegate=true
Type=exec
KillMode=process
   ExecStart=sleep 100   

[Install]
WantedBy=default.target
```

This service script works fine in systemd.

**Comment by TomSweeneyRedHat** [comment]
LGTM
But Catch-22, lint is choking on the trailing whitespace in the test that you're trying to add to test how it is handled....

**Comment by ygalblum** [comment]
LGTM
@vrothberg are you OK with the decision on which trim method is used?

**Review by vrothberg — COMMENTED** [review]
Yes, I am cool with trimming on both sides.  But let's also test that left-trimming works.  Right now, we test right-trims only.

**Pull request merged**
