### PR TITLE
Adjust machine CPU tests

### PR DESCRIPTION
**Pull request by ashley-cui**
Machine cpu default has changed to cpus/2, so adjust the tests to reflect that.

#### Does this PR introduce a user-facing change?

```release-note
The amount of CPUs a podman machine has now defaults to using  available cores/2. https://github.com/containers/podman/issues/17066
```

### CODE REVIEW

**Comment by ashley-cui** [comment]
Waiting on https://github.com/containers/podman/pull/20088

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by vrothberg** [comment]
Not yet happy.  LGTM, feel free to merge once green.

**Comment by ashley-cui** [comment]
@containers/podman-maintainers PTAL and merge, this should unblock common vendoring :)

**Pull request merged**
