### PR TITLE
[v5.2] Bump Buildah to v1.37.2, c/common v0.60.2, c/image v5.32.2

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.  Finishes the vendor dance for Podman v5.2.2

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
packit copr builds are probably blocked on https://github.com/fedora-copr/copr/issues/3380

**Comment by mheon** [comment]
The Mac build amd64 + arm64 step is taking almost an hour... That's suboptimal

**Comment by TomSweeneyRedHat** [comment]
I've added 6 commits for lint/mac testing fixes from main's #23614

**Comment by TomSweeneyRedHat** [comment]
And now the MacOS amd64+arm64 test is passing, in well under an hour.  Fingers crossed for the rest.

**Comment by edsantiago** [comment]
LGTM

**Pull request merged**
