### PR TITLE
Mask out /sys/dev to prevent information leak from the host

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Comment by giuseppe** [comment]
/retest

LGTM

**Comment by TristanCacqueray** [comment]
It seems like this is causing trouble for graphical applications such as `glxgears` that used to work when running inside a podman container started with `--device /dri`. Is there an option to keep `/sys/dev` in the container?

**Comment by rhatdan** [comment]
@TristanCacqueray Please open an issue for this?  So that we can discuss it there.

**Pull request merged**
