### PR TITLE
[Never Merge] Verify parallel build race fix and new storage API

### PR DESCRIPTION
**Pull request by flouthoc**
### DO NOT MERGE

Verify `race condition` fix for parallel builds changes in deps.
Just to verify: https://github.com/containers/image/pull/1480/files & https://github.com/containers/storage/pull/1153

Fixes issue for following reproducer

### Reproducer
```console
#!/bin/bash
x=1
sudo ./podman rmi -af
rm -f log*.*
sudo ./podman build -t first . &> logfirst.log
while [ $x -le 30 ]
do
  echo "$x times"
  sudo ./podman build --log-level debug -t $x . &> log$x.log &
  x=$(( $x + 1 ))
#  sleep 1
done
```

### Dockerfile
```dockerfile
FROM quay.io/jitesoft/alpine
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Looks like happy tests @flouthoc !  For the final, it would be nice to add a test similar to the reproducer.

**Comment by flouthoc** [comment]
> Looks like happy tests @flouthoc ! For the final, it would be nice to add a test similar to the reproducer.

Thanks @TomSweeneyRedHat added a test for this as well.

**Comment by flouthoc** [comment]
@containers/storage-maintainers PTAL but following PR is just to verify not to merge

**Comment by vrothberg** [comment]
Once the c/storage PR is merged, we also need to open a PR against c/common and to migrate Tag/Untag.

**Comment by flouthoc** [comment]
@vrothberg Yes I agree. For `parallel build` issue we only need https://github.com/containers/image/pull/1480 and https://github.com/containers/storage/pull/1153 so should we drive this change slowly.

**Comment by vrothberg** [comment]
Since we know that `SetNames` is broken (and is soon deprecated), we should update all callers rather sooner than later.  It's easy to forget about things on the TODO list.

**Comment by vrothberg** [comment]
@flouthoc is this PR still needed

**Comment by flouthoc** [comment]
@vrothberg Nope. Thanks for reminding.

**Pull request closed without merging**
