### PR TITLE
machine start: qemu: adjust backoffs

### PR DESCRIPTION
**Pull request by vrothberg**
Make sure that starting a qemu machine uses proper exponential backoffs and that a single variable isn't shared across multiple backoffs.

DO NOT BACKPORT: I want to avoid backporting this PR to the upcoming 4.6 release as it increases the flakiness of machine start (see #17403). On my M2 machine, the flake rate seems to have increased with this change and I strongly suspect that additional/redundant sleep after waiting for the machine to be running and listening reduced the flakiness.  My hope is to have more predictable behavior and find the sources of the flakes soon.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@Luap99 @benoitf WDYT?

**Comment by benoitf** [comment]
yes I think all sleep() code is increasing flakiness so getting rid of them might fix the root cause (and having a way to get rid of them at a single place might help to find the root cause)

I want a fast start of a machine as well (so avoiding any unwanted/flaky wait is preferable)

**Comment by Luap99** [comment]
Good idea but if the goal here is to address the flake (which only happens for the ssh volume mount???) maybe I can redirect your attention to https://github.com/containers/podman/pull/16143. This should really just be managed by systemd so that a user can reboot from within the VM without problems.

**Comment by vrothberg** [comment]
> Good idea but if the goal here is to address the flake (which only happens for the ssh volume mount???) 

There is a number of issues including the flaky SSH.  I think it's still valuable to identify why it's failing sometimes.  It does not always fail on the first mount attempt.

> maybe I can redirect your attention to #16143. This should really just be managed by systemd so that a user can reboot from within the VM without problems.

Thanks for the reminder.  I agree, that would be a nice solution.

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by vrothberg** [comment]
@flouthoc @giuseppe merge me please :)

**Pull request merged**
