### PR TITLE
[CI:DOCS] Fix spacing in buildthedocs

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Further fixes: https://github.com/containers/podman/issues/10513

**Comment by rhatdan** [comment]
@saschagrunert @vrothberg @giuseppe @containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
CI claims : FAIL - has whitespace errors. See `git show --check 92789d2ae94b49ac7be40133ca632c2dbe53c70b`.

**Pull request merged**
