### PR TITLE
Refactor version handling in cmd tree

### PR DESCRIPTION
**Pull request by jwhonce**
* Move from simple string to semver objects
* Change client API Version from '1' to 2.0.0

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Code LGTM
But does this have an issue this is fixing?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by lsm5** [comment]
LGTM, this is gonna need some changes to my autobuilder, but no biggie.

**Comment by lsm5** [comment]
btw, would something like this be applicable to buildah and skopeo as well?

**Pull request merged**
