### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**
Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Restarted the flake.
LGTM, @containers/podman-maintainers PTAL

**Comment by TomSweeneyRedHat** [comment]
upgrade tests are unhappy, were those the flakes @vrothberg ?

**Comment by vrothberg** [comment]
> upgrade tests are unhappy, were those the flakes @vrothberg ?

No, initially the validate job flaked due to a CI infra hiccup.  CI gods do not shine upon this PR.  Restarted the next flakes.

**Comment by hswong3i** [comment]
@TomSweeneyRedHat force pushed, CI passed

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL and merge

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
