### PR TITLE
update remote_client.md, save people's life.

### PR DESCRIPTION
**Pull request by cnmade**
I feel sad, due to the id_rsa key auth hang me . i should make some changes. to save people's life.
waste me two hours to dig out what is the cause.

### CODE REVIEW

**Comment by cnmade** [comment]
I almost said : fuck you podman, but at last i found it is the problem of ssh key id_rsa, i fixed it . and i hope no other people feel angry with the same problem.

**Review by giuseppe — COMMENTED** [review]
The same hint is already present few lines above, not sure we need to clarify it again

**Comment by cnmade** [comment]
above is just said  is_rsa may got problem , I add these words to tips who get in trouble ,can try id_ed25519 again.

may solve the problem.

**Comment by cnmade** [comment]
`in some instances ...  will cause`   not a very strong signal, It may happen, but who knows. 
We can tell people. when they got in ssh auth trouble. they can try using id_ed25519 key again.

**Comment by giuseppe** [comment]
so can you please improve the previous sentence?

I don't think we need to document it twice.

**Comment by cnmade** [comment]
ok, fine for me , leave this issue tracks record. some body may search and know

**Pull request closed without merging**
