### PR TITLE
Spell "build linux darwin" as "build !windows".

### PR DESCRIPTION
**Pull request by coypoop**
Equivalent for supported platforms, and makes it easier to support
additional unix-like OSes.

### CODE REVIEW

**Review by Luap99 — CHANGES_REQUESTED** [review]
I don't think this will work correctly. The files in https://github.com/containers/podman/tree/main/pkg/machine/qemu get the build tags via file name. Since there are no build files for the other OSes this will not compile.

**Comment by coypoop** [comment]
Hi Luap99,
I am running podman-remote successfully on netbsd :)
```
$ ./bin/netbsd/podman run alpine ping -c 1 google.com
PING google.com (172.217.18.110): 56 data bytes
64 bytes from 172.217.18.110: seq=0 ttl=42 time=3.746 ms

--- google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 3.746/3.746/3.746 ms
```
This patch is the easiest to digest one of all the changes I needed.
The other changes require some more thought and maybe cleanup.
I hope it is harmless.

**Comment by Luap99** [comment]
Does `podman machine ls` work?

**Comment by coypoop** [comment]
yes, but only with the other patches included :)

**Comment by mheon** [comment]
Hm. All the cross-builds passed, so I think we're good to merge this - it doesn't break anything we're testing/using.

/approve

**Comment by Luap99** [comment]
I think it is great to enable this for other OSes but without any testing this will break easily. We only test the compile for linux, windows, macos.

**Comment by mheon** [comment]
I'd be OK with adding a note in the readme that Windows, OS X, and Linux are the only supported OSes, and while Podman may work elsewhere, it does not receive official testing on those architectures.

**Comment by mheon** [comment]
s/architectures/architectures and operating systems

**Review by Luap99 — COMMENTED** [review]
Is it intentional that you left `pkg/machine/libvirt/machine.go` the same?

**Comment by coypoop** [comment]
> Is it intentional that you left `pkg/machine/libvirt/machine.go` the same?

That might be dead code :-) I don't think anything else is importing it

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
