### PR TITLE
[CI:DOCS] markdown-preprocess: add generic include mechanism

### PR DESCRIPTION
**Pull request by edsantiago**
"It'll be easy", they said.

This is a two-commit PR: one of them simple and easy to review, the other one
completely bonkers. Please see individual commits. Seriously, you cannot review
this monster as one commit. And please see the warning about nroff. That needs
to be addressed before we can even think of merging this, so I'm marking Draft.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
generic md-include mechanism, to embed kubernetes_support.md into podman-kube-play man page
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Oh, yeah, the other thing:  have no idea if I inserted the `@@include` in the right place.

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks Ed!

We can improve on placement and wording in another PR.  I also imagine it at the end of the man page as done here.

**Comment by rhatdan** [comment]
I just ran this patch locally, and the man page looks pretty good on my gnome terminal.

LGTM

**Comment by rhatdan** [comment]
Less nice on xterm but not horrible.
Screenshot from 2022-10-14 09-11-17

**Comment by rhatdan** [comment]
Looks good on terminator as well.  Now I need to get out my VT100.  :^)

**Pull request merged**
