### PR TITLE
Add API support for NoOverwriteDirNonDir

### PR DESCRIPTION
**Pull request by jwhonce**
Update method signatures and structs to pass option to buildah code

```release-note
NONE
```

[NO NEW TESTS NEEDED]

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by vrothberg** [comment]
> #14420 suggests that we should add regression tests for this change.

Yup. It only blocks dirs from being replaced with a file but not the vice versa. I'll add tests when fixing https://github.com/containers/podman/issues/14420.

**Pull request merged**
