### PR TITLE
Bump to v4.0.0-RC5

### PR DESCRIPTION
**Pull request by mheon**
Also includes associated release notes updates and backports

### CODE REVIEW

**Comment by rhatdan** [comment]
We might want to hold this up untile @lsm5 Figures out https://github.com/containers/storage/pull/1131

**Comment by mheon** [comment]
API unit tests are failing, on a test that seems to validate that the current version is compatible with the API. This makes me think the bump to v4.0.0 as the minimum is conflicting with the v4.0.0-dev version set.

**Comment by mheon** [comment]
Specifically https://github.com/containers/podman/blob/29d7ab3f82e38c442e449739e218349b9a4a16ea/pkg/api/handlers/utils/handler_test.go#L14-L54 is failing - returning 400 not 200

**Comment by edsantiago** [comment]
Three failures in `int` tests, all of them remote. Unfortunately I can't figure out any elements common to the failures.

**Comment by mheon** [comment]
It's all manifest changes. I don't think I did any backports that would affect that code?

**Comment by mheon** [comment]
I'm going to restart just one of the tests, in the hopes that it was transitory; if that passes we're probably OK.

**Comment by mheon** [comment]
Nope, failures are consistent. OK...

**Comment by mheon** [comment]
I don't know how, but bumping minimum API version breaks the Libpod API manifest endpoints. I want to debug this, but it's Friday afternoon, so I'm going to vote that we release the RC now and debug later.

**Comment by mheon** [comment]
One flake (I hope...) - restarted

**Comment by mheon** [comment]
Another flake. Restarted.

**Comment by mheon** [comment]
Ready

**Pull request merged**
