### PR TITLE
rootless: fix hang when newidmap is not installed

### PR DESCRIPTION
**Pull request by giuseppe**
when newidmap is not installed the code would hit the
reexec_in_user_namespace_wait code and wait for the child process to
be terminated.  The child process is blocked waiting on the w pipe.

So make sure to unblock the child process first and then clean it up.

Closes: https://github.com/containers/podman/issues/7776

Signed-off-by: Giuseppe Scrivano <giuseppe@scrivano.org>

### CODE REVIEW

**Comment by mheon** [comment]
You have a lint error, otherwise LGTM

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
