### PR TITLE
podman-remote does not support most of the global flags

### PR DESCRIPTION
**Pull request by rhatdan**
podman-remote --help is showing a bunch of global flags that it
does not support

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago Your man page checker missed these global flags for podman-remote man page.

**Comment by edsantiago** [comment]
Man page checker does not test podman-remote.md. That may be a holdover from the varlink days; I'll take a look (tomorrow) and see what it'd take to enable.

**Comment by jwhonce** [comment]
@rhatdan Your fix is the correct method, you just need to filter through the sub-commands that are trying to now unnecessarily hide those flags.

**Review by vrothberg — COMMENTED** [review]
While we're at it, I think that the man pages should be updated as well. A comment indicating that these options are not supported on the remote client may be enough.

**Comment by rhatdan** [comment]
Podman remote man page does not refer to these options.
@vrothberg you want me to change the flags to say that each global option does not effect the remote server on the regular podman.1.md?

**Comment by vrothberg** [comment]
> Podman remote man page does not refer to these options.
> @vrothberg you want me to change the flags to say that each global option does not effect the remote server on the regular podman.1.md?

I didn't check `podman-remote`. I think we're good as the options are not mentioned there.

**Comment by edsantiago** [comment]
Update: without a completely different set of man pages, or at least a robust well-established convention for marking options/subcommands in man pages as remote-only, there's little hope for `hack/xref-helpmsgs-manpages` to check `podman-remote`. Even with a simple exclusion of `-l/--latest` I see 90 warnings, in both options (`run --authfile`, `rm -i`) and subcommands (`system migrate/renumber/reset`, `mount/umount/unshare`).

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by QiWang19** [comment]
LGTM

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Pull request merged**
