### PR TITLE
[CI:DOCS] Fix english on imported options

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by edsantiago — COMMENTED** [review]
Ugh. I really don't like that, but I won't block.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat WDYT?

**Comment by rhatdan** [comment]
How about commands? command man pages?

**Comment by TomSweeneyRedHat** [comment]
My first thought when I brought this up was "commands".  However, I prefer "command man pages".  @edsantiago does that work for you?

**Comment by edsantiago** [comment]
I still have a moderate preference for the wording as it is, because I like conciseness, but I'm staying out of this bike shed. I'll accept whatever y'all decide.

**Comment by rhatdan** [comment]
Since these are not exposed to users, I am going to close this PR.

**Pull request closed without merging**
