### PR TITLE
Fix flake on failed podman-remote build : try 2

### PR DESCRIPTION
**Pull request by rhatdan**
This time we are checking if the function actually succeeded,
otherwise we will report an error.

Also if we did not get the id, report unexpected failure.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Nice!  What I'm seeing now is:
```
Error: stream dropped, unexpected failure
```
instead of the `pull policy is "never"` one. The important factors, though, are (1) it exited nonzero (as it should), and (2) it seems to take a lot longer to fail: 202s, 182s, 48s

LGTM!

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
