### PR TITLE
test/e2e: check for stderr errors in cleanup()

### PR DESCRIPTION
**Pull request by Luap99**
Note I really do not expect this to pass, I only submit in order to gather some data and see if this shows us more bugs. In the long term something like this should be included. There are many code paths which only do logrus but still exit 0 so this should catch more bugs.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago WDYT? I don't expect this to work without further tweeks but I think this important to catch more bugs and flakes.

**Comment by edsantiago** [comment]
I really like it! I think it might be too soon to put this in production (I've tried before and it has been impossible), but maybe once unlinkat/EBUSY gets fixed we can push this, thank you!

**Comment by edsantiago** [comment]
Yow. Everything looks new. Since the hard failures seem consistent, I'm treating those as SEP, and am concentrating on looking at flakes only. The `open pidfd` one is nefarious, it has cropped up repeatedly since 2020 but never well enough to file an issue for. Here, I see it in [f37 root](https://api.cirrus-ci.com/v1/artifact/task/5506136472813568/html/int-podman-fedora-37-root-container-boltdb.log.html#t--podman-pod-container-can-override-pod-not-sharing-pid--1) and actually almost all the tests.  I will file an issue for it later. IPAM/ips is a new one, will look closer at it tonight. And, sigh, [unmount NS is back](https://api.cirrus-ci.com/v1/artifact/task/5154292751925248/html/int-podman-rawhide-rootless-host-sqlite.log.html#t--podman-container-start-single-container-by-id--1) - I had hoped those would be gone with the ginkgov2 `system reset` work.

**Comment by Luap99** [comment]
> And, sigh, [unmount NS is back](https://api.cirrus-ci.com/v1/artifact/task/5154292751925248/html/int-podman-rawhide-rootless-host-sqlite.log.html#t--podman-container-start-single-container-by-id--1)

It may be back but this a completely different failure, `no such file or directory` vs `invalid fs magic`. From the other error report there and all the other errors in these tests it is pretty safe to say that we are trying to Cleanup() twice.

**Comment by Luap99** [comment]
Ok, all last outstanding errors are like this:
```
           # podman [options] stop --all -t 0
           time="2023-06-13T10:17:45Z" level=warning msg="lstat /sys/fs/cgroup/devices/machine.slice/libpod-deb09b1224bf545821fb135679cd6d1ad2bbacd55415b32acb89f26b445ebe78.scope: no such file or directory"
           4e60fd09f05efc6ae524bd0a46e0f6494b09a45fd9ccd6e50e0ed28d2c7c9f12
           deb09b1224bf545821fb135679cd6d1ad2bbacd55415b32acb89f26b445ebe78
           # podman [options] pod rm -fa -t 0
           ca4099d1486c4a67d07d411bb0f7a7911fd53d2197829b1877c02b22212be2de
           # podman [options] rm -fa -t 0

           [FAILED] Failure recorded during attempt 1:
           stop --all -t0 error logged
           Expected
               <string>: time="2023-06-13T10:17:45Z" level=warning msg="lstat /sys/fs/cgroup/devices/machine.slice/libpod-deb09b1224bf545821fb135679cd6d1ad2bbacd55415b32acb89f26b445ebe78.scope: no such file or directory"
           to be empty
```
https://api.cirrus-ci.com/v1/artifact/task/6373332413579264/html/int-podman-debian-12-root-host-boltdb.log.html
(Note the links at the bottom are broken so you need to grep for `[FAILED] `)

Only debian but with root and rootless so could be something runc or cgroupv1 specific?
@giuseppe Could you take a look? Maybe we should ignore ENOENT?

**Comment by edsantiago** [comment]
Looks like #11784 which was closed ENOTHINGWECANDOABOUTIT

**Comment by Luap99** [comment]
> Looks like #11784 which was closed ENOTHINGWECANDOABOUTIT

Thanks, except this here is no flake. It is trivial to reproduce actually when using runc

```
$ sudo podman --runtime runc run -d --name test alpine top
23b74a32da9148ab003a57ea97b53a20e0539e4139fa49ad4171b0b9d11e9ec0
$ sudo podman --runtime runc run -d --pid container:test alpine top
ed3ebef0a4c988b3aedeef9633635002c6affabcb76581b4a9d7d5d527ab2a99
$ sudo podman stop --all
WARN[0000] freezer not supported: openat2 /sys/fs/cgroup/machine.slice/libpod-ed3ebef0a4c988b3aedeef9633635002c6affabcb76581b4a9d7d5d527ab2a99.scope/cgroup.freeze: no such file or directory 
WARN[0000] lstat /sys/fs/cgroup/machine.slice/libpod-ed3ebef0a4c988b3aedeef9633635002c6affabcb76581b4a9d7d5d527ab2a99.scope: no such file or directory 
23b74a32da9148ab003a57ea97b53a20e0539e4139fa49ad4171b0b9d11e9ec0
ed3ebef0a4c988b3aedeef9633635002c6affabcb76581b4a9d7d5d527ab2a99
```

**Comment by Luap99** [comment]
In fact you do not even need two containers just using `--pid host` will trigger this error alone.
```
$ sudo podman --runtime runc run -d --pid host alpine top
d57fe8041fe014d0e85dba2e1aa1e0b903599531ac2067f15528acb4ee3756b7
$ sudo podman stop --all
WARN[0000] freezer not supported: openat2 /sys/fs/cgroup/machine.slice/libpod-d57fe8041fe014d0e85dba2e1aa1e0b903599531ac2067f15528acb4ee3756b7.scope/cgroup.freeze: no such file or directory 
WARN[0000] lstat /sys/fs/cgroup/machine.slice/libpod-d57fe8041fe014d0e85dba2e1aa1e0b903599531ac2067f15528acb4ee3756b7.scope: no such file or directory 
d57fe8041fe014d0e85dba2e1aa1e0b903599531ac2067f15528acb4ee3756b7
```

**Comment by Luap99** [comment]
I tested with runc from the main branch and it seems to not emit these warnings anymore. So I guess the answer is wait a bit longer until this is released and packaged in debian.

**Comment by Luap99** [comment]
Note I ran the reproducers locally on cgroupv2 so it shouldn't matter for this specific warning I assume.
In any case this seems to be fixed upstream so I am fine with just waiting.

**Comment by edsantiago** [comment]
>I tested with runc from the main branch and it seems to not emit these warnings anymore. So I guess the answer is wait a bit longer until this is released and packaged in debian.

FWIW, here is debian-13 [root](https://api.cirrus-ci.com/v1/artifact/task/4755182127415296/html/int-podman-debian-13-root-host-sqlite.log.html) and [rootless](https://api.cirrus-ci.com/v1/artifact/task/4807958685548544/html/int-podman-debian-13-rootless-host-sqlite.log.html) showing that the problem still persists.

**Comment by rhatdan** [comment]
Can we close this or update it?

**Comment by edsantiago** [comment]
I'm totally fine with skipping warning checks on Debian. There is precedent, see #21191 

And needless to say I would LOVE to have this enabled wherever possible.

**Comment by edsantiago** [comment]
/lgtm

thank you!

**Pull request merged**
