### PR TITLE
abi: fix detection for systemd

### PR DESCRIPTION
**Pull request by giuseppe**
create a scope everytime we don't own the current cgroup and we are
running on systemd, regardless of the config manager specified.

Closes: https://github.com/containers/podman/issues/6734

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@baude @vrothberg @mheon @jwhonce @TomSweeneyRedHat @ashley-cui @QiWang19 PTAL

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
rebase on master >= 748e8829d to fix CI. I am sorry for the inconvenience.

**Comment by giuseppe** [comment]
rebased

**Pull request merged**
