### PR TITLE
upgrade all dependencies

### PR DESCRIPTION
**Pull request by Luap99**
The dependabot does not update dependencies when they do not use a tag.
This patch upgrades all untagged depenencies if possible.

You can upgrade all dependencies with `go get -u ./... && make vendor`
in theory however this failed since the k8s changes do not compile on
go v1.16 so I only updated the other dependencies.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
Cross-compile issue looks legit.

**Comment by Luap99** [comment]
The goterm issue is already tracked here: https://github.com/buger/goterm/issues/39 I will revert this to the last working version.

For the coreos stream-metadata-go library I created a new issue https://github.com/coreos/stream-metadata-go/issues/38

**Review by vrothberg — COMMENTED** [review]
/lgtm
/hold
Nice work, @Luap99 !

**Comment by baude** [comment]
LGTM , rebase required.

**Pull request merged**
