### PR TITLE
[v4.7] Vendor Buildah v1.32.2

### PR DESCRIPTION
**Pull request by mheon**
Update Buildah to v1.32.2

#### Does this PR introduce a user-facing change?

```release-note
Updated Buildah to v1.32.2
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
Single error is our expected aarch64 validate failure on this branch. I will force-merge if everything else passes.

**Review by flouthoc — APPROVED** [review]
LGTM

**Review by lsm5 — APPROVED** [review]
/lgtm

**Pull request merged**
