### PR TITLE
Remove unnecessary use of the word "please"

### PR DESCRIPTION
**Pull request by eriksjolund**
To make the language more efficient, only use the word "please" in these situations:

* reader is asked to do something inconvenient 
* reader is asked for permission
* reader is asked for forgiveness

If you think this modification is a good idea, I could put some more work into this PR and find some more edits to make.

References:
https://developers.google.com/style/word-list#letter-p
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/please

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
@TomSweeneyRedHat PTAL

Personally, I like the use of please :)

**Comment by Luap99** [comment]
Tom is out this week, lets wait for him to comment on this.

**Comment by rhatdan** [comment]
I like the changes
LGTM

**Comment by umohnani8** [comment]
changes LGTM

**Comment by TomSweeneyRedHat** [comment]
FWIW, neither variant is really incorrect, and it's more of a tone thing.  The way it is now, it is a bit more dry and business-like. The other way is a more friendly approach.  From a personal perspective/lean, I liked the pleases, but I wouldn't revert.

**Pull request merged**
