### PR TITLE
switch from "kube/play" endpoint to "play/kube" endpoint.

### LINKED ISSUE #15071: play kube: invalid character 'N' looking for beginning of value
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`play kube` error in latest HEAD

**Steps to reproduce the issue:**

```
cat <<EOF >manifest.yml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
EOF
```

1. `podman play kube ./manifest.yml`

**Describe the results you received:**

```
Error: ./manifest.yml: invalid character 'N' looking for beginning of value
```

**Additional information you deem important (e.g. issue happens only occasionally):**

On stable version (tested tag `v4.1.1`) I get this error instead: 

```
Error: ./manifest.yml: error playing YAML file: short-name resolution enforced but cannot prompt without a TTY
```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0-dev
API Version:  4.2.0-dev
Go Version:   go1.18.4
Git Commit:   a298909decc9091da8cc134e6eb2f38a70635a30
Built:        Tue Jul 26 12:08:11 2022
OS/Arch:      linux/amd64

Server:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 22 17:17:44 2022
OS/Arch:      linux/amd64
```

### PR DESCRIPTION
**Pull request by nicrowe00**
When podman kube play was added the endpoint for the kube play/play kube
commands was switched from the "play kube" endpoint to the new "kube play"
endpoint. This caused issues with the remote client, requiring the need
to use the "play kube" endpoint again in order to avoid these issues.
[NO NEW TESTS NEEDED]

Fixes #15071 
Signed-off-by: Niall Crowe <nicrowe@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Please change https://github.com/containers/podman/blob/main/test/apiv2/80-kube.at#L6 to exercise `kube/play` so the endpoint has some testing exposure.

Other than that, LGTM

Thanks!

**Comment by mheon** [comment]
/approve
Changes LGTM

**Comment by TomSweeneyRedHat** [comment]
Once @vrothberg 's comment has been addressed, LGTM

**Comment by vrothberg** [comment]
> Please change https://github.com/containers/podman/blob/main/test/apiv2/80-kube.at#L6 to exercise `kube/play` so the endpoint has some testing exposure.

Still open.  Once done, we can merge.

**Comment by nicrowe00** [comment]
The apiv2 test: https://github.com/containers/podman/blob/main/test/apiv2/80-kube.at#L6 already tests the kube/play endpoint as well as the play/kube endpoint so no change is necessary.

**Pull request merged**
