### PR TITLE
more shell completion improvements

### PR DESCRIPTION
**Pull request by Luap99**
* podman image ls --filter
* podman network ls --filter
* podman volume ls --filter
* podman network connect/disconnect
* podman events --filter

If we return `ShellCompDirectiveError` to the shell the shell will
provide path completion. In none of that cases we want path completion
so it will be better to return `ShellCompDirectiveNoFileComp` instead
and log the error in case we need it.

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago Another one :)

**Comment by Luap99** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
LGTM
/approve

**Pull request merged**
