### PR TITLE
rootfs-overlay: fix overlaybase path for cleanups

### PR DESCRIPTION
**Pull request by flouthoc**
Following commit ensures no dangling mounts are left behind when we are
creating an overlay on top of external rootfs and add test for the same to e2e.

Original patch submitted from @vrothberg here: https://github.com/containers/podman/pull/11170#issuecomment-945582221

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
The test looks a bit complex (and expensive).  Couldn't we add another run with `:O` to https://github.com/containers/podman/blob/main/test/system/030-run.bats#L620-L621?

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by flouthoc** [comment]
@giuseppe PTAL

**Comment by vrothberg** [comment]
That'll fix the restart issue.  The container wasn't marked as unmounted during cleanup, so Podman didn't attempt to remount on restart.

```diff
diff --git a/libpod/container_internal.go b/libpod/container_internal.go                                
index 2678ad496da9..901ddcf0a256 100644                                                                 
--- a/libpod/container_internal.go                                                                      
+++ b/libpod/container_internal.go                                                                      
@@ -1684,12 +1684,27 @@ func (c *Container) mountNamedVolume(v *ContainerNamedVolume, mountpoint string)
 func (c *Container) cleanupStorage() error {                                                           
        if !c.state.Mounted {                                                                           
                // Already unmounted, do nothing                                                        
+               markUnmounted()                                                                         
                logrus.Debugf("Container %s storage is already unmounted, skipping...", c.ID())         
                return nil                                                                              
        }                                                                                               
                                                                                                        
        var cleanupErr error                                                                            
                                                                                                        
+       markUnmounted := func() {                                                                       
+               c.state.Mountpoint = ""                                                                 
+               c.state.Mounted = false                                                                 
+                                                                                                       
+               if c.valid {                                                                            
+                       if err := c.save(); err != nil {                                                
+                               if cleanupErr != nil {                                                  
+                                       logrus.Errorf("Unmounting container %s: %v", c.ID(), cleanupErr)
+                               }                                                                       
+                               cleanupErr = err                                                        
+                       }                                                                               
+               }                                                                                       
+       }                                                                                               
+                                                                                                       
        // umount rootfs overlay if it was created                                                      
        if c.config.RootfsOverlay {                                                                     
                overlayBasePath := filepath.Dir(c.config.StaticDir)                                     
@@ -1717,6 +1732,7 @@ func (c *Container) cleanupStorage() error {                                      
        }                                                                                               
                                                                                                        
        if c.config.Rootfs != "" {                                                                      
+               markUnmounted()                                                                         
                return cleanupErr                                                                       
        }                                                                                               
                                                                                                        
@@ -1761,17 +1777,7 @@ func (c *Container) cleanupStorage() error {                                     
                }                                                                                       
        }                                                                                               
                                                                                                        
-       c.state.Mountpoint = ""                                                                         
-       c.state.Mounted = false                                                                         
-                                                                                                       
-       if c.valid {                                                                                    
-               if err := c.save(); err != nil {                                                        
-                       if cleanupErr != nil {                                                          
-                               logrus.Errorf("Unmounting container %s: %v", c.ID(), cleanupErr)        
-                       }                                                                               
-                       cleanupErr = err                                                                
-               }                                                                                       
-       }                                                                                               
+       markUnmounted()                                                                                 
        return cleanupErr                                                                               
 }                                                                                                      
```

**Comment by vrothberg** [comment]
The first call to `markUnmounted()` makes no sense ^

**Comment by vrothberg** [comment]
Test needs some massaging.  Since you're at it: could also remove the pod at the end?

**Pull request merged**
