### PR TITLE
[CI:DOCS] move footnotes on divisive language to exactly where divisive language is used

### PR DESCRIPTION
**Pull request by krumelmonster**
My commit is not signed or using a realname but I don't believe that the changes I've made can be subject to copyright.

I got a bit confused when reading the manpage as the footnote on problematic and divisive language appeared after a sentence that doesn't use problematic and divisive language and I think moving the footnote to just after the wording deemed problematic makes the manpage more readable

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
@krumelmonster good catch! Thank you for your PR.  How would you like to proceed with it? Our commit guidelines enforce the signing requirement. It looks like you're aware of that, but choose not to sign your commit.

**Comment by krumelmonster** [comment]
Sorry, I was unaware of these requirements until I opened the pr and I still don't fully understand them.
I chose to make a pr instead of an issue because with other projects I've had the experience that when the solution is clear, that prs are preferred.
I only wanted to suggest this change, I don't deem it copyrightable, anyone is invited to re-do the changes and sign it off themselves. Feel free to close the pr, I don't care

**Comment by edsantiago** [comment]
IIUC you do not wish to add a `Signed-off-by` with a name traceable to you. We respect your choice, and appreciate your understanding that we cannot accept your PR without a signature.

In the process of reviewing your contribution I discovered that some of our man pages are an unreadable mess. I am in the process of fixing those. If you wish to close this PR, I will incorporate your suggested changes into my upcoming PR.

Thank you again for finding these issues and for your efforts to fix them.

**Comment by krumelmonster** [comment]
Thank you

**Comment by krumelmonster** [comment]
Just for future reference: krumelmonster is a name "traceable" to me: Unlike with my passport name, you can [track](https://github.com/krumelmonster) [my](https://de.libreoffice.org/about-us/credits/) [contributions](https://aur.archlinux.org/packages/fileshelter) [to](https://codeberg.org/tectogen/tectogen) open source under the name krumelmonster. The Podman contribution guidelines currently require "no pseudonyms or anonymous contributions". I respect that. In the podman irc channel, it was mentioned to me that other projects, Linux and the CNCF, have clarified that pseudonyms do qualify as real names and therefore meet the requirement against anonymous contributions.

https://github.com/cncf/foundation/blob/659fd32c86dc/dco-guidelines.md
https://github.com/torvalds/linux/commit/d4563201f33a022fc0353033d9dfeb1606a88330

To me the wording in podmans Contribution guide sounds like a requirement for a passport name and that I don't use on the internet.

**Pull request closed without merging**
