### PR TITLE
[CI:DOCS] Release notes for 4.5.0 Part 1

### PR DESCRIPTION
**Pull request by ashley-cui**
As title says. 

```release-note
None
```

### CODE REVIEW

**Comment by ashley-cui** [comment]
@mheon FYI, feel free to either close this PR if it makes combining release notes easier, or you can push to this PR, or wait for this to merge and rebase on top of it. Any of these options work :)

**Comment by mheon** [comment]
I'm good to merge this as-is, I can just copy/paste my stuff in.

**Comment by mheon** [comment]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
