### PR TITLE
podman stats: fix race when ctr process exists

### LINKED ISSUE #23334: race: completion: cannot get cgroup path unless container is running
Another parallel-system-test flake, seen in [f39 root](https://api.cirrus-ci.com/v1/artifact/task/4568876212551680/html/sys-podman-fedora-39-root-host-boltdb.log.html):
```
<+036ms> # # podman pod stats --no-stream --format {{"\n"}}
<+198ms> # Error: cannot get cgroup path unless container e3c650c8438160f0c2728fc4ed589bc6c06546e6abfba38db49d5d15b9325310 is running: container is stopped
<+016ms> # [ rc=125 ]
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #|     FAIL: podman pod stats --format '{{"\n"}}'
         # #| expected: = ''
         # #|   actual:   Error: cannot get cgroup path unless container e3c650c8438160f0c2728fc4ed589bc6c06546e6abfba38db49d5d15b9325310 is running: container is stopped
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by Luap99**
stats read from the cgroup, and in order to know the cgroup we check the pid for the cgroup. However there is a window where the pid exited and podman did not yet updated its internal state. In this case the code returns ErrCtrStopped so we should ignore this error as well.

Fixes #23334

#### Does this PR introduce a user-facing change?

```release-note
Fixed a race in podman stats that could cause it to exit with a "container is stopped" error when showing all containers.
```

### CODE REVIEW

**Comment by Luap99** [comment]
cc @edsantiago

**Comment by edsantiago** [comment]
That was quick! Thank you! Cherrypicked onto #23275 and pushed. I need to leave home early, be out all day, so I will not be able to check its status.

**Comment by edsantiago** [comment]
Parallel tests passed. Well, mostly, but the failure is not related to these changes (I'm pretty sure). 

LGTM!

**Comment by edsantiago** [comment]
Whoops. [Failed on a rerun](https://api.cirrus-ci.com/v1/artifact/task/6616812081643520/html/sys-podman-fedora-40-rootless-host-sqlite.log.html)

**Pull request merged**
