### PR TITLE
containers.no_hosts is not considered by podman system service

### LINKED ISSUE #13719: containers.no_hosts is not considered by podman system service
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I use Jetbrains IntelliJ to connect to the Docker api. I don't have control on the way IntelliJ communicates with Docker.
All I can do is point IntelliJ to podman unix socket.

I want podman to behave like `Docker` regarding `/etc/hosts` entries management. `Docker` does not copy host `/etc/hosts` entries to the container `/etc/hosts`. I thought I would use https://docs.podman.io/en/latest/markdown/podman-run.1.html#no-hosts.

But `containers.no_hosts=true` is not considered when running containers via the REST api (works otherwise).

**Steps to reproduce the issue:**

1. Add the following to ~/.config/containers/containers.conf :

```
[containers]
no_hosts=true
```

2. Start a container via the REST api

**Describe the results you received:**

The container `/etc/hosts` contains entries coming from the host `/etc/hosts`.

**Describe the results you expected:**

I don't expect the host `/etc/hosts` entries to be copied to the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

Since podman does not exhibit the same behaviour as Docker, maybe there is also an additional bug about a wrong default to consider here.

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.6
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 16
  distribution:
    codename: focal
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: rhousni
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.0-37-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 39771643904
  memTotal: 67288952832
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 1023406080
  swapTotal: 1023406080
  uptime: 3h 43m 1.36s (Approximately 0.12 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/rhousni/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/rhousni/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 34
  runRoot: /run/user/1000/containers
  volumePath: /home/rhousni/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 100:3.4.2-1 amd64 [installed]
podman/unknown 100:3.4.2-1 arm64
podman/unknown 100:3.4.2-1 armhf
podman/unknown 100:3.4.2-1 s390
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fix #13719

Signed-off-by: Réda Housni Alaoui <reda-alaoui@hey.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
You will need to update tests.

**Comment by reda-alaoui** [comment]
I am not fluent in Go. Could you point me to them?
FYI, I wanted to add test calling directly the rest endpoint but didn’t find any example.

**Comment by rhatdan** [comment]
Most tests are under tests/
API Tests are in tests/apiv2

**Review by Luap99 — COMMENTED** [review]
This should be fixed somewhere in specgen and not in the libpod container config.

The import rule is that cli flag must always overwrite the config setting, with your change this does not work because --no-hosts=false no longer overwrites the config setting, see the failing tests.

**Comment by reda-alaoui** [comment]
@Luap99 could you point me to an architecture overview document? I don't understand what is `specgen` and how it interacts with `libpod`.

**Comment by reda-alaoui** [comment]
In the end, the real issue is https://github.com/containers/podman/issues/13748 . So giving up on this one.

**Pull request closed without merging**
