### PR TITLE
test updates to help debug #18041

### PR DESCRIPTION
**Pull request by vrothberg**
See individual commits for details.  Given the first DELETE didn't actually check if the pod was removed, we may get some better idea on the next flakes.

@edsantiago, that's the best thing I could come up with. PTAL

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by edsantiago** [comment]
/lgtm
/hold

Autotagbot added the "API change" label because the PR touches files under `pkg/something`. I don't believe this is an API change but someone else needs to independently confirm, then remove that label if so.

**Comment by vrothberg** [comment]
I think it got marked as an API change because code in the handler got changed.  The API itself remained untouched.

@Luap99 PTAL

**Pull request merged**
