### PR TITLE
Undo v2.0 branch hacks

### PR DESCRIPTION
**Pull request by mheon**
We committed several sins against CI in our quest to actually get v2.0.5 released. Fix them here by reverting CI to a fully-functional state and properly vendoring a new version of c/storage.

### CODE REVIEW

**Comment by mheon** [comment]
@rhatdan @baude @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by edsantiago** [comment]
Maybe I'm being dense but why don't you have to undo ae2ee65eff71c5780e4484f1316dbbdd87bf1760 (vendor/github.com/containers/storage/drivers/counter.go) ?

**Comment by rhatdan** [comment]
@edsantiago it should be in the updated containers/storage

**Comment by mheon** [comment]
@edsantiago We un-did the change to vendor/ we made, but then updated c/storage which included that change.

**Comment by edsantiago** [comment]
Of course, never mind, it's a NOP diff, that's why I wasn't seeing counter.go in the diffs. Sorry!

**Pull request merged**
