### PR TITLE
Fix podman build --logfile

### PR DESCRIPTION
**Pull request by rhatdan**
Currently this command blows up because it closes the file descriptor before
doing the build.

Add tests to make sure we don't regress.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1877188

**Comment by vrothberg** [comment]
> Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1877188

Can you add that to the commit message? It'll make backporting easier.

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
