### PR TITLE
vendor latest c/common

### PR DESCRIPTION
**Pull request by Luap99**
#### Does this PR introduce a user-facing change?

```release-note
Make podman tag/untag parallel race free (https://github.com/containers/podman/issues/17515)
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

Seems like I created https://github.com/containers/podman/pull/20447 at the very same time (minus the test/apiv2 change) :)

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
```
# get https://proxy.golang.org/golang.org/x/sys/@v/v0.0.0-20190916202348-b4ddaad3f8a3.zip: 200 OK (0.193s)
go: github.com/containernetworking/cni@v0.7.1: Get "https://proxy.golang.org/github.com/containernetworking/cni/@v/v0.7.1.mod": EOF
error: Bad exit status from /var/tmp/rpm-tmp.A7z8rl (%build)
    Bad exit status from /var/tmp/rpm-tmp.A7z8rl (%build)
```

on centos 8 and 9

**Comment by vrothberg** [comment]
Google's infrastructure in south east US is down ...

**Comment by vrothberg** [comment]
Restarted in hope the infra is back

**Comment by Luap99** [comment]
```
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #|     FAIL: NOTIFY_SOCKET is passed to container
         # #| expected: 'Pulling image localhost:42759/name:tag inside systemd: setting pull timeout to 5m0s'
         # #|   actual: 'Pulling image //localhost:42759/name:tag inside systemd: setting pull timeout to 5m0s'
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

@vrothberg Is it expected the the URL starts with `//`? It feels like the transport name is missing, I would expect at least `docker://` because just two slashes make no sense at all. Seems to be caused by https://github.com/containers/common/pull/1704.

**Comment by Luap99** [comment]
https://github.com/containers/image/blob/106139461bbcaef60ced9e479afb7553312aaab9/types/types.go#L52-L54

**Comment by ashley-cui** [comment]
lgtm

**Pull request merged**
