### PR TITLE
[v4.2.0-rhel] libpod: Remove 100msec delay during shutdown

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
When shutting down the image engine we always wait for the image even goroutine to finish writing any outstanding events. However, the loop for that always waits 100msec every iteration. This means that (depending on the phase) shutdown is always delayed up to 100msec.

This is delaying "podman run" extra much because podman is run twice (once for the run and once as cleanup via a conmon callback).

Changing the image loop to exit immediately when a libimageEventsShutdown (but first checking for any outstanding events to write) improves podman run times by about 100msec on average.

Note: We can't just block on the event loop reading the shutdown event anymore, we need to wait until it read and processed any outstanding events, so we now send the shutdown event and then block waiting for the channel to be closed by the event loop.

[NO NEW TESTS NEEDED]

Signed-off-by: Alexander Larsson <alexl@redhat.com>
Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Readying for a backport to RHEL 8.7.0ZeroDay and 9.1.0ZeroDay.  Initial BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2127347

**Comment by mheon** [comment]
LGTM once approval for backport drops.

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
/hold
We're not going to get this into RHEL 8.7 and 9.1 ZeroDay at this point, but will probably merge and backport this later there.

**Comment by TomSweeneyRedHat** [comment]
We'll target for 8.7.0.2 zstream and 9.1.0.2 zstream.  OK to merge anytime after October 31, 2022

**Comment by TomSweeneyRedHat** [comment]
This is good to merge now, can some one hit the shiny button please?

**Pull request merged**
