### PR TITLE
cp: consolidate and simplify

### PR DESCRIPTION
**Pull request by vrothberg**
Consolidate and simplify code in `podman cp` a bit.  PR #11049
introduced some code duplicates that were worth tackling.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM, Big improvement.

**Comment by infiniteregrets** [comment]
Thank you @vrothberg! Can you please update the manpage? I have made the changes, just add them to your commit if possible. If you want I can open a new PR to do that, but would be irrelevant I think. 
https://gist.github.com/infiniteregrets/9b75f48c50dc0d060cf4aaf67d29cd8c (updated page with manpage syntax)

**Comment by vrothberg** [comment]
> Thank you @vrothberg! Can you please update the manpage? I have made the changes, just add them to your commit if possible. If you want I can open a new PR to do that, but would be irrelevant I think.
> https://gist.github.com/infiniteregrets/9b75f48c50dc0d060cf4aaf67d29cd8c (updated page with manpage syntax)

I updated the man page already in #11049.  If you want more changes, please open a PR.

**Comment by vrothberg** [comment]
Green and ready to merge

**Pull request merged**
