### PR TITLE
fix system upgrade tests

### PR DESCRIPTION
**Pull request by Luap99**
Fix many FIXMEs in the upgrade tests. Also add a basic test for pods.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
Curious. Tests passed on my f34 laptop, but CI (also f34) is failing with: 
```
# podman --cgroup-manager=cgroupfs pod rm mypod
time="2021-05-10T12:01:34-05:00" \
   level=warning \
   msg="Error updating pod <SHA> \
        conmon cgroup PID limit: \
        open /sys/fs/cgroup/libpod_parent/<SHA>/conmon/pids.max: no such file or directory"
```

**Comment by edsantiago** [comment]
|       | Ed laptop (pass) | CI (fail) |
| --- | --- | --- |
| kernel | 5.11.**17**-300.fc34 | 5.11.**16**-300.fc34 |
| conmon | 2.0.27-2.fc34 | 2.0.27-2.fc34 (same) |
| crun | 0.19.1-2.fc34 | 0.19.1-2.fc34 (same) |

@giuseppe any idea what this might be? "pids.max" only appears in one place in podman sources, https://github.com/containers/podman/blob/5a8b3cf835742b3ba3bdc79010737ae3e2c69ce3/pkg/cgroups/pids.go#L31 , and that's almost two years old.

**Comment by edsantiago** [comment]
@Luap99 I'm going to recommend that you just disable the new `pod` tests, possibly with a FIXME comment that will be ignored for several months.

I cannot reproduce the failure on my f34 laptop (5.11.17-300.fc34). On a VM with 5.11.15-300.fc34, I can't reproduce it either, but I do get a different failure (not reliably):
```
# podman pod stop mypod
4dfb0157c41df6e834046dd660ab7b89c58f00dd6bd3b1ca1b8c2a97822b3264
# podman --cgroup-manager=cgroupfs pod rm mypod
Error: error removing pod 4dfb0157c41df6e834046dd660ab7b89c58f00dd6bd3b1ca1b8c2a97822b3264 conmon cgroup: remove /sys/fs/cgroup/libpod_parent/4dfb0157c41df6e834046dd660ab7b89c58f00dd6bd3b1ca1b8c2a97822b3264/conmon: remove /sys/fs/cgroup/libpod_parent/4dfb0157c41df6e834046dd660ab7b89c58f00dd6bd3b1ca1b8c2a97822b3264/conmon: device or resource busy
```
As nice as it would be to get pod coverage, I think your `start` fixes are important enough that they deserve merging this PR ASAP, even without the pod tests.

**Comment by giuseppe** [comment]
I think both issues are caused by some race conditions when the cgroup are cleaned up.

In the first case, the cgroup was already deleted (perhaps systemd?) and the `pids.max` file couldn't be found.  In the second case, it attempts to delete the cgroup while there are still processes or sub-cgroups

**Comment by Luap99** [comment]
Updated, I leave the pod test active and only changed to regex to not exactly match for an ID since it was only a logrus error and not a fatal one.

**Comment by edsantiago** [comment]
FWIW, the conmon one is an actual error:
```
# podman --cgroup-manager=cgroupfs pod rm mypod
time="2021-05-12T13:39:14-04:00" level=error msg="Error deleting pod 13248151dba98d371400269103c5ec50ead32feca98156a7fccd01f546b75ace cgroup /libpod_parent/1
3248151dba98d371400269103c5ec50ead32feca98156a7fccd01f546b75ace: remove /sys/fs/cgroup/libpod_parent/13248151dba98d371400269103c5ec50ead32feca98156a7fccd01f546b
75ace/conmon: remove /sys/fs/cgroup/libpod_parent/13248151dba98d371400269103c5ec50ead32feca98156a7fccd01f546b75ace/conmon: device or resource busy"
Error: error removing pod 13248151dba98d371400269103c5ec50ead32feca98156a7fccd01f546b75ace conmon cgroup: remove /sys/fs/cgroup/libpod_parent/13248151dba98d3
71400269103c5ec50ead32feca98156a7fccd01f546b75ace/conmon: remove /sys/fs/cgroup/libpod_parent/13248151dba98d371400269103c5ec50ead32feca98156a7fccd01f546b75ace/c
onmon: device or resource busy
[ rc=125 (** EXPECTED 0 **) ]
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#| FAIL: exit code is 125; expected 0
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I haven't seen that one in CI, though, only in a scratch VM.

**Comment by Luap99** [comment]
Oh, I see I would like to leave this test in for now. If it starts flaking we can disable it.

**Comment by edsantiago** [comment]
SGTM. That's why I didn't mark it as a requested change.

**Comment by TomSweeneyRedHat** [comment]
LGTM
I'll let @edsantiago push the shiny merge button.

**Comment by edsantiago** [comment]
/lgtm

Thank you, @Luap99!

**Pull request merged**
