### PR TITLE
[3.3] auto update: fix custom authfiles

### PR DESCRIPTION
**Pull request by vrothberg**
Vendor containers/common@v0.42.3 to pull in fixes for setting custom
authfiles during auto updates.

[NO TESTS NEEDED] must be tested manually.  The main branch will receive
a new system test shortly.

BZ: bugzilla.redhat.com/show_bug.cgi?id=2000943
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

@rhatdan @TomSweeneyRedHat PTAL

### CODE REVIEW

**Comment by vrothberg** [comment]
@cevich @edsantiago do you know what's going on in https://github.com/containers/podman/pull/11653/checks?check_run_id=3650980034? I don't understand _why/how_ there's a merge conflict.

**Comment by edsantiago** [comment]
Reproduces on my laptop. I wonder if this needs to be `v3.3.1-rhel` instead? 
https://github.com/containers/podman/blob/83052484a/.cirrus.yml#L9

**Comment by vrothberg** [comment]
Thanks for checking, Ed. Testing now.

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
