### PR TITLE
Backports and Release Notes for v2.0.3

### PR DESCRIPTION
**Pull request by mheon**
As the title says.

### CODE REVIEW

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL at release notes
@rhatdan @giuseppe @vrothberg @ashley-cui @QiWang19 PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
With the caveat that I read the Release Notes thoroughly and lightly skimmed the rest.

**Pull request merged**
