### PR TITLE
compose: fix compose provider debug message

### PR DESCRIPTION
**Pull request by xduugu**
[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@xduugu thanks for the PR.  You need to add a `[NO NEW TESTS NEEDED]` tag to the description of this PR to get by CI, or create a new test.

Otherwise LGTM

**Comment by xduugu** [comment]
@TomSweeneyRedHat Thanks, I missed that part!

**Comment by rhatdan** [comment]
Now you need to repush your changes.

git commit -a --amend -s
git push --force

**Comment by xduugu** [comment]
Ah, sorry. I thought it works the same as `[CI:DOCS]`.

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

**Comment by mheon** [comment]
/hold cancel
LGTM for the record

**Pull request merged**
