### PR TITLE
Add support for env from secrets in play kube

### PR DESCRIPTION
**Pull request by AlbanBedel**
This serie add support for the `env.valueFrom.secretKeyRef` and `envFrom.secretRef` elements in play kube. While at it I noticed that podman treat env references as optional, but K8S treat them as mandatory unless the `optional` parameter if set true. So this serie also add support for the `optional` parameter in configMapRef and fix the behavior when it is not present to match K8S.

Note that K8S secrets are dictionaries of binary data, so the value stored in the secret must be a JSON object that contain values in base64 encoding. This match the data type of the `data` field in a K8S secret object.

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @AlbanBedel 
Tests do not look happy.
@ashley-cui @umohnani8 @haircommander PTAL

**Review by ashley-cui — COMMENTED** [review]
LGTM, thanks @AlbanBedel!

**Comment by haircommander** [comment]
LGTM!

**Pull request merged**
