### PR TITLE
Fix containers list/prune http api filter behaviour

### PR DESCRIPTION
**Pull request by jmguzik**
The problem described in #9711 and followed by #9758 affects
containers as well. When user provides wrong filter input, error
message should occur, not fallback to full list/prune command.
This change fixes the issue. Additionally, there are error message
fixes for docker http api compat.

Signed-off-by: Jakub Guzik <jakubmguzik@gmail.com>

### CODE REVIEW

**Comment by zhangguanzhang** [comment]
also need update the doc. otherwise LGTM

**Comment by jmguzik** [comment]
> also need update the doc. otherwise LGTM

Three is no functional change, just fix of the not working functionality. Which docs i need to update in that case?

**Comment by jwhonce** [comment]
LGTM

**Review by Luap99 — APPROVED** [review]

**Pull request merged**
