### PR TITLE
vendor in latests containers/common

### PR DESCRIPTION
**Pull request by BlackHole1**
To include export HostContainersInternal

Ref:
1. https://github.com/containers/common/pull/1516
2. https://github.com/containers/podman/pull/18936

#### Does this PR introduce a user-facing change?

```release-note
None
```

/cc @Luap99

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Can you add a commit on top that uses HostContainersInternal?

**Comment by BlackHole1** [comment]
Hey @vrothberg 👋. I think the PR should be kept clean. This PR is only responsible for updating the `common vendor`. After this PR is merged, I will submit another PR to update `HostContainersInternal` 😀.

**Comment by vrothberg** [comment]
> Hey @vrothberg wave. I think the PR should be kept clean. This PR is only responsible for updating the `common vendor`. After this PR is merged, I will submit another PR to update `HostContainersInternal` grinning.

I leave it up to you.  I prefer to combine such changes. Less time to review and less stress on CI.

LGTM

**Review by Luap99 — APPROVED** [review]
LGTM

**Pull request merged**
