### PR TITLE
api: Add check of nil tuples

### PR DESCRIPTION
**Pull request by mi4r**
add NULL checkings of host and url

Found by Linux Verification Center (linuxtesting.org) with SVACE.

#### Does this PR introduce a user-facing change?

```release-note
   None
```

### CODE REVIEW

**Review by lsm5 — APPROVED** [review]
LGTM

@containers/podman-maintainers PTAL

**Review by Luap99 — CHANGES_REQUESTED** [review]
url and host cannot ever be nil here, it would only be nil if the flags are not defined which should never be the case.
And if for some reason it does happen I rather have it panic here so I know what happened instead of silently ignoring the case which leads to much harder to debug issues.

So I don't see how this check helps us here.

**Comment by mi4r** [comment]
> url and host cannot ever be nil here, it would only be nil if the flags are not defined which should never be the case. And if for some reason it does happen I rather have it panic here so I know what happened instead of silently ignoring the case which leads to much harder to debug issues.
> 
> So I don't see how this check helps us here.

And getting into the default case, where we return an error, can this be called ignoring this error?

**Comment by mi4r** [comment]
Just panicking is also bad, it’s better to avoid it.

**Comment by Luap99** [comment]
> > url and host cannot ever be nil here, it would only be nil if the flags are not defined which should never be the case. And if for some reason it does happen I rather have it panic here so I know what happened instead of silently ignoring the case which leads to much harder to debug issues.
> > So I don't see how this check helps us here.
> 
> And getting into the default case, where we return an error, can this be called ignoring this error? Just panicking is also bad, it’s better to avoid it.

Yes because the default case may not return an error so we completely ignore this error condition. Neither of them can ever be nil as long as both flags are defined, and they are. If they for whatever reason at one point are ever not defined I prefer a panic as this is something that should never happen and with a panic is caught immediately in all our CI runs basically. Sure you could convert the nil check to return error but why bother when it cannot happen in the first place.

**Comment by mtrmac** [comment]
It would be interesting to restructure the CLI so that the flags don’t need to be looked up by a string … [and, uh, to use a language which has optionals and non-`nil` as a property of the type system].

Skopeo uses `c/common/pkg/flag.OptionalString` for similar things, e.g. https://github.com/containers/skopeo/blob/be26f2eb2fcab244cd655bbe413e185513f6ece2/cmd/skopeo/sync.go#L47 ; the flag names only exist at the very top of the CLI definition, all other code sees fields in structs.

Clearly converting the existing CLI layer would be an enormous amount of work that’s not going to happen short term — I’m just mentioning it here to advocate for that kind of a design for the future.

**Comment by mi4r** [comment]
Ok, thus I just close this PR

**Comment by mi4r** [comment]
Ok, thus I just close this PR

**Pull request closed without merging**
