### PR TITLE
add additional fields to podman machine ls --json

### PR DESCRIPTION
**Pull request by rhatdan**
[NO NEW TESTS NEEDED]

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by jwhonce** [comment]
LGTM, once tests are happy

**Comment by TomSweeneyRedHat** [comment]
LGTM
tests are unhappy with `buildah bud`, @edsantiago is this a known issue atm?  I saw the same error in another PR and thought it wasn't a flake, may have to change my thinking on the flakiness...

**Comment by edsantiago** [comment]
Rebase needed to fix buildah-bud tests; see #12818 for details.

**Comment by rhatdan** [comment]
Merging rather then rebasing since we know what the failures are.

**Pull request merged**
