### PR TITLE
[CI:DOCS] Fix man page display of podman-kube-generate

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@adelton PTAL
@TomSweeneyRedHat PTAL

**Review by Luap99 — APPROVED** [review]
LGTM

**Review by lsm5 — APPROVED** [review]
/lgtm
/hold

**Comment by TomSweeneyRedHat** [comment]
late to the review party, but nice catch/fix.  Thanks @rhatdan !

**Comment by rhatdan** [comment]
@adelton actually found the first one of these.

**Pull request merged**
