### PR TITLE
System tests: Usage checks: better error messages

### PR DESCRIPTION
**Pull request by edsantiago**
Current error messages are really awful, and cause great
suffering every time someone adds a new subcommand. Let's
see if these are better.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Three examples, obtained by instrumenting existing code:
```
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: '  podman container inspect [options]' indicates that the command takes no arguments. I invoked it with 'invalid-arg' and expected the following error message
#| expected: 'Error: .* takes no arguments' (using expr)
#|   actual: '[]'
#|         > 'Error: inspecting object: no such container invalid-arg'
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: '  podman container inspect [options] [CONTAINER]' indicates a maximum of 1 args. I invoked it with more, and expected one of these error messages
#| expected: 'Error:.* \(takes no arguments\|requires exactly 1 arg\|accepts at most\|too many arguments\|accepts 1 arg(s), received\|accepts between .* and .* arg(s), received \)' (using expr)
#|   actual: '[]'
#|         > 'error inspecting object: no such container x1'
#|         > 'Error: inspecting object: no such container x0'
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: '  podman container list [options] CONTAINER' indicates at least one required arg. I invoked it with no args and expected an error exit code
#| expected: '125'
#|   actual: '0'
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I think the biggest help is showing the actual `Usage` message.

**Comment by rhatdan** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/hold

**Pull request merged**
