### PR TITLE
[CI:DOCS] socket_activation.md: remove conmon from socket inheritance

### PR DESCRIPTION
**Pull request by eriksjolund**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by eriksjolund** [comment]
I'm pretty sure that the `conmon` process should be removed from the graph that describes how the socket is inherited from process to process. (The socket does not seem to be inherited via conmon).

What do you think?

**Comment by Luap99** [comment]
Conmon is executing the oci runtime to create the container. So the order is systemd->podman->conmon->oci runtime-> container process. I think the current version is correct.

**Comment by eriksjolund** [comment]
If conmon is the parent of crun, shouldn't the text output

```
podman --runtime /home/test/crun.bash run -q docker.io/library/alpine /bin/true 
```

in the following example have been different?

```
$ emacs ~/crun.bash
$ cat ~/crun.bash
#!/bin/bash
echo started crun.bash
cat /proc/$PPID/cmdline | tr '\0' ' '
echo
exec crun "$@"
$ chmod 755 ~/crun.bash
$ podman --runtime ~/crun.bash run -q docker.io/library/alpine /bin/true
started crun.bash
podman --runtime /home/test/crun.bash run -q docker.io/library/alpine /bin/true 
$ 
```

**Comment by eriksjolund** [comment]
@Luap99  You're right. Thanks for explaining!

**Pull request closed without merging**
