### PR TITLE
Fixes #11728 Remove gvproxy listen argument

### LINKED ISSUE #11728: Adjustable machine proxy port
Maybe this can be adjustable? In my env, I have already an daemon service listen on 7777, so there will be error

https://github.com/containers/podman/blob/1dba601b56551b301490b36b198477ee0a58d137/pkg/machine/qemu/machine.go#L646

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

#### What this PR does / why we need it:

#11728

#### Which issue(s) this PR fixes:

Fixes #11728

*** Please also put 'Fixes #' in the commit and PR description***

-->

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @gliptak 
Could you add a little more information to your commit to explain that this is no longer needed.  Also add
[NO NEW TEST NEEDED] to make the tests happy.
LGTM

**Comment by gliptak** [comment]
@rhatdan thank you for the pointers. How would an "integration" test look to cover this?

**Review by Luap99 — CHANGES_REQUESTED** [review]
We cannot change this until we also changed the podman-machine-cni plugin do use the new address.

**Comment by Luap99** [comment]
It does not make sense to change this in the podman-machine-cni repo because I plan to move the code into podman to fix a variety of issues.
Hopefully I get this done this week.

**Comment by Luap99** [comment]
Replaced by #12283

**Pull request closed without merging**
