### PR TITLE
[v3.4] backport Flake fixes

### PR DESCRIPTION
**Pull request by edsantiago**
Backport #12323 and #12297 [EDIT: and #12343] to fix bodhi gating-test failures

### CODE REVIEW

**Comment by edsantiago** [comment]
@lsm5 FYI

**Comment by mheon** [comment]
@edsantiago Are these RHEL relevant? Because we swapped RHEL builds over to v3.4.2-rhel (or at least, we should have)

**Comment by edsantiago** [comment]
I'm pretty sure that at least some of them would affect RHEL gating tests. I now have it on my TODO list to check. Thanks for the heads-up.

**Comment by edsantiago** [comment]
Addressed in #12399

**Pull request merged**
