### PR TITLE
test/system: fix pasta host.containers.internal test

### LINKED ISSUE #23227: Test "pasta/bridge and host.containers.internal" can spuriously fail on system with 1 IPv4 + 1 IPv6 address
### Issue Description

@Luap99, filing this issue as discussed in yesterday's pasta call.

When I run the tests in `test/system/505-networking-pasta.bats` I get a failure if my host is in a state where it has exactly one publically routable IPv4 address and exactly one publically routable IPv6 address.

### Steps to reproduce the issue

These steps use a namespace to create an isolated environment with the triggering configuration.  In order to allow podman to run within the environment we assume that the testing user, `user`, has an entry in `/etc/subuid` like `user:$SUBUID:$N` and in `/etc/subgid` like `user:$SUBGID:$M`.  It assumes cwd is the base of the podman source tree.

Steps to reproduce the issue:
1. Change directory to the base of a podman source tree
2. Create an isolated namespace:
```unshare -Unc --map-users=$SUBUID:$SUBUID:$N --map-groups=$SUBGID:$SUBGID:$M --keep-caps```
3. In the shell started by `unshare` run the following to create a suitable network setup:
```
$ ip link set lo up
$ ip link add type dummy
$ ip link set dummy0 up
$ ip addr add 192.0.2.1/24 dev dummy0
$ ip addr add 2001:db8::1111/64 dev dummy0
$ ip route add default via 192.0.2.2 dev dummy0
$ ip -6 route add default via 2001:db8::2222 dev dummy0
```
4. Still in the unshare shell, execute the problem test:
```$ bats -f host.containers.internal 505-networking-pasta.bats```

### Describe the results you received

```
$ bats -f host.containers.internal 505-networking-pasta.bats 
505-networking-pasta.bats
 ✗ [505] pasta/bridge and host.containers.internal
   (from function `bail-now' in file helpers.bash, line 184,
    from function `assert' in file helpers.bash, line 1000,
    in test file 505-networking-pasta.bats, line 815)
     `assert "$pasta_ip" == "$(hostname -I | tr -d '[:space:]')" "pasta ip must the only one one the host ($network)"' failed
   
   [11:26:10.517272244] $ podman info --format {{.Host.Pasta.Executable}}
   [11:26:10.651263156] /bin/pasta
   
   [11:26:10.672650553] $ podman run --rm --network=pasta quay.io/libpod/testimage:20240123 grep host.containers.internal /etc/hosts
   [11:26:10.944547840] [ rc=1 ]
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: pasta ip must the only one one the host (pasta)
   #| expected: 192.0.2.12001:db8::1111
   #|   actual: 192.0.2.1
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   # [teardown]
   
   [11:26:10.961868351] $ podman pod rm -t 0 --all --force --ignore
   
   [11:26:11.016541053] $ podman rm -t 0 --all --force --ignore
   
   [11:26:11.064244818] $ podman network prune --force
   
   [11:26:11.117363427] $ podman volume rm -a -f
   
   [11:26:11.178819205] $ podman ps --all --external --format {{.ID}} {{.Names}}
   
   [11:26:11.234352468] $ podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   [11:26:11.279688201] quay.io/libpod/testimage:20240123 1f6acd4c4a1d

1 test, 1 failure
```

### Describe the results you expected

The selected test `pasta/bridge and host.containers.internal` passes.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.36.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 97.1
    systemPercent: 1.26
    userPercent: 1.64
  cpus: 20
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    version: "40"
  eventLogger: journald
  freeLocks: 2048
  hostname: zatzit
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.9.7-200.fc40.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 30118445056
  memTotal: 67100430336
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.11.0-1.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.11.0
    package: netavark-1.11.0-1.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.11.0
  ociRuntime:
    name: crun
    package: crun-1.15-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.15
      commit: e6eacaf4034e84185fd8780ac9262bbf57082278
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /bin/pasta
    package: passt-0^20240624.g1ee2eca-1.fc40.x86_64
    version: |
      pasta 0^20240624.g1ee2eca-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 119h 6m 28.00s (Approximately 4.96 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/dwg/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/dwg/.local/share/containers/storage
  graphRootAllocated: 1006801780736
  graphRootUsed: 198175649792
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/dwg/.local/share/containers/storage/volumes
version:
  APIVersion: 5.1.1
  Built: 1717459200
  BuiltTime: Tue Jun  4 10:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.3
  Os: linux
  OsArch: linux/amd64
  Version: 5.1.1
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Host is a Fedora 40 system with `podman-5.1.1-1.fc40.x86_64` and `passt-0^20240624.g1ee2eca-1.fc40.x86_64`.  Running in a podman upstream source tree, commit `v5.0.0-rc6-891-gabf0350529`.

### Additional information

The test in question has two cases: in case one the host has > 1 (IPv4) address, in which case pasta uses one for itself and `host.containers.internal` within the container is assigned to another one.  This case is fine.

The other case is where the host has just 1 IPv4 address, which is needed by pasta, so `host.containers.internal` cannot be assigned.  Here we attempt to check that the IP chosen by pasta is the same as the one on the host.  However, we only consider IPv4 for the expected pasta IP, but use `hostname -I` to get the host's IP, which will list both IPv4 and IPv6 addresses.

### PR DESCRIPTION
**Pull request by Luap99**
When a system has one ipv4 and one ipv6 address hostname -I will show both causing a failure in the case where this is only one address. To fix this stop using hostname -I and use ip -4 to only list v4 addresses and the use jq to filter the output accordingly.

Fixes #23227

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@dgibson PTAL

**Comment by dgibson** [comment]
@Luap99, this seems to fix the problem for me, thanks.

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
