### PR TITLE
Fix machine test

### PR DESCRIPTION
**Pull request by ashley-cui**
DownloadVMImage takes an extra argument.

Signed-off-by: Ashley Cui <acui@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by ashley-cui** [comment]
@containers/podman-maintainers PTAL asap, this fixes broken machine CI on main.

**Review by cdoern — APPROVED** [review]
LGTM

**Review by flouthoc — APPROVED** [review]
/lgtm
/hold

**Comment by Luap99** [comment]
LGTM, we should really enable linters for the tests: https://github.com/containers/podman/issues/14996

**Pull request merged**
