### PR TITLE
podman-play-kube template: rename to podman-kube

### PR DESCRIPTION
**Pull request by vrothberg**
With the upcoming plans of introducing a podman-kube command with
various subcommands, rename the podman-play-kube systemd template
to podman-kube before releasing it.

Also mention it in the docs.  No release notes needed as the template has
already been covered by the commit it was introduced with.

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @baude PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
@Luap99 @flouthoc @giuseppe PTAL

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
