### PR TITLE
[minor] fix duplicate test name

### PR DESCRIPTION
**Pull request by edsantiago**
copy/paste error in #14501.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Review by cdoern — APPROVED** [review]
LGTM, sorry for this one

**Comment by edsantiago** [comment]
Oh, no worries - we've all done it. It's just that with copy/paste, you paste and have to change this-and-that, and sometimes miss one of the things that need to be changed. That's why my encouragement to re-review.

**Pull request merged**
