### PR TITLE
[CI:DOCS]: update the podman logo

### PR DESCRIPTION
**Pull request by unknowndevQwQ**
for podman/#15222

Signed-off-by: unknowndevQwQ <unknowndevQwQ@pm.me>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
/approve
@TomSweeneyRedHat PTAL

**Comment by vrothberg** [comment]
They look like two different "flavors" of the logo.  I am not sure we need to replace it but I may be wrong.

**Comment by TomSweeneyRedHat** [comment]
I think the one in common was aimed toward the desktop.  I'd prefer not to change the one here in GitHub, but I will let  @mairin make the decision as she is the SME in this arena by many leaps and bounds beyond me.

**Comment by mairin** [comment]
Thanks @TomSweeneyRedHat  - this is the correct logo :) The one that this is replacing was an early version. This is a great version to use so +1 from me!

**Pull request merged**
