### PR TITLE
Fix typo in storage.conf file exists message

### PR DESCRIPTION
**Pull request by emsoucy**

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Thanks for contributing!

In order to pass CI, the commit message needs two more things:
1) The commit must be signed via `git commit -s --amend`.
2) The commit message must contain the magic string `[NO TESTS NEEDED]`. The CI is enforcing adding new tests, so commits need to explicitly opt-out from that.

Other than that, LGTM

**Comment by rhatdan** [comment]
Could you rebase and squash your ocmmits.

git rebase -i origin 
git push --force

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests
Thx @emsoucy !

**Comment by rhatdan** [comment]
LGTM
Doing a force merge to save the planet.

**Pull request merged**
