### PR TITLE
[NO TESTS NEEDED] Replace Labels and Options nulls with {} in NetworkResource

### LINKED ISSUE #9466: DOCKER Compatibility bug: http://localhost/networks/[network id] returns null for Options instead of {}
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When doing `curl -XGET --unix-socket /run/podman/podman.sock -H 'Content-Type: application/json' http://localhost/networks/[network name]` the Options field returns `null` instead of `{}`.

Docker returns `{}`. 

This currently breaks the ansible docker_container module if a network is set in there as it doesnt support null here.

**Steps to reproduce the issue:**

1. Create a network

2. Run `curl -XGET --unix-socket /run/podman/podman.sock -H 'Content-Type: application/json' http://localhost/networks/[network name]` where `[network name]` gets replaced with the name of the above created network.

**Describe the results you received:**

The `Options` field is of value `null`

**Describe the results you expected:**

In Docker this field is `{}` instead of `null`

**Output of `podman version`:**

```
➜  dev git:(main) podman version
Version:      3.0.0
API Version:  3.0.0
Go Version:   go1.15.8
Git Commit:   5b2585f5e91ca148f068cefa647c23f8b1ade622
Built:        Thu Feb 11 23:22:46 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
➜  dev git:(main) podman info --debug
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.26-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 0e155c83aa739ef0a0540ec9f9d265f57f68038b'
  cpus: 16
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: arch-marcel
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65537
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65537
  kernel: 5.10.15-arch1-1
  linkmode: dynamic
  memFree: 7309766656
  memTotal: 33583820800
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 0.17-1
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.8-1
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 47h 7m 38.2s (Approximately 1.96 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.redhat.io
store:
  configFile: /home/marcel/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: /usr/bin/fuse-overlayfs is owned by fuse-overlayfs 1.4.0-1
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /home/marcel/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 7
  runRoot: /run/user/1000/containers
  volumePath: /home/marcel/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613082166
  BuiltTime: Thu Feb 11 23:22:46 2021
  GitCommit: 5b2585f5e91ca148f068cefa647c23f8b1ade622
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.0.0
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This was discovered due to ansible failing but is reproducible outside of ansible as that just accesses the socket api.

### PR DESCRIPTION
**Pull request by jmguzik**
Fixes #9466 
Closes #9466

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by jmguzik** [comment]
We do not test this?

**Comment by jmguzik** [comment]
I added no tests needed just to spin ci.
Let me know if tests are needed and if yes - on which level.

**Pull request merged**
