### PR TITLE
Fix remote logs

### PR DESCRIPTION
**Pull request by ashley-cui**
Docker compatibility  - logs endpoint does not write stream headers if container has a tty

There are still some issues with logging behavior that affects this, we need to sort that out in the backend before we can know for certain if this is the right fix

Fixes: https://github.com/containers/podman/issues/7196

Signed-off-by: Ashley Cui <acui@redhat.com>

### CODE REVIEW

**Comment by ashley-cui** [comment]
@vrothberg tagging so you have the link to this PR, thanks for helping me on this

**Comment by ashley-cui** [comment]
Update: this should fix remote logs the best we can: adding a tty to a container makes the logs add return carriage symbols, which is a tty quirk, so this should be an accpetable fix. See: https://github.com/moby/moby/issues/37366#issuecomment-401157643

**Comment by rhatdan** [comment]
LGTM
@mheon @jwhonce @baude PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM but I want a head not from @baude and/or @jwhonce

**Pull request merged**
