### PR TITLE
Add podman system events alias to podman events

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
podman system events now alias to podman events for Docker compatibility
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
Please add the changelog to the commit message as well.

**Comment by rhatdan** [comment]
@edsantiago PTAL, I could not figure out how to get hack/xref-helpmsgs-manpages to recognize that there was a links file for the podman-system-events man page
podman-system-events->podman-events
For some reason this works with 
podman-system-info->podman-info

**Comment by edsantiago** [comment]
```diff
diff --git a/docs/source/markdown/podman-system.1.md b/docs/source/markdown/podman-system.1.md
index c41124510..12b77f5b8 100644
--- a/docs/source/markdown/podman-system.1.md
+++ b/docs/source/markdown/podman-system.1.md
@@ -15,7 +15,7 @@ The system command allows you to manage the podman systems
 | -------    | ------------------------------------------------------------ | ------------------------------------------------------------------------ |
 | connection | [podman-system-connection(1)](podman-system-connection.1.md) | Manage the destination(s) for Podman service(s)                          |
 | df         | [podman-system-df(1)](podman-system-df.1.md)                 | Show podman disk usage.                                                  |
-| events     | [podman-system-events(1)](podman-system-events.1.md)         | Monitor Podman events                                                       |
+| events     | [podman-system-events(1)](podman-events.1.md)                | Monitor Podman events                                                    |
 | info       | [podman-system-info(1)](podman-info.1.md)                    | Displays Podman related system information.                              |
 | migrate    | [podman-system-migrate(1)](podman-system-migrate.1.md)       | Migrate existing containers to a new podman version.                     |
 | prune      | [podman-system-prune(1)](podman-system-prune.1.md)           | Remove all unused pods, containers, images, networks, and volume data.   |
```

**Comment by rhatdan** [comment]
Thanks @edsantiago I love it when it is right in front of your face.

**Review by Luap99 — COMMENTED** [review]
You need to change `eventsCommand` to `cmd` in the new eventsFlags function, otherwise tab completion will not work.

**Review by Luap99 — COMMENTED** [review]
/lgtm
/hold

**Comment by Luap99** [comment]
Looks like the format test is failing, I think you need to add this:
```diff
$ git diff
diff --git a/test/system/610-format.bats b/test/system/610-format.bats
index 8f74634d1..3ee95bdff 100644
--- a/test/system/610-format.bats
+++ b/test/system/610-format.bats
@@ -37,6 +37,7 @@ search            | $IMAGE
 pod inspect       | mypod
 
 events            | --stream=false --events-backend=file
+system events     | --stream=false --events-backend=file
 "
 
 # podman machine is finicky. Assume we can't run it, but see below for more.
```

**Pull request merged**
