### PR TITLE
vendor in containers/(common,buildah,storage)

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago PTAL

**Comment by edsantiago** [comment]
eep. Is there something in particular you'd like me to look at? The only thing that springs to mind is that if we're truly done with go 1.16, maybe this line can be removed:
https://github.com/containers/podman/blob/181c9d3ee3ad4820b9ae91f1f02faf7b9e65fc87/go.mod#L78

**Comment by edsantiago** [comment]
Oh..... I get it now. I was looking for buildah test changes that would cause the `bud` test to fail -- having forgotten that the `tests` dir is not vendored.

OK. Buildah bud tests are going to fail, and fail early (in the patching stage). I would be most grateful if you would, in your checked-out directory for this branch, run:
```
$ hack/buildah-vendor-treadmill --pick
```
...and post the log here, whether it works or not (if it fails, so I can debug it; if it works, for posterity). Thank you!

**Comment by rhatdan** [comment]
Can't locate open.pm in @INC (you may need to install the open module) (@INC contains: /usr/local/lib64/perl5/5.34 /usr/local/share/perl5/5.34 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./hack/buildah-vendor-treadmill line 9.
BEGIN failed--compilation aborted at ./hack/buildah-vendor-treadmill line 9.

**Comment by edsantiago** [comment]
Ouch - I'm so sorry, I thought that was a standard perl package. It's not. Would you be okay with:
```console
# dnf install perl-open perl-File-Temp perl-JSON perl-libwww-perl
```
If that's too much of a hassle, you could try a local checkout of #13808 and cherry-picking the first (ONLY THE FIRST) commit.

**Comment by rhatdan** [comment]
Already grabbed it and added to this commit.

After installing perl-open, I am seeing.

$ ./hack/buildah-vendor-treadmill --pick
|
+---> HEAD is a buildah vendor commit. Good.
501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)

**Comment by edsantiago** [comment]
Thanks. Looks like I need to re-think the `--pick` step, maybe do it in bash instead, at the cost of some error checking. For now, I think you should be OK with the approach you used (manually merging the changes). Sorry about the hassle.

**Comment by rhatdan** [comment]
If this works, that is the least hassle I have ever had.

**Comment by mheon** [comment]
LGTM once this goes green

**Comment by edsantiago** [comment]
I ran `test/buildah-bud/run-buildah-bud-tests` on my laptop. Patches applied cleanly (yay), tests mostly passed. The two exceptions were of the form:
```
  STEP 2/2: RUN apk add nginx
   fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
   ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.10/main: temporary error (try again later)
```
which is an unfortunate flake we get periodically.

Alas, I've just realized that this PR is based on 6984a0f35, and does not include #13990 (the remote --tls-verify fix) so `bud remote` is going to fail. Sorry about that, I wish I'd caught it sooner.

**Comment by TomSweeneyRedHat** [comment]
LGTM
once you win the thumb wrestling match with the tests.

**Comment by edsantiago** [comment]
Yep, `bud remote` failed. Easiest solution: rebase on latest main, and repush. (The good news is that `bud local` passed, and `bud remote` only failed in the single test I was expecting to fail. IOW, the treadmill process is working).

**Comment by edsantiago** [comment]
yay, both `bud` tests passed!

/lgtm
/hold

**Comment by edsantiago** [comment]
ARGH. #13908 clobbered you.

**Pull request merged**
