### PR TITLE
[CI:DOCS] Update Tutorials.rst

### PR DESCRIPTION
**Pull request by jortkoopmans**
fix typo

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @jortkoopmans 
LGTM
But you need to sign your PRs
git commit -a --amend -s
git push --force

**Comment by TomSweeneyRedHat** [comment]
LGTM
once signed and thanks!

**Comment by jortkoopmans** [comment]
Ok, I've tried to fit your requirements here and had to rebase 2 times.

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons.

**Comment by TomSweeneyRedHat** [comment]
and thanks @jortkoopmans !

**Pull request merged**
