### PR TITLE
Update vendor of buildah to latest code

### PR DESCRIPTION
**Pull request by rhatdan**
Fix podman build man pages to match buildah functionality.

Also document .dockerignore formatted files.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @vrothberg @TomSweeneyRedHat @QiWang19 @ashley-cui @mheon @baude @jwhonce PTAL

**Comment by TomSweeneyRedHat** [comment]
Was just going to ask if you could add that c/common was also getting updated in the title and/or description.
Changes LGTM

**Comment by edsantiago** [comment]
/lgtm
/hold

I would've preferred a `--epoch=UINT` arg instead, but that ship has probably sailed

**Pull request merged**
