### PR TITLE
Vendor in containers/(storage, common)

### PR DESCRIPTION
**Pull request by rhatdan**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago a lot of the fixes for composefs from containers/storage by @giuseppe should be in this PR.

**Comment by Luap99** [comment]
we need https://github.com/containers/podman/pull/22465 first to bump go

**Comment by edsantiago** [comment]
Please revendor once  https://github.com/containers/storage/pull/1904 merges

**Comment by edsantiago** [comment]
Also, "thinpool" seems to be gone in latest c-storage, and now podman barfs:
```
WARN[0000] Failed to decode the keys ["storage.options.thinpool"] from "/usr/share/containers/storage.conf"
```
Not sure if this needs to be fixed in podman-land or something-else-land.

**Comment by edsantiago** [comment]
You'll also need to wait for a fix for https://github.com/containers/podman/issues/22478

**Comment by vrothberg** [comment]
Not needed after https://github.com/containers/podman/pull/22638 anymore

**Pull request closed without merging**
