### PR TITLE
v2.0 Backports

### PR DESCRIPTION
**Pull request by ashley-cui**
KubeIP and Default conf didn't get put in last version

### CODE REVIEW

**Comment by ashley-cui** [comment]
@rhatdan PTAL, hopefully properly cherry-picked it

**Comment by rhatdan** [comment]
LGTM
/approve
@mheon @vrothberg @TomSweeneyRedHat @giuseppe @baude @QiWang19 @jwhonce PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
