### PR TITLE
Bump golang to 1.17

### PR DESCRIPTION
**Pull request by PascalBourdier**
Go 1.17 compiler got faster

Signed-off-by: Pascal Bourdier <pascal.bourdier@gmail.com>

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
I am OK bumping the `vendor-in-container` target.  The other changes require much more changes for the testing VMs; @cevich is working on that atm.

**Review by vrothberg — COMMENTED** [review]
Thanks!  Could you squash the three commits into one before we merge?

**Comment by Luap99** [comment]
Wouldn't this mean that if someone runs `make vendor-in-container` and commit the changes they would be not pass CI because CI compares that against make vendor with go 1.16?

**Comment by vrothberg** [comment]
> Wouldn't this mean that if someone runs `make vendor-in-container` and commit the changes they would be not pass CI because CI compares that against make vendor with go 1.16?

I run go 1.18 beta and don't have any issues.  But I see wisdom in your concern.  It's probably a good idea to have vendor-in-container and the consistency check to use the _same_ container image. @cevich WDYT?

I am OK to merge this PR as is and do the remainder in a separate one.

**Comment by cevich** [comment]
> But I see wisdom in your concern. It's probably a good idea to have vendor-in-container and the consistency check to use the same container image. @cevich WDYT?

This is possible to do.  No new container image is needed since we already build one (ref `quay.io/libpod/fedora_podman:$IMAGE_SUFFIX`).  This can be guaranteed to always be in-sync with CI automation. by following the example in skopeo's Makefile (ref. `SKOPEO_CIDEV_CONTAINER_FQIN`) + a `hack/get_fqin.sh` script.  It's slightly convoluted how it works, since it involves parsing of `.cirrus.yml`.  But it's been in use/successful in skopeo for quite a long while.

**Comment by cevich** [comment]
> I am OK to merge this PR as is and do the remainder in a separate one.

If it helps...for similar needs that require coordination with new images, I can always rebase an image-update PR onto other PRs so they all get merged together.

**Pull request merged**
