### PR TITLE
Wrap missing container errors with container ID

### PR DESCRIPTION
**Pull request by rhatdan**
While playing around with podman system df, I saw that my container
database was in bad state.  Basically podman new about containers
that were no longer in container/storage.

The podman system df was just erroring out early stating "container does not exist"
with no indicator of which container.

This Patch wraps the podman system df errors to indicate which container does not exist.
It also logs errors on containers that get into this state, but continues on to work on
all containers.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
The OCI runtime container deletion should not be returning c/storage errors
- it shouldn't be interacting with c/storage at all, only calling OCI
runtime delete?

**Comment by rhatdan** [comment]
Yes you are right.  I am not sure why I got an error when trying to delete. and now I cleaned up my repository.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL
This one is ready to go in.

**Comment by mheon** [comment]
LGTM

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Review by QiWang19 — COMMENTED** [review]
/lgtm

**Pull request merged**
