### PR TITLE
Fix crash on quadlet Mount bad option

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/20104

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM
@ygalblum PTAL

**Comment by vrothberg** [comment]
NOTE that there is also https://github.com/containers/podman/pull/20108 attempting to fix the same issue

**Review by Luap99 — CHANGES_REQUESTED** [review]
Why are we parsing/validation option values in quadlet?
We should simply not do that, this will never match the real code one to one. Juts pass the value to `--mount` and let the podman run command fails is much better for us in terms of maintenance and should match what we do for the other quadlet options.

This code is broken and does not allow valid mount flag values! i.e. `--mount type=bind,src=/tmp,dst=/tmp,ro`

**Comment by vrothberg** [comment]
@Luap99, I agree, the `Mount` code needs some attention.  Quadlet is parsing the code to 
* make sure the specified sources are mounted by adding a `RequiresMountsFor`
* transform a `.volume` mount source

Maybe function for parsing mounts (from Podman) should be used instead to make sure things are being parsed correctly.

> This code is broken and does not allow valid mount flag values! i.e. `--mount type=bind,src=/tmp,dst=/tmp,ro`

I think this works (see tests).

**Comment by giuseppe** [comment]
could we consider #20108 since it was opened first?

**Comment by Luap99** [comment]
> > This code is broken and does not allow valid mount flag values! i.e. `--mount type=bind,src=/tmp,dst=/tmp,ro`
> 
> I think this works (see tests).

I don't see any tests for an option without `=`. This PR adds code which will error out if it does not contain an equal sign which means its breaks valid options and backwards compatibility. 
In general this parsing code is broken, this is not how we parse --mount, we cannot split by comma it has to use a proper CSV parser to handle the escaping of special chars.

please add this as test:
```diff
diff --git a/test/e2e/quadlet/mount.container b/test/e2e/quadlet/mount.container
index dae7be9f2..52b52d06b 100644
--- a/test/e2e/quadlet/mount.container
+++ b/test/e2e/quadlet/mount.container
@@ -8,6 +8,8 @@ Mount=type=bind,src=/path/on/host,dst=/path/in/container,relabel=shared
 Mount=type=bind,src=/path/on/host,dst=/path/in/container,relabel=shared,U=true
 ## assert-podman-args-key-val "--mount" "," "type=volume,source=vol1,destination=/path/in/container,ro=true"
 Mount=type=volume,source=vol1,destination=/path/in/container,ro=true
+## assert-podman-args-key-val "--mount" "," "type=volume,source=vol1,destination=/path/in/container,ro"
+Mount=type=volume,source=vol1,destination=/path/in/container,ro
 ## assert-podman-args-key-val "--mount" "," "type=volume,source=systemd-vol2,destination=/path/in/container,ro=true"
 ## assert-key-is "Unit" "Requires" "vol2-volume.service"
 ## assert-key-is "Unit" "After" "vol2-volume.service"
```

Which will fail with 
```
converting "mount.container": invalid mount option "ro", must contain an `=` sign
```

**Comment by rhatdan** [comment]
Removed parsing from quadlet, let Podman deal with the bogus params.

**Pull request closed without merging**
