### PR TITLE
Prune FCOS related code

### PR DESCRIPTION
**Pull request by baude**
Given the switch to pulling oci artifacts for podman, we no longer need a fair bit of fedora coreos code for automatically downloading images.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by cgwalters** [comment]
I'm not sure if it was this PR but I'm reusing this as a support forum.  I was running a snapshot of podman git main as of about 1.5 months ago.  Updating to git as of today, on MacOS I needed to do a full reset.  Trying to start things from scratch I now get:

```
Error: obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
```

This is coming from the disk image pull from the registry.  So we're now involving the c/image stack on the Mac...was there some corresponding change to set up that infrastructure on there?

(There's obviously also a related thread here about being friendlier to the "empty /etc" model even on Linux, which would also have made this bug less relevant)

**Pull request merged**
