### PR TITLE
[CI:DOCS] Fix example for manifest push

### PR DESCRIPTION
**Pull request by dbaker-rh**
Updating the "podman manifest push" example to match the required syntax.

If you run the command as stated:
- Error: error pushing manifest multiarch to quay.io/myimagelist: Invalid image name "quay.io/myimagelist", expected colon-separated transport:reference

### CODE REVIEW

**Comment by mheon** [comment]
@QiWang19 PTAL

**Comment by mheon** [comment]
@dbaker-rh Can you add a signoff to your commit? `git commit --amend -s` and then a force-push should do it.

**Comment by TomSweeneyRedHat** [comment]
LGTM 
assuming happy tests

**Comment by dbaker-rh** [comment]
signed and re-pushed.

**Review by QiWang19 — COMMENTED** [review]
LGTM

**Pull request merged**
