### PR TITLE
[CI:DOCS] Correct a typo in documentation

### PR DESCRIPTION
**Pull request by tartina**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
Needs a signoff - @tartina Can you do a `git commit --amend -s` and then re-push?

**Comment by mheon** [comment]
/approve
LGTM otherwise

**Comment by tartina** [comment]
Added signoff

**Pull request merged**
