### PR TITLE
Quadlet - fix trailing whitespaces handling

### PR DESCRIPTION
**Pull request by ygalblum**
Remove all trailing white spaces from all lines before the line by line processing
Add test

#### Does this PR introduce a user-facing change?
No

```release-note
None
```

Resolves: #21109

### CODE REVIEW

**Comment by ygalblum** [comment]
@edsantiago I need your help here. The issue that triggered this PR is a case of a trailing space. As part of the fix, I wrote a test unit file that includes a trailing white space. But, the basic tests are failing because of the trailing space. What should I do?

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by ygalblum** [comment]
> @edsantiago I need your help here. The issue that triggered this PR is a case of a trailing space. As part of the fix, I wrote a test unit file that includes a trailing white space. But, the basic tests are failing because of the trailing space. What should I do?

Never mind, I've found the solution

**Comment by ygalblum** [comment]
@vrothberg I change the implementation of the method that clears trims the lines (both because it made the unit test fail and because now it's simpler and cannot return an error)

**Review by vrothberg — COMMENTED** [review]
Nice, LGTM+

**Comment by rhatdan** [comment]
I was working on a different patch to throw an error in this situation. But this looks fine.
/lgtm

**Comment by edsantiago** [comment]
Belated LGTM2

**Pull request merged**
