### PR TITLE
Allow systemd specifiers in User and Group Quadlet keys

### PR DESCRIPTION
**Pull request by rhatdan**
Replaces: https://github.com/containers/podman/pull/18262

#### Does this PR introduce a user-facing change?

```release-note
Systemd specifiers now work with Quadlet User and Group keys
```

### CODE REVIEW

**Review by ygalblum — APPROVED** [review]
LGTM

**Comment by ygalblum** [comment]
golangci-lint is complaining

**Review by vrothberg — COMMENTED** [review]
Please add a test for the example in the other PR:
```
User=%U
Group=%G
```

**Review by vrothberg — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm
/unhold

**Pull request merged**
