### PR TITLE
pkg/machine: make it build for freebsd

### PR DESCRIPTION
**Pull request by Luap99**
This is completely untested as I do not have access to a freebsd system but it compiles and changes look simple enough to assume it works.

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
Let's get this one in quick, I don't like having CI disabled

**Comment by jakecorrenti** [comment]
LGTM

**Comment by lsm5** [comment]
ignore testing-farm failures

**Comment by mheon** [comment]
/lgtm
/hold

Do not un-hold until #21550 merges

**Comment by Luap99** [comment]
Someone has to explain to me why github claims this has a conflict but I was able to git rebase without any conflict locally??

**Pull request merged**
