### PR TITLE
Bump version to v4.1.0-dev

### PR DESCRIPTION
**Pull request by Luap99**
I think we forgot to bump the version in the main branch. It should be
v4.1.0-dev now.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by Luap99** [comment]
@jwhonce PTAL at the bindings test failure.

**Comment by jwhonce** [comment]
@Luap99 

https://github.com/containers/podman/blob/main/pkg/bindings/test/manifests_test.go#L99 should be `Expect(code).To(BeNumerically("==", http.StatusBadRequest))` from reading the handler code. I made the change in https://github.com/containers/podman/pull/13274 to better match the other endpoints and documentation. The worrisome issue is why did it take this long to manifest?

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
