### PR TITLE
test: update fedoraMinimal version

### PR DESCRIPTION
**Pull request by giuseppe**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve
/hold

**Comment by rhatdan** [comment]
Tests do not seem happy with the change.

@edsantiago PTAL

**Comment by edsantiago** [comment]
Looks like this f38 image does not include `useradd` or `groupadd`. I guess we either find an image that does, or build our own, or rewrite those tests

**Comment by giuseppe** [comment]
`fedora-minimal:39` seems to have the tools we need, let's give it a try

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
@edsantiago are you fine with this change?

**Comment by edsantiago** [comment]
Ab-so-lutely! Thank you for finding an image that works!

/lgtm

**Pull request merged**
