### PR TITLE
[v4.2.0-rhel] [CI:DOCS] Cirrus: Update meta task for EC2

### PR DESCRIPTION
**Pull request by cevich**
Ref: #15502

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
You might need to hit dest-branch as well, I completely forgot to on this branch...

**Comment by cevich** [comment]
> You might need to hit dest-branch as well, I completely forgot to on this branch...

Oh, good catch, got it, thanks!

**Comment by rhatdan** [comment]
/approve
LGTM
@containers/podman-maintainers PTAL

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
