### PR TITLE
podman push --delete [WIP]

### PR DESCRIPTION
**Pull request by ParkerVR**
Addresses https://github.com/containers/podman/issues/9866

Ported some code from Skopeo for remote deletion, need to figure out the tunnels component and ?add the auth to replace skopeo global opts?, also needs a test

Signed-off-by: Parker Van Roy <ParkerVR@bu.edu>

### CODE REVIEW

**Comment by vrothberg** [comment]
Closing for now as the internship ended. @ParkerVR, feel free to reopen if you want to push it over the finish line.

**Comment by ParkerVR** [comment]
Started this one on my own time :^)

**Comment by vrothberg** [comment]
Awesome, thanks @ParkerVR !

**Comment by lsm5** [comment]
@ParkerVR hey, just checking if you have time to continue this. Let me know if you're ok with me taking this over.

**Comment by lsm5** [comment]
@ParkerVR gentle re-ping :)

**Comment by ParkerVR** [comment]
@lsm5 sorry to hold you up on this, I’ve been away. Feel free to take over! The last part necessary here is the skopeo context needs to be rebuilt for the necessary values

**Comment by vrothberg** [comment]
Thanks for working on this, @ParkerVR!

I am closing this PR and @lsm5 can continue the work.

**Comment by lsm5** [comment]
thanks a lot @ParkerVR . I'll continue from here.

**Pull request closed without merging**
