### PR TITLE
Cirrus: Update to Ubuntu 21.10 + Disable F33

### PR DESCRIPTION
**Pull request by cevich**
#### What this PR does / why we need it:

Update the Ubuntu CI environment from 21.04 -> 21.10

#### How to verify it

The Ubuntu-based CI tests will all pass

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Does ***NOT*** update the Fedora images, this is being done separately in https://github.com/containers/podman/pull/11795

Ref: https://github.com/containers/automation_images/pull/100

### CODE REVIEW

**Comment by cevich** [comment]
> Oooh! Will this include a new crun

Possibly, it's using whatever is in Lokesh's OBS Kubik testing-repo.  Actually, I can poke at the Ubuntu container image and tell you right now...

**Comment by edsantiago** [comment]
If I read the git log correctly, the fix I need is in crun 1.3. Looks like I have a ways to wait still. Oh well, thank you!

**Comment by cevich** [comment]
> If I read the git log correctly, the fix I need is in crun 1.3

Maybe not too much longer.  With this PR and the F35 one, we can get what you need.

@lsm5 is it possible for you to bump crun in U21.10 kubik testing to 1.3 or are we using the distro-packaged one?

**Comment by cevich** [comment]
Crun 1.3 building now, Ref: https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/crun

**Comment by edsantiago** [comment]
Weird. [podman-remote f33 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5928922169737216/html/int-remote-fedora-33-root-host.log.html) failures are all consistently of the form "timed out waiting for `podman run -dt with-network-ports`".

**Comment by cevich** [comment]
Hmmm, that's new.

**Comment by cevich** [comment]
Yeah, I don't get it, something may have changed in the images since I rebuilt them this morning.  In any case, F33 is officially **dead**, so with this PR + 11795 we should be okay.  In fact today, I've been thinking about just combining the two to make life easier.

**Comment by cevich** [comment]
Okay there, let's do it this way and I'll turn back on "prior-fedora" when it represents F34.

**Comment by edsantiago** [comment]
FWIW I'm not convinced that this is an f33 problem. I ran my PR #11957 using these images, and f33 passed just fine. I don't know what to do with that information, though.

**Comment by cevich** [comment]
> my PR #11957 using these images, and f33 passed just fine

Hmmm...maybe that damn random-isn't-random thing or some other flake is happening then.  Okay, good to know it seems to be a flake of some sort.

**Comment by cevich** [comment]
To be clear: My motivation is to get this PR in ASAP since it seems to have low-resistance test-failure wise.  Also there are a number of other PRs waiting on an image-update (in general) in order to pick up things like the new `golang 1.17` and updated catatonit.

**Comment by edsantiago** [comment]
I'm always eager to merge PRs like this, where the VMs are updated, because they are representative of the real world. My concern here is not "let's skip this PR", but rather "something has broken in f33, and we need to be prepared to troubleshoot it".

**Comment by cevich** [comment]
> and we need to be prepared to troubleshoot it.

Only until this PR is merged since officially F33 isn't supported anymore...Of course I'm assuming this problem hasn't and won't shown up in F34+.  And to TBH, I'm just ***REALLY*** exhausted with working on VM image update PRs and want to move on to other things :stuck_out_tongue_winking_eye:

**Comment by edsantiago** [comment]
OMG [so many flakes](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5997224665546752/html/int-podman-ubuntu-2110-rootless-host.log.html). Restarted.

**Comment by rhatdan** [comment]
LGTM

**Comment by cevich** [comment]
> OMG so many flakes. Restarted.

Thanks.  Nothing stood out at me in the journal, and those tests passed previously, so :man_shrugging: must really be flakes :disappointed: 

```Nov 11 19:58:50 cirrus-task-5997224665546752 conmon[219481]: Load average: 4.70 4.50 4.00 8/1076 1```

Oof...Well...at least we're getting our money's worth out of those two vCPUs :grin:

**Comment by cevich** [comment]
Okay, seems "safe" to merge this (there are some flakes).  I'm just too timid to actually press the button.  Who wants a :cookie: Who wants a :cookie: ?

**Pull request merged**
