### PR TITLE
[CI:DOCS] fix swagger api docs

### PR DESCRIPTION
**Pull request by Luap99**
Separate the volume endpoints into compat and libpod,
as it is done for the other endpoints.

Move the libpod image push endpoint to images.

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon @jwhonce @baude PTAL

**Comment by baude** [comment]
lgtm, @jwhonce ptal

**Comment by rhatdan** [comment]
@mheon @jwhonce @ashley-cui PTAL

**Pull request merged**
