### PR TITLE
[CI:DOCS] point IRC to libera.chat

### PR DESCRIPTION
**Pull request by edsantiago**
Project IRC comms are moving to Libera. Update docs.

Confirmation cookie: libera-ieVeeGahbiaf1einguw1xav6bahquie

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Cookie as requested by Libera.Chat ticket number 421, channel registration.

**Comment by edsantiago** [comment]
@containers/podman-maintainers in case anyone is around this weekend: merging this will grant us ownership of the `#podman` namespace on libera.chat

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by Luap99** [comment]
I think podman.io also needs to be updated.

**Pull request merged**
