### PR TITLE
Allow volume mount dups, iff source and dest dirs

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/4217

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Duplicate volume mounts as long as source and destination match are now allowed.
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Tests LGTM. PR title (and commit message) seems incomplete?

**Comment by mheon** [comment]
What about identical source/dest but different options? I think that's why we did string dedup/exact match detection in the API

**Comment by rhatdan** [comment]
@mheon I believe I have handled the options issue now.

**Comment by baude** [comment]
LGTM

**Pull request merged**
