### PR TITLE
[v2.0.5-rhel] Cirrus: Only essential automated testing

### LINKED ISSUE #8555: v2.0.5-rhel branch near-constant CI-Failures
/kind bug

**Description**

Every day Cirrus-CI triggers a build on the v2.0.5-rhel branch and one/more Fedora tasks frequently fail:

* [11/30 example](https://cirrus-ci.com/build/5095160889475072)
* [11/29 example (passed on re-run)](https://cirrus-ci.com/build/4850328627576832)
* [11/28 example](https://cirrus-ci.com/build/5487638826188800)
* [11/27 example](https://cirrus-ci.com/build/4966383140208640)
* ...+ 8 more daily examples :face_with_head_bandage: 

**Steps to reproduce the issue:**

1. Wait a day

**Describe the results you received:**

One or more Fedora integration tests fail.

**Describe the results you expected:**

Should not be daily failures.

**Additional information you deem important (e.g. issue happens only occasionally):**

Maybe testing tasks on this branch can be pruned so there is less chance for flake?

Another idea could be to add a ginkgo filter statement to exclude frequently flaking test(s)?

### PR DESCRIPTION
**Pull request by cevich**
Fixes #8555

This disables all but the most essential CI tasks for the branch, due to frequent flakes in the F32 Remote client integration test.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@cevich, weird error here, I think a flake.

**Comment by cevich** [comment]
@TomSweeneyRedHat I'm assuming you're talking about the `add branch to title / update_pr (pull_request)` failure.  That's a Github-Actions worflow @vrothberg setup.  He's the best one to try and debug it.  Unf. fixes to it cannot happen in any PR, the workflow only ever takes effected _after_ it's merged into the master branch (Thanks Github!).  So it's probably something you can safely ignore.

**Comment by cevich** [comment]
There...manual PR title rename for clarity.

**Pull request merged**
