### PR TITLE
[v4.6] Bump to v4.6.0-rc2

### PR DESCRIPTION
**Pull request by ashley-cui**
```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by ashley-cui** [comment]
@containers/podman-maintainers mergeme

**Comment by edsantiago** [comment]
This looks like a NOP? What am I missing?

**Comment by ashley-cui** [comment]
@edsantiago It's the version bump for our rc2 release, one of the commits bumps to -rc2 for the tag, and the other commit brings it back to -dev for active work on the branch.

**Review by lsm5 — APPROVED** [review]
/lgtm
/hold

**Comment by edsantiago** [comment]
ack, thanks. [For future reference by those unfamiliar with the process](https://github.com/containers/podman/blob/285665f6f8cedf2bbe5d36a79872b9139a69837e/RELEASE_PROCESS.md?plain=1#L156-L180).

**Comment by lsm5** [comment]
aren't label commands working ?

**Comment by lsm5** [comment]
I'll manually hit `Merge pull request` .  You have a minute to stop me :D

**Pull request merged**
