### PR TITLE
[NO TESTS NEEDED] Update cirrus vms for testing

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@cevich is this the correct VM to check?

**Comment by rhatdan** [comment]
@cevich @mheon @vrothberg Just updating the repo is causing all of the errors.

**Comment by cevich** [comment]
Ya that's the right image ID.  The [APIv2 failure is the flake we've seen](https://cirrus-ci.com/task/5501586081316864?command=main#L687) in a few of the daily cirrus-cron runs.  That's issue https://github.com/containers/podman/issues/9328

[The `podman run blkio-weight test` failure](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4586792407007232/html/int-podman-fedora-33-root-host.log.html#t--podman-run-blkio-weight-test--1) I brought to @giuseppe notice a few weeks ago, IIRC, it looks familiar.  I swore I opened an issue on this...but apparently not :disappointed:  (or I couldn't find it).  It's a real problem (somewhere, kernel update?), I remember going onto a VM and was able to reproduce it.  I also verified the cgroups 1 vs 2 range-conversion on "15" math is correct (it should spit out "51"). I want to say Giuseppe reported it fixed by a crun update, but can't be sure.  However, clearly something is missing or disconnected somewhere.

[The "podman network with multiple aliases" is new to me](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4586792407007232/html/int-podman-fedora-33-root-host.log.html#t--podman-network-with-multiple-aliases--1), I don't recall seeing that before.

Have you tried `hack/get_ci_vm.sh`?

**Comment by rhatdan** [comment]
Yes We have a simple fix for the 51->15 and fixed.

The Multiple networks, I am not sure what is going on there.
The API Test failing, I am also confused, but the podman in podman test failures are the most curios.

**Comment by cevich** [comment]
> the podman in podman test failures are the most curios.

Meaning the `int podman fedora-33 root container` task:
https://cirrus-ci.com/task/5431217337139200?command=main#L6021

I'm confused :confused:  Those (in this PR) look like the same failures we see on the VMs?

**Pull request closed without merging**
