### PR TITLE
WIP: test c/common pasta-result branch

### PR DESCRIPTION
**Pull request by Luap99**
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by jiridanek** [comment]
```
Dependencies resolved.
============================================================================================================================================================================================================================================
 Package                           Architecture               Version                                                                               Repository                                                                         Size
============================================================================================================================================================================================================================================
Upgrading:
 podman                            x86_64                     102:5.0.0~dev-1.20240314140356800899.pr22043.29.18e5d5cdb.fc40                        copr:copr.fedorainfracloud.org:packit:containers-podman-22043                      15 M
 podman-remote                     x86_64                     102:5.0.0~dev-1.20240314140356800899.pr22043.29.18e5d5cdb.fc40                        copr:copr.fedorainfracloud.org:packit:containers-podman-22043                     9.7 M

Transaction Summary
============================================================================================================================================================================================================================================
Upgrade  2 Packages

Total download size: 24 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): podman-5.0.0~dev-1.20240314140356800899.pr22043.29.18e5d5cdb.fc40.x86_64.rpm                                                                                                                         9.4 MB/s |  15 MB     00:01    
(2/2): podman-remote-5.0.0~dev-1.20240314140356800899.pr22043.29.18e5d5cdb.fc40.x86_64.rpm                                                                                                                  5.5 MB/s | 9.7 MB     00:01    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Now,

````
podman run --rm -it quay.io/fedora/fedora:38-x86_64 curl http://download-node-02.eng.bos.redhat.com
```

works with my split DNS! Thanks!

**Comment by Luap99** [comment]
@jiridanek Thanks for checking!

**Comment by jiridanek** [comment]
Had a few unpleasant moments figuring out how to undo that install

```
$ sudo dnf history list | head
$ sudo dnf history rollback 525
```

has gotten me back to my original (broken) state

**Comment by Luap99** [comment]
pushed my fixes into https://github.com/containers/podman/pull/22079 as this already contains the vendor changes and would not pass without it.

**Pull request closed without merging**
