### PR TITLE
Add more unit tests

### PR DESCRIPTION
**Pull request by baude**
Improve "code coverage" with more unit-tests.

Signed-off-by: Brent Baude <bbaude@redhat.com>

<!--
Thanks for sending a pull request!

Please make sure you've read our contributing guidelines and how to submit a pull request (https://github.com/containers/podman/blob/main/CONTRIBUTING.md#submitting-pull-requests).

In case you're only changing docs, make sure to prefix the pull-request title with "[CI:DOCS]".  That will prevent functional tests from running and save time and energy.

Finally, be sure to sign commits with your real name.  Since by opening
a PR you already have commits, you can add signatures if needed with
something like `git commit -s --amend`.

```none

```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by Luap99 — COMMENTED** [review]
btw I prefer to use https://pkg.go.dev/github.com/stretchr/testify/assert for such tests.

Also for errors I like to actually check the string error message instead of just checking if there is an error because sometimes you do not actual test what you think.

**Pull request merged**
