### PR TITLE
More sqlite fixes

### PR DESCRIPTION
**Pull request by vrothberg**
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@edsantiago, feel free to test them in your PR.  I am optimistic.

**Comment by vrothberg** [comment]
> Error: beginning refresh transaction: database is locked

Still there :scream:

**Comment by edsantiago** [comment]
Yep, [in my PR also](https://api.cirrus-ci.com/v1/artifact/task/5339157514420224/html/int-podman-fedora-37-rootless-host-sqlite.log.html).

**Comment by edsantiago** [comment]
Consistently (three out of three runs) failing in `int f37 rootless`. Consistently NOT failing `int root` nor `sys rootless`. What is it about `int rootless` that is triggering this?

**Comment by edsantiago** [comment]
Also... there's something else broken in `int sqlite` tests. They are still running, 40 minutes and counting. Will post final timing results when the jobs finished, but right now it looks very bad.

**Comment by vrothberg** [comment]
I dropped the first commit which actually always caused the DB locked error when running rootless.

**Comment by vrothberg** [comment]
Finger's crossed.  Thinking about it, we haven't seen this issue without the shared cache which I dropped now again.

**Comment by vrothberg** [comment]
@edsantiago this looks better on my end.

**Comment by edsantiago** [comment]
YAY! None of the evil strings appear anywhere in the downloaded CI logs. LGTM but let's wait for my PR to finish CI.

**Comment by vrothberg** [comment]
> YAY! None of the evil strings appear anywhere in the downloaded CI logs. LGTM but let's wait for my PR to finish CI.

\o/ it seems the cache option indeed is evil.

**Comment by vrothberg** [comment]
> Sigh. I'm sorry. [f37 rootless](https://api.cirrus-ci.com/v1/artifact/task/4585926416924672/html/int-podman-fedora-37-rootless-host-sqlite.log.html), two "UNIQUE constraint" failures. I've double-checked that my PR is correctly rebased on top of 17889, but please feel free to check again.

:exploding_head: 

Thanks, Ed.  I'll continue digging tomorrow.

**Comment by vrothberg** [comment]
There's still a race it seems.

**Comment by edsantiago** [comment]
So, from my pov: even if this doesn't fix the UNIQUE bug, I'm OK with this merging. It seems to cause no harm, and I trust your investigation about shared-cache. I don't know enough sqlite to be the one to merge it, though. Maybe @mheon can look at it tomorrow. Thanks, everyone, for your persistence on this.

**Comment by edsantiago** [comment]
Timing results (redacted, to only show difference between boltdb and sqlite):

| type | distro              | user     | DB     |    local |   remote | container |
| ---- | --------            | ----     | --     |    ----: |   -----: | --------: |
| int  | fedora-37           | root     |        |    30:39 |    33:14 |     30:17 |
| int  | fedora-37           | root     | sqlite |    28:50 |    33:38 |
| int  | fedora-37           | rootless |        |    28:55 |          |
| int  | fedora-37           | rootless | sqlite |    27:23 |          |

**Comment by vrothberg** [comment]
> So, from my pov: even if this doesn't fix the UNIQUE bug, I'm OK with this merging. It seems to cause no harm, and I trust your investigation about shared-cache. I don't know enough sqlite to be the one to merge it, though. Maybe @mheon can look at it tomorrow. Thanks, everyone, for your persistence on this.

I am also OK with merging the PR as is.  Maybe @mheon will find the needle in the haystack and get migration code healthy.

**Comment by edsantiago** [comment]
OK, this is weird. Two more `UNIQUE constraint` errors ... but in the same task ([f37 rootless](https://api.cirrus-ci.com/v1/artifact/task/5716217122521088/html/int-podman-fedora-37-rootless-host-sqlite.log.html)) and, Twilight Zone music, the same two subtests, and almost the same delta-T (10s vs 12s) between the failures. I'm tempted to conclude that there's something weird happening when those two tests run simultaneously. But what?? All tests use a different `root` and `runroot`. Could there be some other shared directory when sqlite is involved? And only rootless??

**Comment by edsantiago** [comment]
Another CI run, here's [f36](https://api.cirrus-ci.com/v1/artifact/task/6646594146140160/html/int-podman-fedora-36-rootless-host-sqlite.log.html#t--podman-container-restart-running-container--1) and [f37](https://api.cirrus-ci.com/v1/artifact/task/5520694239297536/html/int-podman-fedora-37-rootless-host-sqlite.log.html#t--podman-container-restart-running-container--1), both rootless, both in "restart running container" test.

**Comment by mheon** [comment]
This LGTM. I know what the other issue is (TOCTOU in the validation code, two Podman processes can race to create the row) but it's a bit annoying to fix to it will have to wait until tomorrow afternoon.

**Comment by edsantiago** [comment]
Here's a really, really nice one. [f37 rootless](https://api.cirrus-ci.com/v1/artifact/task/5072482357477376/html/int-podman-fedora-37-rootless-host-sqlite.log.html), no surprise, but what's sweet is that it's a triple-failure in the `restart` test (single-failure is more common). Not only that, but there's a triple-failure in the `stop podman.service` test. I thought I had fixed that by adding `--runroot` to the podman invocation, but nope. (TL;DR the `stop podman.service` failure is a brand-new one, happening only in sqlite tests. I've never seen it until this week). 

I am over 90% convinced that there is *something* happening with concurrent sqlite processes, some shared file that should not be shared.

**Comment by vrothberg** [comment]
@baude @mheon @edsantiago merge me please

**Pull request merged**
