### PR TITLE
[WIP]change macos directory for machine sockets

### PR DESCRIPTION
**Pull request by baude**
if the machine name is long and/or the username is long, it is possible to exceed the 104byte limit for filenames in MacOS.  This PR shortcuts things to $HOME/.podman instead.

Fixes: #13609

[NO NEW TESTS NEEDED]

Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
is there a way to know where podman is storing machine sockets ? as it's looking like a breaking change for clients assuming the location of the current podman socket.

From clients wanted to connect to this socket, is there a way to know the path by asking `podman` ?

for example `podman machine list --format json` does not contain the link to the `podman.sock` file

**Comment by baude** [comment]
> is there a way to know where podman is storing machine sockets ? as it's looking like a breaking change for clients assuming the location of the current podman socket.
> 
> From clients wanted to connect to this socket, is there a way to know the path by asking `podman` ?
> 
> for example `podman machine list --format json` does not contain the link to the `podman.sock` file

it is a good question, and largely why I put a WIP on the PR.  In the end, I may need to use symlinks, but I really fear the maintenance of those.  I should also consider putting a cap on the length of the machine names.  We can control those but we cannot control the length of the user names.  So yeah, this fixes the issues and maybe creates some hard questions ....

**Comment by benoitf** [comment]
I think it's fine to change the location as long as there is a way to grab the link to the socket from the `podman machine list --format json` data

like: 
```json
   {
        "Name": "podman-machine-default",
        "Default": true,
        "CPUs": 1,
        
        "HostSocket": "/path/to/podman.sock",
        
}
```

**Comment by n1hility** [comment]
> Also wondering why if there is only one socket available at a time it could not be in `/var/run/` like `docker.sock`
> 
> `/var/run/podman.sock` so it's independent of the user name

The one at a time is a VM backend limitation that hopefully goes away one day, as everything else is designed to support multiple machines per user, and multiple users. 

Writing to var requires root perms, so there is a helper agent that establishes a link for the /var/run/docker.sock support. A similar link could also be established for podman.sock, however, the main convention for podman is ssh urls using podman system connection, so nothing knows to look for it there.

**Comment by n1hility** [comment]
> `/var/run/podman.sock` being a symlink to `$HOME/.podman/run/podman.sock`

Yeah, that's doable. The current commits here are using $HOME/.podman/podman.sock which is a link to the local machine sock. the helper could link podman.sock as well as docker.sock. It has to be installed though for it to be effective.

**Comment by n1hility** [comment]
BTW the last one I just push has compatibility links for old clients and old machines

**Comment by baude** [comment]
Closing in favor of larger refactor do this "right" ->  #13674

**Pull request closed without merging**
