### PR TITLE
Fix stutters

### PR DESCRIPTION
**Pull request by rhatdan**
Podman adds an Error: to every error message.  So starting an error
message with "error" ends up being reported to the user as

Error: error ...

This patch removes the stutter.

Also ioutil.ReadFile errors report the Path, so wrapping the err message
with the path causes a stutter.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

[NO NEW TESTS NEEDED] Since this is code cleanup, existing tests will find any problems,

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
A lot of red unhappy tests here @rhatdan

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL
This should be ready to merge, and is likely to cause conflicts, so I would like to get it in.

**Pull request merged**
