### PR TITLE
Move to v3.1.0-dev

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by mheon** [comment]
You’re targeting master - need to make a branch for this. Also, should be
3.0.0-rc1 not 3.0.0.

**Comment by rhatdan** [comment]
The other PR is for v3.0 branch.  Your description did not state that you want the -rc1 flag on it.  I will update the other Branch.

**Comment by mheon** [comment]
Master should not bump to 3.0 - it should just go to 3.1.0-dev. The 3.0.0
and its RCs live only in the branch

**Comment by rhatdan** [comment]
@mheon I want to have the 3.0.0 changes in the main branch?

**Comment by mheon** [comment]
No, we do not want the 3.0 commit to be in two branches simultaneously. 3.0 is only on the branch, master bumps to the next minor version.

**Comment by rhatdan** [comment]
Ok you add the commit the way that you want.  I would think we should have release_notes for 3.0 on main branch.

**Comment by mheon** [comment]
Release notes, yep, but no "bump to 3.0" commit - will just do a CI:DOCS to port only the release notes over.

**Pull request closed without merging**
