### PR TITLE
[NO TESTS NEEDED] Fixes panic condition in cgroups.getAvailableControllers

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>
Fixes: https://github.com/containers/podman/issues/10666

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
Every single system test flaked, we have to get some eyes on the podman-pause cgroup flake.

**Comment by TomSweeneyRedHat** [comment]
LGTM
if we can ever get the system tests hip.

**Comment by ocofon** [comment]
With this change the crash is gone but the subsystem is added to the list of available controllers even when it is unavailable .
I think if os.Stat() fails the subsystem should be skipped.


```diff --git a/pkg/cgroups/cgroups.go b/pkg/cgroups/cgroups.go
--- a/pkg/cgroups/cgroups.go
+++ b/pkg/cgroups/cgroups.go
@@ -165,14 +165,13 @@ func getAvailableControllers(exclude map[string]controllerHandler, cgroup2 bool)
 		if _, found := exclude[name]; found {
 			continue
 		}
-		isSymLink := false
 		fileInfo, err := os.Stat(cgroupRoot + "/" + name)
 		if err != nil {
-			isSymLink = !fileInfo.IsDir()
+			continue
 		}
 		c := controller{
 			name:    name,
-			symlink: isSymLink,
+			symlink: !fileInfo.IsDir(),
 		}
 		controllers = append(controllers, c)
 	}
```

**Comment by zhangguanzhang** [comment]
all had done.  @ocofon @mheon @TomSweeneyRedHat

**Comment by mheon** [comment]
LGTM

**Pull request merged**
