### PR TITLE
CI: sys: fix "kube play url" flake

### PR DESCRIPTION
**Pull request by edsantiago**
Nasty flakes. This one has been hitting us hard, and only
f38 root (both CNI and netavark).

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
### [sys] [700] podman kube play - URL
* fedora-38 : sys podman fedora-38 root host boltdb
  * PR #21542
    * [02-08 09:40](https://api.cirrus-ci.com/v1/artifact/task/4909462608150528/html/sys-podman-fedora-38-root-host-boltdb.log.html#t--00634)
  * PR #21412
    * [01-29 12:36](https://api.cirrus-ci.com/v1/artifact/task/5451211227267072/html/sys-podman-fedora-38-root-host-boltdb.log.html#t--00633)
* fedora-38 : sys remote fedora-38 root host boltdb [remote]
  * PR #21618
    * [02-12 16:53](https://api.cirrus-ci.com/v1/artifact/task/5501562370392064/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00634)
  * PR #21603
    * [02-10 16:45](https://api.cirrus-ci.com/v1/artifact/task/5562418365988864/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00634)
  * PR #21542
    * [02-08 16:07](https://api.cirrus-ci.com/v1/artifact/task/4807181418102784/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00634)
    * [02-08 09:30](https://api.cirrus-ci.com/v1/artifact/task/5894625026637824/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00634)
  * PR #21291
    * [01-18 13:36](https://api.cirrus-ci.com/v1/artifact/task/5872556444483584/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00631)
  * PR #21067
    * [12-20-2023 11:45](https://api.cirrus-ci.com/v1/artifact/task/4596835503833088/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00628)
    * [02-09 12:37](https://api.cirrus-ci.com/v1/artifact/task/5918172788817920/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00634)

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| sys(9) | remote(7) | fedora-38(9) | root(9) | host(9) | boltdb(9) |
|  | podman(2) |  |  |  |  |

**Comment by edsantiago** [comment]
Converting to draft. This does not fix anything! In my local hammer testing I just got:
```
[05:08:09.449963892] # /home/esm/src/atomic/2018-02.podman/libpod/bin/podman run -d --name myyaml -p 5776:80 -v /tmp/podman_bats.1SlOzR/test.yaml:/var/www/testpod.yaml:Z -v /tmp/podman_bats.1SlOzR/ready:/var/www/ready:Z -w /var/www quay.io/libpod/testimage:20240123 /bin/busybox-extras httpd -f -p 80
[05:08:09.681115870] 36a45377fe03f9eeba9d73cc54690a5a4f70f09633a96b0c85154d9a9b56e951                                                                        
# curl -s -S http://127.0.0.1:5776/ready
curl: (7) Failed to connect to 127.0.0.1 port 5776 after 3098 ms: Couldn't connect to server
...repeat repeat repeat
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#| FAIL: Timed out waiting for 'curl -s -S http://127.0.0.1:5776/ready' to return 'READY'
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Okay, this is not something I can fix.

**Comment by Luap99** [comment]
Weird one, FYI the wait_for_port is useless here as `podman run -d` binds the port on the host always before starting the container.
If it is only as root then it could be some firewall rule issue, however we have many tests that forward a port and connect to it (without flakes?) so why is this one different.

Of course there is the potential race that the http server in the container is not ready but than this patch should have fixed it.

**Comment by edsantiago** [comment]
Added post-flake debug, `ps` and `inspect`. Will look at it tomorrow.
```
  #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #| FAIL: Timed out waiting for 'curl -s -S http://127.0.0.1:5457/ready' to return 'READY'
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   
   [14:22:17.553668027] # /home/esm/src/atomic/2018-02.podman/libpod/bin/podman ps -a
   [14:22:17.608806684] CONTAINER ID  IMAGE                              COMMAND               CREATED             STATUS             PORTS                 NAME
S
   72a55a54fe5a  quay.io/libpod/testimage:20240123  /bin/busybox-extr...  About a minute ago  Up About a minute  0.0.0.0:5457->80/tcp  myyaml
   
   [14:22:17.615893042] # /home/esm/src/atomic/2018-02.podman/libpod/bin/podman container inspect myyaml
   [14:22:17.668337800] [
        {
             "Id": "72a55a54fe5a7bb74cab8cbc504749405c33c90401e1790df96f4540ad1ab211",
             "Created": "2024-02-13T14:21:05.622396682-07:00",
             "Path": "/bin/busybox-extras",
             "Args": [
                  "httpd",
                  "-f",
                  "-p",
                  "80"
             ],
             "State": {
                  "OciVersion": "1.1.0+dev",
                  "Status": "running",
                  "Running": true,
                  "Paused": false,
                  "Restarting": false,
                  "OOMKilled": false,
                  "Dead": false,
                  "Pid": 3480362,
                  "ConmonPid": 3480360,
                  "ExitCode": 0,
                  "Error": "",
                  "StartedAt": "2024-02-13T14:21:05.791046692-07:00",
                  "FinishedAt": "0001-01-01T00:00:00Z",
                  "CgroupPath": "/machine.slice/libpod-72a55a54fe5a7bb74cab8cbc504749405c33c90401e1790df96f4540ad1ab211.scope",
                  "CheckpointedAt": "0001-01-01T00:00:00Z",
                  "RestoredAt": "0001-01-01T00:00:00Z"
},                                                                                                                              14:22:18 [265/4864]
             "Image": "1f6acd4c4a1d4d39395870e1c12dbb68da27dd432afecf86e7cb6e23cf4b75d0",
             "ImageDigest": "sha256:17823456328e5f38b2c0dc7f9453aee0196654dba39ae2220f869717f159159a",
             "ImageName": "quay.io/libpod/testimage:20240123",
             "Rootfs": "",
             "Pod": "",
             "ResolvConfPath": "/run/containers/storage/overlay-containers/72a55a54fe5a7bb74cab8cbc504749405c33c90401e1790df96f4540ad1ab211/userdata/resolv.conf
",
             "HostnamePath": "/run/containers/storage/overlay-containers/72a55a54fe5a7bb74cab8cbc504749405c33c90401e1790df96f4540ad1ab211/userdata/hostname",
             "HostsPath": "/run/containers/storage/overlay-containers/72a55a54fe5a7bb74cab8cbc504749405c33c90401e1790df96f4540ad1ab211/userdata/hosts",
             "StaticDir": "/var/lib/containers/storage/overlay-containers/72a55a54fe5a7bb74cab8cbc504749405c33c90401e1790df96f4540ad1ab211/userdata",
             "OCIConfigPath": "/var/lib/containers/storage/overlay-containers/72a55a54fe5a7bb74cab8cbc504749405c33c90401e1790df96f4540ad1ab211/userdata/config.j
son",
             "OCIRuntime": "crun",
             "ConmonPidFile": "/run/containers/storage/overlay-containers/72a55a54fe5a7bb74cab8cbc504749405c33c90401e1790df96f4540ad1ab211/userdata/conmon.pid",
             "PidFile": "/run/containers/storage/overlay-containers/72a55a54fe5a7bb74cab8cbc504749405c33c90401e1790df96f4540ad1ab211/userdata/pidfile",
             "Name": "myyaml",
             "RestartCount": 0,
             "Driver": "overlay",
             "MountLabel": "system_u:object_r:container_file_t:s0:c702,c790",
             "ProcessLabel": "system_u:system_r:container_t:s0:c702,c790",
             "AppArmorProfile": "",
             "EffectiveCaps": [
                  "CAP_CHOWN",
                  "CAP_DAC_OVERRIDE",
                  "CAP_FOWNER",
                  "CAP_FSETID",
                  "CAP_KILL",
                  "CAP_NET_BIND_SERVICE",
                  "CAP_SETFCAP",
                  "CAP_SETGID",
                  "CAP_SETPCAP",
                  "CAP_SETUID",
                  "CAP_SYS_CHROOT"
             ],
             "BoundingCaps": [
                  "CAP_CHOWN",
                  "CAP_DAC_OVERRIDE",
                  "CAP_FOWNER",
                  "CAP_FSETID",
                  "CAP_KILL",
                  "CAP_NET_BIND_SERVICE",
                  "CAP_SETFCAP",
                  "CAP_SETGID",
                  "CAP_SETPCAP",
                  "CAP_SETUID",
                  "CAP_SYS_CHROOT"
             ],
             "ExecIDs": [],
             "GraphDriver": {
                  "Name": "overlay",
                  "Data": {
                       "LowerDir": "/var/lib/containers/storage/overlay/7ffe79913b6cd452b42b4aef7f51ff4eeecbdde76a464ef55c321a345faaa4a6/diff:/var/lib/container
s/storage/overlay/25a964f60e84b2d24f8098376c985a5c057bea74d699ee50c93e417c26516cc3/diff",
                       "MergedDir": "/var/lib/containers/storage/overlay/3eaf2b080947ac9b2014cfea9370ae414dcbc7cf661ddd4850efaf87ff36f792/merged",
                       "UpperDir": "/var/lib/containers/storage/overlay/3eaf2b080947ac9b2014cfea9370ae414dcbc7cf661ddd4850efaf87ff36f792/diff",
                       "WorkDir": "/var/lib/containers/storage/overlay/3eaf2b080947ac9b2014cfea9370ae414dcbc7cf661ddd4850efaf87ff36f792/work"
                  }
             },
             "Mounts": [
{
                       "Type": "bind",
                       "Source": "/tmp/podman_bats.mmlLZN/ready",
                       "Destination": "/var/www/ready",
                       "Driver": "",
                       "Mode": "",
                       "Options": [
                            "nosuid",
                            "nodev",
                            "rbind"
                       ],
                       "RW": true,
                       "Propagation": "rprivate"
                  },
                  {
                       "Type": "bind",
                       "Source": "/tmp/podman_bats.mmlLZN/test.yaml",
                       "Destination": "/var/www/testpod.yaml",
                       "Driver": "",
                       "Mode": "",
                       "Options": [
                            "nosuid",
                            "nodev",
                            "rbind"
                       ],
                       "RW": true,
                       "Propagation": "rprivate"
                  }
             ],
             "Dependencies": [],
             "NetworkSettings": {
                  "EndpointID": "",
                  "Gateway": "10.88.0.1",
                  "IPAddress": "10.88.15.157",
                  "IPPrefixLen": 16,
                  "IPv6Gateway": "",
                  "GlobalIPv6Address": "",
                  "GlobalIPv6PrefixLen": 0,
                  "MacAddress": "0e:54:b1:5a:65:e9",
                  "Bridge": "",
                  "SandboxID": "",
                  "HairpinMode": false,
                  "LinkLocalIPv6Address": "",
                  "LinkLocalIPv6PrefixLen": 0,
                  "Ports": {
                       "80/tcp": [
                            {
                                 "HostIp": "",
                                 "HostPort": "5457"
                            }
                       ]
                  },
                  "SandboxKey": "/run/netns/netns-a684a72e-74d9-00bd-7dcf-ace252d050e2",
                  "Networks": {
                       "podman": {
"EndpointID": "",                                                                                                                   
                            "Gateway": "10.88.0.1",
                            "IPAddress": "10.88.15.157",
                            "IPPrefixLen": 16,
                            "IPv6Gateway": "",
                            "GlobalIPv6Address": "",
                            "GlobalIPv6PrefixLen": 0,
                            "MacAddress": "0e:54:b1:5a:65:e9",
                            "NetworkID": "podman",
                            "DriverOpts": null,
                            "IPAMConfig": null,
                            "Links": null,
                            "Aliases": [ 
                                 "72a55a54fe5a"
                            ]
                       }
                  }
             },
             "Namespace": "",
             "IsInfra": false,
             "IsService": false,
             "KubeExitCodePropagation": "invalid",
             "lockNumber": 260,
             "Config": {
                  "Hostname": "72a55a54fe5a",
                  "Domainname": "",
                  "User": "",
                  "AttachStdin": false,
                  "AttachStdout": false, 
                  "AttachStderr": false, 
                  "Tty": false,
                  "OpenStdin": false,
                  "StdinOnce": false,
                  "Env": [
                       "container=podman",
                       "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                       "HOME=/root",
                       "HOSTNAME=72a55a54fe5a"
                  ],
                  "Cmd": [
                       "/bin/busybox-extras",
                       "httpd",
                       "-f",
                       "-p",
                       "80"
                  ],
                  "Image": "quay.io/libpod/testimage:20240123",
                  "Volumes": null,
                  "WorkingDir": "/var/www",
                  "Entrypoint": "",
                  "OnBuild": null,
                  "Labels": {
"created_at": "2024-01-24T18:38:28Z",
                       "created_by": "test/system/build-testimage",
                       "io.buildah.version": "1.34.1-dev"
                  },
                  "Annotations": {
                       "io.container.manager": "libpod",
                       "org.opencontainers.image.stopSignal": "15"
                  },
                  "StopSignal": 15,
                  "HealthcheckOnFailureAction": "none",
                  "CreateCommand": [
                       "/home/esm/src/atomic/2018-02.podman/libpod/bin/podman",
                       "run",
                       "-d",
                       "--name",
                       "myyaml",
                       "-p",
                       "5457:80",
                       "-v",
                       "/tmp/podman_bats.mmlLZN/test.yaml:/var/www/testpod.yaml:Z",
                       "-v",
                       "/tmp/podman_bats.mmlLZN/ready:/var/www/ready:Z",
                       "-w",
                       "/var/www",
                       "quay.io/libpod/testimage:20240123",
                       "/bin/busybox-extras",
                       "httpd",
                       "-f",
                       "-p",
                       "80"
                  ],
                  "Umask": "0022",
                  "Timeout": 0,
                  "StopTimeout": 10,
                  "Passwd": true,
                  "sdNotifyMode": "container"
             },
             "HostConfig": {
                  "Binds": [
                       "/tmp/podman_bats.mmlLZN/ready:/var/www/ready:rw,rprivate,nosuid,nodev,rbind",
                       "/tmp/podman_bats.mmlLZN/test.yaml:/var/www/testpod.yaml:rw,rprivate,nosuid,nodev,rbind"
                  ],
                  "CgroupManager": "systemd",
                  "CgroupMode": "private",
                  "ContainerIDFile": "", 
                  "LogConfig": {
                       "Type": "journald",
                       "Config": null,
                       "Path": "",
                       "Tag": "",
                       "Size": "0B"
                  },
"NetworkMode": "bridge",
                  "PortBindings": {
                       "80/tcp": [
                            {
                                 "HostIp": "",
                                 "HostPort": "5457"
                            }
                       ]
                  },
                  "RestartPolicy": {
                       "Name": "",
                       "MaximumRetryCount": 0
                  },
                  "AutoRemove": false,
                  "VolumeDriver": "",
                  "VolumesFrom": null,
                  "CapAdd": [],
                  "CapDrop": [],
                  "Dns": [],
                  "DnsOptions": [],
                  "DnsSearch": [],
                  "ExtraHosts": [],
                  "GroupAdd": [],
                  "IpcMode": "shareable",
                  "Cgroup": "",
                  "Cgroups": "default",
                  "Links": null,
                  "OomScoreAdj": 0,
                  "PidMode": "private",
                  "Privileged": false,
                  "PublishAllPorts": false,
                  "ReadonlyRootfs": false,
                  "SecurityOpt": [],
                  "Tmpfs": {},
                  "UTSMode": "private",
                  "UsernsMode": "",
                  "ShmSize": 65536000,
                  "Runtime": "oci",
                  "ConsoleSize": [
                       0,
                       0
                  ],
                  "Isolation": "",
                  "CpuShares": 0,
                  "Memory": 0,
                  "NanoCpus": 0,
                  "CgroupParent": "",
                  "BlkioWeight": 0,
                  "BlkioWeightDevice": null,
                  "BlkioDeviceReadBps": null,
                  "BlkioDeviceWriteBps": null,
                  "BlkioDeviceReadIOps": null,
                  "BlkioDeviceWriteIOps": null,
                  "CpuPeriod": 0,
                  "CpuQuota": 0,
"CpuRealtimePeriod": 0,
                  "CpuRealtimeRuntime": 0,
                  "CpusetCpus": "",
                  "CpusetMems": "",
                  "Devices": [],
                  "DiskQuota": 0,
                  "KernelMemory": 0,
                  "MemoryReservation": 0,
                  "MemorySwap": 0,
                  "MemorySwappiness": 0, 
                  "OomKillDisable": false,
                  "PidsLimit": 2048,
                  "Ulimits": [
                       {
                            "Name": "RLIMIT_NPROC",
                            "Soft": 4194304,
                            "Hard": 4194304
                       }
                  ],
                  "CpuCount": 0,
                  "CpuPercent": 0,
                  "IOMaximumIOps": 0,
                  "IOMaximumBandwidth": 0,
                  "CgroupConf": null
             }
        }
   ]

**Pull request closed without merging**
