### PR TITLE
Vastly improve secrets scanning & false-positives

### PR DESCRIPTION
**Pull request by cevich**
* **Fix new-pr secret-scan review URL JQ format**
  The `before` jq filter was using GHA context elements in it's filter
  (`.github.event`) that don't actually exist in the event JSON.  Removing
  them resulted in successful `jq` before/after commands when run against
  event JSON exported from a new-pr workflow.

* **Secret scanning: Move debugging block**
  Previously, it was possible for one of several steps to throw an error,
  leaving the operator with no debugging details.  Relocate the "important
  details" step earlier in the workflow to mitigate a risk of unavailable
  debugging info.

* **Wave secrets protections on select files/scripts**
  The baseline gitleaks data is unfortunately commit-locked, meaning small
  changes to files due to (for example) rebases, can render them useless.
  Manually go through all findings and where possible mark lines to be
  ignored directly.  In a few cases where secrets are used in tests, mark
  them to be ignored via a new `.gitleaksignore` file.  This will
  hopefully cut way down on the number of false-positive alerts that
  require review.

Note: I intentionally did not wave checks in the `.cirrus.yml` file as
it's currently going through a large number of changes.  I'll leave it
up to a future followup commit to mark known/approved secret references
in this file.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
Potential concern: someone could use .gitleaksignore to hide the fact that an actual leak was introduced. Maybe label PRs with changes to that file so they get extra attention?

**Comment by cevich** [comment]
> someone could use .gitleaksignore to hide the fact that an actual leak was introduced.

Yes, I anticipated this.  This [check runs from the `main` tree against the subject PR tree, checking specifically for what you describe](https://github.com/cevich/podman/blob/ae7a074e7affa65e108fca67d15a23dda484c2f7/.github/workflows/scan-secrets.yml#L168-L186).  In fact, it's why I had to add the `BypassLeakNotification` label, otherwise this PR would fire off the warning e-mails every time I push.

**Comment by cevich** [comment]
Case in point: The scanner for this PR will never ever go green. https://github.com/containers/podman/actions/runs/7834697427/job/21378478408?pr=21570#step:12:77

But once merged, if somebody merges into their PR, hopefully it shouldn't fire off so many damn false-positive alerts.

The other idea I had was to whitelist any PR authored by a maintainer.

If none of this works, and the false-positives continue.  I'll likely give up and yank the scanner - more trouble than it's maintenance-worth.

**Comment by cevich** [comment]
Leaving this as a draft until all the activity on `main` slows down, then I can rebase a final time.

**Comment by Luap99** [comment]
> The other idea I had was to whitelist any PR authored by a maintainer.

Yeah this is not an option IMO, having false positives for *any* contributor is not acceptable to me. For outside people who do not know the CI setup they get greeted with bogus errors they cannot understand and fix which is a frustrating experience, i.e. https://github.com/containers/podman/discussions/21492

**Comment by cevich** [comment]
Worse...AFAIK there isn't a good way in github actions to determine if an action is running on a fork or upstream.  At least without hard-coding it.  Maybe let's just get rid of this damn thing.  It's really intended to be run from a pre-commit anyway, so I guess it will be each maintainers responsibility to do that.

**Comment by cevich** [comment]
Opened https://github.com/containers/podman/pull/21588

**Pull request closed without merging**
