### PR TITLE
fix remote checkpoint/restore

### PR DESCRIPTION
**Pull request by vrothberg**
Nothing was working before, and it's too much to summarize.  To make
sure we're not regressing in the future again, enable the remote e2e
tests.

Fixes: #12007
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
but too much red in the tests still, unfortunately.

**Comment by mheon** [comment]
F34 and Ubuntu 21.10 root test failures look legitimate

**Comment by mheon** [comment]
You have merge conflicts

**Comment by vrothberg** [comment]
Ha, restore is broken as well -.-

**Comment by vrothberg** [comment]
The amount of work to get this fixed shocks me.

**Comment by vrothberg** [comment]
> Should we just drop support for remote checkpoint and restore. Not sure this should be a remote function.

It has been broken since the v2 rewrite.  The remote tests aren't yet exercised in CI, so we never noticed but I guess there are no users since there is no report.

But I almost got it working, so we can keep it I guess.

**Comment by vrothberg** [comment]
Tests passed on my machine :heavy_check_mark:

**Comment by rhatdan** [comment]
LGTM
@adrianreber PTAL

**Comment by vrothberg** [comment]
Note: once merged, we can close https://github.com/containers/podman/issues/12053.

**Comment by vrothberg** [comment]
@giuseppe PTAL

**Pull request merged**
