### PR TITLE
Bump VMs. New pasta, gvisor

### PR DESCRIPTION
**Pull request by edsantiago**
Need pasta 02-20, gvisor 0.7.3

https://github.com/containers/automation_images/pull/329#issuecomment-1959742060

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
Copy of the package diff table from the auto-images PR, for quick reference:

- 20240222t143004z-f39f38d13
- 20240201t143038z-f39f38d13 &#x21D1; (built in #325)

|  |*debian*|*prior-fedora*|*fedora*|*fedora-aws*|*rawhide*|
|----|----|----|----|----|----|
|*base*         | 13              | 38-1.6          | 39-1.5          | ?               | 41-0            |
|               |                |                |                |                | 40-0&nbsp;&#x21D1; |
|*kernel*       | 6.6.15-2        | 6.7.5-100       | 6.7.5-200       | 6.7.5-200       | 6.8.0-0.rc5.41  |
|               |                |                |                |                |                |
|*aardvark-dns* | 1.4.0-5         | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        | 1.10.0-1        |
|               |                | 1.9.0-1&nbsp;&#x21D1; |                | 1.9.0-1&nbsp;&#x21D1; |                |
|*netavark*     | 1.4.0-4         | 1.9.0-1         | 1.10.3-1        | 1.10.3-1        | 1.10.3-1        |
|               |                |                | 1.10.1-5&nbsp;&#x21D1; | 1.10.1-5&nbsp;&#x21D1; | 1.10.1-5&nbsp;&#x21D1; |
|*buildah*      | 1.33.5+ds1-4    | 1.34.0-1        | 1.34.0-1        | 1.34.0-1        | 1.34.0-4        |
|               | 1.33.3+ds1-2&nbsp;&#x21D1; | 1.33.2-1&nbsp;&#x21D1; |                |                | 1.34.0-3&nbsp;&#x21D1; |
|*conmon*       | 2.1.10+ds1-1    | 2.1.8-2         | 2.1.10-1        | 2.1.10-1        | 2.1.8-4         |
|               | 2.1.6+ds1-1&nbsp;&#x21D1; |                | 2.1.8-2&nbsp;&#x21D1; | 2.1.8-2&nbsp;&#x21D1; |                |
|*container-selinux*| ?               | 2.228.1-1       | 2.229.0-1       | 2.229.0-1       | 2.229.0-2       |
|               |                | 2.227.0-1&nbsp;&#x21D1; |                |                |                |
|*containers-common*| ?               | 1-89            | 1-99            | 1-99            | 0.57.3-3        |
|               |                |                | 1-95&nbsp;&#x21D1; | 1-95&nbsp;&#x21D1; | 0.57.1-7&nbsp;&#x21D1; |
|*criu*         | 3.17.1-3        | 3.18-1          | 3.19-2          | 3.19-2          | 3.19-4          |
|               |                |                |                |                |                |
|*crun*         | 1.14.1-1        | 1.14.3-1        | 1.14.3-1        | 1.14.3-1        | 1.14.3-1        |
|               | 1.14-1&nbsp;&#x21D1; | 1.12-1&nbsp;&#x21D1; | 1.14-1&nbsp;&#x21D1; | 1.14-1&nbsp;&#x21D1; | 1.14-1&nbsp;&#x21D1; |
|*golang*       | 2:1.21~3        | 1.20.14-1       | 1.21.7-1        | 1.21.7-1        | 1.22.0-1        |
|               | 2:1.21~2&nbsp;&#x21D1; | 1.20.13-1&nbsp;&#x21D1; | 1.21.6-1&nbsp;&#x21D1; | 1.21.6-1&nbsp;&#x21D1; | 1.22~rc2-1&nbsp;&#x21D1; |
|*gvisor-tap-vsock*| ?               | 0.7.3-1         | 0.7.3-1         | 0.7.3-1         | 0.7.3-2         |
|               |                | 0.7.1-1&nbsp;&#x21D1; | 0.7.2-1&nbsp;&#x21D1; | 0.7.2-1&nbsp;&#x21D1; | 0.7.2-2&nbsp;&#x21D1; |
|*passt*        | 2024-02-20      | 2024-02-20      | 2024-02-20      | 2024-02-20      | 2024-02-20      |
|               | 2023-12-30&nbsp;&#x21D1; | 2023-12-30&nbsp;&#x21D1; |                | 2023-12-30&nbsp;&#x21D1; | 2023-12-30&nbsp;&#x21D1; |
|*podman*       | 4.9.3+ds1-1     | 4.8.3-1         | 4.9.3-1         | 4.9.0-1         | 5.0.0~rc1-3     |
|               | 4.9.0+ds1-2&nbsp;&#x21D1; |                | 4.9.0-1&nbsp;&#x21D1; |                | 4.9.0-1&nbsp;&#x21D1; |
|*runc*         | 1.1.12+ds1-1    | 1.1.12-1        | 1.1.12-1        | 1.1.12-1        | 1.1.12-3        |
|               | 1.1.10+ds1-1&nbsp;&#x21D1; | 1.1.8-1&nbsp;&#x21D1; | 1.1.8-1&nbsp;&#x21D1; | 1.1.8-1&nbsp;&#x21D1; | 1.1.9-2&nbsp;&#x21D1; |
|*skopeo*       | 1.13.3+ds1-2    | 1.14.1-1        | 1.14.2-1        | 1.14.2-1        | 1.14.2-2        |
|               |                |                | 1.14.1-1&nbsp;&#x21D1; | 1.14.0-1&nbsp;&#x21D1; | 1.14.1-2&nbsp;&#x21D1; |
|*slirp4netns*  | 1.2.1-1         | 1.2.2-1         | 1.2.2-1         | 1.2.2-1         | 1.2.2-2         |
|               |                |                |                |                |                |
|*systemd*      | 255.3-2         | 253.15-2        | 254.9-1         | 254.9-1         | 255.3-1         |
|               |                |                |                |                |                |
|*tar*          | 1.34+dfsg-1.2+deb12u1 | 1.34-8          | 1.35-2          | 1.35-2          | 1.35-3          |
|               |                |                |                |                |                |

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
`sys` test is gonna die, the rawhide hang. I need to go into town for an hour. Could someone please restart it when it goes red? TIA

**Comment by Luap99** [comment]
> `sys` test is gonna die, the rawhide hang. I need to go into town for an hour. Could someone please restart it when it goes red? TIA

restarted

**Pull request merged**
