### PR TITLE
Initial quadlet version integrated in golang

### PR DESCRIPTION
**Pull request by alexlarsson**
Based on the initial port in https://github.com/containers/quadlet/pull/41

This should pass make lint, and has some initial tests (ported from the C unit tests).
Remaining work:
 * Convert the quadlet intergration tests
 * Add compilte time options (tags) for quadlet username, and fallback uid/gids
 * Actually install the generator in the right places
 * Documents the code a bit more
 * Actually test this live in the system

```release-note
Added new systemd-generator that can be used to easily write and maintain systemd services using podman (based on quadlet project).
```

### CODE REVIEW

**Comment by alexlarsson** [comment]
I installed via  `sudo cp bin/quadlet /usr/lib/systemd/system-generators/quadlet-system-generator` (after removing traditional quadlet), and my quadlets services seemed to work on reboot:
```
$ systemctl status quadlet-minimal
● quadlet-minimal.service - A minimal container
     Loaded: loaded (/etc/containers/systemd/quadlet-minimal.container; generated)
     Active: active (running) since Mon 2022-10-03 16:48:00 CEST; 16s ago
    Process: 7688 ExecStartPre=rm -f /run/quadlet-minimal.cid (code=exited, status=0/SUCCESS)
   Main PID: 7824 (conmon)
      Tasks: 3 (limit: 38377)
     Memory: 1.2M
        CPU: 271ms
     CGroup: /system.slice/quadlet-minimal.service
             ├─libpod-payload-b230b21be106d9337cf78e919368e4b714b0431a922177580af334917e519beb
             │ ├─ 7827 /run/podman-init -- sleep 60
             │ └─ 7872 sleep 60
             └─runtime
               └─ 7824 /usr/bin/conmon --api-version 1 -c b230b21be106d9337cf78e919368e4b714b0431a922177580af334917e519beb -u b230b21be106d9337cf78e919368e4b714b0431a922177580af334917e519beb -r /usr/bin/crun -b /var/lib/containers/storag>
```

**Comment by alexlarsson** [comment]
I looked at the time spent in generators in the `systemd-analyze plot` output, and there seems to be no real difference.

**Comment by alexlarsson** [comment]
Now with some more comments, config options and we install binaries in the right places.

This is probably a good starting point for initial merge.

**Comment by vrothberg** [comment]
Just returned from PTO.  I will have a look at this PR this week.  Currently, CI is red.

**Comment by alexlarsson** [comment]
Just a rebase on master to see if the vendoring issue still happens in ci

**Review by vrothberg — COMMENTED** [review]
LGTM.  We can do smaller improvements after the merge.

@alexlarsson, could you squash it into one single commit?

@containers/podman-maintainers PTAL

**Comment by alexlarsson** [comment]
Rebased

**Pull request merged**
