### PR TITLE
APIv2 compatibility rootless network fix

### PR DESCRIPTION
**Pull request by baude**
when using the compatibility mode as rootless, containers that were created were not setting their host names correctly due to the netmode not being set.

Fixes: #7934

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Can you add a test?

**Comment by baude** [comment]
> Can you add a test?

ewww .... i dont know if we test rootless calls directly.  @edsantiago any idea?

**Comment by edsantiago** [comment]
Uh-oh, looks like we lost `test/apiv2` in the Cirrus switchover:
```diff
-    apiv2_test_script: '$SCRIPT_BASE/apiv2_test.sh |& ${TIMESTAMP} | ${LOGFORMAT} apiv2_test'
```
@cevich is that easy for you to fix? Maybe add it into one of the local tests?

Anyhow, once that's resolved, this could be tested via code in `test/apiv2`.

**Comment by jwhonce** [comment]
Fix LGTM, now for tests and CI updates...

**Comment by baude** [comment]
the missing test run directly impacts this.  @edsantiago would you feel ok about merging this and adding the test when we have that test suite running again?

**Pull request merged**
