### PR TITLE
Bump to v4.2.0-rc3

### PR DESCRIPTION
**Pull request by lsm5**
#### Does this PR introduce a user-facing change?

```release-note
None
```

Depends on https://github.com/containers/podman/pull/15201 

@TomSweeneyRedHat @rhatdan @baude @ashley-cui @vrothberg PTAL
/cc @containers/podman-maintainers

### CODE REVIEW

**Comment by ashley-cui** [comment]
Did we want to get this in before? https://github.com/containers/podman/pull/15194

**Comment by lsm5** [comment]
> Did we want to get this in before? #15194

@baude @TomSweeneyRedHat @rhatdan wdyt?

**Comment by ashley-cui** [comment]
I believe the folks who worked on it wanted it in so we could test the packaged version of the pkginstaller in 4.2_RC3

cc @gbraad @anjannath @benoitf

**Comment by lsm5** [comment]
woah `build each commit` reports a ridiculous binary size increase

**Comment by TomSweeneyRedHat** [comment]
@lsm5 yeah, cosign bits are a bit plump.  Since you gotta respin, could you grab  https://github.com/containers/podman/pull/15194 too please?

**Comment by TomSweeneyRedHat** [comment]
Good call on the bloat label @lsm5

**Comment by lsm5** [comment]
@TomSweeneyRedHat release notes PR is good to go https://github.com/containers/podman/pull/15201

**Comment by eriksjolund** [comment]
This is not in the PR but there is a typo in the release notes
`--build-contaxt`

**Comment by lsm5** [comment]
> This is not in the PR but there is a typo in the release notes `--build-contaxt`

fixed in the release notes PR https://github.com/containers/podman/pull/15201

**Comment by eriksjolund** [comment]
@lsm5 Thanks, I missed that.

**Comment by ashley-cui** [comment]
LGTM

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Comment by lsm5** [comment]
@ashley-cui @vrothberg needs approve label too

**Comment by lsm5** [comment]
something weird going on the approve label.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
