### PR TITLE
Fix sed regex to update version in version/version.go

### PR DESCRIPTION
**Pull request by jwhonce**
Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
But someone more familiar with sed should take a look - maybe @edsantiago

**Comment by edsantiago** [comment]
parentheses in sed give me a headache too. But, LGTM: I tried it on my command-line, manually setting LOCAL_VERSION, and it produces what I think is the desired effect.

**Pull request merged**
