### PR TITLE
e2e: Avoid hard-coding included in quadlet test

### PR DESCRIPTION
**Pull request by sstosh**
Use `.*/podman_test.*...` instead of `/tmp/podman_test.*...`

Signed-off-by: Toshiki Sonoda <sonoda.toshiki@fujitsu.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM, thanks!

@ygalblum @alexlarsson PTAL

**Review by ygalblum — CHANGES_REQUESTED** [review]
The issue this PR fixes is already addressed in other test cases such as `configmap.kube`. I guess I just missed it in the first test (i.e. `kube.basic`).
I don't think we want to have to write the files in runtime. So, the fix here should be changing `basic.kube` file to not check `/tmp` and instead check `.*/podman_test.*/quadlet/deployment.yml`

**Comment by sstosh** [comment]
> So, the fix here should be changing basic.kube file to not check /tmp and instead check .*/podman_test.*/quadlet/deployment.yml
Thank you for your reply.
I verified `.*/podman_test.*...` succeeds.
I fixed and force pushed.

**Review by ygalblum — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
